### ISSUE TITLE
create_test --force-procs and --force-threads options should change test name

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1017]
I see the convenience of the `--force-procs` and `--force-threads` options added to create_test in #1016 (addressing #897 ). However, for the sake of baseline generation and comparison, as well as tracking the history of passing / failing tests, I feel that it is a Bad Idea to allow changing test configuration without noting this in the test name.

Currently, you could run:

```
./create_test --force-procs 64 SMS.f45_g37.A.yellowstone_intel --generate foo
```

then later run

```
./create_test SMS.f45_g37.A.yellowstone_intel --compare foo
```

If there were differences due to the different PE layout (which is expected for some compsets, unexpected but possible due to bugs for others), then it would be very confusing to try to track down the cause of these differences.

I would suggest that specifying `--force-procs` or `--force-threads` modifies all of the test names to note this modification, by adding `_PNxM` to the test name - unless the test already has a `_PNxM` modifier, in which case it appears that that modifier currently takes precedence over the `--force` option. (I don't think we have a current naming convention for `--force-threads` without `--force-procs`, but we could use something like `PxM`.)

Tagging @jgfouca @jedwards4b

**Comment by jedwards4b** [comment]
Perhaps you should think of these as an extension for acme, not intended for cesm use.   Because of our use of testlist (acme does not partake) we can easily change pe-layout in a single test.   You are correct that using these in the cesm testing system will lead to namelist differences and test failures that may be difficult to track down - so my recommendation is don't use them.

**Comment by billsacks** [comment]
In that case, would it make sense to add a note in the documentation that these options should NOT be used in CESM, at least not if you're doing --compare or --generate? Or should these be put in the section of ACME-specific options in create_test, to avoid confusing CESM users?

**Comment by jedwards4b** [comment]
I think that modifying the MxN in the test name is a possibility @jgfouca ?

**Comment by jgfouca** [comment]
@jedwards4b maybe, we'd have to ask @amametjanov more about the use case that led him to file the original request for this feature.

**Comment by jgfouca** [comment]
@billsacks one thing we could do is to prevent baseline operations when these --force flags are used.

**Comment by jgfouca** [comment]
Another thing we could do is to dynamically rename the tests based on these options.

**Comment by jgfouca** [comment]
Sorry for the spam; yet another thing that may be good is restricting these options to the "acme" model.

**Comment by amametjanov** [comment]
@jgfouca, that was needed for running all tests on Cetus with 64x16 PEs. Cetus does not allow more than 1024 node-hours per person at a time. Acme_developer has 38 tests: 38 tests x 16 nodes/test = 608 nodes to concurrently run all 38 tests.

**Comment by billsacks** [comment]
@jgfouca - I am happy with any of the options you mention: preventing baseline operations, dynamically renaming the tests, or restricting these options to the acme model.

**Comment by jgfouca** [comment]
@amametjanov would you be opposed to dynamically re-naming the tests? For example:
./create_test --force-procs=16 SMS.ne4_ne4.A
... * renames test to SMS_P16.ne4_ne4.A *

**Comment by amametjanov** [comment]
No, I guess we'll just have to create baselines with the new test names, when needed. Any comments @jayeshkrishna?

**Comment by jgfouca** [comment]
If you're using the results for baseline testing, then I strongly recommend we go in this direction due to the issues that @billsacks raised.

**Comment by amametjanov** [comment]
Yes, agreed.

**Comment by jayeshkrishna** [comment]
I agree with the option of renaming the test.
