### ISSUE TITLE
check_input_data not supporting input files outside of input data repo

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1019]
@erichlf has asked for support for the following use case:
* Create a partition file in his home directory
* Point namelist files to use this partition file
* check_input_data should find this file but it doesn't because it insists on looking in the input data repo

**Comment by jedwards4b** [comment]
By what mechanism is he doing step 2?  It should be through user_nl files.

**Comment by erichlf** [comment]
In user_nl_mpas{o,cice} I set 
config_block_decomp_file_prefix
which results in the proper variable being set in BuildConf/mpas-{o,cice}conf/mpas-{o,cice}_in. However, the graph24 variable is not correct in BuildConf/mpas-{o,cice}.input_data_list.
As a work-around I can do a ./case_setup and then set graph24 manually.

**Comment by jedwards4b** [comment]
@erichlf okay - I would expect this to work - are you setting a fully qualified path or a relative path?

**Comment by rljacob** [comment]
I suspect the mpas buildnml scripts in the cime_config dir.

**Comment by erichlf** [comment]
I set the full path.

**Comment by jgfouca** [comment]
@erichlf I just tested this by hand. If you manually add a file to the $model.input_data_list, it works fine (uses the path you provided).

If you set the full path in user_nl_*, you do get some odd behavior that I will fix.
