### ISSUE TITLE
With the exception of for testing, have preview_namelist die with an error on a contradiction

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1021]
Currently if a namelist item is given twice in user_nl_* and is contradictory the later one will be used. We want to keep this behavior for testing. But, we'd like to have preview_namelist die with a error on a contradiction outside of testing.

So for example if you have

foo=1
foo=2

in a user_nl_* it would die with error and say that the setting of "foo" is contradictory.

@mvertens please assign as appropriate

**Comment by rljacob** [comment]
Why do you want to keep the "use last" behavior for testing?

**Comment by jedwards4b** [comment]
Because it's part of the mechanism of testmods to allow redefinition of the same setting.

**Comment by jgfouca** [comment]
@mvertens apologies for assigning myself. I misread this ticket thinking it dealt with my code in compare_namelists.py, but it actually impacts the core namelist readers which I believe are in fortran.

**Comment by mvertens** [comment]
Thank you so much for taking this on!!!

**Comment by mvertens** [comment]
Never mind - I now misread your email. Thanks for the clarification.

**Comment by billsacks** [comment]
I'm removing this from the cesm2 milestone, because other things seem higher priority. If others disagree, feel free to re-add it to that milestone.

**Comment by jgfouca** [comment]
On today's cime telecon, we decided that overrides are a legitimate usecase.
