### ISSUE TITLE
Documentation file name convention

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1026]
When the existing UG content was moved to the wiki, a file-name convention was adopted with the section numbers in the filename:

For example from cime.wiki/CIME-Users-Guide/source (after "git clone git@github.com:ESMCI/cime.wiki.git"):
```
CUG-2.0-Creating-and-Setting-Up-a-Case.rest
CUG-2.1-How-to-create-a-new-case.rest
CUG-2.2-How-to-set-up-a-case-and-customize-the-PE-layout.rest
CUG-2.3-Multi-instance-component-functionality.rest
CUG-2.4-Modifying-an-xml-file.res
```
CUG = Cime Users Guide.

I don't think we need all of those prefixes.

The UG files are already in a separate directory which provides separation from the Developers Guide and other guides.  So we don't need the "CUG" prefix.   

Adding the section number means the file has to be renamed when moving around content.  There's not that many files that they need to be numbered with names.

Finally, the wiki uses the file name for the page title.  The dashes are converted to spaces.  See for example:  https://github.com/ESMCI/cime/wiki/CUG-2.0-Creating-and-Setting-Up-a-Case.

So if there's no objections, I'll remove "CUG" and the section number from the filenames.

**Comment by rljacob** [comment]
There's a similar convention in the Coupler Users Guide and Data Models Users Guide

**Comment by mvertens** [comment]
Sounds good. Thanks!

**Comment by rljacob** [comment]
After further reading, may want to keep the section numbers.  Not sure how it looks in the wiki vs. the Sphinx-processed document.

@gold2718 , can you try taking the current CIME Users Guide content and updating http://esmci.github.io/cime/

**Comment by jgfouca** [comment]
We don't want section numbers in the wiki.

**Comment by rljacob** [comment]
Decision on telecon:  we will remove section numbers from file names as well.
