### ISSUE TITLE
PROJECT setting in CIME5 (question)

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1027]
For reasons I can't remember any more, I had $PROJECT set to a default (now defunct) project in my .tcshrc at the ALCF. With CIME2, the project specified in the ./create_newcase command took precedence over this. With CIME5, this has been reversed - what is set in my environment is what is used in /case.setup, not what is set by the ./create_newcase.

So, this is new behavior. My first question is whether it was intentional. I vaguely remember having a discussion on this topic, pre-CIME and with Bill Sacks in the original introduction of the PROJECT logic into ACME and CESM, and voting for the behavior that was in CIME2. If it was changed intentionally, I'd like to understand the reasoning behind it. If not intentional, I'd like it changed back.

This is a duplicate of a ticket filed by @worleyph on the ACME side.

**Comment by jedwards4b** [comment]
I think that we discussed order of precedence for this variable and it's documented in 
CIME/utils.py line 529:
```

**Comment by jedwards4b** [comment]
But if you are specifying the command line option that should be preferred.  If that's not happening anymore it's unintentional.

**Comment by jgfouca** [comment]
It appears to work fine in current CIME-5.2.
