### ISSUE TITLE
Looking for sources of CPPDEFs

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1029]
When MCT is being built, these are the CPPDEFs:  (from blues, gnu, latest ESMCI master, A case)

`-DLINUX -DCPRGNU -DNDEBUG -DMCT_INTERFACE -DHAVE_MPI  -DFORTRANUNDERSCORE -DNO_R16 -DHAVE_SLASHPROC -DSYSLINUX -DCPR`

I can find some, but not all  of them.

-DFORTRANUNDERSCORE -DNO_R16:  from gnu compiler entry in config_compilers.xml
-DNDEBUG -DMCT_INTERFACE -DHAVE_MPI -DHAVE_SLASHPROC:  from Makefile in machines dir

Can't find where these come from:
-DLINUX -DCPRGNU -DSYSLINUX -DCPR

Anyone know?

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
cime_config/acme/machines/Makefile:CPPDEFS := $(USER_CPPDEFS) -D$(OS) -DCPR$(shell echo $(COMPILER) | tr a-z A-z)

**Comment by jedwards4b** [comment]
externals/mct/configure:CPPDEFS="$CPPDEFS -DSYS$SYSDEF -DCPR$CPRDEF"

**Comment by jedwards4b** [comment]
So the first two are added in Makefile and the second two are added by mct's configure

**Comment by rljacob** [comment]
Thanks!  I'll have to figure out why "-DCPR$CPRDEF" is resolving to just "-DCPR".
