### ISSUE TITLE
Rewrite system tests in python

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#103]
From the old google doc:

1. Create a utils/python/CIME/SystemTests directory, test types will each be represented by a Class in this directory
2. write a template.case.test in python that runs the selected test  (partially done)
3. case.test_build (all tests are now currently built with python, but the test scripts themselves are still csh)
4. move csh test scripts to python
5. Have tests output to teststatus.xml file in each case directory replacing the current TestStatus file
6. Have cs_status collect these teststatus.xml files into a report to cdash or the cesm testdb

**Comment by jedwards4b** [comment]
I have a branch in https://github.com/jedwards4b/cime/tree/systemtestsrefactor

**Comment by rljacob** [comment]
All CIME developer tests are done.
