### ISSUE TITLE
Python implementation of CPRNC

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1031]
Reimplement CPRNC in Python
See https://github.com/mfdeakin-sandia/cprnc_python

**Comment by billsacks** [comment]
Here was a discussion between myself and @mfdeakin-sandia from Sept., 2017:

From me:

> Can you remind me where things stand with the python version of cprnc? I'm not in any rush for it, but I'm just trying to remember what conclusions there were, if any, before this work got put on the back burner. Actually, my main motivations here are thinking about some other desired uses of netcdf within cime's python scripting.
> 
> From re-reading the last few emails in this thread (which is the most recent set of conversations I can find), and also skimming through https://github.com/Unidata/netcdf4-python/issues/640, my impressions/recollections are:
> 
> (1) We decided to ditch scipy's netcdf (or only support it as a fallback option) because it doesn't support netcdf4
> 
> (2) We decided that it's acceptable to require an installation of netcdf4-python
> 
> (3) You ran into some multi-threading issues with netcdf4-python, but it sounds like you found a workaround?
> 
> Some questions:
> 
> • Is that all correct?
> 
> • Moving forward, for this or other applications, will netcdf4-python be a reasonable solution?
> 
> • Do we have a viable path forward for cprnc-python once someone gets time to work on it, or did we decide to ditch it?

From @mfdeakin-sandia 

> Yes, that all sounds like what I remember.
> 
> I think I had it mostly working with my workaround for the netcdf4 multithreading issues, but the change was huge so I was worried about it breaking some untested things, and never got around to finishing the extra testing/implementing more test cases. I'm sorry to say I probably won't get back to this for a while, but am planning on doing so before the ACME release.

However, neither @mfdeakin-sandia nor I have had time to work more on this since then.

**Comment by billsacks** [comment]
See also #2457 and particularly my comment: https://github.com/ESMCI/cime/issues/2457#issuecomment-386106331

**Comment by billsacks** [comment]
I doubt this is going to happen (anytime soon, at least), so I'm closing this.

**Comment by rljacob** [comment]
I think we found it was to slow to be useful.

**Comment by billsacks** [comment]
My recollection is that we could get acceptable performance if we were careful with how the code was written (using vector operations instead of explicit loops), but it took extra work to do that. Performance was still worse than the Fortran version though, and it introduced dependencies on python netcdf libraries. The biggest motivation was wanting the cprnc version to be more closely tied to the cime version, and that was accomplished (at least somewhat) with #2457 , so there are no longer enough benefits of this to justify the downsides.
