### ISSUE TITLE
Makefile directive undefine not available on anlworkstation

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#1033]
The gmake utility (GNU Make 3.81) available on compute001 does not
support the undefine directive. A build on compute001 fails with the following
error message,
```
/sandbox/jayesh/ESMCI_cime/scripts/test_mpi_serial4/Tools/Makefile:228: *** missing separator.  Stop.
if ( 0 == 1 ) then
cp -p Makefile.conf Makefile.conf.old
cp: cannot stat ‘Makefile.conf’: No such file or directory
make SRCDIR=/sandbox/jayesh/ESMCI_cime/externals/mct
Makefile:3: Makefile.conf: No such file or directory
make: *** No rule to make target `Makefile.conf'.  Stop.
exit 1
```
The undefine directive is supported on newer versions of gmake.
The undefine directive was added to cime_config/acme_machines/Makefile in 3dbe9591951f63b17469a2a00f6dbbe1f09dc302

**Comment by jayeshkrishna** [comment]
Does unexport do the same thing as undefine? unexport is supported by gmake on compute001.

**Comment by jayeshkrishna** [comment]
@jedwards4b : Any ideas?

**Comment by jedwards4b** [comment]
The error that you are getting usually indicates space where a tab is expected at line 228 of Makefile

**Comment by jayeshkrishna** [comment]
gnu make 3.82 NEWS file says "undefine" is a new directive. The version of make in compute001 is 3.81 .

**Comment by jayeshkrishna** [comment]
gnu make 3.63 introduced export/unexport

**Comment by jayeshkrishna** [comment]
@jedwards4b : Would unexport (instead of undefine) do the trick here ? Or do we want every machine to have a newer version of gmake (>= 3.82)?

**Comment by jedwards4b** [comment]
I think that it might - but I'm not sure I understand the difference between the two.   In any case you can test this by setting PNETCDF_PATH in your environment and then doing a mpi-serial build.

**Comment by jayeshkrishna** [comment]
Thanks, me neither (export/unexport define/undefine go in pairs maybe?). I will try setting PNETCDF_PATH and testing it with an mpi-serial build.

**Comment by jayeshkrishna** [comment]
The fix in the branch above only uses undefine if PNETCDF_PATH is defined. And at least on the acme machines (that use make 3.81) we don't define it (load modules) when building with mpi-serial.

**Comment by jayeshkrishna** [comment]
To recreate this issue,
* Create an X case (./create_newcase -case test_unexport2 -compset X -res f19_g16 -mpilib mpi-serial)
* Run ./case_setup
* Explicitly define PNETCDF_PATH, PNETCDFROOT in Macros file
* Run ./case_build
