### ISSUE TITLE
Extend generation of default PE configurations with MAX_TASKS_PER_NODE

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1037]
@jedwards4b , @amametjanov asked this question on the ACME side. I thought you might understand what he's asking for better than I do:

Compset-, grid- and machine-specific PE configurations can be specified in cime/machines-acme/config_pes.xml. Currently supported xml tags (ntasks, nthrds, rootpe) do not include max_tasks_per_node, which is set from machine-specific configurations in cime/machines-acme/config_machines.xml. New compsets such as -compset A_WCYCL2000 -res ne30_oEC require undersubscribing nodes on some machines to avoid running out-of-memory. This can only be done from a case directory now.

Default PE configurations need to be extended with max_tasks_per_node for the entire coupled model, or max_tpn_$comp per component. The latter is preferred to undersubscribe specific memory-heavy components such as ATM.

**Comment by jgfouca** [comment]
This is to fix a problem reported by @worleyph on the ACME side.

**Comment by jgfouca** [comment]
@amametjanov , @jedwards4b says this is already possible in the config_pes. Line 1450 of cesm all active pes file for an example.

**Comment by amametjanov** [comment]
Ok thanks. Is there support for shell commands: e.g.
```
<command>$SHELL{xmlchange -id OMP_STACKSIZE -val 32M}</command>
```
to set up other case variables for machine+grid+compset matches?

**Comment by rljacob** [comment]
You want OMP_STACKSIZE to be dependent on gird+compset for a machine?

**Comment by jedwards4b** [comment]
@amametjanov Perhaps if you gave a realistic example I could understand what you want to do - OMP_STACKSIZE is not something you can pass to xmlchange.

**Comment by amametjanov** [comment]
Yes, for some grids and PE layouts on Mira I can avoid out-of-memory errors by lowering OMP_STACKSIZE from default of 64M to 32M. Changing the default to 32M leads to errors in other cases/tests. So it needs to be specific to a PE layout.

In ACME-CIME, `xmlchange -id OMP_STACKSIZE -val 32M` produces error `ERROR: Unknown type 'None'`. And it looks like in ESMCI-CIME that's not a valid xmlchange command either. 

OMP_STACKSIZE is an XML variable in env_mach_specific.xml and should be modifiable through some tool: there was a discussion a while back that editing XML files directly is not supported.

**Comment by jedwards4b** [comment]
OMP_STACKSIZE is *not* an xml variable.   It is a setting in the environment section of the xml in that file - 
```
 <environment_variables>
      <env name="OMP_STACKSIZE">64M</env>
    </environment_variables>
```
Unfortunately there is not yet an interface in xmlchange to modify this field.   What you want to do is not available at this time.

**Comment by rljacob** [comment]
Should a new issue be made to add that capability?

**Comment by jedwards4b** [comment]
Yes - but it should be more general - there are some fields in the env_*xml files that xmlchange and xmlquery cannot yet read and modify.
