### ISSUE TITLE
request for standardized return status codes reported in CaseStatus

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1038]
It would be helpful if the return status codes for each reported operation in CaseStatus
conformed to an agreed upon nomenclature. 

For example,  we could use the following return status codes in a dictionary:

id   code              description
0    Succeeded   process successfully completed
1     Pending        process not yet started
2    Started          process has started            
3    Shutdown     process was shutdown           
4    Error              process error

And then each process that writes to CaseStatus could use the following message
template:

_status_dict = {
0 : 'Succeeded',
1 : 'Pending',
2 : 'Started',
3 : 'Shutdown',
4 : 'Error'
}
from string import Template
_status_template = Template($process: status id = $id; status code = _status_dict[$id])

msg = _status_template.substitute(process='case.run', id=$returncode)

The global variables, _status_dict and _status_template, could reside in the case.py class or
as a separate import file.

**Comment by jedwards4b** [comment]
I think that we already do this to some extent - statuses are defined in CIME/test_status.py.   What problem is it you are trying to solve?

**Comment by bertinia** [comment]
In archive_metadata, I need to report back to the expdb what the current status is of the case.
I'm currently parsing the CaseStatus file looking for the following strings:

# status strings to search for in CaseStatus                                                                                                                      
_run_msgs = ['Model did not complete','Run started','Run FAILED','Run SUCCESSFUL'];
_sta_msgs = ['st_archiving starting','st_archiving completed']
_lta_msgs = ['lt_archive starting','lt_archive completed']

And then translating those strings into corresponding lookup values in the database.
It would be nice to be able to search and parse a single format for status information.

**Comment by jedwards4b** [comment]
thanks for the clarification.   This should be easy to do since all updates to the CaseStatus file go through the append_status routine in CIME/utils.py
