### ISSUE TITLE
Support some interface to the shell in our XML

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1040]
Users like @amametjanov are asking for access to the shell within our XML files. Something like:

```
<env name="NETCDF_PATH">$SHELL{which nc-config | xargs dirname | xargs dirname}</env>
```

**Comment by ndkeen** [comment]
I would also appreciate this power

**Comment by rljacob** [comment]
A new package manager called "Spack" uses hashes in the path names leading to things like this:  <env name="NETCDFROOT">/soft/spack/opt/spack/linux-centos6-x86_64/intel-16.0.3/netcdf-4.4.0-ds5gqquzjytf4efz3d5njsvpkfmmrwq7</env>

Spack is used by Blues and probably coming soon to a cluster near you.  Easier to just use nc-config.

**Comment by rljacob** [comment]
https://spack.io/
