### ISSUE TITLE
Z_FullSystemTest failing on batch systems 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1041]
http://my.cdash.org/index.php?project=CIME 
All tests pass when run outside of the scripts_regression_tests.py and when run with no-batch.

**Comment by jgfouca** [comment]
There's some interaction between re-running the ERS/ERR tests on a batch system. I'm looking at it now.

**Comment by jedwards4b** [comment]
Just to clarify - it's not rerunning yet - they are failing on the first pass.

**Comment by jgfouca** [comment]
Pretty sure that's not true. I'm looking at the output for the ERS fail and it clearly does a round of base->rest comparisons before it fails.
