### ISSUE TITLE
case.build --cleanall does not clean all the mod files

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1045]
when --cleanall (and I assume --clean) is called from case.build, there are some .mod files left around.  I assume these are copies or something.  for instance, I see .mod files in

bld/intel/mpich2/nodebug/nothreads/include
bld/lib/include
bld/intel/mpich2/nodebug/nothreads/*/*/c1a1l1i1o1r1g1w1e1/include

Just wanted to point that out in case there is something more that clean should do.

**Comment by jedwards4b** [comment]
I don't think there is any negative issue associated with these .mod files if you see one please tell us.

**Comment by mvertens** [comment]
I am wondering why these are left around after a cleanall command? If there
is no reason for them to be there, I think we should remove them. Is there
a reason for them not to be cleaned?

**Comment by jedwards4b** [comment]
It's a little harder than it may appear - copies of .h and .mod files are copied from the individual bld obj directories to the general include directory.   The clean command cleans the object directory but it doesn't know how to selectively clean the include directory (it would need to identify only the mod files that originated in the directory you are requesting to clean)

**Comment by apcraig** [comment]
Maybe cleanall should just remove the bld directory completely and clean can leave behind the extra copies of the mod files.  That's just a suggestion.  Most users will probably use cleanall.  I suspect clean is only going to be used by experts that have an idea how the underlying build works and in that case, leaving the extra copies of the mod files seems ok.

**Comment by jedwards4b** [comment]
Actually clean with no arguments cleans all the prognostic model obj directories and cleanall also cleans the support libraries (pio, mct, csm_share) - mostly you don't need to clean those and clean is sufficient for most users.

**Comment by gold2718** [comment]
@jedwards4b, I think you made @apcraig's point. There is already not much left after `--cleanall` but sometimes it is enough to mess up the rebuild. I always have had to remove the bld directory anyway and removing it does not cost much (if any) time on the rebuild so I second the motion that `--cleanall` removes the bld directory.

**Comment by jedwards4b** [comment]
@gold2718 said " I always have had to remove the bld directory "  what?  why?  If there is a real reproducible problem I want to fix it.   Can any of you come up with a test case that indicates that the current tools are not sufficient, or is this an alternative truth?

**Comment by mvertens** [comment]
Is there a reason to not remove the bld directory? If this is cleaner it
should be done this way. I have also had problems in the past that required
me to remove the bld directory - but I don't remember the exact details. I
can't understand why we would argue about a cleaner implementation if there
is one that is simple to do.

**Comment by rljacob** [comment]
An option called "--cleanall" should clean **all**.

**Comment by apcraig** [comment]
Just adding a link to #1052 as the sharedlibroot is something that I wasn't entirely aware of before today, especially with regard to individual tests, and it may need to be considered in terms of how clean or cleanall work when using a test to carry out development.
