### ISSUE TITLE
Update to python 3.0 compliance 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1047]
End of life for python 2.7 is 2020.   What needs to be done to update cime to python 3?

**Comment by jgfouca** [comment]
Python has a 2_to_3 script that should take care of most of it. It would be a matter of running the script, pylinting the result, and running our tests. Hopefully it would mostly just work.

**Comment by rljacob** [comment]
Sounds good but lets not make this a priority.  2020 is a while from now and 2.7 won't disappear over night.

**Comment by mvertens** [comment]
I agree with Rob's plan.

**Comment by jgfouca** [comment]
Yes, and even then, 2.7 will never disappear. They just won't release any further updates to it.

**Comment by mfdeakin-sandia** [comment]
For the future, as a Python 3 evangelist, I would like to work on this
