### ISSUE TITLE
Duplicate grid in cesm/config_grids.xml?

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1049]
The grid, ne30_f09_g16, in cesm/config_grids.xml seems to have a duplicate. Is this okay? On purpose? Glitch? Sign of the apocalypse?

**Comment by jedwards4b** [comment]
Should not be two of them, I didn't think we were supporting tri-grid anymore - do we even need one?

**Comment by gold2718** [comment]
No idea, please assign to someone who knows the answer to that.

**Comment by mvertens** [comment]
We are definitely still supporting trigrid as a possible option.
