### ISSUE TITLE
Merging with ACME cime5.1

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1050]
I'm in the process of bringing in ACME's version of cime5.1 and would like comments on the plan for reconciling the two versions.

The maint-5.1 branch has 2 new tags on it.  cime5.1.4 is what was merged to ACME,  cime5.1.5 is the head of maint-5.1.

The plan:
1.  Merge ACME's 5.1 cime to the head of the ESMCI maint-5.1 branch. (should be easy)
2. Merge the maint-5.1 branch to master (will have tons of conflicts)
3. Once 2 is resolved, update the subtree in ACME/cime with lastest master from ESMCI/cime.
4. After this, all new cime development needed for ACME should start in ESMCI/cime and flow down.

**Comment by rljacob** [comment]
My memory is failing me but there was a recent PR on ESMCI that I was concerned would make it harder to update ACME because its a big change from 5.1.  I think it was the changes to all the model's buildnml files?

**Comment by jedwards4b** [comment]
That was intended to be backward compatible - I think that the current files will still work, but refactoring will give a significant performance improvement.

**Comment by jedwards4b** [comment]
Step 2 will probably not be an automatic process.   Is it possible to break it into several PR's?

**Comment by mvertens** [comment]
The change that came in which you are referring to only effected prognostic
components that used the new nmlgen capability in CIME. I do not think that
any ACME components have done that yet - so it should not effect you. I
have been making a definite effort to make sure that all changes that go
into CIME do not effect ACME. In addition having the new
config_component_acme.xml and config_component_cesm.xml that are in
driver_cpl/cime_config should help keep this separation as we move
forwards. I'm not sure you will get that in cime5.1.

We should discuss more of this in tomorrow's call.

**Comment by rljacob** [comment]
Re: separate PRs.  I don't know.  I'm using "subtree split" to put all of ACME's cime changes since Nov 14th on a branch.  The way to break it up would be to maybe do one month's worth of changes at a time.  @gold2718, can subtree split do that?

**Comment by rljacob** [comment]
Or maybe you could cherry pick off that branch, or the resulting merged maint-5.1, and make separate PRs?

**Comment by rljacob** [comment]
I locally finished the merge in PR #1063  and then tried to locally merge maint-cime5.1 to master.  Its not too bad!  Git notes conflicts with these files.  "us" = latest ESMCI cime, "them" = ACME's cime 5.1

	both modified:   cime_config/acme/allactive/config_pes.xml
	both modified:   cime_config/acme/allactive/config_pesall.xml
	added by us:     cime_config/acme/allactive/testmods_dirs/cam/outfrq9s/shell_commands
	both deleted:    cime_config/acme/allactive/testmods_dirs/cam/outfrq9s/xmlchange_cmnds
	added by us:     cime_config/acme/allactive/testmods_dirs/force_netcdf_pio/shell_commands
	both deleted:    cime_config/acme/allactive/testmods_dirs/force_netcdf_pio/xmlchange_cmnds
	both modified:   cime_config/acme/config_grids.xml
	both modified:   cime_config/acme/machines/Makefile
	both modified:   cime_config/acme/machines/config_batch.xml
	deleted by us:   cime_config/acme/machines/config_build.xml
	both modified:   cime_config/acme/machines/config_compilers.xml
	both modified:   cime_config/acme/machines/config_machines.xml
	added by them:   cime_config/acme/testmods_dirs/allactive/cam/outfrq9s/xmlchange_cmnds
	added by them:   cime_config/acme/testmods_dirs/allactive/force_netcdf_pio/xmlchange_cmnds
	both modified:   cime_config/cesm/machines/config_batch.xml
	both modified:   components/data_comps/datm/cime_config/config_component.xml
	both modified:   components/data_comps/dlnd/cime_config/config_component.xml
	deleted by us:   driver_cpl/bld/build-namelist
	both modified:   driver_cpl/bld/namelist_files/namelist_defaults_drv.xml
	both modified:   driver_cpl/bld/namelist_files/namelist_definition_drv.xml
	both modified:   driver_cpl/cime_config/buildnml
	both modified:   driver_cpl/cime_config/config_component.xml
	deleted by us:   scripts/Tools/taskmaker
	both modified:   utils/python/CIME/SystemTests/homme.py
	both modified:   utils/python/CIME/XML/env_batch.py
	both modified:   utils/python/CIME/XML/machines.py
	both modified:   utils/python/CIME/XML/pes.py
	both modified:   utils/python/CIME/bless_test_results.py
	both modified:   utils/python/CIME/build.py
	both modified:   utils/python/CIME/case.py
	both modified:   utils/python/CIME/compare_test_results.py
	both modified:   utils/python/CIME/provenance.py
	deleted by us:   utils/python/CIME/task_maker.py
	both modified:   utils/python/CIME/test_scheduler.py
	both modified:   utils/python/CIME/utils.py

**Comment by rljacob** [comment]
I wonder if we should first merge maint-cime5.1 to a branch off of master?  Then conflicts can be resolved, everyone can look at those and the branch can be tested.

**Comment by jgfouca** [comment]
@rljacob good idea

**Comment by jgfouca** [comment]
@rljacob I'll play with it.

**Comment by mvertens** [comment]
I am happy to help merge the following:

both modified:   components/data_comps/datm/cime_config/config_component.xml
both modified:   components/data_comps/dlnd/cime_config/config_component.xml
deleted by us:   driver_cpl/bld/build-namelist
both modified:   driver_cpl/bld/namelist_files/namelist_defaults_drv.xml
both modified:   driver_cpl/bld/namelist_files/namelist_definition_drv.xml
both modified:   driver_cpl/cime_config/buildnml
both modified:   driver_cpl/cime_config/config_component.xml

**Comment by rljacob** [comment]
@jgfouca is going to try merging rljacob/bring-acmecime5.1 directly to a branch off of master.  So we won't put those changes on maint-cime5.1.

**Comment by rljacob** [comment]
Updated the steps.  1 and 2 are done.  We're thinking of combining 3 and 4.

**Comment by rljacob** [comment]
Closing this as the merge of ACME'e cime is underway in #1065
