### ISSUE TITLE
Problem with gptl build for with gnu for mpi-serial

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1053]
This works in cime5.2.0-alpha.9, but fails in cime5.2.0-alpha.20. A sample test based off of cesm2_0_beta05 is "SMS_D_Ld1_Mmpi-serial.1x1_vancouverCAN.I1PTCLM45.yellowstone_gnu.clm-default". So this is the gnu compiler on yellowstone, with mpi-serial. pgi, intel and nag all work with mpi-serial for this version.

The build for the above fails when trying to make the gptl library. It looks like the problem is that SCC isn't defined in the Macros.make file when COMPILER==gnu.

**Comment by jedwards4b** [comment]
Fixed in #1022

**Comment by jedwards4b** [comment]
When a developer finds a problem which is not at the head of master, shouldn't the first step be to check if it's already been addressed?

**Comment by ekluzek** [comment]
I am happy to do that. But, it's not clear to me an easy way to do that.

Looking at closed issues and "gnu" as well as closed "pull requests" and
"gnu" I don't see the fix come up. Looking at "closed PR's and SCC" it does
come up. So the right search may find the problem, while another search may
miss it.

*Erik Kluzek, (CGD at NCAR)*

*National Center for Atmospheric Research*

*Boulder CO, *

*(off) (303)497-1326 (fax) (303)497-1348*

*(skype) ekluzek    (cell) (303)859-0183*

*Pronouns: he/his/him*

*------------------ Home page ------------------------*

*          http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*

*          https://staff.ucar.edu/users/erik
<https://staff.ucar.edu/users/erik>*

*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*

**Comment by jedwards4b** [comment]
How about getting the latest master from cime and testing it?

**Comment by ekluzek** [comment]
Closing as fixed in pull request #1022
