### ISSUE TITLE
case.setup in cime user's guide

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1059]
With PES etc.

**Comment by jgfouca** [comment]
Please assign follow up review ticket.

**Comment by mvertens** [comment]
@rljacob @jgfouca @bertinia  - is this now resolved? Is this enough documentation for `case.setup ` - or do we need to add more?

**Comment by mvertens** [comment]
Need to add when you need to run case.setup
- after you change env_mach_pes.xml
- before the first time you call preview_namelists
- before the first time you call case.build
When do you need to use case.setup --clean and case.setup --reset
- case.setup --clean is being depracated
- case.setup --reset is needed if you have already run case.setup and need to run it again

**Comment by rljacob** [comment]
TODO:  Check documentation to see if still an issue.

**Comment by billsacks** [comment]
It looks like the details from https://github.com/ESMCI/cime/issues/1059#issuecomment-327277555 still haven't been added to https://esmci.github.io/cime/versions/master/html/users_guide/setting-up-a-case.html
