### ISSUE TITLE
CIME github issue labels

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1061]
The labels we can attach to github issues (including PRs) have been updated. 
https://github.com/ESMCI/cime/labels

The old "topic:***" labels have been removed.

Are these categories ok?

the part of CIME the issue is about:

- data-models
- driver_cpl
- machine files (is this only for config_machines, config_compilers problems?)
- system tests - for an issue about the ERS, SMS, etc. tests.
- unit tests
- user interface - for an issue about the scripts user's run.  create_*, manage_*, etc.

for cime_config issues:

- acme-only
- cesm-only

issue type (every issue should have one and only one of these?):

- bug
- documentation
- enhancement
- help wanted
- question

issue severity

- CRITICAL
- Low priority

issue resolution (besides "closed")

- wontfix
- duplicate 
- invalid

These labels are used by Waffle and don't need to be manually entered:
- in progress
- ready

**Comment by billsacks** [comment]
I'd like to have a prefix for the labels, as was done here https://github.com/CESM-Development/cime/labels - in order to group similar labels. Otherwise, it's hard to find the right labels for an issue.

**Comment by rljacob** [comment]
What really works for those is the similar color.  About we just use that and skip the prefix?

**Comment by billsacks** [comment]
Similar color helps, but prefix is useful for grouping the labels together. e.g., currently, it's hard to know what categories are available in terms of "data models", "driver_cpl" and the like. Even if they have the same color, you still have to scroll through the whole list to find the most appropriate category; if we have a prefix, it's much easier to just look through the relevant group.

**Comment by rljacob** [comment]
I see how the prefix helps order the labels since they're listed alphabetically in the dropdown menu.  But I want the labels to be short and concise so can the prefix be a letter or two instead of word like "topic"?

**Comment by billsacks** [comment]
@rljacob - yes, that sounds great.

**Comment by rljacob** [comment]
Following up on our telecon, this is the proposal for labels and how to use them.

Some labels are for issues only, some are for PRs and some both.

"may" means adding that label is optional
"must" means one label from that category must be on every issue.

topic = "tp".  PR or issue.  Area of CIME it concerns.  An issue/PR **must** have one of these.  Add more if the PR touches code in multiple areas of CIME.
```
tp: data mod
tp: dead mod
tp: stub mod
tp: documentation - gh-pages or READMEs or other in-code docs
tp: drv mct
tp: src shr
tp: user int (scripts in cime/scripts or ones created by create_newcase)
tp: sys test 
tp: unit test
tp: CIMElib (anything in cime/scripts/lib not part of user int or tests)
tp: auxtools  (things in cime/scripts/Tools)
tp: tools  (things in cime/tools
tp: config (things in cime/config but not the model-specific dirs)
```
type = "ty".  issue or PR.  Must have one
```
ty: Bug   - issue that is a bug report
ty: Bug fix  - PR that fixes a bug.
ty: Enhancement  - use on issue that requests the Enchancement and PR that implements it)
ty: Discussion  - for issues that are just to discuss something
ty: Question - issues that ask a question
```

impact = "imp".  PR-only.  A PR **may** have at least one of these labels.
```
imp: non-BFB
imp: Climate Changing      (implies non-BFB)
imp: backwards incompat
If there is no imp label, the PR is assumed to be BFB and preserves backwards compatibility.
```
status = "st".   A _closed_ issue **may** have one of these labels.
```
st: dup   - issue is a duplicate of a previous issue.
st: invalid - not a real issue or not one that involves CIME.
st: wontfix - a real issue but won't fix/resolve it.
Closed issues without an st label were fixed/resolved by a PR or otherwise completed.
```
others labels without a prefix:
Critical - add to any issue or PR that needs immediate attention.
acme-only - add to any issue or PR for code in cime/config/acme
cesm-only - add to any issue or PR for code in cime/config/cesm

**Comment by rljacob** [comment]
@billsacks and @bertinia, see above

**Comment by mvertens** [comment]
@rljacob - thanks for doing this!

**Comment by billsacks** [comment]
@rljacob - thanks a lot! This list looks pretty good. I'd say:

1. There are a few words that you shortened a bit, which I would spell out to make it more clear what they mean: "mod" -> "models" (data models, dead models, stub models); "user int" -> "user interface". I think it's worth spending a few extra characters for clarity, especially for people who aren't developing cime on a daily basis.

2. I think I'll always get confused about "tools" vs. "auxtools". What about renaming auxtools to scripts tools to connect it with its location in the source tree?

**Comment by rljacob** [comment]
I updated the comment with all the labels with Bill's changes.

**Comment by rljacob** [comment]
Labels have been changed/added in github and description added to https://github.com/ESMCI/cime/wiki/Repository-workflow

**Comment by billsacks** [comment]
I added "tp: unknown" for issues where you don't know the root cause. I figured this is better than leaving off a "tp" label entirely, because it allows filtering on all issues with "tp: unknown".
