### ISSUE TITLE
Fortran unit tests broken on yellowstone since cime5.2.0-alpha.11

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1072]
The Fortran unit tests have been broken on yellowstone since cime5.2.0-alpha.11 (I have confirmed that they work in cime5.2.0-alpha.10). The issue is in the python code that sets up the machine environment. I am running them using the command documented in cime/README.unit_testing

The problem appears in `tools/unit_testing/python/machine_setup.py`, in `add_path`. I think the problem is here:

```python
        match = best_match(self.compiler_xml_tree, "compiler/"+name+"_PATH",
                           self.machine_dict)
        if match is not None:
            macros_printer.print_header(name + " location.")
            libpath = match.text
```

From running this through pdb in both cime5.2.0-alpha.10 and master, I see:

In both:

```
(Pdb) p match
<Element 'PFUNIT_PATH' at 0x2b7052b0a810>
```

In cime5.2.0-alpha.10:

```
(Pdb) p match.text
'$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.1_Intel15.0.1_MPI'
```

On master:

```
(Pdb) p match.text
None
```

I haven't been able to figure out why this no longer works in recent versions - I'm not very familiar with this area of the code.

A temporary workaround seems to be:

1. First build the unit tests with cime5.2.0-alpha.10 or earlier

2. Then git checkout your latest version in the same directory; do NOT remove the `__command_line_test__` directory.

3. Then rebuild the unit tests from your latest version

Tagging @mfdeakin @jedwards4b @mvertens

**Comment by billsacks** [comment]
Tagged the wrong Michael. Should have tagged @mgduda

**Comment by billsacks** [comment]
Also tagging @ekluzek - this likely affects the running of CLM unit tests on yellowstone with the beta05 cime. Personally I usually run the unit tests on my local machine so this shouldn't be an issue for me, but it may affect you or others.

**Comment by jedwards4b** [comment]
Looking at the code in machine_setup.py the problem is that this is attempting to directly access the xml files instead of using the interface routines in CIME/XML.   This code needs to be rewritten to import CIME/XML/machines instead of import ElementTree.

**Comment by jedwards4b** [comment]
I just tried this using the instructions provided and was not able to reproduce the reported problem:
```
run_tests.py --build-dir=./bld --test-spec-dir=Examples/circle_area/src --compiler=intel --mpilib=mpich2
==================================================
Running cmake for __command_line_test__/__command_line_test__.
==================================================
libpath = $ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.1_Intel15.0.1_MPI
libpath = $ENV{NETCDF}
libpath = $ENV{PNETCDF}
libpath = $ENV{TRILINOS_PATH}
-- The C compiler identification is Intel 15.0.0.20141023
-- The CXX compiler identification is Intel 15.0.0.20141023
-- Check for working C compiler: /glade/apps/opt/modulefiles/ys/cmpwrappers/mpicc
-- Check for working C compiler: /glade/apps/opt/modulefiles/ys/cmpwrappers/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /glade/apps/opt/modulefiles/ys/cmpwrappers/CC
-- Check for working CXX compiler: /glade/apps/opt/modulefiles/ys/cmpwrappers/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:6 (sourcelist_to_parent):
  Unknown CMake command "sourcelist_to_parent".
```

**Comment by billsacks** [comment]
@jedwards4b - I'm not sure where those instructions are from. The instructions I'm referring to are the ones in README.unit_testing at the top level of cime:

```
tools/unit_testing/run_tests.py --test-spec-dir=. --compiler=intel --mpilib=mpich2 --mpirun-command=mpirun.lsf --cmake-args=-DPAPI_LIB=/glade/apps/opt/papi/5.3.0/intel/12.1.5/lib64
```

I have verified that this fails in add_path in 38cc009. However, when I updated to the latest master (e367fb4) I was able to get past that point! And I have confirmed in the debugger:

```
(Pdb) p match.text
'$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.1_Intel15.0.1_MPI'
```

So perhaps you or someone else fixed this in the last few days, either intentionally or unintentionally?

However, now I'm getting a different error, further along in the build:

```
[ 39%] Building Fortran object driver_cpl/unit_test/avect_wrapper_test/CMakeFiles/avect_wrapper_exe.dir/glade/p/cesmdata/cseg/tools/pFUnit/pFUnit3.1_Intel15.0.1_MPI/include/driver.F90.o
Linking Fortran executable avect_wrapper_exe
ifort: command line remark #10148: option '-i_dynamic' not supported
/glade/p/cesmdata/cseg/tools/pFUnit/pFUnit3.1_Intel15.0.1_MPI/lib/libpfunit.a(Exception.F90.o): In function `throw_message':
/glade/u/home/sacks/pFUnit/pfunit_source/source/Exception.F90:399: undefined reference to `__kmpc_global_thread_num'
/glade/u/home/sacks/pFUnit/pfunit_source/source/Exception.F90:400: undefined reference to `__kmpc_critical'
/glade/u/home/sacks/pFUnit/pfunit_source/source/Exception.F90:404: undefined reference to `__kmpc_end_critical'
make[2]: *** [driver_cpl/unit_test/avect_wrapper_test/avect_wrapper_exe] Error 1
make[1]: *** [driver_cpl/unit_test/avect_wrapper_test/CMakeFiles/avect_wrapper_exe.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "tools/unit_testing/run_tests.py", line 408, in <module>
    make_stage(name)
  File "tools/unit_testing/run_tests.py", line 385, in make_stage
    subprocess.check_call(make_command)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
```

From a quick google search, it sounds like the problem is that -openmp is needed on the link line: Note that I build pFUnit on yellowstone with OPENMP support. I'm not sure what's changed recently so that this is no longer working - nor do I know what's needed to get -openmp onto the link line here.

**Comment by billsacks** [comment]
I have verified that I can get past the above link error in cime5.2.0-alpha.10. Unfortunately, I'm having trouble determining when the error came in after that point, because the cmake configure step had been broken since cime5.2.0-alpha.11, due to the originally-reported issue, above.

I tried getting past the cmake configure with alpha.10, killing the build with ctrl-c, then checking out a later version of cime and continuing the build from there. With that process, I was able to get the unit tests to all build and run even with the latest cime master. I guess that suggests that something is getting set incorrectly in the cmake configure with the latest cime master.

**Comment by billsacks** [comment]
I also tried adding `--use-openmp` in the call to run_tests.py, but that didn't help.

If it seems like it could take a while to track down this latest problem, I could redo the build of pFUnit to not have OpenMP support. I don't know if any unit tests actually use OpenMP - certainly none that I've added use it: My build was just based on instructions that Sean Santos gave me: he's the one that said I should turn on OpenMP support.

@jedwards4b - can let me know what you think?: how hard do you think it will be to get -openmp added to the link line here? (I'm having trouble figuring out how I would do that with the code in machine_setup.py) I'm trying to figure out if we should pursue that option or if I should try building pfunit without openmp.

**Comment by ekluzek** [comment]
Using git bisect I identified the bad commit as: f117402c0ecb6767e6c8ddf9a582e3a41b9d3e2d. The problem is that this is a pretty large commit so it's not obvious what part of it is the issue. I also couldn't easily revert that commit. But, it's possible that if you can do the revert and handle the conflicts appropriately you could have something that works. Some of the changes in that commit are for acme, so that part we can ignore in terms of getting something that will work for clm.
