### ISSUE TITLE
Need to refactor python for fortran unit tests 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1073]
See issues #787, #872, #1072 

The python code in unit_testing is not integrated with the python/CIME tools.  Integration will make this tool easier to support and will give it a look and feel common to all cime python.   Tools should never attempt to directly access the xml, instead going through the CIME/XML interfaces so that they are isolated from changes in XML format.

**Comment by jedwards4b** [comment]
I've started a branch to refactor the unit tests - 
To git@github.com:jedwards4b/cime.git
 * [new branch]      unit_test_refactor -> unit_test_refactor

**Comment by jedwards4b** [comment]
I've got this mostly working for Examples and driver but I haven't figured out the Regex issue yet - can you help?

**Comment by jedwards4b** [comment]
I spoke too soon - I would really appreciate some help but you had better be prepared for some frustration :-)

**Comment by jgfouca** [comment]
> but I haven't figured out the Regex issue yet - can you help?

@jedwards4b was this directed at me?

**Comment by jedwards4b** [comment]
No - @billsacks
