### ISSUE TITLE
CLM test fails with PIO error

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1074]
The following test fails with cime master as well as cime5.2.0-alpha.15 (it works in the version just before cime5.2.0-alpha.14).

ERP_D_Ld5.hcru_hcru.ICRUCLM45BGC.yellowstone_pgi

It fails with a PIO error...

   5: box_rearrange::compute_dest:: INFO io             5  lb=
   5:                        0                      288                        0
   5:                        0  ub=                      720
   5:                      360                        3                        5
   5: box_rearrange::compute_dest:: INFO dof           631  index=
   5:                   829304  gcoord=                      584
   5:                       71                        0                        1
   5: pio_support::pio_die:: myrank=           -1 : ERROR: box_rearrange.F90.in:
   5:          919 : quitting
   5:Abort(1) on node 5 (rank 5 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
   5:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
   0:Abort(1) on node 0 (rank 0 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
   0:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
   1: pio_support::pio_die:: myrank=           -1 : ERROR: box_rearrange.F90.in:
   1:          919 : quitting
   1:Abort(1) on node 1 (rank 1 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
   1:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
   2:Abort(1) on node 2 (rank 2 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
   2:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
   3:                        0  ub=                      720
   3:                      360                        3                        5
   3: box_rearrange::compute_dest:: INFO dof           631  index=
   3:                   828587  gcoord=                      587

One difference I noticed is that in cime5.2.0-alpha.15 PIO_NUMTASKS is set to 40, while in cime5.2.0-alpha.14 PIO_NUMTASKS is set to -99.

@billsacks @bandre-ucar @mvertens

**Comment by mvertens** [comment]
Could you please assign this to Jim Edwards.

**Comment by rljacob** [comment]
@mvertens you should be able to reset an assignment on any issue or PR.

**Comment by jedwards4b** [comment]
This appears to be a problem in computing the DOF in clm.  The global size of the array being read
is 720x360=259200 but values found in the DOF include 827146, 829299,  827866, 828588, 829305, 828582.

**Comment by jedwards4b** [comment]
Actually the size is 720x360x3x5 so that may not be the problem.

**Comment by ekluzek** [comment]
This seems to be working with

cime5.3.0-alpha.02

PASS ERP_D_Ld5.hcru_hcru.ICRUCLM45BGC.yellowstone_pgi RUN time=1325
PASS ERP_D_Ld5.hcru_hcru.ICRUCLM45BGC.yellowstone_pgi COMPARE_base_rest

This is with what will be tagged as clm4_5_14_r228

**Comment by ekluzek** [comment]
I think PR #1195 fixed this problem.
