### ISSUE TITLE
Be consistent when accessing environment

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1078]
config_compilers uses

```
<env>VARNAME</env>
```

everything else uses

```
$ENV{VARNAME}
```

config_compilers should be changed to be consistent with the other files.

**Comment by jedwards4b** [comment]
I was able to add a call to the genericxml get_resolved_value in the compilerblock.py
method _handle_references - it works but there is a consequence.   
with the <env> method the resulting macros file has the unresolved value ($(NETCDF)) while with the $ENV{} method the fully resolved value is in the file when it's written.   

I think that for this file we want to preserve the <env> style result and so this will need more work.
