### ISSUE TITLE
Mapping CIME variables to CMake variables

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1085]
Building libraries (such as PIO) by directly invoking CMake requires we map CIME variables to ones used by the CMake system. For example:
`NETCDF_PATH = ${NETCDFROOT}`
is exported to Macros.make on machines which use NETCDFROOT by a Compilers object. The Makefile uses this definition to inform the libraries where netcdf is.
For the CMake build system being worked on by @agsalin and @bmpersc, we'd like to do something similar, and export a CMake precache. The precache would be library specific, only defining variables needed by the library being built. These variables and what the corresponding CIME variable is would be defined in another XML configuration file, say "config_library_defines.xml".
Possible issues include mutually exclusive variables used by a library, and CIME variables which need to be modified before they can be put into the precache.

Are there any comments or concerns with this modification?

This would also finish #979.

**Comment by mfdeakin-sandia** [comment]
A proposed xml format can be found here: https://github.com/ESMCI/cime/blob/mfdeakin-sandia/cmake_build/cime_config/acme/machines/config_metabuild.xml

Also, why was this assigned to @jedwards4b?

**Comment by rljacob** [comment]
I don't know why I made that assignment.  Its been fixed.

**Comment by agsalin** [comment]
Copied from Slack: 
Nice progress. I was not expecting this to be so verbose, assuming that this would need to be expanded for libraries beyond pio. It may just mean you are just far ahead of where I was thinking. I was thinking your idea was to make a list of translations: e.g., 
<entry  cime_var="MPICC" cmake_var="CMAKE_C_COMPILER" />, 
and send it all to CMake and let it fly. Seems like you might be taking steps towards designing a build system (e.g. setting <requires>), not just setting defines for a cmake build system.

**Comment by jedwards4b** [comment]
Copied from Slack:  how would I use get_node to get the component element without any attributes? 
I think this would work:
```
get_node('component', xpath="not(@*)")
```

**Comment by mfdeakin-sandia** [comment]
Doesn't work, unfortunately. ElementTree doesn't support not or most of the logical operators: https://docs.python.org/2/library/xml.etree.elementtree.html#elementtree-xpath

**Comment by jedwards4b** [comment]
Oh yea - I remember running into that now.   I've solved this problem before, let me look around.

**Comment by jedwards4b** [comment]
I think that the best way is to read them all using get_nodes and find the ones without attributes, this is a limitation of python elementtree and not of genericxml.py

**Comment by mfdeakin-sandia** [comment]
I have significantly simplified the xml structure after talking with @agsalin, and also started an implementation of the configuration generator.
I left the component node in just in case we might need it in the future, to make changes to the format easier, and because I don't think it adds significant verbosity.

**Comment by jedwards4b** [comment]
Can you update the link to the proposed xml format?

**Comment by mfdeakin-sandia** [comment]
What do you mean? The link points to the current proposed format.

**Comment by jedwards4b** [comment]
Sorry - I do see that now.

**Comment by jedwards4b** [comment]
I'm confused about where you are getting these variables, for example FPPDEFS is a variable defined in the Makefile, it is not available in Macros.CMake.

**Comment by mfdeakin-sandia** [comment]
This is still a work in progress; I intend to find out what FPPDEFS should be and make the appropriate substitution like I've partly done for GPTL_PATH.

**Comment by jedwards4b** [comment]
I'm concerned that this is going to bring us to a situation in which we have to make changes in more than one place.

**Comment by mfdeakin-sandia** [comment]
That's a fair point that I haven't come up with a good way to deal with yet. One thought I've had, but rather dislike, is having all each new tag to append to what was there previously; but then we're requiring that we remember the order that the tags occur in and assuming a default value.
A better idea I think would be to use the non-configuration section specify more variables which can be used for the substitution. This would enable us to only specify GPTL_PATH once, instead of the 4 times I currently have.

**Comment by jedwards4b** [comment]
Any reason we should keep this issue open?

**Comment by jgfouca** [comment]
@jedwards4b , I don't think so. The build system has come a long ways since this ticket was filed.
