### ISSUE TITLE
S-Compset: need to add a test or remove it

### ISSUE THREAD

**Issue by agsalin** [ESMCI/cime#1087]
I don't see any tests for the S compset (stubs only, just needs CIME to build). 
I looked at query-testlists and update_acme_tests.py and didn't see any *.S*.

Seems to me that we should either test it, or dump it.

Opinions please?

**Comment by jedwards4b** [comment]
I think that you are right, stub components are tested as parts of other compsets, but we never test S - does anyone see a need to keep it around?

**Comment by rljacob** [comment]
If we think this should be a valid compset, lets just add a test to cime_developer.

**Comment by agsalin** [comment]
Closing old issue. It was fixed in February by PR #1181
