### ISSUE TITLE
timer defaults in cime 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1096]
With the following code in namelist_definition_drv.xml it would seem that profile_detail_limit can never be set to a value > 1 without using user_nl_cpl.   (TIMER_LEVEL > 1 means timer_level='pos') 
A number of cesm users have requested that this variable have a different default (4) so that some timers are always on by default.  However acme wants 0 to be the default.   These values look backward to me - I think we want 0 when timer_level='neg' and TIMER_LEVEL when 'pos'  and then 
set TIMER_LEVEL=0 in the xml for acme.  Do you agree?
```
 <entry id="profile_detail_limit">                                                 
    <type>integer</type>                                                            
    <category>performance</category>                                                
    <group>prof_inparm</group>                                                      
    <desc>                                                                          
    </desc>                                                                         
    <values>                                                                        
      <value timer_level='neg'>$TIMER_LEVEL</value>                                 
      <value timer_level='pos'>0</value>                                            
    </values>                                                                       
  </entry>            
```

**Comment by mnlevy1981** [comment]
Does this proposal also fix #770?

**Comment by jedwards4b** [comment]
#1097 does

**Comment by mvertens** [comment]
I agree with this approach. Given this TIMER_LEVEL and TIMER_DETAIL should
go into the config_component_[acme,cesm].xml files and not stay in the
unified file.

I am not sure what else I am supposed to do at this point - since #1097
seems to be the fix to this.
