### ISSUE TITLE
Why does scripts_regression_tests.py call cime_developer tests twice?

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1106]
I am having in issue with a new test which has trouble because it is being run twice in the same directory. It is a system_compare_two test but each phase is being called twice.
The second set of runs is being called several minutes after the first set.

At the least, this seems like a waste of resources. What is going on?

**Comment by jgfouca** [comment]
Z_FullSystemTests runs each test twice to ensure that it can be successfully re-run. This is not as trivial as it sounds because the running of the tests changes lots of XML values. These values then need to be set back upon re-run.

**Comment by gold2718** [comment]
In that case, it worked as intended as the DAE test needed to do some cleanup before it could be rerun.
Closing this as 'question' as it is answered.
Thanks!

**Comment by jedwards4b** [comment]
Just to clarify - is the DAE now able to be rerun in a case?

**Comment by gold2718** [comment]
Yes, that change is in the PR you merged this morning.
