### ISSUE TITLE
new cdash failure on master

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1113]
ERRPUT: In TestStatus file for test 'DAE.f19_f19.A.yellowstone_intel', line 'ak test' not in expected format
In TestStatus file for test 'ERIO.f45_g37.X.yellowstone_intel', line 'eak test' not in expected format

**Comment by jedwards4b** [comment]
When I create_test DAE.f19_f19.A.yellowstone_intel on yellowstone it appears that the first run of the test passes, but a subsequent run from the same directory fails with 
FAIL DAE.f19_f19.A.yellowstone_intel COMPARE_base_da

**Comment by jedwards4b** [comment]
The two runs of the base case are identical, but it looks like the first da run begins at date 00010101
while the second begins at date 00010105

**Comment by gold2718** [comment]
I assume the first run was done as part of the `./create_test` call. How did you do the second run?
