### ISSUE TITLE
ERIO test gives false positive in PIO1

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1114]
The netcdf4p and netcdf4c pio types silently fail to open that format and fail over to netcdf and
so this test falsely indicates those tests as passing.

**Comment by jgfouca** [comment]
Still need to confirm that silent fails don't re-appear without us noticing.

**Comment by jedwards4b** [comment]
The way to do it is to open the file and check the format, ncdump -k maybe...

**Comment by jgfouca** [comment]
@jedwards4b , I tried ncdump -k:

```
% ncdump -k ERIO.f45_g37.X.melvin_gnu.20170504_133426_8q7wdv.cpl.hi.0001-01-12-00000.nc.netcdf
64-bit offset
% ncdump -k ERIO.f45_g37.X.melvin_gnu.20170504_133426_8q7wdv.cpl.hi.0001-01-12-00000.nc.pnetcdf
classic
```

Is "64-bit offset" vs. "classic" something we can rely on to differentiate between netcdf and pnetcdf?

**Comment by jedwards4b** [comment]
-k

Show what kind of netCDF file the pathname references, one of ‘classic’, ‘64-bit offset’,‘netCDF-4’, or ‘netCDF-4 classic model’. Before version 3.6, there was only one kind of netCDF file, designated as ‘classic’ (also know as format variant 1). Large file support introduced another variant of the format, designated as ‘64-bit offset’ (known as format variant 2). NetCDF-4, uses a third variant of the format, ‘netCDF-4’ (format variant 3). Another format variant, designated ‘netCDF-4 classic model’ (format variant 4), is restricted to features supported by the netCDF-3 data model but represented using the HDF5 format, so that an unmodified netCDF-3 program can read or write the file just by relinking with the netCDF-4 library. The string output by using the ‘-k’ option may be provided as the value of the ‘-k’ option to ncgen(1) to specify exactly what kind of netCDF file to generate, when you want to override the default inferred from the CDL.   

I believe there is also a '64-bit data' possible.  pnetcdf and netcdf cannot write netCDF-4 and I don't know if there is a way to tell netcdf4p from netcdf4c.

**Comment by jgfouca** [comment]
OK, so I think we've done the best we can with the ERIO test.
