### ISSUE TITLE
archive needs name of history file for config_archive.xml for MOSART and RTM

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1129]
This is with latest cime master. And it looks like it was something that came in between the update of cime for cesm2_0_beta04 and cesm2_0_beta05.

[erik@yslogin4 cime]$ git diff
diff --git a/cime_config/cesm/config_archive.xml b/cime_config/cesm/config_archive.xml
index 51b1831..ff484fa 100644
--- a/cime_config/cesm/config_archive.xml
+++ b/cime_config/cesm/config_archive.xml
@@ -43,7 +43,7 @@
   <comp_archive_spec compname="rtm" compclass="rof">
     <rest_file_extension>\.r.*</rest_file_extension>
     <hist_file_extension>\.h.*.nc$</hist_file_extension>
-    <rest_history_varname>unset</rest_history_varname>
+    <rest_history_varname>locfnh</rest_history_varname>
     <rpointer>
       <rpointer_file>rpointer$NINST_STRING.rof</rpointer_file>
       <rpointer_content>$CASE.rtm$NINST_STRING.r.$DATENAME.nc</rpointer_content>
@@ -53,7 +53,7 @@
   <comp_archive_spec compname="mosart" compclass="rof">
     <rest_file_extension>\.r.*</rest_file_extension>
     <hist_file_extension>\.h.*.nc$</hist_file_extension>
-    <rest_history_varname>unset</rest_history_varname>
+    <rest_history_varname>locfnh</rest_history_varname>
     <rpointer>
       <rpointer_file>rpointer$NINST_STRING.rof</rpointer_file>
       <rpointer_content>$CASE.mosart$NINST_STRING.r.$DATENAME.nc</rpointer_content>

**Comment by bertinia** [comment]
This was fixed in #1131
