### ISSUE TITLE
allow --debug option to propagate to queue dependent jobs

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1130]
If you submit a case using "case.submit --debug" and DOUT_S=TRUE, it would be
helpful to propagate the debug argument to the case.st_archive call. Likewise,
if DOUT_L_MS=TRUE then the --debug argument should be applied to the case.lt_archive arg list.

**Comment by billsacks** [comment]
I'm removing this from the cesm2 milestone, because other things seem higher priority. If others disagree, feel free to re-add it to that milestone.

**Comment by billsacks** [comment]
I'm removing this from the cesm2 milestone, because other things seem higher priority. If others disagree, feel free to re-add it to that milestone.
