### ISSUE TITLE
case_run.py uses an incorrect format descriptor when defining da_script command

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1132]
in case_run.py
    cmd = da_script + " 1> da.log.%s %d %d 2>&1" %(lid, caseroot, cycle)
needs to be
    cmd = da_script + " 1> da.log.%s %s %d 2>&1" %(lid, caseroot, cycle)
because caseroot is a string, not a number.

This prevents the script from completing, so maybe it should
have a higher priority.

**Comment by gold2718** [comment]
This was fixed in PR #1095 and seems to be correct on master.
