### ISSUE TITLE
bld/Depends can get out of sync with dependencies in evolving code

### ISSUE THREAD

**Issue by klindsay28** [ESMCI/cime#1138]
During development, I usually have a stand-alone case that I do test builds and runs in, prior to invoking create_test. As I change code, I regularly run case.build to ensure that the new code compiles.

A recent change I made introduced a new dependency between Fortran modules, A.F90 now uses B.F90, where it did not before. The new dependency was not reflected in the bld/Depends file, because the Depends file was never updated. I also ran case.build --clean, which removed the .mod files. It turns out that make tried to compile A.F90 prior to compiling B.F90, and the compiler couldn't find B.mod. So I couldn't get the build to work. It did work when I setup a completely new case.

I think there needs to be a mechanism to rebuild the Depends file.

**Comment by gold2718** [comment]
You may not consider this a solution but here is my method for this situation (commands executed from case directory):

```
./case.build --clean-all
rm -rf bld
./case.setup --clean
./case.setup
```

**Comment by jedwards4b** [comment]
What @gold2718 said with the additional note that 
./case.setup --clean
./case.setup 

can be replaced by
./case.setup --reset

**Comment by mvertens** [comment]
I think it puts an undue burden on the developers to know that they
actually have to issue a "rm -rf bld" command. Any user would naively
assume that simply issuing a ./case.build --clean-all would be sufficient.
Maybe a new argument such as --clean-bld would clarify that --clean-all
does not remove the bld and therefore any dependencies that are in the bld
directory and that you need a stronger command to ensure this. At least the
user would be aware of this behavior from the help command.

**Comment by gold2718** [comment]
I'm not sure why --clean-all does _not_ remove bld or at least all the files in bld. @jedwards4b? @jgfouca?

**Comment by jgfouca** [comment]
@gold2718 good question, it seems like it should. Maybe there's some legacy reason why it doesn't.

**Comment by jedwards4b** [comment]
I think it just felt like overkill - we can try that change if you want.

**Comment by gold2718** [comment]
I agree about the overkill but right now, we have underkill which is worse because --clean-all does not work.

**Comment by jedwards4b** [comment]
Cleaning by simply removing the build directory is incorrect and causes problems in the case of tests that build two executables in the same directory.   PR #1140 addresses this issue without removing the bld directory.
