### ISSUE TITLE
Build pFUnit on some other machines

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1141]
We should build pFUnit on some other machines so we can run unit tests there:

- cheyenne
- hobart

Instructions for building pFUnit are:

1. Download pFUnit from
   http://sourceforge.net/projects/pfunit/files/latest/download

2. Set the PFUNIT environment variable. For example::

     ```
     export PFUNIT=/glade/p/cesmdata/cseg/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_MPI_openMP
     ```

3. Build pFUnit:

```
     mkdir build
     cd build
     cmake -DMPI=YES -DOPENMP=YES ..
     make -j 4
```

4. Run pFUnit's own unit tests:

```
     make tests
```

   Note: this didn't work on yellowstone. Instead, I had to do it by hand:

```
     DAV_CORES=4 execca
     mpirun.lsf tests/tests.x
```

5. Install pFUnit on your system:

```
     make install INSTALL_DIR=$PFUNIT
```

**Comment by billsacks** [comment]
There are already some pFUnit builds on hobart, in Sean Santos's home directory. I could initially test with these, but eventually want to rebuild this using our standard build arguments (as given above), put in some more central location.

**Comment by billsacks** [comment]
On cheyenne, I built pFUnit3.2.8 with:

```
module load intel/17.0.1
module load cmake

export PFUNIT=/glade/p/cesmdata/cseg/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_MPI_openMP
mkdir build
cd build
cmake -DMPI=YES -DOPENMP=YES -DCMAKE_INSTALL_PREFIX=$PFUNIT ..
make -j 4
make install
```

**Comment by rljacob** [comment]
FYI.  There is some work going on in CMDV to containerize pFUnit.

**Comment by billsacks** [comment]
@rljacob - that sounds great, thanks for the heads-up. For now we at least need this on cheyenne (the yellowstone replacement), but that could be useful in the future.

**Comment by billsacks** [comment]
I'm running into trouble on cheyenne. The fundamental problem is that (1) On the login nodes, I can build the unit tests, but cannot run them, but (2) On the compute nodes, I cannot build the unit tests. The unit test workflow requires building and running in the same place. I'm working with CISL to try to resolve this.

**Comment by billsacks** [comment]
I got the pFUnit build and self-tests working on cheyenne with this procedure:

```
export PFUNIT=/glade/p/cesmdata/cseg/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_MPI_openMP
mkdir build
cd build
cmake -DMPI=YES -DOPENMP=YES -DCMAKE_INSTALL_PREFIX=$PFUNIT -DROBUST=NO ..
make -j 4
make install
```

Then from an interactive session (with qinteractive) I was able to run `make tests`.

I'm still waiting for a resolution to the problem of how to build and run unit tests from the same place.
