### ISSUE TITLE
Unit test build no longer uses debug flags

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1143]
As of PR #1135 , the fortran unit test build no longer uses debug flags in the build.

By running run_tests.py with -v, I see that I got the following flags out of cime5.2.0-alpha.10:

```
  -DCPRINTEL -DFORTRANUNDERSCORE -DHAVE_SSE2 -DINTEL_MKL -DLINUX -DNO_R16 -DUSE_CONTIGUOUS=contiguous, -assume realloc_lhs  -no-opt-dynamic-align -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created -xHost
```

whereas now I get:

```
 -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_ESP=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ROF=1 -DNUM_COMP_INST_WAV=1 -D   -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL  -DINTEL_MKL -DHAVE_SSE2   -qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source    -qopenmp    -xHost   -O2 -debug minimal
```

I have tried --build-type CESM_DEBUG and --build-type CIME_DEBUG, but neither of those give debug flags.

**Comment by billsacks** [comment]
cc @jedwards4b

**Comment by jedwards4b** [comment]
Hard coded at line 257 of run_tests.py - the issue is that the test test_infnan.F90 at line 49 and 51 
segfaults in debug mode because our debug mode traps divide by zero.   The fix might be to add a
#ifndef DEBUG around this code...

**Comment by billsacks** [comment]
Ah, thanks - I'll take a stab at this
