### ISSUE TITLE
Should run_tests.py --clean clean more things?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1146]
When you run the Fortran unit tests with run_tests.py, they are built in-source by default. There are pros and cons to that, but the big pro is that you can quickly rebuild & rerun the unit tests as you make incremental changes, supporting a TDD style of development.

But sometimes you want to clean everything out and start fresh. run_tests.py has a '--clean' argument that is supposed to do this for you. But as of PR #1135 , run_tests.py creates some new files in the build directory, which are not cleaned with '--clean':

	.env_mach_specific.csh
	.env_mach_specific.sh
	Depends.intel
	Macros.cmake
	env_mach_specific.xml

Furthermore, other than Macros.cmake, these files are not recreated when you rerun run_tests.py if they already exist.

For now, I have suggested a workaround in README.unit_testing:

```
tempdir=`mktemp -d --tmpdir=. unit_tests.XXXXXXXX`
tools/unit_testing/run_tests.py --test-spec-dir=. --compiler=intel --mpilib=mpich2 --use-openmp --mpirun-command=mpirun.lsf --build-dir $tempdir
```

-- i.e., creating a fresh directory to hold a unit test build.

But longer-term, should we come up with a more robust solution? I'm thinking one or more of:

1. Make --clean remove all of the above files

2. Put the above files in the `__command_line_test__` directory created by run_tests.py, so that removing this directory will remove those files.

3. Use a temporary directory for the build-dir by default.

**Comment by jedwards4b** [comment]
solution 2 should be easy with a little reordering in run_tests.py
