### ISSUE TITLE
 Formal definitions of pelayout sizes used in create_newcase

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1153]
The create_newcase script includes the option:

 --pecount PECOUNT, -pecount PECOUNT
                        Specify a target size description for the number of
                        coresAllowed options are
                        ('S','M','L','X1','X2','[0-9]x[0-9]','[0-9]')
                        (default: M)

And the pe-layout for 'S','M','L','X1','X2' should be defined in config_pes.xml - but there are only a few defined at this time and there is no clarity around what each of these mean.   I would like to propose that we reduce the number of options here to 2 or 3 instead of 5 and that we find formal definitions for these target sizes in terms of cost vs performance.   

So for example 'S' might refer to a pe-layout that minimizes cost will performing at 25% maximum possible.  'M' might refer to 50% maximum performance and 'L' might refer to maximum performance where maximum performance is defined as the point where the slope of the cost vs performance curve is approximately 0.1 and we would drop the 'X1' and 'X2' values.

**Comment by rljacob** [comment]
Thoughts @azamat ?
