### ISSUE TITLE
allow comments in user_nl files 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1154]
I think that you used to be able to put comments in the user_nl_ files
using # at the beginning of the line.  This no longer appears to work.

**Comment by cacraigucar** [comment]
According to the book "Modern Fortran Explained" comments in namelists use the "!" character.  They may follow any object/name separator other than the slash.  Also a comment line which starts with ! is permitted, but it may not be within a character context.  On the web, I saw a reference that this was a part of Fortran95.

Namelists were extensions for years, and they varied by the machine.

**Comment by gold2718** [comment]
I agree with @cacraigucar that the exclamation mark is the Fortran standard. Close the issue?

**Comment by mvertens** [comment]
I agree. In fact comments with ! are already in place in the user_nl_files
and they are working fine.

**Comment by jedwards4b** [comment]
what can i say - I was tired.  Thanks for pointing out the problem.
