### ISSUE TITLE
Rename manage_case to query_config

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1155]
"manage" is for scripts that can edit xml files.  "query" just reads them.

"manage_case" in its current version only reads xml files so we should change its name to "query_case".

**Comment by gold2718** [comment]
Perhaps this should be merged with xmlquery into `case.query` (to match all the other case tools).
Then, `case.change` would be the tool for making case changes.

**Comment by jedwards4b** [comment]
We had a meeting on 1/30 with some of the scientists to explore requirements for the manage_case tool, I agree that it may be misnamed.  It is not a case tool but rather one you would use before creating a case.

**Comment by jedwards4b** [comment]
Renaming xmlquery and xmlchange would require extensive changes to external components, I'm not sure that's a good idea right now.

**Comment by gold2718** [comment]
Can you list which 'external components' are affected?
We could always make case.query and case.change and then deprecate xmlquery and xmlchange. The xml versions would print a warning and then call the new routine.
I think the time to put in place (and document) a consistent UI is before the release.
Leaving the (deprecated) xmlchange and xmlquery routines in place for a while will help users transition.

**Comment by rljacob** [comment]
@gold2718 please stop hijacking issues. :)

manage_case is available in cime/scripts.   xmlchange/xmlquery are only available to users after making a case.   I think we definitely want a config file query tool available to users before a case is built.  

Since the difference is one works with config.xml files while the other works with env.xml files maybe xmlchange/xmlquery should be envchange/envquery.

**Comment by gold2718** [comment]
Sorry, I guess this shows that all the tools are just a jumble in my head (more a property of my head than anything related to CIME).
I guess what I wanted is a discussion of the CIME UI in a unified context so we don't have to continually explain the weird command names and syntax (well, yeah that was --machine but this is --mach).
I would love to have a better tale to tell at this year's CESM tutorial.

**Comment by jedwards4b** [comment]
There is no longer a --mach option anyplace.

**Comment by rljacob** [comment]
Also "manage_case" with no arguments just returns and does nothing.  It should at least print the help string.

**Comment by rljacob** [comment]
I changed my mind.  This program should be called "query_config".  That's what its really querying.

**Comment by jedwards4b** [comment]
query_case is a confusing name since you don't already have a case when you call this - I thought @rljacob's suggestion of query_config was a good one.

**Comment by erichlf** [comment]
Damn! Did I mess that up? I will fix it.

**Comment by mvertens** [comment]
I agree.
