### ISSUE TITLE
Better detection of true machine at case.setup stage.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1161]
create_newcase will let you specify **any** machine with the --machine argument even if its not the one you're on.   If you then forget, because all your terminals look a like, and try to run case.setup on machineX for a case created on machineY, an error should be thrown.

This happened to me.  I created a case for anvil even though I was on my local laptop.  When I ran "case.setup", I got this unhelpful error:
ERROR: inputdata root is not a directory: "$din_loc_root"

**Comment by jedwards4b** [comment]
It's not always easy to determine what the correct machine is or should be.  For example there is no way to detect the difference between cori-haswell and cori-knl.   And sometimes you intentionally want to build on a different machine that is completely compatible with the one you've configured for - for example mira and cetus.   We can add a warning to the effect that you did not specify the machine I think you are on, but I think an error would be too strong.

**Comment by rljacob** [comment]
You're right.  The machine string can be anything and doesn't have to correspond with the host name or anything discoverable.  A warning would help.

**Comment by rljacob** [comment]
Maybe not even a warning.  Just an informative message like:  Machine name is X, hostname is Y"

**Comment by jgfouca** [comment]
@rljacob maybe the easiest thing here is to not use the --machine flag unless it's absolutely necessary? I would think in 99% of cases, a user would not need this flag, so there'd be no confusion when multiple terminals are open. I'm going to preliminarily close this ticket, feel free to reopen if you think that something needs to be done.

**Comment by rljacob** [comment]
I'm fine with closing the "detection" issue.  I'll open a new one for the informative message.

**Comment by jedwards4b** [comment]
The exception is those machines such as cori which have several architectures available.
Currently on cori we default to cori-haswell and require a machine flag to use cori-knl
