### ISSUE TITLE
Need new names for CIME's 2 types of test suite specifications.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1162]
(while we're talking about renaming things)

CIME supports two methods for specifying suites of tests: one xml-based and the other a python dictionary.   We've been calling these "acme" or "cesm" and conditionals are in create_test and other python scripts that reference those model names.   That practice doesn't fit CIME's model-neutral goals.   We need to refer to these two different methods in some other way in code and documentation.  Maybe "xml" and "pydict" ?

**Comment by mvertens** [comment]
I think that's a very good idea.

**Comment by rljacob** [comment]
Boosting the signal on this one.  @jgfouca @jedwards4b

**Comment by jgfouca** [comment]
Unintentional closure due to ACME merge.

**Comment by jgfouca** [comment]
Sorry @rljacob , never got this email. I don't have a strong opinion here. "XML-based" vs "python-based" tests. @billsacks suggested moving test files to model/component specific places.

**Comment by jgfouca** [comment]
@jedwards4b -> says to put something in configuration XML that says what kind of test method the model uses. config_component_acme TEST_STYLE=python?

**Comment by rljacob** [comment]
Ok but documentation like http://esmci.github.io/cime/users_guide/testing.html#using-create-test-acme needs to be re-written to talk about "python based" not "ACME".  And a similar document has to be written for CLM-based.
