### ISSUE TITLE
Should system tests have specific component lists?

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1171]
Both pem.py and ncr.py have specific component lists, e.g., 
`for comp in ['ATM','CPL','OCN','WAV','GLC','ICE','ROF','LND']:` in pem.py and
`for comp in ['ATM','OCN','WAV','GLC','ICE','ROF','LND']:` in ncr.py
The pem test should include ESP but I want to make sure there is no reason to not use `get_values("COMP_CLASSES")` with an exclusion for 'CPL' and 'ESP' in the ncr.py test.
Anyone?

**Comment by billsacks** [comment]
My understanding is that the tests were originally written with hard-coded lists, then migrated to use get_values("COMP_CLASSES") as they were gradually refactored. So my guess is that these remaining problems are just in tests that haven't been reviewed carefully. You mention nck in your comment, but that one is actually good as far as I can tell - though ncr still has the original hard-coded component list.

**Comment by gold2718** [comment]
Sorry, that was a typo, meant to be ncr.py as my example demonstrated.

**Comment by jedwards4b** [comment]
There is no reason that those can't use the get_values("COMP_CLASSES"), they just haven't been updated yet.

**Comment by gold2718** [comment]
I'll toss that change into my current ESP work (to fix ESP being ignored).

**Comment by gold2718** [comment]
Are these test types even tested by scripts_regression_tests? Do we need to add something?
I see a Yellowstone prealpha driver test for PEM.
I see an ACME prealpha and prebeta test that uses NCR (but I'm suspicious as it is for the T31_g37 grid which I doubt ACME is really interested in).

**Comment by jgfouca** [comment]
PR #1210 should have closed this ticket.
