### ISSUE TITLE
Add check on symbolic links in sourcemods directories when cloning

### ISSUE THREAD

**Issue by lvankampenhout** [ESMCI/cime#1175]
When working with SourceMods I tend to create symbolic links to various places, notably the sandbox from where the source originates. This is helpful for diffing code and for archiving purposes. When cloning a case these symbolic links are not re-created, instead, the folder to which it points is deepcopied. This could potentially lead to problems (disc space usage) when symlinking to very large directories. 

In my head, the solution would be to check for symbolic links in Sourcemods directories and threat these differently:
(1) no copy at all
(2) re-create symlink

**Comment by jedwards4b** [comment]
The intention of the SourceMods directory is to isolate changes so that they only affect a single case.  If you are making modifications in the source sandbox then you don't need to put files into the SourceMods directory at all.   If you copy links from one SourceMods to another and then edit the link you may unintentionally edit the initial experiment an unintended and perhaps dangerous result.

**Comment by billsacks** [comment]
Let me try to explain @lvankampenhout 's use case. Unlike what @jedwards4b is suggesting, he doesn't link directly to the source files he's changing. Rather, his SourceMods/src.clm directory looks like this:

```
-rw-r--r-- 1 lvank ncar 31303 Feb  3 08:56 atm2lndMod.F90
-rw-r--r-- 1 lvank ncar 45311 Feb  3 08:26 CanopyHydrologyMod.F90
-rw-r--r-- 1 lvank ncar 22918 Feb  3 07:33 clm_instMod.F90
-rw-r--r-- 1 lvank ncar 18362 Feb  3 08:57 clm_varcon.F90
-rw-r--r-- 1 lvank ncar 54415 Feb  3 07:47 EnergyFluxType.F90
-rw-r--r-- 1 lvank ncar 32382 Feb  3 08:44 initVerticalMod.F90
-rw-r--r-- 1 lvank ncar 38167 Feb  3 08:33 LakeHydrologyMod.F90
lrwxrwxrwx 1 lvank ncar    69 Feb  3 07:40 src -> /glade/u/home/lvank/cesm/cesm_tags2/clm4_5_14_r222/components/clm/src
-rw-r--r-- 1 lvank ncar 54799 Feb  3 07:20 WaterStateType.F90
```

Having worked with one of his cases, I agree that it's very useful to have that src symlink in there.

**Comment by lvankampenhout** [comment]
Thanks @billsacks for your explainer. I took a quick look at the commit that @bertinia did 2 days ago that referenced this issue, but it appears to be unrelated?
