### ISSUE TITLE
Group fortran code directory within src directory

### ISSUE THREAD

**Issue by agsalin** [ESMCI/cime#1178]
Breaking out discussion from #1150 

I propose a small clean-up of the top-level CIME dir by moving
    **externals, share, driver_cp, components**
within a directory called **src**. Also, the **buildlib.*** files for compiling these libraries will be moved from cime_config to src.

Regarding comments from #1150 

- I like the name "src" over "source" because it is commonly used for source code, such as in virtually all ACME (and presumably CESM) components like cam, clm, cice, mosart. 
- I don't think that CIME infrastructure source (i.e. python) belongs here. To me, there is a distinction between infrastructure source code and model source. common_model_source_code

**Comment by mvertens** [comment]
Jim and I would like to propose the following strawman for today's meeting.

~/CIME/src
==========================================
~/CIME/src/externals

~/CIME/src/share
~/CIME/src/share/include
~/CIME/src/share/shr
~/CIME/src/share/test
~/CIME/src/share/unit_test_stubs
~/CIME/src/share/esmf_wrf_timemgr
~/CIME/src/share/shr_RandNum
~/CIME/src/share/timing

~/CIME/src/components
~/CIME/src/components/data_comps
~/CIME/src/components/data_comps/datm/cime_config
~/CIME/src/components/stub_comps
~/CIME/src/components/xcpl_comps

~/CIME/src/drivers

~/CIME/src/drivers/mct
~/CIME/src/drivers/mct/driver
~/CIME/src/drivers/mct/shr    -> this code could be in share/ - but its
driver specific share code
~/CIME/src/drivers/mct/unit_test
~/CIME/src/drivers/mct/cime_config

~/CIME/src/drivers/nuopc
~/CIME/src/drivers/nuopc/driver
~/CIME/src/drivers/nuopc/shr    -> this code could be in share/ - but its
driver specific share code
~/CIME/src/drivers/nuopc/unit_test
~/CIME/src/drivers/nuopc/cime_config


~/CIME/config (replace ~/CIME/cime_config)
==========================================
~/CIME/config/cesm
~/CIME/config/acme

~/CIME/scripts
==========================================
~/CIME/scripts/Tools  <===== this needs to stay (needed by CESM active
comps)

~/CIME/utils -> ~/CIME/case_control
==========================================
Anything that is not perl can be moved - what do we want to call this?

~/CIME/tools
==========================================

~/CIME/utils/perl5lib  <==== this needs to stay (needed by CESM active
comps)
==========================================

**Comment by rljacob** [comment]
From discussion on telecon.  Changes to above:
/CIME/src/drivers/mct/driver -> /CIME/src/drivers/mct/main
/CIME/src/share/shr -> ~/CIME/src/share/util
/CIME/src/share/shr_RandNum -> ~/CIME/src/share/RandNum
