### ISSUE TITLE
Add test for S-case

### ISSUE THREAD

**Issue by agsalin** [ESMCI/cime#1179]
I noticed there was no tests for S (stub-only) compset, even though it is supported. A discussion on slack showed agreement that we should add a test as opposed to removing the compset.

I have 2 questions:
1. Is adding the test to cime_developer test suite within update_acme_tests.py sufficient to have this tested? I see cime_developer within scripts_regression_tests script and believe this is what gets tested.
2. What grid should I use? I tried  SMS.T42_T42.S  and that worked, since I noticed T42_T42 worked with Stub compset. However, I have little clue if there is a better grid or test type choice.

**Comment by jedwards4b** [comment]
Yes adding the test to cime_developer is sufficient. 

An S test does almost nothing and doesn't care about grids T42_T42 should be fine.
