### ISSUE TITLE
Change arguments and behavior of "manage_case"

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1190]
I'm trying to write some documentation on using "manage_case" but don't really want to in its current form.  There is already issue #1155 for changing its name.  This issue is for other behavior.

1.  ./manage_case with no arguments quietly returns nothing.  It should print the help string instead.
2.  --query-compsets-setby  should be changed to just --compset.  This assumes the name is changed to "query_case". or "query_config"  The "setby" can be explained in the help.
3. --query-compsets-setby with no arguments gives an unhelpful error message that it "expects one argument".  If you supply it with on argument, but the wrong one, you get a more helpful error message listing all the valid options.  No arguments should provide the same error as invalid arguments.
4.  --query-compsets-setby should allow an "all" option that prints all the compsets it can find.
5. --query-compset-setby should not print the compset naming convention with every invocation.
6.  --query-component-name, similarly should just be --component
7.  --query-component-name has the same error message behavior as --query-compsets-setby
8.  --query-grids,  should just be --grids
9.  --grids-shortname and --grids-alias are "not implemented yet".  What are these supposed to do?
10.  --query-machines should just be --machines
11.   --query-machines should include in its output if cime knows the current platform.  Optional argument "current" would only print info about the current machine.
12. The --long additional argument only seems to do anything with --query-grids

**Comment by billsacks** [comment]
A number of us at NCAR had a discussion on this tool a few weeks ago, but we neglected to open an issue documenting this. Specifically, this was a meeting with @mvertens @jedwards4b , Keith Oleson, Dave Bailey, Cecile Hannay and myself. The point was to gather requirements and suggestions from some of the CESM science liaisons. Here are my notes from that meeting (with apologies that they're kind of rough):

• What do you (and other users) want to be able to query?

Jim: Can we start with a list of available compsets, showing which are scientifically supported, and showing which grids are scientifically or test supported for each compset?

e.g.,:

```
B1850
    f09_g16
    f19_g16
```

Dave also wants to be able to subset on compset (with --compset)

If you just want to list F compsets, how should you do that?
* Specify allactive, cam, etc. as primary component?
* Cecile prefers that you specify first letter (B, F, I)
    * Accompanied with some help saying what are the available first letters to query on - e.g.:
        * F means XXX
        * I means YYY
    * If you don't specify a letter, it means give me all compsets
* What about something like B1850*
    * Mariana points out that then we're relying on aliases, which she wants to get away from
    * But does something like a wildcard match require you know stuff to begin with that this tool is trying to make it so you don't have to know?

Note that there isn't necessarily a way to query the system on all the available grids for a given compset (you can query the tested grids for a given compset).

• Do you want to see support level (scientifically supported, etc.)?
* If so, do you want to be able to query on combinations of compsets & grids?

• How do you want the information presented?

Dave: Having output to help you craft the create_newcase command would be useful... but maybe not do this for now

• What is the best user interface to this tool?
* Separate tool vs a -list option to create_newcase
* What would the command line options look like?

Dave likes the idea of having a tool to help you before you try to craft a create_newcase command

People like having a separate tool

• Do we want this sort of information on the web?

Mariana has reservations with having this on the web

Jim: Can we automate the generation of the web information?

Dave: Benefit of having it on the web, but don't need to update it too often
* e.g., For someone who hasn't even downloaded the code yet

Cecile echoes Dave's comments – useful to have some information on the web, but more detailed information available in a more complex way.

Cecile uses this:

http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/modelnl/compsets.html

(though she rarely uses the pop-up info)

So we could list the supported compsets, with long name, alias, and supported grids

**Comment by cacraigucar** [comment]
I would like the ability to organize the order that --query-component-name returns its information.

When I did "./manage_case --query-component-name cam"  I get a list of the CAM naming conventions.  As far as I can tell, there is no order to this list.  I want the ability to group "like" descriptions together.  For instance CAM40, CAM50 and CAM60 which are most important are scattered throughout the list.   If it were to return the order that they are listed in the description in config_components.xml, that would be one solution.  It would nice if we could insert a blank line as well, but this is less important.

**Comment by rljacob** [comment]
@mfdeakin how far along are you on this?  I'd like to give it to @erichlf since he's already doing the rename.

**Comment by mfdeakin-sandia** [comment]
I've barely started; so feel free to give it to @erichlf

**Comment by rljacob** [comment]
Ok.  I'm going to give you one of Jim's.

**Comment by erichlf** [comment]
@rljacob I don't think I understand point 5.

**Comment by erichlf** [comment]
@rljacob One issue I have come across while attempting to add an "all" option for --compsets is that I can't seem to figure out how to make the script model aware. I certainly can get he model from utils.py, but then I can't figure out how to specify the components to print. There are different component xmls, but how do I specify this in 
`files.get_components("COMPSETS_SPEC_FILE")`

**Comment by jedwards4b** [comment]
CIME.utils.get_model()

**Comment by erichlf** [comment]
@jedwards4b I knew that part, but it then how do I specify which components to list?
`files.get_components("COMPSETS_SPEC_FILE")`
lists all components no matter the model.

**Comment by jedwards4b** [comment]
No it doesn't - files is already model dependent so you are reading COMPSETS_SPEC_FILE from
config/acme/config_files.xml and you are going to read the list of components in that file,  you don't have a case so you don't have enough information to refine it any further than that.

**Comment by jedwards4b** [comment]
If you have clm and pop in that file it's not because they need to be there, rather it's because you need to clean it up.

**Comment by erichlf** [comment]
@jedwards4b I am getting errors while trying to find cism.

> Cannot find config_file /home/elfost/workspace/ACME/cime/../components/cism/cime_config/config_compsets.xml on disk

**Comment by jedwards4b** [comment]
Two chooses, one - clean up your config_files.xml to reflect the components in acme
two - check to see if each file exists and don't try to read it if it isn't there. 

I think I would do both.

**Comment by erichlf** [comment]
Okay, but this isn't just for me, so it probably would be a good idea to report an error when a config isn't found.

**Comment by jedwards4b** [comment]
A warning sure but not an error - I think that it's possible that there will be optional components listed in config_files but only available to  a subset of cime users.

**Comment by rljacob** [comment]
If you're running this out of standalone cime, most of the compset files pointed to by config_files won't be available.  query_config should handle that gracefully.

**Comment by rljacob** [comment]
Item 4 said "--query-compsets-setby should allow an "all" option that prints all the compsets it can find."   keywords are "it can find" so if you only have cime standalone checked out or you have the ACME code but have defined the model to be CESM, then "all" will print a short list of compsets.  You could also print out the current value of cime_model to help.

**Comment by rljacob** [comment]
Re item 5.  If I do "./manage_case --query-compsets-setby drv" I first get a big block of code that starts:
```
    =========================================
    compset naming convention
    =========================================
    The compset longname below has the specified order
    atm, lnd, ice, ocn, river, glc wave esp cesm-options

    The notation for the compset longname below is
    TIME_ATM[%phys]_LND[%phys]_ICE[%phys]_OCN[%phys]_ROF[%phys]_GLC[%phys]_WAV[%phys][_ESP][_BGC%phys]
```
and then another 15-20 lines before I get the info I want.  Don't print that block about the compset naming convention.  I can look that up in our excellent online documentation.
