### ISSUE TITLE
PIO settings not adjusted with pe changes 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1192]
Currently both PIO_STRIDE and PIO_NUMTASKS is set at create_newcase time based on the NTASKS value.   But if NTASKS is changed the PIO settings are not - this can lead to some pathologically poor IO configurations.   I propose adjusting the pio settings upon running case.setup. Since users may not always want the pio settings adjusted for them I propose an additional command line argument to case.setup --no-adjust-pio

**Comment by gold2718** [comment]
Is there a call I can add to the pelayout tool to reset the PIO vars when it changes task counts?

**Comment by jedwards4b** [comment]
@gold2718: It happens in case.setup which is outside the scope of the pelayout tool.
