### ISSUE TITLE
GPTL Licensing

### ISSUE THREAD

**Issue by agsalin** [ESMCI/cime#1211]
(Everyone's least favorite topic)

GPTL has a file called COPYING that declares it to have a GPL license. This license is a problem, since it requires all codes that use the library to also use GPL. It is viral. The last paragraph of the license in that file even says: don't use this license for subroutine libraries. 

Who owns GPTL? Is there someone who could get us a version without this license, or a note saying it is no longer covered by this license, so we can remove it? 

gptl appears 3 times currently: share/timing and in each of the PIOs.

**Comment by jedwards4b** [comment]
GPTL is http://jmrosinski.github.io/GPTL/

**Comment by gold2718** [comment]
That page includes the text:
"... that you don't embed GPTL library source in software that you intend to sell. "
As government-funded workers, are we allowed to say that in our code? 
Also, it seems that this statement is in contradiction to the GPL which is not against selling, just against not making the source code available.

**Comment by agsalin** [comment]
An Update: I talked to SNL lawyers who said that the GPL license of GPTL is the bad viral version that asks all software it gets incorporated into to also be GPL. 

I wrote Jim Rosinski explaining the issue and asking him to consider changing it to BSD like CIME.

**Comment by agsalin** [comment]
@bertinia @jedwards4b @rljacob @mvertens 

I went ahead and replaced the COPYING license file in 3 occurrences of GPTL to use the new license. I attached the email chain in the commit log to document that we had Jim Kosinski's permission.

I forgot to create a branch, so ended up pushing this directly to master. We had discussed this pretty thoroughly through emails already, so I think I can just leave it on master. So, I'm using this issue on the topic in place of a PR screen. 

Jim -- this may be an issue if you periodically bring in external PIO directories, that you may end up reverting this fix. I don't know your workflow for PIO. 

Any concerns? Thanks.

**Comment by jedwards4b** [comment]
We will add this back to PIO before the next merge.  Thanks
