### ISSUE TITLE
README.case does not echo create_test command line

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1214]
This was a problem in prior versions and seems to have crept back in with the lastest revision.
Also, lots of extra newlines in README.case.

**Comment by jedwards4b** [comment]
It's still there but because of the workflow is not the first line of the file.
Look for "Case Created using"

**Comment by apcraig** [comment]
OK, thanks.  I see it now.  Sort of odd that it's not the first line, but that's fine.  As long as we know where to look for it.
