### ISSUE TITLE
Unable to set info_debug in the coupler namelist for tests

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1216]
When I setup a test, I no longer have control of the info_debug namelist in the driver.

It used to be (years ago) that I could setup an SMS test, set INFO_DBUG to 2 in env_run.xml, and the driver would then run with info_debug set to 2 for any test.

Then a couple years ago, I could no longer set INFO_DBUG to 2 in env_run because the SMS test automatically reset it to 1 when it ran.  But I could force info_debug to 2 by setting that value in user_nl_cpl.  I wasn't a fan of this implementation but at least could work around it.

As of today, setting info_debug to 2 in user_nl_cpl for an SMS test produces

"ERROR: Cannot change info_debug in user_nl_xxx file, INFO_DBUG"

when I submit.  So I no longer have control of the info_debug namelist setting.  My feeling has always been that the tests should NOT overwrite a user change like this in the env_ settings.  There are some settings that the test has to change (like run length, restart info, etc in ERS tests), but there is other info that a user should be able to change (like INFO_DBUG).

Anyway, there seems to be some conflicting logic with regard to NOT allowing users to set namelist that are set via env_*.xml files and the fact that tests overwrite a number of env_*.xml values as it runs, thereby overwriting values that users might have set.

**Comment by jedwards4b** [comment]
The trick is to change INFO_DBUG in env_test.xml here is an example of that file from an ERS test
```
  <test NAME="ERS">
    <DESC>exact restart from startup, default 6 days + 5 days</DESC>
    <INFO_DBUG>1</INFO_DBUG>
    <STOP_OPTION>ndays</STOP_OPTION>
    <STOP_N>11</STOP_N>
    <REST_N>$STOP_N / 2 + 1</REST_N>
    <REST_OPTION>$STOP_OPTION</REST_OPTION>
    <HIST_N>$STOP_N</HIST_N>
    <HIST_OPTION>$STOP_OPTION</HIST_OPTION>
    <DOUT_S>FALSE</DOUT_S>
    <CONTINUE_RUN>FALSE</CONTINUE_RUN>
  </test>
```

**Comment by apcraig** [comment]
That's a pretty tricky way to do this.  It will be hard for users to know whether to use values in env_test or env_run.  But, at least there is now a way to change the settings.  thanks.

**Comment by gold2718** [comment]
'Pretty tricky' is an understatement IMHO. If the only way to effectively change the variable is by changing the copy in env_test.xml then xmlchange should change it there and xmlquery should show that version.

**Comment by jedwards4b** [comment]
The point of this file is to save parameters that must be reset to an initial value at the start of the test.   I believe that it should require expert level usage to override this feature. @gold2718's suggestion that xmlquery and xmlchange be allowed to operate on this file undermines its purpose.

**Comment by gold2718** [comment]
@jedwards4b, could you define 'expert' in this context? Isn't entire affected community folks using `./create_test` so already reasonably expert?
If the file is not supposed to be changed (since changing it 'undermines its purpose'), why is it copied into the test directory?
Currently, `xmlquery` and `xmlchange` only operate on the `INFO_DBUG` in env_run.xml. What is surprising is that the following command:
`./xmlchange --file env_test.xml INFO_DBUG=3`
silently sets the `INFO_DBUG` in env_run.xml (I filed a bug for that).
Can the documentation be updated to say that env_test.xml does not follow the rest of the CIME convention (encouraging `xmlquery` and `xmlchange` over raw editing)?
Can others (@mvertens, @rljacob, @jgfouca) provide an opinion?

**Comment by jedwards4b** [comment]
I would like xmlchange and xmlquery to work on all case xml files.

**Comment by gold2718** [comment]
Mr. thick here. env_test.xml is in the case directory. Is it not a case xml file?

**Comment by jedwards4b** [comment]
It is.  I don't want anyone to need to hand edit any of those files, I'm working on it.
