### ISSUE TITLE
Driver allows a contradiction in drv_flds_in between CAM and CLM

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1217]
I assume this goes back to the beginning of CIME5, but I know this was nicely working in CIME4.

I expect that if the drv_flds_in namelist created by CAM and CLM contradict each other, that the driver will point out the contradiction when preview_namelist is run. If the namelists are empty for either one, there is no contradiction, and if they both set a namelist item to the same value -- there's no contradiction either. But, if one sets something one way and the other to something else -- the driver should point out the contradiction. The driver build namelist should try to merge the drv_flds_in namelists created by components, and only die if the two are set differently.

An example of what I expect to NOT work is the following, where I contradict the drv_flds_in namelist between CAM and CLM.

./create_test SMS_D.f10_f10.FW2000.yellowstone_intel.clm-fire_emis -n --compare cesm2_0_alpha06d -r . --no-build
cd $CASENAME
./xmlchange CLM_BLDNML_OPTS="-fire_emis -bgc bgc -megan -drydep"
./preview_namelist

I expect it to die on preview_namelist and tell me that CAM and CLM are contradicting each other, and what namelist items were set differently.

**Comment by ekluzek** [comment]
This is with cime5.3.0-alpha.02 in current cesm2_0_alpha06 branch which is being setup for cesm2_0_alpha06f, but 06f hasn't been created yet.

**Comment by gold2718** [comment]
A test for this should be added to scripts_regression_test.py to avoid this sort of regression in the future.

**Comment by jedwards4b** [comment]
This is cam and clm and therefore outside the scope of scripts_regression_tests.py

**Comment by mvertens** [comment]
I think the point is that we should add a CESM test not a CIME test for
this.

**Comment by ekluzek** [comment]
I'm not sure if it's a CESM test or not. Does ACME not use drv_flds_in at all?

The point of this test is for the driver to make sure that when it assembles the drv_flds_in files from any components -- that they don't contradict each other. That's clearly a driver functionality, and not something we can test in CAM or CLM.
