### ISSUE TITLE
Tagapalooza

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1221]
There are currently 455 tags in ESMCI/CIME with 143 of them apparently PIO tags. Are these really CIME tags or were they brought in accidentally with merges from PIO? Can we remove them?
What about tags like **2.0.0**, does that mean anything?
Also, tags like **cesm-master** seem out of place.

**Comment by jedwards4b** [comment]
The pio tags come in because of the weird way that subtree merge works - but really is there a problem with having too many tags?

**Comment by gold2718** [comment]
Well, github will only show 100 tags but my main concern is confusion in that checkout of out a random PIO tag will not mean anything. If our tags are not meaningful or if meaning is random, they cease to be useful.

**Comment by rljacob** [comment]
I'd like to see most non-CIME tags deleted.

**Comment by gold2718** [comment]
How about we start with the ones I mentioned above (pio*, naked numerical tags, cesm*)?

**Comment by jedwards4b** [comment]
I have deleted all of the pio tags - here is a list of additional tags I think should be removed.


git tag --delete 2.0.0
git tag --delete 2.0.1
git tag --delete 2.0.2
git tag --delete cam_topographic_height_n01
git tag --delete cam_topographic_height_n02
git tag --delete cesm-master
git tag --delete cime-workflow-exp-rc01
git tag --delete cime-workflow-exp0.0.1
git tag --delete clm4_5_11_r188_cime4.5.14
git tag --delete clm4_5_12_r198_cime5.2.0-alpha.1-9-gd321e4b
git tag --delete clm4_5_8_r180_cime4.5.14
git tag --delete diurnal_n00_cime0.3.34
git tag --delete diurnal_n01_cime0.3.34
git tag --delete fire01_cime1.1.8
git tag --delete fv3_01
git tag --delete gswp3drvflds_n01_cime4.6.0
git tag --delete gswp3drvflds_n02_cime4.5.14
git tag --delete gswp3drvflds_n03_cime4.5.14
git tag --delete irrig_as_fraction_cime5_n01
git tag --delete irrig_as_fraction_cime5_n02
git tag --delete irrig_as_fraction_cime5_n03
git tag --delete irrig_as_fraction_cime5_n04
git tag --delete irrig_as_fraction_cime5_n05
git tag --delete irrig_as_fraction_n01
git tag --delete irrig_as_fraction_n02
git tag --delete irrig_as_fraction_n03
git tag --delete irrig_as_fraction_n04
git tag --delete irrig_as_fraction_n05
git tag --delete mcog_klindsay_01_cime4.1.2
git tag --delete mcog_klindsay_02_cime4.1.2
git tag --delete mcog_klindsay_03_cime4.1.2
git tag --delete mosart_n00_cime0.3.34
git tag --delete mosart_n01_cime0.3.34
git tag --delete mosart_n01_cime3.0.7p
git tag --delete mosart_n02_cime0.3.34
git tag --delete mosart_n03_cime0.3.34
git tag --delete move_glint_to_cpl2_n01
git tag --delete move_glint_to_cpl2_n02
git tag --delete setpes_cime1.0.0
git tag --delete simple_models0.1.0
git tag --delete strm4d_n00_cime1.1.16
git tag --delete waccm5.5_n01_cime2.0.17-p1.1
git tag --delete waccm5.5_n02_cime2.0.17-p1.1
git tag --delete wave01_cime0.3.34
git tag --delete wave02_cime0.3.34
git tag --delete wave03_cime3.0.5
git tag --delete wcm01_cime4.0.4
git tag --delete wcm02_cime4.0.4

**Comment by gold2718** [comment]
Great, how about
move_glint_to_cpl2_n01
move_glint_to_cpl2_n02
