### ISSUE TITLE
All component builds mislabeled as 'clm builds'

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#1223]
All component builds are labeled as clm builds. 
```
Component csm_share build complete with 3 warnings
         - Building clm Library 
Building atm with output to /homes/jayesh/acme/scratch/test_X_f19_g16/bld/atm.bldlog.170309-084354
         - Building clm Library 
Building lnd with output to /homes/jayesh/acme/scratch/test_X_f19_g16/bld/lnd.bldlog.170309-084354
...
```
I tried it on anlworkstation with master (cime5.3.0-alpha.02-9-g5f4f989) but should be an issue on other systems too.

**Comment by jayeshkrishna** [comment]
Looks like the bug is in build.py@line:41 at
```
        else:
            logger.info("         - Building clm Library ")


```

**Comment by jayeshkrishna** [comment]
This patch should fix the problem,
```
diff --git a/scripts/lib/CIME/build.py b/scripts/lib/CIME/build.py
index 3bbf2c1..6aa1be8 100644
--- a/scripts/lib/CIME/build.py
+++ b/scripts/lib/CIME/build.py
@@ -38,7 +38,7 @@ def _build_model(build_threaded, exeroot, clm_config_opts, incroot, comp
                 else:
                     continue
         else:
-            logger.info("         - Building clm Library ")
+            logger.info("         - Building %s Library ", model)
 
         smp = nthrds > 1 or build_threaded

```

**Comment by jayeshkrishna** [comment]
@jgfouca : Is this the right fix?

**Comment by jgfouca** [comment]
@jayeshkrishna , yes, putting it in now.

**Comment by rljacob** [comment]
You could also put this in the cime5.2.0 branch in ACME.  Otherwise we'll have to live with it there for a while.

**Comment by ekluzek** [comment]
As a CLM developer who is pretty much always only building CLM, I have to say I find this bug  humorous.  It sounds like you've discovered the evil plot of the CLM group to rule the world! Go CLM! And yes I am being sarcastic! ;-)

**Comment by rljacob** [comment]
The comment for that message says:
```
# special case for clm
# clm 4_0 is not a shared library and must be built here
# clm 4_5 and newer is a shared library (but not in ACME) and should be built in build_libraries
```
Should the message be more specific?  All the components are built as libraries after all.  And when the clm build is shared, who is it shared by?

**Comment by jedwards4b** [comment]
It's shared by multiple tests.
