### ISSUE TITLE
Allow users to set pio rearranger options in PIO2

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#1224]
Currently users can only set the pio rearranger options in PIO1.
Since the latest version of PIO2 in CIME has support for setting
rearranger options we need to modify the CIME framework to
allow users to set these options for PIO2.

**Comment by jedwards4b** [comment]
I believe that the only thing that needs to be done to accomplish this is to remove the
#ifdef PIO1 blocks and have pio2 call with the same args as PIO1 in shr_pio_mod.F90

**Comment by jayeshkrishna** [comment]
Yes, and some minor modifs in the script to expose the options.

**Comment by jayeshkrishna** [comment]
Looks like as @jedwards4b mentioned we only need to modify shr_pio_mod.F90 with the latest CIME (older CIME required modifications to expose the rearranger options for pio2)

**Comment by jayeshkrishna** [comment]
PR coming soon
