### ISSUE TITLE
CIME support for workaround for Titan node failures

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#1233]
I'm requesting CIME support for a run-script workaround for frequent node failures on Titan described in the link below in which we allocate more nodes than necessary for the job and put a loop around the aprun command, re-launching when failure occurs as it kicks out the bad node(s).

https://www.olcf.ornl.gov/kb_articles/aprun-tips/#nodefailures

Mark brought up the issue, so I'll tag him if he wants to give more information or tag it as critical: @mt5555

**Comment by rljacob** [comment]
So if aprun fails and you just re-run, during the same batch submission, the batch system is smart enough to exclude the nodes that failed?

**Comment by mrnorman** [comment]
So they say

**Comment by rljacob** [comment]
One thing this would need that CIME doesn't have is a "clean up and start over" command.   If the run dies and you're going to restart it from the same point, there are log files and partially complete history files that need to be removed.  I think this is usually left to the user.

**Comment by ndkeen** [comment]
I could create another issue, but I think _in general_ the opaqueness of the new cime way of interfacing with batch system is difficult.  It might be nice to have the system write a separate batch file that includes everything one needs to submit so that we can use it for special purposes?

**Comment by jedwards4b** [comment]
@mrnorman How do you distinguish between node failures and other types of model failure for which you may not want to loop?

**Comment by mrnorman** [comment]
I have the same question, let me get back to you on that.

**Comment by mrnorman** [comment]
In the meantime, @mt5555 and @worleyph, who was reporting the node failure issues? I could take a look at their output and see if there's a reliable way to guess that it's a node failure so we don't cycle the whole time away on a bug.

**Comment by vanroekel** [comment]
@mrnorman that would be me recently with the node failures.  I have a page with the failure message from all outputs if you'd like to look.
```
https://acme-climate.atlassian.net/wiki/display/OCNICE/GMPAS-IAF_oRRS18to6v3
```

True node failures always seem to have this string in acme.log
```
Received node event ec_node
```

My run directory on titan is also listed on the confluence page if you'd like to look.  Permissions should be set okay.  let me know if they are not.

**Comment by rljacob** [comment]
Not everyone here has read permissions on acme-climate.  The messages look like this:
` [NID 07360] 2017-03-04 19:15:37 Apid 13867310 killed. Received node event ec_node_halt for nid 7361`
Run directory:  /lustre/atlas1/cli115/scratch/vanroek/GMPAS-IAF_oRRS18to6v3/run

**Comment by vanroekel** [comment]
sorry for that.  I've moved all log files from the runs to 
/lustre/atlas1/cli115/world-shared/vanroekel

The job ids for node failures are 3250856, 3253427, 3265788, and 3268461.  There are also a few non-node failures too for comparison 3255937, and 3249807

If it would be useful to add more to world-shared, let me know.

**Comment by mvertens** [comment]
I think that the short term archiver could provide this clean up and then
start over would happen from the last consistent restart set created by the
short term archiver. Recently, I re-implemented short term archiving to
ensure that both ACME and CESM can easily specify what files need to be
archived and the necessary history files that are needed upon restart are
also consistently archived. In addition, short term archiving is done on
intermediate restart files as well (this was not the case before). So if
you are running for 1 year and ask short term archiving to be done every
month and then your model dies in the middle of the 5th month - part of
resuming should be to run the short term archiving and then restart from
the last consistent set of restart files that were generated. This has not
been incorporated flexibly into CIME - but I think that is the right
approach.

**Comment by jedwards4b** [comment]
Currently we use run_cmd_no_fail to run the model executable - this will always cause an abort on non-zero exit status of the model and so will need to be changed to run_cmd and the status and log files checked explicitly.    @mvertens correctly points out that the st_archive script can be used to straighten out the run directory before a new run is started however, st_archive normally runs as a separate job.    There is also the issue of submitting to more tasks than the model is going to use and having the model aprun use the correct number.    I think that you can do this by simply changing the directive in config_batch.xml
``` <directive>-l nodes={{ num_nodes }} + number_of_extra_nodes </directive> ```

So you need to change the run_cmd_no_fail to run_cmd, loop over that run_cmd and if the exit status is non-zero look for the string ec_node_failed if the string matches run case_starchive and then run_cmd again.

**Comment by rljacob** [comment]
This is becoming high-priority need for running on Titan.  Jim will be working on it.
