### ISSUE TITLE
New runoff -> ocean map

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1243]
Using the estuary box model means that POP has a new way of handling liquid runoff in the open ocean -- it now wants a nearest neighbor map instead of the smoothed map. POP still requires the smooth map for runoff in the marginal seas, though (and the ice runoff to ocean should be smoothed globally).

@klindsay wrote an NCL script that takes the runoff -> ocean nearest neighbor map, runoff -> ocean smooth map, and POP region mask files as inputs and combines the two as desired. I will add that NCL script and a bash wrapper in the same pull request that handles #1241 but will leave this ticket open because a better long-term solution is to add the ability to combine maps in this fashion to the Fortran code that produces the map that uses smoothing globally.

**Comment by rljacob** [comment]
Is this finished @mnlevy1981 ?

**Comment by billsacks** [comment]
I see that #1280 fixed this
