### ISSUE TITLE
New option for ERS tests?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1244]
Right now, if you run an ERS_Ld5 test then CIME does the following:

1. Run for 5 days, writing restart file after day 3
1. Go back to the day 3 restart file, run for 2 days (days 4 & 5)
1. Compare the output from step 1 and step 2

I'd like an option to run the test in the following manner:

1. Run for 5 days without writing a restart file
1. Run for 3 days (days 1 - 3) and write a restart file at the end of the run
1. Continue the run for 2 days (days 4 & 5)
1. Compare the output from step 1 and step 3

It is extra work (initializing the model three times instead of twice and running an additional three days), but POP has a "feature" where writing a restart history file changes the eventual history file<sup>1</sup> that is written... so if we have a test that computes 5-day averages for tavg output then the current version of the ERS test will `PASS` and the proposed option will `FAIL`. Having a test that fails in this situation would be handy for when we fix this feature.

<sup>1</sup> Two notes... the change in the history file is round-off level, so it isn't terrible that the test currently passes. Also, the change is due to the fact that the POP restart history file is a normalized version of the accumulation buffer so writing a restart file normalizes the buffer, writes it, and then denormalizes it (hence the pass -- in the current test step 1 denormalizes the buffer after _writing_ the restart and step 2 denormalizes it in an identical fashion after _reading_ the restart). The proposed fix to POP is to write the denormalized buffer into the restart history file.

**Comment by gold2718** [comment]
My vote would be to make @mnlevy1981's 'option' the default usage. I've always been a bit suspicious that the current ERS test properly tests normal CESM restart usage.
