### ISSUE TITLE
Always set core dump size to unlimited in case.run

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1247]
The case.run script should always have the following in it:
```
import resource
resource.setrlimit(resource.RLIMIT_CORE, (resource.RLIM_INFINITY, resource.RLIM_INFINITY))
```

This is equivalent to `ulimit -c unlimited` in the old csh scripts.

**Comment by rljacob** [comment]
@jgfouca came up with those lines for @mrnorman to use by editing his run script but I think the should always be there.

**Comment by mrnorman** [comment]
Note that when I added those to the beginning of main in case.run, I got an error

**Comment by rljacob** [comment]
Updated above with correct code.

**Comment by rljacob** [comment]
@mrnorman does it work with the corrected syntax?

**Comment by rljacob** [comment]
Matt has verified this works.  We'd like to add this to all case.run scripts.

**Comment by mvertens** [comment]
This sounds fine with me.

**Comment by jgfouca** [comment]
Complete on the ACME side.

**Comment by jgfouca** [comment]
This is now merged.
