### ISSUE TITLE
CIME5 user_nl scripts do not recognize array elements

### ISSUE THREAD

**Issue by jonbob** [ESMCI/cime#1248]
In CIME2, we could enter array elements in user_nl and have those changes picked up by the scripts. In CIME5, that no longer works. As an example, we change one array element in user_nl_datm:
   `tintalgo(3) = ‘coszen’`
That has always worked, but in CIME5 we get the following error:
   `ERROR: Error in parsing namelist: 'tintalgo(3)' is not a valid variable name at line 5, column 11`
It does work if we set the entire array, i.e.:
   `tintalgo = "linear", "linear", "coszen", "linear", "linear", "linear", "linear", "linear", "linear", "linear", "linear", “linear"`
but this seems like an unnecessary loss of functionality.

Note: this is also being tracked in [ACME-Climate/ACME #1311](https://github.com/ACME-Climate/ACME/issues/1311)

**Comment by mvertens** [comment]
So it would be useful to determine if we have implemented all the functionality that is in
perl5lib/Build/Namelist.pm. I thought that Sean had implemented all of this functionality - but it seems that this is not the case. Looking here we might be able to average some of the key features that are missing in here and in #1267 .

#-----------------------------------------------------------------------------------------------
# Perl regular expressions to match Fortran namelist tokens.

# Variable names.
# % for derived types, () for arrays
#my $varmatch = "[A-Za-z_]{1,31}[A-Za-z0-9_]{0,30}[(0-9)%a-zA-Z_]*";
......

**Comment by jedwards4b** [comment]
What key feature do you think is missing from #1267?
