### ISSUE TITLE
Fortran unit test infrastructure doesn't define USE_CONTIGUOUS

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1250]
(This isn't critical, because currently CAM developers don't rely on these unit tests; it would be good to fix eventually, but doesn't have to happen immediately.)

With the latest cime, the following CAM Fortran unit tests fail to build: `coords_1d`, `vdiff_lu_solver`  - both fail in building `components/cam/src/utils/coords_1d.F90`, with an error like this:

```
/glade/u/home/cacraig/cam5_4_115-TRUNK/components/cam/src/utils/coords_1d.F90(51): error #5082: Syntax error, found IDENTIFIER 'INTENT' when expecting one of: ( :: , [ /
  real(r8), USE_CONTIGUOUS intent(in) :: ifc(:,:)
---------------------------^
```

It looks like the problem is that the USE_CONTIGUOUS cpp token isn't getting defined in a CMake build.

I see that this is set in the Makefile for a system build, and also see that there's some code in `tools/unit_testing/python/machine_setup.py` that looks like it's supposed to set USE_CONTIGUOUS, but maybe the relevant python code is no longer getting invoked? I don't see any references to USE_CONTIGUOUS in the Macros.cmake file that gets generated when doing the unit test build.

cc @jedwards4b @cacraigucar

**Comment by billsacks** [comment]
Temporary workaround: when running run_tests.py, add this option:

```
--cmake-args ' -DCPPDEFS=-DUSE_CONTIGUOUS=contiguous,'
```

**Comment by jedwards4b** [comment]
The flag in Macros.cmake is   HAS_F2008_CONTIGUOUS note that intel17 on cheyenne needs
set(HAS_F2008_CONTIGUOUS "FALSE")

**Comment by jgfouca** [comment]
@asteyer , we assigned to you since you're working on the Cmake stuff. Just something to think about.

**Comment by billsacks** [comment]
Closing since this doesn't seem to be causing problems in practice.
