### ISSUE TITLE
Queue selection in env_batch is not adequate for blues

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1255]
Some background: blues has two available queues, "shared" and "batch". The shared queue will throw an error if you try to submit a job and request more than an hour of runtime. The "shared" queue will accept num cores 1-64, the "batch" queue will accept 1-thousands. My problem is that we have a lot of tests that take 64 cores (fit in either queue), but some take three hours and some take one. env_batch.select_best_queue seems unable to select the appropriate queue for such jobs (1 hour or less should go to "shared" and the others should go to "batch"), instead it just selects "shared" for everything.

**Comment by rljacob** [comment]
More info on blues:  you can't directly submit to the "batch" queue.  Adding "-q batch" will get your job rejected.  For regular jobs, it figures out where to route you based on nodes and time requested.   Only if you want a different queue, like "shared", then you have to use the "-q" option.

**Comment by jgfouca** [comment]
@rljacob that's been fixed on the ACME side via python hack.

**Comment by jgfouca** [comment]
Had  a request come in on the ACME side so I'll take this.
