### ISSUE TITLE
Remake all glc to ocean mapping files

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1262]
Due to #1241 , we should remake all glc to ocean mapping files.

**Comment by mvertens** [comment]
We need to alert JF and Cecile about this - since this should be in the
cesm control run. Also - we should include this the mapping files in beta06
- and this needs to be added to the plans page.

**Comment by billsacks** [comment]
The glc to ocean mapping files will have no effect on the control run: these are only important if you're running CISM with two-way coupling.

I'm planning to fold this and some other changes that involve cism-cime interdependencies into beta07.
