### ISSUE TITLE
Bug in configure?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1266]
On yellowstone, if I run

```
$ export MPILIB=mpi-serial
$ export COMPILER=gnu
$ $CIMEROOT/tools/configure --macros-format Makefile
```

Then the `.env_mach_specific.sh` script loads all the `gnu` modules, and it generates `Depends.gnu`, but the `SFC` and `SCC` variables are set incorrectly in `Macros.make`:

```
$ grep -e SFC -e SCC Macros.make 
SCC:= icc 
SFC:= ifort 
```

This might be a yellowstone-specific issue; `Macros.make` on hobart has sections like

```
ifeq ($(COMPILER),gnu)
  MPIFC :=  mpif90 
  FFLAGS_NOOPT :=  -O0 
  MPICC :=  mpicc  
  SCC :=  gcc
...
  SFC :=  gfortran 
  SCXX :=  g++ 
endif
ifeq ($(COMPILER),nag)
  MPIFC :=  mpif90 
  FFLAGS_NOOPT := -Wp,-macro=no_com -convert=BIG_ENDIAN -indirect $(CIMEROOT)/config/cesm/machines/nag_mpi_argument.txt
  MPICC :=  mpicc 
  SCC :=  gcc 
...
  SFC :=  nagfor 
endif
ifeq ($(COMPILER),intel)
  MPIFC :=  mpif90 
  FFLAGS_NOOPT :=  -O0 
  MPICC :=  mpicc  
  SCC :=  icc 
```

**Comment by jedwards4b** [comment]
I haven't been able to reproduce this issue.

**Comment by mnlevy1981** [comment]
I wonder if I need to set up a `$HOME/.cime/config` file... `configure` didn't work for me at all on hobart until I did that, and on hobart if I run `configure --machine yellowstone --macros-format` I get a reasonable `Macros.make`.

I'll try again on yellowstone when it's back up, and then close this if it turns out to be user-error.

**Comment by mnlevy1981** [comment]
Yeah, this turned out to be user error; specifying `cesm` in `.cime/config` produced a different `Macros.make` file with compiler-dependent blocks of settings.
