### ISSUE TITLE
Batch error messages not passed to user.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1270]
"Submitting a second job to the debug queue on Titan (where only one is allowed) generates a " " error message. Before it passed through the system error message (that there was already a debug job in the queue)."

This is a regression from 5.1. to 5.2.

**Comment by jgfouca** [comment]
@rljacob when I use create_test, I see the error pretty clearly logged in TestStatus.log. Can you give me a bit more context? Is this just with case.submit?

**Comment by jgfouca** [comment]
Actually, it looks like case.submit produces an error as well, at least on skybridge when I intentionally sabotage the sbatch flags:

```
ERROR: Command: 'sbatch   --time 0:10:00 -p ec --account fy150001 case.test ' failed with error 'sbatch: unrecognized option '--fioasdasda=16'
sbatch: error: Try "sbatch --help" for more information'
```

**Comment by rljacob** [comment]
The above is titan-specific so likely PBS.

**Comment by rljacob** [comment]
And yes this is from executing case.submit by hand.

**Comment by jgfouca** [comment]
@rljacob I bet I know what the problem is. The titan batch command is not well behaved and is sending error output to stdout.
