### ISSUE TITLE
Need support for aprun commands with different task/thread counts

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1271]
An example of the syntax that needs to be supported (and was with the old task_maker).

`aprun   -S 4  -n 680 -N 8 -d 2 xxx/acme.exe  : -S 2  -n 128 -N 4 -d 4 xxx/acme.exe'` 

Translation: the first 680 MPI processes should be assigned to nodes 8 at a time, 4 per numa domain, with a separation of 2 between each task (allowing two OpenMP threads, though that is not required); the second 128 processes should be assigned 4 per node, with 2 per numa domain, and with a separation of 4.

**Comment by jgfouca** [comment]
@rljacob , I have this working (pending Worley approval) on the ACME side, I don't believe we need a ticket on ESMCI side.

**Comment by rljacob** [comment]
We do because that needs to be on the ESMCI master and then protected by a test so it doesn't get removed again.  This ticket should stay open until its added here (through an ACME subtree split).

**Comment by jgfouca** [comment]
OK, that's fine with me. My work on the ACME side already added a test though.
