### ISSUE TITLE
perl namelist should allow both "false" and ".false."

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1283]
The MPAS-CICE buildnml is complaining about a logical a user is trying to set using user_nl_mpascice.

`config_test_case_diag = false`

'ERROR(Build::Namelist::_parse_next): expect a F90 constant for a namelist instead got:  false

If they set it instead to

`config_test_case_diag = .false.`

There there's no error.    But both "false" and ".false." should be allowed.

**Comment by mvertens** [comment]
I assume that this is using the perl old schema with
namelist_definition.xml and namelist_defaults.xml. How is
config_test_case_diag defined in the namelist_definition.xml?

**Comment by rljacob** [comment]
Yes that buildnml is still in perl.

In namelist definition:
```
<entry id="config_test_case_diag" type="logical"
        category="io" group="io">
MISSING DESCRIPTION

Valid values: MISSING POSSIBLE VALUES
Default: Defined in namelist_defaults.xml
</entry>
```
In namelist_defaults: ` <config_test_case_diag>false</config_test_case_diag>`

**Comment by mvertens** [comment]
I believe that perl is assuming that a logical will be  fortran namelist
logical - i.e. .true. or .false. To get the behavior he wants - I would
make it a character and then give the valid values as "true" or "false".
Hopefully, this will work.

**Comment by akturner** [comment]
The fortran standard allows both false and .false. as valid fortran in namelists. The standard actually allows the "f" character (or "t" character for true obviously) followed by anything as a valid value.

**Comment by mvertens** [comment]
I think this is a limitation of our perl modules for namelist parsing.

**Comment by rljacob** [comment]
Does the python parser allow both "false" and ".false."?

**Comment by rljacob** [comment]
Yes python allows both.

**Comment by erichlf** [comment]
The issue appears to in the regex used. I am testing a solution now.
