### ISSUE TITLE
xmlchange usability problems

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1284]
From @PeterCaldwell 

The old xmlchange command was:
 
```
./xmlchange -file env_build.xml -id CAM_CONFIG_OPTS -append -val "-cosp"
 ```

I tried to change it to:

```                                     
./xmlchange --id CAM_CONFIG_OPTS --append --val '-cosp'
 ```

and got the following error:

```                                                             
xmlchange: error: argument -val/--val: expected one argument
 ```

I eventually fixed the error by putting a space in front of -cosp: ‘<space>-cosp’:

``` 
./xmlchange --id CAM_CONFIG_OPTS --append --val " -cosp"
 ```

My thinking is that the python tries to glom appended options directly onto the end of what’s already there (in this case -cam5), so the result is -cam5-cosp which, of course, isn’t right. Maybe I’m mis-diagnosing things though… I would have thought xmlchange would be happy to glom things together and the error would only be found later in the build process. Also, Chris Golaz says this works for him:

``` 
 ./xmlchange --id CAM_CONFIG_OPTS --val='-cosp' --append
 ```

This didn’t work for me (perhaps because I’ve already added -cosp to CAM_CONFIG_OPTS).
 
In any case, all the lines I’ve sent you are direct copy from the command line, so if I’ve made a mistake in typing you should be able to see it in the commands I’ve sent you. Perhaps the overarching message is that xmlchange seems to be fiddly and hard for "dumb" scientists to get working…

**Comment by rljacob** [comment]
You keep switching between single and double quotes. Does that matter?

**Comment by jgfouca** [comment]
@rljacob no, that all gets resolved by the shell in an identical way (in this case)

**Comment by PeterCaldwell** [comment]
Thanks for the formatting help, Jim.

**Comment by mvertens** [comment]
I think that xmlchange should add a space when needed (specifically the
append) and not require the user to know that a space is needed.

**Comment by PeterCaldwell** [comment]
Update on my initial post - I talked with @golaz about my experience and he recalled that he too had problems with "-cosp" and found he needed to put a space in between the first quote and the dash to get things to work. This clears up the mystery in my initial post for why Chris got things working without the dash in front. His understanding was that the python interpreter was stripping the quotes off "-cosp" and interpreting -cosp as an input parameter since it started with a dash.
