### ISSUE TITLE
Should DATM be modified to read all time slices of a time-varying data at once?

### ISSUE THREAD

**Issue by bishtgautam** [ESMCI/cime#1286]
For a given time (`mDate,mSec`), the time-varying data is read independently for the lower bound time (`mDateLB,mSecLB `) and upper bound time (`mDateRB,mSecRB `) via `shr_dmodel_readLBUB()` in `cime/share/csm_share/shr/shr_dmodel_mod.F90`.  To reduce time spent in I/O, would it be worth modifying the code to read `nt` time slices at once?

**Comment by rljacob** [comment]
Yes it would.

**Comment by bishtgautam** [comment]
@mvertens , @billsacks , @ekluzek , @bandre-ucar, @jayeshkrishna : Any thoughts?

**Comment by mvertens** [comment]
Absolutely. This would be a good feature to add to the data models. But I
don't believe this is a simple task.

**Comment by bishtgautam** [comment]
Ok, I will review how a single time slice data is currently read by a data model and try to propose a solution.

**Comment by mvertens** [comment]
I've just been poring through that part of the code for a separate reason -
so if you want to talk about this I'm happy to to.

**Comment by bishtgautam** [comment]
A discussion on this would be helpful. My Thursday afternoon and Friday afternoon schedule are quite open. Let me know if you are available during those time slots. Thanks.

**Comment by bishtgautam** [comment]
@mvertens : My first attempt at reading all time slices in a netcdf is available at https://github.com/bishtgautam/cime/commit/bbe7d84554aeabf030323d65f69b9bd705fa320f. The first implementation is for `(pio_iotype /= iotype_std_netcdf)`.

**Comment by bishtgautam** [comment]
@mvertens : Do you know what setting of PIO_TYPENAME in env_run.xml will lead to `pio_iotype = iotype_std_netcdf` ([shr_dmodel_mod.F90#L774](https://github.com/ESMCI/cime/blob/master/src/share/util/shr_dmodel_mod.F90#L774))?

**Comment by jedwards4b** [comment]
PIO_TYPENAME='netcdf'

**Comment by bishtgautam** [comment]
thanks @jedwards4b

**Comment by bishtgautam** [comment]
@jedwards4b: I ran a simulation on Edison with PIO_TYPENAME='netcdf', but pio_iotype /= iotype_std_netcdf. Could it be a bug and one should be using `pio_iotype_netcdf` instead of `iotype_std_netcdf` to determine if standard netcdf is was specified in the xml file? 

Btw, `iotype_std_netcdf = -99` at [shr_dmodel_mod.F90#L63](https://github.com/ESMCI/cime/blob/master/src/share/util/shr_dmodel_mod.F90#L63))

**Comment by jedwards4b** [comment]
It should be pio_iotype_netcdf and I don't know where iotype_std_netcdf came from - it's not part of pio.

**Comment by jedwards4b** [comment]
This issue was fixed by PR #1418
