### ISSUE TITLE
Need documentation on how to analyze test output

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1288]
Summary: Something failed for me in scripts_regression_test.py in an area I did not modify so something is wrong:

- Someone is checking in broken code to master    -- or --
- Something is wrong with the tests -- false test failures

However, given how discombobulated the test output has become, I can't figure out what is going on. The only indication of failure is in the captured output, the error does not seem to show up in any test status I could find. Details below.

There are [instructions on how to run CIME tests](https://github.com/ESMCI/cime/wiki/Testing). 
However, I often have difficulty figuring out what might have gone wrong or even if everything passed. After running scripts_regression_test.py on Yellowstone, I have the following new files and directories (top level only):
```
scripts_regression_test.20170329_224211
TESTRUNPASS_P1.ne30_g16_rx1.A.yellowstone_intel.G.20170329_230448_hbhws3
cs.submit.20170329_230448_hbhws3
cs.status.20170329_230448_hbhws3
TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel.G.20170329_230438_gy9los
cs.submit.20170329_230438_gy9los
cs.status.20170329_230438_gy9los
TESTRUNPASS_P1.f45_g37_rx1.A.yellowstone_intel.G.20170329_230427_nv1brw
cs.submit.20170329_230427_nv1brw
cs.status.20170329_230427_nv1brw
```
The three cs.status scripts all show PASS except for that annoying PEND for SHAREDLIB_BUILD.
The scripts_regression_test directory has no cs.status files.
And yet, at the end of the captured output of scripts_regression_test.py, I see
```
[ More PIO compilation failures omitted ]
---------------------------------------------------------^
/glade/u/home/goldy/Projects/cime/src/share/util/shr_pio_mod.F90(807): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
      pio_rearr_opts%comm_fc_opts_io2comp%enable_isend = .true.
---------------------------------------------------------^
compilation aborted for /glade/u/home/goldy/Projects/cime/src/share/util/shr_pio_mod.F90 (code 1)
make[2]: *** [src/drivers/mct/unit_test/CMakeFiles/csm_share.dir/__/__/__/share/util/shr_pio_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/drivers/mct/unit_test/CMakeFiles/csm_share.dir/all] Error 2
make: *** [all] Error 2
ERROR: Command: 'make -j 8' failed with error 'None''

----------------------------------------------------------------------
Ran 293 tests in 2344.117s

FAILED (errors=1, skipped=5)
Detected failed test or user request no teardown
Leaving case directory : /glade/scratch/goldy/scripts_regression_test.20170329_224211/TestUnitTests/driver_f90_tests
Detected failed test or user request no teardown
Leaving files:
```
Looking around the `driver_f90_tests` directory gives me no clue as to how to figure out what went wrong.
I think it is important to be able to know what has happened when tests are run and I feel the current test framework is not meeting that standard.

**Comment by jayeshkrishna** [comment]
@gold2718 : Did you figure out the cause of the pio compilation failures (it looks like an issue of incompatibility btw C_BOOL and LOGICAL)?

**Comment by gold2718** [comment]
@jayeshkrishna: No, I don't know anything about these tests and did not change anything that affects the build or PIO (I only added a run-time XML driver variable).
The point of this issue is that I don't even know how to find out that there was an error by looking at the files/directories created by scripts_regression_test.py. I used to be able to run a cs.status.xxx script but I don't even see that anymore.

**Comment by jedwards4b** [comment]
@gold2718 I don't understand how you are misinterpreting this failure in the N_TestUnitTest
portion of scripts_regression_tests.py or how I could make the output clearer for you.  Perhaps we could discuss in person?

**Comment by gold2718** [comment]
Just looking at the output directories from the tests, how do I even know there _was_ a failure? What are the procedures for verifying that the tests did pass or fail?
If I did not happen to see the test output I would not have suspected a failure. I do not see a FAIL anywhere. Is this output logged? Is there a command to discover it?

**Comment by jedwards4b** [comment]
Hi Steve,

There was another problem masking this error, but once I took care of that I found an error that does appear to be related to your changes:

  0: (seq_comm_init) ERROR: esmf_logging not set
   0: ERROR: (seq_comm_init) ERROR: esmf_logging not set
   0:Image              PC                Routine            Line        Source             
   0:vertical_gradient  0000000001808E5D  Unknown               Unknown  Unknown
   0:vertical_gradient  000000000171C22F  shr_sys_mod_mp_sh         401  shr_sys_mod.F90
   0:vertical_gradient  000000000171BD47  shr_sys_mod_mp_sh         230  shr_sys_mod.F90
   0:vertical_gradient  00000000015F0560  seq_comm_mct_mp_s         906  seq_comm_mct.F90
   0:vertical_gradient  00000000015DA297  mct_wrapper_mod_m          42  mct_wrapper_mod.F90
   0:vertical_gradient  000000000041FCCB  test_vertical_gra          29  test_vertical_gradient_calculator_factory.F90
   0:vertical_gradient  0000000001597223  testcase_mod_mp_r         131  TestCase.F90
   0:vertical_gradient  00000000015973E1  testcase_mod_mp_r         143  TestCase.F90
   0:vertical_gradient  00000000015A7B50  testresult_mod_mp         235  TestResult.F90
   0:vertical_gradient  00000000015971B3  testcase_mod_mp_r         120  TestCase.F90
   0:vertical_gradient  00000000015BBACD  testsuite_mod_mp_         120  TestSuite.F90
   0:vertical_gradient  00000000015BBACD  testsuite_mod_mp_         120  TestSuite.F90
   0:vertical_gradient  00000000015B87D0  testrunner_mod_mp         109  TestRunner.F90
   0:vertical_gradient  0000000000427DFF  MAIN__                    176  driver.F90
   0:vertical_gradient  0000000000405DCE  Unknown               Unknown  Unknown
   0:libc.so.6          0000003E2B21ED5D  Unknown               Unknown  Unknown
   0:vertical_gradient  0000000000405CD9  Unknown               Unknown  Unknown

**Comment by gold2718** [comment]
The particular problem is **_not_** this issue.
The fact that you can poke around and find a problem is **_not_** this issue.
This issue is documenting the procedure that anyone using scripts_regression_test.py MUST use to verify that all tests have passed and to locate any and all failing tests.
This is clearly an important issue because, as you yourself point out, it is showing problems unrelated to my changes which means that someone is not noticing failures in testing and that whoever handled the PR also did not notice. This is a hole in our test procedure that needs to be fixed.

**Comment by gold2718** [comment]
@sarich, you closed this issue but the document still does not specify that only the test output is useful. If you do not capture the output, is there a method for finding if anything failed and if so, what? If not, I think the wiki should be updated with the importance of capturing and studying the output (since apparently, there is no summary anymore).

**Comment by jgfouca** [comment]
Added docs.
