### ISSUE TITLE
New NetCDF distribution and CIME

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#129]
As some of you know, NetCDF now makes the C and Fortran implementations of NetCDF available as separate packages.

For most sysadmins, this means they could be installed with completely different paths:  "NetCDF C path"/lib and "NetCDF-Fortran-path"/lib.  We've already seen this on Blues and its a reasonable thing to do.

The CIME build assumes the C and Fortran libs (or includes) are all in the same "lib" (or "include") directory. Should we change that assumption?

**Comment by jedwards4b** [comment]
pio handles this already with NETCDF_C_PATH and NETCDF_FORTRAN_PATH
(more needs to be done for cime to handle it…)

**Comment by rljacob** [comment]
Yes CIME needs to do this.  See Issue #907
