### ISSUE TITLE
Create clear and complete porting documentation

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1293]
There is a new section on CIME internals that has been pushed to gh-pages that will help the porting documentation. The porting documentation needs to be significantly enhanced with examples to enable users to easily determine what needs to be done to port to their platformas.

**Comment by rljacob** [comment]
Agree on more porting instructions.  Don't agree on a new top level section.  You wrote about the config files which is great.   But everything you put in your new "Part 2" I think should just go in the "advanced use".  Doing pe layouts, editing config files, running create_test, adding tests,  and porting all go in the Advanced use guide.   Its all about working with the scripts so its still counts as "user".   If that's not "advanced" what is?   Maybe "Advanced" is throwing everybody.  Its just "beyond-basic use".    Renaming that part is fine but we don't need another major part.

**Comment by mvertens** [comment]
I think we need to have the porting be tied into the CIME internals and
that really seems to be to be a separate section form advanced usage. For
CESM most users will want to port - and that is not an advanced usage of
CIME - its a necessary usage. And to port you need to understand the CIME
internals. And also you need to understand the testing and validation to
validate your port. So it seems to be that all of these are really lumped
into a separate consistent section. At least that was my reasoning. Its
really easy to go back to the older structure - but could we have a wider
discussion of this in a CIME meeting?

**Comment by rljacob** [comment]
Yes we'll need to hash this out in a telecon. 

The CIME config files definitely need to be documented but there are other reasons to know what's in them: curiosity, updating an existing machine, their place in the CIME object oriented design.  They can be linked to from any documentation using internal links.  So I don't think they must be "tied" to the porting.

We also need to decide what we mean by an "advanced user".   The Part 1 material could be followed by someone with barely any unix experience (a typical beginning grad student).   But someone doing a port should be a bit more "advanced" then that even if they've a beginner with CIME.
