### ISSUE TITLE
document CECT

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1294]
Add documentation to the CECT test.   How to run.

**Comment by rljacob** [comment]
From telecon:  We want this in the rst user's guide.

**Comment by jedwards4b** [comment]
@fischer-ncar any progress on this?

**Comment by fischer-ncar** [comment]
I've been working with Allison Baker in getting the PyCECT scripts updated to work on cheyenne.  We're also sorting out issues with too many variables be excluded when I run the scripts, but not for here.  Once we get a work flow that I'm happy with, I'm going to update the user guide.

**Comment by mvertens** [comment]
@fischer-ncar - where is this with respect to the release?

**Comment by fischer-ncar** [comment]
We've sorted out the issue of too many variables being excluded.  The README has been updated for CESM2 and cheyenne.  There's a CECT submission script that still referencing yellowstone's LSF.

Allison also said they're in the process of converting the shell scripts to python.  It should be done about now.  I need to get the current status on that.

**Comment by mvertens** [comment]
@fischer-ncar - we need to add a section for this in the quick start? Or the CIME user's guide. Not sure which is better. This is how users will verify a port - so I think this is high priority for the release.

**Comment by fischer-ncar** [comment]
@mvertens, it's my top priority when I get back from vacation.

**Comment by rljacob** [comment]
Ping @fischer-ncar

**Comment by fischer-ncar** [comment]
Closed via #3012
