### ISSUE TITLE
pio_rearr_opts should not be exposed in shr_pio_mod.F90

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1296]
In shr_pio_mod.F90 the internals of pio derived datatype pio_rearr_opt_t are used directly.
This creates an issue in which the internal data structures of pio are limited by usage in the model.
Settings for these data structures should happen internal to pio so that these internal data types are not exposed.

**Comment by jayeshkrishna** [comment]
A set function with optional arguments could help in keeping the pio_rearr_opt_t structure internal.

**Comment by jayeshkrishna** [comment]
But before we introduce the optional arguments, for this task it would be enough to use the PIO_set_rearr_opts(), after init, to set the rearranger options.

**Comment by jayeshkrishna** [comment]
So this work would also involve implementing pio_set_rearr_opts() in pio1
