### ISSUE TITLE
fortran unit tests need to run on systems other than yellowstone

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1297]
This involves installing PFUNIT https://sourceforge.net/projects/pfunit/

**Comment by billsacks** [comment]
See also https://github.com/ESMCI/cime/issues/1141 - which includes instructions for building pFUnit.

**Comment by billsacks** [comment]
@jgfouca - note that with #1396 you'll just need to provide a _serial_ build of pFUnit - not an mpi-enabled build like we needed in the past. I'm working on the documentation of how to build pFUnit and set up a new machine for unit testing, which I'll push to the documentation page soon.

**Comment by jgfouca** [comment]
ok, thanks

**Comment by jgfouca** [comment]
@billsacks did you finish the documentation for pfunit?

**Comment by billsacks** [comment]
@jgfouca - yes, this documentation should be correct now:

http://esmci.github.io/cime/doc/build/html/users_guide/unit_testing.html#how-to-add-unit-testing-support-on-your-machine

**Comment by jgfouca** [comment]
@billsacks that link gives me a 404

**Comment by billsacks** [comment]
Try http://esmci.github.io/cime/users_guide/unit_testing.html#adding-machine-support
