### ISSUE TITLE
Short term archiver generates invalid characters in the log files

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1306]
This issue is reproducible by running "create_test ERR.f45_g37_rx1.A" on anlworkstation.
In TestStatus.log there is output like below
```
st_archive starting
moving  /sandbox...
```
Between "moving" and "/sandbox" there is a space character, followed by \b (backspace, ASCII code 8)
If we use wait_for_tests script to generate Test.xml (based on TestStatus.log) and submit it to CDash, that xml file cannot be correctly parsed by CDash. If we open Test.xml with Firefox, it shows "XML Parsing Error: not well-formed" and refers to the location of the \b character.

In scripts/lib/CIME/case_st_archive.py, line 123 we have:
`logger.info("moving \b%s to \b%s" %(srcfile, destfile))`

Is there any reason to output \b to the log files? In line 171, it is using \n instead.
`logger.info("moving \n%s to \n%s " %(srcfile, destfile))`

**Comment by rljacob** [comment]
That looks like a typo.  "b" and "n" are right next to each other.

**Comment by jedwards4b** [comment]
Fixed in #1375
