### ISSUE TITLE
Need valid_values for some "OPTION" xml entries

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1318]
Some of the *OPTION xml entries have valid_values, such as STOP_OPTION. But others, like HIST_OPTION, AVGHIST_OPTION, and maybe others, do not. We should add valid_values for those.

**Comment by billsacks** [comment]
I wonder if these weren't given valid_values because they are sometimes set to things like $STOP_OPTION?

**Comment by jedwards4b** [comment]
Setting to another variable such as $STOP_OPTION avoids the valid_value check.  I think that they were just overlooked.
