### ISSUE TITLE
Add a DOI XML variable

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1327]
_From @bertinia on March 6, 2017 23:36_

Starting with CESM2.0, there will be a DOI pointing to the associated CESM model page URL.
This DOI variable will be included in every component history output file as a global metadata attribute.  It needs to be set as a CESM XML variable in: 

cime/driver_cpl/cime_config/config_component_cesm.xml. 

and then picked up by every component model output writer routine similar to the
global attribute time_period_freq.

This is for CMIP6 compliance and also provides additional provenance information in the history file global metadata. 

_Copied from original issue: CESM-Development/cime#483_

**Comment by bertinia** [comment]
Here are the specifics for the minted CESM2.0 DOI - 

DOI:

doi:10.5065/D67H1H0V

URL:

https://doi.org/10.5065/D67H1H0V

Citation example:

Community Earth System Model - CESM2.0 [Software]. (2017). Boulder, Colorado: UCAR/NCAR - Climate and Global Dynamics Laboratory. https://doi.org/10.5065/D67H1H0V

**Comment by rljacob** [comment]
Who issued the DOI?

**Comment by bertinia** [comment]
NCAR has a paid subscription with DataCite and Gary Strand is the gatekeeper for
CGD related DOI minting.

**Comment by ekluzek** [comment]
This has been added into CIME. It is now making it's way into CESM components. CTSM, RTM, and MOSART have issues to add it in.
