### ISSUE TITLE
rewrite archive_metadata in python

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1328]
_From @bertinia on November 18, 2016 17:48_

Here is the list of base fields that need to be harvested from the caseroot and sent to the expdb:
Base list of fields to be harvested from the caseroot XML:
    CASE
    CASEROOT
    COMPILER
    COMPSET
    CONTINUE_RUN
    DOUT_S_ROOT
    GRID
    MACH
    MODEL
    MPILIB
    PROJECT
    REST_N
    REST_OPTION
    RUNDIR
    RUN_REFCASE
    RUN_REFDATE
    RUN_STARTDATE
    STOP_N
    STOP_OPTION
    USER
    CASEROOT
    CESMTAG 
    title (cmd line arg input)

_Copied from original issue: CESM-Development/cime#480_

**Comment by bertinia** [comment]
This is in test but will only be used with CESM.  Is there a way to restrict creating the
link in create_newcase and create_clone to be CESM only?

**Comment by jedwards4b** [comment]
model = CIME.utils.get_model()
if model == 'cesm':

**Comment by rljacob** [comment]
This has been completed.
