### ISSUE TITLE
Refactor of expected fails

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1329]
_From @mvertens on October 23, 2015 18:1_

The testdb needs to be able to handle what the testreporter spits back.
Carry over the notes that you put in for tests.
Management of expected fails. This needs to be moved out of cime. 
These tasks are dependent on the fix of testreporter.pl.

_Copied from original issue: CESM-Development/cime#257_

**Comment by bertinia** [comment]
The testdb code was updated to handle notes carrying forward from one 
test to the next if there is a failure.

**Comment by rljacob** [comment]
JIm says this is fixed.
