### ISSUE TITLE
Handle projects and subprojects in machine/batch variables.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1332]
On Titan, accounting projects often have subprojects.  The "project" name should be used for directories and fits the standard use of $PROJECT in CIME.  But jobs should be submitted to the subproject.  Example:  "csc190" is the $PROJECT for directory names but the account in qsub should be  "csc190acme".

**Comment by rljacob** [comment]
@sarich Where are you with this?

**Comment by sarich** [comment]
I've pushed up a branch sarich/scripts/feature-subproject, testing it now
with various ways of setting subproject (in main config file, user config
file, command line option) and checking that old configurations still work.

I didn't see an easy way to split off 'project' and 'subproject' that would
default the charging to 'project 'if no subproject was given, so the
changes run a little deeper than I might have hoped for.

Also, I think that perhaps 'subproject' is not the correct term for this,
perhaps something more descriptive is needed. projectchargeaccount or
 projectbank

**Comment by rljacob** [comment]
Yeah maybe just call it "account".   If not specified, then account = project.

**Comment by sarich** [comment]
There's already a backward-compatibility usage for 'account', from util.py:

    Hierarchy for choosing PROJECT:
    0. Command line flag to create_newcase or create_test
    1. Environment variable PROJECT
    2  Environment variable ACCOUNT  (this is for backward compatibility)
    3. File $HOME/.cime/config       (this is new)
    4  File $HOME/.cesm_proj         (this is for backward compatibility)
    5  config_machines.xml (if machobj provided)

**Comment by sarich** [comment]
PR submitted to ACME-Climate

See https://github.com/ACME-Climate/ACME/pull/1718
