### ISSUE TITLE
Add a --script-root option to create_newcase

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1353]
Add a --script-root option to create_newcase which will put all of the xml and case files created by create_newcase under the designated directory.

If a user did:
`./create_newcase --case mycase --output-root $CASE_ROOT --script_root $CASE_ROOT/cime_scripts`

They would get a directory layout like this:
```
mycase/
      \-->  cime_scripts
      \-->  bld
      \-->  run
```

**Comment by rljacob** [comment]
@mfdeakin you should work on this since the coupled group wants it soon.

**Comment by mfdeakin-sandia** [comment]
I hope to get to this later today; I've been dealing with more critical issues for them
