### ISSUE TITLE
DATM_CPLHIST_DIR not used?

### ISSUE THREAD

**Issue by lvankampenhout** [ESMCI/cime#1367]
Trying to set up a land-only case with 3-hourly coupler data

    <entry id="DATM_MODE" value="CPLHIST3HrWx">

from one of my own runs: 

    <entry id="DATM_CPLHIST_CASE" value="b.e20.BHIST.f09_g16.20thC.144_01_3hrYS">

. However it seems that the data directory entry

    <entry id="DATM_CPLHIST_DIR" value="/glade/p/work/lvank/forcing/b.e20.BHIST.f09_g16.20thC.144_01_3hrYS/cpl/hist/">

is not used: 

    $ ./preview_namelists
    $ grep -A2 "<filePath>" CaseDocs/datm.streams.txt.CPLHIST3HrWx.Precip 
    <filePath>
      /glade/p/cesm/shared_outputdata/cases/ccsm4/b.e20.BHIST.f09_g16.20thC.144_01_3hrYS/cpl/hist
    </filePath>

**Comment by mvertens** [comment]
Could you please point us to your $CASEROOT.

**Comment by mvertens** [comment]
Several things.

1) I am not seeing the problem you are pointing to. The DATM_CPLHIST_DIR

2) I found your $CASEROOT and for cplhist forcing the stream domain must be
the same as its files. This is a tricky problem with this mode. What you
need to do is to set your ATM_DOMAIN_FILE to "UNSET". In that case the
stream use the domain from the first stream file. This needs to be
documented - which I am in the process of doing. In the cesm2_0_alpha06g
versions of CIME, this is happening out of the box. Alternatively, your can
edit your user_datm.stream file to have

<domainInfo>
   ....
   <filePath>

 /glade/p/work/lvank/forcing/b.e20.BHIST.f09_g16.20thC.144_01_3hrYS/cpl/hist
   </filePath>
   <fileNames>
      b.e20.BHIST.f09_g16.20thC.144_01_3hrYS.cpl.ha2x3h.1960-01-01.nc
   </filenames>
</domainInfo>

3) We are in the process of unifying the land and ocean cplhist forcings to
be one thing - CPLHISTForcing data mode. This should be coming into CIME in
beta06.

**Comment by lvankampenhout** [comment]
Thanks for your help. Indeed I forgot to mention the $CASEROOT: it's 

     /glade/u/home/lvank/cesm/my_cases/bgruns144/ig.e20.f09_g16.20thC.144_iwc2

After my post here I continued working on a workaround, which involved the user_datm.streams.txt* files. Could this explain why you are not seeing the problem? 

Just now I created a clone case under 

    /glade/u/home/lvank/cesm/my_cases/bgruns144/ig_test 

where I removed the user_datm.streams.txt*, and changed ATM_DOMAIN to "UNSET". Then preview namelists warns: 

    File not found: domainfile = "/glade/p/cesmdata/cseg/inputdata/share/domains/UNSET", will attempt to download in check_input_data phase

and stream files under CaseDocs list the wrong file path. 

On a side note: the coupler data generated by setting 

    histaux_a2x3hr = .true.

generates daily files with 8 timesteps each, can these directly be used by DATM? I now concatenated them into monthly files first.

**Comment by mvertens** [comment]
This has been resolved on cime master in a recent update to CIME. Unfortunately, there was no bug listed for this domain problem. 

However, even without cime master -  I have verified that by creating your case and having preview namelist work correctly out of the box using cesm2_0_alpha06i.

There is a subtlety, however, in that domainfile in your datm_in namelist is set incorrectly out of the box

```
&shr_strdata_nml
  datamode = "CPLHIST"
  domainfile = "/glade/p/cesmdata/cseg/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v6.090309.nc"
  ....

```
This domain file does not exactly match the domain from the streams. To get that to happen you need to set ATM_DOMAIN_FILE to "UNSET"
`  ./xmlchange ATM_DOMAIN_FILE=UNSET
`
That in turn will set
` domainfile = "null" `
in datm_in. And what the data models do under the cover is if the domainfile is "null" then it will use the domain from the first stream file it reads in.

It is on my priority list to document this in the data model guid.

And yes - histaux_a2x3hr  - should be able to be read in by datm.

**Comment by adamrher** [comment]
I'm resurrecting this issue b/c @lvankampenhout raised a point that I *think* I'm currently encountering w/ an up-to-date code base @mvertens. He says:

"On a side note: the coupler data generated by setting
`histaux_a2x3hr = .true.`
generates daily files with 8 timesteps each, can these directly be used by DATM? I now concatenated them into monthly files first."

The histaux_a2x3hr = .true. cpl i/o has date stamps in the form of year-month-day-[seconds-of-first-timeslice]. I think Leo is saying that when he runs DATM, it is looking for cpl forcing files of entire months, not days. I concur. Here's an example ...

Setting the XML variables req'd to run a CLM I compset w/  with cpl fields only asks for the year only, e.g.,:

`./xmlchange DATM_CPLHIST_YR_ALIGN=1979
./xmlchange DATM_CPLHIST_YR_START=1979
./xmlchange DATM_CPLHIST_YR_END=1980`

This generates CaseDocs/data.streams.txt* that assume the cpl forcing files use time-stamps as year-month. One can manually re-populate the data.streams.txt* with the correct file names, or cat the cpl i.o to the year-month convention, as leo did. That is, I am not finding that histaux_a2x3hr can be seamlessly used to run DATM in this scenario. 

Here is a $CASEROOT where you can see this in CaseDocs/data.streams.txt* (i.e., compare the files listed to the files in filepath):

`/glade/scratch/aherring/ctsm1.0.dev079.se_grids.n02_I1850Clm50BgcSpinup_f09_f09_mg17_200317_ioproblem-test`

**Comment by billsacks** [comment]
@adamrher can you move your latest comment to a new issue with appropriate title? I actually suspect that the issue is having appropriate documentation about how you're supposed to do this, but I'm not sure.

**Comment by mvertens** [comment]
@adamrher - @klindsay28 has a utility that concatenates the output histaux_xxx files into files that can be used by datm. So you are right - you need this step before datm can use the files. It would be good to both document this as well as integrate the tool that @klindsay28 has into cime. @klindsay28 - can you please provide details - once this issues has been moved.
