### ISSUE TITLE
Need an adjective for model that uses CIME

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1380]
Fill in the blank:
"ACME and CESM are both examples of CIME- _______ models"

"enabled"?
"compliant"?
Don't try. Just say "models that use CIME".

**Comment by Katetc** [comment]
CIME-supported or CIME-integrated models?

**Comment by jedwards4b** [comment]
I like enabled.

**Comment by billsacks** [comment]
CIMEified (part jokingly, but if it sticks I'll take credit for it :-)

**Comment by mvertens** [comment]
I vote for enabled as well.

**Comment by mnlevy1981** [comment]
CIME-dependent?
CIME-reliant?
CIME-based?

You should highlight the fact that neither ACME nor CESM can be run without CIME, which CIME-enabled doesn't get across.

**Comment by mnlevy1981** [comment]
After more thought, I'm leaning towards "CIME-driven."

**Comment by billsacks** [comment]
I like CIME-driven

**Comment by mvertens** [comment]
I am fine with that.

**Comment by mvertens** [comment]
The final verdict is CIME-driven. Driven both by the fortran and by the scripts.
