### ISSUE TITLE
wait_for_tests does not work on test status of ERI.f45_g37.X

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1382]
This issue has been reproduced on anlworkstation, blues and edison.

Create and run a single test ERI.f45_g37.X
`./create_test ERI.f45_g37.X --machine=**** --test-root=****`

View the test-root directory. On edison, the content is like below:
```
cs.status.20170419_074507_0zt7fm
ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm
ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm.ref1
ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm.ref2
```

Run wait_for_tests script on TestStatus, it will fail. On edison, the error message is like below:
```
Test name 'ERI.f45_g37.X.edison_intel' was found in both '~/test_cime/ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm.ref2/TestStatus' and '~/test_cime/ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm.ref1/TestStatus'
Test name 'ERI.f45_g37.X.edison_intel' was found in both '~/test_cime/ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm/TestStatus' and '~/test_cime/ERI.f45_g37.X.edison_intel.20170419_074507_0zt7fm.ref2/TestStatus' with different results
```

It seems that the ref2 case has a TestStatus file, which is not expected.

**Comment by jgfouca** [comment]
@dqwu Sorry for the slow response. The correct use of wait_for_tests is the following:

```
% ./create_text ... -t test-id
% ./Tools/wait_for_tests $TEST_ROOT/*$test-id/TestStatus
```

You can also pass the --wait flag to create_test to do this automatically. The fact that the ref cases have TestStatus files shouldn't matter since they shouldn't be looked at in the first place.
