### ISSUE TITLE
For datm cplhist cases, get topo from cplhist file

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1407]
Currently, datm always gets the topo stream (atmosphere topographic height) from a particular topo dataset. However, for cplhist cases, we really want to get the topo field from the cplhist file.

Changes to write the topo field to the cplhist file are already in place. So this requires extending the logic in datm's namelist / streams file generation to get the topo field from the correct place.

I think this is related to https://github.com/CESM-Development/cime/issues/99

One tricky part of this is how to support backwards compatibility for old cplhist files. When we talked about it in Nov, 2015, @ekluzek suggested: We could have an xml variable that says where to look for topo when running cpl hist. By default it will look on the cplhist files themselves. But the user can change this xml variable to make it look on the static file that is used for other datm cases.

**Comment by billsacks** [comment]
https://github.com/CESM-Development/cime/issues/99 is now #1529

**Comment by billsacks** [comment]
@JeremyFyke this may affect JG runs.

**Comment by billsacks** [comment]
@lvankampenhout has gotten this to work with case-specific mods. Now we need to get this working out-of-the-box. Key aspects to Leo's mods are:

(1) user_datm.streams.txt.topo.cplhist:

```
[yslogin5:/glade/u/home/lvank/cesm/my_cases/igruns179/ig179_control_cplhist]$ diff -u CaseDocs/datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip user_datm.streams.txt.topo.cplhist
--- CaseDocs/datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip2017-06-30 02:00:50.454632000 -0600
+++ user_datm.streams.txt.topo.cplhist2017-06-29 09:49:30.164912000 -0600
@@ -19,16 +19,7 @@
 </domainInfo>
 <fieldInfo>
    <variableNames>
-     a2x3h_Sa_z           z
-        a2x3h_Sa_u           u
-        a2x3h_Sa_v           v
-        a2x3h_Sa_tbot        tbot
-        a2x3h_Sa_ptem        ptem
-        a2x3h_Sa_shum        shum
-        a2x3h_Sa_pbot        pbot
-        a2x3h_Faxa_lwdn      lwdn
-        a2x3h_Sa_dens        dens
-        a2x3h_Sa_pslv        pslv
+        a2x3h_Sa_topo        topo
    </variableNames>
    <filePath>
      /glade/p/cesm/bgcwg_dev/forcing/b.e20.B1850.f09_g17.pi_control.all.179.cplhist/cpl/hist.mon
@@ -276,6 +267,6 @@
 b.e20.B1850.f09_g17.pi_control.all.179.cplhist.cpl.ha2x3h.0056-12.nc
    </fileNames>
    <offset>
-      -5400
+      -10800
    </offset>
 </fieldInfo>
```

Note that the -10800 matches what's used in datm.streams.txt.CPLHIST3HrWx.Solar, but not in the other streams  ... I'm not sure what's right here. It probably doesn't matter for the typically time-invariant topo stream, but we should still do the right thing in the final version. 

(2) user_nl_datm has:

```
taxmode = 5*'extend'

! Workaround for TOPO that had -999 substituted for START, ALIGN, END year

!!streams = "datm.streams.txt.CPLHIST3HrWx.Solar 37 37 56",
!!      "datm.streams.txt.CPLHIST3HrWx.Precip 37 37 56",
!!      "datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip 37 37 56",
!!      "datm.streams.txt.presaero.cplhist 37 37 56",
!!      "datm.streams.txt.topo.cplhist 37 37 56",
!!      "datm.streams.txt.co2tseries.cplhist 37 37 56"

streams = "datm.streams.txt.CPLHIST3HrWx.Solar 37 37 56",
      "datm.streams.txt.CPLHIST3HrWx.Precip 37 37 56",
      "datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip 37 37 56",
      "datm.streams.txt.presaero.cplhist 37 37 56",
      "datm.streams.txt.topo.cplhist 37 37 56"

!!streams = "datm.streams.txt.CPLHIST3HrWx.Solar 37 37 37",
!!      "datm.streams.txt.CPLHIST3HrWx.Precip 37 37 37",
!!      "datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip 37 37 37",
!!      "datm.streams.txt.presaero.cplhist 37 37 37",
!!      "datm.streams.txt.topo.cplhist 37 37 37"

  domainfile = "/glade/p/cesmdata/cseg/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v7.151020.nc"
```

(3) In env_run.xml, DATM_TOPO is set to none rather than 'observed'... I'm not sure if Leo did this explicitly, and whether this is actually required? I'd think this is __not__ wanted in the out-of-the-box implementation.

**Comment by JeremyFyke** [comment]
@billsacks @lvankampenhout:

I am wondering if an easy solution arises here (at least for a 'typical' JG/BG' run) because by default, the previous B(G) simulation outputs topography to the *ha2x3h* files.  So, if DATM_TOPO='none', and the following **bold** line is added to cime/src/components/data_comps/datm/cime_config/namelist_definition_datm.xml:

<fieldInfo>
   <variableNames>
     a2x3h_Sa_z       z
        a2x3h_Sa_tbot    tbot
        a2x3h_Sa_ptem    ptem  
        a2x3h_Sa_shum    shum
        a2x3h_Sa_pbot    pbot
        a2x3h_Sa_dens    dens
        a2x3h_Sa_pslv    pslv
	a2x3h_Sa_co2diag co2diag
	a2x3h_Sa_co2prog co2prog
	**a2x3h_Sa_topo    topo**
   </variableNames>
   <filePath>

I wonder if it will pick up the model-based topography correctly?  I am testing this out now in my current JG iteration.

Thoughts welcome.

**Comment by billsacks** [comment]
@JeremyFyke let me know if you get that working out-of-the-box. Originally we wanted a solution that would also work for older cpl hist files, but I don't know if that's still a requirement, so knowing what's needed without worrying about backwards compatibility would be great.

**Comment by JeremyFyke** [comment]
Probably a dumb question, but: what would be the failsafe way to know that the topography is getting read in/used correctly?

**Comment by billsacks** [comment]
> @billsacks Probably a dumb question, but: what would be the failsafe way to know that the topography is getting read in/used correctly?

Not a dumb question at all! I _think_ you can do this by checking CLM's history field `ATM_TOPO`, and making sure this matches what's on the cpl hist file.

**Comment by JeremyFyke** [comment]
@billsacks After setting DATM_TOPO to 'none', no datm.streams.txt.topo.* appears in the run directory.  Yet in viewing the ATM_TOPO field in clm2 history, there is a reasonable looking global smoothed topography present.  So unless this sneaking in from some other source (clm restart?) it seems like it is being read correctly via streams.  A direct diff of ATM_TOPO and the ha2x3h files is difficult, because topo is changing in these files as GrIS evolves.  But I'll try to keep an eye on this as the JG/BG proceeds.
