### ISSUE TITLE
CDash is reporting a pass for failed tests

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1409]
There are failures here http://my.cdash.org/testDetails.php?test=31185318&build=1182033 but it says "Passed" at the top, and the higher-level CDash pages (http://my.cdash.org/viewTest.php?onlypassed&buildid=1182033 and http://my.cdash.org/index.php?project=CIME) show no indication of failures.

**Comment by jgfouca** [comment]
Whoa, that's not good.
