### ISSUE TITLE
Add a --build-root option to create_newcase

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1415]
Allow the user to specify where the build directory should be placed

**Comment by jedwards4b** [comment]
There is already an option --output-root that controls where the bld and run directories will go.  I think that we should not add another option for this.

**Comment by mfdeakin-sandia** [comment]
I need to talk with the run_acme people some more, but I think you're correct

**Comment by rljacob** [comment]
Were they asking about issue #1353?  Feel free to take that one over.
