### ISSUE TITLE
Clean up python in unit_testing

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1424]
Clean up code in unit_testing/python

**Comment by billsacks** [comment]
(Much of this is now dead code and should be removed.)

**Comment by rljacob** [comment]
Recommend do this after #1423 is closed.

**Comment by billsacks** [comment]
I'll take this. For some reason code_checker is reporting problems with the stuff in this directory (now that I have moved it under scripts/fortran_unit_testing) that didn't seem to be causing problems before... so I'll clean this up as part of addressing #1423 .

**Comment by jedwards4b** [comment]
scripts_regression_tests has a list of directories for which code_checker will not be run, the old unit_tests directory is in that list.
