### ISSUE TITLE
CIME Component Freshwater Budget incomplete 

### ISSUE THREAD

**Issue by jtruesdal** [ESMCI/cime#1429]
While tracking down an inconsistency in the freshwater budget between POP and what is reported in the coupler tables, I found that the coupler freshwater budget calculations were incomplete.  I've filed a pull request (#1427) to correct the error but would like to make sure this is not also a problem for ACME.

**Comment by rljacob** [comment]
We're using the same coupler and therefore the same diagnostic calculation so it might be unless it was somehow compensated for in MPAS.   I'll open an issue in ACME for comment.
