### ISSUE TITLE
Need to change modify_via_xml for more meaningful error messages

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1430]
If you try to modify a namelist variable that has a modify_via_xml attribute, the namelist generation prints out the value of the modify_via_xml attribute. But in many cases, this doesn't give an understandable error message. e.g., when trying to modify atm_cpl_dt, I get:

```
ERROR: Cannot change atm_cpl_dt in user_nl_xxx file, ATM_NCPL
```

(1) user_nl_xxx should be fixed or removed

(2) the modify_via_xml should be changed to the full message. e.g., rather than this (in namelist_definition_drv.xml)

```xml
  <entry id="atm_cpl_dt" modify_via_xml="ATM_NCPL" skip_default_entry="true">
```

it should say

```xml
  <entry id="atm_cpl_dt" modify_via_xml="set via ATM_NCPL" skip_default_entry="true">
```

**Comment by jedwards4b** [comment]
It's difficult to know at the point of the error which user_nl_ file is the problem.  What is wrong with user_nl_xxx ?   It's really not that cryptic.    I can change the message to :
ERROR: Cannot change atm_cpl_dt in user_nl file use xml variable ATM_NCPL.

**Comment by billsacks** [comment]
If it's hard to determine which user_nl file is the problem, I'm fine with (1) not being addressed - though @jedwards4b , I do like your suggestion better - `in user_nl file`.

As for (2), I looked briefly into this: What I had forgotten in the telecon discussion a few minutes ago was that @mvertens had addressed this by adding the capability for a separate attribute named `cannot_modify_by_user_nl`. So, @jedwards4b I actually think your suggestion of changing the python is right after all.

Given this, I'm happy to take this and make the changes you suggest.
