### ISSUE TITLE
./case.build --clean-all does not remove Srcfiles and Depends

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#1431]
When I added a new file to a source directory used by cam's configure script, I expected it to automatically be seen after I ran ./case.build --clean-all. However, the ./case.build --clean-all script does not remove the Srcfiles and Depends files from the bld/atm/obj directory, and so my compilation failed. Once I manually removed these files, the compilation succeeded. I think it's reasonable to expect ./case.build --clean-all to remove those files since it doesn't take that long to recreate them anyway with a fresh search of the directories. I'd like the --clean-all function to do this (or at least another flag be added that does this).

**Comment by jayeshkrishna** [comment]
Similar discussion is in Issue #1045 (the consensus I think was to remove the entire bld directory with "--clean-all")

**Comment by rljacob** [comment]
And PR #1140 was supposed to have fixed it.  Did it not?

**Comment by jayeshkrishna** [comment]
I don't think PR #1140 modified the acme Makefile

**Comment by rljacob** [comment]
In that case, someone should make those mods to our Makefile directly in ACME-Climate/ACME.

**Comment by jgfouca** [comment]
The move to just remove the entire bld directory has solved this ticket I believe. I tested on melvin and the Srcfiles and Depends files were removed.
