### ISSUE TITLE
CESM-ECT ensemble summary files

### ISSUE THREAD

**Issue by allibco** [ESMCI/cime#1468]
Can we organize the ensemble summary files in input data as follows:

(1) Please move data from 

$CESMDATAROOT/inputdata/validation/ensembles_with_global_means/

to

$CESMDATAROOT/inputdata/validation/ensembles

(then remove inputdata/validation/ensembles_with_global_means/ )

(2) Please create a directories for he UF-CAM-ECT ensembles and the
POP-ECT ensembles:

$CESMDATAROOT/inputdata/validation/pop_ensembles
$CESMDATAROOT/inputdata/validation/uf_ensembles

**Comment by mvertens** [comment]
This is fine - and we should move forward with this. However, this is
really a CSEG issue - since I believe that ACME has its own inputdata that
is separate from CESM's. Not sure where this kind of request should go. Jim?

**Comment by fischer-ncar** [comment]
I've update the directory structure on /glade/scratch.  I still need to update the subversion data repository to reflect the changes.

**Comment by fischer-ncar** [comment]
Updated data repository
