### ISSUE TITLE
by default, only archive log files that have been gzipped.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1473]
Currently the short term archiver will move all files with *log* in them.

Instead, only archive files that have *log* and end in .gz.

Reason:  .gz files are from a successful run.  log files that have not been gzipped are from either a live run or a run that crashed and should be left in the run directory always.

**Comment by rljacob** [comment]
We're going to add an option for this in ACME but maybe it should be the default behavior.

**Comment by mvertens** [comment]
@rljacob - I'm concerned that users might want to see log files also for
runs that crashed - as a history of the run. By only archiving successful
runs - you really are losing some of the runs provenance in the archiving.
However, the problem of archiving files from a live run is concerning. I
thought that our job dependency chain prevent this from happening -
@jedwards - is this not the case?

**Comment by rljacob** [comment]
Oh the unzipped files would be left in the run directory, not deleted.  The archiver would ignore them.

Yes the job dependency chain prevents that but some ACME users want to live dangerously.

**Comment by rljacob** [comment]
Oh wait I understand what you're saying.  Even the logs from crashes are worth keeping in the archive with the successful runs so you have some evidence that there were crashes during the run.  Does that assume you were able to continue the run in some way?   If you never get around the crash, the unzipped log file will also be the last log file.

**Comment by mvertens** [comment]
Yes - often we find out that an instability sets in that  is resolved by
shortening the ocean time step for a brief part of the simulation. Or
simply restarting the model with a roundoff level perturbation in the
atmosphere.

**Comment by mfdeakin-sandia** [comment]
@mvertens Should I add a check for CESM as to whether to archive the non-gzipped log files by default?

**Comment by rljacob** [comment]
No we'll keep the default to archive all log files.  Add an option like --gzonly to only archive gzipped files.

**Comment by rljacob** [comment]
This was a discussion and the conclusion (to the question in the title) was "no".
