### ISSUE TITLE
Change lnd -> glc remapping to bilinear with a conservation correction

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1479]
Currently, the remapping from the low-resolution land grid (with elevation classes) to the high-resolution glc grid is done using conservative remapping. However, this leads to extreme grid imprinting / blockiness. @whlipscomb , in consultation with @JeremyFyke, has implemented a new scheme that uses bilinear remapping with a conservation correction. I'll bring this to master.

cc @matthewhoffman

**Comment by rljacob** [comment]
CC @stephenprice

**Comment by billsacks** [comment]
Thanks, @rljacob . @stephenprice - sorry for the omission, just a result of my being overly hasty in filing the initial issue.

@stephenprice @matthewhoffman and @JeremyFyke - My understanding from talking with Jeremy is that ACME wants these changes as well – so I plan to _not_ have backwards compatibility with the old method (since trying to support both leads to some code complexity). Please let me know if you see any problems with that.

**Comment by stephenprice** [comment]
While I suspect that we do want these changes implemented, I am going to defer to @JeremyFyke on this decision. Thanks.

**Comment by JeremyFyke** [comment]
Hey @stephenprice @rljacob @billsacks  - I concur with @billsacks, we want the new CPL-GLC remapping scheme in ACME too.  Also, I concur that retaining the old method won't be necessary in ACME - we would not use it due to excess spurious artifacts that it tends to introduce.

**Comment by stephenprice** [comment]
Thanks @JeremyFyke. Please go ahead then @billsacks, and thanks for checking with us.
