### ISSUE TITLE
Add option to only archive gzipped log files

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1485]
We want to keep the default (see issue #1473) to archive all log files.  So add an option to st_archive like --gzonly to only archive the gzipped log files.

**Comment by rljacob** [comment]
Actual option name is open for discussion.

**Comment by mfdeakin-sandia** [comment]
I was thinking --complete-logs-only or --finished-logs-only (--no-incomplete-logs and --no-unfinished-logs might be more clear) to make it clear what the option relates to, though they seem a bit verbose

**Comment by rljacob** [comment]
Verbose is ok.

**Comment by rljacob** [comment]
"Fixed in ACME"

**Comment by rljacob** [comment]
Added in #1634
