### ISSUE TITLE
python 3 format causing pylint fails 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1488]
In PR #1471 I objected to the usage of python3 syntax format statements instead of %s as used throughout the code.   Now I've noticed that this usage was introduced to the trunk in PR #1388

Master is failing pylint tests due to #1388 - while fixing the pylint test can you please revert to %s usage throughout?

**Comment by erichlf** [comment]
I can do that.

**Comment by erichlf** [comment]
So the question is why wasn't pylint failing with the other python3 string formats that already existed in the code?

**Comment by jedwards4b** [comment]
I don't know, it's also not failing on cheyenne - different pylint version maybe?

**Comment by erichlf** [comment]
@jgfouca has a fix for this.

**Comment by jgfouca** [comment]
@jedwards4b I added an additional warning ignore to code_checker, so we can use python3 string formatting. Based on my discussions with Erich, I believe the python3 format is superior, so it should be a win for us to use it in the longrun.

**Comment by jedwards4b** [comment]
I am not disagreeing that format is a superior usage.  I am arguing for consistent usage throughout the code.  I would like to use %s for now and if another PR comes up changing all %s to format then we can consider switching.

**Comment by rljacob** [comment]
Its reasonable to change them file-by-file as you go along rather then every file all at once.

**Comment by rljacob** [comment]
....but don't want to start that at this time while trying to harden for CESM2 release.

**Comment by rljacob** [comment]
Fixed by #1490
