### ISSUE TITLE
Change Python2 Strings to Python3 Strings

### ISSUE THREAD

**Issue by erichlf** [ESMCI/cime#1492]
For future compatibility we should switch strings from python2, e.g. `'%s' % var`, to python3 strings, e.g. `'{}'.format(var)`. The strength of this approach becomes obvious when we look at something like the following:
```
"%s 1 OR %s 2 OR %s 3" % ((var, ) * 3)
```
vs
```
{0} 1 or {0} 2 or {0} 3".format(var)
```

**Comment by erichlf** [comment]
One can even do the following:
```
"{var3} {var1} {var2}".format(var1=var1, var2=var2, var3=var3)
```

**Comment by rljacob** [comment]
Are we sure these 3.0 features are backwards-compatible with any unix-distro's or HPC vendors version of python 2.7 - 2.9?

**Comment by rljacob** [comment]
Related to #1488

**Comment by mfdeakin-sandia** [comment]
str.format was introduced in Python 2.6, so this should be backwards compatible with any version of Python 2.7

**Comment by mfdeakin-sandia** [comment]
Also, what is Python 2.9? Unless someone's distributing their own Python, 2.8+ doesn't exist?

**Comment by rljacob** [comment]
Sorry.  That was me assuming there's something between 2.7 and 3.0.

**Comment by erichlf** [comment]
Here is a nice cheat sheet:
http://python-future.org/compatible_idioms.html
