### ISSUE TITLE
Add option to st_archive to move files up to a certain date.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1503]
When running a long job, 36 hrs for example, it is useful to analyze model output while the simulation is running.  The diagnostic scripts should be run only on output in the short term archive.  Thus an option  to run short-term archiving while the model is running is necessary.

To make this safe, issue #1485 should be addressed.  Also, add an option to specify the maximum year number that is safe to move.  Using both should make it safe to run st_archive while a job is running.

**Comment by jedwards4b** [comment]
I don't believe that some fixed maximum year number will be adequate - what is safe to move depends on how the history files are configured.

**Comment by rljacob** [comment]
If a run directory has:
```
Wlowrmaster.cam.h0.0001-01.nc
Wlowrmaster.cam.h0.0001-02.nc
Wlowrmaster.cam.h0.0001-03.nc
Wlowrmaster.cam.h0.0001-04.nc
Wlowrmaster.cam.h0.0001-05.nc
Wlowrmaster.cam.h0.0001-06.nc
Wlowrmaster.cam.h0.0001-07.nc
Wlowrmaster.cam.h0.0001-08.nc
Wlowrmaster.cam.h0.0001-09.nc
Wlowrmaster.cam.h0.0001-10.nc
Wlowrmaster.cam.h0.0001-11.nc
Wlowrmaster.cam.h0.0001-12.nc
Wlowrmaster.cam.h0.0002-01.nc
```
I should be able to run:
`case.st_archive --finished-logs-only --upto-year 0001`
and it will 1) leave the log files alone because this run just started and none of them are zipped 2) move all the *0001* history files to the short-term archive.   That won't work?

**Comment by jedwards4b** [comment]
What if the directory also has Wlowrmaster.cam.h1.0001-01.nc?  Is that a complete year of data or is it an incomplete multiyear file?

**Comment by jedwards4b** [comment]
I'm not saying that this task is impossible, just that it's more complicated than it appears.

**Comment by mvertens** [comment]
The problem is that you its not clear what auxiliary files are partly
filled up to year 0001. What if you had a auxiliary file that asked for 10
years of data. You don't want to move that file out of the $RUNDIR during
the run until the 10 years of data are filled. The short term archiver
knows to copy that file back from short term archiving and let the run
proceed on startup. If you move it out of the way during the run you will
have a problem.

**Comment by mvertens** [comment]
I think that being able to run diagnostics during a model run would involve
only copies to the short term archiving directory and not any moves. You
really don't need a short term archiver for that - just a smarter copy
script. Then the short term archiver could move stuff at the run end and
overwrite existing files if need be - but move them out of $RUNDIR.

**Comment by rljacob** [comment]
I like that idea:  just copy as its running.

**Comment by jedwards4b** [comment]
So the option to case.st_archive should just be --copyonly

**Comment by mfdeakin-sandia** [comment]
@golaz Do you have any comments on this? This seems like a more reasonable and safer solution than the version I have on my branch now

**Comment by mfdeakin-sandia** [comment]
Should I implement this in the CESM st_archive as well?

**Comment by jedwards4b** [comment]
It would be nice to keep them in sync

**Comment by mfdeakin-sandia** [comment]
Okay. This and #1485 will come in with the next ACME to CIME merge

**Comment by rljacob** [comment]
There shall be only one case_st_archive.py

**Comment by mvertens** [comment]
There is only one case_st_archive.py - so I'm confused as to what it would
mean to "keep them in sync".

**Comment by rljacob** [comment]
Yes I'm confused what Michael meant by "Should I implement this in the CESM st_archive as well"?

**Comment by jedwards4b** [comment]
The user interface is in template.st_archive which is in the machines directory and distinct for each model, it is unlikely but possible that changes could be made for one model but not the other.

**Comment by mfdeakin-sandia** [comment]
@jedwards4b Would you have suggestions on how to modify the batch script to include the --copy-only option in a create_test? I have most of the test implemented (tenatively called ERRI), but need to add this in

**Comment by mfdeakin-sandia** [comment]
Part of the reason to use short term archiving was to reduce the directory structure gets too large, and causes issues for the centers filesystems and also information management for the user; so the critical path team is opposed to the copy option, unfortunately. They prefer the --last-date option; with the caveat that if the user screws it up, it's their fault.
If it's okay, I will have this feature just as an option in the ACME template so it won't affect CESM

**Comment by rljacob** [comment]
I didn't realize most of this could be done by altering our ACME-specific template.  In that case, yes just do it there.

**Comment by mfdeakin-sandia** [comment]
Most of the code is actually in the case_st_archive (sorry if I implied otherwise); I just didn't add the option to the CESM template

**Comment by rljacob** [comment]
I'm not sure what "to reduce the directory structure gets too large" means but a key point of the copy option is that you use it with the regular short term archiver.   So while a model is running, you can copy fresh output in to the archive.  When the model finishes, the linked regular short term-archive job will safely move all the output from the rundir to the archive, keeping the rundir from filling up.

**Comment by mfdeakin-sandia** [comment]
I think they want to keep the run directory structure small, even during runtime. I don't understand why, maybe @PeterCaldwell or @golaz could explain?

**Comment by golaz** [comment]
@rljacob : haven't we talked about all this at nausea before? :)
Having tens of thousands of files in the run directory is challenging because it slows everything down (for example ls takes tens of seconds). I'm worried about copying files because we are not talking about a small size. 30 years of low-res model output is of the order of 1.6 TB. Try copying this on Edison, it will take several hours.

**Comment by mfdeakin-sandia** [comment]
Having tens of thousands of files in the run directory shouldn't slow things down unless you're listing everything in the directory.
I forgot to mention the slow speed of copying; though that's another thing to consider (it's unfortunate HPCs don't use CoW filesystems...)

**Comment by rljacob** [comment]
We did but wasn't sure what "directory structure small" meant.  Number of files.  That makes sense.

**Comment by rljacob** [comment]
"Fixed in ACME"

**Comment by rljacob** [comment]
Leave it open until its brought over to ESMCI.

**Comment by rljacob** [comment]
Added in #1634
