### ISSUE TITLE
Logger Strings aren't Suppose to be Formatted in Place

### ISSUE THREAD

**Issue by erichlf** [ESMCI/cime#1506]
When using logging in python, string formatting is suppose to be done by the logger, e.g.
```
logger.info("doing an %s %s initial test with restart file at %s %s with pio type %s"
                   .format(str(self._stop_n), stop_option, str(rest_n), stop_option, pio_type))
```
should be 
```
logger.info("doing an %s %s initial test with restart file at %s %s with pio type %s",
                   str(self._stop_n), stop_option, str(rest_n), stop_option, pio_type)
```
https://docs.python.org/2/library/logging.html#logging.debug
http://stackoverflow.com/questions/34619790/pylint-message-logging-format-interpolation
http://stackoverflow.com/questions/20780608/how-to-log-two-variables-values-in-a-single-logging-in-python

**Comment by jgfouca** [comment]
Go ahead and do it the way it is in your first code block. I turned off the pylint warning for this because it wasn't useful.

**Comment by erichlf** [comment]
Sounds good.
