### ISSUE TITLE
config_pes_converter is broken 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1507]
I'm not sure how it ever could have worked - I am getting an error:
 No such file or directory: '../config/cesm/machines/userdefined_laptop_template/config_pes_new.xml'

But it should be opening this file to write, not to read.

**Comment by sarich** [comment]
The error probably means the directory doesn't exist, perhaps because these files and scripts have moved around a bit. I'll take a look.

**Comment by jedwards4b** [comment]
There is another error in the file you'll need to fix
 
-    CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)
+    args = CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)

**Comment by sarich** [comment]
For the first problem (no such file or directory), do you expect this script to recursively create directories if they don't exist, or just to quit gracefully with a message that the given directory is unavailable?
