### ISSUE TITLE
Log files should be more clear about cprnc comparisons

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1510]
From ACME slack:

 I'm trying to confirm that our fix to the PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel test worked. In the log, I see only one cprnc result -- that the results are different from the baseline, which we expect. Does it pass the self-comparison? I don't see that anywhere

017-05-10 00:24:31: Comparing hists for case 'PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246' dir1='/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run', suffix1='base',  dir2='/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run' suffix2='single_thread'

[8:50] 
/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246.cpl.hi.0001-01-01-16200.nc.base matched /gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246.cpl.hi.0001-01-01-16200.nc.single_thread

Jon Wolfe [8:50 AM] 
I had just searched for cprnc, which spits out the results in a long format. Most of the logs have that output

Mark Taylor [8:51 AM] 
it would provide more confidence if it said PASS after the compare - instead I believe no output at all means pass

[8:52] 
I went through this identical drill with @jgfouca a couple of weeks ago

[8:52] 
(wanted to confirm all other tests really did pass)

Jon Wolfe [8:53 AM] 
I agree, it would feel better if it actually said PASS. And It's uncomfortable to make assumptions like this, but I'll deal...

**Comment by rljacob** [comment]
+1 for adding a very clear "PASS" in the test log for each phase that passes.
