### ISSUE TITLE
Determination of primary component needs to be changed to work for user-defined compsets

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1525]
#1523 defines the "principle component" for a compset. However, the way it is determined only works for compsets with aliases, not for user-defined compsets. This determination needs to be done differently to work for user-defined compsets, so that the user mods dir defined in config_component.xml will be picked up for user-defined compsets, too.

This is also needed for #608 

cc @mvertens @jedwards4b

**Comment by rljacob** [comment]
First, it should be "principal" not "principle".   Second, a "principal component" already has an established meaning in climate stats analysis and its confusing to see it in CIME.   https://en.wikipedia.org/wiki/Principal_component_analysis

**Comment by jedwards4b** [comment]
Good grief - nominations for a different name?

**Comment by billsacks** [comment]
> First, it should be "principal" not "principle".

Good point.

> Second, a "principal component" already has an established meaning in climate stats analysis and its confusing to see it in CIME

I felt the same way.

Some options from my thesaurus: "primary"? "focal"? "cardinal"?

**Comment by rljacob** [comment]
"primary component" would work.

**Comment by mvertens** [comment]
That's fine with me.

**Comment by billsacks** [comment]
This was fixed via #1546
