### ISSUE TITLE
Add in CRU V7 forcing

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1526]
We need to add in the ability to handle CRUNCEP version 7 atmosphere forcing for CLM into datm. This will match the way CRUV5 forcing is done. We expect to get a new set of CRU forcing each year, and we'll want the ability to run with the new version at least locally at NCAR. Versions that are released will also be imported into subversion inputdata.

**Comment by mvertens** [comment]
Can you please take this on?

**Comment by ekluzek** [comment]
Yes, I already assigned myself to it.

*Erik Kluzek, (CGD at NCAR)*

*National Center for Atmospheric Research*

*Boulder CO, *

*(off) (303)497-1326 (fax) (303)497-1348*

*(skype) ekluzek    (cell) (303)859-0183*

*Pronouns: he/his/him*

*------------------ Home page ------------------------*

*          http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*

*          https://staff.ucar.edu/users/erik
<https://staff.ucar.edu/users/erik>*

*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*
