### ISSUE TITLE
minor datm and docn changes

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1527]
**DOCN**
- Introduce ability to use a netCDF file for the aquaplanet SST (instead of the analytic SST). Test this with the following example untested dataset: 
`/glade/p/work/brianpm/model_data/sst_c4aquasom_0.9x1.25_clim.c170512.nc`
The idea is to provide this capability in advance of users asking us how to do it. This can be implemented as another aquaplanet model and could be specified in a user compset similarly to the other analytic SST options.

-  In env_run.xml,  need to fix  description  of DOCN_MODE for sst_aquapN 

- QPC4 with non-standard SSTs:  SST values 1-9 look fine but for SST10 it uses SST1.  so the problem seems to be how datamode gets set in docn_in.  Is the “0” in “AQP10” somehow getting chopped off?  

**DATM**
- DATM%S1850-> DATM%CPLHIST

**Comment by billsacks** [comment]
@mvertens - should we add this to the cesm2 milestone?

**Comment by mvertens** [comment]
Yes. I just added it - thanks for pointing this out.
