### ISSUE TITLE
PROXY not set on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1534]
On anlworkstation, there is a error during phase CREATE_NEWCASE: No variable PROXY found in case

In config/acme/machines/config_machines.xml, some machines define a PROXY element (melvin, sandia-srn-sems, anlworkstation, skybridge, redsky). For anlworkstation, this element is empty:
`<PROXY></PROXY>`

Should we set PROXY for anlworkstation or it can be deleted?

**Comment by jedwards4b** [comment]
I believe that this problem was introduced in PR #1517 - can you confirm that removing the PROXY element from config_machines.xml for your system solves the problem?  Thanks,

**Comment by dqwu** [comment]
@jedwards4b 
Yes, it works if we remove this element for anlworkstation.

**Comment by dqwu** [comment]
@jgfouca 
This issue is reproducible again. The empty proxy tag was removed in PR #1590, but it was added back by PR #1634 during the merge.
