### ISSUE TITLE
gx1v7 domain file

### ISSUE THREAD

**Issue by dabail10** [ESMCI/cime#1538]
The scripts are pointing to domain.ocn.gx1v7.151020.nc and should be pointing to domain.ocn.gx1v7.151008.nc. This causes errors in cases that use the DOCN.

Dave

**Comment by mnlevy1981** [comment]
This also affects cases that use the DICE component (C compsets fail because DICE needs the domain file; G compsets run fine because neither POP nor CICE need it).

**Comment by mvertens** [comment]
Could you please assign this to Jim or me with a critical issue and we'll
try to get it through for the next alpha tag.

**Comment by dabail10** [comment]
How does one make it critical?
