### ISSUE TITLE
Add f19_g17 resolution.

### ISSUE THREAD

**Issue by dabail10** [ESMCI/cime#1539]
We are going to need 2-degree FV mapping files to gx1v7 very soon. I think for the tutorial we will be running f19_g37. However, we need some help on this.

Dave

**Comment by billsacks** [comment]
Needed for cesm2?

**Comment by dabail10** [comment]
I believe it is, as this is the paleo configuration.

Dave

**Comment by rljacob** [comment]
@dabail10 can you fix the title to be a short sentence in "verb noun" format?

**Comment by mvertens** [comment]
@mlevy - would you be willing to take this on?

**Comment by mnlevy1981** [comment]
I can get these maps built tomorrow, but I'm a little confused by the request -- the tutorial is going to be `f19_g37`, so we want `f19_g17` supported in the CESM 2.0 release?

**Comment by dabail10** [comment]
I did mix the two things up. Let me double check with a few people, but it was my understanding that f19_g17 would be needed in CESM2.

**Comment by mnlevy1981** [comment]
Mapping and domain files are in ` /glade/p/work/mlevy/maps_and_domains/f19_g17` if you want to test things out.

You should use the `domain.ocn.gx1v7.151008.nc` that is already in inputdata (I have verified that the file I generated is slightly different due to being generated on cheyenne instead of yellowstone, but I will not bring it to the inputdata directory)

**Comment by mvertens** [comment]
I am really confused. It looks like the latest CIME master for creating an
ocean domain file (for docn) is pointing to

/glade/p/cesmdata/cseg/inputdata/share/domains/
domain.ocn.fv0.9x1.25_gx1v7.151008.nc

but this file does not exist.  Where is it in inputdata? If it is there - I
believe it has been put in the wrong location.

**Comment by mnlevy1981** [comment]
I made the T62_g17 maps / domain files on Oct 8, 2015, so that led to

```
domain.lnd.T62_gx1v7.151008.nc
domain.ocn.T62_gx1v7.151008.nc
domain.ocn.gx1v7.151008.nc
```

Which are all in `/glade/p/cesmdata/cseg/inputdata/share/domains/`. Then, on Oct 20, I made the f09_g17 maps / domains. That lead to three files:

```
domain.lnd.fv0.9x1.25_gx1v7.151020.nc
domain.ocn.fv0.9x1.25_gx1v7.151020.nc
domain.ocn.gx1v7.151020.nc
```

The first two files are in the same directory, but the last file was identical to `domain.ocn.gx1v7.151008.nc` so it was not copied to inputdata. That means there is a date mismatch on the files you use when you run f09_g17:

```
domain.lnd.fv0.9x1.25_gx1v7.151020.nc
domain.ocn.gx1v7.151008.nc
```

The file you were looking for (`domain.ocn.fv0.9x1.25_gx1v7.151008.nc`) should have the 151020 datestamp, but it's only used for f09_f09 runs (it is the ocean mask on the f09 grid).

Dave needs to test f19_g17 with

```
domain.lnd.fv1.9x2.5_gx1v7.170518.nc
domain.ocn.gx1v7.151008.nc
```

**Comment by dabail10** [comment]
These changes work with my aux_cice tests. Here are the config_grids.xml changes using Mike's temporary path:

[dbailey@yslogin4 cesm]$ svn diff config_grids.xml 
Index: config_grids.xml
===================================================================
--- config_grids.xml	(revision 8270)
+++ config_grids.xml	(working copy)
@@ -971,6 +971,8 @@
       <nx>144</nx>  <ny>96</ny>
       <file grid="atm|lnd" mask="gx1v6">domain.lnd.fv1.9x2.5_gx1v6.090206.nc</file>
       <file grid="ocnice"  mask="gx1v6">domain.ocn.1.9x2.5_gx1v6_090403.nc</file>
+      <file grid="atm|lnd" mask="gx1v7">/glade/p/work/mlevy/maps_and_domains/f19_g17/domain.lnd.fv1.9x2.5_gx1v7.170518.nc</file>
+      <file grid="ocnice"  mask="gx1v7">/glade/p/work/mlevy/maps_and_domains/f19_g17/domain.ocn.fv1.9x2.5_gx1v7.170518.nc</file>
       <file grid="ocnice"  mask="null">domain.aqua.fv1.9x2.5.nc</file>
       <desc>1.9x2.5 is FV 2-deg grid:</desc>
     </domain>
@@ -1089,8 +1091,8 @@
 
     <domain name="gx1v7">
       <nx>320</nx>  <ny>384</ny>
-      <file grid="atm|lnd">$DIN_LOC_ROOT/share/domains/domain.ocn.gx1v7.151020.nc</file>
-      <file grid="ocnice">$DIN_LOC_ROOT/share/domains/domain.ocn.gx1v7.151020.nc</file>
+      <file grid="atm|lnd">/glade/p/work/mlevy/maps_and_domains/f19_g17/domain.ocn.gx1v7.170518.nc</file>
+      <file grid="ocnice">/glade/p/work/mlevy/maps_and_domains/f19_g17/domain.ocn.gx1v7.170518.nc</file>
       <desc>gx1v7 is displaced Greenland pole 1-deg grid with Caspian as a land feature:</desc>
     </domain>
 
@@ -1257,6 +1259,13 @@
       <map name="OCN2ATM_SMAPNAME">cpl/cpl6/map_mp120v1_to_fv0.9x1.25_aave_da_111004.nc</map>
     </gridmap>
 
+    <gridmap atm_grid="1.9x2.5" ocn_grid="gx1v7">
+      <map name="ATM2OCN_FMAPNAME">/glade/p/work/mlevy/maps_and_domains/f19_g17/map_fv1.9x2.5_TO_gx1v7_aave.170518.nc</map>
+      <map name="ATM2OCN_SMAPNAME">/glade/p/work/mlevy/maps_and_domains/f19_g17/map_fv1.9x2.5_TO_gx1v7_blin.170518.nc</map>
+      <map name="ATM2OCN_VMAPNAME">/glade/p/work/mlevy/maps_and_domains/f19_g17/map_fv1.9x2.5_TO_gx1v7_patc.170518.nc</map>
+      <map name="OCN2ATM_FMAPNAME">/glade/p/work/mlevy/maps_and_domains/f19_g17/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc</map>
+      <map name="OCN2ATM_SMAPNAME">/glade/p/work/mlevy/maps_and_domains/f19_g17/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc</map>
+    </gridmap>
     <gridmap atm_grid="1.9x2.5" ocn_grid="gx1v6">
       <map name="ATM2OCN_FMAPNAME">cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v6_aave.130322.nc</map>
       <map name="ATM2OCN_SMAPNAME">cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v6_blin.130322.nc</map>
