### ISSUE TITLE
Add per-user option to not delete tests once they are run 

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1543]
Users are asking for older results to be archived instead of blown away.

**Comment by jgfouca** [comment]
@ndkeen

**Comment by rljacob** [comment]
Discussion during telecon:  wish is for case directories to be kept.   They would be if ACME Jenkins didn't blow them away.  @ndkeen did you want nightly tests to keep accumulating?  Please clarify this request.

**Comment by jgfouca** [comment]
@ndkeen waiting for you to comment on this one.

**Comment by ndkeen** [comment]
Yes, it would be nice for acme_developer tests to simply remain in place.  This allows us to look at the log files and debug issues more quickly.  Additionally, with a series of acme_developer directories, one can use grep to identify when something changed.  Just let the scratch monster remove them as they age.

**Comment by jgfouca** [comment]
@ndkeen interesting, what's the "scratch monster" and how often does it run?

**Comment by jedwards4b** [comment]
Purging the scratch directory is a machine dependent option outside of cime control - we should probably not depend on it for testing.

**Comment by jgfouca** [comment]
We could maybe have a PURGE_OLD_TESTS setting in config_machines.xml?

**Comment by ndkeen** [comment]
I'm not sure what you are proposing here and how it depends on CIME.  What I'm asking for is within the testing workflow.  Run the tests, and don't copy/move/rename, just leave them.  There is a purge that will happen on scheduled basis, but even if it doesn't, you would not be able to run enough acme_devs for it to matter.

**Comment by ndkeen** [comment]
When I run acme_developer, the tests aren't purged.  So there must be something in the test workflow that is happening.

**Comment by jgfouca** [comment]
@ndkeen the purge is done by jenkins_generic_job.py

**Comment by ndkeen** [comment]
What does it take to change jenkins_generic_job.py?

**Comment by jgfouca** [comment]
@ndkeen it's easy to change, but we need to think of the best way to do it. The only thing I can think of is to add a variable to ACME's xml set, JENKINS_PURGE_TESTS, default it to True, and set it to false for edison and cori. Then have jenkins_generic_job.py look at that value before it does the purge.
