### ISSUE TITLE
comp_pes incorrect in timing file?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1545]
I've noticed this on both hobart and cheyenne, as recently as `cime5.3.0-alpha.12`: the `comp_pes` column in the table near the top of the `cesm_timing.$CASE` file to be off by a factor of two (or maybe I don't know what `comp_pes` is supposed to be?). This is true for all components, not just the coupler... I cut the output for brevity. And while I'm making a ticket, the stride column doesn't quite line up with the header -- looks like it needs 3 more spaces or so.

```
  component       comp_pes    root_pe   tasks  x threads instances (stride) 
  ---------        ------     -------   ------   ------  ---------  ------  
  cpl = cpl        48          0        24     x 1       1      (1     ) 
```

and

```
  component       comp_pes    root_pe   tasks  x threads instances (stride) 
  ---------        ------     -------   ------   ------  ---------  ------  
  cpl = cpl        240         0        60     x 2       1      (1     ) 
```

**Comment by mnlevy1981** [comment]
And maybe this is machine dependent? Numbers look okay on cheyenne, but off on yellowstone

**Comment by jedwards4b** [comment]
I think that this is fixed in the latest cime - do you want to take a look @mnlevy1981 
if you disagree, please refer to a specific case in your comments.

**Comment by mnlevy1981** [comment]
I just checked two cases and hobart is showing `24 x 1 = 24` while yellowstone says `32 x 1 = 32` so I think it's okay. Thanks for taking care of this!
