### ISSUE TITLE
Change README to remove table and history

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1562]
I'd like to propose a change to the README file.

Instead of a table with person, years, versions, funding, lets just list names and institutions without versions.   We can have three groups of names:
Lead developers: (Jim and Jim go here in alphabetical order)
Developers: (everyone currently working on it in alphabetical order with institution in parenthesis)
Former Developers:  (everyone who once contributed to CIME but not currently working on it in alphabetical order with institution in parenthesis)

The institution will imply the funding.   We can also add a sentence like we have on the wiki  "CIME is developed by the ACME and CESM projects."

We don't need to indicate what version people worked on because that's a headache and bound to be inaccurate as people go on and off development.  Also versions 1-4 were never released so there's no point in recounting that history.

I also want to delete the history of CIME because its not relevant for a README or interesting to users.

One of the github heads and a good blog post on what should be in a README:
http://ben.balter.com/2017/04/14/your-projects-readme-is-your-project-constitution/

**Comment by rljacob** [comment]
cc @agsalin @mvertens

**Comment by billsacks** [comment]
Sounds good to me.

@gold2718 may also have thoughts.
