### ISSUE TITLE
Incorrect date stamps on two domain files with gx1v7 mask

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1565]
When you set up a D compset with `g17_g17` resolution, you run into the following issue (this was reported in #1538)

```
$ grep DOMAIN env_run.xml 
    <entry id="ATM_DOMAIN_FILE" value="domain.ocn.gx1v7.151020.nc">
```

(The issue being that file does not exist). Also, when you run `preview_namelist` in an F compset with the `f09_f09_mg17 ` resolution you get an error pointing to a similar issue:

```
File not found: domainfile = "/glade/p/cesmdata/cseg/inputdata/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151008.nc", will attempt to download in check_input_data phase
```

PR coming shortly.

**Comment by mvertens** [comment]
Thanks so much for resolving these issues.
