### ISSUE TITLE
Should we remove this message from case.setup output?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1571]
Whenever I run ./create_test ... then ./case.setup, I get a message like this:

```
/glade/p/work/sacks/cime/scripts/check_int_rest_0519b/env_mach_specific.xml already exists, delete to replace
```

The wording of this message suggests that something is wrong, but it appears that this file always exists and so there's really nothing wrong. I'm a fan of only having messages like this if they likely signal a problem, to avoid the "crying wolf" syndrome of error messages (where you start to just ignore messages like this). So I propose removing this message.

**Comment by mvertens** [comment]
I agree. I found this confusing as well. If we could remove it before the
release that would be great.

**Comment by jedwards4b** [comment]
The point of the message is that if you change config_machines.xml you need to manually delete the env_mach_specific.xml in your case for that change to take effect.   Maybe I can only print it if the timestamp on config_machines.xml (or .cime/config_machines.xml)) is newer than env_mach_specific.xml

**Comment by rljacob** [comment]
Discussion on telecon.   Change "delete to replace" to "will not replace".   Indicates that something is not quite as expected but you don't have to do anything.
