### ISSUE TITLE
adding new testmods directory to drv does not work

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1579]
I am trying to add some more tests to verify that docn changes are bfb.
As part of this I'd like to ensure that cpl history output is generated so that comparisons can be easily made. The testmods directory is the following (as specified in `config_files.xml`)
`<value component="drv"    >$CIMEROOT/src/drivers/mct/cime_config/testdefs/testmods_dirs</value>
`
In my sandbox, I added a new directory 
`$CIMEROOT/src/drivers/mct/cime_config/testdefs/testmods_dirs/default`
that had a simply shell_commands file with the relevant xmlchange commands to get the output.

I tried to create the following test and got the following error output:

```
/glade/u/home/mvertens/src/cesm2_0_alpha06l.docnmods/cime/scripts> ./create_test SMS.f19_g16_rx1.A.cheyenne_intel.default
Testnames: ['SMS.f19_g16_rx1.A.cheyenne_intel.default']
Using project from env PROJECT: P93300606
Creating test directory /glade/scratch/mvertens/SMS.f19_g16_rx1.A.cheyenne_intel.default.20170520_115346_ddogd9
RUNNING TESTS:
  SMS.f19_g16_rx1.A.cheyenne_intel.default
Starting CREATE_NEWCASE for test SMS.f19_g16_rx1.A.cheyenne_intel.default with 1 procs
Finished CREATE_NEWCASE for test SMS.f19_g16_rx1.A.cheyenne_intel.default in 0.009212 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /glade/scratch/mvertens/SMS.f19_g16_rx1.A.cheyenne_intel.default.20170520_115346_ddogd9
    Errors were:
        Test 'SMS.f19_g16_rx1.A.cheyenne_intel.default' failed in phase 'CREATE_NEWCASE' with exception 'need more than 1 value to unpack'
          File "/glade/p/work/mvertens/cesm2_0_alpha06l.docnmods/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 583, in _run_catch_exceptions
            return run(test)
          File "/glade/p/work/mvertens/cesm2_0_alpha06l.docnmods/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 377, in _create_newcase_phase
            (component, modspath) = test_mods.split('/',1)

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL SMS.f19_g16_rx1.A.cheyenne_intel.default (phase CREATE_NEWCASE)
    Case dir: /glade/scratch/mvertens/SMS.f19_g16_rx1.A.cheyenne_intel.default.20170520_115346_ddogd9
test-scheduler took 0.205597162247 seconds

```
The test SMS.f19_g16_rx1.A.cheyenne_intel worked fine.

**Comment by mvertens** [comment]
The following seems to fix this problem.
If the default/ directory is moved into the testmods_dirs/drv/default and the testname is
SMS.f19_g16_rx1.A.cheyenne_intel.drv-default
Then things seem to work.
However, there is an assumption in test-scheduler that there is another level of directory:
`(component, modspath) = test_mods.split('/',1)
`
A better error statement is needed - or this should be generalized so that this is not required for cesm.

**Comment by jedwards4b** [comment]
I don't understand why that code is there - it should get that from config_files.xml I think.

**Comment by mvertens** [comment]
It does get it from config_files.xml - but then this is used to parse
possible subdirectories I believe.
