### ISSUE TITLE
Under certain conditions results from streams can vary by a small amount near roundoff

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1580]
I found this with the new stream for CLM for finundation which only has a single point in time, hence you expect results to be independent of time and identical for any time you give it (with tax_mode='extend'). What I found was that answers vary to small amount which effected some exact restart tests. For things where roundoff level changes grow in time and effect other variables this can have an impact on the model.

A ERS_D_Ld3.f10_f10.IHISTCLM50BGC.cheyenne_intel.clm-decStart test failed with this problem until I no longer set the current time, but held it constant for this stream. This is with cime5.3.0-alpha.02 and ^clm2/branches/ndep with the following change to chFInundatedStreamType.F90

```
===================================================================
--- ch4FInundatedStreamType.F90	(revision 85237)
+++ ch4FInundatedStreamType.F90	(working copy)
@@ -154,11 +154,11 @@
          ! Explicitly set current date to a hardcoded constant value. Otherwise
          ! using the real date can cause roundoff differences that are
          ! detrected as issues with exact restart.  EBK M05/20/2017
-         !call get_curr_date(year, mon, day, sec)
-         year = 1996
-         mon  = 12
-         day  = 31
-         sec  = 0
+         call get_curr_date(year, mon, day, sec)
+         !year = 1996
+         !mon  = 12
+         !day  = 31
+         !sec  = 0
          mcdate = year*10000 + mon*100 + day
 
          call shr_strdata_advance(sdat, mcdate, sec, mpicom, 'ch4finundated')

```

I don't know that we'll fix this one (and labeled it as a wontfix) and certainly won't for CESM2.0. But, I did want it documented.

**Comment by billsacks** [comment]
If I understand this right, this seems like a bad thing that could bite other people in the future. So I'm removing the wontfix label.

In your comment in the CLM code, can you point to this issue, to help remind us that we can remove that workaround if/when this issue is resolved?

**Comment by billsacks** [comment]
@ekluzek since this was presumably an issue with the mct-based streams that we're not using anymore, I'm closing this issue.
