### ISSUE TITLE
Add file driven aquaplanet to DOCN 

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1581]
Present DOCN aquaplanet modes are analytic. There is a desire to also have file driven aquaplanet capability as another mode.

**Comment by rljacob** [comment]
What is "file driven aquaplanet capability"?

**Comment by mvertens** [comment]
Its aquaplanet forcing from a file rather than from analytic conditions.

**Comment by rljacob** [comment]
Ok.  I keep forgetting Aquaplanet is fixed SST but the SST is global.

Is there a mode where the slab ocean is global?

**Comment by mvertens** [comment]
Yes the mode where slab ocean is global is DOCN%SOMAQP. I recent introduced
this. So we now have both a aquaplanet slab ocean, aquaplanet prescribed
ssts and aquaplanet file input ssts. This will be useful for atmosphere
model development.
