### ISSUE TITLE
grid attribute not checked when doing compset matches

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1583]
config_compsets.xml files occasionally list a grid attribute on the compset line. An example from cime is:

```xml
  <compset grid="r%rx1">
    <alias>AIAF</alias>
    <lname>2000_DATM%IAF_SLND_DICE%IAF_DOCN%IAF_DROF%IAF_SGLC_SWAV</lname>
  </compset>
```

According to @mvertens (see discussion on #1582 ), this is supposed to stop you from creating a case with the given compset unless the grid matches the given expression. But this doesn't seem to be working. For example, cime master let me run the following without complaint:

```
./create_test --no-build --test-root . SMS.f19_g16_r01.AIAF.yellowstone_intel
```

- where I'm using a rof grid that does not match 'r%rx1'.

**Comment by billsacks** [comment]
(For the record, I don't view this as "critical", but @mvertens asked me to add that label.)

**Comment by jedwards4b** [comment]
I think that trying to use the grid attribute in this file creates a recursive situation in which the compset is needed to get the grid but the grid is needed to get the compset.

**Comment by jedwards4b** [comment]
The result of discussion - this is a circular dependency and the grid attribute should be removed from config_compsets.xml

**Comment by mvertens** [comment]
@billsacks - I am assigning this to you since you had a clear idea of where compsets had a grid attribute.
