### ISSUE TITLE
PGI 17.04 available on hobart

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1599]
Mark Moore installed PGI 17.04 on hobart -- I verified that the following change in `config_machines.xml`

```
-       <command name="load">compiler/pgi/15.1</command>
+       <command name="load">compiler/pgi/17.04</command>
```

Lets me build / run a CECO compset (PGI 16 and earlier wouldn't build; 17.1 builds but won't run), but I'm hoping to avoid being the one that does more rigorous testing.

Priority-wise: it would be nice to have this in CESM 2, but it's not critical from my point of view so I'll let others decide if it should have the cesm2 milestone or not.

**Comment by jedwards4b** [comment]
Given the current state of PGI compiler it can't hurt - please add a PR with this change.

**Comment by mnlevy1981** [comment]
will do -- just setting up a clean sandbox before submitting the PR
