### ISSUE TITLE
MODEL_BUILD requires more processors than available.

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1600]
Just got the folllowing message when trying to build on a laptop:
``` 
Phase 'MODEL_BUILD' for test 'SMS.T42_T42.S.elm_gnu' required more processors, 4, than this machine can provide, 2
```

Do we really need an error here?  Can't we adjust to the number of available processors?

**Comment by mvertens** [comment]
I think it would be a really good idea to adjust the number of available
processors for the build and just issue an warning. That would be extremely
helpful for the CESM2 release.
