### ISSUE TITLE
GNU update on Hobart

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1601]
GNU 4.8.5 will not build code that is slated for the CAM trunk. GNU 5.4.0 is available and works with this code. Are there any objections to updating the Hobart GNU compiler version?
The mod seems to work for F compsets, I am trying some A and B compsets.

One wrinkle is that GNU 5.4.0 uses openmpi and the other compilers use mvapich2 so one has to specify --mpilib openmpi on the create_newcase or create_test command line since the XML does not currently allow one to specify a default MPI library on a per-compiler basis.

**Comment by bertinia** [comment]
Fixed with #1729
