### ISSUE TITLE
compare_test_results generates error, "Could not find a matching MPI for attributes"

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1607]
Out of cime master (on yellowstone), I did:

```
./create_test --test-root . --walltime 0:30 ERS_Ld3.f45_g37_rx1.A.yellowstone_intel
```

then when it completed

```
Tools/compare_test_results -b cesm2_0_alpha06m --baseline-root $CESMDATAROOT/ccsm_baselines -r . -t 20170525_094940_daztcr
```

This gave:

```
ERROR: Could not find a matching MPI for attributes: {'mpilib': 'mpich2', 'threaded': False, 'compiler': 'intel'}
```

I just ran into similar errors with somewhat older versions of cime - going back to at least cime5.3.0-alpha.13

**Comment by jgfouca** [comment]
I'm unable to duplicate this error on melvin and do not have access to yellowstone. It probably has something to do with CESM configuration, so reassigning to @jedwards4b
