### ISSUE TITLE
Add some more debug flags with gnu

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1621]
@rljacob pointed out that ACME has some extra flags beyond what we now have for gnu (even with #1618 ) (see https://github.com/ESMCI/cime/pull/1618#issuecomment-304458178). They add `-Og` and `-fbacktrace` in both FFLAGS and CFLAGS in DEBUG mode. We should consider doing that, too. They also add 'invalid' to the 'ffpe-trap' list, though I'm a little wary of doing that based on my experience showing that the gnu isnan intrinsic barfs when you give it a signaling NaN with 'invalid' in this list of checks (isn't the whole point of isnan that you should be able to check for NaN values?)

I don't want to add these extra flags unless someone ( @jedwards4b ?) signs off on them, since I don't completely understand the implications.

**Comment by billsacks** [comment]
Regarding adding 'invalid' to the 'ffpe-trap' list, and the problem with isnan: The ideal way to allow this may be to take advantage of the fact that - I think - recent versions of gfortran support Fortran 2003 ieee arithmetic, and modify shr_infnan_mod accordingly (rather than having special code for gnu in there). (I made some preliminary, feeble attempts at this which did not meet with success, but I'm hopeful that a more concerted effort would allow this to work.)

If this is not possible, then maybe we could back off the compiler flags just for shr_infnan_mod using the Depends.gnu mechanism for the system build, and some other mechanism for the CMake-based unit test build.

**Comment by billsacks** [comment]
Actually, I'll take this: I'm finally making some headway on gnu's NaN handling, so I'll combine the changes here with that fix and then run a bunch of testing with gnu.

**Comment by fischer-ncar** [comment]
-Og and -fbacktrace didn't break alpha/beta testing.

**Comment by billsacks** [comment]
Great, thanks for checking. If you've already done this, then go ahead and merge it and I'll do the other piece separately.

**Comment by fischer-ncar** [comment]
Is there a PR associated with this issue?

**Comment by billsacks** [comment]
No, not yet. I was going to work on it today, but haven't made any actual mods yet.

**Comment by billsacks** [comment]
@fischer-ncar - I ended up getting stuck on adding `-ffpe-trap=invalid` (see my comments in #1763 ). So it would be great if you could take this back on after all, adding `-Og -fbacktrace`.

**Comment by billsacks** [comment]
Okay, turns out I've been able to make some progress after all, so I'm taking this back and combining it with what is likely to become a PR when I return.
