### ISSUE TITLE
Need domain files for new gx1v7 mask for SE grids: ne30, ne60, ne120, ne240

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1624]
We need to create domain files for the new gx1v7 mask for SE grids: ne30, ne60, ne120, ne240 and add them to config/cesm/config_grids.xml. I'm not sure who should be assigned to do this.

@mvertens

**Comment by fischer-ncar** [comment]
What about ne30, I have an ne30_g17 test.  But if ne30 isn't supported I can change the test.

**Comment by mvertens** [comment]
I am not sure all of these domain files are needed - and certainly not
before the release. I think just ne30 and possibly ne120 will be sufficient
- but I will check.

**Comment by ekluzek** [comment]
For CLM we have a bunch of tests at ne30 and ne120, and a few at ne60. I'm going to keep them at g16 until we have domain files at g17 available.

**Comment by mvertens** [comment]
I don't think you should be testing CLM at ne120 for I compsets. Definitely
also for ne60. I'll make sure this is clarified with the AMP group as soon
as possible.

**Comment by gold2718** [comment]
CAM-SE is not supported* for the release. We would love to have the ability to run AMIP at NE30 and NE120 (as well as NE5 and NE16) but none of that is critical for the release. We do not plan on doing anything with NE60.

*By not supported, we mean that simple models and aquaplanet compsets will run with analytic initial conditions but there will be no initial data files (ncdata) for CAM-SE in CAM's namelist defaults.

**Comment by gold2718** [comment]
@ekluzek: Most of these resolutions were implemented in PR #1896
The holdout at this point is ne240 since a 1 degree mask does not make much sense. Is there a high-res mask available?

**Comment by ekluzek** [comment]
@gold2718, there's a 10th degree mask (tx0.1v2).

**Comment by gold2718** [comment]
Is the tx0.1v2 domain compatible with the v6 or v7 domains (i.e., where is the Caspian Sea)?

**Comment by ekluzek** [comment]
It's old enough that it most likely includes the Caspian as part of the ocean (so compatible with gx1v6). Does that mean we need to ask for a new tx0.1v3 domain that moves the Caspian to land?

**Comment by gold2718** [comment]
I do not know the answer to that question. What prompted this issue?

**Comment by mvertens** [comment]
@gold2718, @ekluzek - is there an update on this and is this still needed for the CESM2 release? If so who will take this on?

**Comment by ekluzek** [comment]
@mvertens in looking back through, I don't see it ever decided who would work on this nor what it's priority is. I certainly haven't done anything for it. If it's important we need to decide what we are going to do and who is going to do it.

**Comment by gold2718** [comment]
I am going out on a limb and say that while these files are still desirable, this is not a priority for the CESM2 release. I base this on our decision that the only supported CAM-SE use cases for CESM2 are simple physics and aquaplanet. The release will not contain initial data or topography files for F or B cases.

**Comment by mvertens** [comment]
@gold2718 - I think this makes sense. I think we should create a new
cesm2.1 milestone and simply move this issue there.

**Comment by ekluzek** [comment]
@gold2718 can you comment on if this is needed by Friday?

**Comment by gold2718** [comment]
CAM-SE is still unsupported in CESM2.1 (same status as CESM2.0) so this issue should be moved to CESM2.2.

**Comment by gold2718** [comment]
Pretty sure this has been fixed.
