### ISSUE TITLE
CIME assumes all output from "module" commands are errors

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#1625]
I realized this when I was loading a module on Summitdev at OLCF that always gives output, and ./case.setup failed. The details are below, and this is for commit 7822b6b8903feb26c4171160423b472351ddb035. ~~Also, I noticed that the cime/utils/python/CIME directory now only contains compiled python code. Am I missing something, or do we no longer have access to the CIME python source code?~~ Nevermind, I found the cime/scripts/lib/CIME directory now. Thanks.

```
[imn@summitdev-login1:~/ACME/cime/scripts/summit_test1] 8-) ./case.setup 
ERROR: module command module load DefApps failed with message:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
There are messages associated with the following module(s):
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

DefApps:
   Please report any missing or needed software versions to help@olcf.ornl.gov
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Just to be sure about this, I tested a module ls command, and got the following:

```
[imn@summitdev-login1:~/ACME/cime/scripts/summit_test1] 8-) ./case.setup 
ERROR: module command module ls  failed with message:
Currently Loaded Modules:
  1) xl/20161123   2) spectrum_mpi/10.1.0.2-20161221   3) hsi/5.0.2.p5   4) xalt/0.7.5   5) DefApps   6) python/3.5.2
```

**Comment by mrnorman** [comment]
I should also mention that the Lmod system we're using likes to give output, so this is causing errors with every configuration I've tried so far.

**Comment by mrnorman** [comment]
Also, when I try to do a module purge and then see what's listed out:

```
 17     <modules>
 18       <command name="purge"/>
 19       <command name="ls"/>
```

I get:

```
[imn@summitdev-login1:~/ACME/cime/scripts/summit_test1] >:O ./case.setup 
ERROR: module command module ls  failed with message:
Currently Loaded Modules:
  1) xl/20161123   2) spectrum_mpi/10.1.0.2-20161221   3) hsi/5.0.2.p5   4) xalt/0.7.5   5) DefApps
```

So clearly the module purge isn't actually working. Is there a different way I should be doing this?

**Comment by mrnorman** [comment]
OK, I see the offending problem. Our module system puts all output to stderr instead of stdout, even though it returns a 0 exit code (see below). In cime/scripts/lib/CIME/XML/env_mach_specific.py, the stderr is tested, and if it contains anything, it fails with:

```
225             stat, py_module_code, errout = run_cmd(cmd)
226             expect(stat==0 and len(errout) == 0,
227                    "module command %s failed with message:\n%s"%(cmd,errout))
```

Can we change this to just say "expect(stat==0,...)"?


```
[imn@summitdev-login1:~/ACME/cime/scripts/lib/CIME] 8-) module add DefApps 2> /dev/null
[imn@summitdev-login1:~/ACME/cime/scripts/lib/CIME] 8-) module add DefApps 1> /dev/null
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
There are messages associated with the following module(s):
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

DefApps:
   Please report any missing or needed software versions to help@olcf.ornl.gov
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[imn@summitdev-login1:~/ACME/cime/scripts/lib/CIME] 8-) 
```

**Comment by mrnorman** [comment]
Also, I looked, and Titan does the same thing by putting the output into stderr by default, so this change would seem necessary in both cases. Titan's modules just don't output text as often.

**Comment by mrnorman** [comment]
I'm not sure why CIME isn't succeeding in the module purge. When I run the following, it works:

```
  1 #!/usr/bin/env python
  2 
  3 execfile('/sw/summitdev/lmod/7.4.0/rhel7.2_gnu4.8.5/lmod/7.4/init/env_modules_python.py')
  4 
  5 module('purge')
  6 module('ls')
```

Is something different happening in CIME?

**Comment by mrnorman** [comment]
So, I think I should separate these issues and handle the failed module purge in a separate issue. To fix the stderr problem, I propose the following change to both allow the scripts to keep going and print out the output from stderr from the module command.

```
         for cmd in self._get_module_commands(modules_to_load, "python"):
             logger.debug("module command is %s"%cmd)
             stat, py_module_code, errout = run_cmd(cmd)
-            expect(stat==0 and len(errout) == 0,
+            print(errout)
+            expect(stat==0,
                    "module command %s failed with message:\n%s"%(cmd,errout))
             exec(py_module_code)
```

**Comment by mrnorman** [comment]
Well, a better diff is:

```
index 14083b7..73fc073 100644
--- a/cime/scripts/lib/CIME/XML/env_mach_specific.py
+++ b/cime/scripts/lib/CIME/XML/env_mach_specific.py
@@ -223,7 +223,9 @@ class EnvMachSpecific(EnvBase):
         for cmd in self._get_module_commands(modules_to_load, "python"):
             logger.debug("module command is %s"%cmd)
             stat, py_module_code, errout = run_cmd(cmd)
-            expect(stat==0 and len(errout) == 0,
+            if ( len(errout) != 0 ) :
+                print(errout)
+            expect(stat==0,
                    "module command %s failed with message:\n%s"%(cmd,errout))
             exec(py_module_code)
```

**Comment by jgfouca** [comment]
@mrnorman due to the shell function implementation of module, we often cannot rely on sane return codes which is why the code looks for stderr instead. I can't think of a good alternative at the moment.

**Comment by jgfouca** [comment]
Closing. Still no way avoid this problem due to env modules not using return codes. The lmod issues were fixed in ACME.

**Comment by lvankampenhout** [comment]
I ran into the same problem on the Dutch supercomputer Cartesius , which displays an informational message when the NetCDF library is loaded. 

However, contrary to the argument made above that module shouldn't route text to stderr, the message I see appears to be stdout output: 

```
$ module load netcdf-c/impi/intel/4.3.3.1 >text 2>error
$ cat text
load NETCDF C Parallel Library for Intel MPI 5 or higher (SURFSARA_NETCDFC_ROOT,SURFSARA_NETCDFC_LIB,SURFSARA_NETCDFC_INCLUDE).
```
Any thoughts? I have a workaround (as proposed by MrNorman in https://github.com/ESMCI/cime/issues/1625#issuecomment-305172013 ) but it doesn't seem right that stdout from module is seen as an error. Using CIME version https://github.com/CESM-Development/cime/tags/cime5.4.0-alpha.18

**Comment by jgfouca** [comment]
I can take a look.

**Comment by jgfouca** [comment]
@lvankampenhout , can you 'cat error' in your example above?

**Comment by lvankampenhout** [comment]
```
$ module load netcdf-c/impi/intel/4.3.3.1 >text 2>error
$ cat text
load NETCDF C Parallel Library for Intel MPI 5 or higher (SURFSARA_NETCDFC_ROOT,SURFSARA_NETCDFC_LIB,SURFSARA_NETCDFC_INCLUDE).
$ cat error 
$ file error
error: empty
```

**Comment by jgfouca** [comment]
@lvankampenhout , @mrnorman  , I have made changes to CIME such that you can configure a machine to not interpret stderr output from modules as errors. Change the XML configuration for the machine as follows:

```
<module_system type="module" allow_error="true">
```

@lvankampenhout , I'm wondering why you were seeing this problem in the first place since the module operation didn't produce any stderr output?

**Comment by mrnorman** [comment]
Sounds great! Minor request: Can we change it to allow_stderr instead of allow_error, just to be a bit clearer?
