### ISSUE TITLE
CIME is highly prone to race conditions

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1628]
... in the various env xml files.

A recent minor change on the ACME side exposed the races and took many hours to sort out due to their intermittent nature.

Calls to case.set_value that occur outside of case_setup are very risky.

Other risky calls are things like restore, which swaps out the underlying XML file but doesn't necessarily update the in-memory values in the case object. Maybe some kind of tracking of timestamps or checksums of the underlying XML files should be done in the case object to ensure things are in sync.

**Comment by mvertens** [comment]
Can you give some examples of when this occurs.

**Comment by mvertens** [comment]
@jgfouca - this is being used extensively in the buildnml and buildcpp of all data models and CESM prognostic components that have had their buildnml pythonized. Can you please give an example in ACME where this occurred. Would a case.flush() have prevented this race condition (my guess is no). I believe that preview_namelists is not called in parallel - so that would not cause a race. Is it being caused in the build phase?

**Comment by mvertens** [comment]
@jgfouca - so I just checked and case.set_value and restore are not called by any of the cime components or driver. However, they do appear in the cam, cice, and pop cime_config/buildcpp scripts. Would the race condition appear there?

**Comment by jgfouca** [comment]
@mvertens sorry for slow response. GitHub seems to be sending me like 20% of the emails I should be getting. Pythonization goes a long way towards eliminating races because it allows things to use the case object directly instead of having to flush XML files to disk and then forking a subprocess, so you guys are probably OK for now.

**Comment by jedwards4b** [comment]
It would really help if an example were include with this issue.

**Comment by rljacob** [comment]
On Slack, @jgfouca said "just do a set_value on something that's in env_build.xml".   And I think if you run a test suite you'll see it in some of the tests.  Its a race so may or may not happen.

**Comment by jedwards4b** [comment]
Components should not run set_value or xmlchange on env_build.xml during the build phase if we want to maintain the ability to do parallel builds - however I don't know of a way to strictly enforce this rule.

**Comment by rljacob** [comment]
More comments from Slack:  
JimF:  "a PR for ACME introduced a set_value to every case object upon case initialization, this caused the impacted XML file to be re-written every time the case was flushed.  and it caused mayhem in our system"
JimF: " I believe it was between case.flush() and the build system."
JimF: "I think it was in the __exit__ method of case"

**Comment by jedwards4b** [comment]
The only way I see to prevent this is to clearly document that you cannot do a set_value in the case __init__ method.

**Comment by jedwards4b** [comment]
@jgfouca Can we create a test to assure that instantiating and a case object does not invoke a flush and add it to scripts_regression_tests.   Does this look like it would work?

With Case(caseroot, read_only=False) as case:
   expect(not case._env_files_that_need_rewrite, "Instantiating a case should not trigger a flush call")
