### ISSUE TITLE
are externals genf90 and CMake still external?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1637]
Is the code in src/externals/genf90 and src/externals/CMake still maintained as externals?   That is, do we ever try to update from or make PRs to the upstream masters for those codes?  Or are the versions in this repo now the master?

CMake upstream master:  https://github.com/CESM-Development/CMake_Fortran_utils
genf90 upstream master: https://github.com/PARALLELIO/genf90

**Comment by billsacks** [comment]
For CMake_Fortran_utils, we're no longer treating this as an external as far as I know, so in my view this could be moved fully into cime (I just don't know the process for doing that).

I can't speak to genf90.

**Comment by jedwards4b** [comment]
genf90 is used and maintained by PIO and so is a valid external.

**Comment by rljacob** [comment]
Ok.

Since its a subtree, all we have to do for CMake is move its directory out of "externals"

**Comment by rljacob** [comment]
Question answers and new issue opened.
