### ISSUE TITLE
--user-mods-dir does not handle relative paths correctly

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1642]
If I try to create a case like this:

```
./create_newcase --case test_usermods_rel_noinclude_0605a --compset A --res f45_g37_rx1 --user-mods-dir ../src/drivers/mct/cime_config/testdefs/testmods_dirs/drv/default
```

I get:

```
ERROR: Directory not found /Users/sacks/cime/src/drivers/mct/cime_config/usermods_dirs/../src/drivers/mct/cime_config/testdefs/testmods_dirs/drv/default
```

This works if I give an absolute path, but if I give a relative path, it tries to make the path relative to `/Users/sacks/cime/src/drivers/mct/cime_config/usermods_dirs/` (for this case... probably some other location in other cases), rather than relative to the current directory.

This was previously issue #497 , which was supposedly fixed by #501.

**Comment by billsacks** [comment]
Okay, from some playing around with this, I gather that this was set up so that --user-mods-dir works analogously to the testmods directory in a test, but relative to the primary component's (I think) cime_config/usermods_dirs directory. While I see a little rationale for that, I mainly find it unintuitive, particularly since it isn't documented. I'd find it much more intuitive if relative paths were taken as relative to the current directory, since this is typical unix behavior and it would better support user-mods directories that some user has created and put in some arbitrary location.

**Comment by billsacks** [comment]
@ekluzek @bandre-ucar and @olyson - having played around with this for CLM, do you have any feelings on how this should work?

**Comment by olyson** [comment]
I would prefer relative paths that are relative to the current directory.
So, instead of doing this:

--user-mods-dir /glade/p/work/oleson/clm4_5_16_r243/components/clm/cime_config/usermods_dirs/clm/clm5_OutputCrop

I would do this:

--user-mods-dir clm/clm5_OutputCrop

which is how it was intended to work?  And documentation about where usermods are supposed to go (components/clm/cime_config/usermods_dirs/clm).

**Comment by billsacks** [comment]
Ah, I think I see the problem, and also how to make it support both "true" relative paths and paths relative to the primary component's cime_config... I'll work on a fix.
