### ISSUE TITLE
Would this be a way we could convert ERS and ERP to SystemTestsCompareTwo?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1647]
We previously felt that it would be challenging to rewrite ERS and ERP using the SystemTestsCompareTwo infrastructure because we couldn't see a way to have the clone case do a restart of the original case (see also some discussion in #448 and #824 ). But would this be a way to do it?: Name the clone case the same as the original case, just in a different location, and then link to the necessary rpointer and restart files before running case2.

The reason for doing this is that we keep running into problems with the ERP test (e.g., see #1640). I believe this test would be more robust and maintainable if it were converted to the SystemTestsCompareTwo infrastructure, since this would streamline the test and remove the need for resetting things in between runs.

More specifically: Currently, the SystemTestsCompareTwo infrastructure would set things up like this if we tried to write ERS using that framework:

```
Case directories:

ERS.f45_g37_rx1.A.cheyenne_intel
-- ERS.f45_g37_rx1.A.cheyenne_intel.rest

Build & run directories:

ERS.f45_g37_rx1.A.cheyenne_intel
-- bld
-- run

ERS.f45_g37_rx1.A.cheyenne_intel.rest
-- bld
-- run
```

What if we change the organization to this?

```
Case directories:

ERS.f45_g37_rx1.A.cheyenne_intel
-- rest_case
---- ERS.f45_g37_rx1.A.cheyenne_intel

Build & run directories:

ERS.f45_g37_rx1.A.cheyenne_intel
-- bld
-- run
-- rest_case
---- ERS.f45_g37_rx1.A.cheyenne_intel
------ bld
------ run
```

I **think** it works to have two cases have the same name as long as the case directories, bld & run directories all appear in different places, as laid out above. If so, this could be a way to have the clone case do a CONTINUE_RUN from the original case.

Does anyone see any critical flaws with this?

cc @mvertens @jedwards4b @jgfouca @rljacob @mfdeakin-sandia

**Comment by billsacks** [comment]
#1855 rewrites ERP as suggested here, but doesn't touch ERS. We may still want to rewrite ERS in a similar way (as @jgfouca did in #1830 ) for consistency, unless people want to keep ERS as simple as possible. @jedwards4b @mvertens @jgfouca do you have thoughts on this?

**Comment by mvertens** [comment]
@billsacks - I think for now we should leave the ERS test as simple as
possible until we really flush out the usage of the ERP tests and then
determine if this is really how we want to re-implement the ERS tests.

**Comment by jgfouca** [comment]
@billsacks I'm ok leaving it alone for now. Closing
