### ISSUE TITLE
Need better description of CCSM_BGC and related namelist variables

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1650]
The description of CCSM_BGC in src/drivers/mct/cime_config/config_component_cesm.xml and config_component_acme.xml needs to be improved: I can't understand what it does based on this description:

```xml
    <desc>Flag to turn on new fields in coupling.
    If the value is not none, the coupler is compiled so that optional
    BGC related fields are exchanged between component models.
    </desc>
```

I think it's wrong to say "the coupler is compiled...", because this is now a runtime option. More importantly, the meaning of each value (CO2A, CO2B, etc.) should be given here.

The descriptions of related namelist variables in namelist_definition_drv.xml should similarly be improved - e.g.

```xml
    <desc>
      Previously, new fields that were needed to be passed between components
      for certain compsets were specified by cpp-variables. This has been
      modified to now be use cases. This use cases are specified in the
      namelist cpl_flds_inparm and are currently triggered by the xml variable CCSM_BGC.
      If CCSM_BGC is set to 'CO2A', then flds_co2a will be set to .true.
    </desc>
```

I think most of this description (all but the last line) is wrong. And the last line tells me how this is set, but not what it does.

cc @mvertens @klindsay28 @ekluzek

**Comment by ekluzek** [comment]
@billsacks I agree. We don't need to talk about the past and how these used to be CPP tokens. The important part is to define the current usage and what the different options do: none, CO2A, CO2B, CO2C. Each of those options should be defined.
