### ISSUE TITLE
No handlers could be found for logger "CIME.utils"

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#1651]
ACME master hash a4bc319d281259c3ce50122a2b76e10f465832fc

./create_newcase -compset FC5AV1C-04P2 -res ne16_ne16 -case test -mach titan -project stf006
cd test
./case.setup

[imn@titan-ext7:~/ACME/cime/scripts/get_data_downloaded] 8-) ./case.setup 
Machine/Decomp/Pes configuration has already been done ...skipping
If an old case build already exists, might want to run 'case.build --clean' before building
Generating component namelists as part of setup
Creating component namelists
   Running cam buildnml
CAM writing dry deposition namelist to drv_flds_in 
Writing ocean component namelist to ./docn_in 
CAM writing namelist to atm_in
   Running clm buildnml
ERROR: Command: '/autofs/nccs-svm1_home2/imn/ACME/components/clm/cime_config/buildnml /autofs/nccs-svm1_home2/imn/ACME/cime/scripts/get_data_downloaded' failed with error 'No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
No handlers could be found for logger "CIME.utils"
** source directory does not exist: /autofs/nccs-svm1_home2/imn/ACME/components/clm/src/external_models/fates/main
ERROR clm.buildnml: /autofs/nccs-svm1_home2/imn/ACME/components/clm/bld/configure    -comp_intf MCT   -phys clm4_5 -phys clm4_5 -cppdefs -DMODAL_AER  -usr_src /autofs/nccs-svm1_home2/imn/ACME/cime/scripts/get_data_downloaded/SourceMods/src.clm failed: 512'

**Comment by mrnorman** [comment]
Happens for FC5AV1C-L too. Also forgot to mention this is on Titan.

**Comment by mrnorman** [comment]
Resolved by running "git submodule update --init" from the repo root dir.

**Comment by jgfouca** [comment]
The 'no handlers' warning can be ignored. It just means somewhere you're using non-posix options (-longopt instead of --longopt).

**Comment by pwolfram** [comment]
@jgfouca, should this warning always be reported (or at least only once)?  I'm getting it too and each time I see it I feel concerned, even though it obviously isn't a big deal.  Is there some way ithe warning could be caught and processed better?  I'm happy to help if needed because it sounds like it could be caught in some type of try-catch block during the argument parsing based on your comment above.  Thanks!

cc @jonbob and @vanroekel

**Comment by rljacob** [comment]
This has been fixed on the ESMCI master and ACME will get that fix after the pending CIME update is merged.

**Comment by rljacob** [comment]
Change the title to the actual source of the error.

**Comment by pwolfram** [comment]
Awesome, thanks @rljacob!
