### ISSUE TITLE
Indentation error in case_st_archive.py

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1654]
In cime/scripts/lib/CIME/case_st_archive.py, in function `_archive_restarts`, we have:
```
    if datename_is_last or case.get_value('DOUT_S_SAVE_INTERIM_RESTART_FILES'):
        if not os.path.exists(archive_restdir):
            os.makedirs(archive_restdir)

    # archive the rpointer file(s) for this datename and all possible ninst_strings
    _archive_rpointer_files(case, archive, archive_entry, archive_restdir,
                            datename, datename_is_last)
```
Since the function, `_archive_rpointer_files`, assumes that `archive_restdir` exists, the call should be indented one level.
Reported by Thomas Toniazzo

**Comment by jedwards4b** [comment]
I think this is incorrect.  The directory may already exist, indentation is valid as is.

**Comment by gold2718** [comment]
But if the directory does _not_ exist and you call `_archive_rpointer_files`, then you get an error because `archive_restdir` is assumed to exist. Moving it in one level means that `_archive_rpointer_files` is only called if `datename_is_last or case.get_value('DOUT_S_SAVE_INTERIM_RESTART_FILES')` is `True`.
Do you want to archive the rpointer files if neither of those is true?

**Comment by jedwards4b** [comment]
On further review I think that you are correct.

**Comment by jedwards4b** [comment]
The indentation is fine, the tests for dataname_is_last and DOUT_S_SAVE_INTERIM_RESTART_FILES is repeated inside _archive_rpointer_files.     This indicates that the code structure could be improved, but there is no bug here.
