### ISSUE TITLE
Nightly tests on cheyenne are using a very old cime version

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1655]
I checked the recent nightly (or really multiple-times-per-day) cime tests on cheyenne, such as http://my.cdash.org/testDetails.php?test=32154280&build=1223429 and these are all using a very old cime version:

```
$ git show 9d9f09c19a67c237837ed826a58e6b5bbcf5895d
commit 9d9f09c19a67c237837ed826a58e6b5bbcf5895d
Merge: a99eab3 cedf8f0
Author: jedwards4b <jedwards@ucar.edu>
Date:   Tue Apr 18 11:46:37 2017 -0600

    Merge pull request #1370 from ESMCI/jgfouca/minor_fix_for_cheyenne

    Fix NODEFAIL test on cheyenne.
```

**Comment by billsacks** [comment]
The nightlies on melvin look okay, so I'm guessing there's a cron job or something on yellowstone that needs to get restarted.

**Comment by jedwards4b** [comment]
Yes I had an error in the path that was causing the cime version not to be updated.   Fixed now.
