### ISSUE TITLE
Schemas validity error on Mira/Cetus in phase 'XML'

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1659]
I tried the following test on Mira/Cetus with the latest cime master:
`./create_test SMS.T42_T42.S`

Errors were:
`Test 'SMS.T42_T42.S.cetus_ibm' failed in phase 'XML' with exception 'ERROR: Command: '/usr/bin/xmllint --noout --schema /gpfs/mira-home/dqwu/Test_CIME/config/xml_schemas/env_mach_specific.xsd /projects/HiRes_EarthSys_2/dqwu/SMS.T42_T42.S.cetus_ibm.20170608_163553_2kzoez/env_mach_specific.xml' failed with error '/projects/HiRes_EarthSys_2/dqwu/SMS.T42_T42.S.cetus_ibm.20170608_163553_2kzoez/env_mach_specific.xml:11: element init_path: Schemas validity error : Element 'init_path': This element is not expected. Expected is one of ( cmd_path, modules ).`

This issue starts after PR #1461 is merged. Any machine files to be updated for Mira/Cetus to pass the schema validation?

**Comment by jedwards4b** [comment]
This is a problem with the order of init_path and cmd_path in config_machines, 
all of the init_path statements should precede the cmd_path statements.
