### ISSUE TITLE
Flgl_qice name/attname consistency

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1660]
In seq_flds_mod, there seems to be an inconsistency in the name and attname for this variable,

     name = 'Flgl_qice'
     longname = 'New glacier ice flux'
     stdname  = 'ice_flux_out_of_glacier'
     units    = 'kg m-2 s-1'
     attname  = 'Fgll_qice'

should it be Flgl or Fgll.  Some new code I'm working on picked up on this and barfed out an error.  I believe name and attname should always be the same in CESM for all coupling fields.

**Comment by billsacks** [comment]
Thanks for catching this... it looks like this was probably just a typo. This is a flux from land to glc, so I'm thinking the right thing is Flgl_qice... do you agree?

Hmmm, but then I see this at the top of seq_flds_mod:

```Fortran
  !    example: Fall => atm/lnd flux computed by lnd
```

so I'm not sure what the convention is (if any), in terms of which component's letter comes first. Do you know?

And do you happen to know how (if at all) attname is currently used in the coupler - i.e., what might have been affected by this typo?

**Comment by rljacob** [comment]
The convention for Fxyz is "flux between x and y computed on the z grid".   The ordering of x and y is arbitrary (I think).    So Fxyz = Fyzx

**Comment by apcraig** [comment]
With regarding to naming convention.  The convention just indicates what two components are involved, not anything about src and dst.  So Flgl and Fgll are both valid as far as I'm concerned.  I would use Flgl.

This probably didn't affect anything in CESM.  It might have had an impact in the ESMF interfaces and it was caught by the prototype NUOPC implementation, but CESM/mct doesn't care about those attributes.  Everything triggers off the field names.  In fact, looking a bit more at the code, we should use Flgl for the field/att name because that's the what's used in prep_glc_mod.F90.
