### ISSUE TITLE
Do we still want the `--pesfile` argument to create_newcase?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1665]
Now that `--pesfile` is no longer a required argument when you're running with a user-compset (thanks, @jedwards4b !): Do we still want this argument for create_newcase?

If we do keep it, the help text needs to be fixed. Currently it says:

```
  --pesfile PESFILE     Only used and required for --user-compset
                        argument.Full pathname of the pes specification
                        fileThis argument is required if --user-compset is
                        TrueThe file can follow either the config_pes.xml or
                        the env_mach_pes.xml format (default: None)
```

This is incorrect on two points:

(1) It can be used whether or not you're using a `--user-compset`

(2) It is **not** required any more.

**Comment by jedwards4b** [comment]
I think that we do want to keep it with documentation:

Full pathname of an optional pes specification
file.  The file can follow either the config_pes.xml or
the env_mach_pes.xml format (default: None)

**Comment by billsacks** [comment]
Okay, I'll add that in an upcoming PR.
