### ISSUE TITLE
Review and edit help documentation for user-facing scripts

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1668]
The help documentation (what you get with `-h`) of many of our user-facing scripts could use some minor editing for grammar and whitespace, and possibly some heavier editing for general understandability.

One example is a lack of whitespace between words which arises from having python code like this:

```python
    parser.add_argument("--user-grid", action="store_true",
                        help="If set, then the -grid argument is treated as a user specified grid."
                        "As such, the additional argument --gridfile must also be specified"
                        "and all of the grid settings in the --res argument name (which must be a grid longname"
                        "have been defined in the grid file pointed to by --gridfile")
```

– note the lack of spaces before the closing quotes on each line, leading to help text that looks like this:

```
  --user-grid           If set, then the -grid argument is treated as a user
                        specified grid.As such, the additional argument
                        --gridfile must also be specifiedand all of the grid
                        settings in the --res argument name (which must be a
                        grid longnamehave been defined in the grid file
                        pointed to by --gridfile (default: False)
```

Here is a list of what I see as the most critical user-facing scripts. I suggest that we check each one off as someone goes through and edits it (or determines that it doesn't need editing):

Top-level scripts:

- [x] create_clone
- [x] create_newcase
- [x] create_test
- [x] manage_pes (edit: we're planning to remove this)
- [x] manage_testlists (edit: this is gone now)
- [x] query_config
- [x] query_testlists

Scripts created (linked) in caseroot:

- [x] archive_metadata.sh (edit: no longer part of cime)
- [x] case.build
- [x] case.cmpgen_namelists
- [x] case.qstatus
- [x] case.setup
- [x] case.submit
- [x] check_case
- [x] check_input_data (see https://github.com/ESMCI/cime/issues/1668#issuecomment-388194634)
- [x] pelayout (deferred to #2573 )
- [x] preview_namelists
- [x] preview_run
- [x] xmlchange
- [x] xmlquery

This does not include scripts in scripts/Tools/ or elsewhere; given our limited time, I'd consider those to be lower priority.

**Comment by billsacks** [comment]
cc @bertinia @mvertens

**Comment by mvertens** [comment]
@billsacks - thanks for pointing this out and listing out the files that
need to be reviewed.
@bertinia - which files are you willing to take on?
@billsacks - which files are you willing to take on?
I'll do the rest.

**Comment by billsacks** [comment]
I took care of query_testlists via #1669 . I'm happy to take a few others - I don't care which ones.

**Comment by mvertens** [comment]
@billsacks - should we be working off of one branch? Its really confusing to address this PR if we are all working on different branches. Can I please create a branch - mvertens/clean_user_facing_scripts on esmci and we could all work off that that branch? Or how do you envision collectively addressing this?

**Comment by rljacob** [comment]
One branch per script (or maybe set of related scripts) to change.  Each branch from master.  one PR per branch.  You need to communicate here which script you're starting work on so someone else doesn't make a branch for it.

**Comment by billsacks** [comment]
@mvertens - I agree with @rljacob : I am a fan of small, short-lived branches. The problem I see with one big branch for this is that I may not get a chance to do my piece of this for a few weeks, at which point it's possible that some of these scripts will have diverged from master. It also makes reviewing the final PR rather overwhelming.

**Comment by bertinia** [comment]
I'm currently working on archive_metadata in branch bertinia/archive_metadata (CESM only)

I'll also work on:

create_test with Chris
manage_pes
query_config
manage_testlists

Please assign me any additional scripts in the caseroot that need to be updated.

**Comment by billsacks** [comment]
@bertinia and @fischer-ncar I'd like to somewhat arbitrarily make the following assignments. These don't necessarily need a lot of work, but it would be good if someone could at least give each of these a quick once-over:

@bertinia 

- [ ] create_clone
- [ ] create_newcase
- [ ] manage_pes
- [ ] query_config
- [ ] archive_metadata.sh

@fischer-ncar 

- [ ] create_test
- [ ] case.cmpgen_namelists
- [ ] check_case
- [ ] check_input_data
- [ ] pelayout

Myself:

- [ ] case.build
- [ ] case.setup
- [ ] case.submit
- [ ] preview_namelists
- [ ] preview_run
- [ ] xmlchange
- [ ] xmlquery

**Comment by bertinia** [comment]
archive_metadata.sh is no longer part of CIME. The updated archive_metadata python script will be included with CESM2.1 as part of the CMIP6 release. Couple of questions/comments:

1. Please be sure that all in-line style formatting in the python script examples text is removed. This formatting isn't rendered nicely by sphinx as part of the auto-generated documentation (see the example text here: http://esmci.github.io/cime/Tools_user/check_case.html)
2. the script help text should be cross-checked in the sphinx RST source to make sure it is consistent. For example, the create_newcase --h text should match what is described in the RST source text here: http://esmci.github.io/cime/users_guide/create-a-case.html

**Comment by fischer-ncar** [comment]
One thing I've noticed across all help pages is
`        -h, --help     show this help message and exit`
I think the s in show should be capitalized in Readme.configure.

There's also an inconsistent use of periods.  Sometimes it's there, sometimes it's not.  I think the sentences should have the periods.  Does anyone disagree?

**Comment by billsacks** [comment]
@bertinia - @mvertens reassigned your outstanding sections to herself, since you're taking vacation soon. Please let us know if you've done anything on this so Mariana doesn't redo your work.

**Comment by billsacks** [comment]
Regarding @fischer-ncar 's comment (https://github.com/ESMCI/cime/issues/1668#issuecomment-385017569): It looks like, `show this help message and exit` is something generated by argparse. While we could control this, it looks like more trouble than it's worth: see https://stackoverflow.com/questions/35847084/customize-argparse-help-message

**Comment by billsacks** [comment]
I notice that many of our scripts override the default usage message, instead providing a custom usage message. Particularly for simple scripts, I find the default usage message more helpful than the one we've been providing. So I plan to let argparse generate its own usage message for at least some scripts. @mvertens let me know if you have thoughts on this.

An example is 4e9e88828 which changes the usage message to:

```
usage: case.cmpgen_namelists [-h] [-d] [-v] [-s] [-c] [-g]
                             [--compare-name COMPARE_NAME]
                             [--generate-name GENERATE_NAME]
                             [--baseline-root BASELINE_ROOT]
                             [caseroot]
```

rather than the incomplete (and incorrect)

```
usage:
case.cmpgen_namelists [<casedir>] [--verbose]
OR
case.cmpgen_namelists --help

EXAMPLES:
    # Setup case
    > case.cmpgen_namelists
```

**Comment by jgfouca** [comment]
@billsacks , I think having EXAMPLES is pretty important. Maybe we just need to fix the documentation?

**Comment by mvertens** [comment]
@billsacks - I completely agree. However, this also effects other scripts like create_test. What should we do there?

**Comment by billsacks** [comment]
@jgfouca I agree that examples are very important for scripts with complex sets of options. I didn't feel the example provided any value in this case for case.cmpgen_namelists, because it just showed running the script without any options. I can maintain that example, though, if you feel it's useful to have examples even in simple cases like this.

We don't have to choose between the default usage message vs. examples: we can do both. For example, see `scripts/query_testlists`, which gives:

```
usage: query_testlists [-h] [-d] [-v] [-s] [--count]
                       [--list {category,categories,machine,machines,compiler,compilers}]
                       [--show-options] [--define-testtypes]
                       [--xml-category XML_CATEGORY]
                       [--xml-machine XML_MACHINE]
                       [--xml-compiler XML_COMPILER]
                       [--xml-testlist XML_TESTLIST]

Script to query xml test lists, displaying all tests in human-readable form.

Usage:
   ./query_testlists [--show-options] [--define-testtypes]
      Display a list of tests
   ./query_testlists --count
      Count tests by category/machine/compiler
   ./query_testlists --list {category,categories,machine,machines,compiler,compilers}
      List the available options for --xml-category, --xml-machine, or --xml-compiler

   All of the above support the various --xml-* arguments for subsetting which tests are included.
```

So there are two separate questions here:

(1) In general (at least for scripts with a manageable number of options) should we let argparse generate its default usage message?

(2) Should we always have examples, or only in non-trivial cases?

**Comment by billsacks** [comment]
@jgfouca - to keep you in the loop: @mvertens and @jedwards4b feel that we should generally go to something like what's done for `query_testlists`. Let us know if you feel differently.

**Comment by mvertens** [comment]
@billsacks - I have just pushed these type of changes to create_test  in
the branch we are both working on. Please have a look and see if the new
examples makes sense.

**Comment by billsacks** [comment]
@mvertens That looks really good to me. I made some minor tweaks to keep the documentation self-consistent, such as removing angle brackets from arguments (e.g., changing "<TESTNAME>" to just "TESTNAME", since that's how it's shown elsewhere in the documentation). See 2990758d4.

**Comment by billsacks** [comment]
@mvertens - can you please take check_input_data - or assign to someone who knows more about it?

1. Examples should show an example of both using it to check and using it to download, I think... but I'm not familiar enough with this to know if these are actually two different, valid uses

2. The protocol and server arguments are unclear. An example would help clarify how these should be used. e.g., what are the allowed values for protocol, and what format should the server argument take?

3. The information on "input data" in `running-a-case.rst` is wrong and needs to be updated.

**Comment by billsacks** [comment]
@mvertens - can you please assign `pelayout` to someone who knows more about it than I do? It's unclear to me how this is supposed to be used. It _seems_ like there are two usages: one to query and one to set, but I can't tell how the setting is supposed to work.

For example, based on the documentation, I thought this would work:

`./pelayout --set-ntasks 3`

but it gave:

```
Traceback (most recent call last):
  File "./pelayout", line 215, in <module>
    _main_func()
  File "./pelayout", line 206, in _main_func
    modify_ntasks(case, int(set_ntasks))
  File "./pelayout", line 181, in modify_ntasks
    "Task change invalid for {}" % comp)
TypeError: not all arguments converted during string formatting
```

**Comment by jedwards4b** [comment]
this is another redundant tool that I feel could be removed.

**Comment by billsacks** [comment]
@jedwards4b are you referring to pelayout or check_case?

**Comment by jedwards4b** [comment]
both pelayout and check_case are redundant and can be removed.

**Comment by rljacob** [comment]
Huh?  No you can not remove "./pelayout".  That prints the layout to the screen which is very useful as you try different things.

**Comment by billsacks** [comment]
@rljacob do you or someone else understand it well enough to review its documentation? See https://github.com/ESMCI/cime/issues/1668#issuecomment-388195928

**Comment by jedwards4b** [comment]
./xmlquery NTASKS NTHRDS ROOTPE 
```
Results in group mach_pes
	NTASKS: ['CPL:1', 'ATM:1', 'LND:1', 'ICE:1', 'OCN:1', 'ROF:1', 'GLC:1', 'WAV:1', 'ESP:1']
	NTHRDS: ['CPL:1', 'ATM:1', 'LND:1', 'ICE:1', 'OCN:1', 'ROF:1', 'GLC:1', 'WAV:1', 'ESP:1']
	ROOTPE: ['CPL:0', 'ATM:0', 'LND:0', 'ICE:0', 'OCN:0', 'ROF:0', 'GLC:0', 'WAV:0', 'ESP:0']
```

**Comment by jedwards4b** [comment]
I think @gold2718 wrote the pelayout tool but I really think xmlquery is the way to go.

**Comment by rljacob** [comment]
Yuck no.  This is much cleaner:
```
Comp  NTASKS  NTHRDS  ROOTPE
CPL :    108/     1;      0
ATM :    108/     1;      0
LND :     36/     1;    108
ICE :    108/     1;      0
OCN :     36/     1;    108
ROF :     36/     1;    108
GLC :      1/     1;      0
WAV :      1/     1;      0
ESP :      1/     1;      0
```

**Comment by gold2718** [comment]
I love it when we reach consensus so rapidly :) I propose that the pelayout discussion move to a new issue that addresses any documentation issues as well as the fact that some options seem to have been broken in the big python string rewrite (one year ago yesterday).
pelayout also needs to deal with the problem that the ESP component always seems to be assigned one MPI task when it should get all of them (or is that yet another issue).

**Comment by billsacks** [comment]
@jedwards4b I'd like to remove this from the xmlquery help since we don't have anything like this for most scripts; is that okay with you?

```
If this tool is missing any feature that you need, please go to github and create an issue (https://github.com/ESMCI/cime/issues). Detailed information is available at https://github.com/ESMCI/cime.


    AUTHOR AND CREDITS
        Authors: Jim Edwards , ....

        Based on legacy code with many contributers. (see ...)

    COPYRIGHT AND LICENSE

        This library is free software; you can redistribute it and/or modify
        it under the same terms as Python itself.
```

**Comment by jedwards4b** [comment]
Fine with me, I think that it was actually @jgfouca who added it.

**Comment by billsacks** [comment]
@jedwards4b @jgfouca I'm changing xmlquery and xmlchange to give the double-dash version of arguments before the old, single-dash version. For example, I'm changing things like:

```
    parser.add_argument("-subgroup","--subgroup",
```

to

```
    parser.add_argument("--subgroup","-subgroup",
```

The reason is that this makes the double-dash version appear in argparse's auto-generated usage message.

Will this have any consequences that I'm not aware of?

**Comment by jgfouca** [comment]
@billsacks , that should be fine. You may want to do a simple test afterwards to make sure both versions still work.

**Comment by billsacks** [comment]
> @billsacks , that should be fine. You may want to do a simple test afterwards to make sure both versions still work.

Yup, both still work.
