### ISSUE TITLE
Top-level cime_config/usermods_dirs incorrectly added to list of all_user_mods

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1673]
If a component defines a COMPNAME_USER_MODS (e.g., CAM_USER_MODS) entry in config_component.xml, but the value for the current case ends up being blank, we are getting incorrect behavior: The expected behavior is that no user mods directory would be included; the actual behavior is that it tries to pull in user mods from PRIMARY_COMPONENT/cime_config/usermods_dirs . This often will be harmless, because that directory won't contain any user_nl files or others (it typically just contains some subdirectories with the actual user mods). But it's confusing, and it could give wrong behavior if that directory happened to include any files that matched names that are expected in a user_mods directory (e.g., user_nl files).

I have seen this in the latest cesm2_0_alpha06 sandbox, with cime at master, using:

```
./create_newcase --case test_case_configure_0609h --res f09_g16 --mach yellowstone --project P93300601 --compset B1850
```

This prints:

```
This component includes user_mods
Adding user mods directory /glade2/scratch2/sacks/cesm_code/cesm2_0_alpha06_newCime/cime_config/usermods_dirs
```

As far as I can tell, this compset isn't supposed to be pulling in any user mods, at least based on this section in CAM's config_component.xml:

```xml
  <entry id="CAM_USER_MODS">
    <type>char</type>
    <valid_values></valid_values>
    <default_value></default_value>
    <values>
    <value compset="DOCN%AQP3">$SRCROOT/components/cam/cime_config/usermods_dirs/aquap</value>
    <value compset="DOCN%SOMAQP">$SRCROOT/components/cam/cime_config/usermods_dirs/aquap</value>
    <value compset="HIST_CAM60_CLM50%BGC">$SRCROOT/components/cam/cime_config/usermods_dirs/fhist</value>
    <value compset="2000_CAM60_CLM50%BGC">$SRCROOT/components/cam/cime_config/usermods_dirs/f2000</value>
    </values>
    <group>run_component_cam</group>
    <file>env_case.xml</file>
    <desc>User mods to apply to specific compset matches.   These usermods will be used only if
                cam is the principle component in the compset (F or Q compsets) </desc>
  </entry>
```

From tracing this in a debugger, I think the problem arises from case.py: apply_user_mods . I don't completely understand this, but my guess is that in this:

```python
            comp_user_mods = self.get_value("{}_USER_MODS".format(component.upper()))
            if comp_user_mods is not None:
                all_user_mods.append(comp_user_mods)
```

It's getting a `comp_user_mods` of an empty string rather than None, so then it appends an empty string onto the `all_user_mods` list. If that analysis is right, then I think we want to change two instances of

```python
        if comp_user_mods is not None:
```

to something like

```python
        if comp_user_mods is not None and not comp_user_mods.isspace():
```

But I'm not very confident of my analysis, and would like to get another set of eyes on this.

**Comment by billsacks** [comment]
I think I see a solution that fixes the bug and at least should do no harm, so I'm confident enough to take this issue.

**Comment by mvertens** [comment]
My understanding of CAM_USER_MODS was that it would only be used when cam is the primary component. That is evident in the documentation. I'm not sure when the following was introduced in CAM_USER_MODS:
```
       <value compset="HIST_CAM60_CLM50%BGC">$SRCROOT/components/cam/cime_config/usermods_dirs/fhist</value>
    <value compset="2000_CAM60_CLM50%BGC">$SRCROOT/components/cam/cime_config/usermods_dirs/f2000</value>
```   
 This usage is inconsistent with the stated description.
