### ISSUE TITLE
Should the case directory be removed when create_newcase has an error?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1674]
First let me say: cime is now much better than the scripts used to be about not creating a case directory if there was an error in create_newcase. However, some errors generated late in the create_newcase process can still leave you with a possibly-invalid case directory.

An example is errors in case.py: apply_user_mods, e.g., triggered with this artificial change:

```diff
diff --git a/scripts/lib/CIME/case.py b/scripts/lib/CIME/case.py
index b9bb56e..792f222 100644
--- a/scripts/lib/CIME/case.py
+++ b/scripts/lib/CIME/case.py
@@ -1083,6 +1083,7 @@ class Case(object):
         User mods can be specified on the create_newcase command line (usually when called from create test)
         or they can be in the compset definition, or both.
         """
+        expect(False, 'throw an error')
         all_user_mods = []
         for comp in self._component_classes:
             component = str(self.get_value("COMP_{}".format(comp)))
```

These generate an ERROR statement in stdout, but you still have a case directory. So if you're not looking carefully, you might miss that error message. Or, you might think, "it says error, but I see a case directory here, so I guess it worked okay".

Should we somehow catch these errors and remove the case directory in cases like this?

cc @mvertens @jedwards4b @jgfouca @JeremyFyke

**Comment by mvertens** [comment]
I think if there is an error - a case should not be created.

**Comment by jgfouca** [comment]
@jedwards4b says sometimes leaving the case is useful for debugging. Leave it if create_test, delete if create_newcase?

**Comment by gold2718** [comment]
Leave it if `--debug` is set?

**Comment by billsacks** [comment]
I realized @jedwards4b 's suggestion of leaving the case directory in place for create_test is critical, so that you keep around the TestStatus file that has the FAIL line in it.

**Comment by jgfouca** [comment]
@billsacks you're right. So only delete for create_newcase and not --debug.
