### ISSUE TITLE
create_test error messages with command line argument errors

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1678]
create_test error messages for typos in command line arguments should be improved.  create_newcase seems to do this fine,

>./create_newcase --case xxx --compset X --res T31_g37 --mach yellowstone --compiler intel --pcount 64
usage: 
create_newcase --case [CASE] --compset [COMPSET] --res [GRID] [--machine ...] [--compiler ...]
OR
create_newcase --help
create_newcase: error: unrecognized arguments: --pcount 64

create_test does not (there is a typo in --no-build in the following that is not clearly identified as the problem),

>./create_test SMS_EN.T31_g37_rx1.A.cheyenne_intel --test-root . --no-buld -t nBb23 --walltime 00:10
usage: 
create_test --xml-category [CATEGORY] [--xml-machine ...] [--xml-compiler ...] [ --xml-testlist ...]
OR
create_test --help
OR
create_test --test

EXAMPLES:
    # Run all tests in the xml prealpha category and yellowstone machine 
    > create_test --xml-machine yellowstone --xml-category prealpha

**Comment by billsacks** [comment]
I can't reproduce this from master: See the last line below:

```
[roo2:~/cime/scripts]$ ./create_test SMS.T31_g37_rx1.A.roo2_gnu --test-root . --no-buld -t nBb23 --walltime 00:10
usage:
create_test --xml-category [CATEGORY] [--xml-machine ...] [--xml-compiler ...] [ --xml-testlist ...]
OR
create_test --help
OR
create_test --test

EXAMPLES:
    # Run all tests in the xml prealpha category and yellowstone machine
    > create_test --xml-machine yellowstone --xml-category prealpha
create_test: error: unrecognized arguments: --no-buld
```

**Comment by apcraig** [comment]
OK, great.  I think we're OK then.  My cime is a couple weeks old or maybe I just messed up.  We should close the issue.  thanks.
