### ISSUE TITLE
$comp is hard-coded in buildlib.csm_share

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1683]
```
my $COMP_INTERFACE = `./xmlquery COMP_INTERFACE	-value`;
...
my $comp="mct";
...
my $libdir = "$sharedlibroot/$comp/$useesmf/${NINST_VALUE}/csm_share";
```
In above code, a hard-coded string "mct" is assigned to $comp. This value is defined in config_component.xml and submit to change (PR #1663 changed it from "MCT" to "mct")
```
<entry id="COMP_INTERFACE">
  ...
  <valid_values>mct</valid_values>
  <default_value>mct</default_value>
  ...
</entry>
```
Instead of hard-coding, is it better to bind $comp to the value read from config_component.xml?
`my $comp = $COMP_INTERFACE;`

**Comment by jedwards4b** [comment]
Yes
