### ISSUE TITLE
Documentation for different Test Codes (SMS, ERS, ERI ...)

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#1685]
I've been working on getting documentation for the different tests for create_test by going
through the comments in the scripts and an old README.  It would be great if people could
look through the different tests and fill in or fix any missing details for there favorite tests.

DAE
    Implementation of the CIME data assimilation test: Tests simple DA script
    which does not change the CAM input. Compares answers to non-DA run.
    
ERI   
    hybrid/branch/exact restart test, default (by default STOP_N is 22 days)
    (1) ref1case
         do an initial for ${STOP_N}/6 writing restarts at ${STOP_N}/6
         ref1 case is a clone of the main case (by default this will be 4 days)
         short term archiving is on
    (2) ref2case
         do a hybrid for ${STOP_N}-${STOP_N}/6 running with ref1 restarts from ${STOP_N}/6
         and writing restarts at ( ${STOP_N} - ${STOP_N}/6 )/2 +1
         (by default will run for 18 days and write a restart after 10 days)
         ref2 case is a clone of the main case
         short term archiving is on
    (3) case
         do a branch run starting from restart written in ref2 case
         and run for ???  days
    (4) case do a restart run from the branch case

ERIO
    tests restart with different PIO methods

ERP   
    pes counts hybrid (open-MP/MPI) restart bfb test from startup, default 6 days + 5 days (previousy PER)
    initial pes set up out of the box
    do an 11 day initial test - write a restart at day 6     (suffix base)
    half the number of tasks and threads for each component
    do a  5  day restart test starting from restart at day 6 (suffix rest)
       this is just like an ERS test but the pe-counts/threading count are modified on retart

ERR
    does an ERS test except that after the initial run the short term archive tool is run
    which moves model output out of the run directory into the short-term archive directory
    then the restart run is staged from the short term archive directory.  In batch mode there are
    four submitted jobs for this test (mira excepted) these are run1, sta1, run2 and sta2
    run1 and sta1 are submitted together with RESUBMIT=1.  sta1 has a batch system dependancy
    on successful completion of run1, when sta1 is completed it uses the cime resubmit capabilty
    to submit run2.

ERS   
    exact restart from startup (default 6 days + 5 days)
    do an 11 day initial test - write a restart at day 6     (suffix: base)
    if $IOP_ON is set then suffix is base_iop
    do a  5  day restart test starting from restart at day 6 (suffix: rest)
    if $IOP_ON is set then suffix is rest_iop
    compare component history files ".base" and ".rest" at day 11

ERS2
    Run for 5 days without writing a restart file
    Run for 3 days (days 1 - 3) and write a restart file at the end of the run
    Continue the run for 2 days (days 4 & 5)
    Compare the output from step 1 and step 3

ERT
    Similar to ERS but longer.  2 months + 1 month  

ICP   
    cice performance test

LII
    CLM initial condition interpolation test
 
NCK   
    multi-instance validation vs single instance - sequential PE for instances (default length)
    do an initial run test with NINST 1 (suffix: base)
    do an initial run test with NINST 2 (suffix: multiinst for both _0001 and _0002)
    compare base and _0001 and _0002     

NCR   
    I don't think we need this test anymore, we're running NCK instead.
    multi-instance validation vs single instance - concurrent PE for instances  (default length)
    do an initial run test with NINST 1 (suffix: base)
    do an initial run test with NINST 2 (suffix: multiinst for both _0001 and _0002)
    compare base and _0001 and _0002
    (***note that NCR_script and NCK_script are the same - but NCR_build.csh and NCK_build.csh are
    different***)        
               
PEA   
    single pe bfb test
    do an initial run on 1 pe with mpi     (suffix: base)
    do the same run on 1 pe with mpiserial (suffix: mpiserial)

PEM   
    modified pe counts mpi bfb test (seq tests)
    do an initial run with default pe layout                               (suffix: base)
    do another initial run with modified pes (NTASKS_XXX => NTASKS_XXX/2)  (suffix: modpes)
    compare base and single_thread

PET  
    modified threading openmp bfb test (seq tests)
    do an initial run where all components are threaded by default (suffix: base)
    do another initial run with nthrds=1 for all components        (suffix: single_thread)
    compare base and single_thread

PFS   
    system performance test.  Do 20 day run, no restarts

PRE  
    Implementation of the CIME pause/resume test: Tests having driver
    'pause' (write cpl restart file) and 'resume' (read cpl restart file)
    without changing restart file. Compare to non-pause/resume run.
    Test can also be run with other component combinations.

REP
    I don't run this test.  
    reproducibility: do two identical runs give the same results?      

SEQ  
    different sequencing bfb test
    do an initial run test with out-of-box PE-layout (suffix: base)
    do a second run where all root pes are at pe-0   (suffix: seq)
    compare base and seq

SMS   
    smoke startup test (default length)
    do a 5 day initial test (suffix: base)
    if $IOP_ON is set then suffix is base_iop
    success for non-iop is just a successful coupler

 SSP   
    smoke CLM spinup test (only valid for CLM compsets with CLM45 and CN or BGC)  (TODO - 
    change to SPL)
    do an initial spin test (setting CLM_BLDNML_OTPS to -bgc_spinup_on)
    write restarts at the end of the run
    short term archiving is on
    do a hybrid non-spinup run run from the restart files generated in the first phase

**Comment by billsacks** [comment]
Thanks, Chris.

I just glanced through this. A few comments:

- The last line of PEM should say "compare base and modpes"

- LII and SSP have just been moved out of cime

- REP is mainly meant to aid debugging when you're seeing errors in other tests. e.g., if there are failures in an ERS, ERP, PEM or PET test, a first question you can ask is, "Are two identical runs giving the same answers?" Sometimes the answer is 'no', giving you a clue to what's wrong.

**Comment by mvertens** [comment]
Thanks so much Chris. Could you please add this to the create_test section
of the user's guide. That would be really helpful.

**Comment by jgfouca** [comment]
@jedwards4b -> says that we already have documentation of these in the config_tests.xml file. We should provide these docs to the user (if user provides --help)?

**Comment by rljacob** [comment]
Is the "old README" the one in scripts/lib/CIME/SystemTests ?

Something like "./create_test --help TESTTYPE" should return the help for that test instead of the generic help message.

**Comment by fischer-ncar** [comment]
Yes, the "old README"  is in scripts/lib/CIME/SystemTests and looks to be out of date.  The config_tests.xml looks like it's up to date.  We should probably remove the README so we
don't have the tests documented in two different places.

I think the different TESTTYPEs should be listed in the generic held message, minus the detail.  
Then do was @rjacob suggests for more details about the TESTTYPE.

**Comment by billsacks** [comment]
I just re-discovered this issue after submitting #1930 . I still feel like it's useful to have this information available via query_testlists (as I did in #1930 ), but maybe we want it available in create_test, too. Much of the implementation for #1930 could be reused for that purpose.

**Comment by fischer-ncar** [comment]
Closed via PR #2062
