### ISSUE TITLE
Cannot set BRNCH_RETAIN_CASENAME

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1695]
xmlchange cannot set BRNCH_RETAIN_CASENAME on a case with RUN_TYPE=branch.
This was with a coupled case which called case.build after setting RUN_TYPE.

**Comment by jgfouca** [comment]
@mfdeakin-sandia I cannot find any occurrence of "RETAIN_CASENAME" in our repo. What made you think you needed to xmlchange it?

**Comment by mfdeakin-sandia** [comment]
This is a feature scientists were using, as evidenced by this line in the run_acme script
# Only uncomment this if you want to continue the run with the same name (risky)!!
# $xmlchange_exe --id BRNCH_RETAIN_CASENAME --val "TRUE"

**Comment by jedwards4b** [comment]
There used to be a variable with this name but I can't find it in the current repo - searching.

**Comment by jedwards4b** [comment]
Was removed in commit edb5a25 by @mvertens

**Comment by mfdeakin-sandia** [comment]
Ah. So is there a new way to use this feature? Or was it just deprecated?

**Comment by jedwards4b** [comment]
I think that it was an accidental removal of a little used feature, @mvertens can you confirm?

**Comment by mvertens** [comment]
So the xml variable BRNCH_RETAIN_CASENAME was removed. This functionality
is now only a driver namelist variable (brnch_retain_casename) and the
logic for it is set in the driver buildnml and now tied to the xml variable
RUN_REFCASE:

    #--------------------------------
    # Overwrite: set brnch_retain_casename
    #--------------------------------
    start_type = nmlgen.get_value('start_type')
    if start_type != 'startup':
        if case.get_value('CASE') == case.get_value('RUN_REFCASE'):
            nmlgen.set_value('brnch_retain_casename' , value='.true.')

The namelist definition for this variable is in namelist_definition_drv.xml:

  <entry id="brnch_retain_casename" modify_via_xml="RUN_REFCASE">
    <type>logical</type>
    <category>expdef</category>
    <group>seq_infodata_inparm</group>
    <desc>
      Allow same branch casename as reference casename. If $CASE and
$REFCASE are the same and the start_type is
      not startup, then the value of brnch_retain_casename is set to .true.
    </desc>
    <values>
      <value>.false.</value>
    </values>
  </entry>

The above ensures that brnch_retain_casename is now set consistently.

**Comment by mfdeakin-sandia** [comment]
Okay. If this is a namelist only bariable now; then this can be closed
