### ISSUE TITLE
--user-compset should imply --run-unsupported

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1706]
In my opinion, if a user is entering expert mode by specifying `--user-compset`, then they should not also have to specify `--run-unsupported`. It seems to me that any user using this feature intends to be running unsupported code and even if they happen to specify an existing compset (supported or not). We should trust that they already signed the waiver that `--run-unsupported` represents.
Comments from @mvertens? @billsacks? @jedwards4b? Anyone at ACME (@jgfouca?).

**Comment by jedwards4b** [comment]
1. --run-unsupported is a cesm only feature and does not affect acme.  
2. We had considerable discussion about this when the run-unsupported flag was implemented before deciding that using both would be required.

**Comment by billsacks** [comment]
@gold2718 - thanks for bringing this up. I agree that you shouldn't have to specify both. I'd actually argue for ditching the `--user-compset` option entirely at this point, and _only_ requiring `--run-unsupported`. (I'm pretty sure that `--user-compset` predates `--run-unsupported`, and I don't ever remembering having a discussion about whether it's necessary to retain `--user-compset` now that we have the more general `--run-unsupported`.)

**Comment by gold2718** [comment]
I am fine with ditching `--user-compset`.

**Comment by billsacks** [comment]
Everyone at today's CSEG meeting was also fine with ditching `--user-compset`, just keeping `--run-unsupported` in this case.
