### ISSUE TITLE
Support --prereq argument to case.submit

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1710]
The --prereq argument is still giving an error.
```
blogin1[247]: ./case.submit --prereq 1662097
ERROR: --prereq not currently supported
```

We should support or temporarily remove it from --help string.

**Comment by mfdeakin-sandia** [comment]
A few questions:
1. ACME scientists would like to be able to chain jobs to run regardless of failure/crashing; which the depends_string (config_batch.xml) explicitly does not do on most batch systems. Would it be reasonable to change this to chain regardless of failure on batch systems that support this? This variable is currently not used anywhere else.
An alternative would be to rename it to depends_success_string, and add a new variable depends_run_string which would be used for dependencies running regardless of failure.

2. It looks like the existing depends_string for cobalt is not set correctly (it doesn't contain "jobid"). Is cobalt still being supported by ACME and/or CESM? Should I fix this?
