### ISSUE TITLE
drivers and share circular dependency with shr_dmodel

### ISSUE THREAD

**Issue by agsalin** [ESMCI/cime#1713]
In working on the build system, I've noticed that the drivers/mct/util/seq_*.F90 files depend on several share/utils/shr_*.F90 shared functions, as is the purpose of share/util. However, there is also one dependency that goes the backward direction, where share/util/shr_dmodel_mod.F90 has a dependency back into drivers/mct/shr/seq_flds_mod.F90:
`use seq_flds_mod, only : seq_flds_dom_coord, seq_flds_dom_other`
where the seq_ variables are used just once in this line:
```
  call mct_gGrid_init( GGrid=gGrid, CoordChars=trim(seq_flds_dom_coord), &
     OtherChars=trim(seq_flds_dom_other), lsize=lsize )
```

This is a minor annoyance to the build process, in that the share/util directory has to be broken up into multiple libraries to get the dependencies with drivers/mct/shr correct. I realized that this means that the share directory will not compile when another driver (nuopc) becomes an option, since a new driver presumably won't come with seq_flds_mod.F90. So thought it was worth calling attention to it.

Does anyone understand this code enough to untangle the circular dependency between these two directories, and have motivation to do so? (It isn't as simple as moving shr_dmodel into drivers/mct, since it is in turn used in other share/util files.) Thanks.

**Comment by jedwards4b** [comment]
Please see #852 regarding the share library.
It seems like the correct location for shr_dmodel_mod.F90 would be a new directory: src/components/data_comps/dshare
