### ISSUE TITLE
Multi_couplers (PR #1566) and the ESP component

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1714]
The implementation of multiple couplers is probably misnamed because what we are really implementing is multiple drivers at the highest level - we are just duplicating the entire cesm code base with different mpi communicators.   This means that each coupler instance is interacting with a unique set of components including the ESP component.   The implementation of multi-coupler was done this way because it was minimally invasive to the code.  The only new data structure introduced in the fortran code is the split of the top level (Global_comm) communicator into separate comms for each coupler.   If we were to try to implement a single driver multiple coupler method we would need to change a significant number of cpl data structures into arrays.   

For dart we want only one esp component to interact with all of the coupler instances.  I think that we could do this in the current implementation of multi-couplers by having one esp instance per coupler and requiring that the esp component recognize its instance number and have all but one instance return without action.   One consequence of this is that the esp component could not use more than the number of tasks used by one coupler (really driver) instance.

**Comment by gold2718** [comment]
ESP needs to be able to update coupler restart files. How is that done in your scenario?

**Comment by mvertens** [comment]
@goldy - So I see two cases. For DART/ESP, I did not think that the coupler
restart files were touched - only component restart files. So in that case
Jim's suggestion might work. For DATA/ESP - this would not work since you
are touching the coupler restart files. However, maybe we would not want to
use DART/ESP with multi-drivers. But until we had pause/resume working this
PR would speed up the current data assimilation simulations - so that would
be a good thing.

**Comment by gold2718** [comment]
It surely complicates the pause/resume work. Even resurrecting the PER test is complicated by the new code (e.g., does one instance know the names of all the other instance's restart files which is necessary to implement @jedwards4b suggestion?). If each instance is running its own driver, how is the magic instance supposed to know if and when the other instances have 'paused'?
If you really want to put this in now, we at least have to let the pause/resume DART folks know that I have design a new solution and new schedule for completion.

**Comment by gold2718** [comment]
It seems that this version of multi-coupler is incompatible with ESP usage so I think that `create_newcase` and `case.setup` should reject the combo.

**Comment by jedwards4b** [comment]
I think that you are too quick to declare it's incompatibility.   As step one let's get the PRE test working on this branch just for ninst=1 then we can look at what it will take to get it to work for multiple instances.   The driver_comm barrier I added in line 3751 of cesm_comp_mod.F90 should assure that all instances are in the pause state, and I think we can find a way to tell the esp component how many instances there are.    Here is my PRE case, ~jedwards/sandboxes/cesm2_0_alpha/cime.jet/scripts/PRE.f19_f19.ADESP_TEST.cheyenne_intel.20170628_113122_dpw11v, maybe you could help me figure out what the problem with the test is?
