### ISSUE TITLE
Tests should work with longname not just alias.

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1718]
Because we have chosen to minimize defined compset aliases we are in a situation in which we might regularly run compsets using the longname only.  We need the tests to work on any compset not just a subset defined by aliases.   I would like to add an option to create test --compset that will allow you to give a compset longname.   This means that the alias that is an integral part of the testname will have to have a special value - how about 'LONGNAME' - so for example a test might be run with 
```
./create_test SMS.f19_g17.LONGNAME.cheyenne_intel --compset AMIP_CAM50_CLM45%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV
```

**Comment by gold2718** [comment]
Is there any reason the longname can't just be included in the test name? E.g.,
```
./create_test SMS.f19_g17.AMIP_CAM50_CLM45%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV.cheyenne_intel
```
Is the period an allowed character in compset names? I'm not sure we check for it but no one uses it so we could just declare it character _non grata_.
