### ISSUE TITLE
Syntax error in statistical_ensemble_test

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#1720]
@allibco 

We need to change line 244 line of ensemble.sh to
CLONECOUNT=$((${Args[$i]}-1))

And get the change into cime/master.

**Comment by jgfouca** [comment]
Reassigned to @allibco once she's in the he organization.

**Comment by bertinia** [comment]
Posted this issue to the NCAR/pyCECT repo and emailed @allibco to let us know when
it has been fixed so the pyCECT subtree can be updated on ESMCI/CIME master.

**Comment by bertinia** [comment]
Fixed in PR #1761
