### ISSUE TITLE
cime5.3.0-alpha.29 multi-instance CAM fails due to cpl.r size limit

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#1726]
cesm2_0_beta06 F2000_DEV dies while trying to write the cpl.r file
at the end of the forecast when ninst = 30, but not when ninst = 3.  
The error message is
1: pio_support::pio_die:: myrank=          -1
 : ERROR: nf_mod.F90:        1508
 : NetCDF: One or more variable sizes violate format constraints

When ninst = 3 the cpl.r file ends up being 400 Mb, while the 30
member would be 4 Gb, which is larger than the NetCDF Classic
file size limit of 2.1 Gb
This happens even though drv_in:  cpl_cdf64 = .true.

I haven't been able to track down where this restriction is applied.
It was not a problem in cesm2_0_beta05.  This will prevent DART
data assimilation experiments with recent CESM tags.

Thanks for any pointers.

Kevin Raeder

**Comment by mvertens** [comment]
@kdraeder - since you have been carrying out these experiments with cesm2_0_beta05 as well - could you determine if there are more fields in the cpl.r file in beta06? What is the size of the cpl.r file in beta05 when ninst = 3. That would be very helpful to know. We'll look into this as a high priority - we need to have DART data assimilation working in the cesm2 release code.

**Comment by kdraeder** [comment]
Thanks for the quick response!
And thanks to Steve for tipping me off that Github is
the place to file these things, instead of Bugzilla.
I reported this there a month ago, but nobody answered.

I've attached a tar file with summaries of the cpl.r files
for beta05 and beta06.  Note that beta05 was f19_f19, 
while beta06 was f09_f09.  I had to tack on a .txt in
order for Github to upload it, so take that off, then
>> tar -z -x -f beta05_vs_06_ninst3.cpl.r.gztar
will unpack the files.
[beta05_vs_06_ninst3.cpl.r.gztar.txt](https://github.com/ESMCI/cime/files/1133527/beta05_vs_06_ninst3.cpl.r.gztar.txt)

Kevin

**Comment by jedwards4b** [comment]
Just a note that I think that this would be solved with the multi coupler branch.

**Comment by kdraeder** [comment]
I agree.  What's the status of that branch?
I've been looking forward to running a clean multi-coupler
since Raffaele coded it into a pre-python CESM last Fall.
Kevin

**Comment by mvertens** [comment]
@jedwards - irrespective of the multi-coupler (which really should be called multi-driver) this seems like a bug to me and if so needs to be fixed.
@kraeder - there is an outstanding PR to bring this into CIME master. There are issues regarding if this will be problematic with pause/resume that we are trying to sort out. In the meantime we could point you to the CIME branch if you want to try it out.

**Comment by jedwards4b** [comment]
Fixed by #1705

**Comment by kdraeder** [comment]
I'd like the pointer to the multi-coupler/driver branch.
Thanks,
Kevin

**Comment by mvertens** [comment]
@jedwards - could you please point @kraeder to your multi-driver branch.
@kraeder - it would be great if you could use this to do a quick
performance test of your current configuration to determine the benefit of
using this. It would really help us decide how important it is to bring
this into cime master right now. One option is to have multi-driver and
pause/resume be mutually exclusive for the time being if we cannot find a
solution. But we really need to know that the multi-driver gives us a
substantial performance benefit to have two possibly conflicting paths
moving forwards.

**Comment by jedwards4b** [comment]
fork:	git@github.com:jedwards4b/cime.git 
branch: multiple_couplers

**Comment by mvertens** [comment]
@jedwards - thanks. Can you also give Kevin a quick summary about how to
create a case with multiple drivers. We really have not documented that
extensively.
