### ISSUE TITLE
multi-instance rpointer file names in config_archive.xml don't match $rundir

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#1731]
config_archive.xml:
      <rpointer_file>rpointer$NINST_STRING.atm</rpointer_file>'
rundir:
     rpointer.atm_$NINST_STRING

Similarly for all other (multi-instance) components.
I vote for changing config_archive.xml, so that the instance
number is always attached to the component name, 
rather than the file type.   This would also match the
restart, initial, and history files.

Thanks
Kevin

**Comment by bertinia** [comment]
I've fixed the rpointer filename problem for multi-instance but found a problem
with the auto-generation of interim rpointer files (REST_N < STOP_N) only including the first instance. 
Working on that fix now.
