### ISSUE TITLE
Can the driver (either in scripts or in code) check for invalid PE layouts?

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1732]
I saw this as a problem in https://github.com/NGEET/fates/issues/242. A bad PE layout was put together and it dies in an awkward way hard to understand. It would be much preferred if the driver (in either scripts or in code) could recognize bad PE layouts and rather than die awkwardly -- print out a nice error message that the PE layout is invalid.

The specific bad PE layout was intended to construct a layout where DATM was running on concurrent processors with everything else. So rootpe for ATM is 0, and for everything else rootpe starts at 1 node (since DATM was intended to run on one node). The problem was that ATM was given the same number of tasks that everything else was running on (rather than one node). This PE layout results in the error shown on NGEET/fates.

Currently, there is very little checking of the PE layout in either scripts or code. The code checks that rootpe>=0 for all components. And it does some checking for number of instances versus tasks for each component. The scripts only do some checking when PE layout is changed.

For some patterns to check. At least 1 of the component rootpe's should be 0. And the scripts could also check that rootpe is >=0. Also if all rootpe's other than one start at something other than 0 (and that one starts at 0) then the rootpe should be the same as the number of tasks for the one that starts at 0.

The reason this is important is because often scientist's don't understand PE layouts, but a nice error message could tell them what to do. And even for me, it took me some time to track down what the problem was -- the error that happens gives no clue for what the problem is.

I put this as a question and a discussion for now, until we decide on how important this is to work on.

@jedwards4b @mvertens

**Comment by billsacks** [comment]
I don't think everyone has access to the FATES repo. Some relevant things @ekluzek posted there are:

the pe layout:

```
	NTASKS: ['CPL:540', 'ATM:540', 'LND:540', 'ICE:540', 'OCN:540', 'ROF:540', 'GLC:540', 'WAV:540', 'ESP:540']
	ROOTPE: ['CPL:36', 'ATM:0', 'LND:36', 'ICE:36', 'OCN:36', 'ROF:36', 'GLC:36', 'WAV:36', 'ESP:36']
```

The error:

```
144:MPT: #1  0x00002aaab01e979c in mpi_sgi_system (command=<optimized out>) at sig.c:98
144:MPT: #2  MPI_SGI_stacktraceback (header=<optimized out>) at sig.c:339
144:MPT: #3  0x00002aaab0143fae in print_traceback (ecode=0) at abort.c:227
144:MPT: #4  0x00002aaab0144025 in MPI_SGI_abort () at abort.c:90
144:MPT: #5  0x00002aaab0182e01 in errors_are_fatal (comm=<optimized out>, 
144:MPT:     code=<optimized out>) at errhandler.c:230
144:MPT: #6  0x00002aaab0183194 in MPI_SGI_error (comm=114, code=15) at errhandler.c:58
144:MPT: #7  0x00002aaab0141141 in MPI_SGI_request_test (request=0x7fffffff6024, 
144:MPT:     status=0x3441190 <mpi_sgi_status_ignore>, set=0x7fffffff6020, 
144:MPT:     rc=0x7fffffff601c) at req.c:1401
144:MPT: #8  0x00002aaab0141220 in MPI_SGI_request_wait (request=0x7fffffff6024, 
144:MPT:     status=0x3441190 <mpi_sgi_status_ignore>, set=0x7fffffff6020, 
144:MPT:     gen_rc=0x7fffffff601c) at req.c:1659
144:MPT: #9  0x00002aaab01edf7d in MPI_SGI_recv (buf=<optimized out>, 
144:MPT:     count=<optimized out>, type=<optimized out>, des=<optimized out>, 
144:MPT:     tag=<optimized out>, comm=<optimized out>, 
144:MPT:     status=0x3441190 <mpi_sgi_status_ignore>) at sugar.c:40
144:MPT: #10 0x00002aaab015a6dc in MPI_SGI_bcast_basic (comm=<optimized out>, 
144:MPT:     root=<optimized out>, type=<optimized out>, count=<optimized out>, 
144:MPT:     buffer=<optimized out>) at bcast.c:252
144:MPT: #11 MPI_SGI_bcast (
144:MPT:     buffer=0x34466c0 <cplcomp_exchange_mod_mp_seq_mctext_avextend_$ILIST.0.9>, 
144:MPT:     count=4096, type=19, root=15, comm=114) at bcast.c:482
144:MPT: #12 0x00002aaab015ac09 in MPI_SGI_bcast_topo (
144:MPT:     buffer=0x34466c0 <cplcomp_exchange_mod_mp_seq_mctext_avextend_$ILIST.0.9>, 
144:MPT:     count=4096, type=19, root=540, comm=9, force=0) at bcast.c:340
144:MPT: #13 0x00002aaab015a768 in MPI_SGI_bcast (
144:MPT:     buffer=0x34466c0 <cplcomp_exchange_mod_mp_seq_mctext_avextend_$ILIST.0.9>, 
144:MPT:     count=4096, type=19, root=540, comm=9) at bcast.c:457
144:MPT: #14 0x00002aaab015ad52 in PMPI_Bcast (
144:MPT:     buffer=0x34466c0 <cplcomp_exchange_mod_mp_seq_mctext_avextend_$ILIST.0.9>, 
144:MPT:     count=-42580, type=19, root=540, comm=9) at bcast.c:93
144:MPT: #15 0x00002aaab015af7a in pmpi_bcast__ ()
144:MPT:    from /glade/u/apps/opt/mpt/2.15-sgi715a158/lib/libmpi.so
144:MPT: #16 0x000000000042bba5 in cplcomp_exchange_mod_mp_seq_mctext_avextend_ ()
144:MPT:     at /glade/u/home/erik/fates-clm/cime/src/drivers/mct/main/cplcomp_exchange_mod.F90:833
144:MPT: #17 0x000000000042d297 in cplcomp_exchange_mod_mp_seq_mctext_avinit_ ()
144:MPT:     at /glade/u/home/erik/fates-clm/cime/src/drivers/mct/main/cplcomp_exchange_mod.F90:392
144:MPT: #18 0x0000000000426fb4 in component_mod_mp_component_init_cx_ ()
144:MPT:     at /glade/u/home/erik/fates-clm/cime/src/drivers/mct/main/component_mod.F90:347
144:MPT: #19 0x00000000004187cc in cesm_comp_mod_mp_cesm_init_ ()
144:MPT:     at /glade/u/home/erik/fates-clm/cime/src/drivers/mct/main/cesm_comp_mod.F90:1211
144:MPT: #20 0x0000000000424853 in MAIN__ ()
144:MPT:     at /glade/u/home/erik/fates-clm/cime/src/drivers/mct/main/cesm_driver.F90:62
144:MPT: #21 0x000000000040835e in main ()
144:MPT: (gdb) A debugging session is active.
```

Line 1211 of cesm_comp_mod is:

```
call component_init_cx(atm, infodata)
```

**Comment by billsacks** [comment]
@ekluzek it's not at all clear to me why this PE layout would be "bad". i.e., what rules could we have to catch this problem in general? I understand that atm was meant to just be on one node, so there was a mistake here, but at a glance it looks like a valid PE layout to me. The one unusual thing I see is that cpl is a subset of the atm pes but does not start at the root of the atm pes; could that be responsible for this problem?

**Comment by billsacks** [comment]
Specifically regarding this:

> Also if all rootpe's other than one start at something other than 0 (and that one starts at 0) then the rootpe should be the same as the number of tasks for the one that starts at 0.

That seems like a good rule of thumb, but as far as I know it's not actually a requirement of the system.

**Comment by ekluzek** [comment]
@billsacks It's true that if you don't have one rootpe that starts at 0, that you should still be able to run. But, it means you'll be running on a fraction of the processors that are allocated. So I would still consider it a bad PE layout.

**Comment by billsacks** [comment]
I would support warnings rather than errors in situations like this.

**Comment by ekluzek** [comment]
@billsacks the problem with this particular PE layout is that the atm was supposed to be on different processors than everything else (thus running concurrently). The problem was that some processors were concurrent, but some were sequential (on the same processors as land and everything else). The system can't seem to handle this setup. And it's not one you'd actually want to run anyway because you essentially get the problems of both running concurrent AND sequential, without the benefits of either. So in a way it's good it doesn't work, I'd just like to have a more obvious error message about it.

**Comment by ekluzek** [comment]
@billsacks we can see what the larger group thinks about using warning rather than error. The reason I think it should be an error, is that I think the main reason someone would set it up this way -- is because of a mistake. And the upshot is that they'll get charged for using more processors than they are taking advantage of -- which is something I'd prefer to see as an error than a warning. If I could think of a legitimate use case for actually doing this -- I'd support a warning. But, I can't think of a legitimate reason to ever do that.

**Comment by billsacks** [comment]
Legitimate use cases for seemingly-illogical PE layouts include performance testing and running with components whose scaling turns over past a certain point, so that you actually do better by running them on fewer PEs.

**Comment by ekluzek** [comment]
I see limiting the number of processors for a particular component. And there are times when for performance testing you might do something unusual. But, the case I'm talking about is where there are processors that are under MPI -- for which there is NO component that uses. Once, you have at least one component using that MPI rank -- I'd say that's a legitimate PE layout. But, when you have MPI ranks that are completely unused across the system -- I'd say that's an illegitimate PE layout that the system should abort on. 99.9999% of the time such a layout would have been picked as a simple mistake. If there is a power user who had a reason for doing this -- they should be able to turn off the error. But, I still can't think of a legitimate reason to ever do that.

And as we saw from my issue, the system can't necessarily even handle some PE layouts, and it would be far better for the system to abort early, and tell you it's a bad PE layout -- than die in a strange manner that's takes a bunch of time to figure out.

I would support the use of warnings rather than an abort for cases like where you haven't used an even number of nodes, or have components on partial nodes. Those kind of things are sub-optimal, but you might want to do performance testing for it. And I suppose there are performance testing reasons you might want to oversubscribe processors -- I'd say that's legit as well. But, it would be good for it to show you a warning about these cases that are sub-optimal, but should run.

**Comment by rljacob** [comment]
> where there are processors that are under MPI -- for which there is NO component that uses.

At one point, the driver did allow this for async I/O.  The I/O would run on the unused MPI ranks.  But that support has been partly removed and the driver should probably abort for that case.

**Comment by ekluzek** [comment]
@billsacks thinking about this more. OK, I think I see a legitimate reason to have a "hole" in processors in the middle of a PE layout -- but still not in the beginning. You might have a component that can only handle something less than completely full nodes. But, you don't want other components sharing that node that isn't fully used by that component. So you have a "hole" in the MPI processors to make sure you have components on different nodes. But, I still see no reason to have a "hole" in processors used for the lowest MPI ranks.

@rljacob yeah if it's not something that works now, I think it would be best to abort rather than allow it. If it becomes legit again you could change whether it's allowed or not.

**Comment by billsacks** [comment]
I agree that you generally don't want a complete "hole" in your PE layout, but that didn't look like what was happening in your example that caused the issue, so I wasn't thinking about that case. I wouldn't object to an abort in that case.

I feel like we still don't understand what caused the system to crash in your case. I think we can't expect the scripts to catch an issue with PE layouts until we understand what that issue is. I still don't have a clear sense of what kind of check could be put in place in the scripts; do you?

**Comment by ekluzek** [comment]
You're right I'm not completely sure why it crashed. I was able to look at the PE layout and realize it was screwed up though, and immediately get it working. And I do think that having a non-cpl component that spans processors in a way that's both concurrent and sequential is a problem. So I believe we can develop a way to recognize some bad layouts (maybe not all). I was also trying to think beyond my specific case, and think about what layouts could be recognized as bad. A hole at low MPI ranks is one thing I could think of that would be bad and could be easily checked for.

What I do think would be useful though is:

1. Have scripts print warnings about some PE layouts that can be recognized as "strange".
2. Have scripts die for PE layouts we know are bad.
3. Possibly put some of the especially egregious cases in the driver code so it aborts rather than tries to run (this would be redundant with 1 and 2, so maybe it's not necessary, or maybe it would be done for cases where it would be easier to catch in the driver code rather than in the scripts).

If we start to get these three in place, they can be expanded (or relaxed) as needed in the future as requirements change and features are added. Right now there is very little checking done, and no warnings given. Jackie also ran with a layout that was setup for yellowstone on cheyenne, and though it ran it would be screwy. It would be nice for that case to give a warning. And even a warning for the case that died for me would have been helpful in order to make it easier to realize the PE layout was the source of the problem. It might be easier to recognize layouts that are "strange" over ones that we know will crash.

**Comment by jgfouca** [comment]
@ekluzek during CIME meeting we looked at this ticket. We decided CIME cannot determine if a layout is "bad" but it shouldn't have crashed. Please open a different ticket to fix the CIME crash.
