### ISSUE TITLE
archive_metadata.sh

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1733]
The archive_metadata.sh script is in the case directory, it has a couple of problems
1. It's still written in sh - consider rewriting in python.
2. The help message indicates it should work but ...
```
your subversion password may be requested...
svn: warning: W155010: The node '/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/PFS.f09_g17.B1850.cheyenne_intel.allactive-default.20170709_074237_pytptq' was not found.
```
I think that it would be worthwhile to get this cleaned up and working for the release, at a minimum I would like to be able to upload performance data from anyone willing to provide it.

**Comment by bertinia** [comment]
This is being addressed in #1328.
