### ISSUE TITLE
Missing input data for test PRE.f19_f19.ADESP

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1743]
In PR #1734, PRE.f45_g37_rx1.ADESP (a cime_developer test) was renamed to PRE.f19_f19.ADESP.

When I tested it with "./create_test PRE.f19_f19.ADESP --machine=anlworkstation", errors were:
>         Model docn missing file domain1 = '/home/climate1/acme/inputdata/ocn/docn7/SOM/default.som.forcing.aquaplanet.Qflux0_h30_sstQOBS.2degFV_c20170421.nc'
>         
>         Could not connect to svn repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata'
>         This is most likely either a credential, proxy, or network issue .
>         To check connection and store your credential run 'svn ls https://acme-svn2.ornl.gov/acme-repo/acme/inputdata' and permanently store your password

It looks like the input files are not on svn yet. Please upload the missing files to acme-svn2.ornl.gov, thanks.

**Comment by gold2718** [comment]
@dqwu,

1) The file appears to be in the repo:
```
$ ls -l /home/climate1/acme/inputdata/ocn/docn7/SOM/default.som.forcing.aquaplanet.Qflux0_h30_sstQOBS.2degFV_c20170421.nc 
-rw-rw-r-- 1 jayesh climate 5481124 Apr 25 16:36 /home/climate1/acme/inputdata/ocn/docn7/SOM/default.som.forcing.aquaplanet.Qflux0_h30_sstQOBS.2degFV_c20170421.nc
```
@jayeshkrishna, did you download the file for @dqwu? If so, please close this issue.

2) The error message says you could not access the repo, not that the file was not in the repo. 

3) Verify that this is really the file you are missing or please close this issue.

4) If you really have an issue, please assign it to the machine point of contact.

**Comment by rljacob** [comment]
The create_test script is supposed to check both the cesm repo and, for cime-model=ACME, the acme repo for files.  In general, no one on this github org can put things in the ornl repo.

But this must be something else because the file appears to be on local disk as @gold2718 pointed out.

**Comment by jayeshkrishna** [comment]
I also remember having some errors (not credentials) when I ran "./check_input_data --download" for this case on anlworkstation last week. Looks like the file is there (and I can run ./check_input_data without any issues for this case), so we should close this ticket.
```
svn ls https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ocn/docn7/SOM/default.som.forcing.aquaplanet.Qflux0_h30_sstQOBS.2degFV_c20170421.nc
```
