### ISSUE TITLE
Remove the generic GSW DATM_MODE in datm

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1749]
@rljacob @bishtgautam we'd like to remove the older generic "GSW" option for DATM_MODE in config_component.xml for DATM, and only allow the more explicit GSWP3v7 option. We don't believe this affects ACME, but wanted to check. If you want to use the GSWP3 data you should use the GSWP3v7 version.

**Comment by bishtgautam** [comment]
Thanks for checking in, but removing this will not impact ACME as no one so far has been running a simulation with GSW.

**Comment by rljacob** [comment]
Ok with me.
