### ISSUE TITLE
Correct documentation on hybrid/branch run (section 8.3) and augment create_clone

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1764]
The documentation (section 8.3) for creating a branch or hybrid run needs to be amended slightly.  Right now it says to do a case.build prior to copying the restart files into the $RUNDIR.  Since a preview_namelists is the first step of a case.build, this exits with a an error as the restart files are not found.  

It also might be useful to describe briefly the difference between branch and hybrid on this page or have a link back to the descriptions in 6.3 for their definitions.

Also, when does a user want to use create_clone?  The documentation on this is very sparse.  A description on when to make a branch versus a clone would be useful.

For someone who is not "in the know" on hybrid/branch/clone, it was not very straightforward to work through this information.

**Comment by bertinia** [comment]
Moved to #1519
