### ISSUE TITLE
Cannot setup gnu or pgi tests on yellowstone with cime master

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1769]
With something close to cime master (a branch off of b4419efa2b6eb3ce339f1aac371832587cc49315) I get failures when trying to create pgi or gnu tests:

`SMS.f09_g16.X.yellowstone_gnu`:

```
ERROR: module command /glade/apps/opt/lmod/lmod/libexec/lmod python load netcdf-mpi/4.4.1 failed with message:
Lmod Error: Cannot find netcdf-mpi built for gnu version: 5.2.0
```

`SMS.f09_g16.X.yellowstone_pgi`:

```
ERROR: module command /glade/apps/opt/lmod/lmod/libexec/lmod python load netcdf-mpi/4.4.1 failed with message:
Lmod Error: Cannot find Example package built for pgi version: 15.10
```

**Comment by billsacks** [comment]
cc @mvertens @fischer-ncar

**Comment by jedwards4b** [comment]
I will revert the netcdf module for pgi and gnu compilers on yellowstone.
