### ISSUE TITLE
Need optional ability to take in snow data for CLMNCEP mode for DATM

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1774]
This is something that Justin Perket needs for the snow MIP. He needs to be able to specify snow fall as distinguished from rainfall as input forcing data for CLMNCEP mode in DATM.

Currently in DATM, we have this:

```
         !--- split precip between rain & snow ---
         call shr_precip_partition_rain_snow_ramp(tbot, frac)
         a2x%rAttr(ksc,n) = max(0.0_R8, a2x%rAttr(krc,n)*(1.0_R8 - frac) )
         a2x%rAttr(ksl,n) = max(0.0_R8, a2x%rAttr(krl,n)*(1.0_R8 - frac) )
         a2x%rAttr(krc,n) = max(0.0_R8, a2x%rAttr(krc,n)*(         frac) )
         a2x%rAttr(krl,n) = max(0.0_R8, a2x%rAttr(krl,n)*(         frac) )

```

So there is code that divides rain and snow by temperature. The above code should examine if snow is input and if so use it as is.

**Comment by JustinPerket** [comment]
In my local working directory, I created two new stream variables "srainn" and ssnown" in DATM, meant to be separate phase analogues of the total precip stream "sprecn". With appropriate modifications to stofld, stifld, and such, I added an if statement in the CLMNCEP precip section to check for them:

``` fortran 
         if (srainn > 0 .and. ssnown > 0) then
         !--- separate rain and snow precip are both present ---
            a2x%rAttr(ksc,n) = avstrm%rAttr(ssnown,n)*0.1_R8
            a2x%rAttr(ksl,n) = avstrm%rAttr(ssnown,n)*0.9_R8
            a2x%rAttr(krc,n) = avstrm%rAttr(srainn,n)*0.1_R8
            a2x%rAttr(krl,n) = avstrm%rAttr(srainn,n)*0.9_R8
         else
            if (sprecc > 0 .and. sprecl > 0) then
               a2x%rAttr(krc,n) = avstrm%rAttr(sprecc,n)
               a2x%rAttr(krl,n) = avstrm%rAttr(sprecl,n)
            elseif (sprecn > 0) then
               a2x%rAttr(krc,n) = avstrm%rAttr(sprecn,n)*0.1_R8
               a2x%rAttr(krl,n) = avstrm%rAttr(sprecn,n)*0.9_R8
            else
               call shr_sys_abort(subName//'ERROR: cannot compute rain and snow')
            endif

            !--- split precip between rain & snow ---
            call shr_precip_partition_rain_snow_ramp(tbot, frac)
            a2x%rAttr(ksc,n) = max(0.0_R8, a2x%rAttr(krc,n)*(1.0_R8 - frac) )
            a2x%rAttr(ksl,n) = max(0.0_R8, a2x%rAttr(krl,n)*(1.0_R8 - frac) )
            a2x%rAttr(krc,n) = max(0.0_R8, a2x%rAttr(krc,n)*(         frac) )
            a2x%rAttr(krl,n) = max(0.0_R8, a2x%rAttr(krl,n)*(         frac) )
         end if
```

This seems to work for my purposes. If desired, I can put it into a new branch for a later merge.

**Comment by ekluzek** [comment]
I think this is required for CESM2.1 for CMIP.

**Comment by ekluzek** [comment]
@JustinPerket can you comment on the priority for this? What CMIP6 simulations need this in place?

**Comment by dlawrenncar** [comment]
I believe that this is mostly a SnowMIP issue, most of which will be done after the CMIP6 rush.  My understanding is that, if we even have anyone to work on this, that it could be completed for CESM2.1.1 or later.

**Comment by JustinPerket** [comment]
Hi Erik and Dave,
Yes, it is soley for point simulations for snowmip, which gives
phase-separated precip forcing. I'm currently traveling in China sans
laptop, so can't take a good look at code changes, but if there is interest
after 2.1.1, I may be able to conduct these point simulations.

Best,
Justin

**Comment by ekluzek** [comment]
I talked to @swensosc about this, and he confirmed that these changes were put in by hand for SnowMIP. And as such they only need to go to master now and not required for maint-5.6 CESM2.1 release branch.

**Comment by billsacks** [comment]
@swensosc or @JustinPerket - I just want to confirm: when you implemented this for SnowMIP, did you also turn off rain-snow repartitioning inside CTSM (via the `repartition_rain_snow` namelist flag)?

**Comment by swensosc** [comment]
I used 'repartition_rain_snow = .false.' in user_nl_clm

**Comment by billsacks** [comment]
Are these changes still needed? If so, can you please move this to CDEPS?
