### ISSUE TITLE
xmlquery not working on JOB_WALLCLOCK_TIME

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#179]
xmlquery is not returning any value when the input is JOB_WALLCLOCK_TIME
```
env_batch.xml:      <entry id="JOB_WALLCLOCK_TIME" value="00:20">
env_batch.xml:      <entry id="JOB_WALLCLOCK_TIME" value="00:20">
env_batch.xml:      <entry id="JOB_WALLCLOCK_TIME" value="00:20">
env_batch.xml:      <entry id="JOB_WALLCLOCK_TIME" value="00:20">
yslogin5: ~/sandboxes/cesm1_5_alpha/cime.esmci/scripts/foo
:) xmlquery JOB_WALLCLOCK 
yslogin5: ~/sandboxes/cesm1_5_alpha/cime.esmci/scripts/foo
```

**Comment by wilke** [comment]
You mean xmlquery JOB_WALLCLOCK_TIME or should pattern matching be enables as well ?

**Comment by wilke** [comment]
Another issue the -value option is returning multiple values for JOB_WALLCLOCK_TIME. This will cause problems in other scripts. Will change it to return only first hit for this option,

**Comment by jedwards4b** [comment]
Oops - my mistake.  Seems to be working fine except how do you specify an attribute?
./xmlquery JOB_WALLCLOCK_TIME -value -attribute case.run
12:0012:0024:0024:00
:) ./xmlquery JOB_WALLCLOCK_TIME -value -attribute job_submission=case.run
12:0012:0024:0024:00
:) ./xmlquery JOB_WALLCLOCK_TIME -value -attribute job_submission=case.run
12:0012:0024:0024:00
:) ./xmlquery JOB_WALLCLOCK_TIME -value -attribute job_submission:case.run
12:0012:0024:0024:00

**Comment by wilke** [comment]
Subgroup support is another issue #186
