### ISSUE TITLE
Staging a hybrid run is broken

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1794]
When I create a hybrid run using the following commands:
 >./xmlchange RUN_REFCASE=b.e11.B1850C5CN.f09_g16.005_v3                           
 ./xmlchange RUN_REFDATE=0402-01-01                                               
 ./xmlchange GET_REFCASE=TRUE   
 ./xmlchange RUN_TYPE=hybrid

I get the following message from preview_namelists:
>Creating component namelists
   Calling cam buildnml
     ...calling cam buildcpp to set build time options
   Calling clm buildnml
   Calling cice buildnml
     ...calling cice buildcpp to set build time options
   Calling pop buildnml
     ...calling pop buildcpp to set build time options
Traceback (most recent call last):
  File "./preview_namelists", line 48, in <module>
    _main_func(__doc__)
  File "./preview_namelists", line 45, in _main_func
    create_namelists(case, component=args.component)
  File "/glade2/scratch2/cacraig/cam5_4_138_trunk06/cime/scripts/Tools/../../scripts/lib/CIME/preview_namelists.py", line 87, in create_namelists
    mod.buildnml(case, caseroot, compname)
  File "/glade2/scratch2/cacraig/cam5_4_138_trunk06/components/pop/cime_config/buildnml", line 149, in buildnml
    if 'RESTART_FMT=nc' in open(pointer_file).read():
IOError: [Errno 2] No such file or directory: '/glade/scratch/cacraig/test_cecile_b1850_trunk06/run/rpointer.ocn.restart'

My workaround is to hand copy the rpointer.ocn.restart file and the file it references into my RUNDIR.  Since I am building the B1850  compset, this is not a viable long-term solution.

From an email exchange with Mike Levy, he had the following reply:
>Hi Cheryl,

>Do you think the run doesn't need the refcase documents, or do you think CESM should handle the copy for you?

>I actually ran into this exact error with a grad student yesterday, and convinced myself that manually copying the refcase files _was_ necessary for a hybrid because (unlike a branch) you may want to initialize one (or more) of the components as a startup instead of from a restart. Looking closer, though, I'm not sure that first case (starting POP from initial condition files) would build out of the box... this logic in $POP/cime_config/buildnml is triggering the error you are seeing:

        if run_type == 'startup' and not continue_run:
            check_pointer_file = False
        else:
            check_pointer_file = True

        format = 'bin'
        if check_pointer_file:
            if 'RESTART_FMT=nc' in open(pointer_file).read():

>If you want to do a hybrid run and start POP from initial condition files, then check_pointer_file should be False but the scripts apparently don't support that.

>~Mike

**Comment by jedwards4b** [comment]
Could you please run check_input_data on your hybrid case with the --debug flag.

**Comment by jedwards4b** [comment]
The problem is that check_input_data is called by case.submit but the pop buildnml expects the rpointer file to be in the run directory when preview_namelists is run. I think that we need to add a call to check_input_data in the preview_namelist script if get_refcase is true.
