### ISSUE TITLE
Need DARTROOT XML variable

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1806]
We need a DARTROOT XML variable to enable adding tests which use DART scripts and a DART filter.
Should this go in config_machines.xml?

**Comment by jedwards4b** [comment]
I think this might lead to a proliferation of variables that we don't really need.  Can you please provide a specific example so that we can consider how we might support externals like this without having to introduce a new path variable for each one?

**Comment by gold2718** [comment]
Good question. We need to add tests (aux_clm, aux_cam, prebeta, etc) which run actual DART experiments. The thought behind this issue is that we need a way for testmods to point to the correct (machine dependent) script locations to use for DATA_ASSIMILATION_SCRIPT.

**Comment by gold2718** [comment]
What do you think of using machine-name logic inside of shell_commands? Can we put more than just xmlchange commands?
Would that be appropriate?
Some other idea?

**Comment by jedwards4b** [comment]
You can do other things in shell_commands.   But why not just decide on a machine independent environment variable and use that in DATA_ASSIMILATION_SCRIPT?  For example
DATA_ASSIMILATION_SCRIPT=$DART_PATH/bin/dart_script

**Comment by gold2718** [comment]
First, there will be multiple scripts to do different tests (e.g., no assimilation, POP assimilation, CAM assimilation).
Two, that just pushes the issue of where in CIME the DATA_ASSIMILATION_SCRIPT environment variable will be set.

**Comment by jedwards4b** [comment]
I would assume that multiple scripts would be described by multiple compsets and the script name would be part of the compset description.  The environment variable would be set on the machine just as we are currently using CESMDATAROOT on cheyenne and yellowstone.

**Comment by gold2718** [comment]
To be more specific, it sounds like you are proposing to add DARTROOT to the ncarenv module on Yellowstone and Cheyenne.
@jedwards4b, does that correctly capture your proposal?
@mvertens, is that an acceptable solution?

**Comment by jedwards4b** [comment]
I am actually proposing that each dart user on a machine set the DARTROOT environment variable themselves.  I doubt very much, especially in early stages, that all users would be able to use the same dart path - that is each dart user is going to want their own directory with their own local modifications.

**Comment by gold2718** [comment]
We are moving towards adding DART to the CESM test suite (note above where I mentioned aux_cam, aux_clm, prebeta, etc.). Thus, everyone who runs CESM tests will need to be able to access the _same_ DARTROOT.
As part of this exercise, the DAReS will create a fixed space on each supported machine, at which we can point DARTROOT.

**Comment by jedwards4b** [comment]
You would define the variable in the esp component cime_config/config_component.xml and set it in config_machines.xml

**Comment by mvertens** [comment]
The way we are using these tests is outside of the ESP component. These
tests use DART as a separate executable - not as a subroutine call in the
driver. I think the assumption we need for these tests is that there needs
to be a default fixed space for DART. If that is the assumption, then I do
think we need to introduce a DART xml variable (that is analogous to
INPUTDATA_ROOT). This could only be in the config_component_cesm.xml - and
need not be present for ACME.
