### ISSUE TITLE
ccsm_pes namelist error checking

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1811]
If the ccsm_pes namelist (read in seq_comm_mct.F90) has an error the model just proceeds with default settings for the variables in the namelist, this can cause very confusing error later, for example in a b case when rootpe_ocn>0 you will get an error from pop: Input nprocs not same as system request

**Comment by billsacks** [comment]
I agree that it would be good to have more error-checking there, but I just want to point out that the unit tests currently take advantage of the "feature" of the lax error checking in seq_comm_mct, by providing an empty namelist file name:

```
src/drivers/mct/unit_test/utils/mct_wrapper_mod.F90:    call seq_comm_init(Comm_in = mct_communicator, nmlfile = ' ')
```

So more strict error checking would need to be accompanied by a more robust solution there. @gold2718 and I discussed this a while back, but I'd have to rack my brain (or my notes) a bit to remember what we were thinking.

**Comment by jedwards4b** [comment]
I thought that was the case, which is why I just opened an issue instead of trying to fix it.  But it sure tripped me up for a few hours on Friday.

**Comment by billsacks** [comment]
Sorry about that.
