### ISSUE TITLE
proposed test of short term archiving 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1813]
A test should be created that does an initial run with the save interum restart option on and writes restart at some time which is not an even divisor of the total.   It would then clean the run directory and replace it with the files in the archive directory and restart from those files and run to the original runtime comparing history files from the initial run to the restart run.    Perhaps the ERS test could be refactored to do this instead of introducing an entirely new test?

**Comment by billsacks** [comment]
@jedwards4b was this resolved by #1837 ?

**Comment by jedwards4b** [comment]
Yes - closing.
