### ISSUE TITLE
rpointer filename mismatch in archive for multi-instance runs

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#1814]
@kdreader noticed a while ago that the rpointer files created in $rundir,
rpointer.${comp}_${inst} are different than in $archive/rest
rpointer_${inst}.${comp}, which are defined in
cime/cime_config/cesm/config_archive.xml.
For the moment I've made them consistent by using a
modified config_archive.xml, to make the archived versions
have the same form as the rundir.  But I'm wondering
whether they should be different.   Thanks for any insight.

**Comment by jedwards4b** [comment]
I don't believe that they should be different.  Please open a PR correcting this.

**Comment by bertinia** [comment]
This is the same issue as #1731. So, closing this new issue.
