### ISSUE TITLE
Allow SCAM to run multiple IOPs with the same executable

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1846]
This issue addresses a requirement that SCAM would like to have. They would like to create multiple cases with different SCAM IOPs - but using the same executable. Currently, the SCAM IOPs are obtained via different user_mods in the CAM user_mods directories. 
To address this use case - we would like to have the capability to have a "template" case that does not have any user_mods applied - and clone that directory multiple times with different user_mods - but with the executable created in the original create_newcase directory. 
To do this for SCAM - I propose that we create a "template" IOP that has NO user_mods. Build that case and the clone that case multiple times. 
The main new capability that this issue needs is to have a new user_mods argument to create_clone. 
Also - when --keepexe is added to create_clone
- any SourceMods in the original clone should point to the original template SourceMods. 
- the usermods directory CANNOT have any SourceMods (and an error should be thrown if that is the case)
- env_build.xml cannot modifications CANNOT be in the `shell_commands` file in usermods
- actually env_build.xml should not be allowed to have any modifications if `create_clone --keepexe `is used (so this new functionality needs to be added)

**Comment by rljacob** [comment]
So what is the current workflow for doing different IOPs?

**Comment by mvertens** [comment]
@rljacob - on the CESM side this is still being hashed out.  We have recently migrated SCAM away from using the stand-alone CAM scripts - and using CIME. The issue is that CAM can no longer configure either CLM or CICE - and so the stand-alone scripts would only permit CAM to configure an aquaplanet SCAM - which is very limiting. In addition, we are planning to remove all support for the CAM stand-alone scripts in the near future. The plan is to have a workflow with the above.

**Comment by rljacob** [comment]
Is this it?
Old workflow:  build SCAM with CAM's custom scripts and driver.
current workflow:  Build SCAM with CIME (Create_newcase) but only aquaplanet available.
proposed workflow:  Build aquaplanet SCAM with create_newcase, use create_clone to then make land or sea-ice SCAM's.

**Comment by jedwards4b** [comment]
SCAM = Single Column Atmospheric Model (there is by definition no scam land or scam sea-ice).  There are many possible single column locations and other settings that can be explored with a single executable,   This proposed workflow allows one to create a scam single executable and explore several specific cases through the create_clone tool.

**Comment by rljacob** [comment]
But why isn't this a normal use of create_clone?  Clone my scam case, edit user_nl and .xml files to try a different location or setting?

**Comment by jedwards4b** [comment]
It is sorta but we are adding the capability to use user_mods when running create_clone so that you can create certain predefined scam cases without having to make additional mods in each case - that is create_clone will make the required changes.

**Comment by rljacob** [comment]
Ok.  I just want to figure out what can-of-worms we're opening.  Are we ready for other users of create_clone+user-mods?
