### ISSUE TITLE
create_test --use-existing flag is broken

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1849]
This used to work, but now I get the following when running on yellowstone.  This is with cime5.3.0-alpha.31.

Job <./create_test --xml-machine yellowstone --xml-compiler intel --xml-category aux_cam --queue regular --test-root /glade/scratch/cacraig/aux_cam_20170829172201 --output-root /glade/scratch/cacraig/aux_cam_20170829172201 --project CESM0008 --test-id aux_cam_20170829172201 --walltime 3:00 --compare cam5_4_139 --use-existing> was submitted from host <yslogin1-ib> by user <cacraig> in cluster <yellowstone>.
Job was executed on host(s) <pronghorn01-ib>, in queue <caldera>, as user <cacraig> in cluster <yellowstone>.
</glade/u/home/cacraig> was used as the home directory.
</glade/u/home/cacraig/cam5_4_140-TRUNK/cime/scripts> was used as the working directory.
Started at Wed Aug 30 10:12:56 2017
Results reported on Wed Aug 30 10:12:58 2017

Your job looked like:

'# LSBATCH: User input
./create_test --xml-machine yellowstone --xml-compiler intel --xml-category aux_cam --queue regular --test-root /glade/scratch/cacraig/aux_cam_20170829172201 --output-root /glade/scratch/cacraig/aux_cam_20170829172201 --project CESM0008 --test-id aux_cam_20170829172201 --walltime 3:00 --compare cam5_4_139 --use-existing

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   0.82 sec.
    Total Requested Memory :                     -
    Delta Memory :                               -
    Run time :                                   2 sec.
    Turnaround time :                            9 sec.

The output (if any) follows:

Testnames: ['ERP_Ln9.f09_f09_mg17.F2000_DEV.yellowstone_intel.cam-outfrq9s', 'SMS_Lm13.f09_f09_mg17.F2000_DEV.yellowstone_intel.cam-outfrq1m', 'ERP_Ln9.f09_f09_mg17.FHIST_DEV.yellowstone_intel.cam-outfrq9s', 'ERP_Ln9.f09_f09_mg17.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s', 'ERP_D_Ln9.f19_f19_mg17.QPC6.yellowstone_intel.cam-outfrq9s', 'ERP_D_Ln9.f19_f19_mg17.QSC6.yellowstone_intel.cam-outfrq9s', 'ERS_Ln9.f19_f19_mg17.FSPCAMS.yellowstone_intel.cam-outfrq9s', 'SMS_Ld1.f09_f09_mg17.FW1850.yellowstone_intel.cam-reduced_hist1d', 'ERP_Ld3.f09_f09_mg17.FWHIST.yellowstone_intel.cam-reduced_hist1d', 'ERS_Ln9.f19_f19_mg16.FXHIST.yellowstone_intel.cam-outfrq9s']
Using existing test directory /glade/scratch/cacraig/aux_cam_20170829172201/SMS_Ld1.f09_f09_mg17.FW1850.yellowstone_intel.cam-reduced_hist1d.C.aux_cam_20170829172201
Traceback (most recent call last):
  File "./create_test", line 541, in <module>
    _main_func(__doc__)
  File "./create_test", line 536, in _main_func
    queue, allow_baseline_overwrite, output_root, wait, force_procs, force_threads, mpilib, input_dir, pesfile))
  File "./create_test", line 489, in create_test
    mpilib=mpilib, input_dir=input_dir, pesfile=pesfile)
  File "/glade/u/home/cacraig/cam5_4_140-TRUNK/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 227, in __init__
    self._update_test_status(test, phase, TEST_PEND_STATUS)
  File "/glade/u/home/cacraig/cam5_4_140-TRUNK/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 309, in _update_test_status
    phase_idx = self._phases.index(phase)
ValueError: 'SUBMIT' is not in list

**Comment by jgfouca** [comment]
@cacraigucar is your repo up to date? I fixed a bug very similar to this in the last couple weeks.

**Comment by cacraigucar** [comment]
This bug was indeed fixed since alpha.31.
