### ISSUE TITLE
st_archive: DART intermediate rpointer files are rpointer.unset

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1854]
Currently this issue is masked by https://github.com/ESMCI/cime/issues/1853 (which prevents DART intermediate restart / rpointer files from being archived at all); once that issue is resolved, this one will appear. As far as I can tell, this doesn't actually cause problems, but it does cause extraneous `rpointer.unset` files to appear in your archive directory.

This issue can be seen by introducing these diffs off of master: billsacks/cime@02c1616 . I plugged this into https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_16_r253 but I think you could see the same issue from standalone cime. I then did:

```
./create_newcase --case check_clm_archiving_issue_0830b --compset I1850Clm45Bgc --res f10_f10_musgs --user-mods-dir /glade/scratch/sacks/cesm_code/clm4_5_16_r253_newCime2/components/clm/cime_config/testdefs/testmods_dirs/clm/default

cd check_clm_archiving_issue_0830b
./case.setup
./xmlchange HIST_OPTION=ndays,HIST_N=1,REST_OPTION=ndays,REST_N=1
./xmlchange DOUT_S_SAVE_INTERIM_RESTART_FILES=TRUE
./case.build && ./case.submit
```

Near the end of the short-term archiver output, I see:

```
-------------------------------------------
doing short term archiving for dart (esp)
-------------------------------------------
Archiving for date 0001-01-02-00000
writing rpointer_file /glade/scratch/sacks/archive/check_clm_archiving_issue_0830b/rest/0001-01-02-00000/rpointer.unset
Archiving for date 0001-01-03-00000
writing rpointer_file /glade/scratch/sacks/archive/check_clm_archiving_issue_0830b/rest/0001-01-03-00000/rpointer.unset
Archiving for date 0001-01-04-00000
writing rpointer_file /glade/scratch/sacks/archive/check_clm_archiving_issue_0830b/rest/0001-01-04-00000/rpointer.unset
Archiving for date 0001-01-05-00000
writing rpointer_file /glade/scratch/sacks/archive/check_clm_archiving_issue_0830b/rest/0001-01-05-00000/rpointer.unset
Archiving for date 0001-01-06-00000
```

and indeed, in my archive directory, I see a bunch of rpointer.unset files whose contents are simply `unset`.

I'm not sure how to resolve this issue. I think it arises because dart is always added to the list of compset_comps in _archive_process:

```python
    compset_comps.append('dart')
```

and its entry in config_archive.xml is (see the rpointer section near the end):

```xml
  <comp_archive_spec compclass="esp" compname="dart">
    <rest_file_extension>inflate_restart.*</rest_file_extension>
    <hist_file_extension>\.True_State.*</hist_file_extension>
    <hist_file_extension>\.Prior_Diag.*</hist_file_extension>
    <hist_file_extension>\.Posterior_Diag.*</hist_file_extension>
    <hist_file_extension>\..+\.posterior*</hist_file_extension>
    <hist_file_extension>\..+\.prior*</hist_file_extension>
    <hist_file_extension>\..+$_obs_seq.*</hist_file_extension>
    <rest_history_varname>unset</rest_history_varname>
    <rpointer>
      <rpointer_file>rpointer.unset</rpointer_file>
      <rpointer_content>unset</rpointer_content>
    </rpointer>
  </comp_archive_spec>
```

But I'm not sure what the right thing is to do here.

cc @mvertens @bertinia @jedwards4b

**Comment by jedwards4b** [comment]
Use unset (or something else if you don't like that) as a keyword and don't write files that contain it.

**Comment by billsacks** [comment]
@kdraeder - @bertinia thought you might have some insight here.

**Comment by kdraeder** [comment]
I'm a bit out of my depth here (I don't work with CLM much)
but here are my thoughts.

It does seem like the 
    compset_comps.append('dart')
in _archive_process should be dependent on DATA_ASSIMILATION from env_run.xml.
Can that be done?

Farther down in the rpointer path some changes might be desirable.  
In _archive_rpointer_files any component with <rpointer> set to 'unset' 
will have rpointer files created;
                if rpointer_content is not 'unset':
                    if not ninst_strings:
                        ninst_strings = ["empty"]
                for ninst_string in ninst_strings:
                    ...
If that 'for' loop were indented 4 spaces, to be controlled by the 'if rpointer_content' line,
then no rpointer files would be created for 'unset'.

**Comment by billsacks** [comment]
@kdraeder Thanks a lot for these thoughts. To be clear: while I found the problem in a clm test, I actually don't think it has anything to do with clm. I'll let someone else evaluate and test your suggestion, since I'm supposed to be getting back to some other critical work.

**Comment by kdraeder** [comment]
I have not been able to reproduce the rpointer.unset problem.
My caseroot is /glade/p/work/raeder/Exp/Intermed_rpointer_unset
I built a cesm2_0_beta06 CAM, then inserted cime5.3.0-alpha.33 
into my cesm2_0_beta06 tree
/glade/p/work/raeder/Models/cesm2_0_beta06.

The relevant parts of config_archive.xml seem to be the same.

The output is (temporarily) in 
/glade2/scratch2/raeder/Intermed_rpointer_unset/{archive,run}

I'll try another run if anyone can point out what I missed
in recreating Bill's setup.

Bill; is seems like it should be a fast and helpful test to
try my indenting idea in your setup, if you still have it.

Kevin

**Comment by billsacks** [comment]
@kdraeder it looks like your case is not using that sandbox, but is instead using an out-of-the-box beta06 sandbox, which would not exhibit this problem:

```
[cheyenne5:/glade/p/work/raeder/Exp/Intermed_rpointer_unset]$ ./xmlquery CIMEROOT
	CIMEROOT: /glade/p/cesmdata/cseg/.dev/cesm2_0_beta06/cime
[cheyenne5:/glade/p/work/raeder/Exp/Intermed_rpointer_unset]$ ./xmlquery SRCROOT
	SRCROOT: /glade/p/cesmdata/cseg/.dev/cesm2_0_beta06
```

**Comment by kdraeder** [comment]
Thanks to Bill for pointing out my blunder.
I've recreated the 'rpointer.unset' problem and found the actual cause of it.
case_st_archive.py, line 124 is
                if rpointer_content is not 'unset':
but should be 
                if rpointer_content != 'unset':
We want to compare the contents, and not whether the 2 objects are the same object.
And I still think that the indenting I suggested earlier is the best choice.
Kevin

**Comment by mvertens** [comment]
Hi Kevin,

Thanks for tracking this down. Could you please raise an issue regarding
the problem and the solution. We can then get it into the next beta tag.

Mariana

**Comment by kdraeder** [comment]
I've looked in several sources for how to raise an issue,
but haven't found anything.  Does it just mean start an issue?

I think that I'm solving the problem that was the source of this issue, 
so it seems redundant to raise it in an additional issue.  
However, I do have more changes in case_st_archive.py 
which need to be checked by someone else, so I could combine 
this issue (1854) and those changes into a new issue.  
What do you recommend?
Kevin

**Comment by gold2718** [comment]
Isn't this (#1854) the appropriate issue? I think it just needs to be assigned to someone to create a PR using Kevin's solution.

**Comment by jedwards4b** [comment]
@kdraeder you need to create a PR with your changes, I can walk you through how do to that.
