### ISSUE TITLE
config_component v3 description not printed correctly

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1859]
I _think_ this is a bug, but I may be misunderstanding the intended functioning:

If I run this command from cesm2_0_alpha07c with the latest cime:

```
./create_newcase --case test_0829c --compset IHistClm50SpG --res f09_g17 --run-unsupported
```

It prints (among other things)

```
Compset longname is HIST_DATM%GSWP3v1_CLM50%SP_SICE_SOCN_MOSART_CISM2%EVOLVE_SWAV

ATM component is  Data driven ATM
```

I expected that the output would include `GSWP3v1 data set`  , based on this entry in datm's config_component.xml:

```xml
  <description modifier_mode="1">
    <desc atm="DATM[%QIA][%WISOQIA][%CRU][%CRUv7][%GSW][%GSWP3v1][%CPLHIST][%1PT][%NYF][%IAF]"> Data driven ATM </desc>
    <desc option="QIA"> QIAN data set </desc>
    <desc option="WISOQIA">QIAN with water isotopes</desc>
    <desc option="CRU"> CRUNCEP data set </desc>
    <desc option="CRUv7"> CLM CRU NCEP v7 data set </desc>
    <desc option="GSW"> GSWP3 data set </desc>
    <desc option="GSWP3v1"> GSWP3v1 data set </desc>
    <desc option="CPLHIST"> Coupler hist data set </desc>
    <desc option="1PT">single point tower site data set </desc>
    <desc option="NYF">COREv2 normal year forcing</desc>
    <desc option="IAF">COREv2 interannual forcing</desc>
  </description>
```

Yet it does not.

cc @jedwards4b @bertinia

**Comment by mvertens** [comment]
@billsacks - other than the output you see after create_newcase - is
everything else okay with the created case?

**Comment by billsacks** [comment]
@mvertens I didn't check, but I assume this only affects the output, since my understanding is that that's separate from the parsing of anything that actually affects the case.

**Comment by billsacks** [comment]
And indeed, I see this in env_run.xml, so it looks right:

```xml
env_run.xml:    <entry id="DATM_MODE" value="CLMGSWP3v1">
```
