### ISSUE TITLE
wait_for_tests needs a timeout option

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1867]
We run scripts_regression_tests.py from cron on some batch systems.  Jobs submitted to the batch system from the test may end up in the queue and not run if resources are not available.  I think that we need to add a timeout to wait_for_tests so that the nightly cdash testing can report the partial results even if batch jobs fail to run within a defined time window.  This option needs to be available at the scripts_regression_tests.py command line.

**Comment by jgfouca** [comment]
@jedwards4b we have some experience with this problem on the ACME side. We currently rely on Jenkins' timeout system, which sends a SIGTERM to the process when it's out of time. Wait_for_tests is designed to handle this signal gracefully (stop waiting on stuff and report to dashboard). Jenkins will wait a couple minutes for your processes to stop and, if not, will then finish them off with a SIGKILL.

This is a long way of saying most of the infrastructure you're asking for already exists and you might be able to implement what you need in bash.

**Comment by jedwards4b** [comment]
Your solution implies access to tools that we don't have, I am suggesting an alternative that can be completely contained within cime.

**Comment by jgfouca** [comment]
@jedwards4b sorry, I didn't read your comment closely enough. I gather that you want timeouts in the individual wait_for_tests calls in scripts_regression_tests.

**Comment by jedwards4b** [comment]
@jgfouca right
