### ISSUE TITLE
ERI test's cprnc.out files overwrite each other

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1869]
I don't think this causes any significant problems, but makes debugging a failed test harder:

An ERI test does two comparisons at the end of the test:

```python
        self._component_compare_test("base", "hybrid")
        self._component_compare_test("base", "rest")
```

However, due to #453 (closed as a wontfix), both of these sets of cprnc.out files are written with a `.base` suffix, leading the second set to overwrite the first.

Solutions could be either:

1. Resolving #453 - going back to the old behavior of using the second suffix for the suffix of the cprnc.out file

2. Changing one of the comparisons in the eri test; for example, I'd suggest:

```python
        self._component_compare_test("hybrid", "base")
        self._component_compare_test("base", "rest")
```

What do others think? Should we just do the simple solution of (2) for now? Or could this have any unforeseen consequences?

**Comment by jedwards4b** [comment]
My observation was that the file was appended, not overwritten.   Am I incorrect?

**Comment by billsacks** [comment]
Ah, you're right. Tricky, but maybe workable if others feel it's okay. Closing.
