### ISSUE TITLE
Errors with cime_bisect tool when not doing baseline comparison

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1872]
I tried running:

```
[cheyenne5:/glade/scratch/sacks/cesm_code/cesm2_0_alpha07_diffCime/cime]$ scripts/Tools/cime_bisect '-q premium --test-root . --walltime 2:00 ERI.f09_g17.B1850.yellowstone_intel.allactive-defaultio' 66e23fc 68fff51 -r scripts/bisect_0906a
```

Relevant output from this was:

```
RUN: git bisect run sh -c '/glade2/scratch2/sacks/cesm_code/cesm2_0_alpha07_diffCime/cime/scripts/create_test -q premium --test-root . --walltime 2:00 ERI.f09_g17.B1850.yellowstone_intel.allactive-defaultio --test-root scripts/bisect_0906a --compiler intel -p P93300641 -c -b  && scripts/Tools/wait_for_tests scripts/bisect_0906a/*cime_bisect/TestStatus -i'
  stat: 2
```

```
create_test: error: argument -c/--compare: expected one argument
```

So, it looks like it's trying to do a comparison, even though I did not tell it to, and according to the cime_bisect documentation:

```
  -b BASELINE_NAME, --baseline-name BASELINE_NAME
                        Baseline id for comparing baselines. Not specifying
                        means no comparisons will be done. (default: None)
```

There are also inconsistencies in the cime_bisect documentation: The top-level documentation:

```
cime_bisect <testargs> <last-known-good-commit> [<bad>] [--compare=<baseline-id>] [--no-batch]  [--verbose]
```

does not match the more detailed help message.

This makes me wonder if part of the problem is a misunderstanding of the usage based on inconsistent documentation.

**Comment by jgfouca** [comment]
@billsacks , I only use cime_bisect infrequently, so I'm not surprised that it's not in great shape. I have never attempted to use it in CESM mode, so that might not work.

Looking at the code, it's clear the python2->3 conversion was not done correctly on this file, which is the source of your baseline error. I will fix.
