### ISSUE TITLE
Review mode implementation in data models

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1877]
The data models need to review implementation of the different mode support.  It looks like in the latest refactor, only datm, desp, dice, and docn have a "select case for the mode".   Different modes should be supported in all data models, at least for NULL and not NULL to provide clearer paths for extensions.

**Comment by jedwards4b** [comment]
Can you please elaborate?   Has the refactor limited removed options that were previously available?

**Comment by apcraig** [comment]
I think the answer is probably not, but I'm not sure.  I think we need some input from @mvertens.
