### ISSUE TITLE
Test latest CIME with full CESM components

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#188]

**Comment by rljacob** [comment]
Issues that have come up:   different component developers aren't  understanding how xml is parsed.    Have to work on python AND the config_components.xml.
Can still use the perl buildlib/buildnml in the components.

**Comment by rljacob** [comment]
update:  most of pre-alpha and auxilary tests are passing on yellowstone/intel.

**Comment by jedwards4b** [comment]
cesm2 is on the way
