### ISSUE TITLE
Allow changing env_mach_pes without reset, rebuild

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1882]
We need some way to change env_mach_pes without requiring "case.submit --reset and a rebuild.  There are many cases that don't need to be recompiled if pes are changed.

**Comment by rljacob** [comment]
One idea, make "preview_run" capable of examining env_mach_pes and re-creating case.submit if necessary.   User has to know that its ok to just run preview_run after editing env_mac_pes

**Comment by jedwards4b** [comment]
Can you provide an example change that could be made without these steps?  The make system already understands dependancies and will not recompile code that doesn't require recompiling.

**Comment by rljacob** [comment]
I thought doing case.setup --reset, which you have to do for the submit script to be recreated, forces one to rebuild.  Does it not?

**Comment by jedwards4b** [comment]
It forces one to run the case.build script but what is actually rebuilt is handled by make dependancies.

**Comment by jedwards4b** [comment]
Is there really an issue here or can we close this - if you do really think that there is an issue can you provide an example?

**Comment by rljacob** [comment]
Yeah lets close it.  I'll try it and if there's a problem, open a more specific issue.
