### ISSUE TITLE
Rename PES_PER_NODE to MAX_MPITASKS_PER_NODE

### ISSUE THREAD

**Issue by fvitt** [ESMCI/cime#1885]
It seems that the total number of MPI tasks is incorrect when ntasks is set to a negative value (number of machine nodes) and nthreads is greater than 1.  The total of  MPI tasks is nthreads times too large.  My workaround has been to set ntasks to the number of MPI tasks I want (positive), rather than the number of machine nodes.

**Comment by jedwards4b** [comment]
Please provide a detailed description that will allow me to reproduce this problem.

**Comment by fvitt** [comment]
Jim,

Take a look a case /glade/scratch/fvitt/fw1850_ntks_nthrds_test

I set ntasks to -32 and nthreads to 3 expecting to place 12 mpi tasks on
each cheyenne node spread across 32 nodes -- 12x32=384 total number of mpi
tasks.  Instead I got ntasks = 1152.

**Comment by jedwards4b** [comment]
ntasks = -32 sets ntasks to 32*PES_PER_NODE (36 on cheyenne) = 1152.
The problem is in how this variable is defined, threads are not considered.   
If you want you can change PES_PER_NODE=12 and this case will work as you expect.

**Comment by fvitt** [comment]
Your suggestion seems to work.
What is the definition of PE?  Is a PE a singe execution thread or an MPI
task?  It seems PES_PER_NODE should be renamed as MPITASKS_PER_NODE.

**Comment by jedwards4b** [comment]
Your interpretation is correct.  What do others think about changing the name?

**Comment by mvertens** [comment]
I think that changing the name makes sense. Its much more intuitive to have
MIPTASKS_PER_NODE and would lead to fewer misunderstandings.

**Comment by jedwards4b** [comment]
It needs to be MAX_MPITASKS_PER_NODE since it can be greater than the actual number of mpi tasks on a node.
