### ISSUE TITLE
Wanted: command to clean the Srcfiles and Depends files for a component

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1889]
At least in some circumstances, if you rebuild a case (i.e., it already has been built, then you rerun `./case.build`) after adding a new source file, the build fails because the new source file and the changed dependency tree are not picked up.

For example, I added a file named NumericsMod.F90 to the CLM source tree, and added `use NumericsMod` in SoilHydrologyMod.F90. Then I reran `./case.build` and got:

```
   use NumericsMod       , only : truncate_small_values
      1
Fatal Error: Can't open module file 'numericsmod.mod' for reading at (1): No such file or directory
compilation terminated.
```

We discussed this on a recent cime concall, and felt that it would be too hard to automatically detect this situation. What I'm asking for here is something simpler: It would be great if there were some `./case.build` option that reset a given component's build _just enough_ to allow picking up any new source files and regenerating the dependency tree. From a quick look at the CESM Makefile, I think this would involve a new set of clean commands that just remove Srcfiles from the given component (which it seems would also force a regeneration of Depends).

So can we have something like `./case.build --reset-srcfiles [component]` that calls something like `make clean-srcfiles-component` for the given component?

**Comment by jedwards4b** [comment]
I think that this is a user knowledge issue - any attempt we make to automate it will be fraught with unintended consequences.    Even if we added this kind of command most users wouldn't look for it and wouldn't understand what it did when they found it.

**Comment by billsacks** [comment]
@jedwards4b sorry, I'm not sure I understand your concerns.

> any attempt we make to automate it will be fraught with unintended consequences

I understand your concerns with automating it. Please note that I'm not suggesting trying to automate it.

> Even if we added this kind of command most users wouldn't look for it 

Is that really a reason not to add it? By that argument, we should remove most of the tools in cime.

> and wouldn't understand what it did when they found it.

Isn't this just a documentation issue? Would you be open to adding this option if it were documented clearly?

The reason I'm running into this problem more now - and will continue to run into it more in the future - is that I am more and more using a workflow that greatly speeds up my development:

1. Use the same git clone for multiple branches, checking out the one I'm currently working on

2. Create a test case out of that clone, build it to completion

3. As I make changes to Fortran source code, rebuild that test case. The incremental rebuild tells me within seconds (rather than minutes) whether my changes compile.

The great thing about this workflow is that I can check out some other branch, make some small tweak, then do an incremental rebuild from the same test case, without having to set up a whole new test and wait minutes for the initial build. However, if the other branch has significant changes in what files are present, then I run into the problem listed in this issue. Sure, I can manually remove Srcfiles from the appropriate location, but particularly for CLM (where this is buried in a directory structure that's about 8 deep) this can take me a while to find, so a command like this would help me and others who want to do something similar.

**Comment by mvertens** [comment]
@billsacks - I think what you are proposing sounds very reasonable. I
myself have wanted this type of capability. We can add additional examples
in the User's Guide along with the documentation in case.build that would
clarify this usage.
