### ISSUE TITLE
Request for derived variable: NTASKS_PER_INST_COMPNAME

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1897]
Particularly with the new multi-driver code, it would be helpful if we had a set of derived variables (not to be set directly) in env_mach_pes.xml like `NTASKS_PER_INST_COMPNAME` for each component.

Reasons why this would be useful:

1. With the old multi-instance code, it was often confusing to users that the number of tasks per instance was _not_ NTASKS_COMPNAME but rather was (I think) floor(NTASKS_COMPNAME/NINST_COMPNAME). With the new multi-driver capability, this relationship is apparently more confusing: the number of tasks per instance is floor(NTASKS_COMPNAME/NINST_COMPNAME) if running without multi-driver, but is simply NTASKS_COMPNAME if running with multi-driver. Number of tasks per instance is something that users want to know, and it is asking a lot for them to all know this subtlety, so it would be great if this were listed explicitly for users.

2. Some components need to know the number of tasks per instance at build time. Before multi-instance, this was as simple as querying NTASKS_COMPNAME. With multi-instance, this needed to be expanded to also consider NINST_COMPNAME. With multi-driver, this gets more complicated, requiring all of these components to duplicate the logic where ntasks per instance depends on whether multi-driver is set. And what if the logic for number of tasks per instance changes again in the future? I am a firm believer in having any rule be coded in one and only one place, arguing for a central place in the cime scripts where the rule "number of tasks per instance" is encoded.

cc @gold2718 @dabail10 (for cice) @alperaltuntas (for pop, where this might also be an issue)

**Comment by gold2718** [comment]
I always wanted the behavior from the current multi-driver implementation. That is, you specify NTASKS_COMPNAME for one instance and the total NTASKS is computed from that.
I would suggest implementing that as a solution to the issues you raise but I worry about the number of multi-instance run scripts that will break and have to be rewritten. Does anyone have any idea about this?

**Comment by billsacks** [comment]
> I always wanted the behavior from the current multi-driver implementation. That is, you specify NTASKS_COMPNAME for one instance and the total NTASKS is computed from that.
> I would suggest implementing that as a solution to the issues you raise but I worry about the number of multi-instance run scripts that will break and have to be rewritten. Does anyone have any idea about this?

I agree that this is the more intuitive operation in general. However, in the non-multi-driver case, it could make understanding the full system PE layout more challenging. (e.g., you'd need to set ROOTPE_OCN equal to NTASKS_ATM * NINST_ATM.) Maybe that's okay, though. I'd be fine with this solution if others are.

**Comment by jedwards4b** [comment]
I'm just finishing up testing on the first solution - introducing
NTASKS_PER_INST_COMPNAME.   The other suggestion would be a lot more involved.
