### ISSUE TITLE
Creating cime_config/acme

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#19]
(coverted this issue from omnibus to single issue)

machines changes.
delete cime/machines
git mv cime/machines-acme to cime/cime_config/acme/machines and update acme's create_test (which still works) as needed.

**Comment by rljacob** [comment]
First suggetions:  
delete cime/machines
git mv cime/machines-acme to cime/cesm_config/acme/machines and update acme's create_test (which still works) as needed.

**Comment by rljacob** [comment]
Another one possibly for @jgfouca.
create cime/utils/python and move file.py files there.
Rename cime/scripts-acme to cime/scripts-python

**Comment by jgfouca** [comment]
Yep, on it

**Comment by jgfouca** [comment]
For the CSEG people, I see a lot of ACME config stuff that needs to be moved to cime_config/acme. I'll take care of that. Focus on the changes that impact your side.

**Comment by jgfouca** [comment]
Pushed to master.
