### ISSUE TITLE
Multi-driver problem(s) for large ensembles

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#1907]
I'm trying to build and run timing tests for multi-driver CAMs,
compared to single driver (but still multi-instance) CAMs.
I've found and solved (with help) several problems for the
case when the number of drivers > number of tasks/instance.
I'll gather and commit those later when I have a package that works
(unless that's not the right strategy here).  Now I've run into
a problem that I don't think I can figure out in a finite amount of time.
components/cam/src/dynamics/fv/spmd_dyn.F90: 
   color = iam/npes_yz
dies due to a divide by 0, because 
atm_in_0001: &spmd_fv_inparm
   npr_yz             = 0,1,1,0

npr_y   = npr_yz(1)    
npes_yz = npr_y*npr_z

I'm guessing that the default values of npr_yz should work in all cases,
even if they are not the most efficient.  Otherwise, some diagnostic 
output would help us set good values in the namelist.
The caseroot is 
/glade/p/work/raeder/Exp/Inst_50_drv_50_debug_mpi_comm_split

Kevin

**Comment by jedwards4b** [comment]
We are aware of this problem and it will be fixed in alpha07e.  In the meantime you can fix it in
components/cam/cime_config/buildnml 
```
Index: buildnml
===================================================================
--- buildnml	(revision 86666)
+++ buildnml	(working copy)
@@ -25,7 +25,7 @@
 ###############################################################################
     """Build the cam namelist """
 
-    # Build the component namelist 
+    # Build the component namelist
     if compname != "cam":
         raise AttributeError
 
@@ -43,6 +43,7 @@
     RUN_REFCASE         = case.get_value("RUN_REFCASE")
     RUN_REFDATE         = case.get_value("RUN_REFDATE")
     RUN_REFTOD          = case.get_value("RUN_REFTOD")
+    MULTI_DRIVER     = case.get_value("MULTI_DRIVER")
 
     #--------------------------------------------------------------------
     # call buildcpp to set both cppdefs and config_cache.xml file for generating namelist
@@ -51,7 +52,7 @@
     if not os.path.exists(os.path.join(caseroot,"LockedFiles","env_build.xml")):
         call_buildcpp = True
     else:
-        file1 = os.path.join(caseroot,"env_build.xml")  
+        file1 = os.path.join(caseroot,"env_build.xml")
         file2 = os.path.join(caseroot,"LockedFiles","env_build.xml")
         if not filecmp.cmp(file1, file2):
             call_buildcpp = True
@@ -64,7 +65,7 @@
         except:
             raise
 
-    # Verify that we have a config_cache file (generated by the call to buildcpp) 
+    # Verify that we have a config_cache file (generated by the call to buildcpp)
     camconf = os.path.join(caseroot, "Buildconf", "camconf")
     filename = os.path.join(camconf, "config_cache.xml")
     expect(os.path.isfile(filename),
@@ -139,9 +140,11 @@
         # -----------------------------------------------------
         # call build-namelist
         # -----------------------------------------------------
+        if MULTI_DRIVER:
+            ntasks = NTASKS_ATM
+        else:
+            ntasks = int(NTASKS_ATM) / ninst
 
-        ntasks = int(NTASKS_ATM) / ninst
-
         buildnl_opts = ["-ntasks", str(ntasks), "-csmdata", din_loc_root,
                         "-infile", os.path.join(camconf, "namelist")]
```

**Comment by kdraeder** [comment]
Thanks, Jim.
Since my/our update of my local cime (fix_st_archive) this test now
dies during submission (instead of during the namelist read) with:
   Calling /glade/p/work/raeder/Models/cesm2_0_beta06/cime/src/drivers/mct/cime_config/buildnml
   NOTE: ignoring setting of rof2ocn_liq_rmapname=idmap in seq_maps.rc
   NOTE: ignoring setting of glc2ice_rmapname=idmap in seq_maps.rc
ERROR: Need to provide valid mapping file between glc and ocn in xml variable glc2ocn_rmapname

I didn't get this error in the single driver, 50 instance case,
which submitted and ran fine (with a cime from a couple weeks ago).

This is an F2000_DEV compset; 2000_CAM60_CLM50%BGC_CICE%PRES_DOCN%DOM_MOSART_CISM1%NOEVOLVE_SWAV
In src/drivers/mct/cime_config/buildnml:write_seq_maps_file 
should the mapping between glc and ocn be ignored like glc2ice or rof2ocn?
Thanks,
Kevin

**Comment by billsacks** [comment]
@jedwards4b isn't this the same as the problem you found, where we need to add glc2ocn_rmapname to the list of mapping files that are ignored when checking for idmap?

I'm confused, though, because I already see this in driver_cpl/cime_config/buildnml on master:

```python
ignore_idmaps = ["rof2ocn_fmapname", "glc2ice_rmapname", "glc2ocn_rmapname"]
```

**Comment by jedwards4b** [comment]
That code is also on the branch  - but I'm pretty sure this branch is not compatible with the beta06 components and Kevin should update first.

**Comment by kdraeder** [comment]
I seem to have fixed all the relevant bugs in my sandbox and have generated
a timing picture (see attached).  The process was a bit messy, so if it doesn't
make sense, I might need to re-run the tests using a fixed, consistent CIME.
What I get from the picture is that the multi-driver implementation scales
well inside the fortran code (CPL:INIT time is roughly independent of num_inst),
but something outside the fortran is not scaling as well (Wall clock increases
by 3x from 2 instances to 50), so there's no net gain in wall clock by using
multi-driver.  My first guess is the building of namelists, which was a problem
in Montuoro's first implementation.
[single+multi_driver_times.xlsx](https://github.com/ESMCI/cime/files/1341864/single.multi_driver_times.xlsx)

**Comment by kdraeder** [comment]
@mvertens wants to see the results of the multi-driver timing tests.
See the previous comment for details.

**Comment by kdraeder** [comment]
@jedwards4b suggested tests using --skip-preview-namelists added to
case.submit.  I'm trying that and will add the results here.

**Comment by kdraeder** [comment]
That argument was passed to qsub in case.run, so the submission failed.
Submitting job script 
qsub -q regular -l walltime=0:30:00 -A P86850054 case.run  --skip-preview-namelist
ERROR: Command: 'qsub    -q regular -l walltime=0:30:00 -A P86850054 case.run  --skip-preview-namelist' failed with error 'usage: qsub' ...

**Comment by jedwards4b** [comment]
I've opened issue #1935 for this and will look at it tomorrow.

**Comment by jedwards4b** [comment]
Hi Kevin,
Please try the following change in cime/scripts/lib/CIME/case_run.py
```
diff --git a/scripts/lib/CIME/case_run.py b/scripts/lib/CIME/case_run.py
index e2d09ef..ed57842 100644
--- a/scripts/lib/CIME/case_run.py
+++ b/scripts/lib/CIME/case_run.py
@@ -280,6 +280,7 @@ def case_run(case, skip_pnl=False):
         if cycle > 0:
             case.set_value("CONTINUE_RUN", "TRUE")
             lid = new_lid()
+            skip_pnl = True
 
```
I just want to establish that this is the performance issue before we put in a more permanent fix.

**Comment by kdraeder** [comment]
Here's the failure message from submission after I added the skip_pnl line:
Submit job case.run
Submitting job script 
qsub    -q regular -l walltime=0:30:00 -A P86850054 case.run  --skip-preview-namelist
ERROR: Command: 'qsub    -q regular -l walltime=0:30:00 -A P86850054 case.run  
              --skip-preview-namelist' failed with error 'usage: qsub ....

**Comment by jedwards4b** [comment]
Sorry I wasn't clear: you no longer need the --skip-preview-namelist flag to case.submit.

**Comment by kdraeder** [comment]
It ran without the --skip-preview-namelist, but the wall time was only reduced
to 593 from 612 seconds.

**Comment by jedwards4b** [comment]
Did you have some expectation that this would reduce the initialization time?  I think that you will need the pause/resume functionality to see the real benefit of this change.

**Comment by kdraeder** [comment]
It sounded like a possibility, based on our experience with Montuoro's
first implementation of multi-coupler, and the name of the argument.
My impression of the pause-resume is that it will speed up the execution
of the fortran code when stopping for DART, while preview_namelists
is a shell script called before the fortran.

**Comment by gold2718** [comment]
I thought `preview_namelists` is only called once even if the DART loop runs `n` times. Is that not correct?

**Comment by jedwards4b** [comment]
preview_namelists was called each cycle, this modification changes that so that it's only called the first time.  But the timing output suggests that the majority of time is spent in model initialization, which the multi driver code will do nothing to improve.

**Comment by kdraeder** [comment]
In the timing table and picture I attached above it looks to me like 
the multi-driver (orange curve) CPL:INIT time stays more or less constant 
when increasing ensemble size from 10 to 50 (~200 s), while the wall clock
(which includes the CPL:INIT) increases from 300 to 600 s.  None of the other
timing numbers from the fortran part of the job (CPL:RUN_LOOP,...)
increased notably with larger ensemble size.  So it seems that the wall clock 
increase must come from outside the fortran.  Maybe I'm reading
the timing files incorrectly.  If so, I'd appreciate some pointers.

**Comment by kdraeder** [comment]
Jim has installed code to not call preview_namelists for the cycles 2,...
of each job, which saves the time needed to copy
["*_in_[0-9]*", "*modelio*", "*_in",
   "*streams*txt*", "*stxt", "*maps.rc", "*cism.config*"]
from $rundir to $caseroot/CaseDocs.
For a 50 instance ensemble, this saves 4 minutes per cycle,
which is 40% of the wall clock for a CAM4 2 degree job.
The copy for cycle 1 could be sped up by 100x by using
tar -z -c $caseroot/nml.gztar *_in_[0-9]* "*modelio* *_in* \
     *streams*txt* *stxt *maps.rc *cism.config*

I've attached the new timing picture.
[single+multi_driver_times.xlsx](https://github.com/ESMCI/cime/files/1360582/single.multi_driver_times.xlsx)

Thanks for all the core hours!
Kevin

**Comment by kdraeder** [comment]
@mvertens will want to see the updated timing numbers.
As far as I can see, the only thing keeping this issue open is the
question of whether to replace the copy of all the namelist(-like)
files to CaseDocs with something faster.

**Comment by jgfouca** [comment]
@kdraeder closing this issue. We can open a new ticket for improving file copies.
