### ISSUE TITLE
Want confirmation of some change made to system_tests_compare_two in #1904

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1909]
@jedwards4b can you clarify / confirm this change that you made to system_tests_compare_two.py in #1904 

```diff
+            # Go to case2 for the generate and compare baselines
+            self._activate_case2()
```

I am pretty sure that is NOT what we want to do in general. system_tests_compare_two is set up to put all necessary files for comparison / generation in the case1 directory. I'm pretty sure that some things will break if this is done from case2. Can you clarify what the problem was that you were trying to solve with that change?

**Comment by jedwards4b** [comment]
I believe this is correct.   The internal comparisons happen above this line and this only affects generation and comparison of baselines.

**Comment by billsacks** [comment]
Yes, I'm referring to the generation and comparison of baselines, too. Can you please describe the problem you were having before introducing this line?

**Comment by jedwards4b** [comment]
In the ERR test run1 archives output and so the history files are not necessarily present and thus cannot be copied to the baseline directory.

**Comment by billsacks** [comment]
> In the ERR test run1 archives output and so the history files are not necessarily present and thus cannot be copied to the baseline directory.

Okay, thanks. Now I understand the problem. I still think that the current fix is problematic, though:

1. I think that scripts/tools/component_generate_baseline and component_compare_baseline won't work on an ERR test now. (This fix doesn't make things any worse, but it also doesn't make things any better in that respect.)

2. I'm pretty sure that tools/cprnc/summarize_cprnc_diffs will not work at all now. (I think I'm the only one who uses this, but I use it heavily.)

3. Have you confirmed that various other things work with this fix? Off the top of my head, I'm thinking about:

a. Whether the TestStatus is appended in the correct case directory: should be put in the case1 directory

b. If a comparison fails, does the cprnc.out file get copied into the correct place?: should be put in the case1 directory (I think this is done in wait_for_tests)

4. It is confusing to users if the cprnc.out files from baseline comparison are sometimes generated in the main case directory (for things not using system_tests_compare_two), but sometimes generated in the case2 directory.


Rather than this fix that affects behavior in such a far-reaching way, I'd prefer a fix more specific to the ERR test. For example, could the ERR test copy the relevant *.nc files from case1 to case2 at the end of case2 for the sake of baseline generation and comparison? I know that's a bit ugly, and maybe there's something better, but I'd rather have some ugliness restricted to this one test type rather than having ugliness applying to all test types.

Or, backing up a bit: I thought that, at least at one point, comparison and generation were done using the '*.base' files. Am I remembering wrong, or is that no longer true? If that were true, then I'm not seeing why this would be an issue for the ERR test, because I don't think the '*.base' files should be archived, right?

**Comment by billsacks** [comment]
Actually, I think I see a cleaner solution than this:

> For example, could the ERR test copy the relevant *.nc files from case1 to case2 at the end of case2 for the sake of baseline generation and comparison?

If the problem is that some of the \*.nc files are moved out of case1 into the archive space, but the \*.nc.base files are still present, then: Can we have the ERR test do something like: foreach file named FOO.nc.base, if there is no file named FOO.nc then copy FOO.nc.base to FOO.nc.

**Comment by jedwards4b** [comment]
why would it be .base and not .rest?   Are we not using the output of the second run in the baseline directory?

**Comment by billsacks** [comment]
> why would it be .base and not .rest? Are we not using the output of the second run in the baseline directory?

It doesn't really matter, I guess, since they should be the same. But up until now we have been using the output of the first (.base) run for baseline generation and comparisons. You can see evidence of this by looking at *.nc.cprnc.out files: these files show that it's the case1 (i.e., main case) files that have been used for baseline comparisons. I'm looking at this with a slightly older version of cime, as is currently used in CLM: e.g., see the *.nc.cprnc.out files in /glade/scratch/sacks/PEM_D_Ld5.ne30_g16.I2000Clm50BgcCru.yellowstone_intel.clm-default.GC.0915-0612y_i/run . I also see this behavior with more recent versions of cime, e.g. /glade/scratch/fischer/ERP_D_Ln9.f19_f19_mg17.QPC6.yellowstone_intel.cam-outfrq9s.GC.c2_0_a7d_int/run

By the way: at a glance, it looks like this may no longer be true:

> Or, backing up a bit: I thought that, at least at one point, comparison and generation were done using the '*.base' files. Am I remembering wrong, or is that no longer true?

**Comment by jedwards4b** [comment]
I don't think that it was ever true.   Anyway I have another fix for the ERR test, PR coming soon.

**Comment by billsacks** [comment]
> I don't think that it was ever true

I just did a bit of digging to understand the history. It was true when system_tests_compare_two was first put in, at which point we were still using component_compgen_baseline.sh to do generation and comparison: this tool was hard-coded to use .base files. But I think it's no longer true. So it was originally necessary for us to use the .base files from case1 for generation/comparison. Now it shouldn't matter if we use .base or .rest, but it would still be best to do it from case1.
