### ISSUE TITLE
New two-case ERP test mistakenly fails some comparisons between initial and restart cases

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1910]
With the new two-case ERP test (based on the system_tests_compare_two infrastructure), in some uncommon circumstances, the base vs. restart comparisons can fail when they shouldn't.

Examples are these tests:

    FAIL ERP_D_Ld5.f10_f10_musgs.I2000Clm50Sp.yellowstone_intel.clm-decStart COMPARE_base_rest

    FAIL ERP_D_P15x2.f10_f10_musgs.IHistClm50Bgc.yellowstone_intel.clm-ciso_decStart COMPARE_base_rest

I understand the problem, but I'm not quite sure what to do.

Here's the problem: The test starts in late December. The initial case runs through the end of the year, at which point CISM writes a history file, then keeps going a bit further. The model writes restart files on Jan 2. The restart case picks up on Jan 2 and runs for a few days. The key point is that CISM only writes a history file on the year boundary, so it writes a history file in the initial case, but no history file in the restart case. So the comparison fails because it can't find a match in case2 for the CISM history file found in case1.

Prior to converting the ERP test to system_test_compare_two, this passed (arguably for a bad reason) because there was a single case directory, so it treated the history file produced by the initial run as both the .base and the .rest file.

Off-hand, I can see three possible solutions:

(1) I think (but am not 100% positive) that I could add a user_nl_cism setting in CLM's relevant testmods that forces CISM to produce a history file at the same time in both runs.

(2) Relax the error check that causes a failure if a history file is found in one case but not the other. I could imagine some logic like this:

- In restart tests, call a function that determines the date/time-stamp of the restart (e.g., by looking for the last cpl.r file?)

- Pass that date/time-stamp to a new optional argument to _component_compare_test (and whatever it calls); this argument could be called "ignore_hists_before_datetime"

- In the logic that currently says, "fail the test if a history file is found for one case but not the other":

        for item in one_not_two:
            comments += "    File '{}' had no counterpart in '{}' with suffix '{}'\n".format(item, from_dir2, suffix2)
            all_success = False
        for item in two_not_one:
            comments += "    File '{}' had no counterpart in '{}' with suffix '{}'\n".format(item, from_dir1, suffix1)
            all_success = False

add some extra code that says: if the date/time-stamp of item is <= ignore_hists_before_datetime, then do NOT set all_success to False.

(3) Relax the error check even further: Allow a given test type (e.g., ERP) to set a variable saying, "Don't fail if you find a history file in one case but not the other". Then don't try to do all of the complex stuff listed in (2), but instead just skip setting all_success = False if that variable is set.

Any opinions on which of these is best, or any other ideas? (1) would be easier than (2) short-term, but it feels like a kludge, and I wouldn't at all be surprised if we run into similar problems to this in other scenarios (so we'd keep having to add more kludges to get ERP tests to pass). (2) feels like a generally useful thing to have in place, but would be challenging if not all components follow the same conventions in terms of how date stamps appear in history file names (which I suspect they don't). (3) could let some legitimate problems fall through the cracks.

I'm personally inclined to go with (3), because I don't feel like the risk here is that large. (And we wouldn't be that much worse off than we were before converting to system_tests_compare_two.) But I'm open to other thoughts.

**Comment by mvertens** [comment]
I agree that (3) is the way to go at this point. I don't like (1) - its not
a general long term solution. (2) needs a lot more thought and testing. I
think that (3) at this point would satisfy the current requirements.

**Comment by billsacks** [comment]
Okay, I can do (3) unless anyone objects ( @jedwards4b @jgfouca any objections?)

**Comment by jedwards4b** [comment]
No objections here.

**Comment by jgfouca** [comment]
I'm worried that (3) will cause us not to see real problems. I would prefer (1).

**Comment by mvertens** [comment]
@jgfouca - I see your point. However, think of the case where we do runs where no history files are created (because we are using monthly history output inadvertently) but the test passes since there are no files to compare other than coupler files. We are not insisting that all components produce history files for the tests to pass. This is not quite the same case here - but I think there is an analogy. I think its up to the developers to create tests that do not give false positives - but I think that (3) provides us with less burdensome requirements for always ensuring history files are present in both phases of a test.

**Comment by jgfouca** [comment]
I can live with it if it's only for ERP

**Comment by billsacks** [comment]
I agreed with @mvertens 's comment when she wrote it. But as I think about it more, maybe (1) is sufficient for now, with the plan that we'll revisit this if the problem starts to show up in other contexts.

**Comment by billsacks** [comment]
Closing this as a wontfix, since with option (1) the fix will instead be in CLM.
