### ISSUE TITLE
Queue selection is not updated when PE layout changes

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#1913]
I've hit a case that CIME does not handle very well at all. Here is the problematic pattern:

- create_test FOO.a.b
  - create_newcase ...
    - Selects a certain queue for case.test job
  - case.setup
  - case.build: FOO test case makes changes that require more nodes to be used, in this case the additional nodes mean that the queue selected during create_newcase is no longer able to run the job
  - case.submit FAILS

In order to solve the above I proposed:
* Changing all queue specifications to use nodemin and nodemax instead of min/max tasks
* Queue selections will be recomputed in case.initialize_derived_attributes unless the user has forced us to try to use a certain queue
  - initialze_derived_attributes always computes a fresh value for num_nodes, this value should then be fed into env_batch so that we can check if the queue selections for case.run and case.test are still valid

**Comment by jgfouca** [comment]
@jedwards4b

**Comment by jedwards4b** [comment]
I'm okay with this proposal.
