### ISSUE TITLE
More path length issues with new system_tests_compare_two

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1914]
We have been running into a number of path length issues with the new system_tests_compare_two, where CIME_OUTPUT_ROOT for case2 looks like `$CIME_OUTPUT_ROOT/TESTNAME/case2/TESTNAME`, with the bld and run directories under there. For long testnames, this creates some very long source file names, which exceed various maximum limits for compilers. The latest issue I'm running into is that CMake tries to compile a test program in a subdirectory of the build directory, and ifort barfs when the abs path to this test source file is too long.

**Comment by billsacks** [comment]
I propose fixing this by moving the location of the case2 bld directory.

So we'll still have the run directory here: 

`$CIME_OUTPUT_ROOT/TESTNAME/case2/TESTNAME/run`

But we'll have the bld directory here:

`$CIME_OUTPUT_ROOT/TESTNAME/case2/bld`

I'll probably put in a symlink: `$CIME_OUTPUT_ROOT/TESTNAME/case2/TESTNAME/bld -> $CIME_OUTPUT_ROOT/TESTNAME/case2/bld` to make it easier for people to find the bld directory.

**Comment by billsacks** [comment]
@fischer-ncar @ekluzek and @jedwards4b I think this will solve the cism intel build problems Chris ran into.

**Comment by jedwards4b** [comment]
Maybe just change both EXEROOT and RUNDIR to take out the $CASE?
 ./xmlquery EXEROOT --no-resolve
	EXEROOT: $CIME_OUTPUT_ROOT/$CASE/bld
yslogin6: ~/sandboxes/cesm2_0_alpha/cime/scripts/ERR.f19_g16_rx1.A.yellowstone_intel.GC.20170921_090015_k45txl
:) ./xmlquery RUNDIR --no-resolve
	RUNDIR: $CIME_OUTPUT_ROOT/$CASE/run

I don't think that you need to add the link to the old path, no-one has been using this enough for that to be a difficulty.

**Comment by billsacks** [comment]
@jedwards4b okay, I'm happy with that suggestion. So to be clear, we'd have:

Run directory:

`$CIME_OUTPUT_ROOT/TESTNAME/case2/run`

Bld directory:

`$CIME_OUTPUT_ROOT/TESTNAME/case2/bld`

Is that what you're thinking?

I'm thinking we'd still have case2's `CIME_OUTPUT_ROOT` be 

`$CIME_OUTPUT_ROOT/TESTNAME/case2`, as it is now, but nothing should appear under `$CIME_OUTPUT_ROOT/TESTNAME/case2/TESTNAME` any more.

**Comment by jedwards4b** [comment]
Yes - that's it.  By default (if you don't using the --test-root option) the case directory will still appear in $CIME_OUTPUT_ROOT/TESTNAME/case2/TESTNAME
