### ISSUE TITLE
Add new capabilities to test short term archive.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1927]
The short term archiver works, mostly, just with filenames so it should be possible to set up a "fake" run directory with empty files in whatever config we want to test.  If you want to test archiving 4 years of data with output every month and 4 additional cam history files, you don't need to actually run that, just populate the rundir with files with the correct names.

The exception is the cam.r file which has to really be netcdf because the archiver opens it to read nhfil.

So I'm envisioning some kind of fake filemaker that will be used by multiple future archive tests.

**Comment by mfdeakin-sandia** [comment]
I was considering making this issue for myself :+1:
Though my approach was going to be to make it more modular w.r.t the filesystem to make it more doc-testable.

**Comment by rljacob** [comment]
Tagging @kdraeder and @jedwards4b  .  We still have no way of testing the archiver's operations on directories full of files.

**Comment by kdraeder** [comment]
The CAM+DART software now uses the CESM file naming convention,
so it would be helpful to us to include file names generated by DART
in whatever st_archive testing is developed.  I have a directory full of
DART+CAM+POP fake files, which I made by echoing each file name
into a file of the same name.  The exception is the one mentioned by @rljacob ; 
the .r. files for various components, including esp.  The dart.r file has just
the names of the DART restart history files in it.  It was created by ncgen just
for that purpose.  The same thing could be done for the other components,
but I haven't done that yet.

I've attached a zip file that contains a file that outlines (in csh) how I
created the minimal dart.r file and contains the directory referenced above.
Note that this case is a multi-instance, so many filenames have
_#### attached to the $comp, which excercizes more parts of st_archive.
[CAM+POP+DART_run+fake_restarts.zip](https://github.com/ESMCI/cime/files/1891743/CAM.POP.DART_run.fake_restarts.zip)

**Comment by kdraeder** [comment]
@jedwards4b Thanks!
If you don't want to make the minimal CLM restart files (just the 
restart history names), and don't mind the size of the real files, 
I can point you to them (until they're scrubbed).

**Comment by jedwards4b** [comment]
I only need the file names, but yes if you could provide a directory.

**Comment by kdraeder** [comment]
/glade2/scratch2/raeder/CIME_DA_vars_10/archive_2/rest/2008-08-02-64800/*clm2*.r.*
