### ISSUE TITLE
Add ability to query test types

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1929]
There was a request from users of CLM to be able to get a list of the different test types (ERS, ERP, etc.) and their meaning.

Coming in a PR shortly....

**Comment by rljacob** [comment]
That should also be in our Users's Guide under "testing".

**Comment by billsacks** [comment]
@rljacob there is already a todo in the User's guide to add this. We also need documentation of query_testlists in there, which will presumably go where there is currently a place-holder for "manage_testlists" (which no longer works with new-style test lists). Do you think we should open a separate issue for these documentation needs?

As an aside: I started thinking about updating that page (http://esmci.github.io/cime/users_guide/testing.html) yesterday, but quickly got overwhelmed due to the completely different workflows in ACME vs. CESM. I'm not quite sure how to organize this to make it useful to both CESM and ACME users.
