### ISSUE TITLE
create_clone --keepexe --user-mods-dir USER_MODS_DIR is broken

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1954]
In this case exeroot in create_clone in case.py is actually set to the value of USER_MODS_DIR and the following exceptions is triggered in case_clone.py:
```
    # set exeroot and rundir if requested
    if exeroot is not None:
        expect(not keepexe, "create_case_clone: if keepexe is True, "
               "then exeroot cannot be set")
```        
I believe that the problem is due to the fact that create_clone should have keyword-value pairs for optional arguments in create_clone as follows:

    with Case(cloneroot, read_only=False) as clone:
        clone.create_clone(case, keepexe=keepexe, mach_dir=mach_dir, project=project,
                           cime_output_root=cime_output_root, user_mods_dir=user_mods_dir)

I am concerned that this type of error did not get trapped before and we need to have tests that use it.

**Comment by billsacks** [comment]
fix incoming
