### ISSUE TITLE
Limit resolutions that a compset can use?

### ISSUE THREAD

**Issue by jonbob** [ESMCI/cime#1967]
Is there a way to limit the resolutions or girds that a compset can be combined with? Or trigger an error for unsupported combinations? One easy example of this would be MPAS compsets referencing POP/CICE resolutions, but we also have an issue in E3SM of a compset that requires spun-up initial conditions getting used with a resolution that does not have the specified IC files.

**Comment by rljacob** [comment]
What do you think @jedwards4b or @mvertens ?    Do we currently allow any compset to be matched with any grid in a create_newcase call with no sanity checking?

**Comment by mvertens** [comment]
There is the currently the capability to have a <science_support> element
in the <compset> block that is grid dependent. For example, in CAM
config_compsets.xml there is:

  <compset>
    <alias>F2000_DEV</alias>
 <lname>2000_CAM60_CLM50%BGC_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV</lname>
    <science_support grid="f09_f09_mg17"/>
  </compset>


I don't think we currently have the capability to limit the resolutions
that the compset can be run at. @jedwards4b - do you agree with this
statement? We could potentially add a new element that would limit the
resolutions of the compset - e.g. <grids_only> or something like that.

In terms of the example ofinitial conditions, CLM does currently support
doing run-time regridding of the initial dataset from an input spinup
dataset to the target model grid. I'm not sure if ALM does that at this
point. If not - there are ways to run an offline interpolation code. But I
would be wary of saying you would not support a model grid because spun up
initial conditions are not available. In that case - I think that the
<science_support> element would be more appropriate.

**Comment by jedwards4b** [comment]
We do have the limitation in more recent cime versions in that if mapping files don't exist for a particular grid combination then an error will be generated at build time.   In at least some cases an incorrect grid will be caught and corrected by the component model (outside of cime) in it's buildnml step - MPAS may be able to do something similar.   The issue of IC files should also perhaps be trapped in the buildnml stage by the component model.

**Comment by jonbob** [comment]
@mvertens - what happens if a grid is not listed in <science_support>?

**Comment by mvertens** [comment]
@jonbob - if you specify a grid that does not exist then the science support field will not be matched However,  I'm not sure that you will abort with an unmatched grid in that field. @jedwards4b - I don't think we check that grid attributes are actually valid - they are simply used for matching. Is this correct?

**Comment by jedwards4b** [comment]
```
 create_newcase --case foo --compset B1850 --res f19_f19
Compset longname is 1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD
Compset specification file is /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/../cime_config/config_compsets.xml
ERROR: grid alias f19_f19 not valid for compset 1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD
```
and
```
 create_newcase --case foo --compset A --res T62_g37 
Compset longname is 2000_DATM%NYF_SLND_DICE%SSMI_DOCN%DOM_DROF%NYF_SGLC_SWAV
Compset specification file is /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/src/drivers/mct/cime_config/config_compsets.xml
Compset forcing is 1972-2004
ATM component is  Data driven ATM 
LND component is Stub land component
ICE component is dice mode 
OCN component is DOCN 
ROF component is Data runoff model
GLC component is Stub glacier (land ice) component
WAV component is Stub wave component
ESP component is 
Pes     specification file is /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/src/drivers/mct/cime_config/config_pes.xml
Machine is cheyenne
Pes setting: grid          is a%T62_l%null_oi%gx3v7_r%rx1_g%null_w%null_m%gx3v7 
Pes setting: compset       is 2000_DATM%NYF_SLND_DICE%SSMI_DOCN%DOM_DROF%NYF_SGLC_SWAV 
Pes setting: tasks       is {'NTASKS_ATM': -1, 'NTASKS_ICE': -1, 'NTASKS_CPL': -1, 'NTASKS_LND': -1, 'NTASKS_WAV': -1, 'NTASKS_ROF': -1, 'NTASKS_OCN': -1, 'NTASKS_GLC': -1, 'NTASKS_ESP': -1} 
Pes other settings: {}
 Compset is: 2000_DATM%NYF_SLND_DICE%SSMI_DOCN%DOM_DROF%NYF_SGLC_SWAV 
 Grid is: a%T62_l%null_oi%gx3v7_r%rx1_g%null_w%null_m%gx3v7 
 Components in compset are: ['datm', 'slnd', 'dice', 'docn', 'drof', 'sglc', 'swav', 'sesp', 'cpl', 'dart'] 
STOP:  
This compset and grid combination is untested in CESM.  Override this warning with the --run-unsupported option to create_newcase.
```
Note that the second case uses the cesm test xml method that acme doesn't use.

**Comment by jonbob** [comment]
@jedwards4b - thanks. How do the scripts know the first one is invalid? Not just from <science_support>, I assume? How hard would it be to implement <grids_only>?

**Comment by jedwards4b** [comment]
The config_grids.xml file (version 2.0) list which compsets are valid for each grid https://github.com/ESMCI/cime/blob/master/config/cesm/config_grids.xml

**Comment by jonbob** [comment]
Thanks @jedwards4b - I bet we can work with that

**Comment by jonbob** [comment]
@jgfouca - I'm not seeing the e3sm config_grids file set up this way. Is that on our radar?

**Comment by jgfouca** [comment]
yes, but the work should be tracked within E3SM since it's specific to that model.

**Comment by jonbob** [comment]
I guess I don't understand what you're saying then

**Comment by jgfouca** [comment]
We need to make a story on the E3SM scrum board (or a github ticket) to change our grid file to be 2.0-compatible.

**Comment by jonbob** [comment]
Is this issue enough? Our grid file seems to be full of grids we don't support anyway

**Comment by jgfouca** [comment]
The issue we are commenting-on now is in ESMCI. @jedwards4b has indicated the capability to do what you wanted in this ticket already exists in CIME, we just need to update our grid file to be able to take advantage of it. That make this an E3SM-specific task that we should track in E3SM.
