### ISSUE TITLE
Importing DO_DATA_ASSIMILATION into components

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#1980]
This issue is related to #1807 (CESM+DART tag testing)
and is created to handle the inclusion of DART SourceMods
into the CESM trunk, so that they are not needed.
After some discussions it appears (to me) that the most
pervasive change needed is to provide the value of
env_run.xml:DO_DATA_ASSIMILATION to the components,
so that they can take appropriate actions ( restart in a certain
mode, change printed output, etc.).  

I can start looking at how to implement that, but I'll be starting
from mostly ignorance.  It would be helpful if someone would
outline how an env_run.xml variable should be communicated
to the components.

I may not be understanding all of the important implications of this.
From email discussions:
@mvertens  (2017-10-4) CIME/drv:
"there will need to be source mods or a more extensible implementation
to set read_restart = .false. in dart mode."
@mvertens 2017-10-4) POP: 
"(from DART's SourceMod)
    !*****hardcode read_restart so that dlnd does not look for rpointers
    !**** or restart files
If this is really needed,  we need to come up with a more extensible scheme to put it in."
@billsacks  (2017-10-6) CLM:
"it might be possible to do something a bit more nuanced than just disabling the balance checks entirely. For example, maybe it's only a problem for the first time step or two after restarting in a data assimilation context, in which case it might be best if we only bypass the balance checks for that first time step or two."
Tim Hoar (2017-10-6) CLM:
"I'd like CLM to recompute the snow layers, etc. Snow is a real nuisance when it comes 
to DA, it is easiest to modify total SWE - but the prognostic variables in CLM are the individual snow layers. Going from SWE to the layers changes with the versions of CLM,
so I'd like to not have to try to track those changes in the DART scheme.
Fei has moved on to the CICE model, but has similar desires for the ice classes 
(not a CLM problem, I know)."
Kevin; We decided in a meeting that this is a separate issue to be fixed later,
but it will be another example of CLM doing something differently based on 
DO_DATA_ASSIMILATION.

Thanks!
Kevin, for DART

**Comment by jedwards4b** [comment]
So to clarify:  you want the value of the xml flag DO_DATA_ASSIMILATION communicated to the component models at runtime?  I think that the way to do this would be to add a variable to the coupler namelist and then communicate the value of that variable to the component models through the infodata structure.

**Comment by kdraeder** [comment]
I believe that's what I want, but I'm open to other suggestions,
especially considering Mariana's comments that make me think
that this may be a specific case of a broader need.

**Comment by jedwards4b** [comment]
@gold2718 can you comment on this?  Is a new coupler namelist logical and a new field in infodata the best way to go about this?

**Comment by kdraeder** [comment]
A complication we'll need to consider is that we may run multiple
active components, but only do assimilation in some of them.
For example,  F compsets have active CAM and CLM, but we
may want to only assimilate into CAM.  So we would not want
to do anything DA related in CLM.  So a single DA logical variable
may not be enough.

**Comment by ekluzek** [comment]
Maybe the DO_DATA_ASSIMILATION, should list which components will have data assimilation run on them as a comma delimited list?

So values could be things like:

none
all
lnd,atm
atm
lnd,atm,ice,glc

So when a particular component queries the field, it would look for either the generic component name, or the word "all" to see if it should be turned on for it.

How about that?

**Comment by jedwards4b** [comment]
Or we could handle it like the pio options and have a separate variable for each component - we would still read them into the driver namelist and components would read from infodata.

**Comment by gold2718** [comment]
I still have not had time to fully wrap my mind around this but I do not understand why we are adding this variable. First, I think that if a component will be doing data assimilation (and needs to do something special like re-balance their state), they should have a namelist variable for this purpose.
Also, instead of adding a new variable to the driver, how about using the existing pause/resume infrastructure? It already allows you to specify which components get a resume signal. The only change needed is (I think) to get the resume signal to trigger at the beginning of the run.
For now, components could learn to do a 'startup resume' and learn a 'mid-run resume' later.
What am I missing?

**Comment by kdraeder** [comment]
Steve,
about your first point; the plan _is_ to have a namelist variable for each component,
but it also seems necessary to have an env_run.xml variable (maybe 1 for each
component) to tell the run script to execute the data assimilation script after the
forecast is done.
I can't say anything about the pause/resume option, except that I don't know
the current capabilities.
Kevin

**Comment by gold2718** [comment]
@kraeder,
When is the namelist variable set? For all runs? Only for runs after the filter runs?

**Comment by kdraeder** [comment]
@gold2718 The direct answer to your question is 'both'.  The atm DA 
namelist variable is true for every forecast, while the ocn variable may
be true for every forecast, or not, depending on what other components
are active and assimilating.  Having that flexibility is important for the
science we want to do.

The reason for that can be seen in another scenario I hadn't brought
into the discussion.  When we do DA in both the atm and ocn in a 
'weakly coupled' assimilation, both atm and ocn stop every 6 hours. 
DA is done every 6 hours in atm, but only at midnight (GMT) in ocn.  
The next forecast starts as a restart, except for CAM, which must start
as an initial run.   At hour 0 the ocn restart will not be b4b because
the model state has been changed by DART.  This requires using a
modified read_restart subroutine.  But at hours 6, 12, 18 the restart will 
be b4b and those mods shouldn't be used.  This choice is currently
controlled by an option in namelist variable init_ts_nml ('data_assim')
which is controlled by the hour of the date.

**Comment by gold2718** [comment]
@kdraeder, thanks for the explanation.
The most important phrase for me is:

> 
> This choice is currently
> controlled by an option in namelist variable init_ts_nml ('data_assim')
> which is controlled by the hour of the date.

Since the system currently works this way, what problem exists which requires a new driver variable to solve?

**Comment by jedwards4b** [comment]
After discussion @gold2718 and I came to the following proposal:
Use the presence of DATA_ASSIMILATION_SCRIPT and DATA_ASSIMILATION_CYCLES > 0 to determine if DA is engaged.
DATA_ASSIMILATION_XXX will be set by the DATA_ASSIMILATION_SCRIPT to signal component XXX to do a post-assimilation restart (including CPL).
PAUSE_COMPONENT_LIST is redundant - this is replaced by DATA_ASSIMILATION_XXX.

**Comment by kdraeder** [comment]
That sounds like it will work.
Just to confirm; DATA_ASSIMILATION_yyy are xml variables
and the DATA_ASSIMILATION_$components will be translated
into something the components can use to turn on/off DA-related
code.

**Comment by gold2718** [comment]
Let me try some examples to see if we are on the same page.
In the `DATA_ASSIMILATION_SCRIPT`, you would do:

`./xmlchange DATA_ASSIMILATION_ATM=TRUE`
to turn on post DA behavior in CAM.
`./xmlchange DATA_ASSIMILATION_OCN=FALSE`
to turn off post DA behavior in POP
`./xmlchange DATA_ASSIMILATION=FALSE`
to turn off all post DA behavior.

Inside the code (imagining POP), you would have something like:
`call seq_infodata_GetData(infodata, data_assimilation_ocn=do_post_da_step)`
which would set the variable, `do_post_da_step`, to `.true.` or `.false.` depending on the value of `DATA_ASSIMILATION_OCN`.

**Comment by kdraeder** [comment]
That looks like it would do what we need.

It also looks like it's working in the current CESM+DART architecture,
where the model stops to execute a DA script, and then restarts when
that script is done.   Is this proposal a reasonable intermediate step
towards the full pause-resume architecture, where the DA script is
replaced by a DA subroutine?

**Comment by gold2718** [comment]
Yes. With this implementation, models would have little work to do to accommodate working in the pause/resume manner. They would have to use the infodata variable to take post-filter action in their run loop, not just in their initialization routine.
