### ISSUE TITLE
Return default behavior of emailing user upon job completion/abort

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2004]
As @mnlevy1981 noticed: Sometime in the last few months - probably in #1719 from @erichlf - the default behavior for emails at the end of a job changed so that, by default, you no longer receive emails. I don't remember any discussion of this change, and I feel the default behavior should revert back to how it was a few months ago, which was to send emails upon either a successful or unsuccessful completion of the job.

In addition to reverting that behavior, I feel it's important that we avoid hidden behavior changes like this in the future: These sorts of changes should be accompanied by discussion on github, ideally in an issue or PR whose title makes it clear what's going on, so others can notice the topic and reply if they're interested. "Add Support for Email Options" (for example) does not make it clear that the default behavior is changing.

**Comment by mnlevy1981** [comment]
I want to add that I like the ability to change email settings from the command line, but as Bill said it would be nice if the default behavior was not changed as a result of this ability. Also, two issues with the implementation:

1. The default settings on cheyenne were "email at end of run or if the run aborts" but now users can not specify more than one action to trigger an email
1. Changing the email settings is a command line option for `case.submit` but there is no way to change it when the jobs are submitted via `create_test`

**Comment by jgfouca** [comment]
@billsacks I understand your concern. I'm curious as to what a reasonable default would be because I personally hate my inbox getting filled everytime the nightly test suites run. Maybe turn it off for create_test but leave it on for create_newcase?

**Comment by rljacob** [comment]
I also don't want an email with every run.   Can the defaults be set per-machine?  Or is this something can go in the .cime directory so a user can always get the behavior they want?

**Comment by billsacks** [comment]
Definitely leaving it on for create_newcase: I think that many CESM users have come to rely on this feature.

For create_test: I have email filters set up that direct passed jobs into one folder and failed jobs into another; that tends to work well for me (although I do need to set up a new filter for each new batch system, since the email formats are so different). That said, the best default for me would be to get emails on job failure from create_test, but not on successful job completion. But I agree with @mnlevy1981 that it would be really good to have create_test have an option that lets you specify this for the whole test suite (or @rljacob 's idea of having a user specify this in .cime).

My biggest concern about all of this, though, was that the default behavior changed without soliciting input from very many people. To that end: I don't want to speak for all of cseg on this matter. We can bring it up at our meeting next Monday.

**Comment by jedwards4b** [comment]
I like the idea of this default going into the users .cime directory I really don't want email for most of my work.

**Comment by mnlevy1981** [comment]
Something in the `.cime` directory (especially if it can differentiate between user-initiated `case.submit` and `create_test`) would be great for my needs, and the additional ability to override the `.cime` setting from the command line would be welcome as well.

**Comment by jgfouca** [comment]
OK, sounds like we are mostly in agreement (.cime + additional cmd-line options). I will try to get to this soon.

**Comment by mnlevy1981** [comment]
@jgfouca Thanks! I just want to reiterate a point from an earlier comment:

> The default settings on cheyenne were "email at end of run or if the run aborts" but now users can not specify more than one action to trigger an email

In addition to the proposed changes, the `--mail-type` option needs to be updated to accept multiple options

**Comment by jgfouca** [comment]
@mnlevy1981 , ok I can look at that too.

**Comment by billsacks** [comment]
We brought this up with CSEG today, and the general consensus was:

- create_newcase: you should get emails at the end of the job, whether it terminated successfully or failed

- create_test: just get emails for job failures (some people like receiving emails upon success, but they're okay needing to set an option to do that)

**Comment by rljacob** [comment]
I think we decided this should be something the user puts in .cime and the default would be no email.

**Comment by mvertens** [comment]
@jacob - CSEG developers really wanted to have defaults for emails.  I
think we should bring this up on Wednesday.

**Comment by billsacks** [comment]
@rljacob we would still like the option to configure this in .cime and/or via command-line arguments, but the CSEG discussion was based on what we feel most CESM users/developers would want as default, out-of-the-box behavior (so that they can get reasonable behavior without needing to configure anything).

**Comment by rljacob** [comment]
I still think this should be at most a machine-level default, not a CIME-wide default.  Then we can each put in our config_machines. entries.

**Comment by mnlevy1981** [comment]
Is there a `config_model.xml` file, so CESM could have one default and ACME could have another? It seems like all ACME machines would default to "no email" and all CESM machines would default to "failed tests and end of all non-test runs", so it's somewhat error-prone to put that information in on a machine-by-machine basis.

**Comment by jedwards4b** [comment]
No there is not a config_model.xml file.   I really don't think it matters what the default is as long as users have the option of configuring for themselves.

**Comment by mnlevy1981** [comment]
I disagree -- when someone new arrives (be it a scientist, postdoc, or student), they should be concerned with getting the model and running `create_newcase`, not with understanding the intricacies of the CESM notification system.

In addition to believing that most users prefer the email notifications, I think it makes more sense from another point of view as well: if the default is "no email" and the user is new to the machine, they probably won't think to ask "hey, is there a way to get notified when my job finishes?" On the other hand, if the email is actually cumbersome it would be natural to seek out an answer to "can this be disabled?"

**Comment by jedwards4b** [comment]
People with overflowing inboxes can turn it off as easily as those who want more email can turn it on, the default doesn't matter.

**Comment by rljacob** [comment]
CIME does a great deal to tell users what is going on through CaseStatus.  Reading emails from the queue system shouldn't even be necessary.   Any new users should be reading the user's guide which will spell out all these options.

**Comment by mvertens** [comment]
@mlevy - CIME is a collaborative project between two very large groups and
compromises need to be made to ensure that the collaboration goes forth
smoothly. Given that the default behavior that CSEG wants is not acceptable
to ACME and given that we have a way to have the users have the ability to
customize their settings I think we can proceed with the default setting
that @rjacob is proposing.

**Comment by jgfouca** [comment]
All, I'm trying to summarize this discussion so I can begin work. Here's my current understanding:

- We need to support multiple email conditions
- Implement a default email setting in config_components_$model.xml. For CESM it will be set to "ALWAYS" (or something like that), for ACME it will be "NEVER".
- Allow email behavior to be configured in .cime

**Comment by billsacks** [comment]
@jgfouca that sounds good to me, as long as your "ALWAYS" implies "always at the end of the run" (since I don't think people want to receive emails when a run starts - which I think is included in the current meaning of "always").

**Comment by mvertens** [comment]
@jgfouca - is this going to be difficult to implement?

**Comment by jgfouca** [comment]
@billsacks , yes ENDRUN would be better.

@mvertens , no I don't see why it would be too hard.

**Comment by billsacks** [comment]
> ENDRUN would be better.

Sounds good

**Comment by rljacob** [comment]
Since its batch email we're talking about, and every machine needs an entry in config_batch.xml, we should probably put the default settings there.  config_component_$model.xml is for driver configuration.

**Comment by jgfouca** [comment]
@rljacob , I don't think we want a different default for every machine, I think we want something consistent globally. config_component*.xml defines all our case entry-ids, not all of which have to be related to the driver.

**Comment by rljacob** [comment]
It may start out global but over time we may each find machines were we want something different.  The logical place is in config_batch.xml and better build in the finer control now.

**Comment by jgfouca** [comment]
Do we have broad agreement for putting this in config_batch.xml? @jedwards4b ?

**Comment by jedwards4b** [comment]
That sounds like the correct place.
