### ISSUE TITLE
Runoff mapping generates incorrect weights for scrip grid files with area in square degrees

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2018]
When running `runoff_map` (in `tools/mapping/gen_mapping_files/runoff_to_ocn`) with a file with `gridtype = 'scrip'`, which has area in square degrees: The tool generates incorrect weights because it assumes that areas are in square radians. The resulting weights are off by a factor of about 3300 ((180/pi)^2).

It turns out that this doesn't affect the values mapped by the coupler (at least not much), maybe because the area correction in the coupler takes care of this? But we should still fix this so that we have correct mapping weights on the runoff mapping files.

**Comment by mvertens** [comment]
@billsacks - so the current rof->ocn mapping files have this problem and
have had this since april?

**Comment by billsacks** [comment]
I have run `SMS_Ld3.f19_g17_gl4.J1850G.hobart_intel.allactive-defaultio` with this fix in place. This is bit-for-bit with and without this fix, other than roundoff-level changes in x2oacc_Foxx_rofi.
