### ISSUE TITLE
scripts_regression_tests.py does not take command line --machine arguments

### ISSUE THREAD

**Issue by jhkennedy** [ESMCI/cime#2019]
When trying to run the CIME regression tests on my linux desktop, using [this command](https://github.com/ESMCI/cime/wiki/Testing):

```bash
./scripts_regression_tests.py --machine linux-generic 2>&1 
```

I get this error: 

```bash
ERROR: Could not initialize machine object from $CIME/config/acme/machines/config_machines.xml or $HOME/.cime/config_machines.xml
```

*Note: This occurs in both ACME/cime and ESMCI/cime.* 

It looks like this error is caused by:

https://github.com/ESMCI/cime/blob/2d39e6128f60d11b55918b23592bdea6c2436c9d/scripts/tests/scripts_regression_tests.py#L34

where the `Machines()` class is initialized *upon import*, before the `_main_func()` is run, causing this `expect` to fail

https://github.com/ESMCI/cime/blob/2d39e6128f60d11b55918b23592bdea6c2436c9d/scripts/lib/CIME/XML/machines.py#L45-L51

and the regression tests to never reach the handling of the command line arguments in `_main_func()`: 

https://github.com/ESMCI/cime/blob/2d39e6128f60d11b55918b23592bdea6c2436c9d/scripts/tests/scripts_regression_tests.py#L2464-L2472

--- 

**Possible Fix**:

This could be fixed by *deleting* the initialization on import: 

https://github.com/ESMCI/cime/blob/2d39e6128f60d11b55918b23592bdea6c2436c9d/scripts/tests/scripts_regression_tests.py#L34

and changing the `--machine` option handling in `_main_func()` to: 

```python
    if "--machine" in sys.argv:
        midx = sys.argv.index("--machine")
        mach_name = sys.argv[midx + 1]
        MACHINE = Machines(machine=mach_name)
        os.environ["CIME_MACHINE"] = mach_name
        del sys.argv[midx + 1]
        del sys.argv[midx]
    else:
        MACHINE = Machines()
```

I don't see any place that `./scripts_regression_tests.py` is imported in CIME or ACME, so there is no need as far as I can tell to initialize `MACHINE` on import. 

---

*Note: it might be a good idea to change the options handling here to argparse as well.*

**Comment by jedwards4b** [comment]
Set CIME_MACHINE=yourmachinename  before running scripts_regression_tests.py 

There were problems with using argparse in scripts_regression_tests.py

**Comment by jhkennedy** [comment]
@jedwards4b That is also a fix, but still requires changes to CIME. That is, if that's the expected use, the machine option should be remove (it is non-functional right now) and the error message or documentation should also tell you to set the `CIME_MACHINE` environment variable. 

Interesting about argparse; do you remember what the problems were?

**Comment by jedwards4b** [comment]
I think that argparse was incompatible with the unittest argument handling mechanism.
I would encourage you to issue a PR with the changes you suggest.
