### ISSUE TITLE
xmlchange fails when setting JOB_QUEUE with --file and --subgroup options

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2046]
```
cori04% ./xmlchange --file env_batch.xml JOB_QUEUE="regular" --subgroup=case.run
setting case file to env_batch.xml
ERROR: No variable USER_REQUESTED_QUEUE found in case
```
I've tested this on Skybridge, and it only occurs when both --file and --subgroup are specified.

**Comment by jedwards4b** [comment]
USER_REQUESTED_QUEUE and USER_REQUESTED_WALLTIME are defined in env_run.xml 
and so using the --file env_batch.xml would give the above response as expected.

**Comment by jedwards4b** [comment]
Oh - on rereading this - why are you using the --file option?   @jgfouca this would seem to be a problem with locating these variables in env_run.xml but the usage of the --file flag is also unusual.

**Comment by rljacob** [comment]
Should the error message say: "ERROR: No variable USER_REQUESTED_QUEUE found in env_batch.xml"?

**Comment by jedwards4b** [comment]
Yes, we can probably improve that error message, however the issue in this case is that the user wasn't directly referring to the USER_REQUESTED variable.

**Comment by jedwards4b** [comment]
But this also points to another bug:  
```
:) ./xmlchange --subgroup case.st_archive JOB_QUEUE=fred
yslogin3: ~/sandboxes/cesm2_0_alpha/cime/scripts/foo
:) ./xmlquery JOB_QUEUE

Results in group case.run
	JOB_QUEUE: caldera

Results in group case.st_archive
	JOB_QUEUE: fred

Results in group case.test
	JOB_QUEUE: caldera
yslogin3: ~/sandboxes/cesm2_0_alpha/cime/scripts/foo
:) ./case.setup --reset
Successfully cleaned batch script case.run
/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/foo/env_mach_specific.xml already exists, delete to replace
Creating batch script case.run
Writing case.run script from input template /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/config/cesm/machines/template.case.run
Writing case.st_archive script from input template /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/config/cesm/machines/template.st_archive
WARNING: queue 'fred' is unknown to this system
Locking file env_mach_pes.xml
Creating user_nl_xxx files for components and cpl
If an old case build already exists, might want to run 'case.build --clean' before building
yslogin3: ~/sandboxes/cesm2_0_alpha/cime/scripts/foo
:) ./xmlquery JOB_QUEUE

Results in group case.run
	JOB_QUEUE: fred

Results in group case.st_archive
	JOB_QUEUE: fred

Results in group case.test
	JOB_QUEUE: caldera
```
Suggested solution:  the USER_REQUESTED variables need to be removed from env_run.xml and added to env_batch.xml in each of the job groups.

**Comment by rljacob** [comment]
Is "--file" a legacy argument?  Its never needed, right?

**Comment by jedwards4b** [comment]
It is a legacy argument and not needed in this case, but it's still useful for some other things.
I'm testing a fix for this and should have a PR soon.
