### ISSUE TITLE
bugs in scripts_regression_tests.py test_cime_case_prereq for lsf batch system

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2048]
config_batch.xml needs a field
+    <depend_separator>&amp;&amp;</depend_separator>

This would have been caught by config_batch.xsd but the schema is defined such that this is not a required field - it seems that scripts_regression_tests.py thinks it should be.

After fixing this I found that line 1463 of scripts_regression_tests.py
```
          dep_str = dep_str_fmt[:-len(jobid_ident)]
```
assumes that the dep_str format ends with the jobid, which is not the case for lsf systems, so dep_str gets set to ```-w 'done(jo``` which is incorrect.

**Comment by jgfouca** [comment]
Needed to support summit
