### ISSUE TITLE
Failures in K_TestCimeCase for CESM

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2057]
Running scripts_regression_tests from the head of master (da29a73) I get failures in these three tests in `K_TestCimeCase` (running on yellowstone, with cime_model = cesm):

(1)

```
test_cime_case_prereq (__main__.K_TestCimeCase) ... job case.run depends on ['prereq_test']
Submit job case.run
dependencies: ['prereq_test']
job case.st_archive depends on ['prereq_test', '0']
Submit job case.st_archive
dependencies: ['prereq_test', '0']
ERROR
```

(2) `test_cime_case_test_walltime_mgmt_6 (__main__.K_TestCimeCase) ... FAIL`

(3) `test_cime_case_test_walltime_mgmt_7 (__main__.K_TestCimeCase) ... FAIL`

I notice that the other `test_cime_case_test_walltime_mgmt` tests are skipped for CESM; should these be skipped, too?

**Comment by jedwards4b** [comment]
These fail on yellowstone (only) due to the way that the lsf system handles time with hh:mm instead of hh:mm:ss - I've known about this for a while, but since it was only this machine I have ignored it.

**Comment by billsacks** [comment]
Okay, if it's just yellowstone I'm okay closing this as wontfix.

**Comment by billsacks** [comment]
@jedwards4b is this one also yellowstone-specific? It doesn't look to have anything to do with time formats:

```
======================================================================
ERROR: test_cime_case_prereq (__main__.K_TestCimeCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1472, in test_cime_case_prereq
    self.assertTrue(prereq_name in prereq_substr, "Dependencies added, but not the user specified one")
UnboundLocalError: local variable 'prereq_substr' referenced before assignment
```

**Comment by jedwards4b** [comment]
Yes see #2048
