### ISSUE TITLE
Allow getTiming summary from failed run

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2061]
From Pat Worley.  "When a job ends, case_run.py calls get_timing(case, lid) to generate the performance summary based on the case particulars and on the global timing statistics files generated at the end of a run.

When a job fails (e.g., runs of out of time), this summary is not generated. However, in the timing/checkpoints subdirectory are typically global statistics files generated as the simulation was running. These can also be used to generate a performance summary up to this point in time.

In CIME2 and earlier I could put one of these checkpoint global timing statistics files in the "right place" and run the getTiming script and generate a performance summary. Kind of a kludge, but it worked.

With CIME5, I don't know how to do this any longer. Perhaps this is simple, but even better would be a tool that was designed just for this, run from the case directory with a pointer to one of these global timing statistics files as an argument."

**Comment by jedwards4b** [comment]
cime/scripts/Tools/getTiming --help
usage: 
getTiming  [-lid|--lid] [-h|--help]

Get timing information from run

optional arguments:
  -h, --help           show this help message and exit
  -d, --debug          Print debug information (very verbose) to file /glade2/
                       scratch2/jedwards/cesmtests/b.e20.B1850.f09_g17.pi_cont
                       rol.all.beta07_debug/getTiming.log (default: False)
  -v, --verbose        Add additional context (time and file) to log messages
                       (default: False)
  -s, --silent         Print only warnings and error messages (default: False)
  -lid LID, --lid LID  print using yymmdd-hhmmss format (default:
                       999999-999999)
  --caseroot CASEROOT  Case directory to get timing for (default: /glade2/scra
                       tch2/jedwards/cesmtests/b.e20.B1850.f09_g17.pi_control.
                       all.beta07_debug)

**Comment by rljacob** [comment]
So the --caseroot argument should do it?

**Comment by jedwards4b** [comment]
you need --lid as well

**Comment by jedwards4b** [comment]
Actually you only need --lid to name the output file, --caseroot should be fine.

**Comment by worleyph** [comment]
Sorry about this. Did not even notice that Tools/getTiming existed in CIME5, and the request (from April 2017) was based on looking at how getTiming was invoked in case_run.py. Noel Keen found it for us at our end right after Rob created this issue.

If anyone is looking for something further to do ( :-) ), it would be nice if there were options to read the stats file from a different location and with a different name and to redirect the output to some other location. The use case would be when running this for some other user's job, feeding it a file from $RUNDIR/timing/checkpoints and saving the output locally, so not writing into the user's case directory.

What exists now is what I was looking for, so thanks again.
