### ISSUE TITLE
cesm clm build broken

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2075]
recent merge of Makefiles broke cesm's clm build.

**Comment by billsacks** [comment]
@jedwards4b thanks for finding and fixing this! Do you know what cime versions this affects, so that we ( @ekluzek @bandre-ucar and I) can avoid using these in a CLM tag?

**Comment by jedwards4b** [comment]
None - it was broken in PR 2072 about 2 hours ago.

**Comment by billsacks** [comment]
Excellent, thanks for the fast catch :-)
