### ISSUE TITLE
case.submit --job case.st_archive errors if you don't have a built case

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#208]
Testing the case.st_archive job submission with case.submit and working with pre-existing run directory files generated from a  DART test run returns the following error:

./case.submit --job case.st_archive
Submitting job 'case.st_archive', resubmit=False
Checking file env_case
Checking file env_mach_pes
Running ... [component buildnml] 
ERROR: Build complete is not True please rebuild the model by calling case.build

**Comment by jedwards4b** [comment]
Case.submit should be able to ignore build status for certain cases.
