### ISSUE TITLE
Problems setting up unit testing framework

### ISSUE THREAD

**Issue by brhillman** [ESMCI/cime#2080]
Not sure if this is the right place to put this, but I am having trouble setting up the unit testing framework, following the instructions [here](http://esmci.github.io/cime/users_guide/unit_testing.html). I have installed pFUnit on a cluster that we have CIME otherwise configured for, adding the configuration to `config_compilers.xml`, and followed the instructions for running the existing unit tests, running
```
scripts/fortran_unit_testing/run_tests.py --build-dir `mktemp -d ./unit_tests.XXXXXXXX`
```
from the top-level CIME directory. This seems to fail somewhere short of actually running unit tests for me. The first errors that seem to show up are in reference to undefined references to operators in shr_vmath_mod.F90, e.g.,
```
CMakeFiles/vmath_test_exe.dir/__/__/__/util/shr_vmath_mod.F90.o: In function `shr_vmath_mod_mp_shr_vmath_sqrt_':
shr_vmath_mod.F90:(.text+0x3e): undefined reference to `vdsqrt_'
```
There's a handful of these errors, and then a lot more warnings...finally the script exits, with the following error:
```
ERROR: Command: 'make -j 8' failed with error 'None' from dir '/home/bhillma/codes/e3sm/branches/brhillman/cime/add-unit-tests-sems/cime/unit_tests.0DQu7Goq/__command_line_test__/__command_line_test__'
```
I don't know if any of this is helpful, but does anybody have any ideas as to what is going on here? I would really like to get this working so that I can use the framework to write unit tests for new development that I am doing.

**Comment by jedwards4b** [comment]
What compiler and compiler version are you using?   Can you successfully build a simple case on this machine?

**Comment by brhillman** [comment]
I am building on skybridge with the Intel compiler, my `.env_mach_specific.sh` is as follows:
```
module purge 
module load sems-env
module load sems-git
module load sems-python/2.7.9
module load sems-cmake
module load gnu/4.9.2
module load sems-intel/16.0.2
module load mkl/16.0
module load sems-netcdf/4.4.1/exo
export NETCDFROOT=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/16.0.2/exo
export NETCDF_INCLUDES=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/16.0.2/exo/include
export NETCDF_LIBS=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/16.0.2/exo/lib
export OMP_STACKSIZE=64M
export COMPILER=intel
export MPILIB=mpi-serial
export DEBUG=FALSE
export OS=LINUX
```
I can build and run ACME/E3SM without issues.

**Comment by jedwards4b** [comment]
Send the entire output of scripts/fortran_unit_testing/run_tests.py --build-dir `mktemp -d ./unit_tests.XXXXXXXX`
maybe we'll spot something there.

**Comment by brhillman** [comment]
[run_tests_output.txt](https://github.com/ESMCI/cime/files/1480679/run_tests_output.txt)

**Comment by brhillman** [comment]
@mfdeakin-sandia it didn't seem to like that...I get the following error:
```
checking for strings.h... ld: cannot find -lvml
```
See attached: 
[run_tests_output_2.txt](https://github.com/ESMCI/cime/files/1481191/run_tests_output_2.txt)

**Comment by mfdeakin-sandia** [comment]
I looked at Skybridge's libraries, can you try changing it to `mkl_vml_avx` instead?

**Comment by brhillman** [comment]
@mfdeakin-sandia yes but not for a week...I'm on my way out of town at the moment and will have to revisit when I get back.

**Comment by mfdeakin-sandia** [comment]
Alright, I'll look into it

**Comment by billsacks** [comment]
I'd be surprised if adding a link line like this in the CMakeLists.txt is the right solution. The CMake build is supposed to pick up the link libraries specified in config_compilers.xml. For skybridge, I see:

```xml
  <ADD_SLIBS> $(shell $(NETCDF_PATH)/bin/nf-config --flibs) -L/projects/ccsm/BLAS-intel -lblas_LINUX</ADD_SLIBS>
  <PIO_FILESYSTEM_HINTS>lustre </PIO_FILESYSTEM_HINTS>
  <ADD_SLIBS MPILIB="openmpi"> -mkl=cluster </ADD_SLIBS>
  <ADD_SLIBS MPILIB="mpi-serial"> -mkl </ADD_SLIBS>
```

My first question is whether those SLIBS are being correctly added to the cmake build. 

You can run run_tests.py with the -v argument to get the full build commands for each target. It would be helpful to compare the output from this with the output from a system build on this machine/compiler to determine what's missing from the build lines of the unit test builds.

**Comment by mfdeakin-sandia** [comment]
I agree it's not the correct solution, I just want to understand what needs to happen for this to work at this point

**Comment by billsacks** [comment]
@mfdeakin ah, got it - thanks for the clarification.

**Comment by mfdeakin-sandia** [comment]
The issue is two-fold: it needs to link to mkl_rt, and the MKL library path isn't specified
@jgfouca Is it okay to just add these to the SLIBS variable for Skybridge, or should it only be for a subset of the things we build? Also, is the mkl library compiler specific?

**Comment by billsacks** [comment]
MKL is intel's math kernel library (which includes lapack and blas functionality), so yes, it's compiler-specific.

**Comment by jgfouca** [comment]
@mfdeakin-sandia , I think it would be OK to just add them.
