### ISSUE TITLE
create_test does not take suite name(s) as position argument

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2094]
`./create_test --help` says (among other things):
```
positional arguments:
  testargs              Tests or test suites to run. Testname form is
                        TEST.GRID.COMPSET[.MACHINE_COMPILER] (default: None)
```
However, attempts to use one or more test suite names (e.g., `prealpha`) results in the error:
```
ERROR: Could not fill-out test name, partial string 'prealpha' had no grid information and you did not provide any
```
Either the documentation is incorrect or the code is not correct. It would be really convenient to be able to specify multiple test suites in one `create_test` call so all output is collected in one place.

**Comment by jedwards4b** [comment]
That is an interesting interpretation of the help text.   Test suite names can only be used with the 
--xml-category option.    I think that it only accepts one at a time however if you use some --xml-* options  but not others it will do all - that is 
./create_test --xml-machine yellowstone --xml-compiler gnu will run all categories defined for machine yellowstone and compiler gnu.

**Comment by gold2718** [comment]
Where does it say "Test suite names can only be used with the --xml-category option."?

Are you saying the phrase "or test suites" under positional arguments is incorrect?

Is there a way to (for instance) run two suites for a single machine_compiler combination with a single create_test call?

**Comment by jedwards4b** [comment]
I don't think so.

**Comment by billsacks** [comment]
I have also been confused by this help text. So it sounds like the answer to this

> Are you saying the phrase "or test suites" under positional arguments is incorrect?

is "yes"?

**Comment by jgfouca** [comment]
@gold2718 , positional testargs are for ACME.

**Comment by gold2718** [comment]
@jgfouca,
I am aware that ACME has a different interface to create_test which is why I marked this as CESM-only. The issue here is that either the CESM-specific documentation is wrong or the CESM implementation is wrong and I think we should get those aligned.

Of course, in this case, we could just adopt the ACME interface to create_test and solve a lot of problems (IMHO).

**Comment by jgfouca** [comment]
Fix the description help-dump for create_test.
