### ISSUE TITLE
Contributing to CIME

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2096]
With the release of cesm and e3sm coming soon we may expect to get many new contributors to CIME.   The Unidata metpy github page has a very nice document on how to contribute to that project https://github.com/Unidata/MetPy/blob/master/CONTRIBUTING.md  we may want to consider something similar.  In particular the Contributor License Agreement (CLA) is interesting and has already been vetted by NCAR/UCAR legal.

**Comment by rljacob** [comment]
I recently found that github has an open-source standards checklist: https://github.com/ESMCI/cime/community
So yes lets add CONTRIBUTING and also "code of conduct".

**Comment by rljacob** [comment]
github has 2 CODE_OF_CONDUCT templates derived from:
https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
and http://citizencodeofconduct.org/

They don't have CONTRIBUTING templates but do point to some examples:
Atom:  https://github.com/atom/atom/blob/master/CONTRIBUTING.md
Ruby on Rails:  https://github.com/rails/rails/blob/master/CONTRIBUTING.md
OpenGovernment: https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

**Comment by jedwards4b** [comment]
I thought that the one I pointed you to was pretty good - do you see a problem with it?

**Comment by rljacob** [comment]
No. I was just noting the ones Github pointed to.
