### ISSUE TITLE
Incorrect warning being generated regarding cheyenne economy queue?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2098]
I’m building a [CESM] job on cheyenne that should run in the `economy` queue, and I noticed this warning flash by:

```
WARNING: queue 'economy' is unknown to this system
```
However, other jobs are actually running in the `economy` queue, so I assume this warning is coming from CIME based on a missing valid value in a CIME configuration file rather than the machine itself?

**Comment by jgfouca** [comment]
That's correct. It needs to be added to the config_batch.xml entry for cheyenne.
