### ISSUE TITLE
Investigate CIME build system

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2099]
Cmake conversion efforts have been slowed due to poor understanding of the CIME build system on the ACME side. We need to understand the CIME build infrastructure better and document the control flow.

**Comment by jedwards4b** [comment]
How can I help?   Should we set up a meeting?

**Comment by jgfouca** [comment]
I'll start off solo and ask you if I have questions.

**Comment by jedwards4b** [comment]
Some thoughts on the cmake build:
1. The cmake build of cime should not know anything about external components.  Those components should continue to be built via buildlib and cime should expect a lib$comp.a regardless of how the component library is built.   This will allow cime to adopt cmake independent of external components and allow for external components to determine their own build method.  It will also allow an incremental update of the build system.
2. We need to figure out how to include SourceMods in the build

**Comment by billsacks** [comment]
> We need to figure out how to include SourceMods in the build

For what it's worth, CISM does this in its cmake-based build:

https://github.com/ESCOMP/cism/blob/34642dfaad8687925b9ac35d7a11e658d367745f/CMakeLists.txt#L370-L396

I believe @agsalin originally wrote this, maybe 5 years ago. It could probably be done more elegantly, but this at least could be a starting point that gets the job done.

**Comment by jgfouca** [comment]
This was completed long ago.
