### ISSUE TITLE
Organization of python code within merged CIME

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#21]
Suggestion:
create cime/utils/python and move the *.py files from scripts-acme to there.
rename scripts-acme to scripts-python for further development.

**Comment by mvertens** [comment]
I agree with this proposed approach.

**Comment by jgfouca** [comment]
Git doesn't track directories, so there won't be a scripts-python until there's something to put in there.

**Comment by rljacob** [comment]
No don't do that because users aren't supposed to look in utils.   Leave the python executables that user's are supposed to run in scripts-python.

**Comment by jgfouca** [comment]
Oh, I see what you mean now. Fixing it.
