### ISSUE TITLE
arg organization

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2104]
cime command with a great number of arguments/options (create_test, create_newcase) could probably benefit from the use of argument groups.

**Comment by billsacks** [comment]
Can you explain this? Is this referring to the user interface, the internals or both?

**Comment by jgfouca** [comment]
User interface.

**Comment by billsacks** [comment]
Okay. Can you please describe what you're thinking in more detail, then, so that it can receive broader input, particularly as it affects the user interface to create_newcase?

**Comment by jgfouca** [comment]
@billsacks , I was thinking of using argparse argument groups (https://docs.python.org/2/library/argparse.html#argument-groups) for organizing related options.

**Comment by billsacks** [comment]
@jgfouca That sounds like a good idea.

**Comment by jgfouca** [comment]
Another thing that would be nice is to use **vars in order to reduce some of the tedious duplicated of long arg lists.
