### ISSUE TITLE
Consider upgrading status of the job ID

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2108]
When submitted jobs to a batch system, the job ID is a critical integer and could be made more available.  One place it seems it could easily be added is in the CaseStatus.

```
2017-11-29 14:01:27: case.submit starting 
 ---------------------------------------------------
2017-11-29 14:02:15: case.submit success  JOB ID is 42
 ---------------------------------------------------
2017-11-29 15:37:35: model execution success 
```

Jim F. suggested a query that doesn't do what I would expect: 
```
cori08% pwd
/global/cscratch1/sd/ndk/ACME_simulations/2017-master-nov28.hmod526t03.mnov28.st04.atune.long.ne120np4_oRRS18to6v3_ICG.cori-knl/case_scripts
cori08% xmlquery JOB_IDS
        JOB_IDS: case.run:8787607
cori08% 
```

The job ID returned is the ID for the job that is currently submitted, but I'd like to know the job ID of the previous job that just failed (for example).

I might even argue to put the job ID with the date/time stamp for the log files.  `cpl.log.171129-022802` could be `cpl.log.171129-022802.8787607`.

Also, after the job is complete, the slurm system (at least) has a nice way of getting some info from the job:
```
cori08% sacct -j 8700613 -X --format=JobID,JobName,NNodes,Elapsed,Account,QOS,State
       JobID    JobName   NNodes    Elapsed    Account        QOS      State 
------------ ---------- -------- ---------- ---------- ---------- ---------- 
8700613      hmod600t0+      600   01:23:35       acme normal_kn+     FAILED 

or:

cori08% sacct -j 8700613 -a -o JobID%-20,JobName,State,ExitCode,DerivedExitCode,Elapsed,NNodes,NTasks,MaxRSS
               JobID    JobName      State ExitCode DerivedExitCode    Elapsed   NNodes   NTasks     MaxRSS 
-------------------- ---------- ---------- -------- --------------- ---------- -------- -------- ---------- 
8700613              hmod600t0+     FAILED      1:0             0:0   01:23:35      600                     
8700613.batch             batch     FAILED      1:0                   01:23:35        1        1     43568K 
8700613.extern           extern  COMPLETED      0:0                   01:25:03      600      600          0 
8700613.0              acme.exe CANCELLED+      0:9                   00:25:13      600    38400    548784K 

```

This will tell you exactly how much time the entire job used and if it failed.  The memory reported in the second command is only moderately useful, but can point to a job that used too much memory.

**Comment by jgfouca** [comment]
@jedwards4b any thoughts on this? At first glance, adding tis info to CaseStatus seemed the easiest approach.

**Comment by jedwards4b** [comment]
Sending it to CaseStatus seems entirely appropriate.   We can make the addition of jobid to the log files an option too.   Probably we should have a string format option for the log file names.

**Comment by jgfouca** [comment]
OK, I am going to consider the discussion over and convert this to action ticket.

**Comment by ndkeen** [comment]
I see the jobid is now in the log file names which I think is nice and will always be one place to easily find the job id.  I still think there are other places we could stash the jobid.

However, I do see that the tests are NOT also placing the jobid in the log file names.  Was that the intention?

**Comment by jgfouca** [comment]
@jedwards4b , I think you did the work on the log file names. Can you answer @ndkeen 's question?

**Comment by jedwards4b** [comment]
@ndkeen I'm not sure what you are referring to - my tests have jobid in the log file names.   Is it possible you are running the tests without queueing in which case there is no jobid?

**Comment by ndkeen** [comment]
I now see jobid's in the log files even for "tests" (ie using create_test).  I'm not sure if something changed or if I'm using newer code, but looks good now.  I don't even know how to run without using batch system.

**Comment by jgfouca** [comment]
@ndkeen good to hear.

```
./case.submit --no-batch
```

^ How to run without batch system.
