### ISSUE TITLE
cime_bisect needs to support general shell scripts

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2112]
It currently only supports create test commands.

Filed on behalf of @ndkeen

**Comment by rljacob** [comment]
What does this mean?

**Comment by rljacob** [comment]
So it issues a bunch of "create_test" commands and the alternative would be...?

**Comment by jgfouca** [comment]
Any arbitrary shell script.

**Comment by ndkeen** [comment]
As an example...
I refer to a "launch script" as something that builds/modifies/submits a case (eg a run_acme script or your own. -- I use both).  I am usually changing PE layouts and other things that make create_test not really work.  If a user made their script capable of accepting a git hash as input, then I could imagine a bisect tool being able to work in the same way as it does now, right?  Simplest (for me) would be to simply give a script that has a string like GIT_HASH_BISECT_ME that the bisect tool could replace/run.  Would also need to provide a script that could determine if the result of interest is found (PASS/FAIL).  Now for this to be immediately useful to me, each of these launches would be jobs submitted to Q.  Or... I suppose I could submit a single long job that could work on a create_newcase one-by-one.

**Comment by jedwards4b** [comment]
Perhaps you should explain your use cases better and determine if there is an existing solution.   For example the PFS test nicely allows for multiple runs with different pelayouts and records the layout and performance for each case.

**Comment by rljacob** [comment]
I'm still trying to understand what it means to bisect a code with an arbitrary shell command.

**Comment by ndkeen** [comment]
I thought I did explain it above?

**Comment by jgfouca** [comment]
@rljacob , that's how native git bisect works. I had to write cime_bisect in order to skip all the non-merge commits (hit first parents only) and I designed it to always use create_test. There's no reason it couldn't run any shell command.

**Comment by jgfouca** [comment]
@ndkeen is right, there's no reason to force the user to use create_test since there are other ways to run E3SM/CESM.

**Comment by jedwards4b** [comment]
I'm not trying to force anything, but if a solution already exists maybe we don't need another one.

**Comment by jgfouca** [comment]
@jedwards4b , the default will still be to go through create_test since that's the most convenient way to run and has batch-system waiting built-in. If @ndkeen wanted to create a small bash script that did create_newcase and some xmlchanges, I don't see why we couldn't support that too.

**Comment by rljacob** [comment]
Ok I get it now.

**Comment by jedwards4b** [comment]
I think I disagree - if every user/developer wants to develop their own methods and scripts for testing then we reduce the ability to communicate with one another about what tests were done and what the results are.

**Comment by jgfouca** [comment]
@jedwards4b , yes, I expect the requested feature will be for bisecting 1-off things. We should allow if, but recommend create_test.

**Comment by jgfouca** [comment]
That said, I can't think of much that couldn't be tested with proper use of test-options and/or test-mods.

**Comment by mfdeakin-sandia** [comment]
Is the use of test mods and test options documented somewhere? http://esmci.github.io/cime/users_guide/testing.html?highlight=test%20mods doesn't really say anything about how to use test mods, and doesn't mention test options at all as far as I can tell

**Comment by rljacob** [comment]
Its not an deserves its own issue.  https://github.com/ESMCI/cime/issues/2115

**Comment by jgfouca** [comment]
@ndkeen , going to close this ticket on the assumption that your needs for cime_bisect can be met via testmods. If that's not the case, please reopen.
