### ISSUE TITLE
config_grids.xml has multiple grid entries with the same lname

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#212]
There are several entries in cime_config/acme/config_grids.xml that appear to be different entries for the same grid lname. Is there a reason for this or is it an error? 

When I automatically convert the ACME grids to the new format, should I remove these?

For example, in ESMCI

 <grid compset="DOCN.*_CISM">
      <sname>1.9x2.5_1.9x2.5_gl5</sname>
      <alias>f19_f19_gl5</alias>
      <lname>a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%gland5UM_w%null</lname>
    </grid> 

    <grid compset="(DOCN|XOCN|SOCN|AQUAP).+CISM1">
      <sname>1.9x2.5_1.9x2.5</sname>
      <alias>f19_f19</alias>
      <lname>a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%gland5UM_w%null</lname>
    </grid>

The corresponding ACME node is:
<GRID sname="1.9x2.5_1.9x2.5"   alias="f19_f19"  compset="DOCN.*_CISM">a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%gland5UM_w%null</GRID>

**Comment by rljacob** [comment]
Might be a paste error but I can't tell what the problem is.

**Comment by sarich** [comment]
Sorry about the formatting.
The CIME4 file /working/cime4/cime_config/acme/config_grids.xml has two different entries with the
same lname tag. Is this ok? Do we want to keep both? (there are several examples of this)

```
<grid compset="DOCN.*_CISM">
  <sname>1.9x2.5_1.9x2.5_gl5</sname>
  <alias>f19_f19_gl5</alias>
  <lname>a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%gland5UM_w%null</lname>
</grid> <!-- back compat -->
```


```
<grid compset="(DOCN|XOCN|SOCN|AQUAP).+CISM1">
  <sname>1.9x2.5_1.9x2.5</sname>
  <alias>f19_f19</alias>
  <lname>a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%gland5UM_w%null</lname>
</grid>
```

**Comment by rljacob** [comment]
Discussion from call:  It is ok.  This lets two different aliases reach the same longname.  If a full longname is specified on create_newcase then config_grids isn't checked.
