### ISSUE TITLE
Allow default mpilib to differ based on compiler

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2128]
On cheyenne, we need to use a different mpilib for gnu than for intel (openmpi for gnu, mpt for intel). However, as far as I can tell, there's no way to get the correct behavior out of the box: For gnu, you need to specify the mpilib at create_newcase or create_test time with `--mpilib openmpi`. It would be great if there were a way to specify default mpilibs and/or available mpilibs on a per-compiler basis. For example, I'd like to be able to do this for cheyenne:

```xml
    <MPILIBS compiler="intel">mpt,openmpi</MPILIBS>
    <MPILIBS compiler="gnu">openmpi</MPILIBS>
```

But currently I can't: besides violating the xml schema, it also appears that queries for the mpilib don't pass in the compiler attribute (if I'm understanding the error message correctly).

**Comment by billsacks** [comment]
As an aside: I don't like that you can specify `--mpilib` in `create_test`: It took me a while to figure out why my tests were failing despite similar tests passing that @fischer-ncar had run: Eventually @jedwards4b pointed out that @fischer-ncar must be running the cheyenne gnu tests with `--mpilib openmpi`, but this doesn't show up anywhere in the test name. I feel that we should either remove the `--mpilib` option to `create_test`, or have it modify all test names to add something like `_Mopenmpi`.

**Comment by jgfouca** [comment]
@billsacks , I agree. The flags for create_test should either not directly influence the test behavior or should automatically update the test name.

**Comment by billsacks** [comment]
@mvertens @jedwards4b I'm adding this to the cesm2 milestone because it seems it could trip up users trying to create a gnu case on cheyenne; feel free to remove it from the milestone if you disagree with its priority.

**Comment by ekluzek** [comment]
The clm testlist isn't working anymore because of this issue. The following tests aren't working:

ERS_D_Ld6.f10_f10_musgs.I1850Clm45BgcCrop.cheyenne_gnu.clm-clm50CMIP6frc		
ERS_Ld5.f10_f10_musgs.I2000Clm50BgcCruGs.cheyenne_gnu.mosart-default		
SMS_D_Ld5.f10_f10_musgs.I2000Clm50BgcCruGs.cheyenne_gnu.mosart-default

**Comment by billsacks** [comment]
@ekluzek the workaround is to specify `--mpilib openmpi` in your `create_test` command.

**Comment by jedwards4b** [comment]
It's not because of this issue that the test isn't working anymore, since this issue is requesting a feature that never existed and the test used to work.

**Comment by ekluzek** [comment]
I get the workaround for setting mpilib in create_test. So that's probably OK, as I can run my tests that way.

The question I have is that I've never had to explicitly set mpilib on the command line for create_test before. But, the gnu tests worked in the past. So did gnu work with mpt in the past, and now requires openmpi? Or what changed so that I have to be explicit about mpilib on the create_test command line?

**Comment by fischer-ncar** [comment]
gnu never worked well with mpt on cheyenne.  openmpi was suppose to be a temporary work around until mpt was fixed.  It's looking like a fix for mpt isn't going to be coming.

**Comment by ekluzek** [comment]
OK, that makes sense. I realize changes for the content of this issue "allowing different defaults for different compilers" might be involved. What I'm wondering is if we can add a simpler change that will just abort, if you use a machine/compiler/mpilib combination that's known not to work. Could that be done? Should I open that as a separate issue?

**Comment by jedwards4b** [comment]
How are you to make that determination and how would someone override it?

**Comment by ekluzek** [comment]
You could add it to the XML in config_machines.xml as something like...

  <machine MACH="cheyenne">
    <DESC>NCAR SGI platform, os is Linux, 36 pes/node, batch system is PBS</DESC>
    <NODENAME_REGEX>.*.cheyenne.ucar.edu</NODENAME_REGEX>
    <OS>LINUX</OS>
    <COMPILERS>intel,gnu</COMPILERS>
    <MPILIBS>mpt,openmpi</MPILIBS>
    <INVALID_COMPILER_MPILIB_COMBINATIONS>gnu_mpt</INVALID_COMPILER_MPILIB_COMBINATIONS>

It would be an optional field that isn't required, but if it's given the compiler/mpi combination is checked  to see if it's in the list and if it is -- the build aborts. I suppose you could then have a command line option to override it, or another option in the XML. Or honestly, for an individual case, the user could just remove the contents of "INVALID_COMPILER_MPILIB_COMBINATIONS" as if there's nothing in there, there would be no restrictions. I think the last one is the best option.

Should I create a separate issue for doing that?

**Comment by jedwards4b** [comment]
well you could but I think that it's a really bad idea.   I should have the ability to choose the preferred compiler/mpilib combination working soon.

**Comment by fischer-ncar** [comment]
I don't think we should abort based on a bad machine/compiler/mpilib combination.  You'll also need to add compsets, because some compsets ran fine with cheyenne/gnu/mpt.  Then there's stealth system updates.  One combination might work one day, then be broken the next.  I just think it would be impossible to keep up with all of the system changes.

**Comment by ekluzek** [comment]
@jedwards4b yes, I think the preferred compiler/mpilib combination is the most important thing. But, it could still be nice to have a way of knowing, "by the way this combination is known to not work out of the box". 

@fischer-ncar yeah the point wouldn't be to constantly be kept up to date with system changes -- the purpose would be for situations like this where mpt has been known to not work well with gnu on cheyenne for months. I think it's also a good clue for releases, where we know a given combination doesn't work (and we've been trying to get it to work for a very long time) and want to convey that somehow to users. As an optional field it isn't one you'd have to keep up to date for all machines.

I think I'll open an issue for discussion, and if I'm shot down that's fine. The two of you can immediately give it a thumbs down.  There might also be someone that has a different idea on a way to convey to users "this combination doesn't work out of the box".
