### ISSUE TITLE
Abort if user tries to do CONTINUE_RUN in the first iteration of a case

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#213]
This isn't critical, but it has bitten two people in the last month, so at today's CSEG meeting we decided we should open an issue on it: Two people recently have tried to set up branch runs with the same case as the run they're branching from, and then set CONTINUE_RUN to TRUE in the first iteration of the branch run (thinking that that was what they were supposed to do, or at least that it was allowed). The scripts allowed this to happen, and then the model aborted in CISM, whose time manager gets confused by this case. (Apparently other components handle this more correctly.)

The conclusion from the CSEG meeting is that this case shouldn't be allowed: you should never set CONTINUE_RUN to TRUE in the first iteration of a run, whether it's a branch run or something else. Ideally, the scripts would catch this.

A simple solution would be to have a counter of the number of times a case has completed, and fail with an error message if you try to set CONTINUE_RUN before the case has successfully completed. Others pointed out that there are a number of cases where this wouldn't work, but in most / all of these cases, the problem would just be that the error message wouldn't be triggered (i.e., you wouldn't typically get false error messages).

**Comment by billsacks** [comment]
This still seems to be an issue in the latest cime.

**Comment by jedwards4b** [comment]
Wouldn't a better solution be to have a prerun check of the contents of the run directory - there are certain rpointer files that we are expecting for a CONTINUE_RUN case that won't be in a branch or startup case.

**Comment by billsacks** [comment]
@jedwards4b - that wouldn't have helped in the two cases that the original issue was referring to: In those cases, users copied the contents of a restart directory (from the archive space) into their run directory, so the rpointer files were there as well.

**Comment by jedwards4b** [comment]
Then it would need to be a run time error, I think that the solution you propose is ripe for unintended side effects.

**Comment by billsacks** [comment]
A runtime error would be acceptable.

**Comment by jedwards4b** [comment]
But that's what you get now...  as I understand it all of the expected rpointer and restart files that are required for a CONTINUE_RUN are there - so how are we going to detect this problem?

**Comment by billsacks** [comment]
You get a very cryptic runtime error right now. The consensus in the CSEG meeting last June was that we should provide a clearer error message in this case.

> so how are we going to detect this problem?

My suggestion is above. What are some of the unintended side effects you see with this? Recall that we had some discussion on this point at the CSEG meeting that I reference in this issue. We could come up with some (unusual) cases where this solution would fail to produce an error message, but nobody came up with a solution where this produced an error message when it shouldn't.
