### ISSUE TITLE
Illegal memory access in driver initialization

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2131]
With the address sanitizer and the following case, acme.exe crashes in the MCT driver initialization
`create_newcase --case f_sanitize_test --compset F1850C5AV1C-04P2 --res ne4_ne4 --pecount S --compiler gnu --mach anvil`

I'm not certain this issue isn't in the MPI library yet, so this may not be a CIME issue

Complete log: 
[acme.F1850C5AV1C-04P2.ne4_ne4.log.171211-120502.txt](https://github.com/ESMCI/cime/files/1548925/acme.F1850C5AV1C-04P2.ne4_ne4.log.171211-120502.txt)

Logs grepped by process id
[acme.F1850C5AV1C-04P2.ne4_ne4.log.132.171211-120502.txt](https://github.com/ESMCI/cime/files/1548898/acme.F1850C5AV1C-04P2.ne4_ne4.log.132.171211-120502.txt)
[acme.F1850C5AV1C-04P2.ne4_ne4.log.131.171211-120502.txt](https://github.com/ESMCI/cime/files/1548899/acme.F1850C5AV1C-04P2.ne4_ne4.log.131.171211-120502.txt)
[acme.F1850C5AV1C-04P2.ne4_ne4.log.130.171211-120502.txt](https://github.com/ESMCI/cime/files/1548900/acme.F1850C5AV1C-04P2.ne4_ne4.log.130.171211-120502.txt)
[acme.F1850C5AV1C-04P2.ne4_ne4.log.129.171211-120502.txt](https://github.com/ESMCI/cime/files/1548901/acme.F1850C5AV1C-04P2.ne4_ne4.log.129.171211-120502.txt)
[acme.F1850C5AV1C-04P2.ne4_ne4.log.128.171211-120502.txt](https://github.com/ESMCI/cime/files/1548902/acme.F1850C5AV1C-04P2.ne4_ne4.log.128.171211-120502.txt)

**Comment by rljacob** [comment]
For the driver, you may want to explore this using X or A cases first.   Those have less code then anything with a full model.

**Comment by mfdeakin-sandia** [comment]
The X case is fine AFAICT, aside from potential memory leaks. I haven't tried an A case yet, I'll do that next, though I suspect it will run into this also.

**Comment by rljacob** [comment]
X case does not have illegal memory access?  That's good to know.

**Comment by mfdeakin-sandia** [comment]
Actually, I misremembered; my previous report of potential leaks was for an A case. I'll try an X case next then

**Comment by mfdeakin-sandia** [comment]
I should stop replying and check everything; both A and X are fine

**Comment by mfdeakin-sandia** [comment]
This definitely looks like an MPI error...
It fails here:
`   call mpi_init(ierr)`

**Comment by rljacob** [comment]
It can't be mpi_init because all the cases (A and X too) call that.   And you'd see a problem if you just ran an MPI "hello world".

**Comment by mfdeakin-sandia** [comment]
I agree that there's something weird going on. I managed to solve this by switching to openmpi

**Comment by mfdeakin-sandia** [comment]
I've submitted a bug report to mvapich, hopefully they know what's going on
