### ISSUE TITLE
xmlchange of MPILIB=mpi-serial does not set NTASKS=1 for all components

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#2134]
If a user specifies "--mpilib mpi-serial" on a create_newcase, all of the NTASKS are set to 1.

If a user issues create_newcase without specifying the mpilib, but instead issues an xmlchange MPILIB=mpi-serial before calling case.setup, the NTASKS are NOT set to 1.

I believe both ways of running should result in NTASKS being set to 1.

**Comment by jedwards4b** [comment]
@cacraigucar I was not able to reproduce your problem, setting MPILIB=mpi-serial does reset all NTASKS=1.   Try again, if you can reproduce please indicate the steps to reproduce.

**Comment by cacraigucar** [comment]
This was an issue back in cime5.4.0-alpha.05/cime_config0.1.0.alpha.02, but is no longer a bug when I upgrade to cime5.4.0-alpha.14 and cime_config0.1.0.alpha.06.
