### ISSUE TITLE
Add reproducibility test

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#214]
This was suggested at today's CSEG meeting; it doesn't seem critical, but could be a good addition to the set of possible system test types (SMS, ERS, etc.): A test that two startup runs with the exact same configuration are bit-for-bit identical.

The specific issue this would have caught was a reproducibility problem that just appeared in the first timestep of a startup run with WaveWatch. Because this problem only appeared in startup runs, exact restart tests didn't catch it. Regression tests against baselines would have caught it, but there were expected answer changes that masked the existence of this problem.

For more heavily-developed components, bit-for-bit refactoring is common enough that this test may not be needed, since reproducibility problems are usually caught in the course of running the component's system test suite on a set of changes that are expected to be bit-for-bit. But it could be a useful, quick sanity check: e.g., if an ERS test is failing, it can be helpful to confirm that two startup cases give bit-for-bit identical results before looking into problems that are specific to restart.

**Comment by rljacob** [comment]
+1  We also had a case where an ERS test passed but someone noticed BFB differences between two startup runs (same executable run twice).

**Comment by billsacks** [comment]
With the refactoring I proposed here: https://github.com/ESMCI/cime/issues/292 I believe that the SystemTestsCompareTwo base test would itself be a reproducibility test; or, if you prefer:

```python
class reproducibility(SystemTestsCompareTwo):
    pass
```

**Comment by jedwards4b** [comment]
Replying to Rob's comment - the ERS test is not designed to test for differences between two startup runs.   The PET test however might be expected to pick up that difference - it might be interesting to try it on that case and see if it in fact does find the problem.

**Comment by rljacob** [comment]
The PET test probably would find it but people would think diffs were from the threading change.  There really needs to a "run the same thing twice" test.

**Comment by billsacks** [comment]
I'm implementing a reproducibility test (currently, REP) as part of my attempt to address #292 . I'll point people to this when I have something to demonstrate.
