### ISSUE TITLE
Y10K bug:  Restart file names mangled after model crosses year 10,000 boundary

### ISSUE THREAD

**Issue by olsonjg** [ESMCI/cime#2140]
#
  I am running aquaplanet.  After crossing the Y10K model time boundary some filenames
 are mangled.  The cam.h0 and cam.r file names were *correctly* configured, for example:

  cam4_aqua_4x5.cam.h0.10031-01-01-00000.nc
  cam4_aqua_4x5.cam.r.10031-01-01-00000.nc
  cam4_aqua_4x5.cam.rs.10031-01-01-00000.nc

But the following filenames were mangled because of an apparent 4 character restriction:
```
cam4_aqua_4x5.cpl.hi.****-01-01-01800.nc
cam4_aqua_4x5.cpl.r.****-01-01-00000.nc
cam4_aqua_4x5.docn.rs1.****-01-01-00000.bin
```
  The model is still successfully able to restart, however, using these mangled files

                 Jerry Olson

**Comment by olsonjg** [comment]
The dialog box further mangled the names by dropping "\*\*\*\*" in the first 2 names.  But you get the
 idea

**Comment by billsacks** [comment]
I remember being part of some discussions on the Y10K bug about five years ago, either at CSEG meetings or via email. The conclusion was that there would need to be a lot of changes throughout the system (in component models as well as what is now cime) to support crossing the Y10K boundary robustly. I don't remember details of the discussion, but I think @apcraig was a key member.

That said, it would be great if the system could support this... just a word of caution that it may not be easy.

**Comment by jedwards4b** [comment]
@billsacks Component models shortcomings are beyond the scope of this issue.   I believe I have addressed the problems in cime.
