### ISSUE TITLE
Update BUILD_COMPLETE if build fails?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2152]
I've been bitten by this a couple times (using `cime5.4.0-alpha.03`, apologies if this has been addressed in a later tag). If 

```
$ ./case.build
```

ran successfully, and then I change the code in a manner that doesn't build (never my intent, but it's been known to happen), I get the expected error message.

```
$ ./case.build
...
ERROR: BUILD FAIL: pop.buildlib failed, cat /scratch/cluster/mlevy/C1850ECO.T62_g37.ciso.marbl_dev_levy/bld/ocn.bldlog.171218-135455
```

However, this seems to break my ability to build. Trying again, I get

```
$ ./case.build
Building case in directory /home/mlevy/codes/CESM/cesm2_0_beta07+marbl_dev_levy/cases/C1850ECO.T62_g37.ciso.marbl_dev_levy
sharedlib_only is False
model_only is False
File /home/mlevy/codes/CESM/cesm2_0_beta07+marbl_dev_levy/cases/C1850ECO.T62_g37.ciso.marbl_dev_levy/LockedFiles/env_build.xml has been modified
  found difference in BUILD_COMPLETE : case False locked True
Setting build complete to False
ERROR:
ERROR env_build HAS CHANGED
  A manual clean of your obj directories is required
  You should execute the following:
    ./case.build --clean-all
```

Comparing `env_build.xml` to what's in `LockedFiles` is interesting:

```
$ diff env_build.xml LockedFiles/
264c264
<     <entry id="BUILD_COMPLETE" value="FALSE">
---
>     <entry id="BUILD_COMPLETE" value="TRUE">
289c289
<     <entry id="BUILD_STATUS" value="1">
---
>     <entry id="BUILD_STATUS" value="0">
```
I say interesting because simply copying `env_build.xml` into `LockedFiles/` isn't sufficient; it turns out I need `BUILD_COMPLETE=FALSE` and `BUILD_STATUS=0` (in both my case directory and `LockedFiles/`; even removing the version in `LockedFiles/` causes the same `env_build HAS CHANGED` error).

**Comment by gold2718** [comment]
Duplicate of #1971? Hopefully fixed by #2051.

**Comment by gold2718** [comment]
Looking at the log, this would mean updating to `cime5.4.0-alpha.10`.

**Comment by mnlevy1981** [comment]
Cool, thanks for pointing me to that!
