### ISSUE TITLE
Way to convey to user about a machine/compiler/mpilib combination that isn't working

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2159]
This started as a discussion in #2128. @jedwards4b and @fischer-ncar aren't sure about the idea, but I'd like to have a larger discussion on it, and if I get shot down so be it.

The thing I'd like to see is an optional way for a given machine/compiler/mpilib combination to indicate to the user that the combination is known not to work (at least out of the box). This would be used in cases where effort has been put into a combination, but it still doesn't work. Conveying this is especially important when releases are made, so that the public can know -- by the way this doesn't work. In the middle of development cycles it would be hard to impossible to stay on top of this -- and you probably don't need to. But, if something is known to not work, and it hasn't worked for a long time, it would be good to have a way to indicate that.

An implementation I propose is an optional field that can be added to a given machine in config_machines.xml. Something like adding a field "COMP_MPILIB_COMBINATIONS_NOT_GENERALLY_WORKING" as below...

```
  <machine MACH="cheyenne">
    <DESC>NCAR SGI platform, os is Linux, 36 pes/node, batch system is PBS</DESC>
    <NODENAME_REGEX>.*.cheyenne.ucar.edu</NODENAME_REGEX>
    <OS>LINUX</OS>
    <COMPILERS>intel,gnu</COMPILERS>
    <MPILIBS>mpt,openmpi</MPILIBS>
    <COMP_MPILIB_COMBINATIONS_NOT_GENERALLY_WORKING>gnu_mpt</COMP_MPILIB_COMBINATIONS_NOT_GENERALLY_WORKING>
```

I'd prefer that if the field is given and it matches what the user specifies -- that it abort on the build. But, it could also just be a warning. And in either case, it could say 

to continue, remove the gnu_mpt setting in the field COMP_MPILIB_COMBINATIONS_NOT_GENERALLY_WORKING in config_machines.xml.

So it's easy to get around, and the warning (or error) tells you exactly what to do. You'd also only add this to combinations that aren't being tested and only as an indicator "we can't seem to get this combination to work".

@fischer-ncar brought up the point that sometimes a combination works for some compsets and not others. I think that kind of information would be best to put in a comment something like...

`<!-- The gnu_mpt combination works for C and G compsets, but fails for I EBK 12/20/2017. -->`

Another way to do it would be with a comment in config_machines.xml, but that isn't something that people would look at right away, so I'd prefer it to give at least a warning regarding it.

Mentioning some specific people to add to the discussion: @billsacks @bandre-ucar @mvertens @gold2718 @rljacob @jgfouca

**Comment by billsacks** [comment]
(@mvertens felt this was not something we need to do, based on discussions at cseg meetings.)
