### ISSUE TITLE
use of python datetime in case_st_archive precludes dates beyond 9999

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2162]
We don't need to use datetime here.

**Comment by mfdeakin-sandia** [comment]
Would it make sense to just write our own datetime object?

**Comment by jedwards4b** [comment]
Writing a fully general datetime is pretty involved, but I think we can get the functionality we are currently using without resorting to that.

**Comment by mfdeakin-sandia** [comment]
That's fair. I'm not fond of this idea, since it seems like too much of a hack, but thinking about it, maybe we could get away with just changing MAX_DATE to something much larger? IIRC, the Python code only uses it in one place, and raises an exception if we're too large, though it may cause issues with formatting.

**Comment by jedwards4b** [comment]
I tried that, couldn't figure out how to change that value - maybe you can?   I was also worried about side-effects.

**Comment by mfdeakin-sandia** [comment]
I'm finally starting on this, but was wondering what the format for dates with years >9999 was?
The format most dates use has only 4 digits for the year

**Comment by jedwards4b** [comment]
The only place this is used is in case.st_archive and the functionality that we need is really minimal, I think we can easily do this without an external date object at all.

**Comment by mfdeakin-sandia** [comment]
The primary issue is that I need to add a timedelta object to a date - I'd rather not get into the details of adding dates if possible

**Comment by mfdeakin-sandia** [comment]
Alright, looking at what the addition is needed for, you're correct, a datetime object isn't really needed
