### ISSUE TITLE
setting COMPILER in .cime/config breaks scripts_regression_tests.py

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2171]
On hobart, my `.cime/config` file looks like

```
[main]
CIME_MODEL=cesm
COMPILER=nag
[create_test]
```

And when I run `scripts_regression_tests.py` I get a lot of errors that boil down to the system generating cases with `nag` but looking for case directories using `intel`:

```
======================================================================
FAIL: test_cime_case_xmlchange_append (__main__.K_TestCimeCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1552, in test_cime_case_xmlchange_append
    self.assertTrue(os.path.isdir(casedir), msg="Missing casedir '%s'" % casedir)
AssertionError: Missing casedir '/scratch/cluster/mlevy/scripts_regression_test.20171227_093212/TESTRUNPASS_P1x1.f19_g16_rx1.A.hobart_intel.fake_testing_only_20171227_093300'
```

(Note that `TESTRUNPASS_P1x1.f19_g16_rx1.A.hobart_intel.fake_testing_only_20171227_093300` does not exist but `TESTRUNPASS_P1x1.f19_g16_rx1.A.hobart_nag.fake_testing_only_20171227_093300` does; the only difference being `hobart_nag` instead of `hobart_intel`).

Commenting out the `COMPILER` line "fixes" the problem in the sense that the case is built using `intel` instead of `nag` so the directory match works.

**Comment by jedwards4b** [comment]
Don't set compiler in .cime/config for scripts_regression_tests.py -  set it in the environment using CIME_COMPILER instead.

**Comment by mnlevy1981** [comment]
So is `COMPILER` not supported in the `config` file? I had it set that way so that I don't need to remember to add `--compiler nag` every time I create a case on that machine. I'm happy to switch to an environment variable, but it seems strange that some scripts will take the compiler from `config` and others won't.

**Comment by jedwards4b** [comment]
I think that scripts_regression_tests.py is the only exception to using .cime/config

**Comment by gold2718** [comment]
@jedwards4b,
Does this mean that every time I run scripts_regression_tests.py, I have to first edit the `.cime/config` file and then edit it again when scripts_regression_tests.py is complete?

**Comment by jedwards4b** [comment]
I think that if you set environment variable CIME_COMPILER to the value you have in .cime/config it would work correctly.   It may be possible to fix this by having scripts_regression_tests.py read the .cime/config at a higher level, but that may also have unexpected side effects.

**Comment by gold2718** [comment]
Are you saying this should work on Hobart?
`(export CIME_COMPILER=nag; ./scripts_regression_tests.py)`
or do I need to do:
`(export CIME_COMPILER=intel; ./scripts_regression_tests.py)`

**Comment by jedwards4b** [comment]
If COMPILER is not defined in .cime/config than either should work correctly.  If it is defined then I think that CIME_COMPILER needs to match that value.

**Comment by jedwards4b** [comment]
Maybe the easiest fix for this is to make sure that CIME_COMPILER, if set, takes precedence over .cime/config

**Comment by jedwards4b** [comment]
I lied - there is no CIME_COMPILER environment variable.   Working on this now.

**Comment by gold2718** [comment]
That is a possibility but it brings up the issue that (as far as I can tell), we have not documented whether environment variables ever override settings in XML files or in .cime/config. For instance, we have statements such as:

> `PROJECT`: a project or account number used for batch jobs; can be overridden in environment or in **$HOME/.cime/config**

in [section 2.3](http://esmci.github.io/cime/users_guide/porting-cime.html#config-machines-xml-machine-specific-file) but even that statement does not say which takes precedence.

Is there a rule or consistent behavior in CIME? Should we open a separate issue on this?

**Comment by jedwards4b** [comment]
There is a rule and, I think, consistent behavior.  Environment variables always take precedence if set.  PROJECT is a good example.
