### ISSUE TITLE
Document precedence rules of variables

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2172]
In #2171, @jedwards4b mentioned:

> There is a rule and, I think, consistent behavior. Environment variables always take precedence if set. PROJECT is a good example.

However, I could not find anywhere this is documented in the CIME documentation. There are several ways PROJECT can be set -- what are the rules of precedence?
In general, I think we should document precedence rules for command-line switches, environment variables, CIME XML file entries and a user's .cime/config file.
I have no idea where this should be in the documentation. Anyone?

**Comment by mvertens** [comment]
@gold2718 - I completely agree. Thanks for raising this issue. I think this
should go into the of the User's Guide part 1 - since it really is a basic
usage that we are addressing. Thoughts?
