### ISSUE TITLE
run case.submit while case is in the queue

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2185]
Some users would like to stage multiple continuation jobs in the queue by running case.submit multiple times with the --prereq flag to indicate a dependency on previous runs in the queue.  This would be an alternative to using the RESUBMIT flag and may give an advantage in the queue waiting list on some HPC systems.

**Comment by jgfouca** [comment]
@mfdeakin-sandia

**Comment by jgfouca** [comment]
Need to make sure case.submit does not make XML changes, only the submitted scripts should do that in order to avoid races etc in case.submit. Maybe have case_submit use its Case object in read-only mode.

**Comment by jgfouca** [comment]
@jedwards4b , looking at case_submit, it should be safe to have multiple case submits under the following conditions:

1) The submitted case is not a test
2) The user is not using resubmit
3) The user is not using --no-batch for any of the submits

I have no idea how to enforce this without making the code a mess. I'm tempted to just close this ticket.

**Comment by jedwards4b** [comment]
So a careful user could do it, but we can't protect them from themselves.

**Comment by jgfouca** [comment]
Yeah, there's really no elegant way of supporting resubmit and/or no-batch if the case object is read_only.
