### ISSUE TITLE
bless_test_results failing on cheyenne

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#2190]
When I issue the following bless_test_results on cheyenne, it has an error.   This is using cime5.4.0-alpha.17.   For a point of reference, when I ran bless_test_results on both cheyenne and yellowstone right before I left for the holidays (using cime5.4.0-alpha.14)  , the yellowstone test ran correctly and cheyenne did not.  Unfortunately I did not have time to investigate this further before yellowstone was decommissioned.  (I've put the first error in bold so it is more easily visible).  

    ../../../../cime/scripts/Tools/bless_test_results -r /glade/scratch/cacraig/aux_cam_20171219150408 -b cam5_4_157-test2 

###############################################################################
Blessing results for test: ERS_Ln9.f19_f19_mg17.FSPCAMS.cheyenne_intel.cam-outfrq9s, most recent result: PASS
###############################################################################
Test 'ERS_Ln9.f19_f19_mg17.FSPCAMS.cheyenne_intel.cam-outfrq9s' had namelist diff
Update namelists (y/n)? y
**ERROR BFAIL baseline directory '/UNSET/cam5_4_157-test2/ERS_Ln9.f19_f19_mg17.FSPCAMS.cheyenne_intel.cam-outfrq9s' does not exist**
Update this diff (y/n)? y
Traceback (most recent call last):
  File "../../../../cime/scripts/Tools/bless_test_results", line 109, in <module>
    _main_func(__doc__)
  File "../../../../cime/scripts/Tools/bless_test_results", line 103, in _main_func
    report_only=report_only, force=force, bless_tests=bless_tests, no_skip_pass=no_skip_pass)
  File "/glade2/scratch2/cacraig/cam5_4_157/cime/scripts/Tools/../../scripts/lib/CIME/bless_test_results.py", line 148, in bless_test_results
    success, reason = bless_history(test_name, test_dir, baseline_name, baseline_root, report_only, force)
  File "/glade2/scratch2/cacraig/cam5_4_157/cime/scripts/Tools/../../scripts/lib/CIME/bless_test_results.py", line 64, in bless_history
    gen_result, gen_comments = generate_baseline(case, baseline_dir=baseline_full_dir)
  File "/glade2/scratch2/cacraig/cam5_4_157/cime/scripts/Tools/../../scripts/lib/CIME/hist_utils.py", line 387, in generate_baseline
    os.makedirs(basegen_dir)
  File "/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/UNSET'

**Comment by jgfouca** [comment]
@cacraigucar , can you go to the case directory and do this:

```
./xmlquery BASELINE_NAME_CMP
./xmlquery BASELINE_ROOT
```

**Comment by cacraigucar** [comment]
cheyenne4$ ./xmlquery BASELINE_NAME_CMP
        BASELINE_NAME_CMP: UNSET
cheyenne4$ ./xmlquery BASELINE_ROOT
        BASELINE_ROOT: /UNSET
cheyenne4$ printenv | grep CESMDATAROOT
CESMDATAROOT=/glade/p/cesmdata/cseg

**Comment by jedwards4b** [comment]
@jgfouca is it enough to just always assign these in the case - I think right now they depend on the --generate or --compare flags in create_test.

**Comment by jgfouca** [comment]
@jedwards4b , if BASELINE_ROOT is assigned in the case, then that will fix the bug since @cacraigucar was already providing the baseline name.

**Comment by jedwards4b** [comment]
I think that line 167 of test_scheduler.py should be moved to 176 - do you agree?

**Comment by jedwards4b** [comment]
testing that change now.  @cacraigucar if you set BASELINE_ROOT in the case then bless_test_results should work correctly.

**Comment by jgfouca** [comment]
@jedwards4b , yes, nice catch.
