### ISSUE TITLE
CAM-SE needs low-res refined grid for testing

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2191]
CAM-SE needs to test refined-grid functionality but the available grids are too large.
I will introduce a new low-resolution grid for testing. Some possible grid names are:

ne0EQFACEne5x4_ne0EQFACEne5x4_mg37
or
ne0TESTONLYne5x4_ne0TESTONLYne5x4_mg37
or
something else?

Note, the current refined-grid grid is called ne0CONUSne30x8_ne0CONUSne30x8_mg17

Any thoughts? @mvertens? @fischer-ncar?

**Comment by fischer-ncar** [comment]
I think that if the low-resolution grid still covers CONUS it should be  

ne0CONUSne5x4_ne0CONUSne5x4_mg17

I'm not a fan of TESTONLY, unless it's some completely fictional grid.  I'm not exactly sure what EQFACE
means.

**Comment by gold2718** [comment]
It is not a CONUS grid, the refined region is just a random spot on an equatorial face (one of 4 in the cubed sphere as opposed to the 2 polar faces).

**Comment by fischer-ncar** [comment]
Then I would go with TESTONLY.
