### ISSUE TITLE
Conflict characters left over

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#22]
A few files still have conflict characters in them.  May need to re-merge?

blogin3blogin3[227]: grep -lr '<<<<<<<' .
./driver_cpl/driver/seq_hist_mod.F90
./driver_cpl/shr/seq_flds_mod.F90
./scripts/Testing/Testcases/config_tests.xml
./scripts/Tools/case.build
./scripts/create_newcase
./share/csm_share/shr/shr_pio_mod.F90
./share/csm_share/test/old_unit_testers/run_file_test
./share/csm_share/test/old_unit_testers/test_shr_file.F90

blogin3[228]: grep -lr '>>>>>>' .
./externals/pio/examples/basic/perl5lib/ChangeLog

**Comment by jgfouca** [comment]
Those are intentional. They should be commented out with a "JGF NEED HELP" at the top.

**Comment by jedbrown** [comment]
@jgfouca You could commit into a temporary branch and amend the merge commit after sorting it out, but intentionally committing a broken merge on 'master' is a crazy workflow. My $.02.

**Comment by jgfouca** [comment]
@jedbrown , normally I'd agree with you. Rob and I agreed that this repo would be "wild west" while the merge was sorted out. If others feel as you do, I can reset the master branch to before the merge and put all the commits since then on a branch.

**Comment by rljacob** [comment]
All but one in shr_pio_mod.F90 were removed after PR #37 .
