### ISSUE TITLE
Want ability to select default queue based on number of tasks, not just number of nodes

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2209]
We used to have the ability for cime to select a default queue based on the number of tasks. With @jgfouca 's changes in #1918 (to fix #1913), this is no longer possible.

This is important for jobs that use less than a full node - such as single-point or other jobs that use a single task. CLM, CISM and possibly other components have used this capability in some configurations. Now these single-processor jobs are using a full node - so, on cheyenne, they are getting charged 36x what they should be.

Can we get back the capability to select queues based on the number of tasks?

@jedwards4b @ekluzek

**Comment by jedwards4b** [comment]
Would a special case for single task jobs be an adequate solution?

**Comment by billsacks** [comment]
> Would a special case for single task jobs be an adequate solution?

That would be better than nothing, but in the past we settled on something like half a node as a good compromise: there are some jobs that use more than one task but still significantly less than a full node - for example, a few ensemble members of a single-point case (we have some things like that in the test suite).

If we could have just one special case, I think the best special case would be for jobs using less than half of a node.

**Comment by jgfouca** [comment]
Need to decide on how to handle this usecase.

**Comment by billsacks** [comment]
I don't think #2326 actually addressed this, since my request related to the core job, and #2326 only addressed non-core jobs.

**Comment by jedwards4b** [comment]
We still need a little more work to use the share queue on cheyenne,  I'll take this on
https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs/using-mpt-cheyenne-share-queue

**Comment by billsacks** [comment]
Thanks, @jedwards4b . I'm going to move your note to a separate issue.
