### ISSUE TITLE
The -list command is broken in create_newcase

### ISSUE THREAD

**Issue by changliao1025** [ESMCI/cime#2218]
I only tested the query_config script with --query-compsets-setby 

*_The OPTIONAL %phys attributes specify submodes of the given system
    For example DOCN%DOM is the data ocean model for DOCN
    ALL the possible %phys choices for each component are listed
    with the -list command for create_newcase
    ALL data models must have a %phys option that corresponds to the data  model mode__*

Then I tried the -list command, but it is not supported in create_newcase.

**Comment by jedwards4b** [comment]
Not sure what version you are using, but in the latest there is no query_case and there is no --list option to create_newcase.

**Comment by changliao1025** [comment]
I had a typo and it should be "query_config" script. I guess the -list was removed? If so then the "config_compsets.xml" file may need an update.

**Comment by jedwards4b** [comment]
Yes - its the help section of the acme config_compsets.xml that is out of date.

**Comment by jgfouca** [comment]
I will update the help section.

**Comment by changliao1025** [comment]
Thanks for the updates.
Then does that mean this functionality is also removed? How can I find all the phys choices for each component in this case?
