### ISSUE TITLE
st_archive in the context of esp (DART data assimilation)

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2240]
@bertinia @jgfouca 
Please tag anyone else who should be in this discussion.

I'm testing the st_archive and have run into a conflict
between how I've set up the env_archive.xml file and what
   archive.py:setup  -> generic_xml.py:get_optional_node
is expecting.

I've put a section in env_archive.xml to archive the output from
data assimilation.  We've settled on the file naming convention
that already existed for CESM, which uses the .e. extension applied to
the relevant componenent extention (e.g. .cam[_0001].
so that the new files which must be archived have names like
CIME_DA_vars_3.cam.e.preassim_mean.2008-08-02-43200.nc.
The new section in env_archive.xml starts with
    <comp_archive_spec compclass="esp" compname="cam">
but this 'cam' is viewed as being redundant with the earlier
    <comp_archive_spec compclass="atm" compname="cam">

After archiving the log files, the error message appears:
ERROR: Multiple matches for 
        nodename 'comp_archive_spec' and 
        attrs '{'compname': 'cam'}' in file
        '/glade/p/work/gaubert/cases/run_Dec18/env_archive.xml'

Do I need to change the esp compname, or should the scripts
view these 2 "cam"s as different?
If you think that I need to change it, we should reopen the discussion
about how these bits are used and the naming convention for files.

**Comment by jedwards4b** [comment]
@kdraeder are you using an older version of cime?  get_optional_node no longer exists in generic_xml.py and updating to the latest version may solve the problem.

**Comment by kdraeder** [comment]
So you're suggesting that I rewrite these sections 
of the modules so that they do what I think they should
do for esp/dart, and still do what the rest of cime wants
them to do?

**Comment by jedwards4b** [comment]
Maybe we should talk about this - according to our convention (which is young and not widely known) the compclass esp would not have a component cam, it would have a component dart.

**Comment by kdraeder** [comment]
I agree.   I'm available this afternoon until 4
and tomorrow before 11 and after 1:30.

Kevin

**Comment by gold2718** [comment]
I'm at home but can join in via phone.
I agree with @jedwards4b -- this feels a bit like a square peg in a round hole but I admit to not understanding the problem you are trying to solve.

**Comment by jedwards4b** [comment]
Meeting set for tomorrow at 2 in my office.

**Comment by kdraeder** [comment]
I'll describe it here, but it might require pictures and pointing.

St_archive will archive the output from DART (not the model forecast)
in the standart $DOUT_S_ROOT/esp/hist.

The DART file names Alice and I settled on have a CESM standard form
    $CASE.$comp.e.$string.$date.nc
    where string = {the various file types written by DART; prior_mean,
posterior_sd, ...}

We planned for the imminent date when we do an assimilation in multiple
components
(e.g. CAM and POP), in which each components' assimilation will create a
similar set
of files (see 'string', above).  All those files will be archived into
esp/hist, so they
need distinct file names.  For example, the prior_mean files from CAM and
POP
will be distinguished by $comp (= cam and pop):
   Case.cam.e.prior_mean.$date.nc
    Case.pop.e.prior_mean.$date.nc
So I think this should/would/will be implemented in env_archive.xml with
<comp_archive_spec compclass="esp" compname="cam">
     ...list of suffixes for DART's CAM output
<comp_archive_spec compclass="esp" compname="pop">
     ...list of suffixes for DART's POP output

In the current CIME this "cam" is considered to be redundant with the "cam"
in
<comp_archive_spec compclass="atm" compname="cam">
even though they are actually differentiated by the compclass; 'esp' vs
'atm'.

Kevin

**Comment by jedwards4b** [comment]
I believe that <comp_archive_spec compclass="esp" compname="dart">
should have a list of suffixes for DART's output
independent of model component.

**Comment by kdraeder** [comment]
I believe the compname is used to create the file names to be archived:
def _archive_history_files(
    ...
                    newsuffix = casename + '.' + compname + ".*" + suffix
So under your proposal the 2 file names would end up
   Case.dart.e.prior_mean.$date.nc
   Case.dart.e.prior_mean.$date.nc
which can't live in the same directory.

The way I see it, there are a bunch of file types associated with CAM:
.i., .r., .h#....   We're introducing another, .e.$string, which doesn't
come directly from CAM, but has the same grid structure, variable names,
etc.
So naming it with .cam.e seems very consistent to me.

We could attach component information onto the string,
but that would make the names even longer, with redundancy
between the 'dart' and 'e' parts.
Putting the component information anywhere else doesn't seem
to fit in the CESM naming convention.

Also, the current CIME code is saying that different compclasses
may never use comp instances which have the same name,
which seems to be not in the spirit of modularity of components.
If the perfect land glacier model ends up with the name CICE,
then that name can't be used in CIME because it's already used
by an instance of the sea ice compclass.

Kevin

**Comment by jedwards4b** [comment]
We need to figure out another way to do it.  The compclass and compname combination you are suggesting is not compatible with our current logical relation between those names.

**Comment by kdraeder** [comment]
Alice has been working on this with me for a year or so,
so she should probably be invited to our meeting.
She's busy from 2-3, so hopefully we can find another time,
when we (and any others you think would be helpful)
can meet.

Kevin

**Comment by gold2718** [comment]
I'm not sure what the `.e.` part of your filename is supposed to stand for but I suggest using the one-letter abbreviation we use for component classes. In your example, this would make the filenames:
```
 Case.dart.a.prior_mean.$date.nc
 Case.dart.o.prior_mean.$date.nc 
```
and there would be no conflict. The only restriction is having one component of any class but that is all over the system already.

This naming convention would be similar to CAM's in that different types of output files are distinguished by that field (e.g., `.i.`, `.h0.`, `.h1.`). To make it even more CAM like, we can get rid of the extra period.
```
 Case.dart.a_prior_mean.$date.nc
 Case.dart.o_prior_mean.$date.nc 
```

**Comment by kdraeder** [comment]
For file names I've been working off of
http://www.cesm.ucar.edu/models/cesm2.0/cesm/filename_conventions_cesm.html
where e stands for esp.

That site doesn't mention the generic component class abbreviations a, o,
...
What are the rest and where are they described?
I don't remember ever seeing those.   Thanks for bringing them up.

**Comment by gold2718** [comment]
@kdraeder, 

In the document you cite, 'e' stands for External Statistical Package, not External System Processing.

The filename template is:
```
$output = $CASE.$scomp.$type.[$string.]$date[$ending] 
```

Here, I think `$type` should be `h` for history (unless you really mean `e` for External Statistical Package) and I am suggesting adding the one-letter code to the beginning of `$string`.  The list (from the top of config_grids.xml) is:
```
a% => atm
l% => lnd
oi% => ocn/ice
r% => river
m% => mask
g% => glc
w% => wav
```
We could modify that list as needed -- it is an internal DART naming convention.

**Comment by kdraeder** [comment]
Did I accidentally use "External System Processing" somewhere?
I don't see it in this thread or in the web page.

If we label these as history files, will that imply that they have some
sort of format and/or contents that they might not have?

I guess the reason I wasn't considering the naming convention
from config_grids.xml is that those are for describing grids,
not CESM output files.  Are there any CESM output files that
use these grid abbreviations?  If so, will those abbreviations
be put into the CESM file naming convention web page?

In any case, 'oi' won't work in the DART  context because we do
assimilations separately in the ocean and sea ice.   So we'd need
to expand the list to include 'o' and 'i' (or 's' or 'si' or ...?).
You may consider it an internal DART convention when it's part
of $string, but I think that  it should be consistent with a publicly
documented CESM naming  convention, to minimize confusion
and conflicts and documentation needs.
A smaller number of lists of abbreviations is valuable too.

Kevin

**Comment by bertinia** [comment]
The http://www.cesm.ucar.edu/models/cesm2.0/cesm/filename_conventions_cesm.html
document does refer to $type of "e (External Statistical Package)" which I think should be
(External System Processing) - clearly, my ESP wasn't working when I updated this webpage - it's corrected now. 

At any rate, I think if we adhere to this naming convention, then all that is needed for DART is
to add an element:

`<hist_file_extension>\.e.*.nc$</hist_file_extension>`

to the <comp_archive_spec> element.

So for CAM, this would look like:

`  <comp_archive_spec compname="cam" compclass="atm">
    <rest_file_extension>\.[ri]\..*</rest_file_extension>
    <rest_file_extension>\.rh\d\.*</rest_file_extension>
    <rest_file_extension>\.rs\.*</rest_file_extension>
    <hist_file_extension>\.h.*.nc$</hist_file_extension>
    **<hist_file_extension>\.e.*.nc$</hist_file_extension>**    
    <rest_history_varname>nhfil</rest_history_varname>
    <rpointer>
      <rpointer_file>rpointer.atm$NINST_STRING</rpointer_file>
      <rpointer_content>$CASE.cam$NINST_STRING.r.$DATENAME.nc </rpointer_content>
    </rpointer>
  </comp_archive_spec>

This shouldn't have any affect on non-DART cases because the archiver just passes if
a filename matching that pattern is absent in the rundir. 

@kdreader - can you try this in your caseroot by changing the env_archive.xml to make
sure it works and then we can update the config_archive.xml in CIME accordingly?

**Comment by kdraeder** [comment]
Am I right in thinking that this will archive the DART output to
archive/cam/hist?   Even if it's POP+DART output?

Kevin

**Comment by bertinia** [comment]
Yes, as long as there are history filename pattern matches in the rundir, then the rules for where
those files are archived is independent of the compset or active components.

**Comment by kdraeder** [comment]
Ah, I see that I was mistaken; "cam" is used to construct the filenames,
so POP files would not be put in cam/hist.

But it still seems odd to put DART output there, instead of in esp/hist.
Shouldn't each component have its own comp_archive_spec section
of env_archive.xml?

Kevin

**Comment by kdraeder** [comment]
It looks like we've come up with a st_archive scheme for DART output
that is acceptable to everyone.  Here's a summary.  Tell me if I'm
misunderstanding any of it.

Following Alice's suggestion, we add something like
   <hist_file_extension>\.e.*.nc$</hist_file_extension>
to each comp_archive_spec section in env_archive.xml
which handles a component that's used in data assimilation.
This will archive DART output that's directly related to
a component into that components archive/$comp/hist directory.
These files will be named
   $CASE.cam[_$instance].e.$dart_type_string.$date.nc

The rest of the DART output will be archived into
archive/exp/{hist,rest,logs} by a
 <comp_archive_spec compname="dart" compclass="esp">
section, and will be named
   $CASE.dart.e.$dart_type_string.$date[.nc]

The test preventing multiple compnames having the same value will stay.

I'll test this and see if there are any unexpected problems.
Thanks for working through this with me.

Kevin

**Comment by jedwards4b** [comment]
@kdraeder I think we can drop the .e. and just use .dart.

**Comment by gold2718** [comment]
> The rest of the DART output will be archived into
archive/exp/{hist,rest,logs} by a

Is that supposed to be archive/esp/{hist,rest,logs}?

**Comment by jedwards4b** [comment]
yes

**Comment by kdraeder** [comment]
Why don't you like .e.?

I'm under the impression that the $type (.r. .e. ...) is a required part of
the name.
Are you suggesting replacing .e. with .dart.?
It's too long, according to the convention web page.  And it would leave us
with names for the purely DART output having .dart.dart. in them.

Or is the $type not a required part, so I could have files in
archive/atm/hist like  $CASE.cam.$dart_type.$date.nc   and files in
archive/esp/hist like  $CASE.dart.$dart_type.$date.nc?

Kevin

**Comment by kdraeder** [comment]
Thanks for the careful reading.  esp is correct.

**Comment by jedwards4b** [comment]
No you can leave out $type

**Comment by kdraeder** [comment]
The next stage of this is handled in #2334 and PR 499 (py_regex_kdr).

**Comment by kdraeder** [comment]
@jedwards4b @gold2718 @bertinia @jgfouca 
From my perspective, this and related DART st_archive issues 
have been resolved, so this can be closed.  I'm the assignee,
so I guess that's my job, but I'd like to make sure there are
no objections.
