### ISSUE TITLE
INVALID_COMPILER_MPILIB_COMBINATIONS needs to be added to config_machines.xsd

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2241]
This is with cime5.4.0-alpha.20 and current master. INVALID_COMPILER_MPILIB_COMBINATIONS was added to the config_machines.xml file, but not added to the XSD file, so xmllint gives an error as follows...

`ERROR: Command: '/bin/xmllint --noout --schema /fs/cgd/data0/erik/clm_cesm20beta08externals/cime/config/xml_schemas/config_machines.xsd /fs/cgd/data0/erik/clm_cesm20beta08externals/cime/config/cesm/machines/config_machines.xml' failed with error '/fs/cgd/data0/erik/clm_cesm20beta08externals/cime/config/cesm/machines/config_machines.xml:261: element INVALID_COMPILER_MPILIB_COMBINATIONS: Schemas validity error : Element 'INVALID_COMPILER_MPILIB_COMBINATIONS': This element is not expected. Expected is one of ( MPILIBS, PROJECT, CHARGE_ACCOUNT, SAVE_TIMING_DIR, SAVE_TIMING_DIR_PROJECTS, CIME_OUTPUT_ROOT ).`

**Comment by jedwards4b** [comment]
When was this added?  I thought that this suggestion was rejected?  How did it get in without testing?

**Comment by ekluzek** [comment]
Whoops, this was just in my sandbox. I had done an update and thought it was in the latest version.
