### ISSUE TITLE
Add pstrid as value to modify in config_pes.xml file

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2246]
Here is an example of the file:

```
        <ntasks>
          <ntasks_atm>43200</ntasks_atm>
          <ntasks_lnd>43200</ntasks_lnd>
          <ntasks_rof>43200</ntasks_rof>
          <ntasks_ice>43200</ntasks_ice>
          <ntasks_ocn>43200</ntasks_ocn>
          <ntasks_glc>64</ntasks_glc>
          <ntasks_wav>64</ntasks_wav>
          <ntasks_cpl>43200</ntasks_cpl>
        </ntasks>
        <nthrds>
          <nthrds_atm>2</nthrds_atm>
          <nthrds_lnd>2</nthrds_lnd>
          <nthrds_rof>1</nthrds_rof>
          <nthrds_ice>1</nthrds_ice>
          <nthrds_ocn>1</nthrds_ocn>
          <nthrds_glc>1</nthrds_glc>
          <nthrds_wav>1</nthrds_wav>
          <nthrds_cpl>2</nthrds_cpl>
        </nthrds>
        <rootpe>
          <rootpe_atm>0</rootpe_atm>
          <rootpe_lnd>0</rootpe_lnd>
          <rootpe_rof>0</rootpe_rof>
          <rootpe_ice>0</rootpe_ice>
          <rootpe_ocn>0</rootpe_ocn>
          <rootpe_glc>0</rootpe_glc>
          <rootpe_wav>0</rootpe_wav>
          <rootpe_cpl>0</rootpe_cpl>
        </rootpe>
```

We've found cases that benefit from changing the PSTRID value (default is 1).  Can we add pstrid as another set of values to change?

And, can we have defaults for all 4 of these:
For any component where ntasks is not listed, use MPITASKS_PER_NODE
For any component where nthrds is not listed, use 1
For any component where rootpe is not listed, use 0
For any component where pstrid is not listed, use 1

**Comment by rljacob** [comment]
Add a block like this:        
```
<pstrid>
          <pstrid_atm>0</pstrid_atm>
          <pstrid_lnd>0</pstrid_lnd>
          <pstrid_rof>0</pstrid_rof>
          <pstrid_ice>0</pstrid_ice>
          <pstrid_ocn>0</pstrid_ocn>
          <pstrid_glc>0</pstrid_glc>
          <pstrid_wav>0</pstrid_wav>
          <pstrid_cpl>0</pstrid_cpl>
        </pstrid>
```
@jedwards4b  does that look right?   Can this be added to just one entry in config_pes.xml?

**Comment by ndkeen** [comment]
Well that's the first thing I tried. I added
```
        <pstrid>
          <pstrid_atm>1</pstrid_atm>
          <pstrid_lnd>1</pstrid_lnd>
          <pstrid_rof>1</pstrid_rof>
          <pstrid_ice>1</pstrid_ice>
          <pstrid_ocn>1</pstrid_ocn>
          <pstrid_glc>1</pstrid_glc>
          <pstrid_wav>1</pstrid_wav>
          <pstrid_cpl>2</pstrid_cpl>
        </pstrid>
```

```
cori11% create_test SMS.ne30_oECv3_ICG.A_WCYCL2000S
Using project from .cesm_proj: acme
Creating test directory /global/cscratch1/sd/ndk/acme_scratch/cori-knl/mfpeat03/SMS.ne30_oECv3_ICG.A_WCYCL2000S.cori-knl_intel.20180123_172353_akk2gf
RUNNING TESTS:
  SMS.ne30_oECv3_ICG.A_WCYCL2000S.cori-knl_intel
Starting CREATE_NEWCASE for test SMS.ne30_oECv3_ICG.A_WCYCL2000S.cori-knl_intel with 1 procs
Finished CREATE_NEWCASE for test SMS.ne30_oECv3_ICG.A_WCYCL2000S.cori-knl_intel in 1.868962 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /global/cscratch1/sd/ndk/acme_scratch/cori-knl/mfpeat03/SMS.ne30_oECv3_ICG.A_WCYCL2000S.cori-knl_intel.20180123_172353_akk2gf
    Errors were:
        ERROR: No variable pstrid found in case

```

(note: you would not want to use 0 as in your example)

**Comment by ndkeen** [comment]
Any thoughts/progress on this?

**Comment by rljacob** [comment]
This is something E3SM wants so maybe @jgfouca should do it?

**Comment by jgfouca** [comment]
@jedwards4b could probably do it faster, but I could take it on.

**Comment by jedwards4b** [comment]
I should be able to work on this this afternoon.

**Comment by jedwards4b** [comment]
@ndkeen - you made the comment:

> And, can we have defaults for all 4 of these:
> For any component where ntasks is not listed, use MPITASKS_PER_NODE
> For any component where nthrds is not listed, use 1
> For any component where rootpe is not listed, use 0
> For any component where pstrid is not listed, use 1
This should already be the case, do you have a counter example?

**Comment by rljacob** [comment]
You mean you can just leave a component out in the block and one of those defaults will be assumed?  I don't think we tried it.  Thought you had to set everything.

**Comment by jedwards4b** [comment]
yes the defaults are assumed except the ntasks one which isn't an obvious default value.

**Comment by ndkeen** [comment]
Yea, I admit I didn't actually try to leave out a rootpe setting of 0 and see if it still got set to 0.  If this works, we could save 1384 lines in `config_pesall.xml` just from rootpe's set to 0.

**Comment by ndkeen** [comment]
fyi: Finally actually tried this in config_pesall.xml  Works!  Great! 

I also tested leaving off some of the components -- ie test using default PSTRID and that works as well.

Thanks!
