### ISSUE TITLE
ERR test not setting DOUT_S

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2249]
It should be TRUE but its currently false on master, git blame doesn't make any sense to me this must have just happened because ERR tests will fail when DOUT_S is FALSE.

**Comment by jedwards4b** [comment]
DOUT_S should be set in err.py in _case_one_setup but this routine does not appear to be called.

**Comment by jedwards4b** [comment]
Seems to be a race condition?

**Comment by jedwards4b** [comment]
What I'm seeing is that at case.build time the DOUT_S in the first case is set correctly to TRUE 
but then in _case_two_setup the case1 value is being set back to true - there should be two case objects in these compare_two style tests - but I think maybe there is only one?

**Comment by jedwards4b** [comment]
Yes I think that the recent caching changes somehow cause these objects not to be distinct.

**Comment by jedwards4b** [comment]
I've traced this to commit 263c909

**Comment by jgfouca** [comment]
@jedwards4b , does ERR fail due to this error? That would give me something to test when I try to repair the new caching feature.

**Comment by jgfouca** [comment]
@jedwards4b , I'm unable to reproduce this error when caching is enabled:

```
% ./create_test --no-build ERR.f45_g37_rx1.A.melvin_gnu
% cd $CASE
% ./case.build
% ./xmlquery DOUT_S
	DOUT_S: TRUE
% cd case2/$CASE
% ./xmlquery DOUT_S
	DOUT_S: FASLSE
```

Can you give me some additional context?

**Comment by jedwards4b** [comment]
It appeared to be a race condition and didn't happen every time.

**Comment by jedwards4b** [comment]
Also I think it only happens on batch systems.

**Comment by jgfouca** [comment]
Did you see the error at build or runtime?

**Comment by jedwards4b** [comment]
At runtime - it would submit the first job but because DOUT_S was FALSE it would not submit the 
archive job.

**Comment by jedwards4b** [comment]
I think what was happening was that the setting of DOUT_S to FALSE for case2 was modifying the case1 instead.
