### ISSUE TITLE
Check locked files function is broken.

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2252]
When a user who doesn't have access to the default account (or repo) on a machine, they can try (at least) these 2 things:
a) use the -p option to create_test
b) go into case directory and xmlchange CHARGE_ACCOUNT=new_repo

Both of these methods show some issues.

a) Example:
./create_test -p m1759 SMS.ne4_ne4.FC5AV1C-L

Then looking at CHARGE_ACCOUNT:
cjyang@cori12:/global/cscratch1/sd/cjyang/acme_scratch/cori-knl/SMS.ne4_ne4.FC5AV1C-L.cori-knl_intel.20180125_112550_jdwdsv> ./xmlquery CHARGE_ACCOUNT
 
Results in group case.run
	CHARGE_ACCOUNT: /project/projectdirs/nstaff/cjyang
 
Results in group case.st_archive
	CHARGE_ACCOUNT: /project/projectdirs/nstaff/cjyang
 
Results in group case.test
	CHARGE_ACCOUNT: /project/projectdirs/nstaff/cjyang

However, user job seems to be OK. ?

b) Somewhat similar issue.  And for both, it looks like what is reported from ./preview_run is a little confusing.

**Comment by jedwards4b** [comment]
@ndkeen Can you please make it clear which version of cime you are using and want machine you are running on.

**Comment by jedwards4b** [comment]
I think I know what is going on - this variable affects the job queue stanza in submitted jobs, thus you must run ./case.setup --reset after changing it for it to take effect.

**Comment by mvertens** [comment]
@jedwards4b - thanks for tracking this down. Can we update the
documentation with this - or issue some type of error command?

**Comment by ndkeen** [comment]
This was on cori @ NERSC with e3sm master of Jan 24.

Regarding default account (repo) to use, I understand it ultimately involves how the machine/center is configured, but I would think it would be nice to:
a) use any account most associated with running these codes (for example at NERSC there is 'acme') _if_ you have access to run there (commands exist to query what accounts you have access)
b) if you dont have access to any "obvious climate-associated accounts", go ahead and try to use your default repo.

Or just (b) altogether.  That is, instead of our system picking a default repo, query what the _users_ default repo is.
