### ISSUE TITLE
Changing *any* env_batch.xml variable requires rerunning case.setup

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2259]
The recent locked file support improvement introduced a minor issue - 
changing JOB_QUEUE or JOB_WALLCLOCK_TIME now require rerunning 
case.setup.  This should be a minor inconvenience for most users and its 
kind of a better safe than sorry situation, because not all machines can be 
configured such that these changes do not require running case.setup.

**Comment by billsacks** [comment]
Will rerunning case.setup require you to rerun case.build? If so, I'd say this is more than just a minor inconvenience: In addition to needing to wait for the rebuild (which isn't *too* long, but is long enough to be annoying), it also forces you to wonder if anything has changed in your source tree since you built the case. (This hopefully isn't an issue for production simulations, but for development, I often iteratively create cases as I go: create and build a case, make some changes in my source tree, create and build another case, etc.)

So I'd say: If this just requires rerunning case.setup, I'm fine with it. But if it requires rerunning case.build, then I think it's worth considering if, for example, the scripts could be smarter (or some option could be added) so that, in this particular case, case.setup can be rerun without forcing a rebuild.

**Comment by mnlevy1981** [comment]
I just ran into this issue because I have a script that runs `case.setup` and then uses `xmlchange` to change `JOB_WALLCLOCK_TIME`. Easy enough for me to change my script to run `xmlchange` first, but figured I'd add a comment that this has affected at least one user.

**Comment by jedwards4b** [comment]
@mnlevy you can also change job wallclock time in the call to create_newcase or create_test with the --wallclock option.

**Comment by jgfouca** [comment]
When the user re-runs case.setup, if the only thing that's changed in the case are settings for batch system, then do NOT reset build-complete to false. Use the lock files to know.

**Comment by jgfouca** [comment]
Add --keep-build too to force this behavior.

**Comment by rljacob** [comment]
People don't think about batch settings until right before they submit.  Asking them to do it at create_newcase or case.setup time is not good.

**Comment by jgfouca** [comment]
@rljacob , yes, i think my original comment from a day ago should address the problem. Users will only need to remember to re-run case.setup after xmlchange.

**Comment by rljacob** [comment]
"only need to remember" is much easier said then done.    We already ask users to keep a lot in their head as they move up and down the newcase-setup-build-submit chain.  Now they have to remember "this run of case.setup won't require a rebuild because its only modifying batch commands".  Really?

**Comment by jonbob** [comment]
I second @rljacob's comment

**Comment by jgfouca** [comment]
@rljacob , this change should be transparent to the user. They can still re-run case.build after case.setup if they want, it just won't be required.

**Comment by jgfouca** [comment]
Users should already know they need to regenerate batch submit scripts when they modify batch settings.

**Comment by rljacob** [comment]
How will they "already know" this?

**Comment by jedwards4b** [comment]
They may not already know but they are presented with a clear message:
ERROR: Batch configuration has changed, please run case.setup --reset

**Comment by jgfouca** [comment]
@rljacob because that's CIME's interface and, as far as I know, has been for decades. Maybe @jedwards4b can confirm. I don't believe we or CESG have ever told users to directly modify XML or batch scripts; that violates the principle of coding to interfaces, not implementation.

**Comment by jedwards4b** [comment]
Currently failing to run case.build after case.setup will cause an error when running case.submit.   With this change the user will be able to run case.submit after running case.setup without running case.build in cases that do not require a rebuild.   So they don't need to remember any new information , the system will guide them in the correct direction.

**Comment by billsacks** [comment]
I do share some of @rljacob 's concerns here, though I'm not quite sure what we should do about it - at least in the short-term.

It used to be that most batch settings were made by editing the generated batch submission script. I believe that was still the case as of the last CESM public release. At that point, the main configuration change that required rerunning `case.setup` (called something different then) was changing PE layouts. There was therefore a (somewhat) intuitive ordering:

1. create case

2. change PE layout

3. run setup command

4. change build settings

5. run build command

6. change runtime options and job submission options

7. submit

Now that ordering is messier, particularly with respect to batch submission options.

At least in the longer-term, would it work to separate (a) what needs to happen before the build (changing PE layouts, maybe other things), and (b) what needs to happen before submission - including creating the batch submission file. Then we'd want a new command in between (6) and (7) above.

**Comment by rljacob** [comment]
+1 to what Bill said but in the meantime can we also add a warning message if someone xmlchange's a batch setting?  "WARNING:  changing a batch setting will require running case.setup --reset"

**Comment by jedwards4b** [comment]
I think that the change proposed here is an incremental improvement and the suggestions by @rljacob and @billsacks adding another process step and another message would make things worse not better.

**Comment by rljacob** [comment]
Its better to warn people ahead of time they need to run some other command then to give them a fail message when they do what they think is right.  Of course we should do both to be as user friendly as possible.

**Comment by billsacks** [comment]
Here's another idea, which maybe won't work: Could the case.submit script itself create the necessary batch scripts?

**Comment by jonbob** [comment]
What is driving the change? As a user, I'm very familiar with the process that @billsacks described so well. It seems like there should be a very compelling reason for breaking that ordering

**Comment by rljacob** [comment]
2 things broke it:  requiring all changes through "xmlchange" while keeping the role of case.setup in making the batch script.

**Comment by jgfouca** [comment]
@billsacks that seems like a good idea.

**Comment by jedwards4b** [comment]
@billsacks I think that might work, we need to be careful to only do this when the files are needed - that is I don't think we want to generate those scripts everytime case.submit is run - do we?

**Comment by jgfouca** [comment]
@jedwards4b it might be pretty harmless to generate them every time. case.setup is quite cheap if you can avoid calling preview_namelists.

**Comment by jedwards4b** [comment]
I think that this means the code from line 167 to 177 of case_setup.py becomes a separate subroutine which can then be called from case.submit.

**Comment by jgfouca** [comment]
@jedwards4b , I was thinking along similar lines. I'll add that as part of this ticket.

**Comment by nanr** [comment]
I am getting the same behavior (changing wallclock results in Batch configuration error and case.setup --reset) in the cesm2.0.0 release tag.  (cime_cesm2_0_rel_04)

**Comment by jedwards4b** [comment]
@nanr lets walk through this together, I cannot reproduce.
