### ISSUE TITLE
Problems with new test in cdash test_env_loading

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2262]
I'm seeing lots of issues with the new test, this one for example has two directories which differ only by the final '/'
AssertionError: Value mismatch for key LMOD_DIR: '/glade/u/apps/ch/opt/lmod/7.5.3/lmod/lmod/libexec' != u'/glade/u/apps/ch/opt/lmod/7.5.3/lmod/lmod/libexec/'

**Comment by jgfouca** [comment]
@jedwards4b I knew this kind of thing would happen. If you list all the mismatches, I can try to add more exceptions.

This is going to continue to come up, maybe the best thing is to just limit this test to melvin? Using "generic" mode and "module" mode to validate each other is a powerful test, but very prone to false positives.

**Comment by jgfouca** [comment]
I limited the test to melvin.
