### ISSUE TITLE
Components need post-DA resume signal

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2266]
In order for components to do post-data assimilation state processing, they need a resume signal from the driver during their initialization phase. This 'resume' signal should be set for component `XXX` if the driver XML variable, `DATA_ASSIMILATION_XXX` is `TRUE`.

**Comment by ekluzek** [comment]
Is this done now? This is required for DART to work in CESM right? And it's desired for CESM2.0 right?

**Comment by gold2718** [comment]
That is weird. This issue was fixed by PR #2267 which contains the line:

> Fixes CIME Github issue #2266

Closing it manually now
