### ISSUE TITLE
Can we remove the commit template from the wiki?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2268]
I noticed that the wiki (https://github.com/esmci/cime/wiki/CIME-Git-Workflow#configure-git-one-time) says that you need to use a commit template, but it seems like nobody is doing that. Can I remove the information about the commit template from the wiki?

**Comment by jedwards4b** [comment]
It's a PR template, not required for all commits - yes you can remove that info.

**Comment by billsacks** [comment]
Done.
