### ISSUE TITLE
Remove MODEL entry id from config_files

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#227]
The entry id at the top of config_files for MODEL (acme or cesm) is never checked against env variable CIME_MODEL and is not necessary because the different config_files are already separated by directory.

**Comment by erichlf** [comment]
@rljacob This entry is used within the config_files themselves in the form of $MODEL. Certainly, $MODEL can be hard coded, but it seems like a good idea (for convenience) to leave it as it is.

**Comment by rljacob** [comment]
Ok.
