### ISSUE TITLE
case_st_archive.py:_get_datenames needs to use MULTI_DRIVER

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2275]
@gold2718 @jedwards4b
This issue stems from #2240.
CESM+DART cases will generally be built with the MULTI_DRIVER option,
since it saves a lot of core hours and wall clock.
_get_datenames creates a list of all of the cpl restart files in order to know
how many restart file sets need to be archived.  But  in the M_D cases
there are NINST cpl restart files for each date stamp: cpl_0001.r, ..., 
so the archiver tries to archive NINST*#_dates file sets.
The proposed fix is to pass "case" down to _get_datenames,
query MULTI_DRIVER, and assemble the appropriate list
of restart sets.  I've coded and tested this, and will issue a PR soon,
unless I shouldn't.

**Comment by gold2718** [comment]
Seems reasonable to me.

**Comment by kdraeder** [comment]
This has been superceded by #2285.

**Comment by jedwards4b** [comment]
The issue hasn't been superseded, only the proposed solution has.
