### ISSUE TITLE
query_config no longer works for CESM

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2276]
query_config no longer works for either cime5.4.0-alpha.23 or on master.
Here is the error for cime5.4.0-alpha.23:

[aliceb@cheyenne1:scripts]>./query_config --components clm
Traceback (most recent call last):
  File "./query_config", line 343, in <module>
    _main_func(__doc__)
  File "./query_config", line 336, in _main_func
    query_component(args.components)
  File "./query_config", line 146, in query_component
    if not all_components and not config_exists:
UnboundLocalError: local variable 'config_exists' referenced before assignment
and here is the error from master:

[aliceb@cheyenne6:scripts]>./query_config --component clm
ERROR: locked

**Comment by rljacob** [comment]
So this is a consequence of PR #2269?  Why didn't testing catch it?

**Comment by jgfouca** [comment]
@rljacob because of differences between ACME and CESM.
