### ISSUE TITLE
"ERROR: locked" when .config_files.xml is present in SRCROOT

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2280]
If a `.config_files.xml` file is present in `SRCROOT` (as is the case for a standalone CTSM checkout), I'm getting `ERROR: locked` when trying to create a case from cime master:

```
git clone git@github.com:ESCOMP/ctsm.git
cd ctsm
./manage_externals/checkout_externals
cd cime
git remote add esmci git@github.com:ESMCI/cime.git
git fetch esmci
git checkout esmci/master
cd scripts
./create_newcase --case test_0207a --compset A --res f19_g16_rx1
```

This gives:

```
ERROR: locked
```

If I remove `.config_files.xml` from the top-level ctsm directory, this works.

@jedwards4b @jgfouca @ekluzek @bandre-ucar

**Comment by jedwards4b** [comment]
Please try the current cime master, I believe I've already fixed this.

**Comment by jedwards4b** [comment]
Also in future issues please indicate what version of cime you are using.

**Comment by billsacks** [comment]
Sorry for that omission. I'm using 877250bd2, which is the latest version of master on esmci.
