### ISSUE TITLE
CPL_USER_MODS match for b1850 is too general

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2282]
c8c758224a introduced this in `config_component_cesm.xml`:

```xml
  <entry id="CPL_USER_MODS">
    <type>char</type>
    <valid_values></valid_values>
    <default_value></default_value>
    <values match="last">
      <value compset="1850_">$SRCROOT/cime_config/usermods_dirs/b1850</value>
    </values>
    <group>run_component_cpl</group>
    <file>env_case.xml</file>
    <desc>User mods to apply to specific compset matches. </desc>
  </entry>
```

But matching on compset="1850_" is too general: This matches non-B compsets (e.g., I compsets). For a standalone ctsm checkout, this raises an error because `$SRCROOT/cime_config` doesn't exist. For other configurations, I'm not sure this is working as intended - e.g., is this supposed to be included in an I1850 compset?

@jedwards4b I'm not sure exactly what's intended here.

**Comment by jedwards4b** [comment]
This is just adding the orbital info for 1850, it should be a default and not set via user mods as it is here.

**Comment by billsacks** [comment]
Do you know what the correct behavior here is? It seems like changing this to year 1850 for all year-1850 compsets would change answers for non-B compsets... intuitively, that seems like the right thing to do, but it makes me wonder why it hasn't been done in the past.

**Comment by ekluzek** [comment]
Dave Lawrence just approved this change from the CLM angle for I compsets.

"I think this is fine. Should be negligible impact. "

**Comment by rljacob** [comment]
Are the orbital params that get used in the output somewhere?

**Comment by jedwards4b** [comment]
Yes, they are output in the cpl.log in lines beginning with (shr_orb_params)

**Comment by rljacob** [comment]
Without the usermod or the change in 2283, what is having "1850" in the compset do for you?

**Comment by jedwards4b** [comment]
Nothing.

**Comment by jedwards4b** [comment]
Sorry that isn't true.  In the driver it determines what boundary files are selected, components may also set parameters based on the 1850 date in the compset.

**Comment by billsacks** [comment]
For example, CLM selects different datasets based on the year, and I imagine this affects CAM in many ways (CO2, aerosols, etc.) though don't know the details off-hand.
