### ISSUE TITLE
Unsupported option in testlist schema

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2284]
We have cases in CAM where we create tests to protect new functionality which is not ready for prime time. We would like these tests run regularly which is easiest if they are in aux_cam. However, currently, that makes that compset / resolution combination 'supported' for `create_newcase`.

I propose a new `attribute` in the `test` element in testlist.xsd:
```
<xs:attribute name="supported" use="optional" type="xs:boolean" default="true"/>
```
I am fine with leaving off the `use="optional"` property if that is not standard usage in CIME.

Adding a new, optional argument to Testlist.get_tests (`supported_only=False`) which would trigger culling of those tests which have an `supported=false` attribute.
@jedwards4b, @jgfouca: thoughts?

**Comment by jedwards4b** [comment]
Should functionality which is not ready for primetime be included in the cesm2 release?   
If not then I would suggest waiting until after the release and since there has been clambering to 
reconsider the testlist format this should be included in that task.

**Comment by gold2718** [comment]
Some might argue that CAM is not ready for primetime :)
However, another use case is that we have a refined mesh test with a test grid which **should not be used** (it was created just to be able to run fast tests). We really do _not_ want to support that resolution but we need to test the refined mesh functionality as a CAM regression test.

**Comment by jgfouca** [comment]
I can't give guidance since E3SM doesn't use testlists.

**Comment by jedwards4b** [comment]
I don't have any objection to adding this and the optional argument is fine.
