### ISSUE TITLE
MODEL_VERSION doesn't get set correctly for non CESM checkouts...

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2289]
For cesm MODEL_VERSION gets set by reading in the ChangeLog at the top of SRCROOT as follows in case.py. This is with the latest master.

```
    def set_model_version(self, model):
        version = "unknown"
        srcroot = self.get_value("SRCROOT")
        if model == "cesm":
            changelog = os.path.join(srcroot,"ChangeLog")
            if os.path.isfile(changelog):
                for line in open(changelog, "r"):
                    m = re.search("Tag name: (cesm.*)$", line)
                    if m is not None:
                        version = m.group(1)
                        break
```
This logic requires that ChangeLog exist at the top of SRCROOT, and that the tag name start with cesm. Neither of these things are true for CLM checkouts. Nor would be true for a CAM checkout.

This problem doesn't happen for acme since they use get_current_commit from utils.py, which fills the value with the SHA1 using a git command (git rev-parse HEAD). For acme, they also save a bunch of provenance information including the value from "git describe".

Since, cesm has now moved over to git, could we have MODEL_VERSION for cesm set by "git describe" of SRCROOT rather than the ChangeLog file? 'git describe' is nice since it gets you the most recent tagname plus part of the SHA from any commits since that tag. For example, 'git describe' on current master of cesm gives you "cesm2_0_alpha09a".

@billsacks @bandre-ucar @gold2718 @cacraigucar

**Comment by ekluzek** [comment]
We talked about this at the cseg meeting this morning and @jedwards4b agreed to take this on. Both in the sense of have cesm do something closer to acme, and making sure MODEL_VERSION is set in a way that would work for CESM, CLM, and CAM.

**Comment by jedwards4b** [comment]
I believe that we can use the --status flag from checkout_externals to do this and will work on this approach.
