### ISSUE TITLE
When should we increment version numbers?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2291]
CIME has X.Y.Z version numbers (MAJOR.MINOR.PATCH).  After the release of 6.0.0, can we come up with rules for incrementing those numbers?

semver.org has some rules:

- Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
- Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.
- Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

A related question:  Can we define CIME's "public API"?

**Comment by jgfouca** [comment]
@rljacob , I'm fine with this as long as this only applies to releases. IE, I don't have to remember to update the version every time I make a PR.

**Comment by rljacob** [comment]
You would have to be aware of if your PR triggers one of the conditions to increase X, Y or Z.

**Comment by jgfouca** [comment]
@rljacob , we'd be on cime version 99.999.9999 . That's an exaggeration, but we've had at least a dozen major X change PRs, many dozens of Y changes, and hundreds of Z changes in the last few months.

**Comment by rljacob** [comment]
That means we were still in "version 0 mode" 

> Major version zero is all about rapid development. If you’re changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version.

(which is why I wanted to start released versions at "1".)  If if looks like we're still doing that kind of development even after a "release", then we're not ready to do any kind of rational x.y.z versioning.

**Comment by jgfouca** [comment]
@rljacob , that makes sense. Maybe we can consider the current master to be the development branch? I don't think CIME/master will be stable-enough for semantic versioning for a couple more years.

**Comment by rljacob** [comment]
Reopening this because having second thoughts about switching to 6.0 with our first frozen version.

I'd like to instead just stop doing "alpha" tags as discussed in in our Feb 14 meeting notes
https://github.com/ESMCI/cime/wiki/Meeting-Notes

We're currently doing 5.4.0-alpha tags.  When we have a version for release in E3SM,  let's call that 5.5.0 and stop using alpha tags.

I want to save the switch to 6.0 for when we make a major change, not just start doing maintenance branches.

**Comment by mvertens** [comment]
Lets talk about this today. I'd really like to have a clean 6.0 for the
CESM2 release. I think it would be much better than an incremental version.

**Comment by jgfouca** [comment]
We've already agreed to a versioning system.
