### ISSUE TITLE
ACME and CIME4 grid configs are not compatible

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#23]
cime_config/acme/config_grids.xml
and
cime_config/cesm/config_grids.xml
... are not in the same format. The changes made on the ACME side will need to be examined and converted to the new format.

**Comment by jgfouca** [comment]
@jedwards4b , did you make a script to do the change in format of config_grids.xml? I'd like to use it if you can track it down.

**Comment by rljacob** [comment]
ACME's additions to config_grid are for MPAS, RRM and a few single point CLM grids.  Might be best to just use the CIME4 version for now (for drv test cases) and add back our changes later.

**Comment by jgfouca** [comment]
@rljacob , I'm trying to do that. It's just a little unclear what the exact conversion should be. I could punt as you suggest. If they have a script, that would help too. I don't believe they changed all these thousands of lines of XML by hand.

**Comment by jgfouca** [comment]
@rljacob , I've figured out the conversion and fortunately, there haven't been too many commits to our side.
