### ISSUE TITLE
inputdata repository reform

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2301]
Add an xml file just for information about the available inputdata repositories,  remote address and access method, thus allowing for multiple repositories as described in file cime/config/$model/machines/config_inputdata.xml 
This would first give us an editable list of potential inputdata servers and allow us to configure the input method - initial methods are subversion, grid ftp, ftp, scp?  
Add an interface method for this file in CIME/XML/config_inputdata.py 
and methods in lib/CIME/check_input_data.py

**Comment by rljacob** [comment]
Cool.  I was just asking on slack if ftp was an option.  Does anyone remember why data files are served with svn instead of ftp?

**Comment by mvertens** [comment]
This is an excellent addition. Thanks for taking the initiative to put this
in.

**Comment by rljacob** [comment]
Can you add wget as a protocol too?

**Comment by rljacob** [comment]
@jgfouca we are probably NOT going to use svn to serve the E3SM data to the public.  ftp and wget are being looked at for options.

**Comment by jedwards4b** [comment]
In pr #2309 I have made allowance to support any number of new protocals - we are looking at grid-ftp and ftp.
