### ISSUE TITLE
CESM's config_component_cesm.xml changed in last merge from ACME

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2302]
Among the 1785 changed files in a recent merge from ACME (commit 
87e0b1db78bc4f8fbaef289435772dc3556567d0) is src/drivers/mct/cime_config/config_component_cesm.xml

This has broken lots of default values (e.g., `ATM_NCPL`) which of course cost time to track down.

Why is ACME modifying CESM configuration files? Can someone please fix this?

**Comment by mvertens** [comment]
I agree. I am surprised that this did not get addressed in the PR. We need
to fix this as soon as possible - since its a show stopper for the release.
I am reassigning this to @jedwards4b.

**Comment by rljacob** [comment]
The last merge from ACME was https://github.com/ESMCI/cime/pull/2264 which only has 17 changed files.

**Comment by jedwards4b** [comment]
This is a misinterpretation due to the problems with the merge and git blame.   Acme did not change this file.

**Comment by rljacob** [comment]
See issue https://github.com/ESMCI/cime/issues/2177

**Comment by billsacks** [comment]
And specifically see https://github.com/ESMCI/cime/issues/2177#issuecomment-354893661

**Comment by gold2718** [comment]
Git blame shows @worleyph for commit 87e0b1db78bc4f8fbaef289435772dc3556567d0
The file is correct as of the previous commit (586b1762c401cf00114322fe3dce9005dcf60f00) from 2017-10-02.
If ACME did not change the file, how did it get changed?

**Comment by jgfouca** [comment]
@gold2718 : 

```
% git log -p src/drivers/mct/cime_config/config_component_cesm.xml
```

^ Shows no recent changes to this file.

**Comment by rljacob** [comment]
@gold2718 you really need to read #2177.  You can't trust "git blame" anymore.

**Comment by jgfouca** [comment]
Git blame should become trustworthy again over time, but we severely broke it due to the way we were doing updates from E3SM. This has since been address, but the blames will be broken for a while since we didn't go back and repair history. I generally find "git log -p" to be more useful than blame in most cases anyway.

**Comment by gold2718** [comment]
Sorry everybody, it looks like the tree is okay at the moment (reporter's sandbox was out of date).
Thanks to @billsacks for stepping me though the labyrinth of the git merge fiasco.
Sorry to everyone for the unnecessary panic.

**Comment by billsacks** [comment]
> I generally find "git log -p" to be more useful than blame in most cases anyway.

For the record, `git log -p` also seems broken by the acme merges.

**Comment by jgfouca** [comment]
@billsacks , oh, that's not good.

**Comment by billsacks** [comment]
@jgfouca an example is the case in question: `git log src/drivers/mct/cime_config/config_component_cesm.xml` does not show f073fa50e. You need to do `git log 9dfce922134be23a0aead8143c23bd3336725fd8^ src/drivers/mct/cime_config/config_component_cesm.xml` for that commit to show up.

**Comment by jgfouca** [comment]
@billsacks , so did the new squash-based process fail us?

**Comment by billsacks** [comment]
@jgfouca As far as I know, the new squash-based process worked. The problems here are carry-overs from the previous two (?) merges. However, I do still feel it would be great if you could pursue an alternative scripting strategy to make it less likely for this problem to reappear in the future, as discussed in #2177 .
