### ISSUE TITLE
xs:boolean types read as string using XML get

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2322]
When using `self.get(node, attribute)`, an xs:boolean attribute is returned as a string. Python treats this as True when used as a boolean which is not what is meant by `attribute="false"`

An example of this error is line 69 of namelist_definition.py but there may be other cases where xs:boolean XML attributes are being treated as boolean in Python (line 79 of testlist.py was recently introduced). These codes should be found and fixed (maybe a more general fix for reading xs:boolean using get?).

**Comment by jedwards4b** [comment]
There were two variables in that file that had this problem.  I looked through all other attributes declared as bool in the xsd files and didn't find any other problems.
