### ISSUE TITLE
Request: Better documentation of TIMER_DETAIL, TIMER_LEVEL

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2329]
I can never remember how to get more detailed timing information out of the model. I think it has something to do with `TIMER_DETAIL` and `TIMER_LEVEL`, but the documentation of these xml variables doesn't really help: the documentation for both says, `timer output depth`. The description of the corresponding drv namelist variables, `profile_depth_limit` and `profile_detail_limit` is empty.

Can someone please add more documentation for these variables?

**Comment by mvertens** [comment]
Can you raise an issue about adding this in the documentation. @jedwards4b
and I are having a documentation session on Monday - and it would be good
to address this during that time.

**Comment by rljacob** [comment]
Documentation session?

**Comment by mvertens** [comment]
Yes! Jim and I are scheduled to do this on Monday from 2:30 - 4:30. Want to
join?

**Comment by rljacob** [comment]
Sure!

**Comment by bertinia** [comment]
if this is going to be a more open general documentation session, will it be on gotomeeting or google handouts?

**Comment by rljacob** [comment]
So TIMER_DETAIL, for example, has to be described in 2 places?  config_component_cesm.xml and config_component_e3sm.xml?   The description seems unlikely to change between the two.

**Comment by rljacob** [comment]
I said that wrong:  one description is all that's needed but if it has to be in 2 places its highly likely they'll get out of sync and one will lag.
