### ISSUE TITLE
Duplicate travis-ci builds

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2331]
It looks like there are two sets of identical travis-ci builds for every PR: one for the pr and one for the push.

Digging into this a bit, I think it's because we have both "build pushed branches" and "build pushed pull requests" turned on: see the "double builds" documentation here:

https://docs.travis-ci.com/user/pull-requests/#%E2%80%98Double-builds%E2%80%99-on-pull-requests

My understanding is that we definitely want "build pushed pull requests", but probably not "build pushed branches": I think the latter means that a travis-ci build is kicked off whenever anyone pushes any branch to esmci/cime.

(More documentation: https://docs.travis-ci.com/user/web-ui/#build-pushed-pull-requests and https://docs.travis-ci.com/user/pull-requests/

@jedwards4b do you agree with this?

**Comment by billsacks** [comment]
Indeed, I have confirmed that the travis-ci build is being kicked off for all branches pushed to ESMCI, even those not attached to a PR.

**Comment by jedwards4b** [comment]
@billsacks I have changed this setting in the web interface, thanks.

**Comment by billsacks** [comment]
Thanks. I'm just doing some testing now to make sure it still works for a PR. I'll also make a change to the travis yml file so that it still does do a build whenever we push master, since that seems useful.

**Comment by billsacks** [comment]
Okay, I've confirmed that, with the new settings, a Travis-CI build is still triggered when the PR is submitted and whenever the PR's branch is re-pushed. (See #2332)

**Comment by billsacks** [comment]
Incidentally: If we switch to a fork-based workflow, where the only branches on ESMCI are "important" ones, then I could imagine re-enabling this "build pushed branches" option, at which point #2333 could be reverted.
