### ISSUE TITLE
case_st_archive.py and env_archive.xml regexes in the context of DART

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2334]
@jedwards4b @gold2718 @mvertens 

Some of the discussion in #2308 about changing regular expressions
in st_archive may be relevant to this issue.

While developing the ability to st_archive the files
created by DART, it was difficult to understand how
to use env_archive.xml.  (I have since stumbled across
www.cesm.ucar.edu/models/cesm2.0/cesm/env_archive.html,
but others might not find it, since there's no link to it
that I can find.)
There are several related issues.
1) The use of regular expression metacharacters
   makes it harder to understand.  There are no
   comments to note that they are python regexes.
   There's not enough context in the env_archive.xml
   file to understand what they need to do.
2) The inconsistency between the need for '.' separators
   in the <rest_file_extension> 'suffixes' but not
   in the <hist_file_extension> 'suffixes' because
   _archive_history_files inserts them
   (or tries to; see item 3).
3) Quite a few regular expressions that *are* in
   case_st_archive.py seem to not do quite what was
   intended.  They worked in many cases, but not as
   robustly or selectively as they should.
   These mostly involved combinations of ., \., \d and *.

I've modified scripts and xml files to move many
of the metacharacters out of env_archive.xml and
into case_st_archive.xml.
To see how this cleans up env_batch.xml, first look at
   config/config_headers.xml     (additional header comments for users)
   config/cesm/config_archive.xml
   src/drivers/mct/cime_config/config_archive.xml
   src/components/data_comps/docn/cime_config/config_archive.xml
Then look at case_st_archive.py.

I've attached a tar file of a representative CAM+POP+DART $rundir
if someone wants it for testing st_archive.  The files in it are just
placeholders, so it can be copied fast.
[CAM+POP+DART_run.gztar.zip](https://github.com/ESMCI/cime/files/1772851/CAM.POP.DART_run.gztar.zip)

**Comment by Chakosai** [comment]
Edi
