### ISSUE TITLE
Remove scripts/Tools/pointclm

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2337]
The code in scripts/Tools/pointclm used to be in the old scripts-acme directory.   ACME long ago moved it to its clm directory and the code here is no longer developed.

**Comment by rljacob** [comment]
I'm pretty sure CESM isn't using this particular version either.  @billsacks ?

**Comment by ekluzek** [comment]
@rljacob I was wondering about that code as well. CLM people certainly do not use it, and I doubt they know of it's existence.

**Comment by billsacks** [comment]
@rljacob - I agree with @ekluzek
