### ISSUE TITLE
Document setting job dependencies and batch system control

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2342]
Some questions this documentation should answer:

How to change the wallclock time and submit a chain of dependent runs?

Why does CIME  auto regenerate batch scripts when env_batch is edited?

**Comment by rljacob** [comment]
Marking this as "critical" since its easily the biggest source of questions/complaints I hear about CIME.

**Comment by jonbob** [comment]
I get complaints from users here almost everyday about this. Who requested this change? And why wasn't anyone asked? It is part of why CIME has such a bad reputation in other parts of the project

**Comment by jedwards4b** [comment]
The submitted jobs are not intended to be edited by users and alternative mechanisms exist to change the characteristics of those scripts.   If one wants to change add to or delete lines of the batch directives or change the mpirun command they would do that in the env_batch.xml file.  If one wants to add code to be run either before or after the model run they would set the PRERUN_SCRIPT or POSTRUN_SCRIPT xml variables to point to the additional code they wish to run.

**Comment by jedwards4b** [comment]
To change wallclock time one would xmlchange JOB_WALLCLOCK_TIME, they can also use the command line option --walltime to create_newcase or create_test
There are a couple of ways to issue a chain of runs, the primary mechanism is through the RESUBMIT variable which will submit the next job when the previous job is completed.   On some HPC systems it is desirable to submit dependent jobs right away instead, one can do this using case.submit --prereq ### where ### is the jobid of the job which should complete prior to starting the new job.

**Comment by ndkeen** [comment]
This is something I did a lot, which is to pass some flags directly to the batch system.  What flags work and what they do will be dependent on the batch system (maybe man sbatch).

`case.submit --batch-args="--mail-type=ALL --mail-user=ndkeen@lbl.gov --dependency=afterany:8694275 -t 1380 -J jobname"`

The `-t` is how you would change the wallclock time -- an integer will be interpreted as minutes.  The dependency is pointing to an existing jobid. This example just shows all of the things I did frequently, but not all are required, of course.

@jedwards4b : I did not know about PRERUN and POSTRUN. I should try that because that could help me with certain tasks.  It will will not help me do everything I need, but it's nice to know about.

**Comment by jonbob** [comment]
Has any of this been communicated to users? Or did anyone bother to ask?

**Comment by rljacob** [comment]
@jonbob what change are you referring to?  This is a thread about documentation.   The change I'm requesting is to add more.

**Comment by jedwards4b** [comment]
@ndkeen demonstrates that there is more than one way to do it, all of these changes could be made in env_batch.xml or with different arguments to the case.submit script

**Comment by jonbob** [comment]
@rljacob - sorry, I couldn't agree more about documentation. But it also feels like these changes were implemented without much prior communication or buy-in.

**Comment by jgfouca** [comment]
@jonbob what do you mean by "these changes"? The only recent change related to batch systems was getting rid of the lockfile error for env_batch.xml and instead regenerating this file automatically if env_batch.xml was changed. I thought this change was specifically requested by you and Noel.

**Comment by jonbob** [comment]
@jgfouca - OK, my bad. I'm just referring to the change that you're now fixing. So I apologize.

**Comment by jgfouca** [comment]
@jonbob , that fix should already be in es3m master.

**Comment by jonbob** [comment]
Thanks

**Comment by jgfouca** [comment]
@jonbob , @ndkeen , please continue to vocalize any common user complaints about CIME. I personally use CIME in a very uncommon way (almost always through create_test), and @jedwards4b has good knowledge of create_newcase flags and xmlchange to achieve what he wants. Without you guys, we would have no way of knowing that things aren't good.

**Comment by jonbob** [comment]
Thanks for understanding, @jgfouca. So many people on E3SM use CIME in so many different ways -- create_newcase, create_test, and run_e3sm. So any changes affect us in different ways, especially when we weren't aware of them...

**Comment by rljacob** [comment]
@ndkeen what documentation do you think is missing for controlling the batch system?

**Comment by ndkeen** [comment]
Well I'm not so sure the documentation is at fault, I just think we should be doing it differently.

**Comment by jgfouca** [comment]
@ndkeen can you be more specific? What usecases are giving you problems?

**Comment by ndkeen** [comment]
To use various profilers, machine-specific tools, machine-specific hardware, it is often assumed that you can edit you batch script to do what you want.  And we can't.  
We also do work on the compute nodes that is not needed.
What we need is a very simple batch script that contains directives and ONLY a handful of lines: prerun script, srun, postrun, for example.

**Comment by jgfouca** [comment]
@ndkeen , I would think that those would be supported with either pre/postrun scripts or customizations of MPI_RUN_COMMAND.

**Comment by rljacob** [comment]
CIME has all the machinery to output a simple bash script that people can edit to their hearts content and submit themselves.  Why not implement that?  Yes its not the recommended workflow, use at your own risk, etc.

**Comment by ndkeen** [comment]
That could work, but I'd need to see an example.

**Comment by jgfouca** [comment]
@rljacob , are you sure? It actually sounds difficult to me seeing how integral python is to the operation of CIME.

@ndkeen ,  I could try to provide an example but I'd need you to be as specific as possible of what it is you want to do. You could start with a hypothetical bash script.

**Comment by jedwards4b** [comment]
This is already entirely possible.   The batch scripts are created from templates which are named in the file env_batch.xml in the fields:
<entry id="template" value="template.case.run">
These templates are located in the config/$model/machines directory
If one wants to replace the case.run script with a simple template they need only replace the value in this line in env_batch.xml with a pointer to their own template file.

**Comment by jedwards4b** [comment]
But I think that the user needs to understand that if they are replacing that template they cannot expect to get support from the developers if their replacement template doesn't work.

**Comment by rljacob** [comment]
@jedwards4b that sounds promising and I think many users would be willing to make that trade.

Still not quite sure how just replacing the template would work.  I still want CIME to use what it knows to put in the #BSUB lines and the actual mpirun command.  I don't think even an advanced CIME user could write a template that would result in a simple bash script.

**Comment by jedwards4b** [comment]
I disagree that "many users" would make this change - it should be limited to a few advanced users like @ndkeen who know what they are doing and who are knowingly sacrificing cime functionality for personal convenience.   They will lose much of the functionality of cime and so they should definitely not consider using a script like this for production use.   If e3sm in general feels strongly that the current approach is incorrect then you can reinvent that wheel in bash.

**Comment by jedwards4b** [comment]
@ndkeen How can it not do what you would like to do when you can write a template to do anything at all.   We are making every effort to accommodate your requests but you don't seem to provide any information other than that you don't like what is currently being done.

**Comment by rljacob** [comment]
@ndkeen it would help if you made a gist with the run script you wish you had.

**Comment by ndkeen** [comment]
How about, for example, being able to add lines just before/after the mpirun command?

**Comment by rljacob** [comment]
Such as?

**Comment by ndkeen** [comment]
Whatever I want to do?

**Comment by rljacob** [comment]
How do the user-definable postrun and prerun script options not do what you want?

**Comment by ndkeen** [comment]
Yea I was noting the issues here: https://github.com/ESMCI/cime/issues/2360

I think would would be good is to have scripts that do what CIME wants, but have them packaged and callable from the batch file.  So the batch file _could_ be _something_ like:

1) directives
2) cime_setup_env.py
3) cime_do_an_enormous_amount_of_stuff_prerun.py
4) mpirun command
5) cime_do_an_enormous_amount_of_stuff_postrun.py

So then I can choose to 
a) add things in between
b) comment out 3 and 5

**Comment by jedwards4b** [comment]
```
!#/usr/bin/env bash
{{ batch_directives }} 
cd {{ caseroot }}
source .env_mach_specific.sh 
```
you get the idea?

**Comment by ndkeen** [comment]
Those aren't the pieces I'm missing.

**Comment by billsacks** [comment]
Can someone summarize the outstanding requests here?

@jedwards4b should this be flagged with the cesm2 milestone?
