### ISSUE TITLE
namelist comparison test doesn't recognize a new variable in marbl_in

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2343]
I don't know if this is an issue with the namelist comparison test, or if this is a result of the fact that `marbl_in` is not a Fortran namelist (it contains `foo = bar` lines but does not have the `&[namelist name]` line at the top or the `/` at the bottom), but when we add `particulate_flux_ref_depth` to the file, instead of noting the additional line it produces a whole flurry of inequivalent line messages:

```
Inequivalent lines PON_bury_coeff = 0.5 != particulate_flux_ref_depth = 100
  NORMALIZED: PON_bury_coeff = 0.5 != particulate_flux_ref_depth = 100
Inequivalent lines parm_init_POC_bury_coeff = 1.1 != PON_bury_coeff = 0.5
  NORMALIZED: parm_init_POC_bury_coeff = 1.1 != PON_bury_coeff = 0.5
Inequivalent lines parm_init_POP_bury_coeff = 1.1 != parm_init_POC_bury_coeff = 1.1
  NORMALIZED: parm_init_POP_bury_coeff = 1.1 != parm_init_POC_bury_coeff = 1.1
Inequivalent lines parm_init_bSi_bury_coeff = 1.0 != parm_init_POP_bury_coeff = 1.1
  NORMALIZED: parm_init_bSi_bury_coeff = 1.0 != parm_init_POP_bury_coeff = 1.1
Inequivalent lines parm_CaCO3_diss =   5.0000000000000000e+04 != parm_init_bSi_bury_coeff = 1.0
  NORMALIZED: parm_CaCO3_diss =   5.0000000000000000e+04 != parm_init_bSi_bury_coeff = 1.0
[cut for brevity]
Inequivalent lines tracer_restore_vars(44) = '' != tracer_restore_vars(43) = ''
  NORMALIZED: tracer_restore_vars(44) = '' != tracer_restore_vars(43) = ''
Inequivalent lines tracer_restore_vars(45) = '' != tracer_restore_vars(44) = ''
  NORMALIZED: tracer_restore_vars(45) = '' != tracer_restore_vars(44) = ''
Inequivalent lines tracer_restore_vars(46) = '' != tracer_restore_vars(45) = ''
  NORMALIZED: tracer_restore_vars(46) = '' != tracer_restore_vars(45) = ''
Found extra lines
tracer_restore_vars(46) = ""
```

**Comment by jedwards4b** [comment]
This is because marbl is not a fortran namelist.

**Comment by mnlevy1981** [comment]
Is this going to be marked "won't fix" or is it possible to update the namelist comparison to treat non-namelist files as if the contents are all a single namelist?

**Comment by jedwards4b** [comment]
I think it can be fixed but I'll need to look into it.  I know that you have some novel data structures in this namelist and the example you've provided is a pretty simple case.   Do you want to provide a more extreme example?

**Comment by mnlevy1981** [comment]
I think from a comparison point of view, the file is fairly simple so I'm not sure what a more extreme example would look like. Variables are listed alphabetically by group, which are marked via Fortran-esque comments:

```
! config PFTs
PFT_defaults = "CESM2"
autotroph_cnt = 3
max_grazer_prey_cnt = 3
zooplankton_cnt = 1

! config flags
ciso_lecovars_full_depth_tavg = .false.
ciso_lsource_sink = .true.
ciso_on = .true.
ladjust_bury_coeff = .false.
lcompute_nhx_surface_emis = .true.
lecovars_full_depth_tavg = .false.
lflux_gas_co2 = .true.
lflux_gas_o2 = .true.
lsource_sink = .true.
lvariable_PtoC = .true.
```

Every array element is explicitly declared (such as `tracer_restore_vars(46)`), and if we add additional tracers that specific array will get longer. We also have some MARBL-specific data-structures leading to file entries such as `grazing(1,1)%auto_ind(1) = 1` (which may get moved to `zooplankton(1)%grazing(1)%auto_ind(1)` down the line); for that I'd be happy with reporting the former as no longer being in the file while the latter are reported as new lines... not need to recognize the variable name change.
