### ISSUE TITLE
Need a better error message for wrong test suite

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2348]
When trying to run create_test on suite that doesn't exit, the error message is not obvious.
" ./create_test blah_blah
ERROR: Could not fill-out test name, partial string 'blah_blah' had no grid information and you did not provide any
Exit 1"

Shouldn't this be more direct like "test suite blah_blah not found" ?

**Comment by jgfouca** [comment]
@rljacob how do we know it was intended to be a test suite?

**Comment by rljacob** [comment]
Don't you already have a way to distinguish between running a specific test that starts with SMS, ERS, etc.  and a test suite?

**Comment by jgfouca** [comment]
@rljacob , no. create_test accepts N arguments, any of which can be a test-suite or individual test. If the argument given is not a known test suite, it's assumed to be an individual test case.

**Comment by rljacob** [comment]
Do you think the error message is just fine the way it is?

**Comment by jgfouca** [comment]
@rljacob , let me see if I can make it a bit better.

**Comment by rljacob** [comment]
This isn't a high priority item.
