### ISSUE TITLE
Add the gfdl fms library into externals 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2349]
https://github.com/NOAA-GFDL/FMS/ 
Needed for MOM ocean and FV3 ATM

**Comment by rljacob** [comment]
That adds 150 files and 140K lines of code.  It will be the biggest external by loc.  Can it just be installed outside of cime like netcdf, mpi?

**Comment by gold2718** [comment]
I think that we should have some discussion on whether this belongs in CIME before taking action.
For CESM, this can easily be managed as an external in Externals.cfg.

**Comment by jedwards4b** [comment]
@gold2718 good idea - that may be a better approach.

**Comment by jedwards4b** [comment]
Moved to https://github.com/ESCOMP/cesm/issues/29
