### ISSUE TITLE
Using PRE and POSTRUN scripts

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2360]
When in the flow do the pre and post scripts execute? Do they happen on the compute node? Would they would be just before/after the "srun" command?

And where should the pre and postrun scripts be?  Apparently they need to be in bash?  I see `/bin/sh` executing them.

If I put them in case directory, and then do:

```
./xmlchange PRERUN_SCRIPT="../prerun_script.sh"
./xmlchange POSTRUN_SCRIPT="../postrun_script.sh"
```

I get:
```
cori10% cat SMS.ne4_ne4.m71-mar12.intel.mpt.n001p0048t48x1.BB.run.10937713 
ERROR: External script ../prerun_script.sh not found
```

If instead I try 

```
./xmlchange PRERUN_SCRIPT="./prerun_script.sh"
./xmlchange POSTRUN_SCRIPT="./postrun_script.sh"
```
That seems to go further, however, the contents of 
` prerun.external.log.10937953.180313-170053` (which is written in the run directory) does not have what I would expect, so I'm no longer sure when the scripts are executed.

Also, is it really necessary to make the script executable if it's being called with a `/bin/sh`?
```
 failed with error '/bin/sh: ./prerun_script.sh: Permission denied' 
```
I had to change the permissions.

**Comment by ndkeen** [comment]
Looking at the output, I see `   Running ./prerun_script.sh ` as well postrun.  And it looks like the prerun script is done before a lot of other things happen.  What I need is something that happens just before srun.

`PREMPIRUN_SCRIPT` and `POSTMPIRUN_SCRIPT` ?

**Comment by jedwards4b** [comment]
They do happen on the compute nodes and they do happen pretty close to just before and after srun, but we need to re-read xml files after running each of the scripts since they could have changed values in those files which would cause them to be out of sync with the case object in memory.
I suggest that @ndkeen should use my suggestion of a custom script - see https://github.com/ESMCI/cime/issues/2342#issuecomment-372858197

**Comment by rljacob** [comment]
@jedwards4b I tried using PRERUN_SCRIPT to set up some environment variables for the Extrae tracer.  It looked like this:
```
#!/bin/bash
echo "Running EXTRAE setup"
source /soft/climate/bsctools/extrae/3.5.2-mvapich2-2.2-intel-17.0.0-acme/etc/extrae.sh

export EXTRAE_CONFIG_FILE=/home/jacob/extrae.xml
export LD_PRELOAD=${EXTRAE_HOME}/lib/libmpitracef.so # For Fortran apps
```
It was executed because the echo shows up in prerun.external.log but the changes to the environment were forgotten by the time the mpiexec command ran.  I verified this should work while running interactively.

**Comment by jedwards4b** [comment]
You should add environment variables to the env_mach_specific.xml not a prerun_script.

**Comment by rljacob** [comment]
ah!  Thanks.   There are several <environment_variables> blocks.  Does it matter which one I add them to?

**Comment by jedwards4b** [comment]
It shouldn't as long as the attributes match your needs.

**Comment by rljacob** [comment]
Hang on, the first line in that script "source /soft/climate/bsctools/extrae/3.5.2-mvapich2-2.2-intel-17.0.0-acme/etc/extrae.sh" sets a bunch of other variables that I'd rather not add one-at-time to env_mach_specifc.xml.

**Comment by jedwards4b** [comment]
The issue with trying to do it in a prerun script is that that script is launched in a subprocess and so anything sourced from there is lost when you return to the parent process.    You may be able to get around this by formatting the script as a python subroutine.  If the script and the subroutine have the same name (eg callme.py contains subroutine callme(caseroot)) then it will be called as a subroutine and not a subprocess.

**Comment by jedwards4b** [comment]
But why, if these are commands needed for a particular soft env, are they in a script and not a soft module?

**Comment by rljacob** [comment]
We're testing that this works at all.  We could ask systems to make it a softkey after we're done.
