### ISSUE TITLE
Possible hang on slow processors

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#2363]
Getting these stack-traces repeatably (twice) on abort after a wall-clock timeout on Theta (KNL nodes):
```
[Task A]
Source:Line                  Call
shr_mpi_mod.F90:568          call MPI_BCAST(vec,lsize,MPI_LOGICAL,lpebcast,comm,ierr)
seq_infodata_mod.F90:2586    call shr_mpi_bcast(infodata%atm_present,        mpicom, pebcast=cplpe)
cime_comp_mod.F90:1300       if (iamin_CPLALLOCNID) call seq_infodata_exchange(infodata,CPLALLOCNID,'cpl2ocn_init')
cime_driver.F90:92           call cime_init()

[Task B]
m_Rearranger.F90:1218        call MPI_WAITANY(RecvRout%nprocs,recv_ireqs,proc,recv_istatus,ier)
cplcomp_exchange_mod.F90:273 call mct_rearr_rearrange(dom_s%data, dom_d%data, mapper%rearr, tag=ltag, VECTOR=mct_usevector, ALLTOALL=mct_usealltoall)
component_mod.F90:405        call seq_map_map_exchange(comp(1), flow='c2x', dom_flag=.true., msgtag=comp(1)%cplcompid*100+1*10+1)
cime_comp_mod.F90:1225       call component_init_cx(ocn, infodata)
cime_driver.F90:92

[Task C]
cplcomp_exchange_mod.F90:544 call mpi_allreduce(mranko,mrankog,1,MPI_INTEGER,MPI_MAX,mpicomo,ierr)
cplcomp_exchange_mod.F90:332 call seq_mctext_gsmapExtend(gsmap_old     , mpicom_old  , gsmap_old_join, mpicom_join, ID_join)
component_mod.F90:376        call seq_mctext_gsmapInit(comp(1))
cime_comp_mod.F90:1226       call component_init_cx(ice, infodata)
cime_driver.F90:92 
```

with this pe-layout on 863 nodes, 64 tasks/node:
```
> ./pelayout 
Comp  NTASKS  NTHRDS  ROOTPE
CPL :  43200/     1;      0
ATM :  43200/     1;      0
LND :   4800/     1;  38400
ICE :  24000/     1;      0
OCN :  12000/     1;  43200
ROF :   4800/     1;  33600
GLC :      1/     1;      0
WAV :      1/     1;      0
ESP :      1/     1;      0
```

I've added a barrier as a workaround to make sure that slow tasks (B and C) stay relatively close to fast tasks (A): in cime_comp_mod.F90
```
1220     call t_startf('CPL:comp_init_cx_all')
1221     call t_adj_detailf(+2)
1222     call component_init_cx(atm, infodata)
1223     call component_init_cx(lnd, infodata)
1224     call component_init_cx(rof, infodata)
1225     call component_init_cx(ocn, infodata)
1226     call component_init_cx(ice, infodata)
1227     call component_init_cx(glc, infodata)
1228     call component_init_cx(wav, infodata)
1229     call t_adj_detailf(-2)
1230     call t_stopf('CPL:comp_init_cx_all')
1231     call mpi_barrier(mpicom_GLOID,ierr)    ! <--
```

This has worked so far. Message tags may need to be adjusted to avoid the hangs.

**Comment by jedwards4b** [comment]
I don't understand why you need to add these barriers - why is task A completing a collective before B and C arrive?   Something is wrong.

**Comment by amametjanov** [comment]
To clarify, CPL and OCN tasks are on a disjoint set of nodes, and CPL and ICE tasks share some nodes. Task B (a CPL task) is waiting for irecv to come in from Task A (an OCN task). OCN tasks never get to `mpi_allreduce` collective of Task C, because OCN tasks do not share a communicator with ICE tasks.

So what appears to have happened is that message from fast OCN Task A to slow CPL Task B got lost or was consumed by a different task. So B hangs, and because C waits for B, C also hangs.

This line may need to be changed to reduce the likelihood of message tag collisions:
```
- call seq_map_map_exchange(comp(1), flow='c2x', dom_flag=.true., msgtag=comp(1)%cplcompid*100+1*10+1)
+ call seq_map_map_exchange(comp(1), flow='c2x', dom_flag=.true., msgtag=comp(1)%cplcompid*10000+1*10+1)
```

**Comment by jedwards4b** [comment]
If this change works I would be much more comfortable with it than with adding a barrier.  Barriers in my opinion just mask the problem.

**Comment by PeterCaldwell** [comment]
I'm on my 3rd 24 hr submission without MPI errors after making this change. This isn't proof that the fix works (and in particular, better stability could also be explained by a recent Cori reboot), but does seem promising. Are there any plans to get this change into the E3SM v1 release?
