### ISSUE TITLE
acme still referenced in some of the scripts/Tools files

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#2379]
I found these references to ACME in cime/scripts/Tools:

'grep -r acme *
bless_test_results:    > {0} -r /home/jenkins/acme/scratch/jenkins -b next --hist-only
compare_test_results:    > {0} -r /home/jenkins/acme/scratch/jenkins -b next
pointclm/pointCLM.py:#PTCLMfiledir = csmdir+'/scripts/acme/pointclm/PTCLM_files/'
pointclm/pointCLM.py:os.system('mkdir -p '+csmdir+'/cime/scripts-acme/pointclm/temp')
pointclm/pointCLM.py:              +csmdir+'/cime/scripts-acme/pointclm/temp/clm_params.'+pftphys_stamp+'.'+ \
pointclm/pointCLM.py:os.system('chmod u+w ' +csmdir+'/cime/scripts-acme/pointclm/temp/clm_params.'+pftphys_stamp+'.'+ \
pointclm/pointCLM.py:    pftfile = csmdir+'/cime/scripts-acme/pointclm/temp/clm_params.'+pftphys_stamp+'.'+casename+'.nc'
pointclm/pointCLM.py:              +csmdir+'/cime/scripts-acme/pointclm/temp/CNP_parameters_'+CNPstamp+ \
pointclm/pointCLM.py:os.system('chmod u+w ' +csmdir+'/cime/scripts-acme/pointclm/temp/CNP_parameters_'+CNPstamp+ \
pointclm/pointCLM.py:os.system('mv '+csmdir+'/cime/scripts-acme/pointclm/temp/*'+casename+'* ' \
pointclm/pointCLM.py:   os.system('mv '+csmdir+'/cime/scripts-acme/pointclm/temp/domain*'+options.site+'* ' \
pointclm/pointCLM.py:        output = open(csmdir+'/cime/scripts-acme/pointclm/temp/ensemble_run'+numst[1:]+'.pbs','w')
pointclm/pointCLM.py:                              '/cime/scripts-acme/pointclm/temp/mynodefile'+ngst[1:]+'\n')
pointclm/pointCLM.py:                                 csmdir+'/cime/scripts-acme/pointclm/temp/mynodefile'+ngst[1:]+ \
pointclm/pointCLM.py:                                 ' '+orig_dir+'/acme.exe > ccsm_log.txt &\n')
pointclm/pointCLM.py:                os.system('qsub '+csmdir+'/cime/scripts-acme/pointclm/temp/ensemble_run'+ \
pointclm/pointCLM.py:                              numst[1:]+'.pbs > '+csmdir+'/cime/scripts-acme/pointclm/temp/jobinfo')
pointclm/pointCLM.py:                myinput = open(csmdir+'/cime/scripts-acme/pointclm/temp/jobinfo')
pointclm/pointCLM.py:                              '/cime/scripts-acme/pointclm/temp/ensemble_run'+ \
pointclm/pointCLM.py:                              numst[1:]+'.pbs > '+csmdir+'/cime/scripts-acme/pointclm/temp/jobinfo')
pointclm/makepointdata.py:            metcmd = 'python '+csmdir+'/cime/scripts-acme/makemetdata.py' \
pointclm/makepointdata.py:os.system('mkdir -p '+options.csmdir+'/cime/scripts-acme/pointclm/temp')
pointclm/makepointdata.py:domainfile_new = options.csmdir+'/cime/scripts-acme/pointclm/temp/' \
pointclm/makepointdata.py:    surffile_new  = options.csmdir+'/cime/scripts-acme/pointclm/temp/surfdata_'+str(numxpts)+'x' \
pointclm/makepointdata.py:    surffile_new =  options.csmdir+'/cime/scripts-acme/pointclm/temp/surfdata_'+str(numxpts)+'x'+str(numypts)+'pt_'+ \
pointclm/makepointdata.py:        pftdyn_new = options.csmdir+'/cime/scripts-acme/pointclm/temp/' \
pointclm/makepointdata.py:        pftdyn_new = options.csmdir+'/cime/scripts-acme/pointclm/temp/' \
xmlconvertors/config_pes_converter.py:    CIME2: cime/machines-acme/config_pes.xml
xmlconvertors/config_pes_converter.py:    CIME5: config/acme/allactive/config_pesall.xml
xmlconvertors/grid_xml_converter.py:    CIME5: config/acme/config_grids.xml
xmlconvertors/grid_xml_converter.py:#    CIME5: config/acme/config_grids.xml
xmlconvertors/grid_xml_converter.py:                logger.info("config/acme/config_grids.xml. These nodes")'

**Comment by rljacob** [comment]
@bertinia You must have an old version because there is no scripts/Tools/acme directory.

The refs in bless_test_results/compare_test_results are local directory pathnames on Sandia machines and can stay I think.  @jgfouca ?

I'll remove the pointclm dir.

@sarich should we remove the xmlconverters dir?  The tools did their job and I don't think are needed anymore.  Otherwise they need to be updated.

**Comment by jgfouca** [comment]
@rljacob , yes, harmless.

**Comment by sarich** [comment]
Yes, I think we can remove the xmlconverters. We can always revive them if
we're wrong.

Jason

**Comment by bertinia** [comment]
@rljacob - working from CIME master but still see acme references in cime/doc/source *.rst files. 
I can go through and rename them to E3SM if the references are still valid? Here's what I'm seeing:

cd cime/doc/source
grep -r -i acme .

**Comment by rljacob** [comment]
Go ahead.  These are the only 4 acme references that are still valid:

```
./users_guide/testing.rst:  Creating test directory /home/jgfouca/acme/scratch/SMS.f19_f19.A.melvin_gnu.20170504_163152_31aahy
./users_guide/testing.rst:    Case dir: /home/jgfouca/acme/scratch/SMS.f19_f19.A.melvin_gnu.20170504_163152_31aahy
./users_guide/testing.rst:  ./bless_test_results -r /home/jenkins/acme/scratch/jenkins/ -t mytest -b master
./users_guide/testing.rst:  ./compare_test_results -r /home/jenkins/acme/scratch/jenkins/ -t mytest -b maste
```r
