### ISSUE TITLE
Enabling/allowing queue manipulation with CIME

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2381]
Also discussed a better decoupling CIME from compute nodes.

@ndkeen will explain the details below.

**Comment by jgfouca** [comment]
@ndkeen , waiting on you to describe the queue manipulation you want to do.

**Comment by jedwards4b** [comment]
Can we either figure out what this is or close it?

**Comment by jgfouca** [comment]
@ndkeen , last chance.

**Comment by rljacob** [comment]
We are all busy with the release.  There is no rush.

**Comment by ndkeen** [comment]
Yea this is more of a general philosophy and conversation.

**Comment by jgfouca** [comment]
@ndkeen closing since we never understood what was needed.
