### ISSUE TITLE
Setting up hybrid or branch run out of the box.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2388]
Jim pointed me to an example of how an out-of-the-box hybrid run is configured:
https://github.com/ESCOMP/cesm/blob/master/cime_config/config_compsets.xml#L308

Still got a bunch of questions:
Is RUN_REFDIR supposed to be located in the input data directory? 
Will CIME's check_input_data download the refcase restart files if the files aren't there?
In a hybrid run, what combinations of initial/restart files are allowed?   Not clear how the exact mix is specified out-of-the-box.

**Comment by rljacob** [comment]
Tried to define a hybrid run for e3sm.   Edited the compsets file.  Ran create_newcase.  Got an error on "case.setup"
```
Generating component namelists as part of setup
ERROR: 
*****************************************************************
prestage ERROR: $refdir is not on local disk
obtain this data from the svn input data repository
> mkdir -p /home/ccsm-data/inputdata/e3sm_init/beta3rc13_1850.ne30_oECv3_ICG/0331-01-01
> cd /home/ccsm-data/inputdata/e3sm_init/beta3rc13_1850.ne30_oECv3_ICG/0331-01-01
> cd ..
> svn export --force https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata//home/ccsm-data/inputdata/e3sm_init/beta3rc13_1850.ne30_oECv3_ICG/0331-01-01
or set GET_REFCASE to FALSE in env_run.xml
and prestage the restart data to $RUNDIR manually
*****************************************************************
```
Its true the refdir is not on the local disk.  So I created it and case.setup was able to almost finish (unrelated mpas problem).

Why does the user have to create the missing directories in the inputdir?  If they have permission to download files to the inputdir, they should be able to make directories and the script should just do it.

**Comment by rljacob** [comment]
Also, why does the error message say the user ALSO has to execute "svn export"?   If GET_REFCASE is TRUE, won't they be downloaded by check_input_data?

**Comment by jedwards4b** [comment]
See my PR #2439 - once that is in you could conceivably have an inputdata server that only provided those hybrid input files.

**Comment by rljacob** [comment]
I've got the server set up.  I don't understand who is supposed to actually put the files in my DIN_LOC_ROOT.  Is the user supposed to do that or will get_check_data do it?
```
blogin3[137]: ./check_input_data --download
Checking server https://web.lcrc.anl.gov/public/e3sm/inputdata/ with protocal wget
Loading input file list: 'Buildconf/clm.input_data_list'
Loading input file list: 'Buildconf/cam.input_data_list'
 - Prestaging REFCASE (/home/ccsm-data/inputdata/e3sm_init/beta3rc13_1850.ne30_oECv3_ICG/0331-01-01) to /lcrc/group/acme/jacob/acme_scratch/Cmip6hyb/run
Exit 1
```
No other error messages even with --debugging.

**Comment by rljacob** [comment]
Experimention, I put the files in DIN_LOC_ROOT/REF_CASE myself and ./check_input_data is able to complete the prestaging which is apparently just setting a link?

The error message about the "prestage error" above seems to have text that assumes cesm.  Its ignoring the actual repo where the refcase lives.

**Comment by rljacob** [comment]
So "GET_REFCASE=TRUE" just means it will set a link to the refcase restart files from the RUNDIR to DIN_LOC_ROOT assuming the files are already there?   User has to put the files in DIN_LOC_ROOT themselves?  check_input_data won't fetch them?

**Comment by jedwards4b** [comment]
I think that's correct, I'm not sure why check_input_data doesn't fetch them automatically.  Perhaps we should change that. @mvertens ?

**Comment by rljacob** [comment]
Is RUN_STARTDATE also supposed to be changed for a hybrid run?

**Comment by rljacob** [comment]
It must be.  Land model errors with " ERROR: Current model year does not match year on initial conditions file (finidat) " if I don't change it to match RUN_REFDATE

**Comment by jgfouca** [comment]
JimE has fixed the refcase downloading. I think this discussion is complete.
