### ISSUE TITLE
Mosart rh0 files no longer archived

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2394]
PR #2338 made this change to the mosart entry:
 <rest_file_extension>\.r.*</rest_file_extension>	  ->   <rest_file_extension>r</rest_file_extension>

This will miss "rh0" files created by mosart when the restart boundary is not on a history file boundary.

Fix is to add another rest_file entry for rh0 as done in clm and cam.

**Comment by jedwards4b** [comment]
I think you need:
```<rest_file_extension>rh\d*</rest_file_extension>``` added to the mosart entry.

**Comment by jgfouca** [comment]
@jedwards4b , thanks, trying that now. Could this change have unintended side effects? Why is this needed for mosart but no other component?

**Comment by rljacob** [comment]
Other components either don't write an rh0 file, do and already have an entry for it, or they write an rh0 file and no one has noticed that they are no longer being archived.

**Comment by jedwards4b** [comment]
cam and clm already have it.

**Comment by jedwards4b** [comment]
For our testing we write daily history files which gives us a better test of component diagnostic variables but as a side affect masks problems that may come up in history restart (rh) files.

**Comment by jgfouca** [comment]
@jedwards4b , i see cam and clm have multiple XML entries for rest_file_extension, maybe that's what's needed here?

**Comment by rljacob** [comment]
Yes that's what we're saying.  ADD <rest_file_extension>rh\d*</rest_file_extension> after the existing rest_file_extension entry in mosart.  Want me to do it?

**Comment by jedwards4b** [comment]
That's what I said above.
I think you need:
<rest_file_extension>rh\d*</rest_file_extension> added to the mosart entry.

**Comment by jgfouca** [comment]
@jedwards4b , ah sry, misunderstood you

**Comment by rljacob** [comment]
And do this in the CIME update branch for E3SM and re-merge to next so we can get the ERP test passing.

**Comment by jgfouca** [comment]
@rljacob , yep, retesting it now (the ERP test).

**Comment by jgfouca** [comment]
Jim's recommendation worked and we now have st archive testing built-in to the system.
