### ISSUE TITLE
Construct not working in py3

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2399]
This line 
```
case.locals()[function_name](skip_pnl=skip_pnl)
``` 
https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/XML/env_batch.py#L462

Works in py2 but in py3 generates:

 AttributeError: 'Case' object has no attribute 'locals'

**Comment by jedwards4b** [comment]
I changed from 
```
locals()[function_name](case, skip_pnl=skip_pnl)
```
but it turns out that this also doesn't work in py3.

**Comment by jgfouca** [comment]
@jedwards4b , since we know the function exists on case:

```
getattr(case, function_name)(case, skip_pnl=skip_pnl)
```
