### ISSUE TITLE
create_newcase needs to be merged

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#24]
Most of the ACME testing will fail until create_newcase is fixed.

**Comment by rljacob** [comment]
A couple of gists may help:
All diffs from start of ACME until right before adopting cime2:
https://gist.github.com/rljacob/6574f6e66f1d277bea75

All diffs by ACME since cime2 adoption.
https://gist.github.com/rljacob/cb3b660915f7d99a9770

**Comment by rljacob** [comment]
I'll try to summarize the main categories:
timing dirs:  Create dirs for holding timing info if specified in machine file.  Option -nosavetiming is used in testing.
python scripts:  some now need to be copied to $caseroot/Tools (if that is still a thing) and used.
Support for Depends.$mach.$compiler
(more)

**Comment by jgfouca** [comment]
merge complete.
