### ISSUE TITLE
Death in CESM cases with START_TOD not on the year boundary: "glcrun_avg_alarm is true, but glcrun_alarm is false"

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2401]
@andrewgettelman reports that, in SCAM cases with SGLC, he's getting a death at the year boundary (both in cases with Gregorian calendar and in cases with NO_LEAP calendar):

```
ERROR: glcrun_avg_alarm is true, but glcrun_alarm is false
Make sure that NCPL_BASE_PERIOD, GLC_NCPL and GLC_AVG_PERIOD
are set so that glc averaging only happens at glc coupling times.
(It is allowable for glc coupling to be more frequent than glc averaging,
but not for glc averaging to be more frequent than glc coupling.)
ERROR: (seq_mct_drv) glcrun_avg_alarm is true, but glcrun_alarm is false
```

He pointed me to a case that has:

```
	NCPL_BASE_PERIOD: day
	GLC_NCPL: 1
	GLC_AVG_PERIOD: yearly
```

which seems like it should work, so I can't figure out what the problem is here.

However, I do see that this check (and the setting of `glcrun_avg_alarm` at all) isn't necessary for a case with SGLC. So I'm going to fix this by avoiding doing this check (and the setting of `glcrun_avg_alarm`) in cases with `glc_prognostic` false.

cc @mvertens

**Comment by billsacks** [comment]
Ah, I think I see the underlying issue that's causing the death for @andrewgettelman and @jtruesdal - it looks like their case is starting at a time not on a day boundary:

```
	START_TOD: 64800
```

For now, I'm going to put in place the workaround I suggested above, because it feels like the right thing to do anyway. But I'll open a separate issue about the real, underlying problem.

**Comment by andrewgettelman** [comment]
Thanks @billsacks. The odd start time happens when we use observed forcing. The workaround will be fine. I appreciate you getting to the bottom of this!
