### ISSUE TITLE
Cannot run CISM when START_TOD is not on a day boundary

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2402]
As noted in #2401 , @andrewgettelman and @jtruesdal ran into a problem when starting a case with START_TOD not on a day boundary (i.e., different from `00000`): When the model crosses the year boundary, this gives:

```
ERROR: glcrun_avg_alarm is true, but glcrun_alarm is false
Make sure that NCPL_BASE_PERIOD, GLC_NCPL and GLC_AVG_PERIOD
are set so that glc averaging only happens at glc coupling times.
(It is allowable for glc coupling to be more frequent than glc averaging,
but not for glc averaging to be more frequent than glc coupling.)
ERROR: (seq_mct_drv) glcrun_avg_alarm is true, but glcrun_alarm is false
```

I'm going to address #2401 by ensuring that this error isn't triggered when running with SGLC. However, I believe this is still going to be an issue when running with CISM.

I think the problem is the following: There are two alarms that are important when running with an active GLC model: glcrun_alarm says when to run, and glcrun_avg_alarm says when to average fields to send to GLC. By default in CESM, glcrun_alarm is set to go off daily, and glcrun_avg_alarm is set to go off on the year boundary. It's important that, whenever glcrun_avg_alarm is ringing, glcrun_alarm is also ringing. If you start the model on a day boundary, this will be true with the default settings. However, if you start the model not on a day boundary, then glcrun_alarm will ring in the middle of each day, whereas glcrun_avg_alarm will ring on the year boundary, and thus also on a day boundary.

If I remember correctly, this should **not** be an issue in E3SM, with the way things are currently configured, because I think glcrun_avg_alarm is set the same as glcrun_alarm in E3SM.

cc @mvertens @apcraig @rljacob

**Comment by billsacks** [comment]
One solution would be to set the glcrun_alarm to ring on the day boundary, rather than ringing daily from the point of model start. I think this would require adding more flexibility in how coupling frequencies are set (in the xml). Another solution would be to make glcrun_avg_alarm ring yearly from the point of model start; I'm not sure what that would require, and I don't really like that solution.

However, this raises a broader issue: The whole reason why glcrun_alarm rings daily rather than on the year boundary is to support writing restart files not on the year boundary: Restart files can only be written at the coupling interval. We have assumed that a daily opportunity to write restart files is sufficient. But when users start a run in the middle of a day, what might they want in terms of the frequency of writing model restarts? In particular: I'm concerned that, if we changed glcrun_alarm to ring on the day boundary, this could mean that we don't call glc at a time when it needs to be called to write a restart file.

**Comment by billsacks** [comment]
Long-term, the robust solution here may be to extract a separate call to write component restart files. That way, we could do away with the whole problem of needing to call glc with some frequency just to support model restarts: we could make the coupling frequency equal to the averaging frequency, with both occurring on the year boundary.

@mvertens and @apcraig - Would the idea of having a separate call to components when it's time to write a restart file be feasible under NUOPC? In an ideal world, I feel it would be useful to expand the init/run/finalize interface to init/run/write_restarts/finalize. But I realize that may be too invasive for components. So an alternative would be to keep init/run/finalize, but optionally, components can support a `only_write_restarts` flag in their run method; if true, they would just write a restart file without actually running. (Components that don't want to support this flag can just abort if it's set to true; e.g., CAM probably doesn't need to support this.) Then the driver would have some logic like: If this is time to write restart files: For any component for which this is not a coupling time, call its run method with `only_write_restarts` set to true.

**Comment by billsacks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot run CISM when START_TOD is not on a day boundary](https://trello.com/c/ok3biWE4/95-cannot-run-cism-when-starttod-is-not-on-a-day-boundary)

**Comment by billsacks** [comment]
@Katetc @mvertens - To do: investigate whether this is an issue with CMEPS; if so, move this issue there; if not, close it.

**Comment by mvertens** [comment]
@billsacks - can you please move this issue to CMEPS so we remember to investigate it there. It does not belong in CIME.

**Comment by billsacks** [comment]
@mvertens @Katetc - Actually, reading back through this, it feels to me like the theoretical situation in this issue is unlikely to come up in practice (the actual problem that prompted this issue was with SGLC; the SGLC issue is fixed, but at the time it made me realize that there is this theoretical problem with CISM, too) – and the only really satisfactory solution that I could see would be the relatively big change of adding a new interface to component models to just tell them, "it's time to write a restart", so we could do away with the whole complexity of needing to call CISM daily just so it can check if it's time to write a restart. (Wow, that was quite the run-on sentence!) Short of that, it seems like the real limitation is just that the model can only stop and start on a multiple of the daily GLC coupling frequency, which is a general limitation of the system anyway.

So I'm going to just close this as a wontfix, since my recollection is that it isn't on the table right now to implement this new interface to tell a component model, "it's time to write a restart".
