### ISSUE TITLE
Allow more intelligent project selection

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2403]
A request from the E3SM side: 

CIME currently will default to config_machines.xml PROJECT if the user has not provided any guidance to the system regarding their desired PROJECT. This can lead to submit errors if the user is not in that project. CIME should check, if possible, to confirm that the user is in the default PROJECT. If not, raise an error or default them to their own default allocation on the system.

**Comment by jedwards4b** [comment]
Isn't the determination of PROJECT going to be different on every system?   Users already have the ability to override the default project by setting $PROJECT in their environment or $HOME/.cime/config

**Comment by ndkeen** [comment]
The determination of many things is different on every system.  But surely there is a way of asking 2 questions:
1) is this user a member of the current default (or set of common allocations?)
2) what is default for user
based on that, we could use an allocation that might shield us from emails about why it didn't work, when all they needed was to specify project

**Comment by ndkeen** [comment]
I did some searching and found gentnim:  (I also sent email, but will take a while to get response)

```
cori01% getnim -Undk
m1759                234941.85 ACTV
acme                6760604.77 ACTV
m888                1868997.60 ACTV
m1517                100000.00 ACTV
m2637                 10000.00 ACTV
```

And I *think* the first line is my default allocation

**Comment by billsacks** [comment]
My feeling is that, rather than adding this complexity to cime, we should remove any attempt to set a default project in cime. Project numbers should be up to the user to provide explicitly, either via one of the methods @jedwards4b mentioned or case-by-case on the command line, via the `--project` argument.

**Comment by rljacob** [comment]
After some thought, I agree with Bill.   Its not to hard to set the PROJECT variable and most users only need to change it once per allocation cycle (typically once per year at most).  So you can nearly "set it and forget it".

**Comment by rljacob** [comment]
That said, given that a user has specified a project, should we test for its validity and that the user can use it?  Otherwise there won't be any indication until the submitted job fails.

**Comment by jedwards4b** [comment]
There is no standard way to do that - we would have to incorporate code unique to each system, my feeling is no.   We could however make sure that output directories are available and writable - we already do this much and it happens before the case is submited.   Under what circumstances does the error only occur at submit time - again this is very machine dependent.

**Comment by rljacob** [comment]
I forgot about the directories.  But yeah that's not easy to do in a general case.

Do any of the CESM machines have a default project specified?

**Comment by jedwards4b** [comment]
yes, several do

**Comment by rljacob** [comment]
Do you want to remove them?    We would remove the default projects from all machines and all users have to specify a project somehow at create_newcase time.

**Comment by jedwards4b** [comment]
I'm fine with that plan.  It would mean removing project and charge_account from the config_machines.xml file and env_mach_specific.xml and moving to env_run.xml

**Comment by jedwards4b** [comment]
Users can set PROJECT env variable in their dotfiles.
