### ISSUE TITLE
testmod breaks cime-developer

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2408]
The testmod added to e3sm which is specific to the pet test on a single machine (https://github.com/ESMCI/cime/tree/master/config/e3sm/testmods_dirs/allactive/mach/pet)
Is used in the cime-developer test list (https://github.com/ESMCI/cime/blob/master/scripts/lib/update_e3sm_tests.py#L52)
but this testmod does not exist and the directory is not defined on the cesm side.   

One solution might be to add an empty testmod directory on the cesm side.  However I think that using the mechanism of testmod for this change is perhaps not the best way to go about it.

**Comment by jgfouca** [comment]
@jedwards4b , I removed the test mod directly on master.

**Comment by jedwards4b** [comment]
Thanks - it seems to me that we need a rule that if your change is very narrow in scope - such as one that applies to one test on one machine then testmods is not the mechanism you want to use.   I'm just not sure how that rule should be stated.

**Comment by rljacob** [comment]
We don't have any other way to do machine-specific mods for a test.

**Comment by jedwards4b** [comment]
@rljacob I think we can come up with something - using testmods to do this is in my opinion going to get overly complicated very quickly.
