### ISSUE TITLE
 cprnc: Separate NetCDF C and Fortran libraries

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#2416]
Cross-posted from E3SM issue: https://github.com/ACME-Climate/ACME/issues/2218

On Summit, NetCDF C and Fortran libraries are installed separately. 

So, the .env_mach_specific.sh that is generated from CIME contains
```
export NETCDF_C_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/gcc-6.4.0/netcdf-4.4.1-6ouxbcpqvoewop7h3mv6sc6v5t5oztrf
export NETCDF_FORTRAN_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/gcc-6.4.0/netcdf-fortran-4.4.4-j66gqx5cyqzfarns7laaxds25j7uho6k
```
But I manually need to set NETCDF_PATH to NETCDF_FORTRAN_PATH to build. 
```
export NETCDF_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/gcc-6.4.0/netcdf-fortran-4.4.4-j66gqx5cyqzfarns7laaxds25j7uho6k
```
Even while running, it seems to miss one of the NetCDF lib/modules due to dynamic linking. So the invocation for cprnc from tests needs to load the appropriate modules.
```
module load netcdf-fortran
```

This needs to be handled in a more robust manner as this scenario (separate libs) becomes more common as they are distributed separately upstream.

Dynamic linking is a problem too as the modules and compiler used for building cprnc need to be loaded while running and we would need separate cprnc executables for different supported compilers. This dynamic linking issue may be a headache unique to Summit. I tried building the static version but was unable to find requisite static versions of libc and libm.

**Comment by jedwards4b** [comment]
When running cprnc under testing you should be in the cime environment (the modules listed in 
config_machines for that system should be loaded).   This is not the case if you try to run cprnc from
the command line in which case you need to manually load modules.  
The dynamic linking issue can be solved with a wrapper to the cprnc script, here is an example:
```
#!/bin/sh

export LD_LIBRARY_PATH=/usr/common/usg/darshan/2.3.0/lib:/usr/common/usg/mysql/5.6.21/lib:/opt/torque/5.0.1/lib:/opt/intel/composer_xe_2015.1.133/compiler/lib/intel64:/opt/intel/composer_xe_2015.1.133/mpirt/lib/intel64:/opt/intel/composer_xe_2015.1.133/mkl/lib/intel64:/usr/syscom/nsg/lib

/project/projectdirs/ccsm1/tools/cprnc.edison/cprnc.exe $*
```

**Comment by sarats** [comment]
Yes, I realized wrapper script is the way to go. I have different compilers (ibm,pgi,gnu) which require respective LD_LIBRARY_PATH. I have now built a cprnc for each compiler. I'm invoking the suitable compiler based on environment variable on Summit (LMOD_FAMILY_COMPILER).

What is the CIME recommended way (env variable?) to identify the compiler in the current case?

**Comment by jedwards4b** [comment]
You don't need a separate cprnc for each compiler - just build one and use it regardless of the compiler used for testing.

**Comment by jedwards4b** [comment]
I'm not able to reproduce the problem 
```
But I manually need to set NETCDF_PATH to NETCDF_FORTRAN_PATH to build.
```   
but perhaps I misunderstood and you are referring to the cprnc build and not the model build?

**Comment by sarats** [comment]
Yes, I was referred to cprnc build, but that's a simple enough fix. 

I guess I just wanted to bring this up to understand if anything else needs to be done for other tests/components in case of separate NetCDF builds.
