### ISSUE TITLE
test_mods_dir vs user_mods_dir 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2421]
These should be defined consistently, however testmods_dir gets the component name tacked to the end of it at line 439 of test_scheduler.py while usermods_dir does not.

**Comment by jgfouca** [comment]
The ship has sailed.

**Comment by rljacob** [comment]
why is this not fixable?

**Comment by jedwards4b** [comment]
I think that the feeling on the call was that the convention was too firmly entrenched to back out now.
