### ISSUE TITLE
Need better testing of archiving

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2428]
Both @jedwards4b and I have been burned by recent cime updates to our respective models due to problems with st_archiving that were not caught by our cime standalone testing. It would be awesome if we could have somehow caught these errors in scripts_regression_tests. I'm wondering if we could make some additional Fake tests that mimic hist and restart file creation of a real coupled run so we could test archiving.

**Comment by jedwards4b** [comment]
Was actually discussing this with @mfdeakin-sandia this morning:
I"m thinking of creating a list of history and restart file names for each component - perhaps they should be listed in config_archives.xml?  And a test that would populate a run directory and then run case.st_archive and make sure files are disposed of correctly.
There are some pretty common negatives too - files that should not match the regex

**Comment by jgfouca** [comment]
@jedwards4b that sounds great.

**Comment by jedwards4b** [comment]
Fixed by #2470
