### ISSUE TITLE
Can we stop copying log files to the case directory?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2435]
I was talking to @cecilehannay about disk space issues on cheyenne. She pointed out that it's often useful to keep case directories around for a long time, but they take up much more space than they need to because the log files are copied into your case directory. Can we stop copying log files into your case directory, just leaving them in your archive directory?

**Comment by mvertens** [comment]
I think this is a good idea moving forwards.

**Comment by mvertens** [comment]
Why are you attached to having them there? You don't have the data there.
Why can't the log files coexist with the data?
