### ISSUE TITLE
Problems cloning a case from another user

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2445]
When I tried cloning a case from another user, my CIME_OUTPUT_ROOT was kept as that user's, so pointed in this case to /glade/scratch/hannay.

In this instance, I was able to run that way (I guess Cecile gives write permission to her scratch space). However: when I also tried to use `--keep-exe` in my clone of her case, I got a failure because my clone case was trying to write some file in the original case (sorry, I forget the details).

**Comment by jedwards4b** [comment]
You need to add the option --cime-output-root to your create_clone command.

**Comment by mvertens** [comment]
Can we make sure this is documented in the create_clone overview in the
users guide.
