### ISSUE TITLE
Do not allow + in casename

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2452]
I thought that this was already in a list of characters not allowed in casename but apparently it isn't

**Comment by bertinia** [comment]
It is called out as a verboten character in the CESM casename conventions:

http://www.cesm.ucar.edu/models/cesm2.0/cesm/casename_conventions_cesm.html

`*** IMPORTANT NOTE: none of strings delimited by a "." in the casename should contain any of these special wildcard characters +,*,?,{,} that are used by the CESM scripts in pattern matching. *** `

but I don't see it mentioned anywhere in the CIME documentation anywhere.  

I'll add it to the doc but do we also need a check in create_newcase, create_test, and create_clone?

**Comment by rljacob** [comment]
CIME should document forbidden case name characters.  Any additional conventions would be in model-specific documentation.

**Comment by jedwards4b** [comment]
So @rljacob would you agree to this list of forbidden chars for cime casenames?
  
+*?<>/{}[\]~`@:

**Comment by rljacob** [comment]
Yes.

**Comment by mvertens** [comment]
This should go into the user's guide as an important note. @rljacob - can
you add this when you add your documentation for hybrid/branch?
