### ISSUE TITLE
SSP tests are failing in cime5.4.0-alpha.28 with missing datm_in file in ref1 directory

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2453]
With clm5.0.dev005 updated to point to cime5.4.0-alpha.28, all of the SSP tests are failing, in ref1 because the datm_in file isn't copied into it's run directory.

**Comment by jedwards4b** [comment]
Hi Erik, I think that you need to add a self.skip_pnl=False just prior to the self.run_indv line.

**Comment by jedwards4b** [comment]
It's self._skip_pnl=False

**Comment by ekluzek** [comment]
@jedwards4b yep you are right. The following change in CTSM fixes it. So I'm closing this as wontfix because the bug is in CTSM not cime.

```
diff --git a/cime_config/SystemTests/ssp.py b/cime_config/SystemTests/ssp.py
index 444c286..a2aacc9 100644
--- a/cime_config/SystemTests/ssp.py
+++ b/cime_config/SystemTests/ssp.py
@@ -62,6 +62,7 @@ def run_phase(self):
 
         dout_sr = clone.get_value("DOUT_S_ROOT")
         # No history files expected, set suffix=None to avoid compare error
+        self._skip_pnl = False
         self.run_indv(suffix=None, st_archive=True)
 

```
