### ISSUE TITLE
CAM+DART SourceMods into trunk

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2454]
@gold2718 @jedwards4b @mvertens 
This is a continuation of the discussion and issues stemming from #1807.
The st_archive issues are resolved, so I'd like to learn the status of 
merging the DART+CAM SourceMods into the trunk, so that they are
included in the pre-tag testing.  The last activity I saw about this was 
#2039 on Jan 27.   Is there still realistic hope of having this implemented
before the CESM2 freeze/release?
Thanks,
Kevin

**Comment by jedwards4b** [comment]
Are there any cime changes in this issue?   I think that you may be opening it in the wrong place.

**Comment by kdraeder** [comment]
@gold2718 @jedwards4b @mvertens
Brian Eaton has merged the CAM+DART SourceMods into the trunk.
They have been tested in a create_test of the multi-instance capabilities in test 
SMS_C80_P108x1_Lh1.f09_f09.FC6L5_HIST_FOREC.cheyenne_intel.allactive-dartcambigens.
After that test, the test was moved from CIME into CAM, 
and the compset was renamed FHIST_DARTC6.
So I believe that this issue can be closed.

**Comment by mvertens** [comment]
This is great news. Thanks everyone for helping with this milestone.
