### ISSUE TITLE
Running tools/configure on my mac gives a `source None` line

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2456]
When I run `CIMEROOT=. tools/configure --macros-format=Makefile --mpilib=mpi-serial` on my mac, the resulting `.env_mach_specific.sh` has, at the top: `source None`. Then if I run `source ./.env_mach_specific.sh` I get:

```
-bash: None: No such file or directory
```

Comparing this with a version on cheyenne, it looks like this is where it would normally source something needed for modules, and of course I don't have a module system on my Mac.

This doesn't seem to cause any problems (the other commands in env_mach_specific still get executed), but it could be good to clean up at some point.

**Comment by jgfouca** [comment]
This is my fault, sry. Fix coming.
