### ISSUE TITLE
compset/compname logic in CIME is not enforced.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2459]
While trying to change MPAS sea ice filenames and source code directory names recently, I found that following is possible (doesn't trigger any errors):
value of COMP_ICE in the config_components.xml file for the sea ice model:  mpassi
string used in compsets:  MPASCICE
source code directory:  components/mpas-seaice
"component" in config_files.xml:  mpasfoo  (pointing to mpas-seaice directory)
"compname" in config_archive.xml  mpascice
string used in filenames:  "mpascice"

The string used in filenames MUST match the compset string and MUST match the compname entry in config_archive.xml for short term archiving to work.

IF compname in config_archive.xml doesn't match, there is no error.  Just env_archive.xml won't have an entry for the "ice" compclass and no sea ice files will be archived.

IF COMP_ICE in config_components.xml doesn't match the string in the compset, anything after a %  in the compset is silently ignored.

**Comment by rljacob** [comment]
More logic found:  user_nl_$string must make the value of COMP_$COMPONENT.  So when I changed COMP_ICE to mpascice, had to also make user_nl_mpascice.  If you don't, you'll get an error from SetupTools.pm

**Comment by jedwards4b** [comment]
I think that it is consistent and there are rules, the problem is that the rules are not documented or enforced.

**Comment by jedwards4b** [comment]
The component name in cime/config/config_files.xml should match the COMP_XXX name defined in the components config_component.xml file, otherwise cime should throw an error when creating a case.   I think this will take care of the problem.

**Comment by rljacob** [comment]
I don't think it will take care of flagging 2 different compset names in the config_compsets.xml file.

**Comment by rljacob** [comment]
Looked up this issue and can't remember what I meant by "string used in filenames" in the description.
