### ISSUE TITLE
Mapping scripts re-worked for "new" geyser and caldera?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2469]
A grad student from Michigan contacted me because she was having trouble running [very old versions of] `gen_cesm_maps.sh` and `create_esmf_map.sh` on geyser. The current version of the script won't fair any better:

```
./gen_ESMF_mapping_file/create_ESMF_map.sh: line 108: mpirun.lsf: command not found
Error status returned from create_ESMF_map script
```

Also, `gen_cesm_maps.sh` should abort if `create_esmf_map.sh` returns an error rather than continuing on to the next file.

**Comment by billsacks** [comment]
Does this need to be fixed for cesm2? If so, can you please add it to the cesm2 milestone?

**Comment by ekluzek** [comment]
@mnlevy1981 it seems to me this should be done for CESM2.0, so I added it to that milestone. @jedwards4b I bet it's too late to de couple these now. These tools are required for making datasets needed to run CESM and so are required.

**Comment by billsacks** [comment]
Is the plan for this to be fixed for cesm2.0?

**Comment by mnlevy1981** [comment]
It should be in cesm2.0, and I'll work on it this afternoon / Monday

**Comment by mnlevy1981** [comment]
Okay, I have a branch where we can run all the mapping tools in serial on all the CISL machines (cheyenne, geyser, caldera, pronghorn). I have also submitted a ticket to CISL for guidance on how to run these tools in parallel, because I get different errors from different versions of `mpiexec` (mpich, openmpi, mpt) but nothing that actually runs.

I'll submit a PR tomorrow, whether the parallel tools work or not (working serial / broken parallel seems better than everything being broken, and my current branch defaults to using the serial tools even if you're on geyser)

**Comment by mnlevy1981** [comment]
I'm not confident in CISL's ability to get the parallel ESMF tools running so I guess we'll only provide serial tools for the release.
