### ISSUE TITLE
CESM: Update cheyenne_gnu to v. 7

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2473]
We'd like to update cheyenne_gnu to v. 7 for the cesm2 release. With a recent fix in CLM (workaround for a compiler bug), there are no known issues with v. 7.

@fischer-ncar could you give this a shot, running the necessary cheyenne_gnu prealpha / prebeta tests to verify that v. 7 of gnu will now work with cheyenne?

**Comment by fischer-ncar** [comment]
CLM is still having issue with gnu v. 7.   Get the following errors on cheyenne.

       cascade_step_name(i_l1s1) = 'L1S1'
      1
      Error: Unclassifiable statement at (1)
      /glade/u/home/fischer/code/cesm2_0_alpha10d.gnu7/components/clm/src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90:568:6:

       cascade_step_name(i_l2s1) = 'L2S1'
      1
       Error: Unclassifiable statement at (1)
       ...

**Comment by ekluzek** [comment]
Reopened issue 68 for ctsm:

https://github.com/ESCOMP/ctsm/issues/68

**Comment by billsacks** [comment]
@fischer-ncar - The latest CLM tag from @ekluzek should fix the gnu issues, so we should try this update to gnu v. 7 again.
