### ISSUE TITLE
Running in another user's case dir.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2485]
Making note of this feature request.

A user makes their case directory and all the output directories world or group writeable.  Another user cd's to that case directory and starts running the model.  Everything should work.

**Comment by rljacob** [comment]
@jgfouca was #2475 all that was needed to make this happen?

**Comment by jedwards4b** [comment]
This could lead to some unfortunate problems - I think we need to assure that if a case is cloned by another user, the new user clearly understands that they may overwrite the previous users rundir.

**Comment by rljacob** [comment]
Why would this mess up a clone?  Doesn't a clone reset the Rundir and the short term archive to the new user's?

**Comment by jedwards4b** [comment]
not unless they explicitly use the --cime-output-root option

**Comment by jgfouca** [comment]
@rljacob , yes, that's all that was needed. But as @jedwards4b , we can't make any guarantees about safety.
