### ISSUE TITLE
JOB_WALLCLOCK_TIME incorrectly reset when multiple queues available and neither match the settings

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2495]
ie, on Skybridge, the following issue occurs:
```
/create_newcase --case vsplit-f3-5y --res ne30np4_ne30np4 --mach sandiatoss3 --compiler intel --compset FC5AV1C-L --walltime 11:00:00
./xmlchange NTASKS=3072
./case.setup
./xmlquery JOB_WALLCLOCK_TIME
Results in group case.run
	JOB_WALLCLOCK_TIME: 04:00:00

Results in group case.st_archive
	JOB_WALLCLOCK_TIME: 0:20:00
```
This case is using 192 nodes, which is greater than the `nodemax=64` specified in `config_batch.xml` for Skybridge. That `JOB_WALLCLOCK_TIME` resets to `4:00:00` suggests it's defaulting to the short queue option.
Also, checking `JOB_QUEUE` after case.setup shows it selected the short queue.
If `NTASKS` is not set, it doesn't reset the `JOB_WALLCLOCK_TIME`, which is the desired behavior. 
Changing the `config_batch.xml` entry's `nodemax` option to `200` gives the desired behavior.

**Comment by mfdeakin-sandia** [comment]
Actually I'm wondering if the best solution would be to just change the order of the two, since it seems to be a case of the default being wrong? Trying to choose the "best" queue based on the parameters passed seems like a potentially bad heuristic. Alternatively, change `maxnode` to be essentially infinite for this queue

**Comment by jgfouca** [comment]
Fixed by https://github.com/E3SM-Project/E3SM/pull/2306
