### ISSUE TITLE
A few multi-word options that don't have - between words

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2496]
It seems like multi-word options are typically separated by a single dash (`--test-root` in `create_test`, `--run-unsupported` in `create_newcase`, and `--user-mods-dir` in `create_clone`, to name a few).

However, `create_clone` has a `--keepexe` option that I think should follow the same convention and thus be `--keep-exe`. There are several options in `create_newcase` that raise the same question: `--srcroot`, `--gridfile`, `--pesfile`, and `--pecount`

**Comment by jgfouca** [comment]
We would need to maintain backward compatibility.
