### ISSUE TITLE
Batch-related perl modules will need examination

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#25]
The files:
utils/perl5lib/Batch/BatchMaker.pm
utils/perl5lib/Batch/BatchUtils.pm
will need to be closely examined and tested as they were full of conflicts. @jayeshkrishna made most of the changes on our side.

**Comment by jedwards4b** [comment]
Some new fields have been added to the acme config_machines.xml
I have a couple of concerns about them.

1.  I don't think that "default" should be in the name of the variables
(default_run_suffix, default_run_exe, default_run_misc_suffix).

2. $config{'EXEROOT'} is inconsistent with the naming convention we have
established for xml - it should be $EXEROOT or ${EXEROOT} or for env
variables $ENV{EXEROOT}

3. I'm not sure of the motivation to add these variables - if it was to
distinguish between cesm.exe and acme.exe perhaps we can find a place to
define it once instead of needing to do it for each machine? Or perhaps we
just use the $MODEL variable already defined in cime?



On Fri, Jan 8, 2016 at 3:00 PM, James Foucar <notifications@github.com>
wrote:

> Assigned #25 <https://github.com/ESMCI/cime/issues/25> to @jedwards4b
> <https://github.com/jedwards4b>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/25#event-509923929>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jayeshkrishna** [comment]
Most of the changes in these files were done to get ACME jobs working correctly (the job submit args were incorrect or unoptimal) on Titan and MIra. So feel free to suggest/modify any changes as long as we can run the ACME test cases.
1. The default* tags were named based on the "default_run_suffix" tag that already existed in CIME. We could change them if needed.
2. $config{'EXEROOT'} was present in the xmls in the CIME version that we used. These could be changed to reflect newer conventions.
3. The new variables that were added are being used in BatchMaker.pm:setCESMRun() to separate out the executable and the command suffixes (AFAIR, it was to get the executable string when creating the optimized job submit command). Again, any changes as long as we can get the ACME jobs to run on Titan+Mira with the correct+optimal job submit/run args would work for me.

**Comment by rljacob** [comment]
Can you say more about why it was necessary to separate out the executable and command suffixes?

**Comment by jedwards4b** [comment]
Yes - an example might help.

On Mon, Jan 11, 2016 at 9:39 AM, Robert Jacob <notifications@github.com>
wrote:

> Can you say more about why it was necessary to separate out the executable
> and command suffixes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/25#issuecomment-170611801>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jayeshkrishna** [comment]
The relevant commit message is  below,
```
    Fixing scripts with diff no of threads/component
    
    This change fixes the submit command for jobs where atleast one
    component has a different number of threads than other components.
    The scripts now also generate optimized submit commands for these
    jobs.
    This commit fixes the bugs in the code copied from the old
    taskmaker.pl script to generate optimal layouts for the jobs.
    Without the fix the generated run scripts were wrong on Mira
    and Titan (and possible other machines) if atleast one component
    had a different number of threads than other components.
    
    * New XML attribute, args, added to the executable tag. If this
      attribute is set to "default" (and the arguments are not explicitly
      listed) the scripts try to find if an optimized mpirun command
      can be created for the executable. See machine->mpirun->executable
      tag in config_machines.xml.
    
    * The default_run_suffix XML tag is now broken into two tags (the
      cesm executable and misc suffix) since the optimized mpirun
      command generator needs the name of the CESM executable.
    
    * If a job has atleast one component with different number of
      threads and has an mpirun executable that currently does not have
      an optimized job layout support (e.g. Job on Mira with atleast
      one component with different number of threads than other
      components) a correct, but possibly sub-optimal, job layout
      is generated by the scripts.
    
    * Added new accessors to the taskmaker to check availability and
      access the optimized mpirun command.
    
    * The optimized job layout is currently only enabled for Titan.
    
    [BFB]
    
    SEG-179

```

**Comment by jayeshkrishna** [comment]
Excerpt from the associated jira task,
```
A testcase used by Pat on Titan,
./create_newcase -case ne30_B1850C5_pgi_cimetestAy -mach titan -compiler pgi -compset B1850C5 -res ne30_g16 -project cli112
Tweak the env_mach_pes.xml,
COMP|TASKS|THREADS|ROOTPE|NINST|
ATM| 675 | 2 | 0 | 1 |
LND| 168 | 2 | 512 | 1 |
ICE| 512 | 2 | 0 | 1 |
OCN| 256 | 1 | 680 | 1 |
CPL| 512 | 2 | 0 |
GLC | 1 | 2 | 0 | 1 |
ROF| 168 | 2 | 512 | 1 |
WAV| 512 | 2 | 0 | 1 |

The pre-CIME ACME scripts generated the following submit command (*.run script) on Titan,

aprun -n 680 -N 8 -d 2 $EXEROOT/cesm.exe : -n 256 -N 16 -d 1 $EXEROOT/cesm.exe >&! cesm.log.$LID
```

**Comment by jayeshkrishna** [comment]
To generate commands like the ones shown above you need the executable string (without the clutter of the command suffixes).

**Comment by rljacob** [comment]
Has this been settled?

**Comment by jedwards4b** [comment]
yes I think so.

On Wed, Jan 20, 2016 at 4:50 PM, Robert Jacob <notifications@github.com>
wrote:

> Has this been settled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/25#issuecomment-173405706>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO
