### ISSUE TITLE
Check if map is in radians or degrees fails for small regional grids

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2506]
This is a bug I'm moving over from CESM-Dev. Here are the notes on it from there from @quantheory 

"Note the Bugzilla bug:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2102

To summarize, shr_map_mod has a function called shr_map_checkRad, which attempts to figure out whether an array of angles is in degrees or radians by testing whether the maximum and minimum values in the array are separated by greater than 2.02 * pi. Setting aside the fact that attempting to "guess" the units on a variable is terribly bad practice, the code of course breaks for small regional grids.

What we should be doing is checking the units on the input file. If there are files out there without appropriate units, we can perhaps fall back on the current method with a warning, and ideally change that warning into an appropriate error once those files fall out of use."

https://github.com/CESM-Development/cime/issues/100

**Comment by ekluzek** [comment]
This is an issue for users of CTSM:

https://github.com/ESCOMP/ctsm/issues/353

**Comment by email-lhe** [comment]
I met the similar problem with my single point run. I regenerated the domain and surface files, and I also double checked the latitude and longitude. The numbers shown in the files are within the arrays, but I still can't get through the model run. Anyone has suggestions? Thanks in advance.
