### ISSUE TITLE
Can change batch submission options before submit but not before build

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2514]
@jgfouca 's changes in #2320 allow users to change batch submission options (such as JOB_WALLCLOCK_TIME) after building but before submitting. However, I noticed an asymmetry: If you try to change these options between case.setup and case.build, you get an error:

```
File /glade/scratch/sacks/cesm_tests/x_0430a/LockedFiles/env_batch.xml has been modified
  found difference in JOB_WALLCLOCK_TIME : case '5:00:00' locked '4:00:00'
  found difference in USER_REQUESTED_WALLTIME : case '5:00' locked '4:00'
ERROR: Batch configuration has changed, please run case.setup --reset
```

This isn't a big deal, but I do find the asymmetry a bit troubling: Normally, if you can safely change a variable at a given stage of the setup-build-submit process, then you can also safely change that variable at any earlier stage. But this is not the case here.

@jedwards4b and @mvertens I'm going to add this to the cesm2 milestone because I think it would be nice to have this resolved by then. But I'd view it as non-essential for cesm2 (lower priority than some other things for the release).

**Comment by jgfouca** [comment]
@jedwards4b , is there a reason env_batch.xml is locked for case.build?
