### ISSUE TITLE
Unclear how to set JOB_WALLCLOCK_TIME just for the main job

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2528]
I probably knew this at one time, but now I can't figure out how to set JOB_WALLCLOCK_TIME just for the main job (not the short-term archiver), and I can't find any documentation of this.

I ran into a problem setting `./xmlchange JOB_WALLCLOCK_TIME=12:00:00`, which set it for the short-term archiving job as well as the main job, and then my short-term archiving job was rejected for requesting too much time for the share queue on cheyenne.

It seems like users would generally want to just set JOB_WALLCLOCK_TIME for the main job. Ideally that would be the default behavior. But at least this common use case should be documented somewhere. Places I looked were in the cime sphinx-based documentation and in the help output for xmlchange. I have a feeling I'm supposed to use "subgroup" here, but I'm not sure... an example in the xmlchange documentation would help a lot.

**Comment by jedwards4b** [comment]
--subgroup case.run

**Comment by mvertens** [comment]
@jedwards4b - Can we please add this to the documentation before the
release.

**Comment by jedwards4b** [comment]
I think that this would go in section 5 - do you agree? http://esmci.github.io/cime/users_guide/running-a-case.html

**Comment by mvertens** [comment]
Yes - that is the right place.
