### ISSUE TITLE
remove manage_pes script

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#2529]
This does not work and is not used by CESM. We would like to remove it before the release. Is there any problem on the E3SM side with removing this script?

**Comment by rljacob** [comment]
I don't know.  @amametjanov  do you use it?

**Comment by mvertens** [comment]
@rljacob - I would be surprised if anyone uses it since testing it this
morning showed that it did not work.

**Comment by amametjanov** [comment]
I haven't used it
