### ISSUE TITLE
Project id from cmd line not taking precedence over xml value

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#253]
The project id specified via command line (--project argument in ./create_newcase) does not take precedence over the project id specified via xml tags (<PROJECT> tag in config_machines.xml).

**Comment by jayeshkrishna** [comment]
Can be tested by specifying "--project" argument (with a different project id) to ./create_newcase for machines that have <PROJECT></PROJECT> specified in config_machines.xml

**Comment by jedwards4b** [comment]
It looks like the correct (cli) value of project is put into the env_batch.xml file but then the value from config_machines.xml is used when building the run command.

**Comment by jedwards4b** [comment]
I have this fixed in my more_mira_port branch, but still working on other issues before submitting PR

**Comment by jedwards4b** [comment]
fixed
