### ISSUE TITLE
model_doi_url unset in cpl restart file

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2532]

**Comment by billsacks** [comment]
@bertinia did not state as a requirement that this appear in restart files - only that it appear in history files. If this is actually needed in restart files, too, then do component liaisons need to add it to every component?

**Comment by jedwards4b** [comment]
No - I think that the issue here was that the coupler history and restart meta data are written by the same routine and so a model_doi_url variable was appearing in the restart file but wasn't defined.   I think we don't need this field in the restart file but if you are going to write there it should have a consistent value.

**Comment by billsacks** [comment]
@jedwards4b thanks for explaining - that makes sense.
