### ISSUE TITLE
Some medium resolution cases with cheyenne_gnu timeout at initialization

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2544]
This is with the current cime version, but I also see it in cesm2_0_beta08 which was using cime5.4.0-alpha.23.

The following case, and several others time-out at initialization

SMS.f19_g17.I2000Clm50Cn.cheyenne_gnu.clm-default

There's plenty of wall-clock time given to the case, but it seems to run very slow compared to previous builds with gnu. Two differences I note in the build are that openmpi is used in place of mpt, and netcdf is used rather than pnetcdf. Note, also that lower resolution cases do work. And I also have DEBUG on and off cases that work.

**Comment by ekluzek** [comment]
@billsacks and I looked this over a bit. We think this is a problem with cheyenne_gnu/openmpi trying to run with lots of processors. Tests using 288 tasks or more seem to fail. So the solution seems to be to use a smaller number of tasks when using cheyenne_gnu.

**Comment by billsacks** [comment]
@ekluzek Recording some notes from our conversations, partly for the benefit of @jedwards4b . It looks like at least some of these cases were hanging while reading the domain file. My best guess for what's going on is that the combination of gnu/openmpi/netcdf has problems for cases with high PE counts: These cases were mostly/entirely running with 1000-2000 tasks, whereas the highest PE count I can find for successful tests in the prealpha/prebeta test suite were 144 lnd tasks.

Based on that, I'm inclined to say that this is a known issue that we can only run with relatively small PE counts with cheyenne_gnu, and close it as a wontfix. @ekluzek and @jedwards4b do either of you think differently about this?

**Comment by billsacks** [comment]
Okay, I have removed the cesm2 milestone.

**Comment by billsacks** [comment]
I'm going to close this stale issue as a wontfix.
