### ISSUE TITLE
case.build --clean is incredibly slow

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2545]
It almost takes long to clean than to build.

**Comment by jgfouca** [comment]
gmake itself has historically worked fine for me. Is is because it's doing a bunch of xmlqueries? Or is it out of our control?

**Comment by jedwards4b** [comment]
I think that you can tease out the gmake argument and try it from the command line - I believe that's where all the time is spent.

**Comment by jgfouca** [comment]
Closing. This will be addressed by the upcoming CMake work.
