### ISSUE TITLE
Running case.st_archive with RESUBMIT > 0 submits case.run jobs

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2547]
One of our users complained about this, and it seems very unintuitive from a UI perspective for people who run case.st_archive from the login node.
My thought on a solution to this is to add an argument to case.st_archive which enables resubmitting, and have case.submit set that option for the archiving jobs.

**Comment by jedwards4b** [comment]
Hmmm - if case.st_archive is run from the command line instead of from case.submit then it should not invoke case.run - I don't think that this requires a new argument, just a minor change in logic.

**Comment by mfdeakin-sandia** [comment]
I don't see an obvious mechanism for determining if it's being run from the command line as opposed to case.submit? If there is one, I'd expect the mechanism for determining this to be in env_run.py or env_batch.py?
I could make that method if you'd prefer that
