### ISSUE TITLE
Update and fill out testing documentation; focus on create_test

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2556]
This issue results my effort to add prebeta testing of DART-related features, #2455. 
The documentation seemed incomplete, and some of what I did find is out of date.

Most of what I've learned has been through searching through directories and files
for connected bits of information.  I found a prebuilt user's guide at 
http://esmci.github.io/cime/users_guide, but it seems like I should be able 
to build the most recent html documentation and/or users_guide to navigate 
and find things more easily, and to test my local changes.  But when I try to follow 
the instructions in cime/doc/README I get

> $> make clean
> /bin/sh: sphinx-build: command not found
> Makefile:37: recipe for target 'clean' failed
> make: *** [clean] Error 127

What motivated a lot of my searching was looking for a list of 'categories' used 
in the cesm testlist*.xml files, and the definitions of them, so that I can assign 
the right one to the DART tests.   
What's the process for assigning a category to a test?  
Should that be documented where it's easy to find?

`doc/source/users_guide/testing.rst:Adding tests`
recommends opening config/$model/tests.py, but that only works for model = e3sm.
That file collects test names into named test suites(?).
The only other tests.py  is `scripts/lib/CIME/XML/tests.py`, which seems to serve
a very different purpose.   I've added a subsection for CESM which describes
the very different process for adding a test to CESM.

cime/doc/source/README seems to have been truncated.  Is there a complete
version somewhere that I can import?

When these questions are resolved, I'll issue a PR with my suggested documentation
changes.  Who should be reviewers and the person assigned to it?

**Comment by kdraeder** [comment]
@billsacks Thanks for assigning people.
@jedwards4b @mvertens 
Is there an updated cime/doc/source/README that I can use?

I have lots of potential updates to cime/doc/source/users_guide/testing.rst.
Should I issue a PR with those, or wait until the mechanism for
converting them into html works (cime/doc/README ... sphinx), 
and I can check that at least the formatting is right?

**Comment by kdraeder** [comment]
@billsacks @jedwards4b @mvertens,
I'd hate for anyone to re-invent this wheel without looking at my changes first.
Should I try to incorporate answers to my questions (above) before issuing a PR?
Or use the PR as a way to get the questions answered?
Thanks,
Kevin

**Comment by jedwards4b** [comment]
@kdraeder there have been a lot of documentation updates in the past week or so, please have a look and see if your issue has been covered.   Using the PR as a way to get questions answered is fine.

**Comment by kdraeder** [comment]
@gold2718 @jedwards4b @bertinia 
Thanks for the additional instructions and link.

The wiki tells me to use sphinx, or load sphinx using pip, on my local machine.
Neither cheyenne nor my Mac has either of those, including all the modules
available on cheyenne.  Shouldn't it already be available on cheyenne?
Caldera?

I also don't have a python-packages directory on my Mac.
I tried to install py27-sphinx on my Mac using Macports.
That led me down the rabbit hole of updating things on my Mac
for an hour, and I still don't have sphinx.  
Is this an issue for the CISL consultants, or am I missing something in CESM+CIME?

**Comment by jedwards4b** [comment]
We don't do or expect to do documentation on cheyenne.  On a mac I did:
 
pip install sphinx
pip install sphinxcontrib.programoutput

**Comment by kdraeder** [comment]
Where did you get pip?
I don't have it on my Mac, and can't import it with macports:
bash-3.2$ sudo port install pip        
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
Error: Port pip not found

and 'port selfupdate' fails too:
 Error: Insufficient privileges to write to MacPorts install prefix.

**Comment by gold2718** [comment]
I think this may be an issue for lab support as your Mac is configured by CISL and ours is configured by CGD-IS.
An easy way to (mostly) check your file is to push to your fork and open the file on GitHub. It will render .rst files and you can proofread it there. Note that it will not necessarily show you errors, it just will not look right.
Getting sphinx installed is definitely a better approach but it looks like you need lab support for that.

**Comment by mvertens** [comment]
There is cgd support for this. @bertinia could you please point kevin to
this.

**Comment by kdraeder** [comment]
@bertinia @jedwards4b @gold2718 
I've finally built sphinx on my Mac.
When I run 'make html' I get

> Running Sphinx v1.7.4
> Extension error:
> Could not import extension sphinxcontrib.programoutput (exception: No module named programoutput)
> make: *** [html] Error 2

I don't see any files under cime with programoutput in their names.
Same for sphinxcontrib.  And that's not in /opt/loca/bin/..., where the sphinx
files are living.

**Comment by kdraeder** [comment]
I found programoutput in source/conf.py in the list of extensions.
I'll try removing that from the list, since it doesn't seem to be used anywhere.

**Comment by bertinia** [comment]
@kdraeder - on your mac, type the following:

>pip list

You may need to install additional sphinx related packages including:

sphinxcontrib-bibtex (0.3.5)
sphinxcontrib-programoutput (0.11)
sphinxcontrib-versioning (2.2.1)
sphinxcontrib-websupport (1.0.1)

using pip. For example,

>pip install sphinxcontrib-programoutput 

After the install, check your PYTHONPATH env var to make sure the 
the path to the installed packages is included. 

The CGD machines have the full Sphinx distribution installed if you have a login account.

**Comment by kdraeder** [comment]
@bertinia 
Thanks for the package names.  I don't have pip, so 
I use macports, which is not finding those packages (without the '(#.#.#)')
Do you happen to know whether there's a different form, 
maybe with the version number attached, that I should try?
Thanks,
Kevin

**Comment by bertinia** [comment]
@kdraeder - looking at the Macports guide, https://guide.macports.org/#using.variants.invoking,
you might be able to use the `port search [package-name]`. Otherwise, it looks like 
`port install [package-name]` gets the most recent version by default.

**Comment by kdraeder** [comment]
I see that py27-sphinxcontrib-websupport had already been loaded,
but the corresponding versions of programoutput, bibtex, and versioning
don't seem to exist, or be available, according to:
> sudo port search sphinxcontrib              
py-sphinxcontrib-websupport @1.0.1 (python, textproc, devel, www)
py27-sphinxcontrib-websupport @1.0.1 (python, textproc, devel, www)
py34-sphinxcontrib-websupport @1.0.1 (python, textproc, devel, www)
py35-sphinxcontrib-websupport @1.0.1 (python, textproc, devel, www)
py36-sphinxcontrib-websupport @1.0.1 (python, textproc, devel, www)

So no other sphinxcontrib packages are available to me.

**Comment by kdraeder** [comment]
I've found one potential source for these other packages, e.g.:
    https://aur.archlinux.org/packages/python-sphinxcontrib-programoutput/
but I'm not keen on trying to figure out how to install them in a way that's
consistent with the rest of the sphinx installation.

**Comment by kdraeder** [comment]
@bertinia @jedwards4b @gold2718 
I seem to have found a path to success.
I needed to use macports to install pip (which doesn't show up as "pip", only "py-pip":
> sudo port install py-pip
> sudo port select --set pip pip27
> sudo -H pip install sphinxcontrib-programoutput

Repeat for -versioning and -bibtex.
