### ISSUE TITLE
Incorrectly specified testmods don't explain what's wrong

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2563]
The following is an example on the latest master of create_test not providing a reasonable error message when testmods are not specified correctly
```
./scripts/create_test SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio
No project info available
Creating test directory /gpfs1/mdeakin/acme_scratch/sandiatoss3/SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio.20180509_153811_kbkhtr
RUNNING TESTS:
  SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio
Starting CREATE_NEWCASE for test SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio in 0.018858 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /gpfs1/mdeakin/acme_scratch/sandiatoss3/SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio.20180509_153811_kbkhtr
    Errors were:
        Test 'SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio' failed in phase 'CREATE_NEWCASE' with exception 'need more than 1 value to unpack'
          File "/home/mdeakin/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 673, in _run_catch_exceptions
            return run(test)
          File "/home/mdeakin/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 433, in _create_newcase_phase
            (component, modspath) = test_mods.split('/',1)

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio (phase CREATE_NEWCASE)
    Case dir: /gpfs1/mdeakin/acme_scratch/sandiatoss3/SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel.force_netcdf_pio.20180509_153811_kbkhtr
test-scheduler took 0.207417964935 seconds
```

**Comment by jedwards4b** [comment]
The fake_testing_only string is something generated by scripts_regression_tests and not actually part of the testname - try  ./scripts/create_test SMS_D_Ln9.f19_g16_rx1.A.sandiatoss3_intel  instead

**Comment by jedwards4b** [comment]
fake_testing_only is not a testmod it's a test id.

**Comment by billsacks** [comment]
@mfdeakin-sandia so can we close this issue?

**Comment by mfdeakin-sandia** [comment]
I created the PR #2565 which will close this issue when merged, yes. It just tells the user what they've done wrong in this case

**Comment by mfdeakin-sandia** [comment]
I've edited this issue to better reflect what I'm fixing in the PR

**Comment by jedwards4b** [comment]
The preferred way to set force_netcdf_pio might be in a config_pio.xml file.

**Comment by mfdeakin-sandia** [comment]
I don't actually care about force_netcdf_pio (I don't know what it does), I was just trying to understand in general why it wasn't working

**Comment by mfdeakin-sandia** [comment]
Should I not be using testmods in my workflow? I was mainly interested in using them to try and replace the run_e3sm script with something better

**Comment by jedwards4b** [comment]
I'm not missing the point, I understand and I think that the PR #2565 is a good clarification, at the same time I think that it's important to explain that there are several ways to do things and testmods is in my opinion not the best choice.

**Comment by mfdeakin-sandia** [comment]
@jedwards4b Thanks for the clarification. I guess I'll look for a better per-case method of configuring and running the whole model with a single command.
