### ISSUE TITLE
check_input_data failure doesn't stop job submission

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2564]
There are files in the inputdata repository that are not yet on hobart... when I create a new job relying on those files, I expected they would be exported for me. Instead, when I run `case.submit` I get a message that they are missing and then `case.run` is added to the queue anyway:

```
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/ww3.input_data_list'
Loading input file list: 'Buildconf/dice.input_data_list'
Loading input file list: 'Buildconf/datm.input_data_list'
Loading input file list: 'Buildconf/pop.input_data_list'
  Model pop missing file nox_flux_monthly_input%filename = '/fs/cgd/csm/inputdata/ocn/pop/gx3v7/forcing/ndep_ocn_1850_w_nhx_emis_gx3v7_c180427.nc'
  Model pop missing file nhy_flux_monthly_input%filename = '/fs/cgd/csm/inputdata/ocn/pop/gx3v7/forcing/ndep_ocn_1850_w_nhx_emis_gx3v7_c180427.nc'
Loading input file list: 'Buildconf/drof.input_data_list'
Check case OK
submit_jobs case.run
```

**Comment by jedwards4b** [comment]
@mnlevy1981 Please when you open an issue like this provide enough information to reproduce the problem.

**Comment by mnlevy1981** [comment]
Sorry - this is using cime 5.6.0 (cesm2_0_alpha10e) -- a C1850ECO compset.

**Comment by mnlevy1981** [comment]
A couple of updates:

1. I copied `ndep_ocn_1850_w_nhx_emis_gx3v7_c180427.nc` into `/fs/cgd/csm/inputdata` by hand so I could continue my testing
2. there aren't any `C1850ECO` or `G1850ECO` tests on hobart in `prealpha` (though there are some in prebeta, which wasn't run on alpha10e)... I'll add a test or two so that something like this might be caught sooner in the future.
