### ISSUE TITLE
check_case script needs better documentation

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2569]
I have done some minor cleanup of the documentation for check_case on the branch mvertens/documentation_updates. However, I realized that I have no idea what this script is meant to be used for, and the documentation doesn't help. When in the process are you supposed to run this? What, exactly, does it check?

It would be helpful to answer these questions in the help documentation for the script, and optionally in the user's guide.

**Comment by jedwards4b** [comment]
Looking at the source code:
```
    with Case(read_only=False) as case:
        case.check_lockedfiles()
        case.create_namelists()
        build_complete = case.get_value("BUILD_COMPLETE")
```
So it makes sure that all the env xml files are in sync with lockedfiles, then runs preview_namelists, then verifies that the build is complete.   That's all it does.

**Comment by jedwards4b** [comment]
It's intended to make sure that your job is ready to submit prior to running case.submit but case.submit does the same thing prior to actually submitting anything so it's not clear to me that there is any point in having this tool - should we remove it?

**Comment by billsacks** [comment]
Okay, #2572 opened for comment.

**Comment by billsacks** [comment]
I've added more documentation in 2f3a5248a
