### ISSUE TITLE
Update config_batch.xml

### ISSUE THREAD

**Issue by wilke** [ESMCI/cime#257]
The type attribute is missing in some batch_system elements. Type is required otherwise element will be ignored.

<batch_system MACH="MASCHINE" type="BATCHSYSTEMNAME" version="x.y">

(batch.py -> set_batch_system)

**Comment by jayeshkrishna** [comment]
Some changes (adding type attribute in config_batch.xml for many machines - including titan) related to this Issue is being updated in PR #258 .

Please see https://github.com/ESMCI/cime/pull/258/files

**Comment by rljacob** [comment]
You mean the batch_system entry for a specific machine must have a "type="?
e.g. <batch_system MACH="edison" type="slurm" version="x.y">

Then what is the <BATCH_SYSTEM> key in config_machines for?
