### ISSUE TITLE
Questions about case.setup

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2576]
In addressing #1668 , I found I have two questions about case.setup for which I cannot find an answer:

(1) What files need to be changed before running case.setup? I know this includes env_mach_pes.xml, and at one point this included batch settings, but: are there still batch settings that need to be changed before running case.setup?; are there others?

(2) When do you need to run `./case.setup --reset` as opposed to just rerunning `./case.setup`?

@jedwards4b @jgfouca can you please either answer these questions here or update the help for case.setup in mvertens/documentation_updates, and/or the cime web documentation, to answer these questions?

**Comment by jedwards4b** [comment]
env_mach_pes.xml and env_mach_specific.xml.   Batch settings are now updated in the case.submit stage.

./case.setup is the first time it's run ./case.setup --reset thereafter.  It used to be a requirement to run
case.setup --clean followed by case.setup - I replaced those two commands with case.setup --reset
but looking at the code  in case_setup.py now I don't think that there is any difference between running case.setup and case.setup --reset

**Comment by jedwards4b** [comment]
Also if you change config_compilers.xml and want a new Macros file generated you can manually remove the current Macros file and run case.setup to generate it again.

**Comment by billsacks** [comment]
Thanks, @jedwards4b . From looking at the code a bit and playing around with this, it looks like:

1. `case.setup --reset` sets `BUILD_COMPLETE to FALSE`; simply running `case.setup` does not

2. `case.setup --reset` regenerates the `.case.run` file (and maybe does some other stuff: I think the whole block of code below is only executed on the first run or a reset), whereas simply running `case.setup` does not

https://github.com/ESMCI/cime/blob/fcebaadcf66024036f306f2d000ffd040f4fe5c7/scripts/lib/CIME/case/case_setup.py#L138-L175

**So based on this, I'll probably put in the documentation that, if you want to rerun `./case.setup`, you should use `./case.setup --reset`. Does that sound good?**

**Comment by jedwards4b** [comment]
sure
