### ISSUE TITLE
(Long-term) Would it be possible to stop having xml variables with the same name in multiple subgroups?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2584]
In reviewing the documentation for xmlquery and writing similar documentation for xmlchange, I came away feeling that it's confusing that there are a few variables - but some important ones, like JOB_QUEUE and JOB_WALLCLOCK_TIME - for which the same variable name appears in multiple subgroups. I understand the elegance of this from an implementation perspective, but from a UI perspective, this is a confusing part of the system.

Would it be feasible (not for the cesm2 release at this point, but longer-term) to rename these variables so that there are unique variable names rather than the same variable name appearing in multiple groups? As a user, I'd like to be able to do something like this:

```
./xmlchange RUN_WALLCLOCK_TIME=2:00
./xmlchange ARCHIVE_WALLCLOCK_TIME=0:05
```

rather than needing to use the special `--subgroup` option for `JOB_WALLCLOCK_TIME` and a few related variables.

**Comment by jedwards4b** [comment]
I disagree.  First we are going to train folks how to use this with cesm2 and changing it again for the next release will just cause another round of confusion.  Second available groups are mutable depending on the workflow defined in config_batch.xml.   I think that once users and developers are more familiar with the workflow capabilities of cime the subgroup option will make more sense.

**Comment by billsacks** [comment]
Okay, that's reasonable - thanks for the explanation.
