### ISSUE TITLE
In the documentation, we should give an example of load balancing

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2587]
I'm periodically asked to help with load balancing a fully-coupled configuration. I see that there is some good general theory here http://esmci.github.io/cime/users_guide/pes-threads.html , but what I find really helps is to go through an example. I think we should give an example in the documentation - e.g., starting with a case that has some load balance problems, describing those problems, then showing a configuration that is well load balanced and describing what's better about it.

I'm willing to take this on if this isn't already on someone's to-do list.

**Comment by rljacob** [comment]
The general help should also include a pointer to the load balancing tool and its docs:
http://esmci.github.io/cime/misc_tools/load-balancing-tool.html

**Comment by billsacks** [comment]
I know I volunteered for this on the telecon, but as I look at my task list, I can't see how I'll possibly get to this in the near future, so I'm unassigning myself.

**Comment by billsacks** [comment]
Pinging @briandobbins and @mnlevy1981 based on today's conversation.

Here's an example email I sent 5 years ago (I haven't done much load balancing work since then):

----
Here's what I see from your last timing file:

```
  component       comp_pes    root_pe   tasks  x threads instances (stride) 
  ---------        ------     -------   ------   ------  ---------  ------  
  cpl = cpl        1200        0        600    x 2       1      (1     ) 
  glc = cism       1200        0        600    x 2       1      (1     ) 
  wav = swav       1200        0        600    x 2       1      (1     ) 
  lnd = clm        420         0        210    x 2       1      (1     ) 
  rof = rtm        420         0        210    x 2       1      (1     ) 
  ice = cice       780         210      390    x 2       1      (1     ) 
  atm = cam        1200        0        600    x 2       1      (1     ) 
  ocn = pop        60          600      30     x 2       1      (1     ) 


    TOT Run Time:    7963.390 seconds       21.892 seconds/mday        10.81 myears/wday 
    LND Run Time:     908.653 seconds        2.498 seconds/mday        94.76 myears/wday 
    ROF Run Time:      28.706 seconds        0.079 seconds/mday      2999.57 myears/wday 
    ICE Run Time:     801.017 seconds        2.202 seconds/mday       107.50 myears/wday 
    ATM Run Time:    6569.674 seconds       18.061 seconds/mday        13.11 myears/wday 
    OCN Run Time:    5924.130 seconds       16.286 seconds/mday        14.53 myears/wday 
    GLC Run Time:      18.290 seconds        0.050 seconds/mday      4707.80 myears/wday 
    WAV Run Time:       0.000 seconds        0.000 seconds/mday         0.00 myears/wday 
    CPL Run Time:     401.395 seconds        1.103 seconds/mday       214.52 myears/wday 
    CPL COMM Time:    685.623 seconds        1.885 seconds/mday       125.59 myears/wday 
```

The important things to understand here are:

(1) LND and ICE run concurrently – meaning, if one of them finishes earlier, the other will wait around

(2) OCN runs concurrently with (ATM + LND/ICE)

(3) The general principle for load balancing when components are running concurrently is that you want the component that runs on fewer processors to finish sooner than the component that runs on more processors – that way, it's the smaller set of processors that is left idle.

From this, the overall balance between OCN and the other components looks good. But I don't like that LND takes longer than ICE, since LND has fewer processors than ICE.

So my first inclination would be to give about 30 more tasks to lnd, 30 less to ice – so lnd would be 240 x 2, ice 360 x 2... also changing ice rootpe from 210 to 240. We could then confirm that that reduces the total run time.

One caveat: At least at one point, cice only supported a limited set of processor counts. I'm not sure if that's still true....

**Comment by sherimickelson** [comment]
Here's an updated link to the documentation for the current version of the load balancing tool
http://esmci.github.io/cime/versions/master/html/misc_tools/load-balancing-tool.html

From my experience, the tool works fairly well in picking a load balanced pe layout, with a couple of large caveats .... when you setup the test pe layouts in the first step, make sure your test points cover the full range of the scaling curve (including the heel and tail) and because this was switched to linear, each of the component's run time must decrease when more pe's are added.
