### ISSUE TITLE
land pause/resume doesn't seem to work?

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2590]
I've got a land pause/resume test that does the following xml changes. The LND_DATA_ASSIMILATION, signal does work, but I don;'t see the LND_PAUSE_ACTIVE signal ever during a run. I've even ramped it up to every time-step and it's never triggered. I turned on CPL_PAUSE_ACTIVE just thinking that maybe it was needed as well as LND. And I thought that maybe LND_DATA_ASSIMILATION, was required as well. The only thing I notice there is that it will send the signal at startup when that's set. So that part seems to be working fine. This is with cim5.6.6 the latest cime tag.

This has been flagged as a feature needed for CESM2.0 and DART -- is that true? Is there something I'm missing in my setup or understanding?

```
./xmlchange --force LND_PAUSE_ACTIVE=TRUE
./xmlchange --force LND_DATA_ASSIMILATION=TRUE
./xmlchange --force CPL_PAUSE_ACTIVE=TRUE
./xmlchange --force CPL_DATA_ASSIMILATION=TRUE
./xmlchange --force PAUSE_OPTION=nhours
./xmlchange --force PAUSE_N=6
```

@gold2718 @kdraeder any advice here?

**Comment by gold2718** [comment]
@ekluzek,
The `LND_DATA_ASSIMILATION` flag is only used to send a resume (not pause) signal to the model during initialization. That should be working fine. This is the feature needed for CESM2-DART. Note that this feature is separate from pause/resume.

As for the `LND_PAUSE_ACTIVE` flag, how are you looking for that signal?

**Comment by ekluzek** [comment]
@gold2718 the same was as for the LND_DATA_ASSIMILATION signal, by reading lnd_resume from infodata, and responding if lnd_resume(inst_index) is set to something besides blank. There's a specific thing that has to happen in CTSM if the state was been mucked with by DA.

**Comment by gold2718** [comment]
You should be seeing that signal during initialization (with `LND_DATA_ASSIMILATION`) but not during run time.
If you set `LND_PAUSE_ACTIVE`, you should check to see if the pause alarm is ringing in your interface function `(lnd_run_mct`). You will not see a resume signal unless you are running an ESP component which sets it.

**Comment by gold2718** [comment]
Is this really an issue for interaction with DART in CESM2? If not, please close it.

**Comment by ekluzek** [comment]
OK, I think I understand now. LND_DATA_ASSIMILATION is the part that's needed for CESM2.0/DART and that's working. For LND_PAUSE_ACTIVE I need to check the input ESMF clock for it's pause alarm. And that's done as a separate check. So it sounds like CTSM needs to check the pause alarm and if it's ringing to trigger writing/reading a restart file and also turn off balance checks for a bit. So this is new behavior needed for the future.

So I'll close this as it sounds like CIME is working right, and add a future issue for ctsm to check the pause alarm. Since, LND_DATA_ASSIMILATION is working correctly, we have what we need for CESM2.0. So that's all good.

**Comment by gold2718** [comment]
@ekluzek,
Your description is almost correct.
1) Yes, this is possible _future_ functionality (although if pause/resume becomes a supported feature, it is likely to be for CESM3)
2) If the pause alarm is ringing, your only action is to _write_ a restart file
3) If the resume signal is set, you should reset your state from the provided restart file. Turning off the balance checks would still be controlled (possibly) by the `LND_DATA_ASSIMILATION` flag.

**Comment by ekluzek** [comment]
@gold2718 thanks for that. The most important thing for me was understanding if this was a CESM2.0 issue or not. I just wanted to make sure we had what was needed for CESM2.0 in place. Since, we do I'm happy.

I'm going to update my ctsm issue with what you say above. Feel free to add to it as well..

https://github.com/ESCOMP/ctsm/issues/378
