### ISSUE TITLE
With change in #2588, xmlquery sometimes doesn't give you an error when it should

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2593]
This is a minor issue, so I don't feel like it needs to be fixed for the CESM2 release, but I feel like it would eventually be good to fix this to work more robustly:

With the fix that @jedwards4b put in in #2588 , a new issue appears: If you xmlquery a non-existent variable with flag `--file`, you no longer get an error: e.g.:

```
$ ./xmlquery STOP_FOO --file env_run.xml
setting case file to env_run.xml
$ echo $?
0
```

(This still works fine - giving an error as expected - if you don't include the --file option.)

Since specifying --file in this single-variable usage of xmlquery seems uncommon, this doesn't feel critical to fix immediately.

From a quick look through the logic, I'm wondering if a better solution to #2580 would be to revert the logic on these lines to the pre-PR #2588 logic:

https://github.com/ESMCI/cime/blob/6c4b1524cd0cdab8257dc98ea6c7e6024a1ac9d9/scripts/Tools/xmlquery#L255-L258

and instead adding an option to `case.get_record_fields`, as called on this line:

https://github.com/ESMCI/cime/blob/6c4b1524cd0cdab8257dc98ea6c7e6024a1ac9d9/scripts/Tools/xmlquery#L286

to pass in an optional file; if specified, it would only query that file, rather than querying all files.

My understanding of the current --listall logic when --file is given is that it gets variables from all files, then builds up a result list containing just those variables in the given file; with the above suggestion, the subsetting on file would happen up-front. I'm not sure if this would work right, though.

**Comment by jedwards4b** [comment]
@billsacks thanks - this makes sense and I think I can still do it before the freeze tomorrow.
