### ISSUE TITLE
Problem with pio_rearr_comm_enable_hs

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#26]
Cases created by the python create_test are dying in case.setup due to this error:
```
% /home/jgfouca/cime_unified/driver_cpl/bld/build-namelist -infile /home/jgfouca/acme/scratch/TESTBUILDFAIL.f19_g16_rx1.A.melvin_gnu.doesnt_work/Buildconf/cplconf/namelist -caseroot /home/jgfouca/acme/scratch/TESTBUILDFAIL.f19_g16_rx1.A.melvin_gnu.doesnt_wo\
rk -cimeroot /home/jgfouca/cime_unified -grid a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%rx1_m%gx1v6_g%null_w%null -rof_grid rx1 -atm_grid 1.9x2.5  -lnd_grid 1.9x2.5 -ocn_grid gx1v6 -wav_grid null

build-namelist - ERROR: No default value found for pio_rearr_comm_enable_hs
user defined attributes:
key=PIO_REARR_COMM_ENABLE_HS  val=
```
In ACME's CIME, I see PIO_REARR_COMM_ENABLE_HS defined in env_run.xml, but with the shared CIME, the created case doesn't have that entry anywhere.

Any ideas? I'm dead in the water until I get past this.

**Comment by jgfouca** [comment]
I'll add that this entry used to be in Tools/config_definitions.xml, but apparently that file went away on the CSEG side.

**Comment by jedwards4b** [comment]
There is no such variable on the CESM side - this is something that Jayesh
added for pio1.

On Tue, Jan 12, 2016 at 11:01 AM, James Foucar <notifications@github.com>
wrote:

> I'll add that this entry used to be in Tools/config_definitions.xml, but
> apparently that file went away on the CSEG side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/26#issuecomment-170995754>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jgfouca** [comment]
@jedwards4b , thanks! Since ACME may need PIO1 for a while, is there any way to add it back?

**Comment by jedwards4b** [comment]
What was Tools/config_definitions.xml is now in
cime/driver_cpl/cime_config/config_component.xml

On Tue, Jan 12, 2016 at 11:08 AM, James Foucar <notifications@github.com>
wrote:

> @jedwards4b <https://github.com/jedwards4b> , thanks! Since ACME may need
> PIO1 for a while, is there any way to add it back?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/26#issuecomment-170997841>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
But I think that it makes more sense to add pio related variables to
/cime/cime_config/$model/machine/config_pio.xml

On Tue, Jan 12, 2016 at 11:13 AM, Jim Edwards <jedwards@ucar.edu> wrote:

> What was Tools/config_definitions.xml is now in
> cime/driver_cpl/cime_config/config_component.xml
>
> On Tue, Jan 12, 2016 at 11:08 AM, James Foucar <notifications@github.com>
> wrote:
>
>> @jedwards4b <https://github.com/jedwards4b> , thanks! Since ACME may
>> need PIO1 for a while, is there any way to add it back?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ESMCI/cime/issues/26#issuecomment-170997841>.
>>
>
>
>
> --
> Jim Edwards
>
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jgfouca** [comment]
Great, thanks for the advice.

**Comment by jgfouca** [comment]
I got past this error, but I had the put the values in config_component.xml. We can move/remove them later.
