### ISSUE TITLE
Add tools in scripts top directory to  tools_autodoc.py

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#2610]
This will permit links to be put into the cime user's guide that permits any changes to create_newcase, etc to be easily updated in the documentation.

**Comment by mvertens** [comment]
I have come up with a quick hack to this - so a more general approach can be done after the release.

**Comment by bertinia** [comment]
I have a programmatic fix for this in the tools_autodoc.py script that I'm working. @mvertens would you back out your hack, please? I'm finishing up the coding in tools_autodoc.py to also include the template files (template.case.run, template.case.test, template.st_archive) that @jedwards4b asked me to include.
