### ISSUE TITLE
Allow --mach default to come from .cime/config

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2621]
I think it's great that CIME can run on Macs with `--mach homebrew` and some generic linux configurations with `--mach centos7-linux`. It would be nice if I could add

```
MACH=homebrew
```

or

```
MACHINE=homebrew
```

to my `.cime/config` file rather than needed to remember the `--mach` option every time. @jedwards4b recommended

> you can add a .cime/config_machines.xml file with the homebrew section from config_machines.xml and rename it [machine name] then change NODENAME_REGEX to match your hostname

This is a reasonable workaround for a specific version of CIME, but if something changes in the `homebrew` section of config_machines.xml as part of the CIME development process then I need to remember to update the version of the file in `.cime/`; it would be much easier to have a way to just alias my hostname onto an existing machine in `config`.

**Comment by jgfouca** [comment]
FWIW, you can avoid having to use --mach everytime by setting the CIME_MACHINE env var.

**Comment by mnlevy1981** [comment]
@jgfouca 

> FWIW, you can avoid having to use --mach everytime by setting the CIME_MACHINE env var.

Thanks, I didn't know that! What's the reasoning behind what settings can come from the environment, what can come from `.cime/config`, and what can come from either place? (And for things that come from either place, what takes precedence if it is in both?)

**Comment by jgfouca** [comment]
@mnlevy1981 , machine should probably be settable in cime/config. I would expect environment vars to take precedence over cime/config.
