### ISSUE TITLE
E3SM testlist fails to validate

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2642]
I don't know if this matters as I thought it wasn't used for E3SM, but the allactive testlist for E3SM fails to validate against the XSD file.

xmllint --noout --schema cime/config/xml_schemas/testlist.xsd ./cime/config/e3sm/allactive/testlist_allactive.xml
./cime/config/e3sm/allactive/testlist_allactive.xml:2: element testlist: Schemas validity error : Element 'testlist': The attribute 'version' is required but missing.
./cime/config/e3sm/allactive/testlist_allactive.xml:3: element compset: Schemas validity error : Element 'compset': This element is not expected. Expected is ( test ).
./cime/config/e3sm/allactive/testlist_allactive.xml fails to validate

**Comment by rljacob** [comment]
That file should be deleted.

**Comment by ekluzek** [comment]
Looks like this is no longer an issue since there isn't a separation of cesm and e3sm for the xsd files.
