### ISSUE TITLE
PIO_NETCDF_FORMAT does not recognize 64bit_data setting

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2646]
Due to the ifdef at line 630 of shr_pio_mod.F90 
workaround is to add _PNETCDF to CPPDEFS in Macros.make in the case.

**Comment by jedwards4b** [comment]
We should remove this ifdef and set the default format to 64bit_data.

**Comment by ekluzek** [comment]
This is no longer an issue with cime, as share code has been moved outside. In CESM this issue seems to be handled correctly inside of CESM_share in shr_pcdf_mod.F90.
