### ISSUE TITLE
component ww3 buildnml has inputdata dependancy

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2649]
Component ww3 issues error 
           WAVEWATCH III ERROR IN W3IOGR : ERROR IN OPENING FILE
  Workaround:  The first time you run the ww3 buildnml script on a new system the data must be staged, but the staging step happens after the buildnml step.   Simply submitting the case again will
resolve the problem

**Comment by fischer-ncar** [comment]
Closed via PR #2650
