### ISSUE TITLE
Blues not getting env variables at runtime.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#265]
Using latest master 9a4db4dbecfe1671f6760760492820c1d288973e,
Create an X-case on blues:
 ./create_newcase -case Xcase3 -compset X -res f19_g16 -compiler intel
setup, build and submit

The jobs stops immediately after starting with this message in the pbs error file:
ERROR: must set CIMEROOT environment variable

**Comment by rljacob** [comment]
Workaround from @jayeshkrishna:  Add  <arg flag="-v" name="CIMEROOT=$CIMEROOT"/> to submit_args in env_batch.xml

**Comment by jayeshkrishna** [comment]
After explicitly passing CIMEROOT (via submit_args) the run fails due to other missing environment variables.
The permanent fix ( @jedwards4b is working on this) might be to re-introduce the "-V" PBS flag to export all environment variables from the login nodes to the compute nodes (job).

**Comment by rljacob** [comment]
Do the other missing env vars cause #266 ?
