### ISSUE TITLE
Passing arguments through LSF queues doesn't always work

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2672]
See issue E3SM-Project/E3SM#2390 
I have a temporary fix for this in E3SM, but would like to come up with a better one.
Also, the `K_TestCimeCase.test_cime_case_resubmit_immediate` in scripts_regression_tests isn't correct for LSF systems

**Comment by mfdeakin-sandia** [comment]
My temporary fix is in; I unfortunately don't think I have time before I move on to make a better one

**Comment by rljacob** [comment]
Anyone have lsf queues anymore?
