### ISSUE TITLE
CHARGE_ACCOUNT doesn't listen to --project flag

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2676]
I think this is a bug, but I don't really understand `CHARGE_ACCOUNT`, so I may be wrong:

If I do:

```
./create_test --no-build --project foo --test-root . SMS.f19_g16.X.cheyenne_intel
```

Then this is correct:

```
 ./xmlquery PROJECT

Results in group case.st_archive
	PROJECT: foo

Results in group case.test
	PROJECT: foo
```

but this is wrong:

```
./xmlquery CHARGE_ACCOUNT

Results in group case.st_archive
	CHARGE_ACCOUNT: P93300601

Results in group case.test
	CHARGE_ACCOUNT: P93300601
```

I would expect `CHARGE_ACCOUNT` to also be `foo` in this case.

It looks like the `--project` flag on the command-line never makes it into the logic used to determine `charge_account` (the `get_charge_account` call from `case.py`).

**Comment by sarich** [comment]
The --project command line argument will now set both PROJECT and CHARGE_ACCOUNT to the given value.
