### ISSUE TITLE
case.submit fails when some arguments have '%[A-Za-z]' in them

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2679]
case.submit previously allowed substituting things like the job id into strings, such as the batch job id. This now causes a failure.
For an example, see E3SM-Project/E3SM#2395

**Comment by rljacob** [comment]
The command in question:
"case.submit --batch-args --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j"

I tried to see what the --help command said about --output and...its not in the help.  I can't even find where that option is processed in https://github.com/E3SM-Project/E3SM/blob/master/cime/scripts/Tools/case.submit

**Comment by rljacob** [comment]
Oh is it because " --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j" is all one input to --batch-args ?

**Comment by mfdeakin-sandia** [comment]
Yes
