### ISSUE TITLE
Trouble(s) with multi-driver, specified dynamics, CAM-Chem

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2682]
@gold2718   Reassign as you will.

I've built a FCSD case with 2 instances in 
/glade/p/raeder/Exp/Chem_debug0.
The setup script is in .../cesmchem_ens_start.original
It uses a CESM2.0 which may be slightly modified for chemistry:
/glade/u/home/fvitt/camdev/pm2.5_n01_cam6_0_001.

It's dieing in the print out of one of the fields.
The character variable it's trying to print is dimensioned size (CXX=4096),
but is filled with "only" 1179 characters.
I've printed 100 characters at a time of the offending field 
from a modified seq_flds_mod.F90 in .../SourceMods/src.drv.

The case was run in /glade/scratch/raeder/Chem_debug0/run:

0:cesm.exe           00000000004978F4  seq_flds_mod_mp_s        3251  seq_flds_mod.F90
0:cesm.exe           000000000041E639  cime_comp_mod_mp_         869  cime_comp_mod.F90

 len(trim()) of seq_flds_l2x_states =         1179
   1 :Sl_avsdr:Sl_anidr:Sl_avsdf:Sl_anidf:Sl_tref:Sl_qref:Sl_t:Sl_fv:Sl_ram1:Sl_snowh:Sl_u10:Sl_tsrf00:Sl_t
 101 :tsrf01:Sl_tsrf02:Sl_tsrf03:Sl_tsrf04:Sl_tsrf05:Sl_tsrf06:Sl_tsrf07:Sl_tsrf08:Sl_tsrf09:Sl_tsrf10:Sl_t
 201 :topo00:Sl_topo01:Sl_topo02:Sl_topo03:Sl_topo04:Sl_topo05:Sl_topo06:Sl_topo07:Sl_topo08:Sl_topo09:Sl_t
 301 :topo10:Sl_dd001:Sl_dd002:Sl_dd003:Sl_dd004:Sl_dd005:Sl_dd006:Sl_dd007:Sl_dd008:Sl_dd009:Sl_dd010:Sl_d
 401 :dd011:Sl_dd012:Sl_dd013:Sl_dd014:Sl_dd015:Sl_dd016:Sl_dd017:Sl_dd018:Sl_dd019:Sl_dd020:Sl_dd021:Sl_dd
 501 :d022:Sl_dd023:Sl_dd024:Sl_dd025:Sl_dd026:Sl_dd027:Sl_dd028:Sl_dd029:Sl_dd030:Sl_dd031:Sl_dd032:Sl_dd0
 601 :033:Sl_dd034:Sl_dd035:Sl_dd036:Sl_dd037:Sl_dd038:Sl_dd039:Sl_dd040:Sl_dd041:Sl_dd042:Sl_dd043:Sl_dd04
 701 :44:Sl_dd045:Sl_dd046:Sl_dd047:Sl_dd048:Sl_dd049:Sl_dd050:Sl_dd051:Sl_dd052:Sl_dd053:Sl_dd054:Sl_dd055
 801 :5:Sl_dd056:Sl_dd057:Sl_dd058:Sl_dd059:Sl_dd060:Sl_dd061:Sl_dd062:Sl_dd063:Sl_dd064:Sl_dd065:Sl_dd066:
 901 ::Sl_dd067:Sl_dd068:Sl_dd069:Sl_dd070:Sl_dd071:Sl_dd072:Sl_dd073:Sl_dd074:Sl_dd075:Sl_dd076:Sl_dd077:S
1001 :Sl_dd078:Sl_dd079:Sl_dd080:Sl_dd081:Sl_dd082:Sl_dd083:Sl_dd084:Sl_dd085:Sl_dd086:Sl_dd087:Sl_dd088:Sl
1101 :l_dd089:Sl_dd090:Sl_dd091:Sl_dd092:Sl_dd093:Sl_dd094:Sl_dd095:Sl_dd096:Sl_dd097
1201 :                                 
1301 :                                           
1401 :                                           
1501 :                                           
1601 :                                 
1701 :                                           
1801 :                                           
1901 :                                 
2001 :                                 
2101 :                                 
2201 :                                 
2301 :                                 
2401 :                                                                                                     
2501 :             
2601 :                                                              
2701 :                                                               
2801 :                                                               
2901 :                                                                        
3001 :                                                                         
3101 :                                                                       
3201 :                                                               
3301 :                                                               
3401 :                                                               
3501 :                                                                                                     
3601 :              
3701 :                                                               
3801 :                                                                
3901 :                                                                

I don't know what all of the Sl_dd### variables are.
The ensemble size is only 2.  There are a lot of chemicals in the namelist.

**Comment by gold2718** [comment]
This appears to running off the end of the record. @jedwards4b, @mvertens, do we open the CESM (or any) logfile? I did not find an open statement and it appears there needs to be an open with a recl= statement. I have not seen this error before, perhaps someone changed the default system output record length in the system upgrade?

**Comment by jedwards4b** [comment]
It's output to stdout - I've not heard of any other errors of this nature.

**Comment by gold2718** [comment]
It is a little suspicious that this happened right after a Cheyenne system upgrade. How is the redirect to cesm.log.xxx handled? If we are not opening that file, it is probably using a system default record length which could have changed.

**Comment by jedwards4b** [comment]
There are a number of other factors to consider - can this be recreated with a single instance?  On the cesm2 release tag?

**Comment by kdraeder** [comment]
It did not happen in a single instance case I just ran:
/glade/scratch/raeder/Chem_debug1/run.

**Comment by kdraeder** [comment]
@jedwards4b @gold2718 
I reran the 2 instance case with prints to logunit of increasingly large
pieces of seq_flds_l2x_states.  It succeeded  at printing 256, 512, and 1024
characters, but failed again at printing the 1179 characters.
This is true for both drivers: 
/glade2/scratch2/raeder/Chem_debug0/run/ cpl_000[12].log.443629.chadmin1.180622-222713

**Comment by kdraeder** [comment]
@jedwards4b 
I rebuilt with the cesm2_0 that I downloaded from the CESM website.
It also fails with the message
0:forrtl: severe (66): output statement overflows record, unit 99, file /glade/scratch/raeder/Chem_debug2/run/cpl_0001.log.544707.chadmin1.180626-115608

**Comment by jedwards4b** [comment]
I haven't had a chance to look into this - but refactoring print statements is not very likely any time soon - perhaps you should check with CISL.

**Comment by kdraeder** [comment]
Here's another clue.
I ran the following test program interactively on a login node
and on a single processor of a share node.
It did write out everything, but I see that it will only write
1024 chars to a line.  It starts a new line for more characters.
That suggests that something in CESM is tripping the print
statement when it tries to write a new line.
---------
```
program tst

integer, parameter :: n = 4096
character(n) :: chr
character(1) :: fill
integer :: i

chr = '0'
do i = 1, 1179
   write(fill,'(i1)')mod(i,10)
   chr = trim(chr) // fill
end do

print *, '1:1024'
print *, chr(1:1024)
print *, '1:1025'
print *, chr(1:1025)
print *, 'trim (1179)'
print *, trim(chr)
print *, 'whole'
print *, chr
print *, 'end'

end
```
---------

**Comment by kdraeder** [comment]
This issue is fixed.
