### ISSUE TITLE
Improve config_machines.xsd

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2686]
The current schema allows the < mpirun > and < module_system > sections to be missing, but they are both required for cime usage.

**Comment by rljacob** [comment]
Telecon:  create_newcase --machine name  should give an error if the machine entry is missing those sections.

**Comment by jhkennedy** [comment]
@rljacob do you want an error only if the `--machine` option is given, or anytime a machine is instantiated that doesn't have those values?

**Comment by jedwards4b** [comment]
@jhkennedy It should be anytime those values are not provided.
