### ISSUE TITLE
Issue downloading data (wildcards not supported in HTTP)

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2699]
I was wanting to have a case download all of the data it needs. First create an empty tmp inputdata directory, set the DIN env vars.  However, I got error below which seems like a problem with wget and wildcards?

```
        Refcase not found in /global/cscratch1/sd/ndk/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01, will attempt to download from inputdata
          Model refcase missing file refdir = '/global/cscratch1/sd/ndk/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/'
        wget failed with output:  and errput Warning: wildcards not supported in HTTP.
        --2018-06-29 14:11:00--  https://web.lcrc.anl.gov/public/e3sm/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/*
        Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.74.23
        Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.74.23|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2018-06-29 14:11:00 ERROR 404: Not Found.
```

The test I was using: `SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6`

**Comment by jedwards4b** [comment]
The wget interface should recognize the path ends with a wildcard and use -r instead.

**Comment by jedwards4b** [comment]
@ndkeen - can you test this from my branch:
git@github.com:jedwards4b/cime.git
 * [new branch]      wget_fix -> wget_fix

**Comment by ndkeen** [comment]
I can get your branch, but not sure how best to make the reqd changes in my cime.

**Comment by jedwards4b** [comment]
You shouldn't have to - if my branch works for you I'll open a PR and it'll get there.

**Comment by ndkeen** [comment]
Well if I try to launch test from within that cime, I get 
```    Errors were:
        ERROR: Config file /global/cscratch1/sd/ndk/wacmy/cimewgetfix/../components/cam/cime_config/config_component.xml for component cam not found.
```

**Comment by jedwards4b** [comment]
put it in a subdirectory parallel to the cime you wish to replace - that is under the top level e3sm directory

**Comment by ndkeen** [comment]
It looks like that might have done something (copying over wget.py). Many files are not downloading due to others reasons on the server, not wget.

**Comment by ndkeen** [comment]
I also tried to copy this cime branch to be a parallel subdirectory and try from there.  

```    Case dir: /global/cscratch1/sd/ndk/acme_scratch/cori-knl/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6.wgetfix
    Errors were:
        NOTE: ignoring setting of rof2ocn_fmapname=idmap in seq_maps.rc
        ERROR: module command /opt/modules/default/bin/modulecmd python load craype PrgEnv-intel cray-mpich failed with message:
        /opt/modules/default/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
```

**Comment by jedwards4b** [comment]
are you satisfied that it solves the issue?

**Comment by ndkeen** [comment]
I suppose I can't say for sure yet as it hasn't run cleanly, but certainly the wget problem I was seeing previously seems to no longer be there.

**Comment by ndkeen** [comment]
It might have been failing because the inputdata directory had some directories there (e3sm_init).  Removing that and trying again I see different behavior.  However, now it appears to be wgetting more than we want. 

```
cori12% ls -l /global/cscratch1/sd/ndk/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/web.lcrc.anl.gov/public/e3sm/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/
total 16
drwxrwxr-x 3 ndk ndk 4096 Jul  3 15:31 ./
drwxrwxr-x 3 ndk ndk 4096 Jul  3 15:31 ../
drwxrwxr-x 2 ndk ndk 4096 Jul  3 15:34 0331-01-01/
-rw-rw-r-- 1 ndk ndk 2255 Jul  3 15:31 index.html
```

**Comment by ndkeen** [comment]
What to do next here?

**Comment by rljacob** [comment]
Jim is on vacation so probably have to wait for him to get back.

**Comment by jedwards4b** [comment]
@ndkeen what is the outstanding issue here?   It seems to be doing what it's intended to do - downloading the contents of the directory.

**Comment by rljacob** [comment]
@ndkeen need input or we close this.
