### ISSUE TITLE
Get ACME internal framework tests running

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#27]

**Comment by jgfouca** [comment]
@jedwards4b , another question. It looks like the env_mach_specific functionality has changed a lot on your side. The documentation says to change env_mach_specific.xml in the case directory, but I need the file to be automatically populated. How can I acheive this?

**Comment by jgfouca** [comment]
@jedwards4b , I think I figured it out. Looks like you guys put all the env_mach_specific stuff into config_machines.xml

**Comment by jgfouca** [comment]
ACME tests are running.

**Comment by mvertens** [comment]
Fantastic!
