### ISSUE TITLE
CESM2.0.0 -> CIME create_test documentation is out of date

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2707]
This is a follow-on to #2647.
http://www.cesm.ucar.edu/models/cesm2/
has a pointer to 
http://esmci.github.io/cime/users_guide/testing.html
which has not been updated since the release of CESM2.
So the extensive changes made to 
cime/doc/source/users_guide/testing.rst
(and possibly many others) are not easily available to users.
Is there a schedule for rebuilding and updating the online CIME documentation?

**Comment by billsacks** [comment]
I just rebuilt the documentation based on the head of the maint-5.6 branch. Do you want to see if it looks good now?

**Comment by kdraeder** [comment]
Thanks!  It looks right from my (limited) perspective.
If that's enough, I'll close it.

**Comment by billsacks** [comment]
Okay, great. I'll close this issue.
