### ISSUE TITLE
Hobart module clean-up broke cprnc

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2708]
Given all the module clean-up being done on hobart, building `cprnc` without loading any modules causes a build failure and building `cprnc` with (for example) intel but running it with the nag module loaded causes a run-time linking error. I think the easiest work-around is to just keep multiple `cprnc` executables around and point to the correct one in `env_test.xml`. To that end, I've built

```
/fs/cgd/csm/tools/cime/tools/cprnc/cprnc.gnu
/fs/cgd/csm/tools/cime/tools/cprnc/cprnc.intel
/fs/cgd/csm/tools/cime/tools/cprnc/cprnc.nag
```

so adding `.$COMPILER` to the end of `CCSM_CPRNC` should do the trick:

```
-    <CCSM_CPRNC>/fs/cgd/csm/tools/cime/tools/cprnc/cprnc</CCSM_CPRNC>
+    <CCSM_CPRNC>/fs/cgd/csm/tools/cime/tools/cprnc/cprnc.$COMPILER</CCSM_CPRNC>
```

Note that there is not a `cprnc.pgi` yet - something changed Friday afternoon and the PGI compiler is not working (it's a machine issue, not a CESM issue).

**Comment by fischer-ncar** [comment]
Closed via #2709
