### ISSUE TITLE
Where to put shared parameterization code

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2717]
Consider the following scenario:  Both MOM6 and POP2 are full ocean components in CESM.  They both use the CVMIX param which has its own repo.  Where should that repo live in the source code of a CIME-enabled model?

**Comment by jedwards4b** [comment]
We have solved that with the manage_externals program in cesm which allows us to point to a single cvmix which can be used by both mom and pop.

**Comment by rljacob** [comment]
Yes but where does manage_externals check out the code to?

**Comment by jedwards4b** [comment]
I created a top level directory in cesm - so it's outside cime:
cesm/libraries/CVmix 
cesm/libraries/FMS

**Comment by rljacob** [comment]
That makes sense.  I was thinking of putting them under e3sm/components but do we have a rule that things in "components" must be top level models that talk to the coupler?

**Comment by jedwards4b** [comment]
I think that's a convention that we should stick to.

**Comment by rljacob** [comment]
Other scenario:   What if MOM and POP need different versions of CVmix?   Or CAM and MOM need different versions of FMS?

Telecon:  we won't support that.  Component model developers have to settle on one version.
