### ISSUE TITLE
MODEL_VERSION isn't updated like it should be after case.build is called again

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2725]
MODEL_VERSION is figured out in the build phase, and is being properly set the first time that's done. But, it isn't being redone each time case.build is called after that.

**Comment by jedwards4b** [comment]
I don't think that it should be updated after the case is created.   Information about changes to model tags are recorded at each build in the CaseStatus file.

**Comment by ekluzek** [comment]
Well, it's equally wrong in the CaseStatus file. So you can't tell that you committed changes between builds. MODEL_VERSION also shows up on the history file and it would be nice to have it correct there as well. I think the CaseStatus file is probably correct for the externals, but must use MODEL_VERSION for the top level version and hence is wrong.

So I still say it's a bug. I'm happy to be the one that provides a fix for it.

As an aside it looks like CaseStatus has the tag information only for a non test case. Which I think is fine. I'm just noting that as a difference in behavior between tests and normal cases.

The use case for this is scientists who commit a few different things to their clone, and then run cases on each. They want to be able to see which case was run with which commit. I think this is a good usage that we should support.

**Comment by jedwards4b** [comment]
I don't understand your statement:
`it's equally wrong in the CaseStatus file'  I'm looking at a CaseStatus file.  Here is the initial build:
```

**Comment by jedwards4b** [comment]
```
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cvmix, marbl, cism, source_cism, rtm, cam, 
s   ./cime
        clean sandbox, maint-5.6 --> cime5.7.0
    ./components/cam
        clean sandbox, on cam1/trunk_tags/cam6_0_002/components/cam
    ./components/cice
        clean sandbox, on cice5_20180530
    ./components/cism
        clean sandbox, on cism2_1_60
    ./components/cism/source_cism
        clean sandbox, on 34642dfaad8687925b9ac35d7a11e658d367745f
    ./components/clm
        clean sandbox, on ctsm1.0.dev001
    ./components/clm/src/fates
        clean sandbox, on fates_s1.8.1_a3.0.0
    ./components/clm/tools/PTCLM
        clean sandbox, on PTCLM2_180611
    ./components/mosart
        clean sandbox, on release-cesm2.0.00
    ./components/pop
        clean sandbox, on pop2/trunk_tags/cesm_pop_2_1_20180614
    ./components/pop/externals/CVMix
        clean sandbox, on v0.90-beta
    ./components/pop/externals/MARBL
        clean sandbox, on cesm2.0-n02
    ./components/rtm
        clean sandbox, on release-cesm2.0.00
    ./components/ww3
        clean sandbox, on ww3/release_tags/ww3_cesm2_0_rel_01
```
I then switched the cam to cam6_0_003 and built again - I now see
```
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cvmix, marbl, cism, source_cism, rtm, cam, 
s   ./cime
        clean sandbox, maint-5.6 --> cime5.7.0
s   ./components/cam
        clean sandbox, cam1/trunk_tags/cam6_0_003/components/cam --> cam1/trunk_tags/cam6_0_002/components/cam
    ./components/cice
        clean sandbox, on cice5_20180530
    ./components/cism
        clean sandbox, on cism2_1_60
    ./components/cism/source_cism
        clean sandbox, on 34642dfaad8687925b9ac35d7a11e658d367745f
    ./components/clm
        clean sandbox, on ctsm1.0.dev001
    ./components/clm/src/fates
        clean sandbox, on fates_s1.8.1_a3.0.0
    ./components/clm/tools/PTCLM
        clean sandbox, on PTCLM2_180611
    ./components/mosart
        clean sandbox, on release-cesm2.0.00
    ./components/pop
        clean sandbox, on pop2/trunk_tags/cesm_pop_2_1_20180614
    ./components/pop/externals/CVMix
        clean sandbox, on v0.90-beta
    ./components/pop/externals/MARBL
        clean sandbox, on cesm2.0-n02
    ./components/rtm
        clean sandbox, on release-cesm2.0.00
    ./components/ww3
        clean sandbox, on ww3/release_tags/ww3_cesm2_0_rel_01
```
Which is what I expect.  So please give a detailed explanation of what you think that the problem is and enough information to reproduce it.

**Comment by ekluzek** [comment]
@jedwards4b as I said I thought the tag information for externals -- as you have demonstrated -- would be correct. But, the CaseStatus also writes a line on the CESM Version. That wasn't being updated at least for a case that @wwieder was doing. In your example what does it write out to CaseStatus for CESM version in each of the above builds?

**Comment by billsacks** [comment]
I think the confusion here is that @jedwards4b is thinking about a use case with CESM (in which case the version of the externals is pretty much all you care about), whereas @ekluzek is thinking about a use case with standalone CTSM – in which case you're generally most interested in the CTSM hash, which is reflected in MODEL_VERSION.

Maybe we should get together briefly to try to work this out?

**Comment by ekluzek** [comment]
@billsacks yes, that's accurate. @wwieder case looks like this...

git describe from his source code shows the following...

```
cd /gpfs/fs1/work/wwieder/ctsm/ctsm1.0.dev003
ctsm/ctsm1.0.dev003> git describe
ctsm1.0.dev004-4-g855e39
```

Which means he's done four commits since ctsm1.0.dev004 and the last one starts with 855e39.

What we'd like to be able to see is those commits to show up in the CaseStatus. What we do see in the case status is...

```
cd /gpfs/fs1/work/wwieder/ctsm/ctsm1.0.dev003/cime/scripts/clm50_ctsm1.0_HF_test1b
grep "CESM version" CaseStatus
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004
CESM version is ctsm1.0.dev004

```

What I expect to see is that there would be at least one build associated with each of the four commits. So you'd see it change from vanilla ctsm1.0dev004 to the first commit, second commit and so on. And since it shows up in the history files, he can then match the case he ran with the code that was committed. Having that capability means scientists are more likely to use git in their workflow and to be able to use it in a way that's useful.

I'm up for having an in face meeting if that's useful.

**Comment by billsacks** [comment]
@ekluzek - I just talked with @jedwards4b . As long as your proposed changes wouldn't change behavior for his CESM use case (which I don't think it would), and wouldn't negatively impact E3SM (which I'm unclear on), then he seemed fine with your suggestion of updating `MODEL_VERSION` to reflect the current hash at build time. (@jedwards4b I hope I'm summarizing this correctly.)

I guess there is still a somewhat arbitrary choice that is needed as to what phase sets `MODEL_VERSION`. You're suggesting the build, I think, and I agree that that probably makes as much sense as anything. This would give you some wrong information if you: (1) built the model, (2) updated to a commit that changed some namelist defaults, (3) submitted the model (in which case you'd want `MODEL_VERSION` to be updated at submit time). But it does seem like the version at build time is most often what scientists will be interested in.
