### ISSUE TITLE
Comment at the top of env_batch.xml is wrong

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2731]
The comment at the top of env_batch.xml (imported from config/config_headers.xml) is:

>       These variables may be changed anytime during a run, they
>       control arguments to the batch submit command.
> 
However, if I submit a job and then try:
```
./xmlchange JOB_WALLCLOCK_TIME=40:00:00
./xmlchange JOB_QUEUE=long
```
My job is killed (if it is in the queue when I make the change) or resubmit fails and I see the following message in my output file:
```
goldy@hobart^GFile /scratch/cluster/goldy/FQ3D_ne5pg3_ne5pg3_mg37/LockedFiles/env_batch.xml has been modified
  found difference in JOB_WALLCLOCK_TIME : case '40:00:00' locked '80:00:00'
  found difference in USER_REQUESTED_WALLTIME : case '40:00:00' locked ''
ERROR: Batch configuration has changed, please run case.setup --reset
```
The CIME documentation does not seem to mention this ability to change (cf http://esmci.github.io/cime/users_guide/running-a-case.html?highlight=job_wallclock_time).

Please fix the header with correct information.

Question: Is there a way to see the `<header>` information via `xmlquery`?

Reported by a CESM 2.0 user.

**Comment by gold2718** [comment]
I ran a new case (in /scratch/cluster/goldy/FKESSLER_f19_f19_mg17) and while the first run was running tried:
```
./xmlchange JOB_QUEUE=medium
```
However, when the next run started up, it crashed with the following output:
> goldy@hobart File /scratch/cluster/goldy/FKESSLER_f19_f19_mg17/LockedFiles/env_batch.xml has been modified
>   found difference in JOB_QUEUE : case 'medium' locked 'long'
>   found difference in USER_REQUESTED_QUEUE : case 'medium' locked 'long'
> ERROR: Batch configuration has changed, please run case.setup --reset
> -------------------- Post Job Clean Up --------------------
>

**Comment by jedwards4b** [comment]
You must run case.setup --reset when changing the JOB_QUEUE.  The issue here is that the number of mpi tasks must be specified in the PBS (or other scheduler) code at the top of the run script and changing the queue may change the allowed number of tasks.

**Comment by gold2718** [comment]
This does not work during a run. The resubmit notices the reset and reports:
```
goldy@hobart ERROR: BUILD_COMPLETE is not true
Please rebuild the model interactively
```
However, note that if instead of `./case.setup --reset`, I change the queue and then hit `./case.submit`, I get the following:
```
File /scratch/cluster/goldy/FKESSLER_f19_f19_mg17/LockedFiles/env_batch.xml has been modified
  found difference in JOB_QUEUE : case 'medium' locked 'long'
  found difference in USER_REQUESTED_QUEUE : case 'medium' locked 'long'

env_batch.xml appears to have changed, regenerating batch scripts
manual edits to these file will be lost!
```
Then the job is changed and resubmitted to the requested queue. Can something like that be done on resubmit?
