### ISSUE TITLE
Request for short-term archiving of CAM initial data files

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2732]
A query from a CESM 2.0 user:

> The cam namelist includes an option for inithist, which can be used to
> control the frequency of generation for the IC files.  We often set
> inithist='DAILY', because we use these files for perturbation experiments.
> A long time ago, before CIME existed, if IC files were generated that
> didn't belong to a set of restart files the short term archive moved them
> to a casename/atm/init directory.  Since the switch to CIME, that's no
> longer an option.  In fact by default the IC files not associated with a
> restart set don't get archived at all; they get left in the run directory.  I
> figured out that I can add a hist_file_extension entry for these files in
> env_archive.xml, and they'll get archived to the casename/atm/hist
> directory.  That's better than leaving them in the run directory, but to me
> they are distinct from the casename.cam.h# files, so it's not an entirely
> satisfactory solution.  Was this a deliberate decision, or just an accident?
> Maybe nobody there is generating or paying attention to these files ...  Is 
> there a better way to handle these files?

Is this intentional? Is this a weird case because CAM initial data files are different from restart files? Is there a solution we can implement?

**Comment by jedwards4b** [comment]
The problem is that as currently written in cam/cime_config/config_archive.xml
```
      <rest_file_extension>[ri]</rest_file_extension>
```
does not distinguish .r. and .i. as distinct extensions.   The solution is to have separate entries:
```
      <rest_file_extension>r</rest_file_extension>
      <rest_file_extension>i</rest_file_extension>
```
this is a cam issue and should be moved there.   @cacraigucar

**Comment by jedwards4b** [comment]
I ran test IRT_Ld11.f19_f19.FHIST.cheyenne_intel with 
inithist='DAILY' 
in user_nl_cam and note that even with the cam change suggested above I do not archive cam.i. files except at restart times.   I will reopen and investigate.

**Comment by jedwards4b** [comment]
The fix still is in cams config_archive.xml file
replace
```
       <rest_file_extension>[ri]</rest_file_extension>
```
with
```
      <rest_file_extension>r</rest_file_extension>
       <hist_file_extension>i\..*\.nc$</hist_file_extension>
```
and remove line
```
  <tfile disposition="ignore">anothercasename.cam.i.1976-01-01-00000.nc</tfile>
```

**Comment by gold2718** [comment]
Does this put the initial files with the history files or with the restart files?

**Comment by jedwards4b** [comment]
With history files, which I think is the correct location since they are not needed for restart.

**Comment by gold2718** [comment]
They are used for post data-assimilation restart.

**Comment by jedwards4b** [comment]
in that case are they concurent with the restart cycle?  Perhaps adding
```
<rest_file_extension>i</rest_file_extension>
```  
in addition to the above would solve the problem?

**Comment by gold2718** [comment]
No, it is more like a CAPT situation where you do a run, manipulate the .i. files, and then restart from different modified .i. files.

**Comment by jedwards4b** [comment]
So when they do the run they don't write restart files?   If not then they could look in the archive hist directory for the cam.i files.  Otherwise case_st_archive.py will need some major reworking to account for this use case that wasn't considered during the original construction of that file.

**Comment by gold2718** [comment]
Thanks for the info.

**Comment by brian-eaton** [comment]
In addition to the suggested fix it was also necessary to:
change
      <tfile disposition="copy">casename.cam.i.1976-01-01-00000.nc</tfile>
to
      <tfile disposition="move">casename.cam.i.1976-01-01-00000.nc</tfile>

This was committed to cam6_0_011.

**Comment by jedwards4b** [comment]
@brian-eaton Thanks.

**Comment by brian-eaton** [comment]
Sorry, I didn't notice that the xml got stripped out of what I pasted.  The difference is that the disposition attribute value changed from "copy" to "move" in the tfile elements.  Just for practice I'm going to try that again using the 'insert code' button:

`change
      <tfile disposition="copy">casename.cam.i.1976-01-01-00000.nc</tfile>
  to
      <tfile disposition="move">casename.cam.i.1976-01-01-00000.nc</tfile>
`

**Comment by brian-eaton** [comment]
Hmmm.  Not sure why the code option isn't respecting the whitespace...

**Comment by gold2718** [comment]
You can use preview to check what will happen. I fixed your entry, see the raw entry where I used triple backquotes on a separate line to make a code block. The code button only gives you a code formatting without making it verbatim.
