### ISSUE TITLE
No checks for python version and unhelpful error messages

### ISSUE THREAD

**Issue by brhillman** [ESMCI/cime#2734]
CIME implicitly requires Python 2, but there do not appear to be any checks for Python version in use. This seems to lead to some pretty misleading and unhelpful error messages when the wrong version of Python (i.e., 3.x) is accidentally used. In my case, I need to explicitly load the proper Python module before trying to use any of the CIME build and run scripts, or I run into some misleading errors. For example, if I try to run `case.build` without first loading the Python 2.7.9 module in my environment, I get the following error:
```
ERROR: Command: './generate_cice_decomp.pl -ccsmroot /home/bhillma/codes/e3sm/branches/add-rrtmgp -res ne4np4 -nx 866 -n
y 1 -nproc 16.0 -thrds 1 -output all' failed with error 'b'Value "16.0" invalid for option nproc (number expected)\nSYNO
PSIS\n     generate_cice_decomp.pl [options]\nOPTIONS\n     -ccsmroot <path>               Full pathname for ccsmroot\n 
                                   (required)\n     -nproc <number>      (or -n)   Number of mpi tasks used.\t\n        
                            (required)\n     -nx <number>                   number of lons \n                           
         (optional, default is 320)\n     -ny <number>                   number of lats\n                               
     (optional, default is 384)\n     -res <resolution>    (or -r)   Horizontal resolution \n                           
         (optional, default gx1v6)\n     -thrds <number>      (or -t)   Number of threads per mpi task\n                
                    (optional, default 1)\n     -output <type>\t  (or -o)   Either output: all, maxblocks, bsize-x, bsiz
e-y, or decomptype\n\t\t\t            (optional, default all)\n\nEXAMPLES\n\n   generate_cice_decomp.pl -res gx1v6 -nx 3
20 -ny 384  -nproc 80 -output maxblocks\n\n   will return a single value -- t
```
The actual error is that things seem to be parsed differently here in Python 2 vs Python 3, but it would be most useful to have a check at the beginning that made sure the user was invoking the script with the correct Python version if the code requires that.

**Comment by jedwards4b** [comment]
Actually cime itself is python 3 compliant and should be independent of python version.  The error you have encountered is a bug in the python 3 implementation.    Having said that most of the python code in components external to cime have not been ported to python 3.

**Comment by jedwards4b** [comment]
Actually generate_cice_decomp.pl is called by cice/cime_config_buildcpp and is outside the domain of cime - this issue should be reported to the cice developers.  https://github.com/ESCOMP/CESM_CICE5/issues

**Comment by brhillman** [comment]
Okay cool, thanks @jedwards4b. I will copy this over there.
