### ISSUE TITLE
cpl avg hist and aux hist files not archived?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2735]
I haven't confirmed this is an issue, but from looking at https://github.com/ESMCI/cime/blob/4f41034b08cf9922224bb412b0e9ad0b9f5e675a/src/drivers/mct/cime_config/config_archive.xml#L4

it looks like we currently aren't archiving cpl avg hist (.ha) or aux hist files.

(With the changes in #2728 , this means those also wouldn't be picked up in system test comparisons, if we had any system tests that produced those files, which we probably don't yet but may in the future.)

**Comment by klindsay28** [comment]
Cecile turned on cpl aux hist files for a stretch in
b.e20.B1850.f09_g17.pi_control.all.297
and they were picked up by the short-term archiver.

An example st_archive logfile of this working is
$CASEROOT/b.e20.B1850.f09_g17.pi_control.all.297.st_archive.o8613120, where
CASEROOT=/glade/p/cesm/cseg/runs/cesm2_0/b.e20.B1850.
f09_g17.pi_control.all.297_yrs1-139

The settings that were used to generate the additional histaux output,
currently in $CASEROOT/user_nl_cpl~, were
histaux_a2x24hr = .true.
histaux_a2x3hr = .true.
histaux_a2x1hri= .true.
histaux_a2x1hr = .true.
histaux_r2x = .true.

**Comment by billsacks** [comment]
Thanks, @klindsay28 . Now that I look closely at the regex, it looks like the`?` and `*` mean that it might as well be `h.*\.nc$`, so I see why things are working as is.
