### ISSUE TITLE
remove Buildconf/refcase.input_data_list automatically when setting GET_REFCASE to false

### ISSUE THREAD

**Issue by lvankampenhout** [ESMCI/cime#2737]
When changing GET_REFCASE (env_run.xml) from "TRUE" to "FALSE", the file `Buildconf/refcase.input_data_list` is left intact. In my case this led to submit failures, because the referenced case was not found. The workaround is to remove `Buildconf/refcase.input_data_list` manually.

**Comment by jedwards4b** [comment]
This has already been addressed in PR #2648

**Comment by lvankampenhout** [comment]
OK great, sorry for the bother Jim.
