### ISSUE TITLE
Components should enter 'pause' filename as resume entry

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2739]
Currently, the data ESP component (and future active ESP components) must get their information on a component's pause file(s) from that component's rpointer file. However, the data assimilation 'pause' file currently under design by CAM will not be a restart file but a special file containing only state fields needed by ESP components such as DART.
Components need an easy way to pass the name of the file written in response a pause signal to the ESP component.
At the same time, the ESP component needs to be able to have access to and gather these filenames from all component instances.

**Comment by jedwards4b** [comment]
It might be easier to agree on a syntax for the filename than to implement a mechanism to share names.

**Comment by gold2718** [comment]
There already is a mechanism -- the `<comp>_resume` field.
While this field is easy to use, its current incarnation has gotten really clunky due to the implementation of multi_driver. I would like to refactor the resume signaling mechanism to be clear and extensible. The only downside of the new approach is that it will require a small code adjustment in CLM and CAM. I think this is a worthwhile trade-off to clean up from the rushed pre-2.0 implementation.
