### ISSUE TITLE
DATM_MODE of 'CPLHIST' resulting in datamode 'COPYALL' 

### ISSUE THREAD

**Issue by timhoar** [ESMCI/cime#2741]
Section 6.3 of http://esmci.github.io/cime/data_models/data-atm.html indicates that
a DATM_MODE of CPLHIST is supposed to result in a datamode of CPLHIST, but that is not happening.
I am getting a datamode of 'COPYALL'

&shr_strdata_nml
datamode = "COPYALL"
domainfile = "null"
dtlimit = 3.0, 3.0, 3.0, 3.0, 1.5, 1.5
fillalgo = "nn", "nn", "nn", "nn", "nn", "nn"
fillmask = "nomask", "nomask", "nomask", "nomask", "nomask", "nomask"
fillread = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
fillwrite = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
mapalgo = "bilinear", "bilinear", "bilinear", "bilinear", "bilinear",
"bilinear"
mapmask = 'nomask', 'nomask', 'nomask', 'nomask', "nomask", "nomask"
mapread = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
mapwrite = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
readmode = "single", "single", "single", "single", "single", "single"
streams = 'datm.streams.txt.CPLHISTForcing.Solar_0002 1998 1998 2010',
'datm.streams.txt.CPLHISTForcing.nonSolarFlux_0002 1998 1998 2010',
'datm.streams.txt.CPLHISTForcing.State1hr_0002 1998 1998 2010',
'datm.streams.txt.CPLHISTForcing.State3hr_0002 1998 1998 2010',
'datm.streams.txt.presaero.clim_2000_0002 1 1 1',
"datm.streams.txt.topo.observed_0002 1 1 1"

This issue is also mentioned in ESCOMP/ctsm#473

My compset is 2000_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_SGLC_SWAV
and for those with access to cheyenne, the RUNDIR is 
/glade/scratch/thoar/ctsm/clm5_f09_freerun80/run

**Comment by jedwards4b** [comment]
@mvertens I've had a look at this and the documentation is not aligned with the code - which should it be?

**Comment by timhoar** [comment]
Even after you align the two ... I have a question about using a
user-derived  DATM at a resolution other than one for the active component.

I set

./xmlchange
DATM_CPLHIST_DOMAIN_FILE=/glade/p_old/image/thoar/CAM_DATM/4xdaily/CAM_DATM.cpl_0001.ha2x1dx6h.
2001.nc

and the resulting datm_in_0001  has a valid domainfile,

&shr_strdata_nml

  datamode = "COPYALL"

  domainfile = "/glade/p_old/image/thoar/CAM_DATM/4xdaily/
CAM_DATM.cpl_0001.ha2x1dx6h.2001.nc"

 but then generates the following error:   I have looked through the list
of variables that are supposed to be in the domainfile (according to the
table in section 6.5)
but cannot find a variable 'xc' ... and (naturally) there is no 'xc'
variable in my (trusty) old DATM files.


0: ERROR: (shr_ncread_varDimNum) ERROR inq varid: xc

0:Image              PC                Routine            Line        Source

0:cesm.exe           00000000015BB11D  Unknown               Unknown
Unknown

0:cesm.exe           0000000000D411A2  shr_abort_mod_mp_         114
shr_abort_mod.F90

0:cesm.exe           0000000000E459BC  shr_ncread_mod_mp        1807
shr_ncread_mod.F90

0:cesm.exe           0000000000DDE5F0  shr_dmodel_mod_mp         350
shr_dmodel_mod.F90

0:cesm.exe           0000000000E8601C  shr_strdata_mod_m         410
shr_strdata_mod.F90

0:cesm.exe           00000000004E5267  datm_comp_mod_mp_         303
datm_comp_mod.F90

0:cesm.exe           00000000004DD729  atm_comp_mct_mp_a         167
atm_comp_mct.F90

0:cesm.exe           0000000000427428  component_mod_mp_         267
component_mod.F90

0:cesm.exe           00000000004169FB  cime_comp_mod_mp_        1175
cime_comp_mod.F90

0:cesm.exe           0000000000424652  MAIN__                     92
cime_driver.F90

0:cesm.exe           00000000004080DE  Unknown               Unknown
Unknown

0:libc-2.19.so       00002AAAB04DCB25  __libc_start_main     Unknown
Unknown

0:cesm.exe           0000000000407FE9  Unknown               Unknown
Unknown

0:MPT ERROR: Rank 0(g:0) is aborting with error code 1001.

0:      Process ID: 35334, Host: r2i1n10, Program:
/glade2/scratch2/thoar/ctsm/clm5.0.06_f09_freerun80/bld/cesm.exe

0:      MPT Version: HPE MPT 2.16  05/03/17 01:07:48

0:

0:MPT: --------stack traceback-------


My RUNDIR is :  /glade2/scratch2/thoar/ctsm/clm5.0.06_f09_freerun80/run
based off

*0[1588]* cheyenne4:/<4>CESM/ctsm > git status

HEAD detached at release-clm5.0.06

nothing to commit, working directory clean


Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

**Comment by billsacks** [comment]
A similar issue may or may not exist in CDEPS, but I'll be optimistic and assume it doesn't until proven otherwise... so closing this.
