### ISSUE TITLE
Should we support one or more scripts for quickly parsing output from large test suites?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2749]
We're trying to get more CTSM developers to run the full aux_clm test suite. One aspect of making this easier is providing a robust, easy-to-use mechanism for parsing the results of a large test suite to determine what has failed.

I wrote a simple script a few years ago that I use all the time for this purpose (https://github.com/billsacks/bin/blob/master/filter_cs_status). My workflow is (1) Run the appropriate cs.status script(s) for the test suite I ran; (2) Run `filter_cs_status` on the output from each. (I like having these two steps separated, because (1) can take a while on large test suites, and I often rerun (2) a few times for each test suite, excluding various things each time.) [Update 2018-08-14: cs.status seems to run fast enough that these don't really need to be separated. And for the sake of new users, it would be nice if this were built into cs.status.]

It's basically a glorified `grep -v`, with the added benefits that (1) There are a few hard-coded patterns that it always ignores (lines with 'Overall...' and 'PASS'; I also generally ignore TPUTCOMP and MEMCOMP, but that wouldn't need to be the case); (2) It prints counts of the number of lines matching each ignore pattern (so, for example, you can see if _everything_ had a TPUTCOMP failure, or just a few tests).

I'm wondering if I should put this script in cime. (I'd be happy to rewrite it in python.) Would others find this useful? If not, is there another, similar script that is already supported or should be supported for this purpose? There's the old cimeteststatus script, but my sense is that this no longer works with cime5. (Should we delete the old cimeteststatus script?)

**Comment by billsacks** [comment]
By the way, here's some example output from `filter_cs_status`:

```
[cheyenne4:/glade/scratch/sacks/tests_0804_2122c]$ filter_cs_status < cs.i
========================================================================
0804_2122c_i
    FAIL ERI_N2_Ld9.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-default BASELINE ctsm1.0.dev006
    FAIL ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart RUN time=105
    FAIL ERP_D_Ld5.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay RUN time=21
    FAIL SMS_Lm13.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev006
========================================================================
Ignored lines:
   ^\s*$ : 2
   \(Overall:.*details: : 156
   ^ *PASS : 2140
    TPUTCOMP  : 1
    MEMCOMP  : 8
[cheyenne4:/glade/scratch/sacks/tests_0804_2122c]$ filter_cs_status BASELINE < cs.i
========================================================================
0804_2122c_i
    FAIL ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart RUN time=105
    FAIL ERP_D_Ld5.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay RUN time=21
========================================================================
Ignored lines:
   ^\s*$ : 2
   \(Overall:.*details: : 156
   ^ *PASS : 2140
    TPUTCOMP  : 1
    MEMCOMP  : 8
   BASELINE : 2
```

**Comment by ekluzek** [comment]
There's also this script in ctsm that sounds like it does essentially the same thing:

https://github.com/ESCOMP/ctsm/blob/master/parse_cime.cs.status

It's in perl, but's small enough it could be changed.
And here's some sample output that it creates for summary mode (which is how I normally use it):

```
scripts/cases> ../../../parse_cime.cs.status cs.status.ctsm10dev008ch* -s
================================================================================
Test summary
191 Total tests
188 Tests passed
36 Tests compare different to baseline
0 Tests are new where there is no baseline
1 Tests pending
2 Tests failed
================================================================================
================================================================================
These tests passed
================================================================================
DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv			
ERI_D_Ld9.T31_g37.I2000Clm50Sp.cheyenne_intel.clm-SNICARFRC			
ERI_D_Ld9.f09_g16.I1850Clm45BgcCruGs.cheyenne_intel.clm-default			
ERI_D_Ld9.f09_g16.I1850Clm50Sp.cheyenne_intel.clm-default			
.
.
.			
ERP_D_Ld5.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay			FAILED PREVIOUSLY
ERP_D_Ld5.f10_f10_musgs.I2000Clm50BgcCruGs.cheyenne_gnu.clm-ciso_flexCN_FUN			
ERP_D_Ld5.f10_f10_musgs.I2000Clm50BgcCruGs.cheyenne_intel.clm-NoVSNoNI			
ERP_D_Ld5.f10_f10_musgs.I2000Clm50BgcCruGs.cheyenne_intel.clm-rootlit			
.
.
.	
SSP_D_Ld4.f09_g17.I1850Clm50BgcCrop.cheyenne_intel.clm-ciso_rtmColdSSP			
SSP_Ld10.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-rtmColdSSP			
================================================================================
These tests compare different to the baseline
================================================================================
ERI_D_Ld9.f10_f10_musgs.I1850Clm50Bgc.cheyenne_gnu.clm-default
ERI_Ld9.f09_g17.I1850Clm50Bgc.cheyenne_intel.clm-drydepnomegan
ERP_D_Ld5.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay
ERP_D_Ld5.f19_g17_gl4.I1850Clm50BgcCrop.cheyenne_intel.clm-glcMEC_changeFlags
ERP_D_Ld5.f19_g17_gl4.I1850Clm50BgcCropG.cheyenne_intel.clm-glcMEC_changeFlags
.
.
.
SMS_Lm1.f19_g17_gl4.I1850Clm50Bgc.cheyenne_intel.clm-clm50dynroots
SSP_D_Ld10.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-rtmColdSSP
SSP_D_Ld4.f09_g17.I1850Clm50BgcCrop.cheyenne_intel.clm-ciso_rtmColdSSP
SSP_Ld10.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-rtmColdSSP
================================================================================
These tests are pending (some tests may fail in the pending state)
================================================================================
ERS_Lm40_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.cheyenne_gnu.clm-monthly		
================================================================================
These tests failed
================================================================================
ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart		EXPECTED
ERS_Lm20_Mmpi-serial.1x1_smallvilleIA.I2000Clm50BgcCropGs.cheyenne_gnu.clm-monthly		EXPECTED

```

**Comment by jgfouca** [comment]
Don't forgot CIME's wait_for_tests script/library.

**Comment by billsacks** [comment]
Okay, as I should have realized, we all have different workflows and scripts that work well for our workflow and the way we want to see test results summarized. Do people have any feelings as to whether I move my `filter_cs_status` script into cime/scripts/Tools, or maintain it outside of cime? (My preference would be to move it into cime, and I would add some documentation of this as one option for parsing test results. But I'm okay with keeping it out of cime if others would prefer that cime not get cluttered in this way.)

**Comment by billsacks** [comment]
I've given this more thought, and also looked at tools used by @ekluzek and @mnlevy1981 , and I'd like to propose the following requirements:

1. **This parsing / filtering ability should be built in to cs.status.** We've been having trouble getting CTSM scientists to adopt the test suite, so I want to make this as easy as possible. Since cs.status already appears in the test directory, and already has the basic functionality we need, this seems like the simplest option for new users, rather than requiring them to know about yet another script.

2. **It should be possible to see, at a glance, everything that has failed (not having to visually sift through output).** What I find easiest to work with, as a starting point, is a list of just the non-passing lines from all of the relevant TestStatus files. (There can be more than one such line for a given test, e.g., if there are NLCOMP failures and BASELINE failures.) So if you have a fully-passing test suite, you should have very minimal (or no) output. Others seem to prefer to see more information, but to have passes listed separately from failures; that's okay with me, too.

3. **It should be easy to filter out particular failures, but with these filtered failures still appearing in some way.** For example, if baselines are expected to fail, it should be easy to either (a) just see a count of baseline failures, or (b) have baseline failures listed separately from other failures.

As a starting point, I'd like to propose the following implementation, which I feel would be fairly simple to implement and maintain:

1. Add an option to cs.status like `-f` / `--fails-only` (maybe a misnomer, because this really would include PENDs as well as FAILs; I'm not tied to this name). If provided, this would only output lines from the TestStatus files that do not have a PASS status.

   I think this could be implemented simply by having an optional argument to ts.phase_statuses_dump (skip_passes=True), which would avoid giving output for any phase with a PASS status.

2. Add another option to cs.status, `-c PHASE` / `--count-fails PHASE`, where PHASE is any of the phases in `ALL_PHASES` in `test_status.py`. This can be provided multiple times. For any of the given phases: We do not include the line-by-line output from this phase, but instead give a summary count of the number of tests that failed this phase.

   I think this could be implemented fairly easily, by having a bit more logic in `phase_status_dump`, and then having a new routine in `test_status.py`: `phase_status_count_failures(self, counts)`, where counts is a dictionary of counts for each phase of interest; each failure in a phase of interest increments the given count. Then, at the bottom of the cs.status output, we'd print the counts for each listed phase.

3. Add an option to cs.status, `--count-comp-fails`. This is a short-hand for `--count-failures MEMCOMP --count-failures TPUTCOMP`, because this is something we commonly do for the CTSM test suite (since those failures are often false positives).


With all that, a typical CTSM user would run:

`./cs.status.0804_2122c_i --count-comp-fails`, and would get output like:

```
    FAIL ERI_N2_Ld9.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-default BASELINE ctsm1.0.dev006
    FAIL ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart RUN time=105
    FAIL ERP_D_Ld5.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay RUN time=21
    FAIL SMS_Lm13.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev006
========================================================================
Additional failure counts:
    TPUTCOMP  : 1
    MEMCOMP  : 8
```

**Comment by billsacks** [comment]
@jgfouca and others: If you're okay with my proposal in the comment I just made, I'm happy to take this on myself (I'm not asking you or anyone else to do this).

**Comment by jgfouca** [comment]
@billsacks , I think that looks like a good idea.

**Comment by billsacks** [comment]
@jgfouca thanks. I'll take a stab at this soon.
