### ISSUE TITLE
CPL water budget incorrect for I-compset

### ISSUE THREAD

**Issue by bishtgautam** [ESMCI/cime#2756]
For `--res 1x1_brazil --comp I1850CLM45`, coupler reported an incosistent rain budget between land and atmosphere components. 

```
(seq_diag_print_mct) NET WATER BUDGET (kg/m2s*1e6): period =  monthly: date =     10201     0
                           atm            lnd            rof            ocn         ice nh         ice sh            glc        *SUM*
         wfreeze     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
           wmelt     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
           wrain    -0.01514783     0.01515018     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000235
           wsnow     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
           wevap     0.00000000    -0.00329974     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000    -0.00329974
        weqsaltf     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
         wrunoff     0.00000000    -0.00059101     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000    -0.00059101
         wfrzrof     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
           *SUM*    -0.01514783     0.01125943     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000    -0.00388840
```

In `cime_run()`, the call sequence for land, atm, and budget diagnositics are: 
1. `component_run(..., lnd_run)`
2. `call seq_diag_lnd_mct()`
3. `component_run(..., atm_run)`
4. `call seq_diag_atm_mct()`

The incosnstinecy in rain budget between land and atmosphere component is becuase `seq_diag_atm_mct()` is called after `component_run(..., atm_run)`, which results in 
atmosphere water budget diagnostics using values corresponding to the next
model time step. When I added a call to `seq_diag_atm_mct()` before `component_run(..., atm_run)`, the water budget were consistent between the two components. I'm not sure if the order of calls should only be changed for a data-atmosphere model and active atmosphere component.

cc: @rljacob

**Comment by rljacob** [comment]
I think you're right and those calls to the diags need to be together.  It shouldn't matter if there's a data model or fully coupled.  Asking @mvertens and @billsacks for confirmation.

**Comment by billsacks** [comment]
I don't know enough about this to weigh in. My impression was that you generally can't expect budget values to match exactly because of lags in the system, but I'm not sure what design (if any) underlies the placement of the various diag calls relative to the run calls.

**Comment by bishtgautam** [comment]
The order of `call component_run()` is:

1. ice
2. lnd
3. rof
4. wav
5. ocn
6. atm
7. glc
8. esp

If the call to atmosphere component was the last one, calling diags before running the atmosphere model should fix the inconsistency of diag budgets being computed by the coupler as all componets would have run with using the same atmospheric forcing. But, since glc and esp components run after the atmosphere model, I guess there is no way to ensure that the diag budgets for all components is consistent.

**Comment by rljacob** [comment]
@billsacks is right that the total budget will not add up on a given coupler step because of the lagging with the ocean.  In your example above, the ocean hasn't reported yet.

@bishtgautam  the I-case uses a different sequencing from the fully coupled case (in E3SM) which can also affect what we decide here.

**Comment by billsacks** [comment]
@bishtgautam can this be closed, or do you feel something should still be done about it?

**Comment by bishtgautam** [comment]
The issue can be closed.
