### ISSUE TITLE
Copy TestStatus file to the baseline directory

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2760]
I often find myself wanting to know if a given test passed or failed (entirely or some specific phase) in a previous run of the test suite, for which we have baselines. For example, this would be a quick way of seeing if a test failed the last time around, or it can help indicate if / why there might be problems with the baselines for a given test.

So it would be helpful if the TestStatus file were copied to the baseline directory when running a test suite with the `--generate` flag.

There are a few things I'm not sure of in terms of how this should be implemented:

1. If we copy the TestStatus file in the generate phase (which seems like a logical time to do it), it would be missing some information, since generate comes before some other phases. Would it be acceptable to move the generate phase to be the very last phase, or would that have some negative repercussions?

2. Alternatively, we could copy the TestStatus file as a separate step (probably not even a named phase) at the very end of system_tests_common:run. Would that be reasonable?

3. Is there a way to ensure that this copying of the TestStatus file happens even if there is a failure in the run or some other phase? e.g., would putting this copying in a `finally` block at the end of system_tests_common:run ensure this?

I'm happy to make and test this change myself, but I'd like to get input from @jgfouca , @jedwards4b or others if you have any immediate thoughts. My inclination would be to have a `finally` block at the end of system_tests_common:run that does this copying, so I'd probably try that approach first unless you have other feelings.

**Comment by billsacks** [comment]
I realized that if a test doesn't even make it to the run phase, my proposed solution won't work. I don't feel a need for something that _guarantees_ the TestStatus file appears, so I might still go with my proposal, but if others have thoughts on how to ensure that the TestStatus file appears in the baseline directory regardless of whether / when the test failed, I'd be happy to hear it.

**Comment by billsacks** [comment]
(And I'm un-assigning myself for the moment, because if someone else has a good idea for how this could be done and would rather just do it than explain it, that's fine, too.)

**Comment by ekluzek** [comment]
I'd like to see this as well!

**Comment by jgfouca** [comment]
@billsacks , this sounds like an idea that makes more sense in the context of the CESM workflow. I'm fine with putting this is in, but we should probably disable it for E3SM.

You've accurately identified the reasons this will be a little bit tricky. I could put some post-processing into create_test to handle the cases where the test didn't make it to the RUN phase. I could put a bit of extra code into system_tests_common to copy the TestStatus file.

**Comment by rljacob** [comment]
I don't think this would negatively impact our workflow so think its ok to include the TestStatus in our baselines.   I'd rather do that then add more if switches.
