### ISSUE TITLE
Program crash with NAG debug

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2766]
Nag in debug mode shows a runtime error. For instance, the test:
```
SMS_D.f45_f45_mg37.A.hobart_nag
```
will generate the error.

I am not sure of exactly why this error occurs but it is only found with Nag in debug mode (Intel debug seems content to run this code). The error message in this case is:
```
Program terminated by fatal error
Runtime Error: /home/goldy/Projects/newPauseResume/cime/src/share/util/mct_mod.F90, line 1036: Rank 1 of KFLDIN(:) has extent 24 instead of -1
Error occurred in MCT_MOD:MCT_AVECT_VECMULT
/home/goldy/Projects/newPauseResume/cime/src/drivers/mct/main/component_mod.F90, line 579: Called by COMPONENT_MOD:COMPONENT_INIT_AREACOR
/home/goldy/Projects/newPauseResume/cime/src/drivers/mct/main/cime_comp_mod.F90, line 1684: Called by CIME_COMP_MOD:CIME_INIT
/home/goldy/Projects/newPauseResume/cime/src/drivers/mct/main/cime_driver.F90, line 92: Called by CIME_DRIVER

```

**Comment by jedwards4b** [comment]
After looking carefully at this code I do not understand the error the compiler is reporting.  I don't see anything in this subroutine with extent -1.   At the time of the error kfldin has size 24 and av%rattr has a first dimension size 34.   I've also noted that this error is reported on cime master but not on maint-5.6 even though both are using the same compiler.

**Comment by billsacks** [comment]
Regardless of whether this is actually a coding error or a compiler bug, I find the offending lines hard to decipher, with the where statement operating on an array with indirect indexing based on another array:

https://github.com/ESMCI/cime/blob/aa3c8db14bf8ed0627d1d79e73ceb706eb1f4032/src/share/util/mct_mod.F90#L1034-L1038

I would find this code clearer if there were an explicit loop from 1..nfld rather than this whole-array where statement. Hopefully that would make the nag error go away, too.

**Comment by gold2718** [comment]
I agree with @billsacks but only if it is not too slow as it is called from component run.

**Comment by gold2718** [comment]
For grins, I defined an integer p and rewrote the code as:
```
      if (lmspval) then

         !$omp simd
         do n = 1, npts
            do p = 1, nfld
               if (.not. shr_const_isspval(av%rAttr(kfldin(p),n))) then
                  av%rAttr(kfldin(p),n) = av%rAttr(kfldin(p),n)*vec(n)
               end if
            end do
        end do

     else  ! lmspval

        !$omp simd
        do n = 1, npts
           do p = 1, nfld
              av%rAttr(kfldin(p),n) = av%rAttr(kfldin(p),n)*vec(n)
           end do
        end do

     endif  ! lmspval
```
and it passes with Nag debug. I do not know if this still vectorizes in a SIMD fashion or if the compiler created a temporary array (`av%Attr(kfldin(:),n)`) and vectorized that.

**Comment by jedwards4b** [comment]
@gold2718 for grins you should submit your change as a PR.

**Comment by ekluzek** [comment]
Just a note, I did run into this problem in testing the CTSM branch for the new pause-resume (I see it both on @gold2718 cime branch as well as cime master). So with cheyenne down I can't do any more testing on it, until we get past this. I thought about moving just the pause-resume changes in cime to a branch based off the same version that CTSM is using, but would prefer if I could use an updated version.

**Comment by gold2718** [comment]
Only if someone tells me how to make sure it does not affect performance.

Also, after thinking more about this, I do not see how it can be a coding error. Even if a temporary array was being used and there were no members in the `where` statement, I could imagine an array of extent zero, not -1. However, I put in some print statements in my code and the failing test never even hits that condition (i.e., that inner `if` statement is always hit at least once).

So what is a good easy test for performance?

**Comment by jedwards4b** [comment]
intel compiler prints a vectorization report - you could compare those.   I suspect it's not vectorized in either case.

**Comment by gold2718** [comment]
After more examination of the code, I agree with @jedwards4b that this is not a code bug (which implies that it is a NAG run time bug). Still planning on posting a PR to make NAG happy.
