### ISSUE TITLE
Should we remove the cimeteststatus script?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2770]
As far as I can tell, scripts/Tools/cimeteststatus has been broken for a long time (maybe ever since the move to cime5). It used to be a very nice script, and it may still serve some purpose as a reference for some features we may want to bring back at some point, but it looks like it would need an overhaul to work with the much improved test_status design of cime5.

Does anyone object to its removal?

**Comment by jgfouca** [comment]
I don't think we (e3sm) were ever aware of or users of this script.

**Comment by billsacks** [comment]
@fischer-ncar do you know of (or use) this script?

**Comment by fischer-ncar** [comment]
I do know of this script, and have no objections to it's removal.  I believe if was a effort by Jay to combine
cs.status and testreporter into one script.

**Comment by billsacks** [comment]
Okay, I'll remove it.
