### ISSUE TITLE
Inconsistent naming and documentation of histaux_r2x

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2773]
As pointed out by @kdraeder in https://github.com/ESCOMP/cesm/issues/71 - the documentation for histaux_r2x says, "turns on coupler history stream for instantaneous runoff to coupler fields." This is consistent with the name of this variable: in general, histaux flags without a time period in their name give instantaneous values. However, I think that both the documentation and the name are inconsistent with the code:

https://github.com/ESMCI/cime/blob/c4f02062ee6cd0fb1e671513c28eb07582f7d4ed/src/drivers/mct/main/cime_comp_mod.F90#L3054-L3063

My understanding of this code (see the `write_now` argument) is that this gives 24-hour averages.

@klindsay28 or others: do you know what's right here?

**Comment by billsacks** [comment]
My inclination is to at least fix the documentation. It would be nice to make the variable name consistent (by adding '24hr' at the end), but that might break people's scripts, so we could hold off on that change. But before making any change, I'd like confirmation that the code is right and the documentation is wrong.

**Comment by klindsay28** [comment]
I have previously verified that the daily averages of r2x fields from drof
reading histaux_r2x generated output are the same (to single precision
roundofff) as daily averages of r2x fields from the coupled model that
generated the histaux_r2x fields. I'm inferring that the fields must be
averages, not instantaneous.

**Comment by klindsay28** [comment]
I think there's more to it than "people's scripts".
I suspect that changing the variable names would break cplhist mode for
drof.
The drof scripts create stream files that are expecting the existing
variable names in cplhist output.
You could change drof too, but then drof in cplhist mode in the new version
of cime
wouldn't out of the box read previously generated cplhist output.

**Comment by billsacks** [comment]
@klindsay28 thanks for your reply. The variable name that I'm proposing changing is just the namelist variable that turns on this cpl hist output, and some related internal Fortran variables. I don't think this would change anything about the operation of drof, but since I could imagine it breaking scripts that you and others are running for CESM2/CMIP6 spinup, I'm inclined to hold off on that rename.

**Comment by klindsay28** [comment]
Sorry for the confusion, I misinterpreted what variable name you were
proposing to change.
I think I'm with you now.

We have been informing people that using this namelist variable is an
ingredient to generating cplhist output for forcing surface components. I
think it would be disruptive to have those instructions fail to work. So I
fully support holding off on a rename.
