### ISSUE TITLE
DAE.f19_f19.ADWAV fails during phase SETUP on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#2779]
PR #2777 has changed DAE.f19_f19.A in cime_developer list to DAE.f19_f19.ADWAV

However, DAE.f19_f19.ADWAV fails on anlworkstation:
```
        ERROR: WAV_GRID cannot be null

At test-scheduler close, state is:
FAIL DAE.f19_f19.ADWAV.anlworkstation_gnu (phase SETUP)
```
Could you please check if WAV_GRID needs to be set for DAE.f19_f19.ADWAV on anlworkstation (not sure if other machines have this issue)?

**Comment by gold2718** [comment]
This is why I asked @jgfouca to review the PR. When I run this test using cesm as the model, README.case shows:
```
WAV_GRID is ww3a
```
I am not sure how that happens because the cesm version of the f19_f19 grid alias does not mention a wav grid. I note that we have a grid alias:
```
    <!-- The following grid is only used for ADWAV testing -->
    <model_grid alias="ww3a" compset="_WW3|DWAV">
      <grid name="wav">ww3a</grid>
    </model_grid>
```
I do not know how e3sm wants to deal with this.

**Comment by jgfouca** [comment]
@gold2718 , thanks for the info. Whatever trick cesm is doing to pick up a wav grid "ww3a" for f19_f19 is not happening for e3sm. I tried adding the grid XML you pasted and it did not work. @jedwards4b , any ideas?

**Comment by jgfouca** [comment]
Note, if I set "wav" to "ww3a" in the f19_f19 definition, things do work. I'm not sure we want to do that though.

**Comment by jgfouca** [comment]
Oh, I think it's just a matter of default grids.

**Comment by jgfouca** [comment]
Both models appear to have similar defaults, but your f19_f19 definition:

```
    <model_grid alias="f19_f19" not_compset="_POP">
      <grid name="atm">1.9x2.5</grid>
      <grid name="lnd">1.9x2.5</grid>
      <grid name="ocnice">1.9x2.5</grid>
      <mask>gx1v6</mask>
    </model_grid>
```

... is different from ours:

```
    <model_grid alias="f19_f19" compset="(DOCN|XOCN|SOCN|AQP1)">
      <grid name="atm">1.9x2.5</grid>
      <grid name="lnd">1.9x2.5</grid>
      <grid name="ocnice">1.9x2.5</grid>
      <grid name="rof">r05</grid>
      <grid name="glc">null</grid>
      <grid name="wav">null</grid>
      <mask>gx1v6</mask>
    </model_grid>
```

We explicitly set wav to null. I wonder if this is just a bug in the grid converter (v1 to v2) I used?

**Comment by jgfouca** [comment]
This is our V1 definition for f19_f19:

```
    <grid compset="(DOCN|XOCN|SOCN|AQP1)">
      <sname>1.9x2.5_1.9x2.5</sname>
      <alias>f19_f19</alias>
      <lname>a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5_r%r05_m%gx1v6_g%null_w%null</lname>
    </grid>
```

It looks like wav is explicitly set to null there to. @rljacob , please advise.

**Comment by jgfouca** [comment]
As a short term solution, I think we just need a different grid for this test.
