### ISSUE TITLE
create_test: Allow different baselineroot for compare vs. generate

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2787]
It would be helpful if create_test allowed a separate baselineroot to be provided for compare vs. generate. This would be useful for when you're comparing against baselines in the official baseline directory, but either (1) you're generating temporary baselines that you don't want cluttering up the official directory, or (2) you don't have write permission to the official directory. My current workaround in these situations is to make a symbolic link in a temporary location (which I use as baseline-root) pointing to the official baselines for comparison; that works okay, but adds some complexity for new users of the test suite, for whom this is most likely to be an issue.

I'm imagining separate arguments to create_test: `--baseline-root-compare`, `--baseline-root-generate`. I think that, for convenience, there should still be the master `--baseline-root`: if it is provided, then it sets the baseline-root for both compare and generate; it is an error to provide either `--baseline-root-compare` or `--baseline-root-generate` if you also have provided `--baseline-root`.

**Comment by jgfouca** [comment]
Tagging as cesm-only. This wouldn't make a much sense for e3sm.

**Comment by billsacks** [comment]
Closing as a wontfix because a symlink option is good enough.
