### ISSUE TITLE
How to change atm forcing data from within cime

### ISSUE THREAD

**Issue by thiagoveloso** [ESMCI/cime#2798]
I am running the `I2000Clm50BgcCruGs` CLM5 case with Data Atmosphere (DATM). Specifically, I am attempting to run a control case with default settings and two experiment cases with 10% and 20% less precipitation respectively.

Rather than changing the forcing data itself, I am trying to temporarily change the code excerpt responsible for reading the atmospheric data.

My first approach was changing lines 765 to 769 of the file `cime/src/components/data_comps/datm/datm_comp_mod.F90` from

```
!-------------------------------------------------------------------------
! PRECIPITATION DATA
!-------------------------------------------------------------------------

avstrm%rAttr(sprec,n) = avstrm%rAttr(sprec,n)/86400.0_R8        ! convert mm/day to kg/m^2/s
```

to

```
!-------------------------------------------------------------------------
! PRECIPITATION DATA
!-------------------------------------------------------------------------

avstrm%rAttr(sprec,n) = avstrm%rAttr(sprec,n)/86400.0_R8        ! convert mm/day to kg/m^2/s
avstrm%rAttr(sprec,n) = avstrm%rAttr(sprec,n)*0.9_R8            ! decrease precip by 10%
```

However, that change caused no difference in the model output. Am I looking at the right file here? Should I look at the `cpl` or `lnd` components instead?

Any hints to help me find the right file/routine are highly appreciated. Thanks in advance.

**Comment by jedwards4b** [comment]
@thiagoveloso this science question would be more appropriate to post at the cesm forum http://forum.cgd.ucar.edu/

**Comment by thiagoveloso** [comment]
Thanks @jedwards4b, I have just posted it there: https://bb.cgd.ucar.edu/decrease-precipitation-10-clm5-datm
