### ISSUE TITLE
Run phase namelist changes do not appear in *_in files in ru directory

### ISSUE THREAD

**Issue by singhbalwinder** [ESMCI/cime#2799]
We noticed recently that if we make changes to `user_nl_*` files during `run_phase` in a test script (e.g. *.py scripts in cime/scripts/lib/CIME/SystemTests/), those changes do not appear in *_in (e.g. atm_in, lnd_in etc.) files in the run directory. It use to work in the past. I created a very simple test to demonstrate this:
```
from CIME.XML.standard_module_setup import *
from CIME.SystemTests.system_tests_common import SystemTestsCommon
logger = logging.getLogger(__name__)

class NML(SystemTestsCommon):
    def __init__(self, case):
        """
        initialize an object interface to the SLR test
        """
        SystemTestsCommon.__init__(self, case)

    def run_phase(self):
        with open('user_nl_cam', 'w') as atmnlfile:
            atmnlfile.write("dtime = -999 \n")
        self.run_indv()
```

In older version of CIME, the change made above in the `run_phase` to the `user_nl_cam` file would appear in `atm_in` in the run directory. In the current version, this change does not appear in the `atm_in` file even though I see `buildnml` scripts being executed during the `run_phase`.

**Comment by singhbalwinder** [comment]
@jedwards4b : Please feel free to re-assign as appropriate. Thanks!

**Comment by jedwards4b** [comment]
I think that you just need to add a line 
self._skip_pnl = False
to force the rerun of preview_namelists and generation of new namelist files.

**Comment by singhbalwinder** [comment]
Thanks again @jedwards4b ! Adding this line solved the problem!

**Comment by jgfouca** [comment]
Glad it was easy!
