### ISSUE TITLE
Merge ACME env_mach_specific files for blues and titan into config_machines.xml

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#28]
The files that used to define the environment for a machine, env_mach_specific.machine, have been removed on the CESG side of CIME. All the ACME env_mach_specific files will need to be removed and their contents ported into config_machines.xml.

**Comment by rljacob** [comment]
I'd start by just copying their version of config_machines.xml to get things working on the shared machines.  Then we can add our machines.

**Comment by jgfouca** [comment]
I converted melvin, it wasn't hard.

**Comment by rljacob** [comment]
This is done for all machines ACME has in common.  Remaining items on this task is to add the remaining blues compilers.

**Comment by rljacob** [comment]
Closing this as basically done.
