### ISSUE TITLE
CESM2_0:CAM-Chem hanging in mpialltoallint

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2808]
Benjamin Gaubert and I are trying to build a CAM-Chem
version from the released CESM2_0
(/gpfs/fs1/work/raeder/Models/cesm2_0).
I'm building a 1 degree model using compset
HIST_CAM60%CCTS_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
and giving it 6 nodes (per instance).
CAM stops progressing, although when I logged onto
the compute nodes, 'top' reports that all the CPUs were very busy.

I put in debug prints and narrowed the problem down to 
phys_grid.F90:transpose_block_to_chunk:
      call mpialltoallint(rdispls, 1, pdispls, 1, mpicom)
!
\# if defined(MODCM_DP_TRANSPOSE)

I wouldn't be productive for me to try to pursue it any deeper,
so I'm hoping that someone else recognizes a mistake we're
making, or has ideas for things to change.

Thanks,
Kevin and Benjamin

**Comment by jedwards4b** [comment]
It would be very helpful if you tested a single member to see whether it exhibits the same problem.

**Comment by kdraeder** [comment]
I forgot to mention, Benjamin sees essentially the same thing
running it a single instance on 1,2, and 3 nodes.

**Comment by jedwards4b** [comment]
If it is also happening in a single instance case then I think that it's a cam issue, not a cime issue.

**Comment by gold2718** [comment]
Is there a case/run directory to look at? Things like compiler / MPI library / dycore can be important here but are not specified in the problem report. At the moment, I agree with @jedwards4b that this is likely a CAM issue (or a machine/compiler issue) but I need more information to transfer the problem there.

**Comment by kdraeder** [comment]
I submitted this to DiscussCESM and ExtraView on Sep 20.
There has been no response on DiscussCESM, and the consultants
thought about it a couple weeks later, but did not suggest anything.

I'll try to generate a single member case of this
and provide the software versions and case information.

**Comment by kdraeder** [comment]
@jedwards4b @gold2718 
I inserted a call to mpi_barrier before the call to mpialltoallint,
and it hung in the barrier call.  That tells me that there's 1 or more 
tasks that haven't caught up to the rest of them.
I rebuilt with DEBUG=true in env_build.xml, and added 
--assume nobuffered_stdout
to the FFLAGS in the intel:DEBUG section of  in Macros.make 
to get all of the output  from the write(*,*) statements I inserted.

The run didn't make it to the mpi_barrier because the bounds checking uncovered:

> Subscript #1 of the array LND_RESUME has value 2 which is greater than the upper bound of 1

from lnd_comp_mct.F90:
`    if ( len_trim(lnd_resume(inst_index)) == 0 )then`

lnd_resume is dimensioned by  cam/bld/configure:
```
# Parameters for multiple instances
if (!$ccsm_seq){
    $cfg_cppdefs .= " ... -DNUM_COMP_INST_LND=1 ...";
```
This seems to have been done for CAM standalone,
according to components/cam/doc/ChangeLog,
while this is a 2 instance CESM CAM (multi-driver).

This should probably be a separate issue, but I don't know whether to open it
in ESMCI, since it's partly a multi-instance problem, or in DiscussCESM,
since standalone CAM seems to be intruding via the CAM configure.
My guess is that this needs to be resolved before I can make more progress
on the mpialltoallint hang.

**Comment by gold2718** [comment]
This is a bug in the CESM 2.0.0 release, fixed in CESM 2.0.1.
Does using CESM 2.0.1 resolve your issue?

**Comment by kdraeder** [comment]
@gold2718 
Would that fix be in 2.2?  I have that set up and ready to use.

**Comment by gold2718** [comment]
@kdraeder, yes, it is in all tags made after CESM 2.0.1
I assume by 2.2, you mean some CESM 2.2 alpha tag?

**Comment by kdraeder** [comment]
@gold2718 
Right, and I've been using CIME maint-5.6 in it,
which I updated ~ 2 weeks ago.

**Comment by jedwards4b** [comment]
maint-5.6 is not necessarily compatible with cesm2.2.x if you really want cesm2.2 you should use cime/master if you really want cime/maint-5.6 you should use cesm2.1.x

**Comment by kdraeder** [comment]
Thanks for the guidance!
Since cesm2.1 is what will be released next,
and maint-5.6 was recommended for resolving my CIME issues,
I'll start working with cesm2.1.x.   Should I get this from 
https://github.com/ESCOMP/cesm/tree/cesm2.1-alphabranch?

**Comment by kdraeder** [comment]
I've used shr_mpi_barrier to track the original hanging problem back to 
gravity_waves_sources.F90:ghost_array.
The 2 instances are using 216 tasks each (6 nodes each).
Tasks 0-109 and 216-325 do not print a diagnostic message
after the mp_recv3d call of the  'south' section
of the first call to ghost_array. The others do.
Each instance is missing prints from the first 110 tasks, including all 108
which are on the first 3 nodes of the 6 used by each instance.

The output is in
  /gpfs/fs1/scratch/raeder/Chem_debug11/run
and the caseroot is
  /gpfs/fs1/work/raeder/Exp/Chem_debug11.
Note the SourceMods, which shows where the printed output
in $rundir/cesm.log* comes from.

Francis Vitt wrote ghost_array, and agrees with us that
multi-instance it works in CAM and WACCM, it should work in CAM-Chem.
But that doesn't seem to be the case. This is a multi-driver case, 
as well as multi-instance, which may not have been used 
in tests of CAM-Chem and ghost_array.
I could try a single drive, multi-instance case, 
if anyone thinks that would be helpful.
Benjamin Gaubert reports that a single instance case works.

**Comment by kdraeder** [comment]
@fvitt  added a fix to dp_coupling.F90 related to the gravity wave drag,
and also identified (along with @brian-eaton ) that a line in cam/cime_config/buildnml
was defining CAM's npr_yz to be (1,1,1,1), which tried to run the whole domain
on one task.  Replacing that line with what was intended to be the default 
fixed both this issue and the problem I was having with (s)lon in initial files 
being filled with 0s for 1 degree ensembles >= 60 members
(https://bb.cgd.ucar.edu/initial-file-longitudes-are-0s-large-ensemble-cam6).

So I'm closing this issue
Thanks everyone!
