### ISSUE TITLE
Question - Adding modex cluster machine files to cime master

### ISSUE THREAD

**Issue by serbinsh** [ESMCI/cime#2810]
I just wanted to come back to this issue from much earlier this year.  Presently when I pull cime to build CLM/FATES I am using a custom cime branch (https://github.com/serbinsh/cime/tree/clm4518/n04/cime5.4.0-alpha.03/add_modex) that @billsacks and @ekluzek helped me get working on our cluster.  

However, since then I am not certain what branch those changes made it in to and whether those updates will end up in master/release cime at some point? If not, what would be the long term solution for making sure that version of cime machine files get into newer versions?

Apologies for not knowing the process I am just concerned about something breaking my current setup at some point.

Here is some additional info on this:
https://github.com/ESMCI/cime/pull/2087

and

https://github.com/ESMCI/cime/issues/2077

Thanks!

**Comment by jedwards4b** [comment]
I believe that that code is already merged to cime master as well as the maint-5.6 branch.  Try switching to cime branch maint-5.6

**Comment by serbinsh** [comment]
Indeed....for whatever reason when I pulled everything fresh it wasn't showing up in the machines XML but I just made sure I was on master and check again and found the files.  I will confirm they match the files in the custom branch above but otherwise I apologies for posting this.  I really did look before I posted this!  Not sure how/why I didn't see it the first time.  

I am going to close this for now, unless something comes up.

**Comment by serbinsh** [comment]
I realize what I did wrong.  I am working with CTSM branch "fates_next_api" which in Externals.cfg has:

```
[cime]
local_path = cime
protocol = git
repo_url = https://github.com/CESM-Development/cime
tag = clm4518/n04/cime5.4.0-alpha.03
required = True
```

Older CIME.  As such I need to switch that to to a different branch to include the modex files.  Not sure if the master cime will work or if I need to continue using the special branch until this branch of ctsm catches up.  Will need to investigate this.

**Comment by jedwards4b** [comment]
@serbinsh Try the maint-5.6 branch, I think that it will be compatible with your ctsm.
