### ISSUE TITLE
Coupler history files do not restart properly

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2816]
The coupler's average (rather than instantaneous) and auxiliary history files do not restart properly. This is a problem for #873 , but is also a more general problem, such as for data assimilation runs that have frequent restarts.

Currently, no attempt is made to save accumulating cpl fields to a restart history file.

**Comment by rljacob** [comment]
Discussion on telecon:  any averaged file where the restart is in between history writes won't work.  Code to save intermediate average isn't in the mct coupler.

**Comment by billsacks** [comment]
@mvertens is this an issue for CMEPS, too - that cpl avg hist files won't restart properly? If so, I'll move this issue there; if this works, though, I'll close it.

**Comment by mvertens** [comment]
@billsacks - yes this is an issue for CMEPS that should be assigned to me.

**Comment by billsacks** [comment]
Moved to https://github.com/ESCOMP/CMEPS/issues/253
