### ISSUE TITLE
Streams files with time interpolation do not compare exactly when data is the same, but time off

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2820]
Using cime_cesm2_0_rel_05 for an I compset case.

The wrong index is found in streams for the lower bound for multi-year monthly files, when told to just run over a single year and starting at the beginning of the year. I don't see this for files with a single year, or for example the 3-hourly forcing data. It should identify the last index for that year as the lower bound index, but it's finding a different one. Once, it gets beyond that first month it's fine.

I'm seeing this specifically for a multi-year ndep file (where cime/stream code is called from ctsm), but suspect it applies to other cases as well.

I'll be reporting on more specifics as I dive deeper into this issue.

**Comment by ekluzek** [comment]
The bottom line expectation that I have is that answers should be the same for a multi-year file and a single-year file in streams -- if the data is for the particular year going over is identical between the two. So in this case I have a multi-year ndep file where years 1849 and 1850 are identical to the single year file for 1850. I thought the time-interpolation might be the culprit, but I also found this problem without any time or spatial interpolation (with tinitalgo="nearest" and mapalgo="nn").

**Comment by mvertens** [comment]
Do you need to specify cyclic time boundary conditions if you are trying to
run say over 1850 in a file that is 1849-1851?

**Comment by ekluzek** [comment]
@mvertens yes, I am use "cycle". I tried "limit" and it fails because it's before the start of the time period. I didn't do "extend", because that should just use the first time sample.

**Comment by ekluzek** [comment]
The two files I expect to give the same answers for are:

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_WACCM6_CMIP6piControl001_y21-50avg_1850monthly_0.95x1.25_c180802.nc

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc

Since 1849 and 1850 are just a copy of the data from the first file.

**Comment by klindsay28** [comment]
The variable time in the first file has units "days since 0001-01-01 00:00:00" and values
674899, 674929, 674958, 674989, 675019, 675050, 675080, 675111, 675142, 675172, 675203, 675233

If you subtract 365*1849 from those values you get
14    44    73   104   134   165   195   226   257   287   318   348

The variable time in the second file has units "days since 1849-01-01 00:00:00" and the first 12 values are 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5

So it looks like the time values are on different days of the year.
If I'm correct, then you shouldn't expect to get identical interpolated values from these two files.

**Comment by ekluzek** [comment]
Ok, if that's right I'll need to get Keith Oleson to regenerate the file. Thanks for pointing that out!

**Comment by klindsay28** [comment]
Which file are you suggested being regenerated?

I think the time values in the 1849-2015 file are 'better' in the sense
that they are truly mid-month.

However, the 1850 file is already being used in the CESM 2.1 CMIP6
piControl run.

It seems like you have an implicit requirement that these files generate
identical results.
If so, what is the basis of this requirement?

**Comment by ekluzek** [comment]
@klindsay28 this is coming from David Lawrence and Keith Oleson (and maybe others). He explicitly made the 1850 data the same as the one for the piControl run, so that we could get identical results for any 1850 runs we do. If we truly don't care then I'm fine with moving on. But, that was my understanding of why the 1850 data was overwritten for this file.

**Comment by ekluzek** [comment]
I think the new multi-year file should be regenerated with time/date for 1849-1850 that is identical to that for the ndep file for the pi-control. You wouldn't have to change time/date for the data beyond 1850. So the modern data beyond 1850 would have the correct mid-month values, it's just the first 24 month period would be off of that.

**Comment by olyson** [comment]
Keith and Dave and I talked this morning about the ndep file.

First of all, we decided the right thing to do is to use the transient file that has the correct mid-month time coordinate. So the tag you are making would use this file.  We'd also point to the existing 1850 file for 1850 runs to ensure we get the same answers for those runs.

Second, can you repeat just the test that was failing using either a new 1850 file that has correct mid-month time coordinates or a new transient file that has the time coordinates from the 1850 file, whichever way makes sense for testing.  We want to make sure that the differences you are seeing are only due to the shift in the time coordinates.

**Comment by ekluzek** [comment]
OK, I compared the case ERP_Ld5_P48x1.f10_f10_musgs.I1850Clm50Bgc.hobart_nag.clm-default on hobart with an ndep file with the times for 1849 and 1850 that jive with the 1850 pi control ndep file, and answers are identical I'm going to do a little more testing and then close this issue out.

**Comment by ekluzek** [comment]
OK, did a 12 month test and showed exact results. So I'm closing this as it really works the way you'd want it to.

Here are some notes on my testing:

```
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default CREATE_NEWCASE
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default XML
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default SETUP
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default SHAREDLIB_BUILD time=161
FAIL SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default NLCOMP
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default MODEL_BUILD time=43
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default SUBMIT
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default RUN time=704
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default BASELINE ctsm1.0.dev012: 
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default MEMCOMP
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default TPUTCOMP
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default MEMLEAK
PASS SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default SHORT_TERM_ARCHIVER
scripts/SMS_Lm12.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default.C.20181003_121937_jmi50o> cat user_nl_clm
 wrtdia         = .true.
 hist_dov2xy    = .true.,.false.
! Even though only 2 history tapes are defined here, set ndens to 1 for up to 6 history
! tapes, for the sake of mods that extend these default mods and may add other history tapes
 hist_ndens     = 1,1,1,1,1,1
 hist_nhtfrq    =-24,-8
 hist_mfilt     = 1,1
 hist_fincl1    = 'TRAFFICFLUX', 'SNOWLIQ:A','SNOWICE:A'
! Add FCO2 because few (if any) tests send this flux to the coupler, so it isn't checked via cpl hist files
 hist_fincl1   += 'FCO2'
 hist_fincl2    = 'TG','TBOT','FIRE','FIRA','FLDS','FSDS',
                  'FSR','FSA','FGEV','FSH','FGR','TSOI',
                  'ERRSOI','SABV','SABG',
                  'FSDSVD','FSDSND','FSDSVI','FSDSNI',
                  'FSRVD','FSRND','FSRVI','FSRNI',
                  'TSA','FCTR','FCEV','QBOT','RH2M','H2OSOI',
                  'H2OSNO','SOILLIQ','SOILICE', 
                  'TSA_U', 'TSA_R',
                  'TREFMNAV_U', 'TREFMNAV_R',
                  'TREFMXAV_U', 'TREFMXAV_R',
                  'TG_U', 'TG_R',
                  'RH2M_U', 'RH2M_R',
                  'QRUNOFF_U', 'QRUNOFF_R',
                  'SoilAlpha_U',
                  'SWup', 'LWup', 'URBAN_AC', 'URBAN_HEAT'

 use_ssre = .true.

  stream_fldfilename_ndep = '/glade/scratch/erik/ctsm_latest/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c181002.nc'
```
