### ISSUE TITLE
Compset/grid mismatch in T case gives unhelpful errors

### ISSUE THREAD

**Issue by Katetc** [ESMCI/cime#2836]
This create_newcase command:
./create_newcase --case /gpfs/fs1/work/katec/lndice/cism_cases/TestPy2-mast-T1850G1-01 --mach cheyenne --res f19_g17_gl5 --compset T1850G1 --run-unsupported

It shouldn't work, because that grid is not supported by the available input data. (The correct grid is f09_g17_gl5, so a 1-number typo caused this much confusion.) However, the above create_newcase runs just fine. The case builds just fine. Preview namelists goes through great. On case.submit, I get the following errors:

Finished creating component namelists
Checking that inputdata is available as part of case submission
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/dlnd.input_data_list'
Model dlnd missing file domain1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
Model dlnd missing file file1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
Loading input file list: 'Buildconf/cism.input_data_list'
Checking server ftp://gridanon.cgd.ucar.edu:2811/cesm/inputdata/ with protocol gftp
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Client protocol gftp not enabled
Checking server https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata with protocol svn
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/dlnd.input_data_list'
Model dlnd missing file domain1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Model dlnd missing file file1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Loading input file list: 'Buildconf/cism.input_data_list'
Checking server ftp.cgd.ucar.edu/cesm/inputdata with protocol ftp
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
server address ftp.cgd.ucar.edu root path cesm/inputdata
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/dlnd.input_data_list'
Model dlnd missing file domain1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Model dlnd missing file file1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Loading input file list: 'Buildconf/cism.input_data_list'
Checking server ftp://ftp.cgd.ucar.edu/cesm/inputdata with protocol wget
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/dlnd.input_data_list'
Model dlnd missing file domain1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Model dlnd missing file file1 = 'UNSET/UNSET.cpl.hl2x1yr_glc.-999-01-01.nc'
    Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
Loading input file list: 'Buildconf/cism.input_data_list'
Checking server None with protocol None
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Client protocol None not enabled
ERROR: Could not find all inputdata on any server

There are so many grid/compset/input data configuration requirements that trying to catch all of the problems is probably impossible. But, it might be nice to have a more helpful error earlier on in the case timeline. Perhaps a check of input data or look for UNSET values at build namelist time?

**Comment by billsacks** [comment]
I think this is similar to #2535

**Comment by billsacks** [comment]
@Katetc - from talking with @mvertens , she thinks this issue is likely gone with CDEPS, at least in this form. So I'm going to close this, but feel free to reopen if you feel there are still similar issues that need to be resolved with NUOPC/CMEPS/CDEPS. (This may also be similar to the issue we discussed at last Tuesday's CSEG meeting, raised by @mnlevy1981 .)
