### ISSUE TITLE
XML Caching needs to be more robust

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2850]
User should never have to disable caching. Propose adding sha1 to FILEMAP to check that file was not changed. Maybe need addition class-level data in GenericXML to ensure that we never have multiple writable GenericXML objects open to the same file at the same time.

**Comment by gold2718** [comment]
Doesn't computing the sha1 take time and slow performance?

**Comment by jgfouca** [comment]
@gold2718 , it should be much faster than a full XML tree parse.

**Comment by billsacks** [comment]
I'm curious: Are there current issues with the caching that prompted you to open this issue, or is this just a future precaution?

**Comment by billsacks** [comment]
> I'm curious: Are there current issues with the caching that prompted you to open this issue, or is this just a future precaution?

Okay, just skimmed Slack and see the question is answered there.
