### ISSUE TITLE
Should there be another element of compset name that allows specifying a usermods directory?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2863]
In CESM, we're needing to add usermods directories for particular configurations that are being used for CMIP6. The decision has been to do this similar to how we add REFCASEs for specific compsets and resolutions - e.g.:

```xml
    <!-- usermods directories needed for CMIP6 configurations. Among
         other things, these enable settings in CLM that are necessary
         for compatibility with the above REFCASEs -->
    <entry id="CPL_USER_MODS">
      <values>
        <value grid="a%0.9x1.25_l%0.9x1.25_oi%gx1v7_r%r05_g%gland4_w%ww3a_m%gx1v7"      compset="1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO.*MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD"     >cmip6_picontrol</value>
        <value grid="a%0.9x1.25_l%0.9x1.25_oi%gx1v7_r%r05_g%gland4_w%null_m%gx1v7"      compset="1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO.*MOSART_CISM2%NOEVOLVE_SWAV_BGC%BDRD"    >cmip6_picontrol</value>
      </values>
    </entry>
```

Some people have asked if we can have separate compsets that point to these usermods directories, and I am beginning to feel that that would be a cleaner way to do this, longer-term. (I'm not suggesting any changes for our cmip6 experiments at this point.) So we'd have a standard B1850 compset that would not include any usermods, then a B1850_CMIP6 that would pull in the usermods directory (no matter what resolution you're running at).

The problem is that, currently, we don't have a way to distinguish between B1850 and B1850_CMIP6 in the compset long name. So, what do people think about adding another element to the compset long name that could be used for this purpose? I can envision two ways this could be done:

(1) This new element of the compset long name could be used solely for specifying a usermods directory. When parsing the long name, the cime scripts would pick off this piece and add it to the list of usermods directories for this case. So, in the above case, the compset long name would be `1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO%ABIO-DIC_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD_cmip6_picontrol` (hmmm, maybe something needs to be done about the fact that there's an underscore within the usermods directory name, conflicting with the use of underscore as a separator in the compset long name....)

(2) This new element of the compset long name could be used for any desired purpose, for the sake of xml matches elsewhere. So, in the above case, the compset long name could be `1850_CAM60_CLM50%BGC-CROP_CICE_POP2%ECO%ABIO-DIC_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD_CMIP6PICONTROL` and then we'd have xml like:

```xml
    <entry id="CPL_USER_MODS">
      <values>
        <value compset="_CMIP6PICONTROL"     >cmip6_picontrol</value>
      </values>
    </entry>
```

– and you could imagine using this same mechanism for other purposes (though nothing else springs to mind at the moment).

**Comment by rljacob** [comment]
If there's a set of component modifications you're always using, isn't that what the "%" modification is for?  So you should have CAM6%CMIP6, etc. and make the B1850_CMIP6 compset out of that.

**Comment by billsacks** [comment]
@rljacob good point, I guess that's a different way we could have organized this, which I didn't consider. So, in this case, we'd have CMIP6 modifiers for CAM, CLM and CICE, and each of them would have logic in their config_component.xml that sets their respective COMP_USER_MODS directory... interesting... I like it. It's not quite as flexible / easy to modify as the solutions I proposed, but it avoids adding more elements to the compset name, and gives some advantages in terms of decentralization and the ability to easily use the same mechanism (e.g.) for an F compset as for a B compset.

**Comment by billsacks** [comment]
I'm going to prototype this to see if I can get it working in time for CESM2.1. Thanks again for the suggestion.
