### ISSUE TITLE
need cross instance communicators for data assimilation

### ISSUE THREAD

**Issue by osculation** [ESMCI/cime#2870]
There is no communicator for  multi_driver mode  case to  collect data from different instance. 
I  will submit a pull for the create the  communicators.

**Comment by jedwards4b** [comment]
There is actually - it's the esp component.   I suggest that you discuss your intent with @gold2718 and myself, we may be able to guide you to a solution.

**Comment by gold2718** [comment]
@jedwards4b, This is a different application with different communicators needed. I suggested posting this issue so we can clean up Yun's implementation via a related PR. That is why I self-assigned the issue.
