### ISSUE TITLE
Still having nuopc problems for e3sm on melvin

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2878]
```
./create_newcase  --driver nuopc --case /home/jgfouca/acme/scratch/scripts_regression_test.20181025_144318/TestCreateNewcase/testcreatenewcase.nuopc4 --compset X --res f19_g16 --output-root /home/jgfouca/acme/scratch/scripts_regression_test.20181025_144318/TestCreateNewcase

ERROR: Makes no sense to have empty read-only file
```
The file in question is /home/jgfouca/acme/scratch/scripts_regression_test.20181025_144318/TestCreateNewcase/testcreatenewcase.nuopc2/env_case.xml

**Comment by jedwards4b** [comment]
I forgot to add a file to that branch - 
cp src/drivers/nuopc/cime_config/config_component_cesm.xml  to  src/drivers/nuopc/cime_config/config_component_e3sm.xml
