### ISSUE TITLE
Usage isn't quite right for create_test

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#288]
Usage for create_test gives the following

usage: 
create_test <TEST|SUITE> [<TEST|SUITE> ...] [--verbose]
OR
create_test xml --category [CATEGORY] [--machine ...] [--compiler ...] [ --testlist ...]
OR
create_test --help
OR
create_test --test

The xml example line should remove the "xml" as a positional argument and add "xml-" to the command-line options. So it should appear as...

create_test --xml-category [CATEGORY] [--xml-machine ...] [--xml-compiler ...] [ --xml-testlist ...]

The above is also not clear in how test-suites should be listed -- as filenames or what?

I see the above in the latest master as of right now.

**Comment by ekluzek** [comment]
For test suites it gives these examples. But it doesn't define if a SUITE is a filename with a list of tests or what.

usage: 
create_test <TEST|SUITE> [<TEST|SUITE> ...] [--verbose]
OR
create_test xml --category [CATEGORY] [--machine ...] [--compiler ...] [ --testlist ...]
OR
create_test --help
OR
create_test --test

EXAMPLES:
    # Run single test 
    > create_test <TESTNAME>

    # Run test suite 
    > create_test <SUITE>

    # Run two tests 
    > create_test <TESTNAME1> <TESTNAME2>

    # Run two suites 
    > create_test <SUITE1> <SUITE2>

    # Run all tests in a suite except for one 
    > create_test <SUITE> ^<TESTNAME>

    # Run all tests in a suite except for tests that are in another suite 
    > create_test <SUITE1> ^<SUITE2>

**Comment by jedwards4b** [comment]
I have a fix for the xml options in the help message and will include it in my next PR.  
The suite  referred to here is defined in update_acme_tests.py which is an acme mechanism we do not use in cesm (other than the cime_developer list used in cime standalone testing)   We need to talk to the acme team about how to clarify this usage.   
I also plan to add a new option --testfile _filename_ that will allow you to create a line separated ascii list of tests in a file.

**Comment by jedwards4b** [comment]
done
