### ISSUE TITLE
query_config --components yields multiple warnings

### ISSUE THREAD

**Issue by naromero77** [ESMCI/cime#2880]
This is a buglet that can found in the version of CIME that is in E3SM develop. I was told to file a CIME GitHub issue instead of an E3SM GitHub issue.

If I do:
`./query_config --components | grep -i WARNING`

there are several warnings from missing config_file:
```
WARNING: Couldn't find config_file /home/naromero/E3SM-github/cime/config/e3sm//vic/config_component.xml on disk
WARNING: Couldn't find config_file /home/naromero/E3SM-github/cime/src/components/data_comps/dglc/cime_config/config_component.xml on disk
WARNING: Couldn't find config_file /home/naromero/E3SM-github/cime/../components/ww3/cime_config/config_component.xml on disk
```

**Comment by jedwards4b** [comment]
I think that the issue is that the e3sm config_files.xml points to several non-existent xml files. The fix is simply to remove these references from config_files.xml or provide the files.

**Comment by rljacob** [comment]
We should remove the references.
