### ISSUE TITLE
Non transient compsets wtih _BGC%B?R? set CO2C, but then don't work with DATM

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2885]
@Katetc pointed out this problem to me, and I verified it by looking at the lasted code on master. 

Driver config_component_cesm.xml has this...

``` xml
  <entry id="CCSM_BGC">
    <type>char</type>
    <valid_values>none,CO2A,CO2B,CO2C</valid_values>
    <default_value>none</default_value>
    <values match="last">
      <value compset="_CAM">CO2A</value>
      <value compset="_DATM">none</value>
      <value compset="_DATM%CPLHIST.+POP\d">CO2A</value>
      <value compset="HIST.*_DATM.*_CLM">CO2A</value>
      <value compset="RCP.*_DATM.*_CLM">CO2A</value>
      <value compset="_BGC%BPRP">CO2C</value>
      <value compset="_BGC%BDRD">CO2C</value>
    </values>
```

So when _BGC%B?R? is set CO2C is set, but when DATM is being used and it's not a transient simulations, CO2 isn't sent from it, as follows... 

``` xml
  <entry id="DATM_CO2_TSERIES">
    <type>char</type>
    <valid_values>none,20tr,20tr.latbnd,rcp2.6,rcp4.5,rcp6.0,rcp8.5</valid_values>
    <default_value>none</default_value>
    <values match="last">
      <value compset="^RCP8">rcp8.5</value>
      <value compset="^RCP6">rcp6.0</value>
      <value compset="^RCP4">rcp4.5</value>
      <value compset="^RCP2">rcp2.6</value>
      <value compset="^HIST">20tr</value>
      <value compset="^20TR">20tr</value>
    </values>
    <group>run_component_datm</group>
    <file>env_run.xml</file>
    <desc>DATM CO2 time series</desc>
  </entry>
```

I think what should happen is that DATM  should react to the CCSM_BGC setting and turn on DATM_CO2_TSERIES. But, when it's set for a control case, it needs to be a 1850_control and 2000_control setting that needs to be added. Normally, neither of those would be used, only if CCSM_BGC is set to something other than none.

 @jgfouca I did check and this problem also exists for E3SM as well as CESM.

**Comment by ekluzek** [comment]
Since, we now have CO2 files with latitude bands, as well as monthly data rather than yearly, there is additional reason to have CO2 1850_control and 2000_control configurations added.

**Comment by billsacks** [comment]
@Katetc @ekluzek do you know if this is still an issue, including with cmeps/cdeps?

**Comment by jgfouca** [comment]
I think we still want this.

**Comment by ekluzek** [comment]
@jgfouca this is still a problem for CESM, but it's now in CMEPS and CDEPS for CESM and no longer in cime. And I assume the same is true for E3SM, it's in the E3SM driver and data models.

**Comment by jgfouca** [comment]
@ekluzek , gotcha, thanks!
