### ISSUE TITLE
Bring back ability for cs.status to aggregate across suites in a given test root

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#289]
In the CESM-Development/cime perl, we could have multiple test suites in a single test root, and the cs.status command (later renamed to cimeteststatus) would aggregate across all test suites in that directory. While not critical, this was a convenient feature to reduce the time it took to parse test results. It would be nice for this feature to be brought back at some point.

**Comment by rljacob** [comment]
Is this different from #293 ?

**Comment by billsacks** [comment]
@rljacob : this is the same as item (3) in #293. Shall we close this issue and just keep #293 open?

**Comment by rljacob** [comment]
Yes.
