### ISSUE TITLE
PR #2804 broke builds with mpi-serial

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2890]
#2804 added, among other things, a reference to `MPI_ADDRESS_KIND`. Builds with mpi-serial are now failing (example: `SMS_Mmpi-serial_P1x1.f09_g16.S.cheyenne_gnu`) with:

```
/gpfs/fs1/work/sacks/ctsm_code/current_branch1/cime/src/drivers/mct/main/component_mod.F90:66:32:

   integer (kind=MPI_ADDRESS_KIND) :: max_mpi_tag
                                1
Error: Symbol ‘mpi_address_kind’ at (1) has no IMPLICIT type
```

I see MPI_ADDRESS_KIND defined in `src/externals/mct/mpi-serial/mpif.F90`, but I'm thinking that the issue is that component_mod has:

```
#include <mpif.h>
```

but NOT

```
use mpi
```

Should this be changed to `use mpi`, or should mpi-serial be changed to move MPI_ADDRESS_KIND to the header file?

I'm labeling this as critical, because it's blocking our upgrade to a more recent cime version in CTSM.

@jhkennedy @jedwards4b @ekluzek @fischer-ncar

**Comment by jedwards4b** [comment]
I vote for removing the include and replacing with use.

**Comment by billsacks** [comment]
@jedwards4b I just tried that; it didn't work: During the link, it generates:

```
component_mod.o: In function `__component_mod_MOD_component_init_pre':
component_mod.F90:(.text+0x3279): undefined reference to `mpi_attr_get_'
```

**Comment by jedwards4b** [comment]
It looks like we have more that one inconsistency between the mpiF.h and mpi.mod - 
we could fix them or you could add an only clause to your use mpi statement.

**Comment by billsacks** [comment]
@jedwards4b @jhkennedy @rljacob - I'm struggling with how to move forward here. I'd really like to get the latest cime into CTSM, but we rely on mpi-serial pretty heavily in our testing.

One proposal I'd like to make is to temporarily back out #2804 , make a cime tag that we can use in CTSM and CESM, then we can reapply #2804 once we have a fix for mpi-serial. Is that path forward acceptable to all of you?

In terms of fixes needed in mpi-serial: I see two or three:

(1) Move the definition of MPI_ADDRESS_KIND into mpif.h:

```diff
diff --git a/src/externals/mct/mpi-serial/mpif.F90 b/src/externals/mct/mpi-serial/mpif.F90
index 369b71459..ab32e2813 100644
--- a/src/externals/mct/mpi-serial/mpif.F90
+++ b/src/externals/mct/mpi-serial/mpif.F90
@@ -4,9 +4,5 @@

 Module mpi
 implicit none
-! MPI_ADDRESS_KIND: need an 8-byte integer.
-        INTEGER, PARAMETER, PUBLIC :: MPI_ADDRESS_KIND=selected_int_kind(13)
-
-
         include "mpif.h"
 end Module mpi
diff --git a/src/externals/mct/mpi-serial/mpif.h b/src/externals/mct/mpi-serial/mpif.h
index 678ad9e9f..85793381e 100644
--- a/src/externals/mct/mpi-serial/mpif.h
+++ b/src/externals/mct/mpi-serial/mpif.h
@@ -298,6 +298,9 @@ parameter (MPI_BOTTOM=0)
   ! Kinds
   !

+  INTEGER MPI_ADDRESS_KIND
+  PARAMETER (MPI_ADDRESS_KIND=selected_int_kind(13))
+
   INTEGER MPI_OFFSET_KIND
   PARAMETER (MPI_OFFSET_KIND=selected_int_kind(13))
```

(2) Define `mpi_attr_get`. I have no idea what's needed for this, or if it's even remotely feasible. If this isn't feasible in the near-term, then is it possible to implement #2804 in some alternative way?

(3) (MAYBE) Make mpi_barrier accessible via 'use mpi, only : mpi_barrier' (I can't tell if that's needed, and if it is needed, then what needs to be done to support it.)

**Comment by billsacks** [comment]
I'll add that the answer, "We should stop supporting mpi-serial" is acceptable to me, personally....

**Comment by billsacks** [comment]
@rljacob - mpi_attr_get was just recently added to the driver code in #2804 , which is why we're first finding this issue now.

@ekluzek do you feel it's acceptable for CTSM to stop testing with mpi-serial, or do you feel this is a critical configuration that still needs to be supported?

**Comment by rljacob** [comment]
Sorry I misread what happened.

@jhkennedy you want to try adding mpi_attr_get to mpi-serial?  Only the version of that function that you call.  It looks simple enough.

**Comment by jedwards4b** [comment]
@billsacks I agree with @rljacob it should be easy to add that function to mpi_serial

**Comment by jhkennedy** [comment]
@billsacks one way to get you moving forward quickly would be to take out the check against the max MPI tag -- that only serves to throw an exception if it's exceeded, but MPI itself will do that with a decently descriptive message as well. This exception really just adds a message that contains what the max tag is for that machine, so I don't think removing it would be a big problem as both the MPI and this exception will be thrown at runtime. 

Here is a diff of what I mean: 

```diff
diff --git a/src/drivers/mct/main/component_mod.F90 b/src/drivers/mct/main/component_mod.F90
index 426ab7d83..983b7af69 100644
--- a/src/drivers/mct/main/component_mod.F90
+++ b/src/drivers/mct/main/component_mod.F90
@@ -63,8 +63,6 @@ module component_mod
   integer  :: mpicom_GLOID, mpicom_CPLID           ! GLOID, CPLID mpi communicator
   integer  :: nthreads_GLOID, nthreads_CPLID
   logical  :: drv_threading
-  integer (kind=MPI_ADDRESS_KIND) :: max_mpi_tag
-
 
   !===============================================================================
 
@@ -106,9 +104,6 @@ contains
     call seq_comm_getinfo(CPLID, mpicom=mpicom_CPLID, iamroot=iamroot_CPLID, nthreads=nthreads_CPLID)
     iamin_CPLID = seq_comm_iamin(CPLID)
 
-    ! MPI spec. guarantees at least 32768 tags available, but most implementations will have more.
-    call mpi_attr_get(MPI_COMM_WORLD, MPI_TAG_UB, max_mpi_tag, flag, ierr)
-
     ! Initialize component type variables
     do eci = 1,size(comp)
 
@@ -332,7 +327,6 @@ contains
     type(mct_gGrid) :: dom_tmp   ! temporary
     character(*), parameter :: subname = '(component_init_cx)'
     character(*), parameter :: F0I = "('"//subname//" : ', A, 2i8 )"
-    character(*), parameter :: F1I = "('"//subname//" : ', A, I10, A, I10 )"
     !---------------------------------------------------------------
 
     ! Initialize driver rearrangers and AVs on driver
@@ -394,10 +388,6 @@ contains
                 else
                     mpi_tag = comp(eci)%cplcompid*10000+eci*10+1
                 end if
-                if (mpi_tag > max_mpi_tag) then
-                   write(logunit, F1I) 'MPI message tag ',mpi_tag,' exceeds max ',max_mpi_tag
-                   call shr_sys_abort(subname//' ERROR: Max mpi tag exceeded')
-                end if
                 call seq_map_map_exchange(comp(1), flow='c2x', dom_flag=.true., msgtag=mpi_tag)
 
              else if (eci > 1) then
@@ -574,7 +564,6 @@ contains
     integer :: eci, num_inst
     integer :: mpi_tag
     character(*), parameter :: subname = '(component_init_areacor)'
-    character(*), parameter :: F1I = "('"//subname//" : ', A, I10, A, I10 )"
     !---------------------------------------------------------------
 
     num_inst = size(comp)
@@ -589,10 +578,6 @@ contains
           else
              mpi_tag = comp(eci)%cplcompid*10000+eci*10+5
           end if
-          if (mpi_tag > max_mpi_tag) then
-             write(logunit, F1I) 'MPI message tag ',mpi_tag,' exceeds max ',max_mpi_tag
-             call shr_sys_abort(subname//' ERROR: Max mpi tag exceeded')
-          end if
           call seq_map_map(comp(eci)%mapper_Cx2c, comp(eci)%dom_cx%data, comp(eci)%dom_cc%data, msgtag=mpi_tag)
 
           ! For only component pes
@@ -616,10 +601,6 @@ contains
           else
               mpi_tag = comp(eci)%cplcompid*10000+eci*10+7
           end if
-          if (mpi_tag > max_mpi_tag) then
-             write(logunit, F1I) 'MPI message tag ',mpi_tag,' exceeds max ',max_mpi_tag
-             call shr_sys_abort(subname//' ERROR: Max mpi tag exceeded')
-          end if
           call seq_map_map(comp(eci)%mapper_cc2x, comp(eci)%c2x_cc, comp(eci)%c2x_cx, msgtag=mpi_tag)
 
        endif
@@ -856,7 +837,6 @@ contains
     integer :: ierr
     integer :: mpi_tag
     character(*), parameter :: subname = '(component_exch)'
-    character(*), parameter :: F1I = "('"//subname//" : ', A, I10, A, I10 )"
     !---------------------------------------------------------------
 
     if (present(timer_barrier))  then
@@ -885,10 +865,6 @@ contains
              else
                 mpi_tag = comp(eci)%cplcompid*10000+eci*10+2
              end if
-             if (mpi_tag > max_mpi_tag) then
-                write(logunit, F1I) 'MPI message tag ',mpi_tag,' exceeds max ',max_mpi_tag
-                call shr_sys_abort(subname//' ERROR: Max mpi tag exceeded')
-             end if
              call seq_map_map(comp(eci)%mapper_Cx2c, comp(eci)%x2c_cx, comp(eci)%x2c_cc, msgtag=mpi_tag)
           else if (flow == 'c2x') then ! component to coupler
              if ( size(comp) > 1) then
@@ -896,10 +872,6 @@ contains
              else
                 mpi_tag = comp(eci)%cplcompid*10000+eci*10+4
              end if
-             if (mpi_tag > max_mpi_tag) then
-                write(logunit, F1I) 'MPI message tag ',mpi_tag,' exceeds max ',max_mpi_tag
-                call shr_sys_abort(subname//' ERROR: Max mpi tag exceeded')
-             end if
              call seq_map_map(comp(eci)%mapper_Cc2x, comp(eci)%c2x_cc, comp(eci)%c2x_cx, msgtag=mpi_tag)
           end if
 ```
--- 

@jedwards4b @rljacob do you agree with the above, or would you rather I add I the function to mpi-serial?

**Comment by rljacob** [comment]
Yes if you don't need that function that's even better.

**Comment by jedwards4b** [comment]
@jhkennedy can you also change one of the cime-developer tests to use mpi-serial?
I think this one https://github.com/ESMCI/cime/blob/master/scripts/lib/get_tests.py#L67
would be a good choice - just add _Mmpi-serial

**Comment by ekluzek** [comment]
I think mpi-serial is important for a couple of different reasons. First it's the simplest build/run configuration. It's the easiest thing you can setup for a new machine or compiler. For CTSM it's pretty critical because running with a single processor for a single grid-cell is actually an important configuration for us. There's a lot that can be done with running that single-point. Technically you can run with a single processor and use full MPI, but you are adding a ton of complexity for no reason, and actually adding possible failure points as well as slowing down initialization. For CTSM in our testing many of our tests explicitly tell it to use mpi-serial explicitly, so using MPI would require testnames to change. I'm pretty sure other component models have configurations with a single process as well, hence it's important outside of just CTSM. CAM has SCAM and I know POP has a single point option.

I think people can see that this is an important configuration that we need to keep working. But, I wanted to make sure it's clear to everyone that it really is important.

**Comment by billsacks** [comment]
Thanks, @jhkennedy this looks like a good solution. I appreciate your help getting this working!

**Comment by jhkennedy** [comment]
@jedwards4b -- that's a good idea -- I'm running the tests now, so a PR should be coming soon. 

@ekluzek -- thanks! That's good insight. My fix should keep mpi-serial wroking

@billsacks -- No problem! I broke it, so I should fix it!
