### ISSUE TITLE
shr_spnf_mod.F90 special functions, compilers, performance.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2893]
The shr_spfn_mod module in src/share/util defines special functions like erf for F2008 compilers that don't have them  OR compilers where the intrinsic is slower then the coded version.

The comments are from 2015:
```
! These compilers have the intrinsics.
! Intel also has them (and Cray), but as of mid-2015, our implementation is
! actually faster, in part because they do not properly vectorize, so we
! pretend that the compiler version doesn't exist.
#if defined CPRIBM || defined __GFORTRAN__
#define HAVE_GAMMA_INTRINSICS
#define HAVE_ERF_INTRINSICS
#endif

! PGI has external erf/derf and erfc/derfc, and will link them for you, but
! it does not consider them "intrinsics" right now.
#if defined CPRPGI
#define HAVE_ERF_EXTERNALS
#endif

! As of 5.3.1, NAG does not have any of these.
```

The Intel performance may need to be revisited.

Maybe NAG 6 has the intrinsics?

Experiments by @shz0116 for E3SM show that a routine like ndrop.F90 will vectorize better IF it calls the erf function directly and not through the shr_spfn_erf interface defined by shr_spfn_mod.F90.   One way to implement that is to add #ifdefs to ndrop.F90 to use either the intrinsic or the interface.  Another way, suggested by @philipwjones is to rewrite shr_spfn_mod.F90 so its just overloads erf with either the intrinsic or the code .

**Comment by rljacob** [comment]
See https://github.com/E3SM-Project/E3SM/pull/2586 for more discussion.

**Comment by shz0116** [comment]
Which compiler you have in mind ? In file
cime/config/e3sm/machines/config_machines.xml, it looks only intel compiler
is supported on cori-knl.


shan

**Comment by rljacob** [comment]
Yes its more the compiler version.  Any machine can that has it can be used.

**Comment by rljacob** [comment]
After discussion on a CIME telecon on May 29, 2019, we decided that E3SM can go ahead and use the built in erf by modifying its code and its config_compilers.   Doing this for all cases is deferred until someone has time to study it.
