### ISSUE TITLE
Rework #2828 to avoid changing answers for E3SM

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2898]
#2828 updated datm in a way that likely affected e3sm as well as cesm, but these changes aren't actually wanted in e3sm (yet). @ekluzek will rework this to distinguish between cesm and e3sm.

Initial questions before @ekluzek tackles this:

(1) @jgfouca can you let us know once you have confirmed that that PR was indeed responsible for some of the unexpected diffs you were seeing?

(2) @rljacob and/or @jgfouca - do you want Erik to fix this on maint-5.6 or just the master branch?

**Comment by jedwards4b** [comment]
I'm pretty sure that they are only working with master and not maint-5.6

**Comment by rljacob** [comment]
Just master.

**Comment by jgfouca** [comment]
@billsacks , confirmed. The change to namelist_definition_datm.xml causes the DIFF.

**Comment by billsacks** [comment]
Thanks, @jgfouca . So, @ekluzek can you please make this change on master when you get a chance in your schedule?

**Comment by ekluzek** [comment]
OK

**Comment by ekluzek** [comment]
OK, I took a look and it looks correct to me. I made one comment that you can take or reject.

**Comment by rljacob** [comment]
telecon: fixed.
