### ISSUE TITLE
Error in creat_newcase

### ISSUE THREAD

**Issue by Sanghoon-Shin** [ESMCI/cime#2899]
I am trying to run CLM for global scale in 0.5 degree (i.e., 720x360 grids).

I tried several compsets using the following command: For example,
“/create_newcase --case ~/ex1 --compset I2000Clm40SpCruGs  --res hcru_hcru --run-unsupported”
“/create_newcase --case ~/ex1 --compset IHistClm40SpCruGs  --res hcru_hcru --run-unsupported”
…. and others .....

I am repeatedly getting the error message as follows:
Compset longname is 2000_DATM%CRUv7_CLM40%SP_SICE_SOCN_RTM_SGLC_SWAV
Compset specification file is /gpfs/u/home/shinsa11/CLM/clm5.0/cime/../cime_config/config_compsets.xml
Compset forcing is 1972-2004
ATM component is  Data driven ATM  CLM CRU NCEP v7 data set
LND component is clm4.0:Satellite phenology:
ICE component is Stub ice component
OCN component is Stub ocn component
ROF component is RTM: River Transport Model
GLC component is Stub glacier (land ice) component
WAV component is Stub wave component
ESP component is
Pes     specification file is /gpfs/u/home/shinsa11/CLM/clm5.0/cime/../cime_config/config_pes.xml
Machine is cheyenne
Pes setting: grid          is a%360x720cru_l%360x720cru_oi%null_r%r05_g%null_w%null_m%null
Pes setting: compset       is 2000_DATM%CRUv7_CLM40%SP_SICE_SOCN_RTM_SGLC_SWAV
Pes setting: tasks       is {'NTASKS_ATM': -1, 'NTASKS_LND': -1, 'NTASKS_ROF': -1, 'NTASKS_ICE': -1, 'NTASKS_OCN': -1, 'NTASKS_GLC': -1, 'NTASKS_WAV': -1, 'NTASKS_CPL': -1}
Pes setting: threads     is {'NTHRDS_ATM': 1, 'NTHRDS_LND': 1, 'NTHRDS_ROF': 1, 'NTHRDS_ICE': 1, 'NTHRDS_OCN': 1, 'NTHRDS_GLC': 1, 'NTHRDS_WAV': 1, 'NTHRDS_CPL': 1}
Pes setting: rootpe      is {'ROOTPE_ATM': 0, 'ROOTPE_LND': 0, 'ROOTPE_ROF': 0, 'ROOTPE_ICE': 0, 'ROOTPE_OCN': 0, 'ROOTPE_GLC': 0, 'ROOTPE_WAV': 0, 'ROOTPE_CPL': 0}
Pes setting: pstrid      is {}
Pes other settings: {}
Pes comments: none
 Compset is: 2000_DATM%CRUv7_CLM40%SP_SICE_SOCN_RTM_SGLC_SWAV
 Grid is: a%360x720cru_l%360x720cru_oi%null_r%r05_g%null_w%null_m%null
 Components in compset are: ['datm', 'clm', 'sice', 'socn', 'rtm', 'sglc', 'swav', 'sesp', 'drv', 'dart']
No project info available
ERROR: PROJECT_REQUIRED is true but no project found

How can I solve the problem?

**Comment by jedwards4b** [comment]
Please use the user forum for this type of question http://forum.cgd.ucar.edu/
Cheyenne requires that you supply a user account.   You can do this on the command line with --project (see https://esmci.github.io/cime/Tools_user/create_newcase.html) 
See also 
https://esmci.github.io/cime/CIME_api/CIME.html?highlight=project#CIME.utils.get_project
Hierarchy for choosing PROJECT: 0. Command line flag to create_newcase or create_test 1. Environment variable PROJECT 2 Environment variable ACCOUNT (this is for backward compatibility) 3. File $HOME/.cime/config (this is new) 4 File $HOME/.cesm_proj (this is for backward compatibility) 5 config_machines.xml (if machobj provided)

**Comment by Sanghoon-Shin** [comment]
The project name (using --project) should be specified even if it is an optional variable.

**Comment by jedwards4b** [comment]
That depends on the system and on the user environment.
