### ISSUE TITLE
python 3 incompatibility

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2906]
@matt-long ran into this issue building a `G1850ECOIAF` compset on cheyenne with `T62_g17` resolution, and I can reproduce this error. Both of us are using `cesm2_1_alpha01d`, which includes CIME tag `cime_cesm2_1_rel_02`. The error comes from `case.submit`:

```
$ ./case.submit
...
ERROR: Command: 'qsub -q regular -l walltime=12:00:00 -A P93300606 -m ea -v ARGS_FOR_SCRIPT='--resubmit' .case.run' failed with error 'b'qsub: Illegal attribute or resource value select.mpiprocs''
```

But I think it can be detected after `./case.setup`:

```
(py2) $ ./case.setup
(py2) $ grep mpiproc .case.run
#PBS  -l select=14:ncpus=36:mpiprocs=18:ompthreads=2
```

```
(py3) $./case.setup
(py3) $ grep mpiproc .case.run
#PBS  -l select=14:ncpus=36:mpiprocs=18.0:ompthreads=2
```

Notice that python3 writes `mpiprocs` with a decimal point rather than as an integer. So I guess when parsing `env_batch.xml`, the line

```
<directive> -l select={{ num_nodes }}:ncpus={{ max_tasks_per_node }}:mpiprocs={{ tasks_per_node }}:ompthreads={{ thread_count }}</directive>
```

is computing `tasks_per_node` as a float rather than an integer? That's about as far as I've traced it, the workaround of "just use python 2" seems to be a good one.

**Comment by alperaltuntas** [comment]
PR #2859 solves this issue.

**Comment by mnlevy1981** [comment]
Oops, I missed the closed ticket (and merged pull request) when looking to see if this had been reported. I've verified that the issue is resolved by updating to `cime_cesm2_1_rel_03` so I'll close this ticket.
