### ISSUE TITLE
LII test does not fail when it should

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#291]
There are two bugs in the LII test (utils/python/CIME/SystemTests/lii.py):

1. the 'interp' version sets use_init_interp to .false., when it should in fact be set to .true.

2. The comparison between the 'base' and 'init_interp_on' versions was never implemented

**Comment by billsacks** [comment]
cc @mvertens @ekluzek

**Comment by mvertens** [comment]
I have pointed Bill to a modified version that hopefully works. Once this test is verified as working I will issue a PR with the fixes.
