### ISSUE TITLE
Need test for configure tool

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2911]
The configure tool (scripts/tools/configure) has been broken for a while and we didn't notice it. I've fixed it in E3SM. After the next split, we should add a test for it so we catch problems in the future.

**Comment by jgfouca** [comment]
@rljacob , @brhillman

**Comment by jedwards4b** [comment]
The configure tool is in tools/configure.   It would help if the issue included details about how it is broken.   
```
Traceback (most recent call last):
  File "../configure", line 159, in <module>
    _main()
  File "../configure", line 156, in _main
    opts['compiler'], opts['mpilib'], opts['debug'], opts['os'])
TypeError: configure() takes at least 8 arguments (7 given)
```
note that this occurs on master but not maint-5.6 (we are planning a new maint-5.6 release soon and so I thought it important to verify this).

**Comment by jedwards4b** [comment]
A test in scripts_regression_tests.py could run the configure script and compare the resulting Macros.make and env_mach_specific.xml to those generated in a case.   They should be the same.

**Comment by jgfouca** [comment]
@jedwards4b , yes, that would be a good test.

**Comment by mnlevy1981** [comment]
@jgfouca What is the fix to get the script working? I was about to open an issue because I just ran into the configure error (will switch to `maint-5.6` in the meantime)

**Comment by jgfouca** [comment]
@mnlevy1981 , I did the E3SM split, so master should have the fix. It's:

https://github.com/E3SM-Project/E3SM/pull/2626

**Comment by mnlevy1981** [comment]
Apologies for the above, my git remotes were not set up the way I thought they were... latest ESMCI master does indeed work for me
