### ISSUE TITLE
More flexible handling of domain information on cpl aux hist files

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2913]
Currently, when writing cpl auxiliary history files, domain information is only written to the first file. I believe this is the logic that implements that behavior:

https://github.com/ESMCI/cime/blob/a0c20f0892f73e1dcd22701acb29e7146d41238d/src/drivers/mct/main/seq_hist_mod.F90#L1223-L1226

This can be problematic when you want to do a later cplhist-forced run with a subset of the forcing data: You need to copy the domain information onto the first year that you're actually using. This can sometimes just be a minor annoyance, but it can be more problematic if you're using data from a location where you don't have write access.

Laura Muntjewerf in the CESM Land Ice Working Group has requested that this domain information be written to all files rather than just the first. For dlnd forcing files (which is what the LIWG cares about), this would increase file sizes by 36% – from 7.0 MB per year to 9.6 MB per year. I could imagine doing this via a flag to the `seq_hist_writeaux` call, so that this is just done for dlnd forcing files, not affecting file sizes in other cases.

I wonder if another alternative would be to tell dlnd the file name containing the domain information, which may not be one of the files that you're looping over. I seem to recall @Katetc and myself trying this and it didn't work, but this may have been user error on my part. @mvertens do you know if this option is possible, and if not, how hard it would be to make it possible?

@Katetc I'm tentatively assigning this to you, but I'm not sure of the priority at this moment.

**Comment by billsacks** [comment]
@mvertens do you have a sense of whether this issue would still apply in CMEPS? To summarize: there was a request to write domain information to all of the cpl aux hist files, not just the first, at least optionally; or to be able to tell dlnd the file name containing the domain information, which may not be one of the files you're looping over. Do you know if this will work already in CMEPS/CDEPS or if we should move this issue there?

**Comment by mvertens** [comment]
@billsacks - this issue is not relevant for CMEPS and should be closed in CIME.
