### ISSUE TITLE
PET test does baseline generation and comparison twice

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2916]
I noticed that the PET test is doing baseline generation and comparison twice: once before the base vs. single-therad comparison and once after it.

While this doesn't cause any major problems that I can see, it is a bit confusing, especially when looking at the copied cprnc.out files in the test directory from a failed baseline comparison (which contain two copies of the cprnc output concatenated together).

From a quick glance, my best guess is that this is due to the PET test being a multi-submit test, but I'm not sure about that.

**Comment by rljacob** [comment]
telecon:  in a "compare with baselines mode" it will compare each phase against the same single baseline.  in "generate baselines" it will copy files twice to the baseline, the last one sticks around.

**Comment by rljacob** [comment]
@jhkennedy are you working on this?

**Comment by jhkennedy** [comment]
@rljacob Yep! I should be able to get it wrapped up late this week or early next

**Comment by WesCoomber** [comment]
@billsacks 
Hi Bill, I am working on fixing this issue but I am having trouble recreating the bug. 

_When I do a run of create_test such as "./create_test -g -b wesleyCase PET_Ln9_P4.f19_f19.A", I only see a single instance of generating baselines in the TestStatus.log file._ Is there somewhere else I should be looking?

Wesley

**Comment by jedwards4b** [comment]
I think that to do this you need to run once and generate baselines and then run again to compare against those baselines - so you'll need to use the flags --generate, --compare and probably --baseline-root

**Comment by billsacks** [comment]
@WesCoomber I just did something similar from cime master on cheyenne: `./create_test --baseline-root /glade/scratch/sacks/cesm_baselines -g pet_0206a PET_Ln9_P4.f19_f19.A.cheyenne_intel` and got two blocks of `Generating baselines` in my `TestStatus.log`. Are you doing this on a machine with a batch system? I think the issue may be in the multi-submit implementation, so might only show up on a machine with a batch system (as opposed to your desktop, for example).

**Comment by WesCoomber** [comment]
_I have been working on the Sandia 'Melvin' machine and I did the --generate and --compare flag runs with no recreation of the bug. I will look into doing this on a machine with a batch system._ Thank you for the direction @jedwards4b and @billsacks .
