### ISSUE TITLE
Update hobart PGI compiler

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#2922]
PGI 18.10 is available on hobart, and it would be great if `config/cesm/machines/config_machines.xml` was updated to use it (we want to remove a PGI bug workaround from MARBL, but can't do that if CESM is still using a buggy version of the compiler).

I'm happy to put together a PR if someone lets me know the target branch / branches.

**Comment by jedwards4b** [comment]
maint-5.6 and master

**Comment by mnlevy1981** [comment]
Do we still need to support PGI on hobart? I'm pretty sure this issue can be closed, but I'd still like to remove the workaround from MARBL so basically it would mean CGD users couldn't use hobart for compsets that include POP (because POP always builds MARBL). Once the MARBL driver is finished in MOM, users could set `MOM6_BUILD_MARBL=FALSE` in `env_build.xml`, but that would preclude them from running with `USE_MARBL_TRACERS=True`. Is that okay, or should I try to bump hobart up to `compiler/pgi/18.10` (or `compiler/pgi/19.9`) one more time?
