### ISSUE TITLE
Support multiple queue matches

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2927]
On sandia machines, the "short" queue for small jobs generally gives you a shorter wait time and should thus be preferred if your job qualifies for it. However, sandia admins are sometimes seeing long lines for the short queue while the main "batch" queue has lots of free nodes. We want to request the short queue with an optional fallback to the batch queue. This can be done from the command line with "-p short,batch". It would be nice if CIME supported this.

**Comment by rljacob** [comment]
You want CIME to query the queue system to determine which one to submit to?

**Comment by jgfouca** [comment]
@rljacob , it already does that unless the user requests a specific one. What I want is, instead of stopping at the first compatible queue, continue iterating over queues and find all the compatible ones, and then let the batch system know that any of them would be acceptable for the job.

**Comment by rljacob** [comment]
You can submit a job with multiple "-q" options and let the system pick?  I didn't know that.

**Comment by jgfouca** [comment]
@rljacob , yes, I'm positive that slurm supports that and I wouldn't be surprised if other queue systems do too.

**Comment by jgfouca** [comment]
I've decided that the least-disruptive way to implement this feature is to simply embed the ability to fallback to another queue in the name of the shorter queue:

```
   <batch_system MACH="sandiatoss3" type="slurm" >
     <queues>
-      <queue nodemax="12" walltimemax="04:00:00" strict="true" default="true">short</queue>
+      <queue nodemax="12" walltimemax="04:00:00" strict="true" default="true">short,batch</queue>
       <queue walltimemax="24:00:00">batch</queue>
     </queues>
   </batch_system>
```
