### ISSUE TITLE
cime5 lost some functionality in cs.status that was in cimeteststatus

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#293]
cime5 lost some of the functionality in cs.status that was in the prior cimeteststatus. cimeteststatus was written in python, so adding some of this functionality back might not be that hard to do.

1.) cs.status requires you to cd to test directory

2.) cs.status doesn't allow helpful arguments like help

3.) cs.status doesn't have an option to combine test Id's together or specify a given test ID with a "-i" option

4.) cs.status removes the "-s" summary option, which made it easier to parse for fails

I also think the creation of the bash script for the specific test ID in the test directory is a bit awkward (the cs.status.<testID> scripts). Number "3" above is a better handling of this.

**Comment by billsacks** [comment]
For:

>3.) cs.status doesn't have an option to combine test Id's together or specify a given test ID with a "-i" option

we could just give cs.status an option saying what testid(s) to aggregate over, rather than having a separate cs.status file for each testid.

**Comment by ekluzek** [comment]
As a temporary workaround I have a script in CLM (currently on the esmci branch clm4_5_8_r174_esmciport) that replicates the functionality of cimeteststatus. @bandre-ucar. I'll take a look at the cimeteststatus in cime4 and make sure I replicate it's operation.

**Comment by fischer-ncar** [comment]
@ekluzek, can you point me to your script in clm4_5_8_r174_esmciport that replicates the functionality.

**Comment by ekluzek** [comment]
Yes it's at the top level, above the cime directory. The name starts with
parse.

**Comment by rljacob** [comment]
Is this still an issue?

**Comment by fischer-ncar** [comment]
Yes, I'm still working on it.

**Comment by rljacob** [comment]
@fischer-ncar are you still working on this?  Would like to assign to @jgfouca .

**Comment by fischer-ncar** [comment]
I want to be working on it, but haven't had the time.  You can go ahead and assign it to @jgfouca.
