### ISSUE TITLE
create_newcase and trailing '/' on case name

### ISSUE THREAD

**Issue by briandobbins** [ESMCI/cime#2937]
Hi all,

  This came up during some testing the other day - apparently creating a case with a trailing slash works fine (during create_newcase), but running a ./case.build on the created case will fail with the error:

ERROR: No default value found for case_name.

  Example:
create_newcase --case /home/foo/testcase_fails/ --compset B1850
...
./case.setup
...
./case.build
...
ERROR: No default value found for case_name._

  Is it worth adding a check to create_newcase for trailing slashes? 

  Thanks,
  - Brian

**Comment by jedwards4b** [comment]
@briandobbins thanks - I've pushed a fix to the aws-tutorial branch and also fixed on our main development branch.
