### ISSUE TITLE
Need an "all" option to --xml-category or preferably a regular expression check to create_test

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#294]
In cime4 the xml options for create_test had the ability for an "all" option or to enter a regular expression to match more than one category or compiler. I used this to match several CLM test lists (with -xml_category aux_clm.+), as well as match all compilers (with "-xml_compiler .+"). This was also useful to do a namelist generate/compare test for ALL tests for any machine, compiler, or category in the xml test list. 

The cime5 version doesn't require all of the -xml settings, and if not set will match everything -- but you still have to provide at least one "--xml-*" option. So if the "--xml-category" option could have the ability to do a regular expression pattern match for categories that would get the same functionality back. If the regular expression match seems too strange, the ability to set an option like "all" to "--xml-category" would at least allow the namelist generation functionality to work. But, since regular expression matching is a standard module of Python, I think the regular expression matching is a reasonable request.

**Comment by jgfouca** [comment]
Assigning @jedwards4b because he set up the xml options for create_test.
