### ISSUE TITLE
Allow CHARGE_ACCOUNT to be set from environment

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#2942]
On a machine with multiple projects or multiple charge accounts (e.g. Theta), it is convenient to set PROJECT and CHARGE_ACCOUNT from env-vars. CHARGE_ACCOUNT always inherits PROJECT's value. It would be useful for it to be set from CHARGE_ACCOUNT env-var, when this var is defined.

**Comment by sarich** [comment]
This was hopefully fixed by ESMCI PR #2888. It looks like it hasn't been merged to E3SM yet.

**Comment by jgfouca** [comment]
@amametjanov , can you confirm that CIME (not E3SM) currently does what you want?
