### ISSUE TITLE
CIME exception handling needs some improvement

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2947]
Problems:
* The bare except pattern ("except:") is used too frequently throughout CIME. It's only safe to use this pattern if the exception is re-raised by the handling block. Incorrect use of this pattern can result in very strange behavior when the user does a keyboard interrupt. We could catch BaseException if we want to satisfy code checkers.
* We rely too heavily on SystemExit. SystemExit is nice because it allows us to report user error without dumping an ugly stacktrace. It should probably not be used for CIME internal errors. We could continue to use "expect(...)" to check user inputs and use some other function, like "assert" for internal checking.
* We should probably subclass SystemExit for user errors.

**Comment by rljacob** [comment]
From telecon:

See https://airbrake.io/blog/python-exception-handling/class-hierarchy

Maybe just need to get rid of the few bare "except:".   So don't need a subclass?

Stacktrace from normal errors were confusing to users.   Any error would generate it.
