### ISSUE TITLE
data model processor limits

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2949]
Do the data models have limits on the number of processors they are run on ?  If so, some checking may need to be added for those limits.

Originally reported by Pat for datm.  He tried to run a DATM using T62 data on a 32000x1 decomposition and got a runtime error:

    20098:  ERROR: (shr_tInterp_getCosz)  ERROR: lon lat cosz sizes disagree

(many times - 11390 on Cori-KNL and 13952 on Titan), with the traceback for one of the failed processes of

     e3sm.exe           0000000001FB3116  Unknown               Unknown  Unknown
     e3sm.exe           00000000011EC50C  shr_abort_mod_mp_         114  shr_abort_mod.F90
     e3sm.exe           00000000013708C2  shr_tinterp_mod_m         388  shr_tInterp_mod.F90
     e3sm.exe           000000000133AB49  shr_strdata_mod_m         882  shr_strdata_mod.F90
     e3sm.exe           00000000004DC1AB  datm_comp_mod_mp_         643  datm_comp_mod.F90
     e3sm.exe           00000000004E276A  datm_comp_mod_mp_         554  datm_comp_mod.F90
     e3sm.exe           00000000004DA928  atm_comp_mct_mp_a         167  atm_comp_mct.F90
     e3sm.exe           000000000042C0EF  component_mod_mp_         267  component_mod.F90
     e3sm.exe           000000000041A0E1  cime_comp_mod_mp_        1174  cime_comp_mod.F90
     e3sm.exe           0000000000428F5F  MAIN__                     92  cime_driver.F90

Setting DATM to 9600 tasks worked.

**Comment by jedwards4b** [comment]
I'll wager that the limit is 192*96 = 18432 - are you surprised?

**Comment by rljacob** [comment]
Todo:  Make a more informative error message.
