### ISSUE TITLE
Locked cice file causing failed build.

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#2953]
With the current cime master, getting the following build error when running
SMS_Ln9.f09_f09_mg17.F2000climo.cheyenne_intel.cam-outfrq9s.

    ...calling cice buildcpp to set build time options
ERROR: locked

**Comment by jgfouca** [comment]
I think @jedwards4b already fixed this. Are you on latest master?

**Comment by jgfouca** [comment]
Whoops, you said so in your ticket. @jedwards4b , did you push that fix you made?

**Comment by fischer-ncar** [comment]
This is using the fix that @jedwards4b.  He fixed the error for cam and pop, but then the cice error
came up.

**Comment by jgfouca** [comment]
Ah, my bad. So he just needs to replicate his fix in cice.

**Comment by jedwards4b** [comment]
For both pop and cam the values were changed while the file was not locked and then there was a second attempt to change the values (to the same value as the first time) and that failed because the file was locked.   My fix (work around really) was not to worry about the file being locked if you were trying to set the value to the current setting.   I'll need to take a closer look at what is going on with cice.

**Comment by fischer-ncar** [comment]
It's not just the cice locked file that's a problem.    I'm also getting pop and cam locked
file errors when I try generating baselines.

./create_test SMS.f09_f09_mg17.F1850.cheyenne_intel.cam-outfrq9s --generate remove_me
             ...calling cam buildcpp to set build time options
        ERROR: locked'

./create_test SMS.T62_g17.C1850ECO.cheyenne_intel.pop-ecosys --generate remove_me
             ...calling pop buildcpp to set build time options
        ERROR: locked'

**Comment by jedwards4b** [comment]
I have a potential fix involving changes in pop, cam and cice - no changes in cime required.  I'm not entirely satisfied with the solution and want to discuss with @jgfouca before committing...

**Comment by jedwards4b** [comment]
I still get occasional errors like:
ERROR: File /gpfs/fs1/scratch/jedwards/SMS.f09_f09_mg17.F1850.cheyenne_intel.cam-outfrq9s.G.20190104_133903_bmjcgu/env_build.xml appears to have changed without a corresponding invalidation, modtimes 1546634478.46 != 1546634643.08

**Comment by jedwards4b** [comment]
Fixed by https://github.com/ESCOMP/CESM_CICE5/pull/12
and #2966
