### ISSUE TITLE
Remove support for building clm4.0

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2963]
In CESM, we're removing CLM4.0. This allows cleaning up some of the build logic in cime, since the clm4.0 library is handled differently from the modern clm library (the latter is done using a sharedlibbuild). I'll do this cleanup.

@rljacob @jgfouca @bishtgautam  I think the amount of cleanup I can do depends on whether you still use clm4.0 in e3sm. Can you please let me know if you do? I'm especially thinking of this block in the Makefile:

https://github.com/ESMCI/cime/blob/37d7afbe9e12bf8d281af7283756720faedb2aa4/scripts/Tools/Makefile#L816-L834

For cesm, we'll now _always_ have `USE_SHARED_CLM=TRUE`, so the `ifeq ($(USE_SHARED_CLM),FALSE)` block will just apply to e3sm. What I'm wondering is if you still need this block:

```Makefile
  ifeq ($(CLMVER),$(null))
    LNDLIB := liblnd.a
```

or if you can always use the clm4_5/clm5_0 version,

```Makefile
  else
    LNDLIB := libclm.a
```

It would really clean things up if I can get rid of the use of `CLM_CONFIG_OPTS` entirely, but I'll keep it in place if need be.

**Comment by rljacob** [comment]
We have removed clm40.  @jgfouca had some other reason why we couldn't build the shared clm lib.

**Comment by jedwards4b** [comment]
If I remember correctly it was because the e3sm version of clm still has build time dependancies while these have all been removed from ctsm.

**Comment by billsacks** [comment]
Thanks, @rljacob . I'll move ahead with the more aggressive removal of all things clm4.0-related.

**Comment by billsacks** [comment]
Hmmm, before I move ahead with this, I want to double check: I do see this on e3sm master:

```python
    if "clm4_0" in clm_config_opts:
        complib = os.path.join(libroot,"liblnd.a")
```

so I want to confirm: is that still present but unused?

**Comment by billsacks** [comment]
Ah, it looks like clm4.0 source code has been removed in E3SM, so I guess the remnants of references to clm4_0 there truly aren't exercised.
