### ISSUE TITLE
Have CIME control "pcols" setting in components/cam/bld/config_files/defaults_se.xml

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#2969]
Currently the value for "pcols" seems to be hardwired for all machines & compilers to 16 in components/cam/bld/config_files/defaults_se.xml. I would like to be able to set this parameter in CIME for machine files with a default to 16. I would also like to be able to have a compiler modifier to this entry in CIME. 16 is fine for most cases, but for the GPU port, we need to be able to set to 256 or even higher to have large kernels on the GPU. Currently we're having to hardwire 256 for the ACME-ECP repo, but ideally this would be CIME configurable since that value is not optimal for CPU architectures when you're scaled out and don't have many columns per node.

**Comment by jedwards4b** [comment]
You can change the pcols value with xmlchange - it is set in the CAM_CONFIG_OPTS variable as follows:
```
xmlchange --append CAM_CONFIG_OPTS="-pcols 32"
```

**Comment by billsacks** [comment]
I'm somewhat naive on this point, but I'd argue that the right way to do this would be for CAM's default file to have different options depending on the machine or compiler, which can be queried by CAM's build-namelist. It seems like we want to avoid having CIME know about component-specific variables like this for (at least) two reasons: (1) to keep cime model-agnostic as much as possible, and (2) (more pragmatically) to avoid requiring a cime update whenever CAM wants to change these defaults.

**Comment by jedwards4b** [comment]
@mrnorman : does my response meet your need?  If so please close.

**Comment by rljacob** [comment]
I would also agree with @billsacks, this is something for the CAM/EAM build-namelist machinery to handle.

**Comment by mrnorman** [comment]
@jedwards4b , thanks for the response. That seems like a good workaround for the meantime. I'm fine with this being handled in the CAM build-namelist stuff instead of CIME. I'll make this a github issue on the E3SM repo instead (assuming I'm understanding the conversation correctly).
