### ISSUE TITLE
--verbose is claimed to be an option to preview_namelist, but it isn't

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#297]
preview_namelist usage mentions: --verbose option, but it isn't available...

erik@yslogin6 ERI_D_Ld9.f10_f10.ICLM45BGC.yellowstone_pgi.clm-reduceOutput.GC.20160725_174057]$ ./preview_namelists --verbose
usage: 
preview_namelists [--verbose]
OR
preview_namelists --help
OR
preview_namelists --test

EXAMPLES:
    # Run 
    > preview_namelists
preview_namelists: error: unrecognized arguments: --verbose

Verbose is a useful feature, that I'd like to see added. But, at least the usage should be corrected.

**Comment by jedwards4b** [comment]
It appears that commit  9dba2a2799a21b769ffdc479fd16eaf396fafbd3 made jun 22nd removed the verbose option.   The debug option is still available and I have changed the documentation for preview_namelists to reflect this.

**Comment by jgfouca** [comment]
Fixed by #298
