### ISSUE TITLE
Backup input namelists

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#2971]
In a continued run, input namelists may change from run to run and not get reflected in corresponding component logs. This may have been brought up before. Can ${comp}_in files backed up to ${comp}_in.${LID} in the RUNDIR or its subdirectory?

**Comment by jedwards4b** [comment]
In general namelist values are output to the cooresponding ${comp}.log file at runtime - can you give an example where this is not the case?

**Comment by amametjanov** [comment]
For example, `bfbflag` for CPL and `docosp` for ATM. But I just found them in `performance_archive` subdirectories. That should be sufficient.
