### ISSUE TITLE
--skip-preview-namelists option doesn't work for tests.

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2981]
I found in an SMS test that this option doesn't work because the tests invoke case_setup.py which calls preview_namelists without consideration for this flag.   An SMS test can run without invoking preview_namelists on the compute nodes but there are other tests which probably cannot.  
We should either fix this or error out if a user trys to use the option in a test.

**Comment by WesCoomber** [comment]
@jedwards4b Hi JimE I am looking into this issue. 

The documentation says that the skip-preview-namelist option is supposed to skip calling preview-namelist during case.run.

_Could you give me an example of the steps to recreate proper usage and outcome of the --skip-preview-namelist option?_ 

When I create a new case (not a test) and run case.submit --skip-preview-namelist, I see the case still calling preview_namelists. Is this intended behavior for the -skip-preview-namelist, option on a cime case?

First I inserted print statements in preview_namelists.py to see when we call create_dirs() or create_namelists().

Then I create a new case:
`./create_newcase --case mycase --compset X --res f19_g16 `

Then I run case.submit --skip-preview-namelist and the arg is parsed.
```
mappy@</home/wpcoomb/skip/E3SM/cime/scripts/mycase>% case.submit --skip-preview-namelist
Namespace(batch_args=None, caseroot='/home/wpcoomb/skip/E3SM/cime/scripts/mycase', debug=False, job=None, mail_type=None, mail_user=None, no_batch=False, only_job=None, prereq=None, prereq_allow_failure=False, resubmit=False, resubmit_immediate=False, silent=False, skip_preview_namelist=True, verbose=False)
```
However, I observe the case still calling preview_namelists during case.run:
```
...
submit_jobs case.run
Submit job case.run
Starting job script case.run
2020-09-22 23:20:30 CASE.RUN BEGINS HERE
2020-09-22 23:20:30 RUN_MODEL BEGINS HERE
2020-09-22 23:20:30 PRE_RUN_CHECK BEGINS HERE
Setting Environment NETCDFROOT=/projects/sems/install/rhel7-x86_64/acme/tpl/netcdf/4.7.4/gcc/7.3.0/openmpi/2.1.5/acme
Setting Environment OMP_STACKSIZE=64M
Setting Environment OMP_PROC_BIND=spread
Setting Environment OMP_PLACES=threads
2020-09-22 23:20:31 NAMELIST CREATION BEGINS HERE
wpc0a. in preview_namelists.py. create_dirs. exeroot /ascldap/users/wpcoomb/acme/scratch/mycase/bld: libroot: /ascldap/users/wpcoomb/acme/scratch/mycase/bld/lib incroot /ascldap/users/wpcoomb/acme/scratch/mycase/bld/lib/include
wpc0b. in preview_namelists.py. create_namelists. casebuild /home/wpcoomb/skip/E3SM/cime/scripts/mycase/Buildconf: caseroot: /home/wpcoomb/skip/E3SM/cime/scripts/mycase rundir /ascldap/users/wpcoomb/acme/scratch/mycase/run
Creating component namelists
...
```
