### ISSUE TITLE
Baseline namelists for failed tests are not world-readable

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2982]
For most tests, the generated namelists (i.e., in the baseline directory) have permissions `-rw-rw-r--` (at least on cheyenne). However, for at least some tests that fail, the generated namelists have permissions `-rw-rw----`. This leads to incorrect NLCOMP failures when someone tries to do baseline comparisons but isn't in the appropriate group.

This is an issue for tests that are expected to fail some later phase (say, the RUN phase), but for which namelists should still have been generated / compared. It is also an issue for the FUNIT test.

**Comment by jgfouca** [comment]
@billsacks , take a look at utils.SharedArea context manager. We could tweak it to allow world read if everyone agreed that was OK.

**Comment by jgfouca** [comment]
Hmm, now that I look, 0o002 should already include world read. I'll take a look. Can you list one of the tests you had trouble with?

**Comment by billsacks** [comment]
This can be reproduced from standalone cime with something like the following (you'll need to adapt this to whatever machine you test this on, of course):

`./create_test --walltime 0:10 FUNIT_P1x1.f09_g17.X.cheyenne_intel --generate funit_0116a --baseline-root /glade/scratch/sacks/cesm_baselines`

I see:

```
[cheyenne6:/glade/scratch/sacks/cesm_baselines/funit_0116a/FUNIT_P1x1.f09_g17.X.cheyenne_intel]$ ls -l
total 2
drwxrwxr-x 2 sacks ncar 4096 Jan 16 10:59 CaseDocs
-rw-r--r-- 1 sacks ncar  532 Jan 16 11:01 TestStatus
-rw-rw---- 1 sacks ncar  848 Mar 16  2017 user_nl_cpl

[cheyenne6:/glade/scratch/sacks/cesm_baselines/funit_0116a/FUNIT_P1x1.f09_g17.X.cheyenne_intel]$ ls -l CaseDocs/
total 25
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 atm_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 cpl_modelio.nml
-rw-rw---- 1 sacks ncar 6123 Jan 16 10:59 drv_in
-rw-rw---- 1 sacks ncar  393 Jan 16 10:59 esp_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 glc_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 ice_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 lnd_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 ocn_modelio.nml
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 rof_modelio.nml
-rw-rw---- 1 sacks ncar 3911 Jan 16 10:59 seq_maps.rc
-rw-rw---- 1 sacks ncar  399 Jan 16 10:59 wav_modelio.nml
-rw-rw---- 1 sacks ncar  455 Jan 16 10:59 xatm_in
-rw-rw---- 1 sacks ncar  312 Jan 16 10:59 xglc_in
-rw-rw---- 1 sacks ncar  312 Jan 16 10:59 xice_in
-rw-rw---- 1 sacks ncar  312 Jan 16 10:59 xlnd_in
-rw-rw---- 1 sacks ncar  312 Jan 16 10:59 xocn_in
-rw-rw---- 1 sacks ncar  346 Jan 16 10:59 xrof_in
-rw-rw---- 1 sacks ncar  312 Jan 16 10:59 xwav_in
```

That test passed, but my hunch is that a passing FUNIT test (for which most aspects of the GENERATE phase are skipped) is having the same problem as a failing regular test in this respect.
