### ISSUE TITLE
NCR test fails at runtime and has never successfully run on yellowstone / intel

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#2989]
_From @bertinia on March 2, 2016 17:48_

Here is the email thread between Jim and Tony regarding this issue. Added this information as
a CIME issue for better tracking:
Hi Tony,

I'm looking closely at the NCR test and I don't see how it can ever work, or what it's intended to do. 

Tests that do two builds must assure that both builds use the same number of total mpi-tasks or they won't work.   This test doesn't seem to follow that rule at all.

It does two builds, in the first it sets the ROOTPE for all components to 0 and sets the task count for each component to ntasks/2.   So an f19_g16.B1850 uses 210 tasks by default and this first build will use 90 tasks.    The second build goes back to the original number of tasks per component but then sets ROOTPE so that no components overlap so that ends up being 746 total tasks.  

Neither of these builds will work.    Now maybe you defined a test with a narrow intent and we are trying to use it outside the scope of that intent.   So I would like to correct the problem by putting in
some error checks so that if the test isn't properly specified it won't let you build it - maybe even put the error checks in create_test so that it won't let you create it in the first place -  In order to do that I need to figure out what the original intent of the test was.   Can you explain?

---

Hi Jim,

The desc for NCR in the config_tests.xml says,

```
<DESC>multi-instance validation sequential vs concurrent (default length)</DESC>
```

I'm looking at the scripts now to try to understand what the goal was.

I think at some point, we had some problems where two identical instances were
not getting identical answers.  I think this test tries to cover that case and more.
I think the idea was to run all models sequentially as a single instance and then
to run the model concurrently with two instances where each instance pe count
matches the pe count of the single instance sequential run.  Then we can check all 
three instances that they are identical.  In a single test, we are checking that
the sequential and concurrent runs are identical and that single and multiple
instances are identical.

The cime scripts have changed a lot in time.  I'm pretty sure the original implementation
created queue info that worked for the 2 instance fully concurrent case.  Then the
single instance was run on fewer pes within that request.  I could start to look back
on older versions to try to flush this out further.  The NCK test seems to do
something similar.  I can't remember exactly why we decided to have both tests
around.  Obviously there are differences and the NCR does test some different
aspects.

Anyway, is that enough to move forward?

_Copied from original issue: CESM-Development/cime#384_

**Comment by fischer-ncar** [comment]
I just transferred this from CESM-Development.  This test isn't normally run.  It's current state is it doens't
even build any more.

**Comment by rljacob** [comment]
telecon: this test is still in the repo.  We do need more multi-instance testing.

**Comment by billsacks** [comment]
For CESM, we feel this is no longer a priority, so are closing this as a wontfix. @rljacob feel free to reopen if you feel it's a priority for E3SM.
