### ISSUE TITLE
Problem with cime5 configure when building other tools.

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#299]
configure in cime/tools/configure fails in cime5 due to a missing perl module?

Can't locate Module/ModuleLoader.pm in @INC (@INC contains: /glade/scratch/erik/cesm2_0_alpha01/cime/utils/perl5lib /glade/scratch/erik/cesm2_0_alpha01/cime/utils/perl5lib/Config /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /glade/scratch/erik/cesm2_0_alpha01/cime/tools/configure line 146.

**Comment by jedwards4b** [comment]
Sean is working on this.

**Comment by rljacob** [comment]
Whats the case and machine/compiler?

**Comment by ekluzek** [comment]
@rljacob it's when the configure is used outside of CESM to build an offline tool such as gen_domain. So my case was with gen_domain for yellowstone_intel.

**Comment by ekluzek** [comment]
@quantheory any update on this? I still see this problem in the latest cime -- cime5.0.4.

I looked into it a bit further and I can get further along, if I bring in some of the old perl modules like: Module/ModuleLoader.pm, Config/ConfigMachine.pm, and Config/ConfigCase.pm. But, it will then still fail with...

	ERROR add_config_variables: default_value must be set for SYSTEM_TESTS_DIR in /fs/cgd/data0/erik/clm_esmciport/cime/cime_config/cesm/config_files.xml

**Comment by quantheory** [comment]
Oh, didn't realize I was assigned on this. When Jim said I was working on this, what he meant was that I'm replacing the `configure` script entirely, with a Python version. I wasn't planning to add that until next week, honestly, when I get back to working on `config_compilers`/`config_build`.
