### ISSUE TITLE
cheyenne batch directives incorrect when using an unknown queue

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2994]
This came up in the CTSM tutorial this week, in which participants were directed to use a special queue on cheyenne. I imagine it could impact other, future tutorials, as well as other use cases where users use some special queue for their work.

When you set a cheyenne queue to something unknown to cime, using something like:

```
./xmlchange JOB_QUEUE=R4231261 --subgroup case.run --force
```

you get batch directives that are appropriate for a single-node run rather than a multi-node run.

Here is an example: For `./create_newcase --case $scratch/test_queue_0208a --compset A --res f45_g37 --run-unsupported` followed by `./xmlchange NTASKS=144`: with the default queue, I have the following in `.case.run`:

```
 #PBS  -l select=4:ncpus=36:mpiprocs=36:ompthreads=1
```

But if I use the above `./xmlchange JOB_QUEUE` command, I instead get:

```
 #PBS  -l select=1:mpiprocs=144:ompthreads=1
```

which seems to put the whole job on a single node, leading the job to hang.

A couple of possible solutions come to mind, but I'm not sure which is the right one to do here:

(1) In CESM's config_batch.xml, for cheyenne, have a default directives block that applies to any queue not explicitly specified:

```xml
  <batch_system MACH="cheyenne" type="pbs">
    <directives>
      <directive default="/bin/bash" > -S {{ shell }}  </directive>
      <directive> -l select={{ num_nodes }}:ncpus={{ max_tasks_per_node }}:mpiprocs={{ tasks_per_node }}:ompthreads={{ thread_count }}</directive>
    </directives>
```

(Would this let us remove the duplicate directives blocks that are currently specified for regular, premium and economy, or would those still be needed?)

(2) It seems like there is some logic that picks up the last queue specified in the directives blocks for an unknown queue; if that were either changed to pick up the first, or if we reorder those blocks for cheyenne, then maybe this would work correctly. (Not yet tested.)

(This seems somewhat related to issue #2551 , which @jedwards4b resolved last May.)

**Comment by jedwards4b** [comment]
I would prefer option (1) - do you know if it works in the current cime?

**Comment by billsacks** [comment]
@jedwards4b - from a bit of playing around, it looks like (1) does _not_ currently work.

I'll give more details, but first I want to correct what I suggested for (2) in my original comment: it turns out that an unknown queue is getting values from the share queue because the share queue is listed as the default (`default="true"`) here:

https://github.com/ESMCI/cime/blob/a5bea3aab3cf3669fbc2ff4e73a87dbcddc724ae/config/cesm/machines/config_batch.xml#L204-L209

So if we went with solution (2), the solution would be to change which queue is labeled as default there... I'm not sure what negative implications that might or might not have. (It looks like the share queue has been labeled as 'default' ever since it was added in #2335 .)

Regarding option (1): I tried this:

```diff
diff --git a/config/cesm/machines/config_batch.xml b/config/cesm/machines/config_batch.xml
index b008ccb..8a71942 100644
--- a/config/cesm/machines/config_batch.xml
+++ b/config/cesm/machines/config_batch.xml
@@ -182,17 +182,7 @@
   </batch_system>

   <batch_system MACH="cheyenne" type="pbs">
-    <directives queue="regular">
-      <directive default="/bin/bash" > -S {{ shell }}  </directive>
-      <directive> -l select={{ num_nodes }}:ncpus={{ max_tasks_per_node }}:mpiprocs={{ tasks_per_node }}:ompthreads={{ thread_count }}</directive>
-    </directives>
-
-    <directives queue="premium">
-      <directive default="/bin/bash" > -S {{ shell }}  </directive>
-      <directive> -l select={{ num_nodes }}:ncpus={{ max_tasks_per_node }}:mpiprocs={{ tasks_per_node }}:ompthreads={{ thread_count }}</directive>
-    </directives>
-
-    <directives queue="economy">
+    <directives>
       <directive default="/bin/bash" > -S {{ shell }}  </directive>
       <directive> -l select={{ num_nodes }}:ncpus={{ max_tasks_per_node }}:mpiprocs={{ tasks_per_node }}:ompthreads={{ thread_count }}</directive>
     </directives>
```

This seemed to work correctly for both the regular queue and the premium queue, based on comparing the `.case.run` file with one from a previous case. However, when I specified the share queue, I ended up with two sets of directives – one from the generic directives block (with no attributes), and one from the share queue block:

```
#PBS  -S /bin/bash
#PBS  -l select=4:ncpus=36:mpiprocs=36:ompthreads=1
#PBS  -S /bin/bash
#PBS  -l select=1:mpiprocs=144:ompthreads=1
```

I get the same result when using an unknown queue, presumably because the logic in #2552 leads to picking up the share queue block (since that's the default queue on cheyenne), and that gets added to the block that doesn't have an attribute.

So for solution (1) to work, I think we'd need:
- Only one directives block should be picked up (the one with the "best" match), rather than picking up all matching blocks. (That could quite likely cause problems elsewhere.)
- Parts of #2552 would need to be backed out, so that an unknown queue no longer picks up the block of the default queue

**Comment by jedwards4b** [comment]
Isn't the real solution just to provide cime with a definition for the additional queue? 
I believe that this could be located in the users $HOME/.cime/config_batch.xml file.

**Comment by billsacks** [comment]
@jedwards4b I think that's a complicated solution for people who are not too familiar with cime/cesm, as is the case for most tutorial users. And for the tutorial, there has been a different queue every day, making this even more complex.

That said, I'm open to this issue being closed as a wontfix if you feel it will be too difficult to resolve.

**Comment by jedwards4b** [comment]
I guess I think that it's a pretty unique situation that should be resolved in the context of the tutorial rather than in general.

**Comment by rljacob** [comment]
I like the idea of default directives that apply if the queue you specify is not defined.

**Comment by billsacks** [comment]
I have something that I think is working (see commit referenced above in this issue). I'll open a PR later - I'm on parent duty now.

**Comment by billsacks** [comment]
@jedwards4b while part of me agrees with you, part of me disagrees, because it feels like tutorials are a very important use case, where problems like this can cause massive frustrations for both the leaders and the participants, and people can come away feeling like this system is complicated and buggy rather than something they want to use.

The problem here is that the default queue is used for multiple, sometimes incompatible purposes. I'll open a PR with a possible solution to this problem, which allows specification of a default queue to use for the sake of picking up the correct directives.
