### ISSUE TITLE
Start using ESMF mesh files in place of SCRIP grid files

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2997]
For our mapping we currently using SCRIP grid files to define our grids for components. We then use these files to create mapping files as well as domain files from the mapping files. We are also already using ESMF to create the mapping files. If we upgrade to use ESMF mesh files rather than SCRIP grid files, the mapping files can be created faster. And we can also take advantage of the new ESMF OCGIS tool that can do the mapping in "chunks" rather than requiring to load both files into memory.

@billsacks and @mvertens and I talked about this in regard to CTSM tools. But, this also applies to CESM mapping files and domain files as well.

Perhaps a step we could do in this direction would be to run a tool to convert the current list of SCRIP grid files to ESMF unstructured mesh files. Other steps would be to change gen_domain and gen_cesm_maps.sh.

**Comment by rljacob** [comment]
E3SM may want to do this too.  Can you point me to the ESMF mesh file spec?

**Comment by ekluzek** [comment]
Here's a link for a specific ESMF version:

http://www.earthsystemmodeling.org/esmf_releases/public/ESMF_7_1_0r/ESMF_refdoc/node3.html#SECTION03028200000000000000

**Comment by rljacob** [comment]
@ekluzek what do you mean by "use parallel ESMF tools for mapping".  The parallelism depends on the input grid type?  For what mapping function?

**Comment by ekluzek** [comment]
No. I mean the parallelism that's used in creation of the mapping files. The resulting mapping files should be identical in either case (or nearly identical). The difference is that the ESMF grid files (as opposed to SCRIP grid files) give connectivity information that can help in the creation of the mapping files in parallel. So in most cases using a ESMF grid file rather than a SCRIP grid file will be faster.

Another thing we are investigating for CTSM is using the ESMF tool OCGIS, which can do the mapping in "chunks" so that the memory requirements aren't enormous like it is with the ESMF regrid tool that loads the entire file at once. This is separate from this issue of changing the grid files used in creating maps, but it's in the general topic of creating mapping files for running CIME.

https://github.com/NCPP/ocgis/tree/master/src/ocgis

**Comment by rljacob** [comment]
Ok so its faster but you can still run ESMF_Regridder in parallel with SCRIP files?  That's been my understanding.

**Comment by ekluzek** [comment]
Yes, you are right. I modified the opening statement -- hopefully it's more clear now.
