### ISSUE TITLE
Move new documentation to ESMCI

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#300]
Move the developing user's guide to ESMCI

**Comment by gold2718** [comment]
This is an issue but sounds like a pull request. Am I missing something?
Also, I think ACME-specific stuff should be in the ACME fork/clone and the CESM-specific stuff should be in CESM-Development.

**Comment by jedwards4b** [comment]
The bulk of the CIME users guide should not be model specific.

**Comment by rljacob** [comment]
Its a task that needs to be done.  We're also using issues for tasks.  See https://waffle.io/ESMCI/cime

The CIME users guide should be entirely model-neutral.
