### ISSUE TITLE
use globus-sdk as well as globus-url-copy in cime check_input_data

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3017]
Currently we use the globus-url-copy command line tool for anonymous download from the ncar cgd inputdata server.  But some hpc centers (ncar) don't like that tool and want to use the globus-sdk instead.

**Comment by jedwards4b** [comment]
Baldwin, Sterling Avalon <baldwin32@llnl.gov>
wrote: 
I haven’t used the globus-url-copy tool, but I have made fairly extensive use of the globus-cli and globus-sdk python packages and would be glad to help. I have a couple simple wrappers around the Globus transfer functionality that you can look at for inspiration here: https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/globus_interface.py

 

Using the python API for Globus transfers is fairly straightforward, but it’s a couple steps:

 

Get a transfer client https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/filemanager.py#L555
Create the transfer task with the client and the two UUIDs for the source and destination nodes https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/globus_interface.py#L44
Add the source and destination path for each file that needs to be copied over https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/globus_interface.py#L57
Submit the task https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/globus_interface.py#L66
And optionally wait around for the task to finish/error. https://github.com/E3SM-Project/processflow/blob/master/processflow/lib/globus_interface.py#L78
 

If you’re moving all the contents from a directory and only files from one directory, you can skip the step where you add the files in one at a time and just pass the directory path, all its contents will then be moved (recursively if it’s a directory tree and you set the recursive flag to true). When setting up the transfer task you can also specify several different sync levels, which tells globus to do things like, only move files if they don’t exist on the destination (no over write), only move files if the files at the source are newer (over write old files), or only move files if the checksums are different. The checksum option is usually best since you’re certain to have the correct files at the destination, but it does add some time to the transfer especially for very large files.

 

If you have any questions I’m happy to help!

**Comment by rpwagner** [comment]
@lukaszlacinski can you help with this, as well?

**Comment by lexming** [comment]
We would also be interested in having support for globus-sdk and having an endpoint in Globus with the input data as FTP is commonly blocked for security reasons.

**Comment by lukaszlacinski** [comment]
I will be working on this issue. (I'm from the Globus team).

**Comment by jedwards4b** [comment]
Hi @lukaszlacinski I took a look at this last week and found that the inputdata globus endpoint at ncar is currently broken.  System team is working on it and should have it up sometime this week.

**Comment by rljacob** [comment]
You should be able to test this using the LCRC globus end point since it can read the E3SM inputdata dir.

**Comment by jedwards4b** [comment]
The CESM inputdata end point at NCAR CGD Anon is now working again.   @lukaszlacinski have you made any progress?

**Comment by lukaszlacinski** [comment]
There are two servers with input data (used in the E3SM project):
 - https://web.lcrc.anl.gov
 - https://svn-ccsm-inputdata.cgd.ucar.edu
The input data available on the server at NCAR are also accessible via the "NCAR CGD Anon" Globus endpoint with anonymous access (myproxy.globusonline.org is specified as MyProxy Server). The endpoint is Globus Connect Server v4, so no HTTPS server is associated with the Globus endpoint. The endpoint is set up on gridanon.cgd.ucar.edu. In case, svn-ccsm-inputdata.cgd.ucar.edu is down, the input data might be accessed via the Globus endpoint.

**Comment by jedwards4b** [comment]
@lukaszlacinski The svn server is relatively slow and we consider it the least desirable data transfer method.   The servers are listed in config_inputdata.xml in order of preference.   For cesm this is (gftp, wget, ftp, svn)
