### ISSUE TITLE
Start adding support for CMIP6 SSP-RCP into cime

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3025]
In order to support the new CMIP6 SSP-RCP scenarios in cime, we need the following updates into datm:

- CO2 for each scenario
- prescribed aerosols for each scenario
- CPLHIST forcing for each scenario

Those are all changes in cime/src/components/data_comps/datm/cime_config/config_component.xml

In addition 

cime/src/drivers/mct/cime_config/config_component_cesm.xml needs the following:

Description added for SSP periods, and CCSM_BGC set for SSP periods.

**Comment by rljacob** [comment]
telecon:  this is already in maint-5.6
