### ISSUE TITLE
Remove CMIP5 RCP scenarios

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3026]
I think we should remove the CMIP5 RCP scenarios from cime as we start adding in the CMIP6 SSP-RCP scenarios (see #3025). This means the following changes

In  cime/src/components/data_comps/datm/cime_config/config_component.xml

Setting for CO2 removed for each RCP
prescribed aerosols for each RCP
CPLHIST forcing for each RCP

In addition

cime/src/drivers/mct/cime_config/config_component_cesm.xml needs the following:

Description for RCP removed as well as CCSM_BGC set for RCP's.

**Comment by jedwards4b** [comment]
Are they in the way?  I think that there still may be some desire to run cmip5 scenarios in the future.

**Comment by ekluzek** [comment]
I started removing them in CTSM, so that ssp_rcp and rcp wouldn't get confused. Here I think it might be OK to have both, but it's not immediately obvious to the uninitiated that one is CMIP5 and one is CMIP6. But, if components like CTSM start removing the capability to utilize them, it won't work for the full system anyway. I'm pretty sure not all the CMIP5 RCP's even still exist, nor do components necessarily respond to them. So I don't think you get something useful now, which is why I think they should go away (as well as making it more clear for what you should use for CMIP6 future scenarios).

If there is a desire to run both CMIP5 and CMIP6 as a requirement, we need to hear that that is the case, so we can plan on that. That ability is definitely not there now.

**Comment by jedwards4b** [comment]
Thanks for checking before removing them.

**Comment by jgfouca** [comment]
@ekluzek , is this done?

**Comment by ekluzek** [comment]
@jgfouca no it's not. But, I did get approval for it to happen.

**Comment by ekluzek** [comment]
Here's the message I got from Gokhan on March 6th for the CESM side...

Erik,

As far as I know, we are not planning to carry along CMIP5 RCPs in CESM2. If we were to do so, it goes beyond just carrying RCP data sets as the PI and 20C simulations also need "consistent" data sets, I believe. The only set of simulations that we said we would do is a few ensemble members of RCP8.5 simulation with CESM2 to compare the solutions with RCP8.5 and SSP5-85. These are just one-off simulations and do not necessarily require official support. 

Best,
Gokhan

**Comment by rljacob** [comment]
telecon:  this is done in maint-5.6
