### ISSUE TITLE
Possible issues with inputdata checksum downloads

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3034]
I have noticed two possible issues with the inputdata checksum implementation. I'm not sure if these are actually issues, but wanted to get @jedwards4b 's thoughts on these:

(1) I noticed that my tests were downloading the `inputdata_checksum.dat` file every time I ran `./case.submit`. I would have thought this download from the inputdata server would only happen if (a) you are actually downloading any files (e.g., the first time it goes to download a file, it downloads the checksum file from that server, too), or (b) you run `check_input_data` with the `--chksum` argument.

(2) In this loop:

https://github.com/ESMCI/cime/blob/e1779e35e9d62f2d1a4f66b13aa8a71d6e37cb45/scripts/lib/CIME/case/check_input_data.py#L140-L159

If I'm understanding the logic correctly, the loop will exit as soon as it downloads the first checksum file successfully - rather than, say, downloading the checksum file from each server. Is that actually what's intended here? (Or am I misunderstanding the logic?)

**Comment by jedwards4b** [comment]
Yes these are both issues that should be addressed.
