### ISSUE TITLE
Why does SMS test copy history files to add .base suffix?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#3072]
I'm running a single gx1v7 test of POP (with the ecosystem enabled) - an `SMS` test that isn't generating or comparing to any baselines. The actual CESM run has been finished for 35 minutes, but the test suite is copying a 29 GB history file (`SMS_D_P144x1_Ld1.T62_g17.C1850ECO.hobart_nag.pop-ecosys_144blocks_320x384_spacecurve.20190408_140214_rcor33.pop.h.0001-01-01.nc` to `SMS_D_P144x1_Ld1.T62_g17.C1850ECO.hobart_nag.pop-ecosys_144blocks_320x384_spacecurve.20190408_140214_rcor33.pop.h.0001-01-01.nc.base`). Is this copy necessary? What purpose does it serve?

**Comment by jedwards4b** [comment]
It's not required for an SMS test.

**Comment by mnlevy1981** [comment]
Cool, if it's not necessary can we remove it? I was seeing it with the `cime5.6.13` tag but I wouldn't be surprised if it was an issue on `master` as well

**Comment by billsacks** [comment]
It looks like the SMS test doesn't explicitly do a copy, but this arises from the generic system_tests_common, in the call to `_component_compare_copy` from `run_indv`. Tests that need this copy currently rely on it being done there. That said, it might be a good idea to change this behavior, particularly if it's causing problems. I suspect that this could be moved from system_tests_common to system_tests_compare_two - adding a call to `_component_compare_copy` after the two calls to `run_indv` in the `run_phase` function. That would cover many, but not all of the tests that need it. Similar changes would be needed in the handful of tests that need this but don't extend system_tests_compare_two.
