### ISSUE TITLE
Optional stub component of TEST is unknown

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#3077]
This is related to PR #3068.

For several CESM prealpha and prebeta tests, the ETEST and DTEST compsets have an
unknown model type error.  A couple of tests run were.

ERI.f19_g17_rx1.DTEST.hobart_intel.cice-default
ERS_Ld5.f19_g17.ETEST.hobart_nag.cice-default

The long names for DTEST and ETEST are.
2000_DATM%NYF_SLND_CICE_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST
2000_CAM60_CLM50%SP_CICE_DOCN%SOM_MOSART_SGLC_SWAV_TEST

The error message is.

       ERROR: Unknown model type, TEST

**Comment by jedwards4b** [comment]
This should be fixed on the cime master - have you tried the latest?

**Comment by gold2718** [comment]
Should be fixed in 4e86cc075026bc71c21419f6879920e5c80bf6df

**Comment by fischer-ncar** [comment]
This has been fixed.
