### ISSUE TITLE
Allow datm to have partial years of data

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3083]
For CTSM, we'd like the capability for datm to have partial years of data. This will support regional applications over the U.S., for which we'd like to have a frequently updated dataset with the latest reanalysis data over the U.S.

According to @swensosc, it sounds like the Fortran can handle this, so this is a matter of generalizing the scripts to build the out-of-the-box streams list to allow partial years of streams data. (Currently, nmlgen.py:`_sub_paths` assumes full years of data. I guess we'd need new xml variables controlling this so that it could produce partial years worth of streams files.)

cc @ekluzek @barlage @swensosc @dlawrenncar

**Comment by ekluzek** [comment]
Closing because this should be moved to CDEPS.
