### ISSUE TITLE
For PEM tests, CIME does not download N/2 graph files

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#3092]
In E3SM, we have a test:
```
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF
```
Since it's a PEM test, it needs the 240 graph files in addition to the 480 files, but CIME does not appear smart enough to know that.

**Comment by jonbob** [comment]
This is still an issue for the MPAS components in E3SM

**Comment by jonbob** [comment]
@jedwards4b -- I'm not sure what you're asking, but the MPAS components do not generate graph files on the fly. So we run into issues with the second cases failing because the graph files are not automatically downloaded by the check_input_data script

**Comment by jedwards4b** [comment]
That's exactly my point - there is no good reason that MPAS can not generate graph files in line and my suggestion is that if you fix that issue this issue goes away.

**Comment by jonbob** [comment]
Unfortunately it's not that easy

**Comment by jonbob** [comment]
The situation in E3SM is for MPAS ocn and ice

**Comment by jgfouca** [comment]
@jasonb5 , @jedwards4b , I thought we fixed this? Am I not remembering right?

**Comment by jedwards4b** [comment]
Not as far as I know - I would argue that generating graph files inline for the given PE layout is the better solution.

**Comment by jasonb5** [comment]
I just fixed calling `check_all_input_data` before running each `run` staged of a test. If the data is available through an `input_data_list` then it will be pulled. https://github.com/ESMCI/cime/blob/88255d5a5a1b160ec523a95fd26d6be079c54935/CIME/SystemTests/system_tests_common.py#L452-L460

**Comment by jgfouca** [comment]
@jasonb5 , great. We just need to run a test to confirm that the test listed in the ticket works. @jonbob is that something you could do? You'd need to remove the graph files from the input area to confirm that both get downloaded.

**Comment by rljacob** [comment]
@jonbob for production, we want the good graph files.  For testing, we just need one that works.

**Comment by jonbob** [comment]
Rob -- we make all of the necessary graph files and they are available on the inputdata server. I would worry that since we test more with "real" grids instead of small test ones, we will end up with a mix of efficient and simple graph files, without knowing it. I would push for really fixing this issue instead

**Comment by jgfouca** [comment]
@jonbob , let me confirm that our CIME has the fix.

**Comment by jasonb5** [comment]
@jgfouca Just ran `PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-PISMF`, using `--input-dir` and the test passed.

**Comment by jgfouca** [comment]
@jasonb5 , nice! Did you remember to "sabotage" the input files such that it would have to download both graph files?

**Comment by jgfouca** [comment]
Ah, I see you used your own input_dir. That's great.

**Comment by jonbob** [comment]
Thanks @jgfouca and @jasonb5!
