### ISSUE TITLE
Multi-instance log files not zipped or copied to $CASEROOT/logs

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#310]
This issue is NOT new to cime5, but I just noticed it. (I see the same issue with cime5.0.3 and with cime4.) I have observed this with ERS_D_N2.f10_f10.ICLM45.yellowstone_gnu.clm-default.

The multi-instance log files (files like lnd_0001.log.*, lnd_0002.log.*, etc.) are not gzipped, and are not copied to the $CASEROOT/logs directory.

**Comment by jgfouca** [comment]
Assigning @jedwards4b because I have too many issues already. Feel free to reassign.
