### ISSUE TITLE
DAE.ww3a.ADWAV test hangs on anlworkstation using PIO2

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#3105]
This is a confirmed regression caused by PR #3101, which turns off USE_MALLOC in PIO2 build.
While we will try to fix this issue in PIO2, it is recommended to turn on USE_MALLOC by default.

**Comment by dqwu** [comment]
@jayeshkrishna
The test does not hang with NCAR's PIO2, so we need to check E3SM's PIO2 fork.

**Comment by jayeshkrishna** [comment]
Maybe this should go as an issue in E3SM fork
