### ISSUE TITLE
Misleading TestStatus.log contents for failing 2-case tests

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#3106]
We have a failing test on the E3SM side, ERP_Ln5.ne30_ne30.FC5AV1C-L, which is failing the case2 phase of the test. The resulting $case/TestStatus.log file is somewhat misleading, since all the text it has indicates that the test worked. You have to go to $case/case2/TestStatus.log to begin to see the errors.

It seems like it would make more sense for case2 to simply append it's test log data to the case1's TestStatus.log file.

**Comment by billsacks** [comment]
I'm not supposed to be taking on much cime development right now due to other demands on my time, so I'm unassigning myself.

**Comment by billsacks** [comment]
Would an easy fix be to create a sym link called TestStatus.log in the case2 directory that points to TestStatus.log in the case1 directory when case2 is created? I'm not sure what negative repercussions (if any) that might have?

**Comment by jedwards4b** [comment]
No need for that  - there is already a self._orig_caseroot in the tests, it's just a matter of using that for append_testlog.
