### ISSUE TITLE
Tested compsets category too narrow

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#3127]
Currently, a compset -- grid combination is considered supported if it is tested in certain test categories such as prealpha, prebeta, or aux_*. test_release is omitted from that list.
Is this on purpose? If so, why? If not, can we add test_release to the list?

**Comment by gold2718** [comment]
Test case which I think should work:

`./create_newcase --case supportme --compset FTJ16 --res f09_f09_mg17`

**Comment by jedwards4b** [comment]
The code is here https://github.com/ESMCI/cime/blob/maint-5.6/scripts/lib/CIME/case/case.py#L1328
this is the list agreed to by software liaisons.   test_release is not a category I was even aware existed - did your liaison bring this to cseg members as a category that should be added to the list of those tested and supported?

**Comment by gold2718** [comment]
I know what the code says (which is where I got the list in my original message since I could not find this in the CIME documentation).
This issue was reported by a user who was surprised that a tested compset -- grid combination is still not considered supported.
If you feel that test_release does not qualify as support, then please document what does qualify (or point me to the documentation I missed).
If it does qualify, can we add it to the list?

**Comment by jedwards4b** [comment]
Again - I defer to the cam group and the cam software liaison who were the ones who imposed this entire idea of supported and tested compsets.

**Comment by billsacks** [comment]
It looks like this was fixed, so closing.
