### ISSUE TITLE
Ice shelf coupling needs flag to turn off glcshelf_c2_ice

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3130]
With the ice shelf coupling added in #3123 , @fischer-ncar is getting failures in these two tests:

```
 NCK_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling
 SMS_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling
```

The error message is: `Failed to open file idmap_ignore`. The traceback is:

```
0:MPT: #7  0x0000000002d954e6 in shr_abort_mod_mp_shr_abort_abort_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/share/util/shr_abort_mod.F90:69
0:MPT: #8  0x0000000002e6f44d in shr_mct_mod_mp_shr_mct_smatreaddnc_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/share/util/shr_mct_mod.F90:513
0:MPT: #9  0x0000000002e7459a in shr_mct_mod_mp_shr_mct_smatpinitnc_mapfile_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/share/util/shr_mct_mod.F90:349
0:MPT: #10 0x00000000004e38b0 in seq_map_mod_mp_seq_map_init_rcfile_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/drivers/mct/main/seq_map_mod.F90:143
0:MPT: #11 0x00000000004664be in prep_ice_mod_mp_prep_ice_init_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/drivers/mct/main/prep_ice_mod.F90:181
0:MPT: #12 0x00000000004264ad in cime_comp_mod_mp_cime_init_ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/drivers/mct/main/cime_comp_mod.F90:1839
0:MPT: #13 0x000000000042dc9e in MAIN__ ()
0:MPT:     at /gpfs/u/home/fischer/code/acmesplit/cime/src/drivers/mct/main/cime_driver.F90:122
0:MPT: #14 0x000000000040cee2 in main ()
```

It looks to me like the problem is: @matthewhoffman and @jonbob added a seq_infodata flag to turn off `glcshelf_c2_ocn` (`ocn_c2_glcshelf`), but I don't see a similar flag that turns off `glcshelf_c2_ice`, so the latter is always true for particular compsets, based on this logic:

https://github.com/ESMCI/cime/blob/5c43a153e946096ae0cb7ac14345e64f783b0231/src/drivers/mct/main/cime_comp_mod.F90#L1618

I'm thinking there should be a new `ice_c2_glcshelf` seq_infodata flag.

Incidentally, should `glcocn_present` on that line be `glcice_present`?

@matthewhoffman and @jonbob - do you agree with this diagnosis? If so, can one of you please add the necessary flag?

I'm labeling this as critical because it's causing failures in some of our prealpha tests. It would be great if we can have a fix for this within the next week or so, if possible.

**Comment by jonbob** [comment]
I'll talk to @matthewhoffman and we'll work on a solution asap

**Comment by rljacob** [comment]
When you have it, make a PR directly to ESMCI.
