### ISSUE TITLE
Add rollover of surface fluxes (cdn) at high wind speed

### ISSUE THREAD

**Issue by vlarson** [ESMCI/cime#3149]
The current calculation of the neutral drag coefficient at 10 m (cdn) in [subroutine shr_flux_atmOcn](https://github.com/ESMCI/cime/blob/5c379f87c2c83273273be23e6550fc4c3be00686/src/share/util/shr_flux_mod.F90#L248) and [subroutine shr_flux_atmOcn_diurnal](https://github.com/ESMCI/cime/blob/5c379f87c2c83273273be23e6550fc4c3be00686/src/share/util/shr_flux_mod.F90#L677) does not include a moderating effect at wind speeds greater than 30 m/s.  This rollover effect can be incorporated using equation (11a,b) of Large and Yeager (2009, Climate Dynamics).

**Comment by billsacks** [comment]
@vlarson @mvertens now that shr_flux_mod has been moved out of cime: if this is still needed, can you please open an issue in https://github.com/escomp/cesm_share  (or https://github.com/escomp/cmeps - where @mvertens intends to move the module based on discussion today).

**Comment by vlarson** [comment]
@zarzycki, does the "rollover" effect described above need to be added to CESM?  I don't know whether it is worth including.

**Comment by jedwards4b** [comment]
I don't see an issue in cmeps - is this still needed?

**Comment by zarzycki** [comment]
I do not believe the code has been edited in CMEPS: https://github.com/ESCOMP/CMEPS/blob/98dcf46c8886104b95cddfd5b02588b3dd9f6722/cesm/flux_atmocn/shr_flux_mod.F90#L262C1-L262C72

I still think it would be a worthwhile update myself. It should collapse to the current implementation at wind speeds typically seen in CESM but taper the drag coefficient at high wind speeds occasionally seen in ne120 and finer.

**Comment by jedwards4b** [comment]
So the question was - have you opened an issue in cmeps?

**Comment by zarzycki** [comment]
> So the question was - have you opened an issue in cmeps?

Done.
