### ISSUE TITLE
walltime in workflows doesn't work with lsf

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3151]
The walltime argument in config_workflow.xml needs to conform to the walltime_format in config_batch.xml

**Comment by rljacob** [comment]
Is this because lsf requires "HH:MM:  and doesn't like "HH:MM:SS"?

**Comment by jedwards4b** [comment]
yes

**Comment by rljacob** [comment]
We had the same issue in the python-based testing.  In tests.py, there's a way to specify the max time for a suite:
```
    "e3sm_land_developer" : { 
        "time"  : "0:45:00",
        "tests" : ( 
```

Try to run that suite with an lsf queue and you get errors.   Attn:  @jgfouca

**Comment by rljacob** [comment]
If you give slurm " 01:00"  will it call that 1 hour or 1 minute?

**Comment by jedwards4b** [comment]
It seems to be system dependent and we have a field in config_batch.xml to deal with it but that field is not being used in this case. We should make sure that the walltime_format field is used consistantly https://github.com/ESMCI/cime/blob/master/config/cesm/machines/config_batch.xml#L64

**Comment by rljacob** [comment]
So the convention in CIME config files should be to use HH:MM:SS and the library can use walltime_format to fit that string to what the queue wants?

**Comment by jedwards4b** [comment]
yes

**Comment by jgfouca** [comment]
Fixed in E3SM. Will arrive in the next split.

**Comment by jgfouca** [comment]
https://github.com/E3SM-Project/E3SM/pull/3446

**Comment by jgfouca** [comment]
This was fixed by a CIME split a while ago.
