### ISSUE TITLE
Adding user_datm.streams.txt.* files erases the stream files from CASEROOT/Buildconf/datm.input_data_list after build

### ISSUE THREAD

**Issue by femoyano** [ESMCI/cime#3155]
To me this seams the same or very similar to issue #916. This occurs in cesm release 2.1.1, so I created a new issue.
Briefly, when adding user_datm.stream files under CaseRoot/, those streams are erased from the Buildconf/ after build, and not replaced. Checking/downloading input data then does not work.

Steps to reproduce:
```
cd $CESMDIR
git clone https://github.com/ESCOMP/cesm.git cesm-test
cd cesm-test
git checkout release-cesm2.1.1
./manage_externals/checkout_externals
./cime/scripts/create_newcase --case "$CESMDIR"/cases/test1 --res f09_g17 --compset IHistClm50Sp --run-unsupported
cd "$CESMDIR"/cases/test1
./case.setup
./preview_namelists
cp CaseDocs/datm.streams.txt.CLMGSWP3v1.* ./
rename datm user_datm datm.stream*
./case.build
cat Buildconf/datm.input_data_list # all datm streams are missing
```

**Comment by jedwards4b** [comment]
@mvertens can we discuss this issue when you have time?

**Comment by mvertens** [comment]
After a conversation between @mvertens and @jedwards4b - the following has been suggested:
- created a temporary xml file in memory that is a copy of the user stream file - but that has the right header and footer to be recognized as xml. Then this could be parsed to generated the inputdata list.
In fact - this approach could be used for all of the stream data files - not just the user stream files.
