### ISSUE TITLE
Allow building with different location of PIO source

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3158]
We are going to have a version of PIO in E3SM/externals.   CIME needs to be flexible enough to allow that, or maybe a completely different I/O library, to be built instead of what is in cime/src/externals/pio1,2.  Setting could be done in `cime/config/$model`.

**Comment by jedwards4b** [comment]
Assuming e3sm/externals a location different than cime/src/externals?   CIME already allows for an external PIO build and will not build internally if an environment variable PIO_VERSION_MAJOR is set to a value the same as internal variable PIO_VERSION and PIO_TYPENAME_VALID_VALUES is set to a list of valid pio_typenames such as: 'netcdf','pnetcdf','netcdf4c','netcdf4p' .

**Comment by rljacob** [comment]
Yes a different location   We still want to build internally but with a different PIO source code location.

**Comment by jedwards4b** [comment]
In that case you would just pass a different source PIO_SRC_DIR is defined in scripts/Tools/Makefile as
$(CIMEROOT)/src/externals/pio$PIO_VERSION 
you should be able to override this location with an argument to gmake.

**Comment by rljacob** [comment]
Ok and we could put an ifeq ($(CIME_MODEL),e3sm) around that.   That gets us started.
