### ISSUE TITLE
Cannot create a case using "--driver nuopc" after cf10e65

### ISSUE THREAD

**Issue by gustavo-marques** [ESMCI/cime#3180]
This happens after cf10e651746b8a8a12fa2ea65e5077eea9a49256. When creating a case (./create_newcase --case c.c2b6.CNYF.T62_t061.nuopc --compset CMOM --res T62_t061 --run-unsupported --driver nuopc), I get the following error:

`ERROR: Looks like job groups have already been created
`
If I remove --driver nuopc it works fine.

**Comment by mvertens** [comment]
This just happened. I ran into the same problem. There is  PR that Jim put
out for this today - but it has not been accepted yet.
A work around is simply to use the branch origin/update_for_cime_9eda5dd -
and we will get the PR accepted first thing next week.

**Comment by gustavo-marques** [comment]
Thanks!

**Comment by mvertens** [comment]
The branch is in cmeps - not in cime.

**Comment by jedwards4b** [comment]
@mvertens @gustavo-marques should this issue be closed?

**Comment by gustavo-marques** [comment]
Yes.
