### ISSUE TITLE
Fatal error in PMPI_Group_range_incl: Invalid argument, error stack

### ISSUE THREAD

**Issue by skapilvfaculty** [ESMCI/cime#3188]
Getting Following Error while running cesm2.1.1 case
curl-7.65.3  
netcdf-fortran-4.4.5
pnetcdf-1.11.2 
zlib-1.2.11
hdf5-1.10.5 
netcdf-c-4.7.0 
pio-2.4.3 
 szip-2.1.1
Compiler : Intel 2015
Used with default intel compiler setting & mpiicc mpiifort mpiicpc

#######################################################################
Invalid PIO rearranger comm max pend req (comp2io),            0
 Resetting PIO rearranger comm max pend req (comp2io) to           64
 PIO rearranger options:
   comm type     =
 p2p

   comm fcd      =
 2denable

   max pend req (comp2io)  =           0
   enable_hs (comp2io)     = T
   enable_isend (comp2io)  = F
   max pend req (io2comp)  =          64
   enable_hs (io2comp)    = F
   enable_isend (io2comp)  = T
(seq_comm_setcomm)  init ID (  1 GLOBAL          ) pelist   =     0     4     1 ( npes =     5) ( nthreads =  1)( suffix =)
Fatal error in PMPI_Group_range_incl: Invalid argument, error stack:
PMPI_Group_range_incl(213)........: MPI_Group_range_incl(group=0x88000001, n=1, ranges=0x65fde20, new_group=0x7ffdee1f5ad8) failed
MPIR_Group_check_valid_ranges(326): The 0th element of a range array ends at 119 but must be nonnegative and less than 5
Fatal error in PMPI_Group_range_incl: Invalid argument, error stack:
PMPI_Group_range_incl(213)........: MPI_Group_range_incl(group=0x88000001, n=1, ranges=0x65fde20, new_group=0x7fffde558458) failed
MPIR_Group_check_valid_ranges(326): The 0th element of a range array ends at 119 but must be nonnegative and less than 5
Fatal error in PMPI_Group_range_incl: Invalid argument, error stack:
PMPI_Group_range_incl(213)........: MPI_Group_range_incl(group=0x88000001, n=1, ranges=0x65fde20, new_group=0x7ffcd6d46058) failed
MPIR_Group_check_valid_ranges(326): The 0th element of a range array ends at 119 but must be nonnegative and less than 5
Fatal error in PMPI_Group_range_incl: Invalid argument, error stack:
PMPI_Group_range_incl(213)........: MPI_Group_range_incl(group=0x88000001, n=1, ranges=0x65fde20, new_group=0x7ffe05d0cfd8) failed
MPIR_Group_check_valid_ranges(326): The 0th element of a range array ends at 119 but must be nonnegative and less than 5

**Comment by jedwards4b** [comment]
this error usually indicates that you are starting the job on a different number of tasks than are expected by the model.   It looks like the total number of pes is 5.  Please provide information to reproduce the problem.

**Comment by jedwards4b** [comment]
No response - closing issue.
