### ISSUE TITLE
Need to create software_environment.txt after cime.setup

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#319]
The file "software_environment.txt" lists all the modules loaded when building a CIME model.

The file was created by a command in the old cime2 env_mach_specifc.machine file such as:
"module list >& software_environment.txt"

Example on edison from ACME's CIME2 and an X-case.

edison09 scripts/tryXtiming> more software_environment.txt 
Currently Loaded Modulefiles:
  1) modules/3.2.10.4
  2) nsg/1.2.0
  3) eswrap/1.1.0-1.020200.1130.0
  4) switch/1.0-1.0502.57058.1.58.ari
  5) cray-shmem/7.4.1
  6) slurm/edison
  7) altd/2.0
  8) darshan/2.3.1
  9) craype-network-aries
 10) craype-ivybridge
 11) craype/2.5.0
 12) intel/15.0.1.133
 13) cray-libsci/16.07.1
 14) udreg/2.3.2-1.0502.9889.2.20.ari
 15) ugni/6.0-1.0502.10245.9.9.ari
 16) pmi/5.0.10-1.0000.11050.0.0.ari
 17) dmapp/7.0.1-1.0502.10246.8.47.ari
 18) gni-headers/4.0-1.0502.10317.9.2.ari
 19) xpmem/0.1-2.0502.57015.1.15.ari
 20) dvs/2.5_0.9.0-1.0502.1958.2.55.ari
 21) alps/5.2.3-2.0502.9295.14.14.ari
 22) rca/1.0.0-2.0502.57212.2.56.ari
 23) atp/2.0.2
 24) PrgEnv-intel/5.2.56
 25) cray-mpich/7.3.0
 26) papi/5.4.1.3
 27) cray-hdf5-parallel/1.8.14
 28) cray-netcdf-hdf5parallel/4.3.3.1
 29) cray-parallel-netcdf/1.6.1
 30) cmake/2.8.11.2
 31) cray-petsc/3.5.3.0

**Comment by worleyph** [comment]
Note that at the ALCF we use

printenv >& software_environment.txt

At NERSC @ndkeen has found that capturing both the module list and printenv is useful.

**Comment by jgfouca** [comment]
Yeah, i'll make it so it always does both.

**Comment by rljacob** [comment]
@worleyph remind me:  is that file made all the time or only when SAVE_TIMING is true?

**Comment by worleyph** [comment]
@rljacob, the generation of software_environment.txt is platform specific, via env_mach_specific.XXX. For the platforms where it is generated at all, it is always generated. When SAVE_TIMING is true, it is then copied to the performance_archive (by the cesm_postbuild script). Otherwise it only exists in the case directory, and is overwritten every time env_mach_specific is executed. The copy put into the performance archive is the one generated during the build, not the job submission or the run.

**Comment by rljacob** [comment]
So from greping ACME's env_mach_specific files, we only need to generate this file for cori, edison, cetus, mira and titan.

**Comment by jgfouca** [comment]
Shouldn't we just do it always?

**Comment by ndkeen** [comment]
I just want to quickly add that I'd like to see software_environment.txt include not only the currently loaded modules, but also the output of `env`.  I do this now in env_mach_specific.corip1

**Comment by jgfouca** [comment]
Yes, i'm setting it up to always do both.
