### ISSUE TITLE
Should we add cheyenne settings to help prevent mpt timeout issues?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3192]
MPT timeout issues have been frequent on cheyenne for the last few weeks. The CISL daily bulletin recommends:

> Until the issues are resolved, CISL suggests setting the following two environment variables to help jobs better tolerate the network issues. Users who have added these two settings have reported a significant reduction in the number of job failures due to the MPT errors.
> 
> MPI_IB_CONGESTED=1
> MPI_LAUNCH_TIMEOUT=40
> 
> Also, setting environment variables MPI_VERBOSE=1 and MPI_VERBOSE2=1 will generate more informative diagnostics that may help CISL’s system administrators identify the root cause of the problem. Users should note that setting these two environment variables will produce and add a significant amount of output to their jobs.

@sherimickelson 's earlier email suggested `MPI_IB_CONGEST` rather than `MPI_IB_CONGESTED`; I'm not sure which is correct. (It looks like maybe CISL was originally suggesting `MPI_IB_CONGEST`, then later changed it to `MPI_IB_CONGESTED`?)

I'm reluctant to make this change myself, since I don't understand the possible implications, but wanted to raise this as an issue for discussion, for those who hopefully understand this better than I do (@jedwards4b I'm looking at you).

**Comment by sherimickelson** [comment]
In talking with Mick, I would hold off on this.  I'm not sure if they are
still recommending people try this.

**Comment by billsacks** [comment]
Thanks; I'll close this then.
