### ISSUE TITLE
Run loop feature in cime run script

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#3209]
This is a request for a feature in the cime run script.  We would like to have the ability to carry out multiple sequential runs from a single job submission.  This is currently handled by the RESUBMIT flag, but that forces the job to exit and be resubmitted to the queue.   We have access to machines with long queues (168 hours) and long queue wait times (days).   Our productivity goes way down if we have to wait in the queue before every run.  

We implemented this in the CESM1 scripts quite easily, but feel that taking on this task with the cime scripts would be a large effort (due to their complexity), so are asking for help.  We are large users focused on Arctic simulations with the E3SM model.

The way we implemented this in CESM1 scripts was as follows.  I can convert this to requirements if you prefer.
 - we created a loop in the run script at the highest level and included all aspects of job setup, run, archiving, generating timing output, etc.  It included all of the run script.
 - the loop was driven by 1 parameter (call runmax) defined at the top of the run script that we could manually change before submission.  It was by default 1 (which meant 1 loop was executed per submission, not changing the basic implementation).  Since the cime scripts don't generated "resolved" files, this parameter will almost certainly have to be defined in an xml file (or similar) in cime.
 - when in the run loop, the RESUBMIT flag is not decremented as the job loops internally.  But the RESUBMIT flag still handles multiple job submissions.  So the implementation supported multiple automatic submissions consisting of multiple runs per submission.  
 - the run loop stops if the prior run did not complete successfully.
 - we included the ability to force an exit of the loop gracefully.  at the end of each loop, the RESUBMIT flag is checked.  If it is < 0, then the run loop ends.  Normally, RESUBMIT will only be >= 0 and it does not decrement if it is 0.  So RESUBMIT of <0 provided a graceful escape from the loop if the job needed to be stopped.  (Of course, we could also kill the job, but that is often not ideal).

This implementation required 10-20 lines of code be added to the CESM1 run script, it was easy.  Again, I'm not sure how to do it in cime scripts.  I'm willing to try to get this working if I get some direction about how to implement it.

To help justify the feature, let me answer your questions
 - why don't you just run a single job of 168 hours?  why do you need multiple runs in a single job?
   - 168 hours is a long run and lots of things can happen during that time that could compromise the long run.  we feel it's better to pay a small cost to stop and restart the run at some regular intervals (say 12-24 hours)  than to try to run a full 168 hours as a single run.  this is largely for risk mitigation.
   - we may want to exit gracefully at regular intervals 
     - to invoke archiving
     - to get clean restart sets
     - to get timing information
     - to be able to stop the model gracefully as we analyze data coming out of the model.
   - we were running with the wrf model as our atm component, and it is unable to read multiple (in time) boundary condition files.  these files contain 3 hourly (or so) data and are defined over a month or a year at this time.  to advance the model, we must resubmit and stage the new boundary condition files as we hit the temporal "edges" of the bc files.  this is a short-coming in the wrf implementation, but is probably not unique to wrf.  these files are also large, so creating files of multiple years is somewhat impractical and also slows down the model IO.  it is not a burden to deal with this shortcoming, especially if we can run multiple runs in a single job.
 - what about the "save interim restart files" feature?
   - this only addresses one issue and not in a complete way.  it does not save full restart sets in the standard way, so is less useful to us.  
 - why don't you just submit multiple shorter jobs?
   - it goes without saying, but if the queue waits are long, this will significantly reduce productivity.  If you wait 3 days between submissions in the queue, a 168 hour run with looping every 24 hours will provide about 3x more throughput than single submissions each lasting 24 hours.  As the actual length per run decreases, the difference in productivity increases.

I think this enhancement could benefit lots of users.  You can increase your actual throughput anytime you are running production, you have queue wait times, but you aren't take advantage of the queue time limit due to technical or risk management reasons.

**Comment by gold2718** [comment]
I am probably missing something but is this something that can be handled with the `DATA_ASSIMILATION_SCRIPT` and `DATA_ASSIMILATION_CYCLES` run variables? This allows you to run any arbitrary script between runs for a set number of cycles.

**Comment by apcraig** [comment]
Possibly, I'm not familiar with the data assimilation capabilities, usage, or implementation.

From the user perspective, maybe the run script could always be run in data assimilation mode with the default cycles defined to 1, but also understanding that could be increased.  that seems like it could work.  I don't know how that will impact actual data assimilation runs though where I assume there is another script doing something between runs.  If the data assimilation mode because something more general, it would be good to redefine the feature as "run looping" or something with data assimilation being one thing that it handles.  In standard mode, maybe it just loops over the run script.  Then I guess there would be other modes where other scripts could/would be invoked between runs.  That makes sense to me.

**Comment by gold2718** [comment]
There is nothing data-assimilation specific about the use of these keywords. I think a better name would be run_cycle_script and run_cycle_cycles. It simply runs the model `DATA_ASSIMILATION_CYCLES` times and calls the script each time. The script takes 4 arguments: the case root directory, the cycle number (zero based), the `lid`, and the case run directory.

Unless the script calls a data assimilation program or sets post data assimilation model flags, nothing related to data assimilation is done.

**Comment by jedwards4b** [comment]
Can this issue be closed?

**Comment by jedwards4b** [comment]
I think that you can do a full 168 hr run and right intermediate restart files along the way - I don't think that your reasoning to stop and restart is justified.
