### ISSUE TITLE
Allow histaux_l2x1yrg with a stub glc model

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3218]
A number of people are running into problems because you currently cannot turn on histaux_l2x1yrg (which is needed to write the cpl hist files needed for a later T compset) when running with a stub glc model (SGLC). The latest person to request this ability is Bette Otto-Bliesner.

If I remember correctly, the reason you cannot do this is because the writing of histaux_l2x1yrg depends on the coupler's accumulating and averaging of the l2x fields that are destined for glc. Current logic in the driver only does these accumulations and averages if we're running with a prognostic glc model. But, off-hand, it seems like it should be possible to do these accumulations and averages even if we're running with a stub glc model.

My tentative plan is to *not* change the standard behavior (in part because I plan to do this on the maint-5.6 branch, and I want to be conservative about changes made there), but to introduce a new namelist flag that will change the driver behavior slightly. If this namelist flag is set, then the relevant accum and accum_avg calls will be made regardless of whether glc_present and/or glc_prognostic are true. This, in turn, should allow us to write histaux_l2x1yrg files even when running with SGLC.

If Bette confirms this is a high priority for her runs, then I'll give this a shot in the next couple of weeks. I'll probably do it both on maint-5.6 and master. (Note that I think the relevant code has changed a lot between the two, so I'll need to separately implement this in the two places.)

cc @Katetc @whlipscomb @mvertens

**Comment by billsacks** [comment]
@mvertens gave her blessing for this change.

In talking with her, I realized that we probably shouldn't bother with a separate namelist variable. Instead make the logic key off of the existing `histaux_l2x1yrg` variable. I'll just need to take some care to ensure that the relevant calls are only done once (rather than being done once for the sake of `glc_prognostic` and then a second time for the sake of `histaux_l2x1yrg`). So, for example, have logic like `if (histaux_l2x1yrg .and. .not. (glc_prognostic and/or ...) then call ...`

**Comment by whlipscomb** [comment]
@billsacks, I think this is an excellent idea.  Thank you for working out the details.

**Comment by billsacks** [comment]
I fixed this a while ago: #3356 and #3358
