### ISSUE TITLE
gnu tests are failing to run cprnc in it's environment

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3224]
I first saw this in the CLM branch tag branch_tags/cime5.8.3_chint17-04, but also verified it's a problem in cime master (cime5.8.9-2-g8bffca6d3). This test fails the COMPARE step, because cprnc can't run in the gnu environment.

> scripts/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u> cat TestStatus
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default CREATE_NEWCASE
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default XML
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default SETUP
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default SHAREDLIB_BUILD time=113
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default MODEL_BUILD time=144
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default SUBMIT
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default RUN time=94
> FAIL ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default COMPARE_base_rest
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default MEMLEAK
> PASS ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default SHORT_TERM_ARCHIVER

cprnc fails to run in the gnu environment that's setup for it. It has trouble finding a intel shared library, in the gnu environment.

Here's an example of the attempts at running cprnc for this case.

> scripts/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u>     cat /glade/scratch/erik/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u/run/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u.clm2.h0.2000-01-06-00000.nc.base.cprnc.out
> /glade/p/cesmdata/cseg/tools/cime/tools/cprnc/cprnc.cheyenne: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
> scripts/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u>     cat /glade/scratch/erik/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u/run/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u.clm2.h1.2000-01-06-00000.nc.base.cprnc.out
> /glade/p/cesmdata/cseg/tools/cime/tools/cprnc/cprnc.cheyenne: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
> scripts/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u>     cat /glade/scratch/erik/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u/run/ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default.20190901_130937_iwft5u.cpl.hi.2000-01-06-00000.nc.base.cprnc.out
> /glade/p/cesmdata/cseg/tools/cime/tools/cprnc/cprnc.cheyenne: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

Since, cprnc was compiled and linked with intel, you need to have access to the intel shared libraries at run time, but in the gnu module environment those aren't loaded.

It looks like to me that all gnu tests are failing, but only this one actually records it as a problem.

Here's the .env_mach_specific.csh that it creates...

``` csh
# This file is for user convenience only and is not used by the model
# Changes to this file will be ignored and overwritten
# Changes to the environment should be made in env_mach_specific.xml
# Run ./case.setup --reset to regenerate this file
source /glade/u/apps/ch/opt/lmod/7.5.3/lmod/lmod/init/csh
module purge 
module load ncarenv/1.2 gnu/7.3.0 openblas/0.2.20 openmpi/3.0.1 netcdf/4.6.1 ncarcompilers/0.5.0
setenv OMP_STACKSIZE 256M
setenv TMPDIR /glade/scratch/erik
setenv MPI_TYPE_DEPTH 16
setenv MPI_IB_CONGESTED 1
setenv MPI_USE_ARRAY None
setenv TMPDIR /glade/scratch/erik
setenv MPI_USE_ARRAY
```

when you source this environment you can't run cprnc built on the machine.

The CTSM issue I created for this is here:

https://github.com/ESCOMP/ctsm/issues/798

**Comment by jedwards4b** [comment]
If you build cprnc using the gnu compiler it will work with the intel and pgi environments as well as the gnu environment.   cprnc was reinstalled on cheyenne.
