### ISSUE TITLE
Stand-alone CMake Build

### ISSUE THREAD

**Issue by jhamman** [ESMCI/cime#3226]
We (@negin513, @billsacks, @mvertens, and I) are working on the LILAC project (https://github.com/NCAR/lilac). We are at the stage where we're working on the build infrastructure connecting LILAC to CTSM. What we'd like to be able to do is use CMake to build CIME as a stand alone library. Something close to this would be an ideal function set:

```shell
git clone https://github.com/ESMCI/cime.git
cd cime
cmake .
```

Although CIME includes a top level `CMakeLists.txt`, it does not seem like it is intended to support this type of build workflow. For example, the example above yields the following error.

```
CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CIME_initial_setup
...
```

I imagine there are reasons this isn't currently possible so I'm looking for a) some explanation of those and b) thoughts from those familiar with the CTSM build system (@jedwards4b, @billsacks) on how the desired functionality could be achieved.

Note, I've also raised a similar issue with CTSM (https://github.com/ESCOMP/ctsm/issues/799).

**Comment by billsacks** [comment]
I'm going to mostly put my thoughts in ESCOMP/ctsm#799. But one thought specific to cime: I don't think it makes sense to think about a standalone build of cime outside of a case: It's unclear which parts of cime this build should include. This might make sense for individual pieces of cime, such as `src/share` (or maybe just individual pieces of that???).

**Comment by billsacks** [comment]
I don't think that we'll go this direction of a standalone cime build for lilac, at least for now. (Instead, we'll coordinate the cime build from a build system that resides in ctsm.) This may still be something we want to revisit in the future for the sake of maintainability, but I'm going to close this issue for now.
