### ISSUE TITLE
different behavior for JOB_WALLCLOCK_TIME on cheyenne?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#3235]
I think this is a variant of #3163 that #3164 didn't address. On cheyenne, you used to be able to run

```
$ ./xmlchange JOB_WALLCLOCK_TIME=HH:MM
```

but now (as of early July, I suppose), `cheyenne` interprets that as `MM:SS`. From a user perspective, it would be nice to not have to retrain myself to add the extra `:00` and instead have CIME define a standard for this variable (e.g. `DD:HH:MM` with `DD` assumed to be 0 if omitted) and then translate it to the appropriate format via something in `config_machines.xml`. This will also make some scripts more portable from machine to machine and make it easier for users to move from one machine to another.

**Comment by jedwards4b** [comment]
See variable walltime_format
https://github.com/ESMCI/cime/blob/master/config/cesm/machines/config_batch.xml#L64
