### ISSUE TITLE
running tasks in workflow individually

### ISSUE THREAD

**Issue by uturuncoglu** [ESMCI/cime#3250]
The initial implementation of the FV3GFS workflow, that includes chgres, standalone FV3GFS run and gfs.post has been implemented with the current version of the CIME workflow and the prototype version is documented in [here](https://github.com/ESCOMP/UFSCOMP/wiki/UFS-Global-Weather-Workflow) but there is a need to run individual pieces/tasks of workflow separately such as running only chgres.

**Comment by jedwards4b** [comment]
case.status currently has a --job option that specifies that this will be the first job submitted in a workflow, it needs an additional (--job-only)? option that specifies that only this job will be run.
