### ISSUE TITLE
cime5.6.24 PATH setting is missing running with pgi on izumi

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3262]
Simple change to allow izumi/pgi to run with cime5.6.24. I added the following line in env_mach_specific.xml and it would run.

` xml
<env name="PATH">$ENV{PATH}:/cluster/torque/bin</env>
`
This allows the compute nodes to issue a queue submit.

By, the way I changed the original documentation of this issue to split this into two issue. #3302 is now separated from this one.

**Comment by billsacks** [comment]
@ekluzek I'm confused by this. I added the line you mention in #3221 , but only on cime master, not the maint-5.6 branch. I have been running with that change and pgi tests have been passing for me. I just checked config_machines.xml in cime5.6.24 and confirmed that the line you reference is _not_ present there.

Can you confirm that your setup is what you expect it to be, and then provide instructions for reproducing this error?

**Comment by ekluzek** [comment]
Thanks @billsacks. You must be right, and I messed up when I looked at the diffs. I probably saw them them backwards. Originally when filling this out, I put it that way and then convinced myself that I was wrong. So I'll recheck. What I did was to copy the env_mach_specific.xml from a CTSM master case, to get it to work.

**Comment by ekluzek** [comment]
OK, here's the diff needed...

``` xml
diff --git a/config/cesm/machines/config_machines.xml b/config/cesm/machines/config_machines.xml
index d3cb85677..71f33755d 100644
--- a/config/cesm/machines/config_machines.xml
+++ b/config/cesm/machines/config_machines.xml
@@ -1441,6 +1441,7 @@ This allows using a different mpirun command to launch unit tests
     </module_system>
     <environment_variables>
       <env name="OMP_STACKSIZE">64M</env>
+      <env name="PATH">$ENV{PATH}:/cluster/torque/bin</env>
     </environment_variables>
     <resource_limits>
       <resource name="RLIMIT_STACK">-1</resource>
```

**Comment by jedwards4b** [comment]
@ekluzek Why is this still open?  Please issue a PR or close the issue.

**Comment by ekluzek** [comment]
I have a branch with this change in place. But, it's no longer working for me. So I still get PGI to fail on the maint-5.6 branch of cime. I tried reversing the order of $ENV{PATH} in the diff above, but that doesn't work either. As far as I can tell this is the only thing missing to get izumi to work on maint-5.6 like it does on cime master.

Anyone, have any other ideas to try?

**Comment by ekluzek** [comment]
@jedwards4b pointed out there are problems when running on more than one node. The test case I'm running is SMS.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop. It works on CTSM master, but it's only using one node there, and on the CLM5.0 release branch it's using two nodes.

**Comment by ekluzek** [comment]
OK, when I run on a single node it passes. SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop.20191113_192006_7qnzi0

PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop CREATE_NEWCASE
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop XML
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop SETUP
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop SHAREDLIB_BUILD time=1107
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop MODEL_BUILD time=349
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop SUBMIT
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop RUN time=239
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop MEMLEAK
PASS SMS_P48x1.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop SHORT_TERM_ARCHIVER

**Comment by jedwards4b** [comment]
Note that this is a system issue on izumi and is not a cime issue.

**Comment by ekluzek** [comment]
@jedwards4b I think I should divide this issue into two. One issue is the system issue on izumi for running on more than one node. I can mark that as a known problem and close it. The other is the need for adding the PATH. So I can either close this one, and open two new ones. Or I can relabel this one as the izumi multi-node issue (because it has output for that problem that you'll be able to search for), and open a new one for the PATH issue.
