### ISSUE TITLE
--no-batch flag  not working.

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#3264]
The changes to the workflow, and env_batch.xml now being locked, is causing errors when testing with the --no-batch flag.  The AMWG is hoping to make this the default way of running the cam tests.

```
Output: found difference in BATCH_SYSTEM : case 'none' locked 'pbs'
found difference in BATCH_SYSTEM : case 'none' locked 'pbs'
ERROR: Batch configuration has changed, please run case.setup --reset`
```

**Comment by jedwards4b** [comment]
@fischer-ncar I've put a fix in branch  fix_batch_lock_issue on my fork https://github.com/jedwards4b/cime
I have tested it and it seems to solve the problem, but could you try with cam tests?  Thanks

**Comment by fischer-ncar** [comment]
@jedwards4b, your fix seems to be working for me.
