### ISSUE TITLE
Question: How to optimize PE layout for single-point runs

### ISSUE THREAD

**Issue by serbinsh** [ESMCI/cime#3269]
I am developing a range of single site run tests for ctsm using default forcing data extracted for a specific lat/long. I have already created the domain, surface, and datm files and I can run the single points fine.  However, I am struggling to optimize mpi/processor usage with job submissions on my cluster.  The issue I am having is that when I start more than one job, say site 1 and site 2, the jobs end up sharing the same CPU/core instead of running on another core on the same node.  

I have this in my setup script

```
./xmlchange NTASKS_ATM=1,ROOTPE_ATM=0,NTHRDS_ATM=1
./xmlchange NTASKS_CPL=1,ROOTPE_CPL=0,NTHRDS_CPL=1
./xmlchange NTASKS_LND=1,ROOTPE_LND=0,NTHRDS_LND=1
./xmlchange NTASKS_OCN=1,ROOTPE_OCN=0,NTHRDS_OCN=1
./xmlchange NTASKS_ICE=1,ROOTPE_ICE=0,NTHRDS_ICE=1
./xmlchange NTASKS_GLC=1,ROOTPE_GLC=0,NTHRDS_GLC=1
./xmlchange NTASKS_ROF=1,ROOTPE_ROF=0,NTHRDS_ROF=1
./xmlchange NTASKS_WAV=1,ROOTPE_WAV=0,NTHRDS_WAV=1
./xmlchange NTASKS_ESP=1,ROOTPE_ESP=0,NTHRDS_ESP=1
```

And have messed around a bit using options laid out in here: https://esmci.github.io/cime/users_guide/pes-threads.html#setting-the-pe-layout but whatever I try it seems the jobs only run on 1 core per node.

I have even tried this:

```
qsub -q batch -l walltime=36:00:00 -l select=1,nodes=node03:ppn=1 -v ARGS_FOR_SCRIPT='--resubmit' .case.run
```

I feel like this is either a case of doing it wrong, mis-understanding the options, or that its not feasible.  That said, I am pretty sure I have run tests that run on separate cores on the same node at the same time so I think I must just be messing up the layout or other options to tell job submission to stick to one core per site/case submission.  

Any insight would be appreciated.

**Comment by serbinsh** [comment]
I should say that for global/regional the submission works as expected when I ask for multiple nodes and cores, that is the parallelization scales as requested across nodes.  So I am really only struggling to understand how to define 1 cpu per site.  Currently if say I run 3 cases at the same time for different sites (different site cases) on the same node, they all end up sharing the sampe CPU and take up 33.333% of the CPU utilization

**Comment by jedwards4b** [comment]
@serbinsh instead of naming each individual component you can do the same thing with:
```
./xmlchange NTASKS=1,ROOTPE=0,NTHRDS=1
```
but also note that setting --mpilib mpi-serial in create_newcase does this as well.   
As far as running multiple jobs on the same node and getting them to use different cpus this depends on the queueing system and binding options available on a particular machine.  The default option in cesm is that only one job is allowed per node.
