### ISSUE TITLE
Warning about stop time polluting e3sm.log files (written by many ranks)

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#3270]
In cime/src/drivers/mct/shr/seq_timemgr_mod.F90, this warning is being triggered quite often and can really be annoying with many MPI ranks:

        if(CurrTime + TimeStep > minStopTime ) then
-          write(logunit,*) subname//" WARNING: Stop time too short, not all components will be advanced &
-                                    &and restarts won't be written"
        endif

I've been temporarily commenting the write and have not looked for the cause.

This happens with every repo I've used on cori/theta and with F compsets for sure.

Counting the number of these, it looks like it might be printed on every rank _except_ rank0.

**Comment by rljacob** [comment]
We have a lot of tests that run for only a handful of timesteps so we might see this more then cesm.

**Comment by ndkeen** [comment]
I think it's actually only written once per entire job. But with say 16384 ranks, that's enough to be annoying.

**Comment by jedwards4b** [comment]
You can change to:
       if(CurrTime + TimeStep > minStopTime .and. seq_comm_iamroot(CPLID)) then

**Comment by ndkeen** [comment]
I should have noted earlier that the above code to only write the warning in root0 does "solve" this issue. Should we make a PR? 

Also, it's not clear why the warning is happening at all.

**Comment by jedwards4b** [comment]
It's already there https://github.com/ESMCI/cime/blob/master/src/drivers/mct/shr/seq_timemgr_mod.F90#L1054
