### ISSUE TITLE
shr_file_setIO logic

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#3271]
With nuopc coming in, shr_file_setIO logic is currently problematic.  Either the nuopc.runconfig _modelio values should be migrated back to the *_modelio.nml file OR the shr_file_setIO should provide a way to be called and return gracefully if the modelio namelist does not exist.

As things are currently implemented, the component has to know whether the modelio stuff is set by nuopc in nuopc.runconfig in the cap or by _modelio.nml approach which is often called in the component itself.  It seems some components are having to awkwardly code around this issue.  

I recommend actually doing both.  Provide a way to call shr_file_setIO with an actual return code (maybe as an optional argument) instead of an internal abort.  That is useful in this case and possibly for other future needs.  And I think it also makes sense to move the _modelio stuff back into the .nml file.  The _modelio nml file still exists for the pio stuff.  So I don't understand why the old implementation was broken while retaining the  _modelio.nml files.

**Comment by jedwards4b** [comment]
shr_file_setIO is deprecated in the nuopc cap and should only be called from the mct cap.   
In the nuopc cap use 
```
    if (mastertask) then
       call NUOPC_CompAttributeGet(gcomp, name="diro", value=diro, rc=rc)
       if (chkerr(rc,__LINE__,u_FILE_u)) return
       call NUOPC_CompAttributeGet(gcomp, name="logfile", value=logfile, rc=rc)
       if (chkerr(rc,__LINE__,u_FILE_u)) return

       open(newunit=logunit,file=trim(diro)//"/"//trim(logfile))
    else
       logUnit = 6
    endif
```

**Comment by apcraig** [comment]
You cannot guarantee the shr_file_setIO is only called in component caps.  It isn't and that's the point.

**Comment by jedwards4b** [comment]
It should be - why would you ever need to call it from elsewhere?

**Comment by apcraig** [comment]
In most models, the stdout/err units and output files are set during the model initialization.  In other words, you either set the output file in the cap and then the model init overwrites it.  Or you do your model init first and then in the cap you change it.  But of course, you've initialized your model now and all your output has gone to a different output file than what you want.  This is all pretty typical.  Where in the model cap should it be called, before or after model initialization?

```
subroutine model_cap
  ...
  call model_init()
  ...
end subroutine model_cap

subroutine model_init

  nu_out = something

#ifdef CESMCOUPLED
  call shr_file_setIO(nu_out)
#endif 

! continue initialization

end subroutine model_init
```

**Comment by jedwards4b** [comment]
In general it's done in the  InitializeAdvertise phase.

**Comment by jedwards4b** [comment]
I'm not sure I understand what you are doing since this is already in the ice_comp_nuopc.F90 file that you started with.

**Comment by apcraig** [comment]
Maybe in the cime components, but that's not true in all components.  

This is a really simple modification that would benefit the community.  I don't understand why there is so much pushback.

**Comment by apcraig** [comment]
Why do you think ice_comp_nuopc is the only way CICE6 is coupled?  Look in CICE5, it has the same issue to deal with mct and nuopc.  CICE6 runs stand-alone, it runs with mct, and it's now trying to run with a nuopc cap.  It will run with other couplers as well.  nuopc is not the only option.  The fact that you see it that way is not reasonable.   I understand what ice_comp_nuopc.F90 is doing.  The problem is because it's in the cap there, we have to code around shr_file_setIO in the initialization method of the component to support other coupling capabilities.  Maybe we need to trigger off more cpps like MCT_COUPLED and NUOPC_COUPLED or something.  We could do that too, but none of this is ideal.

Again, I think what I'm proposing is not unreasonable.  Not my decision whether it gets implemented though.  At present, we have a very ugly kludge in the code to work around this problem.  I'd love to clean that up.

**Comment by apcraig** [comment]
I am going to close this.  I have added some new logic to deal with this issue more cleanly in the CICE6 model.   The existing implementation to work around this issue was a mess.  Cannot comment on what other models are doing though.

I'll add one more note.  The awkward and unusual thing about the NUOPC implementation is that stuff that is supposed to be dealt with in the model internally has been pushed to the cap.  Because the implementation is nuopc specific, it cannot be implemented in the component itself (without a CPP).  I think more care should be taken when separating cap/coupling settings and model settings.  Model stuff should not be handled in the cap.  Again, nuopc is doing this for the ice stdout file, it is creating issues with respect to other coupling paradigms, and it's the outlier and problem.

**Comment by jedwards4b** [comment]
as far as I know cice is the only component with this spaghetti logic around opening a log file.

**Comment by apcraig** [comment]
it's not spaghetti logic.  the implementation is actually clean, it's the fact that nuopc wants to define some model internals via nuopc interfaces.  And it's not that different from other models,

pop: source/io_types.F90 where a flag exists to avoid the call to shr_file_setIO and has near identical implementation as cice.

mom: achieves the log unit management by calling into multiple initialization routines FROM the cap and does the log unit setup in the middle of those.  This means each cap must reproduce the initialization sequence independently and when it changes, all caps have to be modified.  Not ideal at all!

mosart: updates the logging file unit in the cap in both mct and nuopc.  mosart doesn't have a standalone capability and this implementation has been driven by cesm.

clm: initializes the logging in Advertise and calls the clm intialization in Realize.  In mct, calls the log initialization near the start of the mct init routine.  This works because the default iulog (the clm log unit) is initialized when declared and because there is no stand-alone mode anymore, at least as far as I could see.

cam: same as clm, but it has a single file/module just to carry around the logunit.

Anyway, I think the point is that it's not as clean across components as you think.  Yes, some components are implemented as you suggest.  But it really depends how the init routine is implemented and handles thru the cap, how many coupling modes have to be supported, what the requirements are in different coupled systems, whether there is a stand-alone mode, and many other things.  It's important to recognize some of these components exist outside CESM.

**Comment by mvertens** [comment]
@apcraig - you are missing a key issue here. shr_file_setIO is **ONLY** called by the mct caps  **OTHER THAN CICE** for all CESM components. CICE actually places this call in ice_init - rather than in the mct cap. In the nuopc caps - shr_file_setIO is not called by **ANY** of the component caps - but rather the log file name is obtained via a config attribute. These values are now set in the nuopc.runconfig file - and not via the namelists used by mct. When @mvertens created the NUOPC caps - I did not want to interfere with the MCT logic - and so I put in the current logic so that only the nuopc code was introduced into my PR. The right thing to do is move the call of shr_file_setIO from ice_init to the MCT cap. This can be done as part of your PR or not. This discussion really does not belong as a CIME issue.

**Comment by apcraig** [comment]
@mvertens, that's not actually entirely correct.  And I also understand the current implementation quite well.  My point is that you could make it much easier for external components to integrate into CESM if you made a few minor changes.  I think you have a much too narrow view about how things should be done from a CESM perspective, and you seem to consistently discount this kind of feedback.  I have closed this issue and worked around it other ways because it became clear quickly there was no interest in thinking about the issue I raise let alone addressing it.
