### ISSUE TITLE
Extend streams mapping capability to add conservative mapping

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3275]
Right now the only option for regridding done from streams files is "mapalgo=bilinear" for bilinear mapping. There are some datasets for which a conservative mapping would be desired. So we'd like to see the mapping capability in share streams extended to at least a first order conservative one.

We think this capability would probably be best added with ESMF online regridding. In the short term it could be added with additional mapping files to read in, but this would bring some new complexity. Another way to do it would be to add a conservative regridding function, but this would take development effort. So it seems like this feature could be tied to having the ESMF online regridding. With that functionality in place, adding it as an option should be straightforward.

**Comment by billsacks** [comment]
@ekluzek @mvertens does the functionality requested above now exist in CDEPS's streams? If not, @ekluzek can you open an issue there if this is still wanted? Either way, can you close this once you're satisfied?

**Comment by ekluzek** [comment]
Moved to CDEPS issue.
