### ISSUE TITLE
bless_test_results failing with ref1 and ref2 directories

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#3278]
bless_test_results is processing the .ref1 and .ref2 directories that are produced by the ERI tests.

The TestStatus file in the .ref directories isn't completed by the ERI tests, so it looks like those tests
failed to run and aren't blessed.  

Another issue is the .ref directories might be the most recent time stamp, which is causing all of the other test to be skipped.

**Comment by jedwards4b** [comment]
Seems like this could be corrected by refining the glob here:
https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/bless_test_results.py#L63

**Comment by billsacks** [comment]
Does this same issue also affect the companion, compare_test_results?

**Comment by fischer-ncar** [comment]
@billsacks, compare_test_results reports that it skips the baseline compare for ref directories, as the test "did not make it to the run phase".  It still gives the right results for the final run of the ERI tests. So not a complete failure like bless_test_results, but something that would be good to address now.

**Comment by jedwards4b** [comment]
@fischer-ncar Try this - I removed the * after the test_id in test_id_glob, I think that will prevent including the .ref1 and .ref2 directories...
test_id_glob = "*{}".format(compiler) if test_id is None else "*{}".format(test_id)
    test_status_files = glob.glob("{}/{}/{}".format(test_root, test_id_glob, TEST_STATUS_FILENAME))

**Comment by billsacks** [comment]
I agree with @jedwards4b 's change for the test_id case (i.e., the `else` piece), but I'm not sure if the first part (`"*{}".format(compiler)`) will work correctly: I think that would only pick up directories that end with the compiler name, which won't typically be the case.

And @jgfouca should weigh in on even the change for the test_id case: I see that he just changed `compare_test_results` to use this extra globbing (in d44027bb8 - merged in #3272); he had earlier changed `bless_test_results` to have his extra globbing in 8c4477746b. @jgfouca can you explain why you wanted that extra `*` at the end of the glob?

It seems like another – more invasive but maybe more robust long-term – fix would be to change ERI (and any other test type that creates these ref directories) to nest its ref directories inside the main case directory, as we do for `system_test_compare_two`. I'd argue that's worth doing at some point, but might be overkill to fix this issue.

**Comment by jedwards4b** [comment]
@fischer-ncar Try /home/jedwards/cesm2_x_alpha/cime/scripts/Tools on izumi

**Comment by fischer-ncar** [comment]
@jedwards4b That works.  We just need to avoid having ref10 or higher directories.  Which I don't see as
a problem.

**Comment by jgfouca** [comment]
@billsacks , @fischer-ncar , @jedwards4b,

In our scripts/Jenkins jobs, we have established a pattern of blessing based on a generic pattern (e.g. 
 JNextIntegration ) instead of the exact test-id (e.g. JNextIntegration_2019_10_27_ads34). This makes life easier for the blesser since they don't have to look up the exact test-id. If you look at bless_test_results, you can see we do some work to ensure to most recent test-run computed from the generic test-id.

**Comment by jedwards4b** [comment]
@jgfouca But then don't you have the .ref1 .ref2 issue too?

**Comment by jgfouca** [comment]
@jedwards4b , we haven't hit it yet. But I can update the glob/regex matching to ignore .ref directories.

**Comment by jedwards4b** [comment]
I'm working on it, hang on.
