### ISSUE TITLE
scripts_regression_tests.py test_rebless_namelist needs cleanup

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3279]
When I run this test:
./scripts_regression_tests.py Q_TestBlessTestResults.test_rebless_namelist

I get a lot of files and directories created outside of the TEST_ROOT which are not subsequently cleaned up.  

```
 cs.status.20191030_102615_xdg75d
 cs.status.20191030_102618_z7fg77
 cs.status.20191030_102622_k1litw
 cs.submit.20191030_102615_xdg75d
 cs.submit.20191030_102618_z7fg77
 cs.submit.20191030_102622_k1litw
 testreporter
 TESTRUNPASS_P1.f19_g16_rx1.A.centos7-linux_gnu.G.20191030_102622_k1litw
 TESTRUNPASS_P1.f45_g37_rx1.A.centos7-linux_gnu.G.20191030_102618_z7fg77
 TESTRUNPASS_P1.ne30_g16_rx1.A.centos7-linux_gnu.G.20191030_102615_xdg75d
```

**Comment by billsacks** [comment]
@jedwards4b I see you assigned me, but I don't think this is something I'm familiar with (unless I'm forgetting some involvement I've had with this).

**Comment by jedwards4b** [comment]
I'll remove you - I think that this is an e3sm issue.

**Comment by jedwards4b** [comment]
@jgfouca I took another look at this one in the context of #3282 but I really don't see how those files are created or how to get them created under the correct test-root.  Can you please do this one?

**Comment by jgfouca** [comment]
Yes, I'll take a look at this as soon as I can.
