### ISSUE TITLE
Problems with streams for at least 3D grids and some options

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3281]
I'm finding problems on maint-5.6 for streams at least for 3D grids. This is for a case with soil moisture streams in CTSM, for a short three day simulation starting on Jan/1st. When tintalgo="nearest" is used, it should match the input file for the time index nearest to the simulation time (would be index 0). I'm finding it doesn't match that (at least for every point), and actually changes in time when it shouldn't (the output for each day differs from each other). "upper" seems to work correctly though (each day is identical and they all match index 0 in the input file). "lower" is matching an index one less than what it should (so it's matching index 10 when it should match index 11). Note, I'm using "C" type indexing starting at 0. But, lower is also constant in time like it should be, so that's also good.

Using nearest I did also show that a change in number of processors doesn't change the results, so that's good.

There's also a 2D LAI stream in my test case, and I haven't done as much checking with it, but in the checking that I did do with it, I didn't see these same problems. So I think this might just be with the 3D grid. Note, the option to use the 3D grid, doesn't allow grid interpolation, the model grid and the input grid have to be identical.

**Comment by ekluzek** [comment]
@alperaltuntas since you are using 3D streams you should be made aware of these problems.

**Comment by jedwards4b** [comment]
@ekluzek you really need to provide a testcase, an expected result and how or where the actual result is different than the expected result.

**Comment by ekluzek** [comment]
@jedwards4b I will put together a clean test case. But, it will take me a bit to do. So that will be coming. But, I'm also going to do some checking for 2D streams to make sure there aren't issues there as well.

**Comment by ekluzek** [comment]
I verified the 2D behavior is working correctly for: lower, upper, and nearest for a SMS_D_Ld3.f09_g17.I1850Clm50BgcCrop.cheyenne_intel.clm-default case comparing the input file: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_WACCM6_CMIP6piControl001_y21-50avg_1850monthly_0.95x1.25_c180802.nc to the output history field NDEP_TO_SMINN. They are only different to roundoff level (1.e-23) and the first three days are identical to the same level. So that's all working correctly. So it seems I'm right this is just a problem with the 3D grids. Since, that's a relatively new feature that does make sense.

**Comment by ekluzek** [comment]
In checking nearest for the 3D grid, for a Jan/1 start date with a monthly file with time-stamps for Feb 1st, through Jan 1st, it matches index 10 for 00 sec (Dec 31st), and then index 0 (Feb 1st) for each step after that for at least the first 4 days.

**Comment by billsacks** [comment]
@ekluzek I'm going to close this issue under the optimistic assumption that it is okay with CDEPS. If you still feel this may be a problem, can you open an issue in the appropriate repository?
