### ISSUE TITLE
Better encapsulation of compiler flag customization

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#3287]
Hi all,

I'm back to spending a lot of cycles look at our build system. One that I noticed is that there's some confusion for concept of customizing compiler flags.

If you want to customize compiler flags, there's many places to look depending on the context:
* If you want a global customization for a file, it's done directly in  tools/Makefile (or CMakeLists.txt) (e.g. rrtmg_lw_k_g.f90)
* If you want compiler/platform specific changes, you use config_compilers.xml
* If you want compiler/platform specific changes for a particular file, you use a Depends file

I'm thinking that it sure would be nice if all compiler flag customizations could be encapsulated by config_compilers.xml. We could enhance it to have filename selectors.

Thoughts?

**Comment by jedwards4b** [comment]
I don't see any problem with this.

**Comment by mvertens** [comment]
@jgfouca - I think this is a really good idea.

**Comment by rljacob** [comment]
I like the idea of file-specific things (either global or compiler/platform specific) being in one config file but I'm concerned about config_compilers getting even larger.

**Comment by rljacob** [comment]
Also filenames from way down deep in component model source code probably shouldn't be in the global config_compilers.  This sounds like a  config file that should live in cime_config.

**Comment by billsacks** [comment]
I feel that component models should have a mechanism for setting file-specific flags for files in their builds that doesn't require touching cime. I think that's what @rljacob is suggesting, too, in his last comment:

> Also filenames from way down deep in component model source code probably shouldn't be in the global config_compilers. This sounds like a config file that should live in cime_config.

I think he means the cime_config in each component, and I would agree with that. In addition to preventing components from needing to update cime whenever they want to change something file-specific, this would also prevent problems like: If one component has a file foo.F90 that needs certain compiler flags, what happens to some other component's foo.F90 compilation?

**Comment by jedwards4b** [comment]
It should be straight forward to check for config_compilers.xml in each components cime_config directory and append it to the xml object if it's there.  We already look for one in ~/.cime/config

**Comment by jgfouca** [comment]
@jedwards4b , @billsacks , that's a good idea.

**Comment by billsacks** [comment]
@jedwards4b 's idea sounds good as long as it maintains a connection between file-specific settings and the component defining those settings. We could get some really hard to track down issues if the settings in one component impact the compilation of a different component (if there are duplicately-named files), so I want to be sure that we take pains to avoid that.
