### ISSUE TITLE
Include submodule status in provenance

### ISSUE THREAD

**Issue by oksanaguba** [ESMCI/cime#3290]
Right now there is no mechanist to find submodules commits from bld folder, only main repo's commit is saved. 

Separately, maybe not for this issue, but it would be good to save status of the clone in bld, not only SHA of the main repo. Right now I have a script that does this to catch possibly all recent changes in it:

```
gitstat=gitstat."${id}"
cd ~/${which}
echo " running stats on clone ${which}"
echo " status is ------------- " >> ${gitstat}
git status >> ${gitstat}
echo " branch is ------------- " >> ${gitstat}
git branch >> ${gitstat}
echo " diffs are ------------- " >> ${gitstat}
git diff >> ${gitstat}
echo " last 10 commits are ------------- " >> ${gitstat}
git log --first-parent  --pretty=oneline  HEAD~10..HEAD  >> ${gitstat}
```

**Comment by jgfouca** [comment]
@WesCoomber , I'm assigning you some of my tickets just to give you a few things to choose from.

**Comment by rljacob** [comment]
@jgfouca this needs to be re-opened.  PR #3696 does not provide the info @oksanaguba requested in this issue.

**Comment by jasonb5** [comment]
@rljacob @oksanaguba
I have a fix for this and want to verify I'm capturing the pertinent information. I've modeled this based on the script provided by Oksana. I've added three new files that capture the relevant info for the **git clone** and **all submodules**.

- GIT_STATUS
  - Provides a compact status, still includes commit and branch info.
- GIT_LOG
  - Provides last 10 commits.
- GIT_DIFF
  - Provides git diff in patch form.

I have not changed any of the existing git files included in the provenance since they capture slightly different details.

**Comment by rljacob** [comment]
Adding @sarats .   Looks good.  Do you have a sample output to point to?  
@oksanaguba what about submodules and any mods there?

**Comment by rljacob** [comment]
Sorry I wasn't reading carefully enough.  This also does submodules.

The GIT_DIFF output is great.

I wonder if GIT_LOG could be shortened to 5 log lines each.

I don't understand why GIT_STATUS just says "## HEAD (no branch)" for each submodule.  It should say something like 
```
HEAD detached at 7709c066
nothing to commit, working tree clean
```
for each submodule unless there are mods in the submodules.

**Comment by jasonb5** [comment]
I'm fine with changing GIT_LOG to 5, still gives a good snapshot and provides the current commit.

I added the `-s -b` flags to try an shorten GIT_STATUS. Looks like the `-b` flag only prints a commit when on an actual branch. I'll remove those flags.

**Comment by jasonb5** [comment]
Here's an updated sample of [GIT_STATUS](https://gist.github.com/jasonb5/30d9b3124620388044e9ac6395aa5a6c), little longer but has the correct information.

**Comment by rljacob** [comment]
Looks good!
