### ISSUE TITLE
Add a true walltimedef option to config_batch.xml

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3293]
Sometimes we need walltimemax to actually be the maximum to help set the rules for picking the right queue (using the "strict=true" setting).   But then the max becomes the default time when someone doesn't specify a time in their create_newcase and the max time can usually result in long wait times.  So add a walltimedef option to specify a more reasonable default time for a queue.

**Comment by jedwards4b** [comment]
The user already has an option to modify wall time on the command line of create_newcase as well as with xmlchange in the case.   For production experiments we most often want the max possible walltime.   I don't think that this change is warranted.

**Comment by rljacob** [comment]
In production experiments, you should specify the walltime and not rely on the default.
