### ISSUE TITLE
Want more easily parseable output in TestStatus and cs.status

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#330]
I have noted some of this to @jedwards4b and others already, and it sounds like this is something that people are thinking about, but I wanted to open an issue to track this and to record some specific thoughts.

In cime4 (thanks to @mvertens, if I remember correctly), test status output in both TestStatus and from running cimeteststatus had the very helpful property that a single "FAIL" line gave you all of the information you needed to know about the failure on that one line. For example, the line comparing the .base and .rest files for an ERS test looked like this:

```
PASS ERS_Ld7.f10_f10.ICLM45.yellowstone_gnu.cpl.hi.nc : test compare cpl.hi (.base and .rest files)
```

and comparisons with baselines gave a lot of information, including the baseline tag being compared against... here's an example from a different test:

```
FAIL ERS_D_Ly3.f09_g16_gl5.TG.yellowstone_gnu.cism-noevolve.cism.h.nc : baseline compare cism.h (baseline: compare .base file with develop_update_2016_07_n06_cism2_1_18_alpha07d file)
FAIL ERS_D_Ly3.f09_g16_gl5.TG.yellowstone_gnu.cism-noevolve.cpl.hi.nc : baseline compare cpl.hi (baseline: compare .base file with develop_update_2016_07_n06_cism2_1_18_alpha07d file)
FAIL ERS_D_Ly3.f09_g16_gl5.TG.yellowstone_gnu.cism-noevolve : baseline compare summary (baseline: compare .base file with develop_update_2016_07_n06_cism2_1_18_alpha07d file)
```

This was great, because you could use grep or similar tools to filter out the PASSes and COMMENTs, and then could see at a glance all of the details of what failed in your test suite.

This is no longer the case in cime5.

The TestStatus file gives _almost_ enough information to do this kind of parsing:

```
COMMENT for ERS_Ld7.f10_f10.ICLM45.yellowstone_gnu COMPCOMPARE: cpl.hi.nc : test compare functionality cpl.hi (.base and .rest files)
PASS ERS_Ld7.f10_f10.ICLM45.yellowstone_gnu compare
```

However, once you filter out the COMMENT lines (again, using grep or some similar tool), notice that the PASS / FAIL lines for the comparison of .base and .rest files are identical to the PASS / FAIL lines for the baseline comparison:

```
COMMENT for ERS_Ld7.f10_f10.ICLM45.yellowstone_gnu COMPCOMPARE : cpl.hi.nc : baseline compare baseline cpl.hi base with cesm1_5_beta07
PASS ERS_Ld7.f10_f10.ICLM45.yellowstone_gnu compare
```

Furthermore, if I remember correctly, a failure in one of the comparisons generates a single 'FAIL... compare' line, which does not indicate which component's history files failed the comparison. The tag being compared against is also missing for the baseline comparison line. These two "furthermore" features are not critical, but would be nice to have back.

__Perhaps more importantly: The output from cs.status further abbreviates the test results, making it even harder to filter this output to see at a glance what has failed.__

So I'd like to request that both the TestStatus and cs.status output be beefed up to be more similar to what we had in cime4.

**Comment by jgfouca** [comment]
I agree.
