### ISSUE TITLE
cime5.6.23 update moving three items to namelist changes answers for two I compsets

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3304]
I've verified that going from cime5.6.22 to cime5.6.25 changes answers for two I compsets

SMS.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel.clm-cropSMS_D.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel.clm-crop

The documentation says it should only change answers for C and G compsets.

One change that happens here is that hardcoded parameters were moved to namelist: seq_flux_atmocn_minwind, seq_flux_mct_albdif, seq_flux_mct_albdir. Currently the default namelist values are in single precision rather than double as they were hard-coded to be before the change. However, simply changing them to double-precision in the namelist doesn't seem to restore answers.

However, if I modify the code to use the previous version of seq_flux_mct.F90 and shr_flux_mod.F90 I can get the same answers again. Therefore I think for this machine and compiler combination there is a slight change in optimization on moving to namelist that causes the change in answers.

**Comment by jedwards4b** [comment]
Are these roundoff level changes or something you think may indicate an error?

**Comment by ekluzek** [comment]
It's difficult to assess if it's truly roundoff in the two tests, since it changes the solution enough that answers are significantly different. But, because it's identical on almost all of the CTSM testing (outside of these two), I'm thinking this must only be a roundoff difference.

But, the difference in going from double precision to single will be single precision roundoff, so we might want to change the default values to double precision in the namelist.

**Comment by billsacks** [comment]
You're saying that you get different answers for I compsets with the new vs. old seq_flux_mct / shr_flux_mod? That is very surprising to me because I thought that code is only used to calculate atmosphere-ocean fluxes, which shouldn't be used in an I compset. What am I missing?

**Comment by ekluzek** [comment]
Hmmm. Well I can't really say why I'm getting those differences. I'm just saying that I do. I do see the namelist in those two cases, so if they really aren't being used, for I cases, it possibly shouldn't set the namelist for these cases.

**Comment by ekluzek** [comment]
I'll try to get the code difference to as small as possible for when answers start to change.

**Comment by billsacks** [comment]
@ekluzek I'm going ahead and closing this old issue.

**Comment by ekluzek** [comment]
I think I must have made it around this problem, so closing it is fine. At one point I was concerned and it was likely holding up a tag. But, I must have found out it wasn't an issue or figured it wasn't enough of a problem to be concerned.
