### ISSUE TITLE
python 3 changes dtime to a float

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3305]
While running our testing under python3 for the first time, the type of "dtime"  in atm_in was changed to a float.
```
  BASE: dtime = 1800
  COMP: dtime = 1800.0
```
Still need to track this down.  May only be in E3SM but wanted to post it here.

Note from @jhkennedy , python3 changed how division works and this might be related.
![image](https://user-images.githubusercontent.com/947068/68901196-13627900-06fb-11ea-830a-b89f150caf76.png)

**Comment by jedwards4b** [comment]
This is in the cam/cime_config/buildnml file. Using // instead of / solves the problem.

**Comment by jedwards4b** [comment]
This is not a cime issue.  CIME is regularly tested with py3.
