### ISSUE TITLE
xmlchange does not handle 'list' settings

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3314]
The variable COMP_CLASSES is a list of variables with
```
    <default_value>CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV,IAC,ESP</default_value>
```
but trying to change this value with xmlchange results in an error:
```
./xmlchange COMP_CLASSES="CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV"                       
ERROR: Expecting a key value pair in the form of key=value. Got ['ATM']
cheyenne6: ~/sandboxes/cesm2_x_alpha/cime/scripts/foo
:) ./xmlchange COMP_CLASSES="CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV 
> ^C
cheyenne6: ~/sandboxes/cesm2_x_alpha/cime/scripts/foo
:) ./xmlchange COMP_CLASSES=CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV
ERROR: Expecting a key value pair in the form of key=value. Got ['ATM']
```

So for example docn has a xml variable SSTICE_DATA_FILENAME which is used to fill the 
strm_data_file field in the docn_streams file.   The strm_data_file variable can accept a list of files however SSTICE_DATA_FILENAME can only accept a single file entry.  The current workaround is to create a user_docn.streams.txt.prescribed and hand edit the field to add additional filenames. 

I think that we need to consider a long term solution to this such that xml variables can accept list values.

**Comment by ekluzek** [comment]
Doesn't it just need to be declared as an array type?

Currently it has...

``` xml
  <entry id="COMP_CLASSES">
    <type>char</type>
    <default_value>CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV,IAC,ESP</default_value>
```

I think it just needs to be declared as...

``` xml
  <entry id="COMP_CLASSES">
    <type>char(10)</type>
    <default_value>CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV,IAC,ESP</default_value>
```

namelist defaults have array types.

The thing that might be missing is that all of these are valid for an array, even though they wouldn't be valid for this specific case.

CPL
CPL,CPL,CPL
CPL,ATM,LND,ICE,OCN,ROF,GLC,WAV,IAC,CPL

**Comment by jedwards4b** [comment]
@ekluzek No - The list type is supported in the namelist xml file but not the config_component.xml files.  I played around with this for a while but there were a lot of unintended consequences.
