### ISSUE TITLE
Allow CESM ROF components to have compsets

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3324]
Allow CESM ROF components to have compsets.

The one change I know already that's required is this to add it for MOSART.

``` xml
diff --git a/config/cesm/config_files.xml b/config/cesm/config_files.xml
index 0b2ac066c..f97d3a80e 100644
--- a/config/cesm/config_files.xml
+++ b/config/cesm/config_files.xml
@@ -261,6 +261,7 @@
       <value component="clm"      >$COMP_ROOT_DIR_LND/cime_config/config_compsets.xml</value>
       <value component="cice"     >$COMP_ROOT_DIR_ICE/cime_config/config_compsets.xml</value>
       <value component="pop"      >$COMP_ROOT_DIR_OCN/cime_config/config_compsets.xml</value>
+      <value component="mosart"   >$COMP_ROOT_DIR_ROF/cime_config/config_compsets.xml</value>
       <value component="mom"      >$COMP_ROOT_DIR_OCN/cime_config/config_compsets.xml</value>
       <value component="nemo"   >$COMP_ROOT_DIR_OCN/cime_config/config_compsets.xml</value>
     </values>
```

This is already in place for E3SM. This will also require an update to CESM MOSART to add the config_compsets.xml and config_pes.xml files.

We also will be adding mizuroute as a new CESM ROF component, so it will need a similar line.

**Comment by ekluzek** [comment]
I propose the CESM letter to use for ROF compsets is "R". So for example I plan to add a R2000MOSART compset. Please give me feedback on that compset name.

**Comment by billsacks** [comment]
Sounds great, and I'm happy with R for the compset alias.

**Comment by ekluzek** [comment]
Note #3325 is needed to be fixed for this to go ahead.
