### ISSUE TITLE
Should we make some changes to support systems that don't support symbolic links?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3333]
Based on https://xenforo.cgd.ucar.edu/cesm/threads/error-build-fail-xatm-buildlib-failed-cesm2-0-0-porting.4966 a user is having problems seemingly because their system doesn't support symbolic links.

This is at least a problem for these buildlib scripts, which are symbolic links to other files in cime:

```
./src/components/stub_comps/socn/cime_config/buildlib
./src/components/stub_comps/sice/cime_config/buildlib
./src/components/stub_comps/satm/cime_config/buildlib
./src/components/stub_comps/sesp/cime_config/buildlib
./src/components/stub_comps/swav/cime_config/buildlib
./src/components/stub_comps/srof/cime_config/buildlib
./src/components/stub_comps/sglc/cime_config/buildlib
./src/components/stub_comps/slnd/cime_config/buildlib
./src/components/stub_comps/siac/cime_config/buildlib
./src/components/xcpl_comps/xrof/cime_config/buildlib
./src/components/xcpl_comps/xwav/cime_config/buildlib
./src/components/xcpl_comps/xatm/cime_config/buildlib
./src/components/xcpl_comps/xocn/cime_config/buildlib
./src/components/xcpl_comps/xice/cime_config/buildlib
./src/components/xcpl_comps/xlnd/cime_config/buildlib
./src/components/xcpl_comps/xglc/cime_config/buildlib
./src/components/data_comps/drof/cime_config/buildlib
./src/components/data_comps/desp/cime_config/buildlib
./src/components/data_comps/dwav/cime_config/buildlib
./src/components/data_comps/datm/cime_config/buildlib
./src/components/data_comps/dice/cime_config/buildlib
./src/components/data_comps/docn/cime_config/buildlib
./src/components/data_comps/dlnd/cime_config/buildlib
```

Should we replace these symbolic links with small wrapper scripts that call the appropriate common script?

I'm not sure if a system like this would also have problems with the symbolic links created on the fly in the case directory and elsewhere. If so, I would hope that os.symlink raises an exception, and I suppose we could try just copying the file in that case (via a wrapper function in utils.py). But maybe we could skip that piece for now and for now just deal with changing the above sym links to small wrapper scripts?

**Comment by jedwards4b** [comment]
Maybe instead we can update config_files.xml so that all point to the original location of the files and eliminate the symbolic links altogether.

**Comment by jedwards4b** [comment]
It would actually be a change in build.py rather than config_files.xml since the model config_dir is always assumed to have a script called buildlib.   Perhaps the path to and name of this script should be in config_files.xml and the only assumptions be the required input arguments to the scripts?

**Comment by mvertens** [comment]
I frankly thought the case directory was more robust when the necessary
files were actually copied in. I have never really understood why we moved
away from that. These are small files - and it would making transferring a
case to another user that had checked their code out in a separate sandbox
easier.

**Comment by jedwards4b** [comment]
@mvertens - Your comment is about links between the case directory and the model source code while the issue is about links within the cime source directory itself.  But to address your comment - when we copy files into the case instead of using those in the source tree it causes a break in the connection to git source code control and (If i recall correctly) issues with correctly finding python dependencies.
