### ISSUE TITLE
New name list option - constant_zenith_deg

### ISSUE THREAD

**Issue by whannah1** [ESMCI/cime#3339]
When adding the RCEMIP compset in E3SM https://github.com/E3SM-Project/E3SM/pull/3371 I really didn't like the redundant nature of the "uniform_angle" option that was added to support the CESM RCEMIP compset. uniform_angle is specified in the namelist, and then has to be loaded and passed through each call to the zenith angle routine only to get the same value back again. I think a much better approach is to have a namelist variable that simply changes the behavior of shr_orb_cosz() in shr_orb_mod.F90 without having to change how shr_orb_cosz is called. So I added "constant_zenith_deg" to do just that. I preserved the behavior of "uniform_angle" when "constant_zenith_deg" is not set, so it shouldn't affect CESM.

**Comment by rljacob** [comment]
I asked Walter to open this issue since we agreed to make issues for new development.

**Comment by jedwards4b** [comment]
@cacraigucar FYI

**Comment by billsacks** [comment]
@whannah1 At a glance, I agree that your implementation is better. It's a shame that there are now two ways to do the same thing, but I appreciate your taking the time to ensure that you wouldn't break the CESM implementation.

**Comment by cacraigucar** [comment]
I spoke with @brianpm and he is okay with the redundancy as long as the mods do not change the answers in the CESM QPRCEMIP compset.  This is especially crucial to not impact in the upcoming CESM2.1.2 release.

**Comment by rljacob** [comment]
Is CESM2.1.2 still using maint-5.6?  This new option will only be on master.

**Comment by jedwards4b** [comment]
Yes, this would not affect the 2.1.2 release

**Comment by rljacob** [comment]
"constant_zenith_deg" was implemented in way that allows the current method to also be used.  I'm going to start merging this to CIME on the E3SM side and once that makes it way back to master here, we can talk about removing one or the other.
