### ISSUE TITLE
PR #3343 breaks CMEPS

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#3349]
PR #3343 breaks the CMEPS test suite. This breaks all of the tests -but can be illustrated by the following simple test. 
Using the CMEPS hash: 5fd6837, `SMS_Vnuopc_Ld2.ww3a.ADWAV.cheyenne_intel`
- fails for cime hash 80cca5e95 
- passes for the previous cime hash b373a0240 

The failure looks like the following
```
20200111 101005.260 ERROR            PET00 src/addon/NUOPC/src/NUOPC_Base.F90:984 Invalid argument  - Attribute not present
20200111 101005.260 ERROR            PET00 esmFlds.F90:448 Invalid argument  - Passing error in return code
20200111 101005.260 ERROR            PET00 med.F90:701 Invalid argument  - Passing error in return code
20200111 101005.260 ERROR            PET00 ESM0001:src/addon/NUOPC/src/NUOPC_Driver.F90:2223 Invalid argument  - Phase 'IPDv03p3' Initialize for modelComp 2: MED did not return ESMF_SUCCESS
20200111 101005.260 ERROR            PET00 ESM0001:src/addon/NUOPC/src/NUOPC_Driver.F90:1589 Invalid argument  - Passing error in return code
20200111 101005.260 ERROR            PET00 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:2223 Invalid argument  - Phase 'IPDv02p3' Initialize for modelComp 1: ESM0001 did not return ESMF_SUCCESS
20200111 101005.260 ERROR            PET00 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:1585 Invalid argument  - Passing error in return code
20200111 101005.260 ERROR            PET00 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:398 Invalid argument  - Passing error in return code
20200111 101005.260 ERROR            PET00 esmApp.F90:137 Invalid argument  - Passing error in return code
20200111 101005.260 INFO             PET00 Finalizing ESMF
```
One option is to back this out of my upcoming PRs until this problem can be resolved.

**Comment by jedwards4b** [comment]
It seems to indicate that the NUOPC_GetAttribute call [here](https://github.com/ESCOMP/CMEPS/blob/master/mediator/esmFlds.F90#L447) has a bad argument.   @uturuncoglu @rsdunlapiv is this a bug in the latest ESMF/NUOPC build (esmf/8.1.0b05)?

**Comment by jedwards4b** [comment]
> There was a need in NUOPC to distinguish between producer and consumer
transfer actions. This came in with ESMF_8_1_0_beta_snapshot_04, in
order to fully support GeomObject transfer through component hierarchies.

The change in NUOPC requires a change in the user code:

(1) Declare two additional local variables:
+      type(ESMF_StateIntent_Flag)             :: stateIntent
+      character(len=80)                       :: transferActionAttr

(2) Obtain the stateIntent for the "state" argument you are handling:
+      call ESMF_StateGet(state, stateIntent=stateIntent, rc=rc)

(3) Set the transferActionAttr string according to the intent:
+      if (stateIntent==ESMF_STATEINTENT_EXPORT) then
+        transferActionAttr="ProducerTransferAction"
+      elseif (stateIntent==ESMF_STATEINTENT_IMPORT) then
+        transferActionAttr="ConsumerTransferAction"
+      else
+        call ESMF_LogSetError(ESMF_RC_ARG_BAD, &
+          msg="The stateIntent must either be IMPORT or EXPORT here.", &
+          line=__LINE__, &
+          file=__FILE__, &
+          rcToReturn=rc)
+        return  ! bail out
+      endif

(4) Replace the current call:
-     call NUOPC_GetAttribute(field, name="TransferActionGeomObject",
value=transferAction, rc=rc)
+     call NUOPC_GetAttribute(field, name=transferActionAttr,
value=transferAction, rc=rc)

This should fix the issue. Let me know.

-Gerhard

**Comment by jedwards4b** [comment]
Now I get an error:
Invalid argument  - The stateIntent must either be IMPORT or EXPORT here.
Do I need to explicitly set that Intent someplace?

**Comment by uturuncoglu** [comment]
@jedwards4b I am not sure but based on the NUOPC ref document

http://www.earthsystemmodeling.org/esmf_releases/last_built/NUOPC_refdoc/node4.html#SECTION00049700000000000000

**field** and **name** is defined as intent(in) and rest of them intent(out)

**Comment by uturuncoglu** [comment]
Sorry, you are getting error from ESMF_StateGet. Right?

**Comment by uturuncoglu** [comment]
State needs to be intent(in).

http://www.earthsystemmodeling.org/esmf_releases/last_built/ESMF_refdoc/node4.html#SECTION04077800000000000000

**Comment by jedwards4b** [comment]
Moving this to the CMEPS repository https://github.com/ESCOMP/CMEPS/issues/45
