### ISSUE TITLE
Current FORCE_BUILD_SMP behavior and documentation disagree

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3352]
(originally reported in https://github.com/E3SM-Project/E3SM/issues/2324)

FORCE_BUILD_SMP is defined as

```
  TRUE implies always build model for openmp capability
  If FALSE, component libraries are built with OpenMP capability only if
  the NTHREADS_ setting for that component is greater than 1 in env_mach_pes.xml.
  If TRUE, the component libraries are always built with OpenMP capability.
```
Currently, if ANY component has NTHREADS_ > 1, then ALL components are built with OpenMP capability, independent of the value of FORCE_BUILD_SMP. The only time the value of FORCE_BUILD_SMP matters is if NTHREADS_ == 1 for all components.

This is a change of behavior. CIME around March 3, 2017 (used in E3SM v1.0.0-beta.1) behaved as described as above. However, this behavior was lost by September 2017 (cime used in E3SM v1.0.0-beta.2)

**Comment by jgfouca** [comment]
@rljacob , the documentation on FORCE_BUILD_SMP has been updated. I don't think we will be going to back to the old behavior.
