### ISSUE TITLE
Attempt to download inputdata files with wget is hanging

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3365]
The check_input_data script is hanging when attempting to check the server with protocol wget.

This problem was originally reported in the CESM forums: https://xenforo.cgd.ucar.edu/cesm/threads/downloading-input-data-b1850-compset-no-server-response.4999/ . I have reproduced it on cheyenne as follows:

```
git clone https://github.com/ESCOMP/CESM.git
cd CESM
git checkout cesm2.1-alphabranch
./manage_externals/checkout_externals
cd cime/scripts/
./create_newcase --case /glade/scratch/sacks/test_inputdata_0124a --compset B1850 --res f09_g17
cd /glade/scratch/sacks/test_inputdata_0124a
mkdir /glade/scratch/sacks/cesm_test_inputdata
./xmlchange DIN_LOC_ROOT=/glade/scratch/sacks/cesm_test_inputdata
./case.setup
./preview_namelists
```

The last command produces:

```
Setting resource.RLIMIT_STACK to -1 from (307200000, -1)
Refcase not found in /glade/scratch/sacks/cesm_test_inputdata/cesm2_init/b.e20.B1850.f09_g17.pi_control.all.299_merge_v3/0134-01-01, will attempt to download from inputdata
Checking server ftp://gridanon.cgd.ucar.edu:2811/cesm/inputdata/ with protocol gftp
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Client protocol gftp not enabled
Checking server ftp://ftp.cgd.ucar.edu/cesm/inputdata with protocol wget
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Using protocol wget with user anonymous and passwd user@example.edu
```

then hangs.

It's possible that the solution to this problem is simply to reboot the system used with wget; that would address the "CRITICAL" nature of this issue.

However, I wonder if it would be possible for the check_input_data script to handle timeouts more gracefully. Now that we support more inputdata servers, it seems like it will be more common for one of them to be down. If the data can be retrieved from the servers that are up, then it seems like the scripts should gracefully handle an unnecessary server being down, and just move on without complaint. (But maybe I'm misunderstanding the problem here, or what I'm suggesting is harder than I think.)

**Comment by billsacks** [comment]
@jedwards4b do you have time to look at this today - at least in terms of the short-term fix of rebooting a server that may be down?

**Comment by billsacks** [comment]
(I'm removing the cesm-only label because I'm not sure if it only affects cesm... and in any case, the more general issue raised in my last paragraph affects everyone.)

**Comment by jedwards4b** [comment]
@billsacks looking into it now

**Comment by jgfouca** [comment]
Agree with @billsacks , a forever-hang is a bad. We should add a timeout field to our run_cmd wrapper. We already have a Timeout context manager in utils.py. I'd all a separate ticket for this.

**Comment by jedwards4b** [comment]
@jgfouca that was my first thought and timeout is supported in python3 for subprocess, 
but not in python2 so I didn't end up using it.

**Comment by jgfouca** [comment]
@jedwards4b , since we have our own Timeout content manager, we can use that for now with some minor changes to run_cmd.

**Comment by jedwards4b** [comment]
Working on it - I didn't see that before - but I think it won't work with the ftp interface, only the wget one.

**Comment by jgfouca** [comment]
@jedwards4b, I'm not familiar with FTP, but the Timeout content manager is very general:

```
with Timeout(num_secs):
    * any code you want*
```
