### ISSUE TITLE
cime_run_ocn_setup_send not called when cpl_seq_option=NUOPC

### ISSUE THREAD

**Issue by herrwang0** [ESMCI/cime#3372]
It looks like `cime_run_ocn_setup_send` is not called in `cime_run()` when `cpl_seq_option` = NUOPC.

The coupling sequence of NUOPC_TIGHT and CESM1_MOD_TIGHT seems to be the same. Is it also the case for NUOPC and CESM1_MOD? If so, then something is missing here https://github.com/ESMCI/cime/blob/d3624d963456f74f122d4d83a58067f443e80a2b/src/drivers/mct/main/cime_comp_mod.F90#L2549

**Comment by mvertens** [comment]
NUOPC mode is only for debugging mct and should at this point be removed.
It should not be used.
