### ISSUE TITLE
Domain filename being stripped from input_data_list

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#3376]
In doing release testing, I ran into an issue where the domain filename was being stripped from the full path of the domain file.  For example

    domain1 = /glade/scratch/fischer/inputdata/atm/datm7/
Should be 
   domain1 = /glade/scratch/fischer/inputdata/atm/datm7/domain.T62.050609.nc

It looks like scripts/lib/CIME/nmlgen.py at line 496 should be
                    filepath = os.path.join(domain_filepath, filename.strip())
Instead of 
                    filepath = os.path.join(domain_filepath, os.path.dirname(filename.strip()))

I'm testing this fix now.  This was happening for several tests, but I'm concentrating on 
T62_g16.GIAF.cheyenne_intel for now.

**Comment by mvertens** [comment]
@fischer - why has this not occurred before?

**Comment by fischer** [comment]
Excellent question - @mvertens let's ask @fischer-ncar.

**Comment by fischer-ncar** [comment]
@mvertens, this has been happening for 8 months now.  Testing has never caught it since the domain
file always existed in inputdata.   When I run my release testing with an empty inputdata, the scripts try to download the file and fail with a bad filepath.

**Comment by fischer-ncar** [comment]
Fixed with #3378
