### ISSUE TITLE
Spectral-element grid updates

### ISSUE THREAD

**Issue by adamrher** [ESMCI/cime#3385]
This issue is to be associated with a CIME PR accommodating a CAM PR: https://github.com/ESCOMP/CAM/pull/63. The thrust of the effort here is to push new spectral-element (SE) grids onto the trunk in preparation for the cesm2.2 release, which will contain many updates and enhancements to the SE dycore. 

Code modifications are currently in my sandbox on glade: /glade/u/home/aherring/src/camtrunk_200115/cime/. @fischer-ncar has agreed to incorporate them into a branch off of his CIME fork.

1. Add in grid entries, domain and mapping files in cime/config/cesm/config_grids* for two variable resolution grids: ARCTIC and ARCTICGRIS, supporting F compset simulations.

2. Add ATM_NCPL entries for ARCTIC (ATM_NCPL=192) & ARCTICGRIS (ATM_NCPL=384) grids to cime/src/drivers/mct/cime_config/config_component_cesm.xml. 

3. Increase CONUS grid ATM_NCPL=384, to be consistent with dycore time-stepping changes in the CAM PR.

3. Add grid entries, domain and mapping files for the 2x2 physics grid: ne120pg2 (grid alias ne120pg2_ne120pg2_mt12) to support an F compset configuration. 

4. Add mapping files for 2x2 physics grid: ne30pg2. Change not_compset="_POP|_CLM" for grid alias ne30pg2_ne30pg2_mg17 to not_compset="_POP" ... i.e, permit this grid to be ran in an F compset.

Please read the [issue associated with the CAM PR](https://github.com/ESCOMP/CAM/issues/62) for a more detailed description and motivations for the proposed enhancements (as well as pictures of the new arctic grids)

**Comment by jedwards4b** [comment]
I didn't think we wanted to start adding variable resolution grids to the config_grids file.  Wasn't the plan to use https://github.com/ESMCI/cime/issues/3330 when it is completed?

**Comment by adamrher** [comment]
https://github.com/ESMCI/cime/issues/3330 is for to make it easy for CESM users to eventually make their own grids. @PeterHjortLauritzen and I have been planning on supporting three variable resolution grids as a standard grid configuration: CONUS, ARCTIC and ARCTICGRIS. This is planned for both the cesm2.2 release, and to assist a joint AMWG/LIWG cross-working group project. We are hoping that we can get these grids into CIME so that cam_development master can run these three grids out of the box and with the appropriate time-stepping.

**Comment by jedwards4b** [comment]
Okay - I think that the mechanism of #3330 would allow that too but it's not ready yet and I don't want to slow your progress.
