### ISSUE TITLE
Improve cprnc build process

### ISSUE THREAD

**Issue by rsdunlapiv** [ESMCI/cime#3389]
The "cprnc" tool is required for CIME regression testing.  I recently tried to install on a new platform and found that the README was not accurate and I had to examine the internals of the Makefile in order to figure out how to build it.  Since CIME is being ported to a lot of different platforms (e.g., for the UFS release), the build of cprnc is currently a major liability--i.e., it may be hard to a regular user to install it and therefore the entire regression testing process would not be viable.  

Recommendations:

1.  Since CIME is capable of building entire models, the build of cprnc should be simplified and standardized, e.g., ./configure && make.  Generation of the env_machine_specific.sh should be hidden entirely from the user and sensible defaults (e.g., mpi-serial) should be preset.

2.  Consider automated build of cprnc when the regression tests are run.  In CIME we already have the full machine/compiler information needed.  Maintaining cprnc in a fixed place has advantages, but it should be straightforward to check if cprnc is already built and if not, to build it in a temporary location using the case compiler info, and use that for the regression tests.  This would completely remove the need for users to know about/install cprnc.

**Comment by jedwards4b** [comment]
cprnc only needs to be built and installed once per platform - if the documentation is inaccurate your PR to update it would be welcome - but it is unnecessary to further complicate the cprnc build process.

**Comment by billsacks** [comment]
I agree with @rsdunlapiv that this would be really good, though I'm not sure if @jedwards4b should be assigned to this right now given everything on his plate. See also #2457 .

**Comment by ekluzek** [comment]
Yes @rsdunlapiv as @billsacks points out your point "2" above is really issue #2457. So the parts of your request for that point should be kept there (I would even suggest deleting that from your text above). The part of making the CPRNC build better and standardized is a good one if someone can be identified to do it. Having it leverage the existing configure and Makefile that we already use for other standalone tools makes a whole ton of sense. @jedwards4b is right that you only need to do it once, but it would help people who are porting CIME to their own systems. There are university users that do that sort of thing, and people that run on their laptops or desktops.

**Comment by jgfouca** [comment]
I'm going to volunteer @WesCoomber for this. I think it would be fairly easy to check for the existence and validity of the CCSM_CPRNC machine setting. If this setting is missing or points to a file that doesn't exist, we add cprnc to the list of sharelibs and set CCSM_CPRNC to point there.
