### ISSUE TITLE
Redundant history writing code in cime_comp_run.F90

### ISSUE THREAD

**Issue by herrwang0** [ESMCI/cime#3399]
Code in subroutine cime_run_write_history() https://github.com/ESMCI/cime/blob/2a8bbd8e5b86e66e7a6e4f355c3815548de11577/src/drivers/mct/main/cime_comp_mod.F90#L2880 is repeated in the lines below.

Maybe auxiliary history write should also be included in cime_run_write_history() (and remove the code between line 2882 and line 3059 altogether)?

**Comment by rljacob** [comment]
This does look like a copy-and-paste error.  Why call cime_run_write_history and then call the code that is in cime_run_write_history?

**Comment by ekluzek** [comment]
With drivers moved out this is no longer an issue for cime.
