### ISSUE TITLE
ERROR: box_rearrange.F90.in

### ISSUE THREAD

**Issue by donakanga** [ESMCI/cime#3408]
Hi,
I am trying to run PTCLM by mostly following the CLM/CTSM materials for running single point simulations. Everything seems to go well: creating the case, case.setup and case.build (steps followed documented in attached file). However, case.submit fails and I get the following **error**:

Will greatly appreciate some help.

[PTCLM_Issue_20200219.pdf](https://github.com/ESMCI/cime/files/4227792/PTCLM_Issue_20200219.pdf)

NODE#  NAME
(    0)  r6i6n32
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Variable not found
 pio_support::pio_die:: myrank=          -1 : ERROR: box_rearrange.F90.in:
         534 : box_rearrange_io2comp: size(compbuf)=          15
  not equal to size(compdof)=      829440

Image              PC                Routine            Line        Source
cesm.exe           0000000001858CAD  Unknown               Unknown  Unknown
cesm.exe           00000000012E8951  pio_support_mp_pi         118  pio_support.F90
cesm.exe           00000000013AA012  box_rearrange_mp_         534  box_rearrange.F90.in
cesm.exe           0000000001363D29  rearrange_mp_rear         108  rearrange.F90.in
cesm.exe           000000000138D553  piodarray_mp_read        1029  piodarray.F90.in
cesm.exe           00000000005F7FEC  ncdio_pio_mp_ncd_        1841  ncdio_pio.F90.in
cesm.exe           0000000000554E9D  dynpftfilemod_mp_         141  dynpftFileMod.F90
cesm.exe           000000000054EB55  dynsubgriddriverm         108  dynSubgridDriverMod.F90
cesm.exe           000000000050610B  clm_initializemod         448  clm_initializeMod.F90
cesm.exe           00000000004F1C1A  lnd_comp_mct_mp_l         233  lnd_comp_mct.F90
cesm.exe           00000000004247C8  component_mod_mp_         267  component_mod.F90
cesm.exe           0000000000413914  cime_comp_mod_mp_        1237  cime_comp_mod.F90
cesm.exe           000000000042196E  MAIN__                    114  cime_driver.F90
cesm.exe           000000000040511E  Unknown               Unknown  Unknown
libc.so.6          00002BA76FBB26E5  __libc_start_main     Unknown  Unknown
cesm.exe           0000000000405029  Unknown               Unknown  Unknown
MPI_Abort: error code = 1
~

**Comment by ekluzek** [comment]
The problem seems to be that your case is pointing to a global timeseries file rather than a single point version.

 flanduse_timeseries = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_0.9x1.25_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c170824.nc'

You either need to change that to point to a single point one, or remove the landuse.timeseries from the simulation.

This issue should be moved over to the CTSM repository.

**Comment by donakanga** [comment]
I have tried changing the path flanduse_timeseries to point to the single point one without success. I notice that the changes are saved after opening, editing, and exiting the vi editor (because I find them once  I exit and reopen the lnd_in to check, almost immediately). However, once I run the ./case.build it goes back to pointing to the global timeseries file. 

The lnd_in file is found in the CaseDocs via the following path:
/glade/u/home/akanga/ptclm_cases/IHistCLM50sp_20200212


The single point timeseries is in the following path

/glade/scratch/akanga/single_point/landuse.timeseries_0.9x1.25_hist_16pfts_Irrig_CMIP6_simyr1850-2015_274.4_42.3_c170824.nc

**Comment by ekluzek** [comment]
You need to add it to your user_nl_clm file so it points to the right one. Otherwise, it'll overwrite it when it creates the namelist.

**Comment by donakanga** [comment]
Okay, thanks, @ekluzek !I added it to the user_nl_clm fie, ran .case.build --clean and then .case.build before submitting the case. Now I get the following error:

 Invalid PIO rearranger comm max pend req (comp2io),            0
 Resetting PIO rearranger comm max pend req (comp2io) to           64
 PIO rearranger options:
   comm type     =
 p2p

   comm fcd      =
 2denable

   max pend req (comp2io)  =           0
   enable_hs (comp2io)     = T
   enable_isend (comp2io)  = F
   max pend req (io2comp)  =          64
   enable_hs (io2comp)    = F
   enable_isend (io2comp)  = T
(seq_comm_setcomm)  init ID (  1 GLOBAL          ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_setcomm)  init ID (  2 CPL             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_setcomm)  init ID (  5 ATM             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID (  6 CPLATM          ) join IDs =     2     5       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID (  3 ALLATMID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID (  4 CPLALLATMID     ) join IDs =     2     3       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID (  9 LND             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 10 CPLLND          ) join IDs =     2     9       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID (  7 ALLLNDID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID (  8 CPLALLLNDID     ) join IDs =     2     7       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 13 ICE             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 14 CPLICE          ) join IDs =     2    13       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 11 ALLICEID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 12 CPLALLICEID     ) join IDs =     2    11       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 17 OCN             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 18 CPLOCN          ) join IDs =     2    17       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 15 ALLOCNID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 16 CPLALLOCNID     ) join IDs =     2    15       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 21 ROF             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 22 CPLROF          ) join IDs =     2    21       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 19 ALLROFID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 20 CPLALLROFID     ) join IDs =     2    19       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 25 GLC             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 26 CPLGLC          ) join IDs =     2    25       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 23 ALLGLCID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 24 CPLALLGLCID     ) join IDs =     2    23       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 29 WAV             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
(seq_comm_joincomm) init ID ( 30 CPLWAV          ) join IDs =     2    29       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 27 ALLWAVID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 28 CPLALLWAVID     ) join IDs =     2    27       ( npes =     1) ( nthreads =  1)
(seq_comm_setcomm)  init ID ( 33 ESP             ) pelist   =     0     0     1 ( npes =     1) ( nthreads =  1)( suffix =)
                                                     
(seq_comm_joincomm) init ID ( 34 CPLESP          ) join IDs =     2    33       ( npes =     1) ( nthreads =  1)
(seq_comm_jcommarr) init ID ( 31 ALLESPID        ) join multiple comp IDs       ( npes =     1) ( nthreads =  1)
(seq_comm_joincomm) init ID ( 32 CPLALLESPID     ) join IDs =     2    31       ( npes =     1) ( nthreads =  1)
(seq_comm_printcomms)     1     0     1     1  GLOBAL:
(seq_comm_printcomms)     2     0     1     1  CPL:
(seq_comm_printcomms)     3     0     1     1  ALLATMID:
(seq_comm_printcomms)     4     0     1     1  CPLALLATMID:
(seq_comm_printcomms)     5     0     1     1  ATM:
(seq_comm_printcomms)     6     0     1     1  CPLATM:
(seq_comm_printcomms)     7     0     1     1  ALLLNDID:
(seq_comm_printcomms)     8     0     1     1  CPLALLLNDID:
(seq_comm_printcomms)     9     0     1     1  LND:
(seq_comm_printcomms)    10     0     1     1  CPLLND:
(seq_comm_printcomms)    11     0     1     1  ALLICEID:
(seq_comm_printcomms)    12     0     1     1  CPLALLICEID:
(seq_comm_printcomms)    13     0     1     1  ICE:
(seq_comm_printcomms)    14     0     1     1  CPLICE:
(seq_comm_printcomms)    15     0     1     1  ALLOCNID:
(seq_comm_printcomms)    16     0     1     1  CPLALLOCNID:
(seq_comm_printcomms)    17     0     1     1  OCN:
(seq_comm_printcomms)    18     0     1     1  CPLOCN:
(seq_comm_printcomms)    19     0     1     1  ALLROFID:
(seq_comm_printcomms)    20     0     1     1  CPLALLROFID:
(seq_comm_printcomms)    21     0     1     1  ROF:
(seq_comm_printcomms)    22     0     1     1  CPLROF:
(seq_comm_printcomms)    23     0     1     1  ALLGLCID:
(seq_comm_printcomms)    24     0     1     1  CPLALLGLCID:
(seq_comm_printcomms)    25     0     1     1  GLC:
(seq_comm_printcomms)    26     0     1     1  CPLGLC:
(seq_comm_printcomms)    27     0     1     1  ALLWAVID:
(seq_comm_printcomms)    28     0     1     1  CPLALLWAVID:
(seq_comm_printcomms)    29     0     1     1  WAV:
(seq_comm_printcomms)    30     0     1     1  CPLWAV:
(seq_comm_printcomms)    31     0     1     1  ALLESPID:
(seq_comm_printcomms)    32     0     1     1  CPLALLESPID:
(seq_comm_printcomms)    33     0     1     1  ESP:
(seq_comm_printcomms)    34     0     1     1  CPLESP:
 (t_initf) Read in prof_inparm namelist from: drv_in
 (t_initf) Using profile_disable=          F
 (t_initf)       profile_timer=                      1
 (t_initf)       profile_depth_limit=                4
 (t_initf)       profile_detail_limit=               2
 (t_initf)       profile_barrier=          F
 (t_initf)       profile_outpe_num=                  1
 (t_initf)       profile_outpe_stride=               0
 (t_initf)       profile_single_file=      F
 (t_initf)       profile_global_stats=     T
 (t_initf)       profile_ovhd_measurement= F
 (t_initf)       profile_add_detail=       F
 (t_initf)       profile_papi_enable=      F


  1 pes participating in computation for CLM

-----------------------------------

NODE#  NAME
(    0)  r6i6n31
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Variable not found
 calling getglobalwrite with decomp_index=            1  and clmlevel= gridcell
 ERROR: ERROR in dynpftFileMod.F90 at line 169
Image              PC                Routine            Line        Source
cesm.exe           0000000001858CAD  Unknown               Unknown  Unknown
cesm.exe           000000000114B4B2  shr_abort_mod_mp_         114  shr_abort_mod.F90
cesm.exe           00000000004F74A0  abortutils_mp_end          91  abortutils.F90
cesm.exe           0000000000555DD1  dynpftfilemod_mp_         169  dynpftFileMod.F90
cesm.exe           000000000054EB55  dynsubgriddriverm         108  dynSubgridDriverMod.F90
cesm.exe           000000000050610B  clm_initializemod         448  clm_initializeMod.F90
cesm.exe           00000000004F1C1A  lnd_comp_mct_mp_l         233  lnd_comp_mct.F90
cesm.exe           00000000004247C8  component_mod_mp_         267  component_mod.F90
cesm.exe           0000000000413914  cime_comp_mod_mp_        1237  cime_comp_mod.F90
cesm.exe           000000000042196E  MAIN__                    114  cime_driver.F90
cesm.exe           000000000040511E  Unknown               Unknown  Unknown
libc.so.6          00002B93904196E5  __libc_start_main     Unknown  Unknown
cesm.exe           0000000000405029  Unknown               Unknown  Unknown
MPI_Abort: error code = 1001

**Comment by jedwards4b** [comment]
In this case check the lnd.log for error details.

**Comment by donakanga** [comment]
I checked; the error is as pasted below:

 landuse.timeseries_0.9x1.25_hist_16pfts_Irrig_CMIP6_simyr1850-2015_274.4_42.3_c
 170824.nc
 (GETFIL): using
 /glade/scratch/akanga/single_point/landuse.timeseries_0.9x1.25_hist_16pfts_Irri
 g_CMIP6_simyr1850-2015_274.4_42.3_c170824.nc
 Opened existing file
 /glade/scratch/akanga/single_point/landuse.timeseries_0.9x1.25_hist_16pfts_Irri
 g_CMIP6_simyr1850-2015_274.4_42.3_c170824.nc      524288

 dynpft_consistency_checks settings:
 &DYNPFT_CONSISTENCY_CHECKS
 CHECK_DYNPFT_CONSISTENCY        = T
 /

 dynpft_check_consistency mismatch between PCT_NAT_PFT at initial time and that
 obtained from surface dataset
 On landuse_timeseries file:   0.000000000000000E+000  5.383352970758751E-002
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.646399914469780
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.233851621709065
  6.591493411356704E-002
 On surface dataset:   0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000

 Confirm that the year of your surface dataset
 corresponds to the first year of your landuse_timeseries file
 (e.g., for a landuse_timeseries file starting at year 1850, which is typical,
 you should be using an 1850 surface dataset),
 and that your landuse_timeseries file is compatible with the surface dataset.

 If you are confident that you are using the correct landuse_timeseries file
 and the correct surface dataset, then you can bypass this check by setting:
   check_dynpft_consistency = .false.
 in user_nl_clm

 local  gridcell index =            1
 global gridcell index =            1
 gridcell longitude    =    275.000000000000
 gridcell latitude     =    41.9371727748691
 ENDRUN:
 ERROR: ERROR in dynpftFileMod.F90 at line 169

**Comment by billsacks** [comment]
@donakanga since your original issue seems to be resolved and now you have a new one that is specific to the land model, can you please post your most recent message to the land model forum in the CESM forums: https://xenforo.cgd.ucar.edu/cesm/forums/ctsm-clm-mosart-rtm.134/ . Please include the information requested in https://xenforo.cgd.ucar.edu/cesm/threads/information-to-include-in-help-requests.4974/ - specifically, the model version, any changes you have made to the source code, and documenting the steps you have taken that lead to this error.

I'm going to go ahead and close this issue.

**Comment by donakanga** [comment]
Thank you, @billsacks. I have posted to the land model forum in the CESM forums.
