### ISSUE TITLE
Allow river input from non-land

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3410]
There is an assumption in the coupler that all x2r fluxes are from the land model.   New capability in MOSART (such as keeping track of heat) mean that other models, such as the atmosphere, send fluxes to the river model.

Following what was done for the land ice component, we should introduce new state and flux strings:
a2x_states_to_rof
a2x_fluxes_to_rof
l2x_fluxes_to_rof

**Comment by rljacob** [comment]
An attempt to do this is in https://github.com/E3SM-Project/E3SM/pull/3460

Attention @billsacks

**Comment by billsacks** [comment]
Thanks, @rljacob . I took a quick look and this looks like a good approach.
