### ISSUE TITLE
Add a --force-build-cprnc argument to create_test

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3418]
This is a follow-up from #3400 . In that PR, @WesCoomber added the very helpful ability for cprnc to be built on the fly if it does not already exist on the given machine. I think that a helpful additional feature (though not needed immediately) would be adding something like a `--force-build-cprnc` flag to `create_test`. If specified, this would ignore the cprnc on the machine and build it as part of `create_test`. I think I would use this feature in my workflow in general to ensure that I am always using the latest cprnc.

Actually, for full disclosure: As I expressed in #2457 , my feeling is that it would be a good idea if we always built cprnc on the fly rather than using a prebuilt version from an unknown version of cime. I was overruled on this point, but I'm hoping that if some of us get enough experience with this on-the-fly building and are happy with how it's working, then we can eventually move to using that always. I feel this will help both in terms of preventing us from needing to update cprnc on all of our machines (which has caused us a lot of problems and lost time in the past) and in terms of allowing new features to be added to cprnc that are tied in with changes needed in the python. (I've really struggled when I've needed to change the behavior of cprnc, because of the need to maintain backwards and forwards compatibility due to this awkwardness of using a fixed cprnc version for all versions of cime on a given machine.)

**Comment by jedwards4b** [comment]
I don't really see this as necessary - you can just modify CCSM_CPRNC in the config_machines.xml file.

**Comment by rsdunlapiv** [comment]
But then you have to go through the steps of manually building it, right?  Isn't the advantage of this that you can build it with a single option while running the test?

**Comment by billsacks** [comment]
> But then you have to go through the steps of manually building it, right? Isn't the advantage of this that you can build it with a single option while running the test?

Right, that's what I'm thinking. Basically, I want the workflow for CTSM testing to include this new option. That would be a trivial change to the workflow (which in fact would be invisible to people doing testing because of the wrapper script we use), whereas @jedwards4b 's proposal would require documenting a fairly complicated series of steps.

**Comment by billsacks** [comment]
Alternatively, I could change the out-of-the-box cheyenne and izumi ccsm_cprnc values to be unset to achieve this goal, but @jedwards4b I'm thinking you don't want that at this time based on your earlier comments in #2457. If you have changed your mind on that and are actually happy with cprnc being built on the fly always on these main test machines, then we could do that instead of this proposal.

**Comment by jedwards4b** [comment]
@rsdunlapiv No - with #3400 this is automatic.  
@billsacks what complicated steps - you just need to change CCSM_CPRNC before you test. 
I don't mind if you want to make this the default on a platform or two.

**Comment by billsacks** [comment]
@jedwards4b - you're right, I overstated with "complicated" because you just need to change CCSM_CPRNC, not actually manually build it. That said, this would still be an awkward addition to our current streamlined CTSM testing procedure, and as a general rule I don't like ever recommending making changes in the source tree when running testing, because it's error-prone and makes it hard to reproduce test results.

But if you're comfortable with our now changing the behavior on cheyenne and izumi to always build cprnc on the fly, then I'll make that change instead. I'll leave this issue open a bit longer to see if it receives any more comments before closing it.

**Comment by billsacks** [comment]
Closing in favor of #3858
