### ISSUE TITLE
Fill pattern diff from cprnc

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3433]
I'm trying to understand this warning from cprnc when it compares 2 ELM files (in a baseline comparison)
 
```
topo   (lon,lat)
 WARNING: Fill patterns differ between files
 FILLDIFF topo
                3312  (     1,     1) (     1,     1)
                   0   0.000000000000000E+00   0.000000000000000E+00
                   0   0.000000000000000E+00   0.000000000000000E+00
                3312  (     0,     1) (     0,     1)
          avg abs field values:    0.000000000000000E+00
                                   0.000000000000000E+00
```

Apparently everything is 0 so how can it tell that a fill pattern is different?

This is the only difference between 2 files and it causes cprnc to say they are DIFFERENT.

The cause of the diff is this PR  https://github.com/E3SM-Project/E3SM/pull/3448

**Comment by billsacks** [comment]
"Fill pattern" refers to which grid cells have actual data vs. missing data (according to the `_FillValue` or `missing_value` attribute on the netcdf file). The values reported ignore grid cells with missing values. So, for example, with a missing value flag of -999, you could have:

File 1: 0, 0, -999, -999

File 2: 0, 0, 0, -999

and that would result in this FILLDIFF message.

I suggest viewing the files in ncview or similar: that usually makes this problem apparent.
