### ISSUE TITLE
Improve documentation and/or logic of env_batch.xml variables. 

### ISSUE THREAD

**Issue by golaz** [ESMCI/cime#3442]
When submitting jobs on compy, I need CIME to specify both SLURM partition and qos:

```
--partition=slurm
--qos=watercycle
```

I can do this manually with

`./case.submit -a="--qos=watercycle"`

but I don't know if the qos specification will also apply to subsequent automatic resubmissions. 

I tried editing `env_batch.xml` to add

`<arg flag="-q" name="watercycle"/>`

or

` <directive> --qos=watercycle</directive>`

but neither one has an effect.

**Comment by jedwards4b** [comment]
So if you are editing env_batch.xml you should run ./case.setup --reset and then
./preview_run should show the flag ou (if you use the arg method) and the .case.test (or case.run) script should show the directive.  To apply to all cases you need to make this change in config_batch.xml instead.

**Comment by golaz** [comment]
@jedwards4b : I tried the following.

Edited `env_batch.xml` to add --qos flag:

```
    <submit_args>
      <arg flag="--time" name="$JOB_WALLCLOCK_TIME"/>
      <arg flag="-p" name="$JOB_QUEUE"/>
      <arg flag="--qos" name="watercycle"/>
      <arg flag="--account" name="$PROJECT"/>
    </submit_args>
```

followed by

```
./case.setup --reset
./preview_run
```

The added --qos flag does not show up:

```
    SUBMIT CMD:
      sbatch --time 24:00:00 -p slurm --account e3sm .case.run --resubmit
```

**Comment by golaz** [comment]
In addition to not accomplishing what I intended, running

`./case.setup --reset`

forced me to rebuild the model before submitting next time.

**Comment by jedwards4b** [comment]
Rebuilding the model in this case should have been basically a noop.
I was able to reproduce the issue and will look into it.

**Comment by golaz** [comment]
Thanks. The rebuilding went pretty fast indeed (193 s).

**Comment by jedwards4b** [comment]
As a workaround, and assuming that you want to port the code to this system and not just the case:  Editing the config_batch.xml and adding the argument works correctly.  This requires creating a new case.

**Comment by jedwards4b** [comment]
@golaz It turns out that last statement is not true.   I can do:
```
<submit_args>
  <arg flag="-qos=watershed"/>
</submit_args>
```
in either config_batch.xml or env_batch.xml and that works fine.   I was also able to add the 
```<directive> --qos=wathercycle</directive> ``` to env_batch.xml and after running ./case.setup --reset I see the directive in the .case.run script.

**Comment by golaz** [comment]
@jedwards4b : indeed, the following worked for me

```
    <submit_args>
      <arg flag="--time" name="$JOB_WALLCLOCK_TIME"/>
      <arg flag="-p" name="$JOB_QUEUE"/>
      <arg flag="--account" name="$PROJECT"/>
      <arg flag="--qos=watercycle"/>
    </submit_args>
```

and I did not have to do a

`./case.setup --reset`

Thanks for helping me figure out the proper syntax since it's not particulalrly intuitive:

`<arg flag="--account" name="$PROJECT"/>`

and

`<arg flag="--qos=watercycle"/>`

but **not**

`<arg flag="--qos" name="watercyle"/>`

You can close this ticket unless you think something in CIME should be changed.

**Comment by jedwards4b** [comment]
You are correct, the usage here is not intuitive, I am going to leave this issue open and change the title.
