### ISSUE TITLE
Add empty "environment_variables" section in env_mach_specific.xml

### ISSUE THREAD

**Issue by bartgol** [ESMCI/cime#3448]
It would be nice if the generated `env_mach_specific.xml` file contained an empty section for user-defined env variables, perhaps with a commented out example. This would allow the user to know exactly how to specify additional env vars.

**Comment by jgfouca** [comment]
This would be for machines that may have little, if anything, in their environment setup in config_machines.xml.

**Comment by WesCoomber** [comment]
Hi Luca I am still learning more about the env_mach_specific.xml generation for each generated case on a specific machine. Could you tell me more about the goal for this task?

So you would like to have the system recognize when a machine listed in config_machines.xml has no entries for "environment_variables", an example of this would be the "oic5" machine. And when the system recognizes this situation it should insert this commented out example into the generated env_mach_specific.xml file located in the case directory. 
``

Am I understanding this correctly?

**Comment by WesCoomber** [comment]
@bartgol @jgfouca  Hi Luca I am still learning more about the env_mach_specific.xml generation for each generated case on a specific machine. Could you tell me more about the goal for this task?

So you would like to have the system recognize when a machine listed in config_machines.xml has no entries for "environment_variables", an example of this would be the "oic5" machine. And when the system recognizes this situation it should insert this commented out example into the generated env_mach_specific.xml file located in the case directory.


Am I understanding this correctly?

**Comment by jgfouca** [comment]
@WesCoomber , yes, that sounds right. The idea is that, if the user wanted to make some temporary env changes in their case, they'd have a template they could follow.

**Comment by WesCoomber** [comment]
@jgfouca There is a Comment object from the Element Tree class. `xml.etree.ElementTree.Comment(text=None)` I have tried to use it to implement the idea but a special comment element can only have a text field, not a tag, and not any child elements. So this is what is produced by the .xml generation system.

`<!--environment_variables-->`

I do have the env_mach_specific.py script correctly detecting if there are no "environment_variables" defined in the machine object and then it makes these two child nodes for the generated env_mach_specific.xml. They are not commented out.

`<environment_variables>`
    `    <env name="NAME">ARGUMENT</env>`
  `</environment_variables>`

**Comment by jgfouca** [comment]
Hi @WesCoomber , 

did you try something like this:

```
the_text = """
<environment_variables>
<env name="NAME">ARGUMENT</env>
</environment_variables>
"""
xml.etree.ElementTree.Comment(text=the_text)
```

**Comment by bartgol** [comment]
How about adding an environment variable that is just a placeholder, but unlikely to clash with a real variable. What about `E3SM_VERSION=X.Y.Z` or something like that? Or even better, `E3SM_ENV_VAR_HELP="User can add specific env vars in this xml section".

Unlikely to class with anything important, but still make the section non-empty, which I understand it's easier to implement than a commented xml section.

**Comment by jedwards4b** [comment]
You could also undefine a variable:
<env name="Fred"/>

**Comment by WesCoomber** [comment]
@jgfouca @bartgol @jedwards4b 
Thank you for the suggestions. I looked more into doing Jim Foucar's comment and it looks good:

<img width="1003" alt="Screen Shot 2020-03-31 at 12 14 32 AM" src="https://user-images.githubusercontent.com/10535300/77993738-f44d3800-72e5-11ea-994b-c60e6f24fefb.png">



I also implemented Luca's good ideas:
<img width="1001" alt="Screen Shot 2020-03-31 at 12 08 05 AM" src="https://user-images.githubusercontent.com/10535300/77993734-f3b4a180-72e5-11ea-87e8-da1526b16640.png">
Commented out.
<img width="1002" alt="Screen Shot 2020-03-31 at 12 01 10 AM" src="https://user-images.githubusercontent.com/10535300/77993730-f1eade00-72e5-11ea-9304-e51de83f2c40.png">

Jim Edward's good idea too: 
<img width="999" alt="Screen Shot 2020-03-31 at 12 10 10 AM" src="https://user-images.githubusercontent.com/10535300/77993735-f44d3800-72e5-11ea-9fea-f4100d31ba05.png">

@bartgol You opened up the GitHub issue-- do you have a preference?

**Comment by jedwards4b** [comment]
Nice work @WesCoomber .   I prefer the first one.

**Comment by bartgol** [comment]
Even though I proposed option 2, I am now leaning toward option 1. Perhaps, at the risk of being extra verbose, in the comment we could add a line saying something like 

"This section is for the user to specify any additional machine-specific env var, or to overwite existing ones. For instance, if you want to try a different installation of netcdf-c than the one already set for this machine (if any), you could set the NETCDF_C_PATH env var here."

I'm not 100% sure what I wrote is correct; in particular, is it true that env_mach_specific overwites vars already set in config_machine/compilers ? It would be neat, and a legit scenario (try a different tpl/compiler version without changing machine files).

**Comment by jedwards4b** [comment]
@bartgol  I agree with adding a comment about how to use this section.  But config_compilers.xml is read after config_machines.xml and so this would not overwrite something set there, but (although you can) you shouldn't set paths in config_compilers.xml.    The environment variables are read after the modules are set so you could use an environment variable to override a module setting, but in most cases it seems to me you would just remove the load of the module instead of loading it and then overwriting it.  If you want to set an environment variable just for a given case and not generally for a machine it's not clear to me why you would not just set it in your shell.   This addition is good in terms of clarifying usage and documentation, but the use-cases for actually adding an environment variable to an existing case in this way seem to me to be pretty limited.

**Comment by bartgol** [comment]
@jedwards4b the whole point for me to bring this up was to be able to use the linux-generic machine, which has no tpl paths set in config_machines. I was hoping to put a more generic example in the comment, in case this was useful for more than just linux-generic, but, as you pointed out, its use cases are quite limited.

I'm ok leaving just the first sentence in the comment.

**Comment by jedwards4b** [comment]
@bartgol Are you aware that you can copy the linux-generic machine definition (config_machines.xml, config_compilers.xml, config_batch.xml) to 
$HOME/.cime/   and customize it for your system?

**Comment by bartgol** [comment]
No I didn't know that. But why wouldn't one just work on env_mach_specific.xml? It seems a bit more intuitive. Would what you propose have an advantage over the env_mach_specific option?

**Comment by jedwards4b** [comment]
If you do that you can make the change for all cases and not just the current one.   It also allows you to update cime and keep your machine definition intact.   And yes using this you can define different compilers and/or mpilibs as well.

**Comment by bartgol** [comment]
@jedwards4b I tried to copy config_machines.xml to ${HOME}/.cime/, and added a new entry for my machine (marzemino). But when running create_newcase specifying marzemino as machine, it says

```
Could not find machine match for 'localhost.localdomain' or 'marzemino'
```

**Comment by jedwards4b** [comment]
Your copy of config_machines.xml can be just a single entry and not a copy of the entire file.   Did you use the --machine argument to create_newcase?  If you don't use the --machine argument then you need to find a REGEX statement that matches your machine name.

**Comment by bartgol** [comment]
Ah, I think the error was indeed b/c I copied the whole file, duplicating some entries (e.g., it complained about `default_run_suffix` being duplicated). Thanks!
