### ISSUE TITLE
mct index error on 1 cpu workstation

### ISSUE THREAD

**Issue by rgknox** [ESMCI/cime#3450]
I'm running single grid-cell simulations in E3SM  on a linux workstattion with 1 land gridcell.  Workstation is "eddi" in the machine files, this uses no batch system.

I've recently encountered the following error during my tests:

At line 2528 of file /home/rgknox/E3SM/cime/src/externals/mct/mct/m_GlobalSegMap.F90
Fortran runtime error: Index '1' of dimension 1 of array 'last_index' above upper bound of 0

Inside the offending routine:  comp_id = 5 and nprocs = 0

log:
[e3sm.log.200312-190230.gz](https://github.com/ESMCI/cime/files/4328013/e3sm.log.200312-190230.gz)

Other information:   The RES on this run is actually CLM_USRDAT (1 grid point), I could also provide the domain and surface files, or other information requested.

Any ideas on what is going wrong would be appreciated.

**Comment by ekluzek** [comment]
It sounds like at the point of the error, it thinks there are zero processors rather than 1. Make sure the PE layout has one task for each component.

I'd also suggest to try building it with MPILIB=mpi-serial so it's a simpler configuration.

**Comment by rgknox** [comment]
Thanks @ekluzek.  Running as a serial job seems to work. (why didn't I think of that....)

I've been specifying my PE layout with commands like this, sometimes I had played around with running the datm on a different rootpe.  
```
./xmlchange NTASKS_ATM=1
./xmlchange NTASKS_CPL=1
./xmlchange NTASKS_GLC=1
./xmlchange NTASKS_OCN=1
./xmlchange NTASKS_WAV=1
./xmlchange NTASKS_ICE=1
./xmlchange NTASKS_LND=1
./xmlchange NTASKS_ROF=1
./xmlchange NTASKS_ESP=1
./xmlchange ROOTPE_ATM=0
./xmlchange ROOTPE_CPL=0
./xmlchange ROOTPE_GLC=0
./xmlchange ROOTPE_OCN=0
./xmlchange ROOTPE_WAV=0
./xmlchange ROOTPE_ICE=0
./xmlchange ROOTPE_LND=0
./xmlchange ROOTPE_ROF=0
./xmlchange ROOTPE_ESP=0
./xmlchange NTHRDS_ATM=1
./xmlchange NTHRDS_CPL=1
./xmlchange NTHRDS_GLC=1
./xmlchange NTHRDS_OCN=1
./xmlchange NTHRDS_WAV=1
./xmlchange NTHRDS_ICE=1
./xmlchange NTHRDS_LND=1
./xmlchange NTHRDS_ROF=1
./xmlchange NTHRDS_ESP=1
```

**Comment by jedwards4b** [comment]
@rgknox You can shortcut those commands with
./xmlchange NTHRDS=1   which will change all component NTHRDS to the same value, true also for NTASKS and ROOTPE
