### ISSUE TITLE
Git CIME5 working on Mira

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#346]
The current master (cime5.0.5-23-ge7b334e) fails at runtime when submitting the cime_developer test suite using create_test. Creating/Running a new case using create_newcase works fine.

**Comment by jayeshkrishna** [comment]
Testing potential fixes on Mira/Cetus.

**Comment by jayeshkrishna** [comment]
The above commits gets cime_developer running on Cetus/Mira (except the mpi-serial test - we have always ignored the mpi-serial tests on Mira because mpi-serial library no longer compiles on Mira)
