### ISSUE TITLE
Guidelines for marking review comments as resolved

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3461]
I like GitHub's feature to mark review comments as resolved, but I feel like it can be a double-edged sword. I tend to be a pretty anal reviewer (have you noticed?) and I generally don't approve a PR until I am satisfied that all of my review comments have been addressed. The job of keeping track of which comments have been addressed can be made easier by marking comments as resolved, but this only works well for me if I'm the one who marks my own comments as resolved.

In CTSM, we experimented with both having the PR author be the one to mark comments as resolved and having the PR reviewer (i.e., the original commenter) being the one to mark comments as resolved. I've been finding the review process much smoother if we stick with the latter - i.e., the person who starts a comment thread is the one who should mark that thread as resolved. There are certainly arguments both ways, which basically come down to whether you want to make things more convenient for the PR author or for the PR reviewer. But I feel that reviewing is already such a time consuming and (frankly) unrewarding activity that we should err on the side of making things easier for the reviewer. And I have found that doing it this way makes my job as reviewer significantly easier, whereas doing it the other way only makes my job as an author marginally easier.

How do people here feel about this? Would you be okay having a guideline that  the original commenter is the one who should mark comments as resolved? Unfortunately there is no way to enforce this, but if we're consistent about reminding people of this guideline for a little while, I think we could get fairly consistent in its application.

**Comment by ekluzek** [comment]
Personally, I agree with this approach. If you start a comment, you should check that it's been fixed and then mark it as resolved. The author can (and should) mark that they've addressed it, but the reviewer should check. It's possible in something complex that the author thinks they addressed the issue -- but didn't really.

**Comment by billsacks** [comment]
On cime telecon there was general agreement to this.
