### ISSUE TITLE
Change sst_aquap11 to sst_aquap_constant

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#3466]
For some reason the following mod is not in cime5.8.18.  Please change sst_aquap11 to sst_aquap_constant in the two locations.

![image](https://user-images.githubusercontent.com/10714463/78054762-c7c60a00-733f-11ea-90bc-083b542d4fdb.png)

**Comment by whannah1** [comment]
So this got reverted somehow?

**Comment by fischer-ncar** [comment]
When maint5.6 was merged back to master, there was several conflicts.  Some of the conflicts weren't
fixed properly.

**Comment by billsacks** [comment]
It looks like this was fixed in https://github.com/ESMCI/cime/pull/3469 but it didn't auto-close.
