### ISSUE TITLE
ERIO_Ln11.f09_g16.X fails due to missing summary string in cprnc output

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#3474]
This issue is reproducible on anlworkstation and Cori.

On Cori, TestStatus shows:
```
  ERIO_Ln11.f09_g16.X.cori-knl_intel (Overall: FAIL) details:
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel CREATE_NEWCASE
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel XML
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel SETUP
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel SHAREDLIB_BUILD time=132
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel MODEL_BUILD time=17
    PASS ERIO_Ln11.f09_g16.X.cori-knl_intel SUBMIT
    FAIL ERIO_Ln11.f09_g16.X.cori-knl_intel RUN time=105
```
At the end of TestStatus.log the error message is:
`ERROR: Did not find an expected summary string in cprnc output`

ERI_Ln9.f09_g16.X has the same issue.

**Comment by jgfouca** [comment]
I was not able to reproduce this on melvin. I think that anlworkstation and cori must be using ancient versions of cprnc that predate the summary output.

**Comment by dqwu** [comment]
@jgfouca
Thanks for the information.

anlworkstation:
    <CCSM_CPRNC>/home/climate1/acme/cprnc/build/cprnc</CCSM_CPRNC>
Cori:
    <CCSM_CPRNC>/global/cfs/cdirs/e3sm/tools/cprnc.cori/cprnc</CCSM_CPRNC>

It seems that the cprnc executable does not support "--version" flag.

To build a custom version of latest cprnc tool, should I refer to the following link?
https://github.com/ESMCI/cime/tree/master/tools/cprnc

I can try modifying CCSM_CPRNC to test the custom version on anlworkstation.

**Comment by jgfouca** [comment]
@dqwu , cime now has the ability to build cprnc on-the-fly if CCSM_CPRNC is not available. I think the easiest thing to do would be to temporarily change the CCSM_CPRNC to a non-existent path on these machines, let cime build cprnc, and then copy the fresh build into the original CCSM_CPRNC path. I can try to help with this since this is a new feature and has not been widely tested.

**Comment by rljacob** [comment]
Looking at the timestamp on the executable:
compute001:  Oct 7, 2016
cori:  Jul 6, 2016

@ndk can you rebuild the cprnc executable on cori with latest source?

**Comment by dqwu** [comment]
@amametjanov 
Could you please update the cprnc executable for anlworkstation? Thanks.
```
/home/climate1/acme/cprnc/build
-rwxr-xr-x 1 azamat   climate 10685432 Oct  7  2016 cprnc
```

**Comment by dqwu** [comment]
@jgfouca 

I followed your steps on anlworkstation to let cime build cprnc but there are some build errors:
```
tools/cprnc/filestruct.F90:2:6:

   use netcdf
      1
Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
..
ERROR: tools/cprnc/filestruct.F90:2:6:

   use netcdf
      1
Fatal Error: Cannot read module file    netcdf.mod    opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
```
However, manually build cprnc has no build errors.
```
// run from the directory cime/tools/cprnc
CIMEROOT=../.. ../configure --macros-format=Makefile --mpilib=mpi-serial
CIMEROOT=../.. source ./.env_mach_specific.sh && make
```

**Comment by jedwards4b** [comment]
gnu is very picky about gfortran module versions - you need to make sure that the version used to build netcdf is the same as what you are using for cprnc

**Comment by dqwu** [comment]
@jgfouca 
I used a manually built cprnc to rerun the test on anlworkstation, TestStatus shows:
```
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu CREATE_NEWCASE
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu XML
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu SETUP
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu SHAREDLIB_BUILD time=70
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu MODEL_BUILD time=12
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu SUBMIT
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu RUN time=331
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf_netcdf.pnetcdf
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf_netcdf.netcdf4p
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf_netcdf.netcdf4c
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf_netcdf.nothing
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_pnetcdf_pnetcdf.netcdf4p
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_pnetcdf_pnetcdf.netcdf4c
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_pnetcdf_pnetcdf.nothing
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf4p_netcdf4p.netcdf4c
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf4p_netcdf4p.nothing
FAIL ERIO_Ln11.f09_g16.X.anlworkstation_gnu COMPARE_netcdf4c_netcdf4c.nothing
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu MEMLEAK insuffiencient data for memleak test
PASS ERIO_Ln11.f09_g16.X.anlworkstation_gnu SHORT_TERM_ARCHIVER
```
There are some DIFFs, but the error "Did not find an expected summary string in cprnc output" is gone now.

**Comment by jgfouca** [comment]
@dqwu , great. Please blow-away the CCSM_CPRNC area and replace the files there with your newly built cprnc.

**Comment by dqwu** [comment]
@amametjanov 
Thanks for updating cprnc. However, the new version still does not work:
Exception from case_test: ERROR: Did not find an expected summary string in cprnc output:

Use the one built by cime on-the-fly (temporarily change the CCSM_CPRNC to a non-existent path)
seems to work.

I also noticed that your new version (or the old one) is static (not a dynamic executable), but the one automatically built by cime is dynamic.

**Comment by dqwu** [comment]
@jgfouca 
By default, the cprnc built by cime on-the-fly on anlworkstation is a dynamic executable. Do you know how to make cime build a static one instead?

**Comment by dqwu** [comment]
@amametjanov 
I have tested your latest cprnc executable (static) on anlworkstation and it works now.

**Comment by jgfouca** [comment]
@dqwu , that's a great point. We want the cprnc executable to be as static as possible so that it will work regardless of what modules are currently loaded. Let me do another PR real quick.

**Comment by dqwu** [comment]
@jgfouca 
Most cime_developer tests look good now on anlworkstation.

For ERI_Ln9.f09_g16.X and ERIO_Ln11.f09_g16.X, they still have DIFFs on anlworkstation.
Are these DIFFs reproducible on melvin?

```
  comparing model 'cpl'
    ERI_Ln9.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0003-01-01-14400.nc.base did NOT match ERI_Ln9.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0003-01-01-14400.nc.hybrid
    cat /sandbox/jenkins-ci/workspace/CIME_SCORPIO_CLASSIC/acme/scratch/ERI_Ln9.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx/run/ERI_Ln9.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0003-01-01-14400.nc.base.cprnc.out
FAIL
```
```
  comparing model 'cpl'
    ERIO_Ln11.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0001-01-01-19800.nc.netcdf did NOT match ERIO_Ln11.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0001-01-01-19800.nc.netcdf.pnetcdf
    cat /sandbox/jenkins-ci/workspace/CIME_SCORPIO_CLASSIC/acme/scratch/ERIO_Ln11.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx/run/ERIO_Ln11.f09_g16.X.anlworkstation_gnu.20200409_124443_q6m6bx.cpl.hi.0001-01-01-19800.nc.netcdf.cprnc.out
FAIL
```

**Comment by jgfouca** [comment]
@dqwu , yes; i see them on melvin too.

**Comment by dqwu** [comment]
@jgfouca 
Thanks for your information. This issue can be closed since cprnc has been updated for anlworkstation (it also needs to be updated for Cori).
