### ISSUE TITLE
Add a Code of Conduct to cime

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3476]
It would be good for CIME to have a Code of Conduct (COC) for expected behaviors

Because the maint5.6 branch is solely CESM, we should probably adopt the standard UCAR COC 
which has a DOI here: https://doi.org/10.5065/6w2c-a132. I'll probably give a PR for that directly.

The question is what should a COC looks like for CIME as a whole on master? It possibly should be more expansive than the UCAR one. The UCAR talks about how to report on issues to UCAR resources (such as the Office of Diversity and Inclusion, Human Resources, and Ethics and Legal). Those resources can be involved even for issues involving people outside of UCAR. But, possibly reporting should be more expansive for CIME with a significant set of people outside UCAR.

Having a  COC in each repository is a github best practice. It's something that NSF wants all of its projects to have. And it's a good idea in order to have  and maintain diversity and inclusion in a project. It helps everyone on a project to be more productive, by having expectations on behavior that encourage everyone to be respectful and understanding with each other.

**Comment by billsacks** [comment]
@ekluzek thanks for starting this discussion and for taking the lead on adding codes of conduct to various repositories. I agree that we should have a code of conduct in the cime repository, though I don't have opinions on what it should look like.

However, I don't think it makes sense to have a different code of conduct on the maint-5.6 branch. We should adopt a single code of conduct in cime that applies across all branches. I think that the most likely time that code of conduct issues will come up is in issue and PR comments, and for those, you'll get linked to the code of conduct version on master, so I don't think it makes sense to have a different version on different branches.

**Comment by ekluzek** [comment]
Ahh, good point. That makes sense to me to have one on master that applies to all branches.
