### ISSUE TITLE
Idea for building a component library on an unsupported machine by creating a cime port on the fly: is this a boneheaded thing to do?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3489]
### Introduction

I'm opening this discussion issue (1) to get feedback from others - especially @jedwards4b and @jgfouca - on whether this seems like a boneheaded thing to do, and (2) to share the idea with others in case it seems genius rather than boneheaded :-)  (Actually, if it turns out to be genius, @jedwards4b gets much of the credit, because he encouraged us months ago to leverage the cime build system as much as possible, so really I've just been thinking about how we can take his suggestion.)

Please let me know if you have thoughts on whether this is a good / bad idea, and if you have any ideas for how I could do this more easily than what I'm suggesting.

Most of the code for my proposal would live outside of cime, at least initially, though I could move it into cime if others would find it useful. However, I might need to make some small changes to cime to support this workflow.

### Overview of the problem

The problem I'm trying to tackle is to put together a build script for https://github.com/escomp/ctsm that will allow people to build and link to CTSM and its dependencies (which include mct, gptl, pio and the share code) without knowing anything about cime. In particular, they should not need to know about the create_newcase, case.setup, case.build sequence, and they should not need to know how to do a cime port.

### The original, tentatively discarded plan

**(I'm including this section for some context, but you can skip it if you want.)**

We had been planning to do this by creating a CMake-based build system, which would build the various libraries of cime and then build the CTSM library. In contrast to the E3SM CMake-based build (if I understand that correctly) this one would be more independent of the cime scripting infrastructure, for example, not reading the `config_machines` and `config_compilers` xml files, because the idea is that this would be usable on a machine that does not appear in these files.

However, as I started down this path, I started to realize how challenging it's going to be to get all of the compiler flags set correctly for each library's build. This is especially an issue for CPP tokens that are needed by various libraries. With enough careful analysis, I could probably get this working, but maintaining it long-term could be painful and error-prone: If any new CPP definitions are added in the future, I would need to be sure to add the appropriate logic for these tokens in the CMake-based build we were maintaining. Something like #3226 would help, but it might be a lot of work to do this robustly.

My basic conclusion was: creating and maintaining a parallel build system feels like a bad idea, particularly if that parallel build system is only used by a small number of people (so I have to be the one to maintain it).

### My new thought, which I'd like feedback on

I went back to the drawing board, considering what our real needs are. As noted above, we really just want a way to hide cime from users. But, I thought, can't we still leverage cime's build system while hiding that from users?

My basic idea is: I could create a script that:

1. Given a few arguments, creates a cime port of a given machine/compiler on the fly. Assuming all we need cime for is to build the case, not to run it; and further assuming that the user has already loaded an appropriate module environment: I think this port would be pretty easy to create, just requiring filling in a few entries in a `config_machines.xml` and `config_compilers.xml` file. I would create these two xml files on the fly in a temporary `.cime` directory (I may need to extend cime to be able to point to a directory in an arbitrary location, rather than assuming `~/.cime`).

2. Invisibly to the user, does the create_newcase, case.setup and case.build steps needed to have cime build the CTSM library and its dependencies.

### Details of the on-the-fly cime port

Looking through `config_machines.xml` and `config_compilers.xml`, I believe the wrapper script would just need to fill out the following in order to create a minimal on-the-fly cime port that should be sufficient for building the model (other xml variables could be left at some unused placeholder value):

**In config_machines - a few required and optional arguments to the wrapper script**
- OS: LINUX, AIX, Darwin, CNL (required argument to wrapper script)
- Compiler: e.g., intel, gnu, nag, pgi (required argument to wrapper script)
- MPILIB: e.g., mpt, openmpi, impi (required argument to wrapper script)
- GMAKE (optional argument to wrapper script; defaults to gmake)
- GMAKE_J (optional argument to wrapper script; defaults to something like 8)

**In config_compilers - various optional arguments to the wrapper script that would allow setting:**
- CPPDEFS for gptl: It looks like many systems use a certain set of flags that turn on nano timers. We could provide a single optional argument which, if provided, would add all of these gptl CPPDEFS to the on-the-fly `config_compilers.xml`.
- `NETCDF_PATH`: I need to do a little more research on when this one is needed, but it seems like we may need to set this optionally
- `PIO_FILESYSTEM_HINTS`: This can optionally be set to gpfs or lustre, which presumably aids with PIO performance
- `PNETCDF_PATH`: This can optionally be set
- Any extra CFLAGS and FFLAGS, provided explicitly by the user (for example, on cheyenne, we use `-qopt-report -xCORE_AVX2 -no-fma`)

Note that I do NOT plan to set anything about the module system or environment variables in `config_machines.xml`. The assumption is that the user would have already loaded the appropriate modules and set any necessary environment variables before running this wrapper script. Then cime wouldn't do anything with the module environment on the machine - just leaving things as they have already been set. (This feels like what would be typical for building libraries using standard build systems without the help of cime.)

**Comment by jedwards4b** [comment]
I think that the next step is to develop a GUI for cime.

**Comment by jgfouca** [comment]
I think that would work and improve usability on machines that are not officially supported (not in config_machines).

**Comment by rljacob** [comment]
I don't think you want to try and make a cime port on the fly if you mean auto-add correct lines to config_machines, config_compilers.

What we should have is an option to just build with "configure; make".   If you have fortran compilers and mpi/netcdf libs installed, configure can find them and then you can just build.  (or the cmake equivalent of that process).

**Comment by jedwards4b** [comment]
We use the xml config files specifically because autoconf and cmake were not adequate to fit our needs - introducing one of these at this time may make things easier for a small subset of systems but increases the burden on developers to support new build methods.  The majority of the problems we see posted on the forums are due to users who do not RTFM.  I know that you are trying to improve things but this won't solve that problem.

**Comment by rljacob** [comment]
Ok after reading Eric's post (instead of just the title and comments) I see creating a config_compilers/config_machines is exactly what he wants to do.   Doing it in HOME/.cime is a good idea.   The end user may have trouble getting all those items on the command line for this tool.

Note that HOMME-in-E3SM does have a separate cmake system for building homme standalone.  It uses pio and gptl from cime but not the CCS.  It does wind up requiring you to maintain the equivalent of config files.  See https://github.com/E3SM-Project/E3SM/tree/master/components/homme/cmake/machineFiles

**Comment by rljacob** [comment]
For "Invisibly to the user, does the create_newcase, case.setup and case.build steps needed to have cime build the CTSM library and its dependencies."  Do you only need to build one compset for this to be useful?

**Comment by billsacks** [comment]
Thanks for your replies. My own replies to a few of them:

@jedwards4b -
> I think that the next step is to develop a GUI for cime.

Hmmm, I won't argue that that could be useful, but I'm struggling to see how it connects with this idea. The biggest contribution of this idea is to create a cime-port-on-the-fly for the sake of building the model, which I'm thinking (hoping) will be simple enough to do that it won't require a gui.

@rljacob -
First, note that it's me, not Erik.

I'm not quite sure what your thoughts are at this point, but I will respond a bit to your suggestion (which you may have rescinded) of allowing for a standard "configure; make" or "cmake; make" build of (some of) the cime components: I do think this could be valuable, but I think this would be a fairly substantial undertaking that would require significantly more discussion. (I am still not that familiar with E3SM's cmake-based build, but my impression is that it still doesn't allow something like this... but @jgfouca or others can correct me if I'm wrong.) Off-hand, the way I could see this working is having a fairly standard cmake-based build at the lower level of the build system. This could be used with a simple "cmake; make" workflow, or you could use the full cime machinery to put a layer on top of this; this extra layer would use the machine-specific information to set the appropriate arguments to cmake (rather than requiring the user to set all of the necessary cmake arguments by hand). Then people using the cime workflow could take advantage of cime's nice mechanisms for machine ports, whereas people wanting to build cime's Fortran code on an unsupported machine could run "cmake; make" by hand – and the two would use the same build system underneath. A key part of this in my mind is that last piece: **the two would use the same build system underneath**: I'm feeling like it's a bad idea to try to maintain two different build systems, with duplicate logic for setting the various needed CPP tokens, etc.

> Do you only need to build one compset for this to be useful?

Yes, for the most part. Much of what makes this easier for CTSM is that CTSM itself is completely runtime configurable. At some point we'll need to extend it to give the user the option for whether to include a river model (and which one), but other than that, I think that a single arbitrary, hard-coded `I` compset will be sufficient.

**Comment by billsacks** [comment]
I'm going to give this a shot; closing this discussion issue. Thanks for your feedback.
