### ISSUE TITLE
Add command-line flag to specify alternate location custom machine files, rather than ~/.cime

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3493]
Connected with #3489 , I'd like to add a command-line flag to create_newcase and create_test that lets you specify the location of the .cime directory, rather than assuming it's in your home directory.

**Comment by billsacks** [comment]
One thing that will be hard to fix is the `set_compiler` function in `utils/perl5lib/Config/SetupTools.pm`. However, I can't find any uses of that old perl function from anywhere in cime, or from anywhere in the CESM or E3SM code bases for that matter. So I plan to just remove that function.

**Comment by rljacob** [comment]
Instead of an alternate path for the .cime, should it be an option for a completely different path/name?

**Comment by billsacks** [comment]
> Instead of an alternate path for the .cime, should it be an option for a completely different path/name?

Yes, good point - I'll do that.

**Comment by jedwards4b** [comment]
Sorry Bill but I don't understand - what's wrong with the $HOME/.cime location?

**Comment by billsacks** [comment]
> Sorry Bill but I don't understand - what's wrong with the $HOME/.cime location?

I'm building a wrapper tool that creates a cime port on the fly. The easiest way I can see to do this is to create `config_compilers.xml` and `config_machines.xml` files on the fly (see #3489 for more details). I'd like this on-the-fly port to live in a case-specific location, because (1) I don't want to clobber anything in the user's existing `.cime` directory, and (2) I wouldn't want different cases to clobber each other's settings.

**Comment by billsacks** [comment]
I'm realizing, though, that I can't totally replace the use of the `~/.cime` directory: the cime config file that lives there is read even before arguments to `create_newcase` are parsed. So this location will just give the directory containing the machine-port files (config_compilers.xml, config_machines.xml, config_batch.xml).

**Comment by billsacks** [comment]
I'm thinking of calling this argument `--user-machines-dir`. If given, this will give the path to the directory in which the user-specified `config_machines.xml`, `config_compilers.xml` and `config_batch.xml` files can be found. Note that I am NOT including the `config_workflow.xml` file in this list: it feels most intuitive and useful to limit this to the location of machine porting files. (It seems to me like the machine porting files are fundamentally different from the workflow file: the former will typically be the same for every case a user creates on a given machine, whereas it seems like the latter will often differ from case to case. So if we provide a mechanism like this for the workflow file, it seems like it should use a different argument from the directory for the machine porting files.)

**Comment by billsacks** [comment]
I decided that it makes sense to have this new directory be additional to any `~/.cime` directory: I felt that was more intuitive and more useful than ignoring the `~/.cime` directory. I am calling the new command-line flag `--extra-machines-dir`. See 370ce1d1b for details. I will open a PR once I add a test for this behavior in scripts_regression_tests (as long as doing so doesn't prove to be too difficult).
