### ISSUE TITLE
Add grids for fv3 C24, C48, C192, C384

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3497]
For the fv3 project, the C96 grid is already added. But, C24, C48, C192, and C384 should be added. Or the capability of running them through a user-mods directory added.

**Comment by ekluzek** [comment]
Note, unless mapping files to ocn, rof, or glc are provided these grids should be marked: compset="_SICE_SOCN_SROF_SGLC"

**Comment by jtruesdal** [comment]
@ekluzek.  I think all of this was addressed with PR 3415 which was  accepted.
https://github.com/ESMCI/cime/pull/3415/files

**Comment by ekluzek** [comment]
Yes, you are right. And mapping files for rof, glc, and ocn are provided so no restrictions on compsets need to be done.

**Comment by jtruesdal** [comment]
Can I close this?

**Comment by ekluzek** [comment]
Yes, you could. If I understand github I think it will auto-close with #3415 because I added a fixed in line for it, and github connected the two. But, you could close it and the other one one if you prefer.

**Comment by jtruesdal** [comment]
Thanks for letting me know.  I haven't had much experience with github yet
and am not sure of next steps.  I will close them.

jt
