### ISSUE TITLE
scorpio / titan specific flags should not be in Makefile

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3500]
These lines https://github.com/ESMCI/cime/blob/master/scripts/Tools/Makefile#L301 in the general Makefile should be moved to the sorpio buildlib script and only applied for the machine or machines they are needed on.  As currently set they invoke a non-standard and possibly slower communication method on all systems for the sake of a single buggy implementation.

**Comment by jayeshkrishna** [comment]
Ok, I will work on moving these flags from the generic Makefile.

**Comment by jayeshkrishna** [comment]
Adding the lines in the generic Makefile (\<CIME\>/scripts/Tools/Makefile) here for reference
```
# Atleast on Titan+cray mpi, MPI_Irsends() are buggy, causing hangs during I/O
# Force PIO to use MPI_Isends instead of the default, MPI_Irsends
ifeq ($(PIO_VERSION),2)
  EXTRA_PIO_CPPDEFS = -DUSE_MPI_ISEND_FOR_FC
else
  EXTRA_PIO_CPPDEFS = -D_NO_MPI_RSEND
endif
```

**Comment by jayeshkrishna** [comment]
@jedwards4b : Do CESM (PIO) users care about this flag (using MPI_Isends instead of MPI_Irsends by default)? If not, we probably don't need any further changes to CIME.

**Comment by jedwards4b** [comment]
I think you are confused wrt 3499, the lines were not removed, they just needed to be in a different place in the file. https://github.com/ESMCI/cime/blob/master/scripts/Tools/Makefile#L130

**Comment by jayeshkrishna** [comment]
ok, thanks. We could remove the lines from the Makefile if CESM (PIO) users don't need it.
