### ISSUE TITLE
query_config seem to be broken

### ISSUE THREAD

**Issue by fvitt** [ESMCI/cime#3501]
In cime5.8.20 query_config seem to be broken:
Invoked as "query_config --compsets" gives error messages such as:
  element entry: Schemas validity error : Element 'entry': Character content other than whitespace is not allowed because the content type is 'element-only'.

This is on cheyenne.

**Comment by jedwards4b** [comment]
@fvitt, I just tried on cime5.8.20 and on cime master and it's working fine.

**Comment by jedwards4b** [comment]
Perhaps you have an invalid compset definition in your component branch?

**Comment by fvitt** [comment]
@jedwards4b is correct.  I had errors in cam's config_compsets.xml.
Thanks.
I will close this issue.
