### ISSUE TITLE
Request for guidelines on what should go in different classes in scripts_regression_tests

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3504]
I wanted to run just a subset of scripts_regression_tests on my mac – specifically, `K_TestCimeCase`. At a glance, I thought this would just run some fairly limited tests that should be pretty quick. However, one test in there – `test_self_build_cprnc` – does a full system test run, taking a relatively long time and downloading a bunch of data.

This made me think that it would be good to have some guidelines on what types of tests are and aren't in the different classes in scripts_regression_tests, both (1) to help keep this file somewhat organized, and (2) to facilitate running a subset of tests. Crucially, I'd argue that all full system tests should be separated from the smaller tests.

**Comment by jgfouca** [comment]
I agree. I'll be the first to admit that I have not always been diligent about this. K_TestCimeCase has been a bit of a catch-all for me when I can't decide where to put something. I've always interpreted this class as testing core case-control mechanics, but that's pretty broad.
