### ISSUE TITLE
case.py get_value() method returns error for item=JOB_QUEUE, subgroup=case.run

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#3507]
Using cime5.6.19, (release-cesm2.1.1), I'm getting the following error when calling:

`case.get_value('JOB_QUEUE', resolved=True, subgroup='case.run')`

`The program exited via sys.exit(). Exit status:  ERROR: Multiple matches for nodename 'entry' and attrs '{'id': 'JOB_QUEUE'}' in file '/glade/work/tomas/cases/2deg/b.e21.B1850.f19_g17.8kaControl-2deg_proto.007/env_batch.xml', found 2 matches
`

It works correctly using xmlquery:

```
./xmlquery JOB_QUEUE --subgroup case.run
	JOB_QUEUE: regular
```

**Comment by jedwards4b** [comment]
@bertinia Have you tried with cime5.6.33?  It looks like the env_batch.xml file in that directory is incorrect and I cannot reproduce that with the release candidate cime.  If you can please elaborate.
