### ISSUE TITLE
Global name 'extra_machines_dir' is not defined

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#3512]
Unable to setup any cases.

./create_newcase --case test --compset X --res f19_g16
cd test
./case.setup

Error message is
  File "/glade/u/home/fischer/code/cesm2_nightly_tests/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 122, in _case_setup_impl
    configure(Machines(machine=mach, extra_machines_dir=extra_machines_dir),
NameError: global name 'extra_machines_dir' is not defined

**Comment by jgfouca** [comment]
Ah, there was a conflict resolution problem when I merged my last PR. Fix coming.

**Comment by fischer-ncar** [comment]
Thanks
