### ISSUE TITLE
Support for `--res 1x1_brazil` broken

### ISSUE THREAD

**Issue by bishtgautam** [ESMCI/cime#3518]
@jedwards4b #3492 broke the support for `--res 1x1_brazil`. With the new code, the `gridvalue['atm'] = 1x1_bra` while the `gridvalue['lnd'] = 1x1_brazil`. In E3SM, I created the case via:

```
./create_newcase -case 1x1_brazil.I1850CLM45 -res 1x1_brazil -compset I1850CLM45
```

**Comment by jedwards4b** [comment]
I will refine the match argument to look for z\d.
