### ISSUE TITLE
Excessive memory allocation when using SST data where ordering not expected

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#3523]
During the initialization phase of model simulations with resolution ne256 or finer, we encountered OOM and/or array index out of bounds errors when using new (0.5degx0.5deg) SST files with F compset. The error appears to occur when the ocean data file is regridded to the ocean grid (in OCN init).

We found that the issue stemmed from the ordering of the latitude dimension (yc in the domain file), not the resolution of the ocean dataset. If yc is ordered in descending order (from 90 to -90), it causes problems including:  OOM error and “array index out of bounds” as noted below. 

The SST data file itself:
/global/cfs/cdirs/e3sm/terai/init/domain.ocn.720x361.200428.nc

When the latitude dimension starts at 90, then every destination yd value other than -90 is larger than Ysrc(1,jsize) = -90, triggering the first condition in shr_map_mod.F90:

```
   if (yd > Ysrc(1,jsize)) then
       if (dopole) then
          pnum = isize+2
          pole = 1
       endif
       ysu =  cpole
    elseif (yd < Ysrc(1,1)) then
       if (dopole) then
          pnum = isize+2
          pole = 2
       endif
       ysl = -cpole
    endif
```

leading to all destination points getting treated like points around the north pole. (The second condition also is almost always true, but the first condition is evaluated first.) The interpolation code then switches to its pole treatment. This is to use all 720 points at the polar boundary of the source grid, leading to 722 new weight coefficients instead of bilinear interpolation’s usual 4 weight coefficients. This leads to a steadily increasing ptot, the sum of individual pnum values, that eventually reaches the point of overflowing integer in the higher resolutions. If instead yc is ordered -90 to 90, then Ysrc(1,jsize) is 90 and Ysrc(1,1) is -90, making almost all points non-polar.

Re-ordering/regridding the ocean sst dataset to a grid where the latitude is in ascending order (-90 to 90) solves this issue. Note that the pnum=722 behavior described above also occurs with ne30; however, the sizes of the arrays being resized/allocated is not large enough to cause OOM or segfault (but still ill behavior).

Would it make sense to at least report error or warning message for this situation? For example:

```
diff --git a/cime/src/share/util/shr_map_mod.F90 b/cime/src/share/util/shr_map_mod.F90
index 634c3d33f..59073d2b0 100644
--- a/cime/src/share/util/shr_map_mod.F90
+++ b/cime/src/share/util/shr_map_mod.F90
@@ -2958,6 +2958,10 @@ contains
        if (xsr < xd) xsr = xsr + csize
     endif
 
+    if (Ysrc(1,jsize) < Ysrc(1,1)) then
+       call shr_sys_abort(subName//' ERROR Ysrc(1,:) should be monotonically increasing')
+    end if
+
     if (yd > Ysrc(1,jsize)) then
        if (dopole) then
           pnum = isize+2
```

```
Example error message:
  0: forrtl: severe (154): array index out of bounds
   0: Image              PC                Routine            Line        Source
   0: e3sm.exe           0000000003990E3E  Unknown               Unknown  Unknown
   0: e3sm.exe           00000000031BB540  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000003AA557D  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000001E1E19C  shr_map_mod_mp_sh        1285  shr_map_mod.F90
   0: e3sm.exe           0000000001DE5D7A  shr_dmodel_mod_mp        1522  shr_dmodel_mod.F90
   0: e3sm.exe           0000000001E99609  shr_strdata_mod_m         620  shr_strdata_mod.F90
   0: e3sm.exe           0000000001E9C713  shr_strdata_mod_m         226  shr_strdata_mod.F90
   0: e3sm.exe           0000000001CAD3CF  docn_comp_mod_mp_         185  docn_comp_mod.F90
   0: e3sm.exe           0000000001CA4CDC  ocn_comp_mct_mp_o         155  ocn_comp_mct.F90
   0: e3sm.exe           0000000000424EBF  component_mod_mp_         257  component_mod.F90
   0: e3sm.exe           0000000000412DE0  cime_comp_mod_mp_        1359  cime_comp_mod.F90
   0: e3sm.exe           0000000000421B94  MAIN__                    122  cime_driver.F90
   0: e3sm.exe           0000000000401F6E  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000003AB9C4F  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000000401E5A  Unknown               Unknown  Unknown
   0: forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

**Comment by jedwards4b** [comment]
Yes, please consider a PR with your proposed change.  I think that you are also suggesting updating some input files with the order changed?

**Comment by ndkeen** [comment]
OK. And maybe I wasn't clear, but this was discovered using SST data file that Chris Terai (can't find his github handle at the moment) was experimenting with (ie not yet an official input file). We have not yet verified if there are indeed any files that have this reverse order issue. I suppose I could write a script to check them. Or implement change and see what gets caught.
