### ISSUE TITLE
Start adding support for mizuRoute in CIME

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3528]
We'd like to start adding support for mizuRoute in cime. Minimally this means CIME needs to know where the mizuRoute cime_config files are and what the default resolution is for cime. In time there might also be mizuRoute specific grids that need support.

**Comment by rljacob** [comment]
What is MizuRoute?

**Comment by ekluzek** [comment]
mizuRoute is a river routing model. Misu is water in Japanese, so literally it means water routing. The author's name also starts with Mizu (Mizukami) so it's a nod to the author as well as the Japanese word for water.
