### ISSUE TITLE
python logger debug statements aren't printed when used in "buildlib".

### ISSUE THREAD

**Issue by nusbaume** [ESMCI/cime#3532]
While updating CAM's buildlib script, it was found that `logger.debug` statements are not printed to any file in the case, even if the log level is set to debug in buildlib itself.  However, `logger.info` statements do make it to the `*.bldlog.*` file. 

This seems to hold even if the `DEBUG` variable is set to True in `env_build.xml`, and if the `--debug` flag is provided to `case.build`.  It also doesn't seem to be CAM-specific, as the same behavior happens in CLM's buildlib script as well (although I didn't test other components' buildlib scripts).

I specifically used the CESM `release-cesm2.1.3` tag on Izumi to run these tests (although I ran a similar test on Cheyenne with the same results).

Any ideas as to why this is the happening would be greatly appreciated.  Thanks!

**Comment by jedwards4b** [comment]
The buildlib python script in your cime_config directory should have a subroutine called from main.

def buildlib(case, libroot, bldroot, compname=None):

Doing this should cause this to be called as a subroutine instead of a subprocess and solve the issue.

**Comment by billsacks** [comment]
@jedwards4b I know that you and I came up with the above on our call, but I dug a little more afterwards and I actually don't think that's right. It looks to me like there are separate functions in cime for calling the buildlib for cime's lower-level libraries vs. calling the buildlib for components.

For lower-level libraries (csm_share, etc.), it uses a function call if possible, with arguments `[full_lib_path, os.path.join(exeroot, sharedpath), case]` (from build.py: `_build_libraries`). However, for component builds, it looks like it's using the function `_build_model_thread`, and for that I don't see any logic for calling a component's buildlib as a function. But I may be missing something.

**Comment by billsacks** [comment]
@nusbaume the broader issue seems to be the following (deduced during today's cime call): if a component's buildlib is called as a subprocess, then the logging options don't get passed down. The ideal solution is for a component's buildlib to be called as a python function rather than a subprocess. Our first look at this suggested that this should be possible if you have a correctly-named function, but now I'm thinking that cime's build function needs a little more logic added to do this properly.

**Comment by jedwards4b** [comment]
@billsacks thanks - I'll take a closer look.

**Comment by nusbaume** [comment]
@billsacks @jedwards4b Thanks for the info!  I tried the first suggestion by adding this code to CAM's buildlib main call:

```
if __name__ == "__main__":

    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildlib(case, caseroot, libroot, bldroot, "cam")
```
where the function `buildlib` replaced the original `_build_cam`.  Sadly it didn't seem to fix the issue, which could mean either there needs to be additional logic, or I didn't apply your fix correctly (which seems just as likely).

**Comment by jedwards4b** [comment]
@nusbaume there is something inside cime that needs to be fixed before this will work correctly, but the code change above is heading in the correct direction, it should look like the following,
you want the 'with Case' statement inside the buildlib subroutine. 

def buildlib(caseroot, libroot, bldroot):
    with Case(caseroot) as case:
       ...

if __name__ == "__main__":
    caseroot, libroot, bldroot = parse_input(sys.argv)
    buildlib(caseroot, libroot, bldroot)

**Comment by nusbaume** [comment]
@jedwards4b thanks for the pointer!  I'll wait until I hear about the cime fix, and then try again with the updated `main` statement.

**Comment by jedwards4b** [comment]
@jgfouca I remember the issue here - the buildlib scripts for external components are called from subthreads and there are some variables communicated to the underlying Makefile through the environment,  environment variables are not thread safe and so we broke the feature of calling as a subroutine in order to solve the issue of setting environment variables independently in each thread.   The variables in question are SMP, MODEL, COMP_CLASS and COMP_NAME, how can we rework this so that both features work?   Or alternatively how do we forward the --debug option if used to the buildlib scripts?

**Comment by jedwards4b** [comment]
I tried passing in the --debug flag, verified that it did in fact change the logger level setting and I still don't get output from logger.debug("HERE I AM")

**Comment by WesCoomber** [comment]
@jedwards4b Hi Jim, I got your email and I will take a closer look.

**Comment by WesCoomber** [comment]
I have started working on this issue here: 
https://github.com/ESMCI/cime/tree/wpcoomb/improve_cime_buildlib_function

**Comment by jedwards4b** [comment]
@nusbaume can you see if this fixes your issue?

**Comment by nusbaume** [comment]
@jedwards4b sadly I still seem unable to get debug printing from CAM's buildlib.  I updated my CIME external to the merge of @WesCoomber's additions, made the modifications described above (about replacing `_build_cam` with `buildlib`), created a new case, and then built with the `--debug` flag passed to `case.build`.  I also tried setting the log level directly in `buildlib`, but that didn't work either.

Is there somewhere specific I should be looking (I looked in both the `atm.bldlog.*` and `case.build.log`), or should I be passing or setting a different flag and/or argument?

**Comment by jedwards4b** [comment]
@WesCoomber I also tried this - it's still not working.

**Comment by jedwards4b** [comment]
@WesCoomber @jgfouca I have a branch  
    github.com:jedwards4b/cime.git
   c8181d6a8..e8ab3173f  buildsub -> buildsub
Where I am approaching a solution to this problem.  It now allows run_sub_or_cmd to be called from threads and sends each threads output to a file.   And it's correctly passing the --debug to the buildlib routine. 

So I am redirecting stdout to the log file but it also seems to continue to send it to stdout - this is where I am stuck at the moment.   Maybe you could have a look and also make sure I haven't messed up your cmake build.

**Comment by WesCoomber** [comment]
@nusbaume and @jedwards4b
_I double checked my tests for this subprocess feature and they are still working on Melvin._ 

There are some minor differences in our development environments, such as we use cmake so I pass a --use-old flag to case.build to recreate the correct behavior.

_Could you follow these steps on your machines and let me know if it works for you?_

**Comment by WesCoomber** [comment]
Insert a `logger.debug("wpc.HERE I AM")` statement into _main_func() in E3SM/components/clm/cime_config/buildlib

Then I create a case that uses a compset that includes the external clm component.
`./create_newcase --case ~/cime/wpcClm3 --compset I1850CLM45 --res f19_g16`

I navigate to the case directory and run case.setup, case.build -- clean, and case.build --debug.
`cd /ascldap/users/wpcoomb/cime/wpcClm3`


```
case.setup

case.build --clean
```

(You may not need the --use-old flag on your machine)
```case.build --use-old --debug```

I see my debug statement in here this output log here:
` /ascldap/users/wpcoomb/acme/scratch/wpcClm3/bld/lnd/obj/buildlib.log` 
and the logger level is set correctly to a value of 10.

**Comment by nusbaume** [comment]
Thanks for the instructions @WesCoomber!  I didn't realize there was a `buildlib.log` file in the `<component>/obj` directory, but after looking I was able to find my own debug logging statements there.  

So, I think I am good to go on my end.  Thanks for the help (to both you and @jedwards4b)!

**Comment by jedwards4b** [comment]
@WesCoomber thanks - sorry I didn't find that myself.

**Comment by WesCoomber** [comment]
@nusbaume and @jedwards4b _That is good news and I am glad to hear the solution is successfully working for you. I am closing this issue and marking it as done. I hope you have a good Memorial Day weekend._
