### ISSUE TITLE
Issue with variable causes garbage to be written to cpl.log* file during initial header info after string "MODEL"

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#3533]
With master as of yesterday, I am not able to grep in the cpl.log.* files and it appears to be due to some garbage which must be from the cime_model variable.

```
(seq_mct_drv) :      License information is available as a link from above
(seq_mct_drv) : ------------------------------------------------------------
(seq_mct_drv) :                      MODEL ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
(seq_mct_drv) : ------------------------------------------------------------
(seq_mct_drv) :                 DATE 05/13/20 TIME 03:57:35
(seq_mct_drv) : ------------------------------------------------------------
```

I see this is printed here:
`cime/src/drivers/mct/main/cime_comp_mod.F90`

I noticed there were recent changes to this file.

Following what I found in the cime_final routine, I tried adding the following to the print header routine:

```
character(len=cs)        :: cime_model
call seq_infodata_GetData(infodata, cime_model=cime_model)
```

And now it will print

```
(seq_mct_drv) :                      MODEL  e3sm
```

**Comment by jedwards4b** [comment]
@ndkeen can you open a PR with this change?

**Comment by ndkeen** [comment]
It looks like the string cime_model is set in cime_init().  But cime_printlogheader() is using this first and is called inside cime_pre_init2(). And the order looks like:

cime_pre_init1()
cime_pre_init2()  -- calls cime_printlogheader() which tries to use cime_model
cime_init() -- sets cime_model

I don't want to make a local tacky change just to get cime_model if there's a more elegant way.

**Comment by ndkeen** [comment]
Yep that would work. Thanks Jim.
