### ISSUE TITLE
cprnc fails comparing CLM params files

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3534]
On cheyenne with the latest cprnc I see the following problem...

$CPRDIR/cprnc.cheyenne -m $CSMDATA/lnd/clm2/paramdata/clm5_params.c200425.nc $CSMDATA/lnd/clm2/paramdata/clm5_params.c200424.nc
.
.
.
>   Did not recognize attribute type  -2132179104        32766
> 
> Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
> 
> Backtrace for this error:
> #0  0x7f558e2f994f in ???
> #1  0x41541a in ???
> Segmentation fault (core dumped)

However, it works correctly with the cprnc.cheyenne.190221 build as well as cprnc.cheyenne.a4faaf4

**Comment by jedwards4b** [comment]
Can you provide $CSMDATA and $CPRDIR please.

**Comment by ekluzek** [comment]
Oh, just the paths to inputdata and the built cprnc...

cheyenne5 home/erik> echo $CSMDATA
/glade/p/cesmdata/cseg/inputdata
cheyenne5 home/erik> echo $CPRDIR
/glade/p/cesmdata/cseg/tools/cime/tools/cprnc/

**Comment by jedwards4b** [comment]
/glade/u/home/jedwards/sandboxes/cesm2_x_alpha/cime/tools/cprnc/cprnc
@ekluzek if this works for you, accept the pr and I will install it.

**Comment by ekluzek** [comment]
Yes, that works for me. I'll accept in the PR.
