### ISSUE TITLE
case.submit broken on edison with CIME_MODEL=acme

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#354]
case.submit is broken on edison with CIME_MODEL=acme.

```
Submitting job script sbatch   case.run 
ERROR: Command: 'sbatch   case.run ' failed with error 'sbatch: option requires an argument -- 'A'
sbatch: error: Batch job submission failed: Invalid user id'
```

Works fine with CIME_MODEL=cesm.

**Comment by rljacob** [comment]
Comparing config_batch.xml between cesm and acme, acme is missing the <submit_args> subsection in the slurm entry.  How did any slurm machine (skybridge, redsky) work?

**Comment by jgfouca** [comment]
It doesn't use any submit args, it does it all through directives.

**Comment by rljacob** [comment]
Something about edison's slurm isn't working with directives.  I added submit_args to the slurm definition and that fixes things.  Should I make a PR for that change?

**Comment by rljacob** [comment]
Looking at the case.run from a case on edison using only directives, looks like the directives are missing some info/wrong:
```
# Batch system directives
#SBATCH  --job-name=Xcase4.run
#SBATCH  --nodes=8
#SBATCH  --ntasks-per-node=12
#SBATCH  --output=Xcase4.run   
#SBATCH  --exclusive                        
#SBATCH  --time=36:00:00
#SBATCH  --partition=regular
#SBATCH  --account=
#SBATCH  -A  
```

**Comment by jedwards4b** [comment]
As you pointed out this is working for CIME_MODEL=cesm 
shouldn't it be a matter of copying the config_batch.xml settings for edison (and slurm) from there?

**Comment by rljacob** [comment]
Yes and that does work but @jgfouca seems to want slurm to use an all-directives approach.

I think I see the root cause:  there's a -A directive in the edison entry.  Let me try just removing that.

**Comment by rljacob** [comment]
Removing the -A from the edison entry works.
