### ISSUE TITLE
not requiring data model directories per driver

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3540]
We're re-basing the MOAB branch onto a more recent version of cime/E3SM and noticed that when building, cime is looking for a data_comps_moab dir for data models.   We want to keep using the mct versions of those models for a while so is there a way to point cime to the mct versions when the driver is moab?

**Comment by jedwards4b** [comment]
Yes you can go in config/e3sm/comp_interface and change data_comps_$COMP_INTERFACE to data_comps_mct

**Comment by rljacob** [comment]
You mean in config/e3sm/config_files.xml?

**Comment by jedwards4b** [comment]
Yes, that's what I meant.

**Comment by rljacob** [comment]
That works.
