### ISSUE TITLE
Have datm send ndep to surface components

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3549]
Both CLM and the ocean model need Nitrogen deposition to be sent in. We've handled this by having it sent in by CAM when WACCM is run -- but having each surface component handle prescribed datasets themselves. This means that OCN and LND could have inconsistent datasets. And it also leads to certain problems when surface components don't know if ndep is provided by the ATM model or not (see for example: https://github.com/ESCOMP/CTSM/issues/946). Since, ndep physically is something in the atmosphere, it makes the most sense if ndep would ALWAYS be provided by the ATM component just like prescribed aerosols are now.

The CAM issue that relates to this is here:

https://github.com/ESCOMP/CAM/issues/104

Once, CAM is able to send ndep, the surface components could stop having to prescribe it and just always rely on what is being sent from that ATM component.

**Comment by billsacks** [comment]
At least within CESM, there's no value in solving this within the mct data models any more, so I have opened this issue in CDEPS: https://github.com/ESCOMP/CDEPS/issues/36
