### ISSUE TITLE
env_mach_specific files should just contain settings for main job

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3553]
The hidden `.env_mach_specific.sh` and `.env_mach_specific.csh` files contain settings that apply for all jobs, one after the other. This is a problem on cheyenne, at least, where we set `MPI_USE_ARRAY=false` on the share queue (which is used by the short-term archiver), but we don't want this setting for the main job. Currently, if you source the env_mach_specific file, you'll end up with this undesired setting.

I propose changing these files so that they only contain settings that are applicable to the main job in a case (case.run or case.test).

I will open a PR with this change soon. @jedwards4b @jgfouca you can let me know if you think this should not be changed for some reason that I'm not aware of.

**Comment by jedwards4b** [comment]
These files are not actually used by the model and so the contents shouldn't matter.

**Comment by billsacks** [comment]
> These files are not actually used by the model and so the contents shouldn't matter.

I use them in a workflow where we use cime to build CTSM and some of its dependencies, then have an external model (WRF in this case) load the same environment to build itself. I pinged you in case you were aware of any other workflows that rely on these files looking the way they currently do.
