### ISSUE TITLE
Resetting changes to case env_mach_specific 

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#3562]
```
./scripts/create_test --no-build SMS.f19_g16.X --machine summit --compiler pgi
# cd to case-dir
# edit env_mach_specific.xml to update pgi/19.9 to pgi/19.10
./case.setup -r && ./preview_run
# still loading pgi/19.9
```
Editing config_machines.xml in CIMEROOT works.

**Comment by jedwards4b** [comment]
there is an option to case.setup --keep env_mach_specific.xml 
that will do what you want.

**Comment by amametjanov** [comment]
ok thanks

**Comment by amametjanov** [comment]
Something else to keep in mind: after `rm -rf bld && mkdir bld && ./case.build && ./case.submit & `, local mods to env_mach_specific are also getting reset.
```
...
Resetting case due to detected re-run of phase SHAREDLIB_BUILD
Successfully cleaned .case.test
Successfully cleaned env_mach_specific.xml
Successfully cleaned Macros.make
Successfully cleaned Macros.cmake
...
```
One more step is needed to keep local mods on re-builds:
```
rm -rf bld && mkdir bld && ./case.setup --keep env_mach_specific.xml && ./case.build && ./case.submit &
```

**Comment by jedwards4b** [comment]
Instead of rm -rf bld && mkdir bld 
you can do ./case.build --clean-all

in any case you don't need mkdir bld, that happens in the ./case.build step
