### ISSUE TITLE
Change grid alias for arctic var-res grids

### ISSUE THREAD

**Issue by adamrher** [ESMCI/cime#3564]
The grid aliases for the arctic grids in config_grids.xml:

    ne0np4.ARCTIC.ne30x4_mt12 
    ne0np4.ARCTICGRIS.ne30x8_mt12 

Have dots in them and are incompatible with testing software. The dots need to be removed. I would suggest renaming these grid aliases to:

   ne0ARCTICne30x4_ne0ARCTICne30x4_mt12
   ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12

@fischer-ncar can you please assess the priority of this issue? Thank you.

**Comment by fischer-ncar** [comment]
Closed via #3566
