### ISSUE TITLE
Issue with namelist compare test

### ISSUE THREAD

**Issue by fvitt** [ESMCI/cime#3571]
compare_namelist.py does not like the following legal cam namelist setting:

 csw_specifier          = 'DMS      -> 1.0 * /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/Csw_DMS_HiResML_f09f09_1990_2019_20190616a.nc',
         'CH3COCH3 -> 0.75* /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/Csw_Acetone_HiResML_f09f09_1990_2019_20190814a.nc'

Seems to be an issue with the scaling factor.
This is the traceback from my test:
---------------------------------------------------
2020-06-10 14:18:29: Exception during namelist operations:
ERROR: In file '/glade/scratch/fvitt/SMS_D_Ln9.f09_f09_mg17.FCHIST.cheyenne_intel.cam-outfrq9s_ocnemis.C.mytests_test/CaseDocs/atm_in', Dict entry ''DMS      -> 1.0 * /glade/p/cesmdata/cse
g/inputdata/atm/cam/chem/ocnexch/Csw_DMS_HiResML_f09f09_1990_2019_20190616a.nc'' does not match expected format
Traceback (most recent call last):
  File "/glade/work/fvitt/camdev/chem_cam6_2_032/cime/scripts/Tools/../../scripts/lib/CIME/case/case_cmpgen_namelists.py", line 123, in case_cmpgen_namelists
    success, output = _do_full_nl_comp(self, test_name, compare_name, baseline_root)
  File "/glade/work/fvitt/camdev/chem_cam6_2_032/cime/scripts/Tools/../../scripts/lib/CIME/case/case_cmpgen_namelists.py", line 46, in _do_full_nl_comp
    elif is_namelist_file(item):
  File "/glade/work/fvitt/camdev/chem_cam6_2_032/cime/scripts/Tools/../../scripts/lib/CIME/compare_namelists.py", line 548, in is_namelist_file
    assert "does not appear to be a namelist file" in str(e), str(e)
AssertionError: ERROR: In file '/glade/scratch/fvitt/SMS_D_Ln9.f09_f09_mg17.FCHIST.cheyenne_intel.cam-outfrq9s_ocnemis.C.mytests_test/CaseDocs/atm_in', Dict entry ''DMS      -> 1.0 * /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/Csw_DMS_HiResML_f09f09_1990_2019_20190616a.nc'' does not match expected format

 ---------------------------------------------------

**Comment by jasonb5** [comment]
@fvitt If you remove the whitespaces between the scaling factor and path this will work e.g. `DMS -> 1.0*/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/Csw_DMS_HiResML_f09f09_1990_2019_20190616a.nc`

If those whitespaces are required then I can put in a fix otherwise it might just be worth making the error message more verbose.

**Comment by fvitt** [comment]
In my opinion the compare should not fail if there are white spaces surrounding the * character.

**Comment by jasonb5** [comment]
That makes sense, I'll check to see if there are any other value formats we missed.
