### ISSUE TITLE
Moving other config files out of cime

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3577]
CESM still has a few config files in cime/config/cesm

config_archive.xml
config_grids.xml
config_inputdata.xml

But the path to these seems to be set in config_files.xml so could they be moved as well?

It looks like several config files in the machines directory could also be moved.  But where are the paths to `Depends.* ` and `template.*` in that dir set?

**Comment by jedwards4b** [comment]
Why would we want to move them?  Reading this issue seems like entering into the middle of a conversation - can you start from the top? template file location is provided in config_workflow.xml  Depends files are just expected to be in the machines directory.

**Comment by rljacob** [comment]
We're going to convert cime in the E3SM source to a submodule.  The more e3sm-specific config files we can move out, the less we have to do a 2 PR workflow to update them (update here, then PR to update submodule in E3SM).

I just moved the allactive configs to match what cesm already did.  Wondering how much else I can move.  config_machines.xml is a file we edit a lot.

**Comment by jedwards4b** [comment]
You can move the e3sm config_machines.xml by adjusting the setting in cime/config/e3sm/config_files.xml field MACHINES_SPEC_FILE.   As long as what you move is defined in config_files.xml it should not affect cesm at all.   If you find that you need to move files whose path is not defined in any xml file then we may need to consider adding them there.

**Comment by jgfouca** [comment]
Everything in cime/config/e3sm should be moved into our repo. We can make CIME see these files via symlink.

**Comment by rljacob** [comment]
I don't trust sym links. Does git preserve those?

Can we have MACHINES_SPEC_DIR that points to the location of the machines file?  That would let us move everything.

**Comment by jgfouca** [comment]
Yes, Git tracks symlinks just fine. I'd prefer the symlink approach since it makes the system look the same as it did before. A new MACHINE_SPEC_DIR could have wide-ranging impacts across CIME.

**Comment by jedwards4b** [comment]
@jgfouca I disagree - the config_files.xml was intended to allow flexibility in the location of inputfiles - you should not need to symlink anything.   If config_files.xml doesn't allow the flexibility you need then let's improve it so that it does.

**Comment by rljacob** [comment]
A MACHINE_SPEC_DIR indicating the location of "machines" would go a long way to close the gap in being able to specify the location of all input files.  Otherwise we need entries for all the `Depends.* ` and `template.*` files.  We also have a bunch of `syslog.*` files in machines.

**Comment by jedwards4b** [comment]
I don't think that there is a problem with Depends and template files.  They are by default expected to be in the machines directory but there is no assumption about where that directory is - if you look in machines.py the machines directory is the directory which contains the machines_spec_file.   I think that you should try moving the files and updateing the config_files.xml and figure out whether there really is a problem - I don't think that there is.

**Comment by jgfouca** [comment]
OK, I am fine with trying an XML approach.

**Comment by rljacob** [comment]
I will experiment with machines.py and moving machines around.

**Comment by rljacob** [comment]
Looks like this will work.  The machines dir is derived from MACHINES_SPEC_FILE.  So just moving that is enough to tell the CCS where everything else is (but you DO have to move everything else).

@jgfouca where is the location of tests.py set?

**Comment by rljacob** [comment]
It is set in some code at the top of get_tests.py.  Will have to change that.
