### ISSUE TITLE
Double-check changes made in #3582

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3584]
@jedwards4b can you please double-check / confirm some changes made in #3582 ? Based on https://github.com/ESMCI/cime/pull/3582/files , I see the following potential issues:

(1) I believe your logic change will change behavior for e3sm with nag: it looks like USE_CXX will be set to true, whereas they seem to want it to be set to false with nag.

(2) Was the commenting out of the error check ("Fatal attempt to include C++ code on a compiler/machine combo that has not been set up to support C++") intentional? At least at the time when we put that check in place, it served a useful purpose. If you feel it's no longer necessary, then I think we should just remove the SUPPORTS_CXX flag entirely, because I think that error check is the only place where it's referenced.

**Comment by jedwards4b** [comment]
We are the only ones using a nag compiler. I put the origin change in so that pio2 would work for nag, but pio2 doesn't need cxx.  No I didn't mean to comment out the error check - I'll fix that.

**Comment by jedwards4b** [comment]
Pushed 4427dd051  to master.

**Comment by billsacks** [comment]
Thanks!

**Comment by rljacob** [comment]
Yes we haven't tried to use nag in a  couple of years.
