### ISSUE TITLE
Change check_input_data output to avoid using logging.warning for normal output?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3588]
I ran into this issue when calling `case.check_all_input_data` from my own script (using CIME as a python library). So I didn't call `CIME.utils.parse_args_and_handle_standard_logging_options` (because I use a somewhat different logging configuration than CIME does). When I did this, I got a ton of WARNING messages; here is a small set of them:

```
WARNING:   Model clm missing file paramfile = '/Users/sacks/projects/scratch/lilac_usermach_0624a/inputdata/lnd/clm2/paramdata/clm5_params.c200519.nc'
WARNING:   Model clm missing file fsnowoptics = '/Users/sacks/projects/scratch/lilac_usermach_0624a/inputdata/lnd/clm2/snicardata/snicar_optics_5bnd_c090915.nc'
WARNING:   Model clm missing file fsnowaging = '/Users/sacks/projects/scratch/lilac_usermach_0624a/inputdata/lnd/clm2/snicardata/snicar_drdt_bst_fit_60_c070416.nc'
WARNING:   Model clm missing file finidat = '/Users/sacks/projects/scratch/lilac_usermach_0624a/inputdata/lnd/clm2/initdata_map/clmi.I2000Clm50BgcCrop.2011-01-01.1.9x2.5_gx1v7_gl4_simyr2000_c190312.nc'
WARNING:   Model clm missing file stream_fldfilename_urbantv = '/Users/sacks/projects/scratch/lilac_usermach_0624a/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc'
WARNING: Client protocol gftp not enabled
WARNING: Client protocol wget not enabled
WARNING: Client protocol None not enabled
WARNING: Client protocol gftp not enabled
WARNING: Client protocol wget not enabled
```

It seems like all of the output from this function is using warnings, when in fact many of these messages seem to be just normal, expected operation – in particular, the messages that files are missing should not (in my view) be warnings, but rather are exactly what you expect. It is therefore misleading to have `WARNING` appear on these messages, and it means that true issues get lost, since both true issues and expected output have the same `WARNING` prefix.

When running the `check_input_data` script from a case, this issue doesn't arise, presumably because of how logging is set up in CIME. However, I feel that we should follow best practices in this respect, and reserve `logging.warning` for true warnings. Based on the guidance in https://docs.python.org/3/howto/logging.html#when-to-use-logging, I feel that the messages about missing files should be made using `print` statements, since my impression is that these fall under the category of "Display console output for ordinary usage of a command line script or program".

**Comment by jedwards4b** [comment]
Please feel free to make this change and submit a PR.
