### ISSUE TITLE
CICE_CPPDEFS UNSET

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#359]
After version cime5.0.5 the CICE_CPPDEFS variable is unset causing a failure in the build phase.
I am running cime_bisect now to identify the commit. 
Test is SMS_Ld5.T31_g37_gl20.B1850C5L45BGCRG2.yellowstone_intel.allactive-cism-test_coupling

**Comment by jedwards4b** [comment]
This was broken by PR #343, we will revert that PR for now and recommit it when resolved.

**Comment by rljacob** [comment]
That PR was fixing issue #323 which is now re-opened.

**Comment by rljacob** [comment]
This was fixed by reverting #343
