### ISSUE TITLE
create_newcase --test mode does not create a viable case without create_test

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#3595]
The XML_PHASE of tests has bugged me for a while. Every other phase of a the case-control system can be run standalone in a case via a command-line tool, but the XML_PHASE can only be run through create_test. If a user copy/pastes the create_newcase command, and then tries to run `./case.setup` and `./case.build`, the build will fail with `No variable CCSM_CPRNC found in case`. Even if we were to fix this particular problem, the behavior of the case will still not match create_test since so many other important env XML settings would be missing.

At the very least, I'd like `create_newcase ... --test ...` to throw a very stern warning to the user if it detects that it was invoked outside of create_test.

I think a better, but more difficult, solution would be to merge the functionality of the xml_phase into either create_newcase or case_setup.

**Comment by jedwards4b** [comment]
I guess I am surprised that a user would cut and paste the create_newcase command from a test like that. So I think the first proposal to throw an error (not a warning) if a user attempts to invoke this option from the command line is appropriate. 

The functionality of the xml_phase is already incorporated in create_newcase but that functionality is partially suppressed by the --test argument.
