### ISSUE TITLE
CIME does not set max pending requests automatically

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#3596]
The maximum I/O pending requests setting in env_run.xml, PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO, is by default set to 0. CIME needs to set the variable to an appropriate value in this case (when its set to 0). However after PR #3499 this behavior is disabled.

PR #3499 intends to use MPI collectives for data rearrangement when using the mpi-serial library. The PR achieves it by setting maximum I/O pending requests to 0, since that setting is used in PIO to use collectives for data rearrangement, and disabling CIME resetting the value. The PR also intends to allow 0 as a valid value for PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO variable.

Also note that a value of 0 for PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO can still be considered a valid setting (e.g. using blocking communication for rearranging data) even if it is not used to decide the type of communication (collective vs point to point).

There are two ways to fix the issue,
1) Use a different default for PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO that indicates that the user wants CIME to reset the value to an appropriate value. See PR #3594 
2) Use the variable PIO_REARR_COMM_TYPE in env_run.xml (set it to "coll") to force using collectives for data rearrangement in PIO for the mpi-serial (number of procs == 1) case. AFAICT this also requires some changes in PIO. We might still need further changes if we need to allow users to set PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO = 0 (i.e. indicating that the maximum number of pending I/O requests should be 0).

**Comment by jayeshkrishna** [comment]
@jedwards4b , @rljacob , @fischer-ncar Please let me know your thoughts

**Comment by jedwards4b** [comment]
I am looking at PIO now to see if 2 can be done without changes in pio.

**Comment by billsacks** [comment]
My understanding from this is that recent uses of cime are incorrectly specifying `PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO`. Does anyone know what impact this has – performance or otherwise? Is it a potentially significant enough impact that we should put out a notification, or is the impact expected to be minor?

**Comment by jedwards4b** [comment]
This is in the development branch only.  It may have some impact on performance but it's hard to determine how much or even if the impact is negative.

**Comment by jedwards4b** [comment]
@jayeshkrishna I have tested setting PIO_REARR_COMM_TYPE=coll in pio2 with mpi-serial and it works.  I will create a new PR that will keep the defaults as they are and only change PIO_REARR_COMM_TYPE for mpi-serial.

**Comment by jayeshkrishna** [comment]
ok, thanks!
