### ISSUE TITLE
Basic CIME testcases need to build successfully

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#36]
The tests are these:
```
                            "NCK_Ld3.f45_g37_rx1.A",
                             "ERI_D.f45_g37_rx1.A",
                             "SEQ_PFC_Ld3.f09_g16.X",
                             "ERS_Ld3.ne30_g16_rx1.A",
                             "ERS_N2_Ld3.f19_g16_rx1.A",
                             "ERS_Ld3.f45_g37_rx1.A"
```

**Comment by jgfouca** [comment]
To clarify: we need:
```
scripts-python/create_test cime_developer
```
to work.

**Comment by jedwards4b** [comment]
This is working on yellowstone

On Wed, Jan 20, 2016 at 4:54 PM, James Foucar <notifications@github.com>
wrote:

> To clarify: we need:
>
> scripts-python/create_test cime_developer
>
> to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/issues/36#issuecomment-173406193>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jgfouca** [comment]
Oh, excellent! Didn't realize you guys made it that far. I'm still trying to get ACME stuff up and running again after the recent merges. Hopefully it will work for me too. If not, I might ask you guys to copy the hobart config to cime_config/acme/machines/config_machines.xml and try to run create_test in acme mode.

**Comment by rljacob** [comment]
On Blues with latest master, c513a9b2d58, I'm getting:

blogin2[97]: ./create_test acme_developer 
/lcrc/group/earthscience/jacob/cimeESMCI/scripts-python/../utils/python
Traceback (most recent call last):
  File "./create_test", line 15, in <module>
    import cime_util
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts-python/../utils/python/cime_util.py", line 328, in <module>
    def get_model_config_location_within_cime(model=get_model()):
NameError: name 'get_model' is not defined
Exit 1

**Comment by jgfouca** [comment]
Cime_developer working on yellowstone and melvin.
