### ISSUE TITLE
Files with .in in share code

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3607]
There are three files in cime/src/share/util that seem to require pre-processing.

shr_assert_mod.F90.in	shr_frz_mod.F90.in	shr_infnan_mod.F90.in

But when I look at the codes, its all standard cpp directives that the Fortran compiler should be able to handle itself.  Why are these not just .F90 files?

**Comment by rljacob** [comment]
@jgfouca re: above.  shr_frz_mod.F90.in is missing from CMakeLists.txt in that directory.

**Comment by jedwards4b** [comment]
These use the genf90.pl script to generate type specific flavors of generic subroutines.

**Comment by jedwards4b** [comment]
For example in shr_frz_mod.F90.in:
```
  ! DIMS 0,1,2                                                                                                         
  function shr_frz_freezetemp_{DIMS}d(s) result(shr_frz_freezetemp)
```
expands to:
```
function shr_frz_freezetemp_0d(s) result(shr_frz_freezetemp)

function shr_frz_freezetemp_1d(s) result(shr_frz_freezetemp)

function shr_frz_freezetemp_2d(s) result(shr_frz_freezetemp)
```

**Comment by rljacob** [comment]
Oh so that is not just a comment.  That makes sense then.

**Comment by naromero77** [comment]
There was an interesting talk at FortranCon 2020 about generic programming technique for Fortran.
https://tcevents.chem.uzh.ch/event/12/contributions/57/

Apparently, there is Python-based preprocessor for Fortran to handle this kind of stuff:
https://github.com/aradi/fypp

But it does not seem like its possible to do this natively with Fortran.

**Comment by jedwards4b** [comment]
Ours is here: https://github.com/PARALLELIO/genf90
same idea I think.
