### ISSUE TITLE
CIME_MODEL can differ between build and execution

### ISSUE THREAD

**Issue by rgknox** [ESMCI/cime#3615]
With E3SM, I recently ran into a run-time error that had to do with the coupler trying to pass fields that were not in its registry of known fields.  This was because I had compiled the model with CIME_MODEL=e3sm (set locally in my build script), but my environment has CIME_MODEL=cesm (which was active during execution).  

I may be an unusual user, in that I am constantly running both models and swapping back and forth.

My thinking is that if a model is built with a CIME_MODEL, I can't see a reason why it wouldn't want to preserve that choice during the execution phase.  Or, at least it should complain gracefully if that choice changes.

Here is the issue I generated on E3SM: https://github.com/E3SM-Project/E3SM/issues/3681

I discussed a little with @ekluzek and @billsacks .  @ekluzek suggested that maybe CIME_MODEL could be stored in a case file, perhaps one of the XMLs such as env_build or env_case.

I personally have learned my lesson and can remember to set the CIME_MODEL correctly now, but was encouraged to at least post this as a discussion topic.

**Comment by jedwards4b** [comment]
There is already a variable in the case - that variable is MODEL.   The issue here is that once a case is defined it should always prefer that to the environment variable for that case.   I think that I can address this.

**Comment by jedwards4b** [comment]
@jgfouca This is due to the _check_for_invalid_args in utils.py.   get_model is called there before the case is initialized and so we cannot yet check the value of MODEL.  It is also used in parse_command_line in several scripts eg case.build and in the __init__ of files.py.   Ideas on how to solve this?  The case MODEL variable should always be prefered.

**Comment by jgfouca** [comment]
@jedwards4b this could be tricky since knowing the model is so fundamental to how CIME operates.

**Comment by jgfouca** [comment]
I guess the solution for _check_invalid would be to officially remove support for those single-dash long-form options in all models.

**Comment by jedwards4b** [comment]
I don't think that would be a problem.  But there are still several other cases where get_model is used before a case object can be established.   Maybe the solution is to write a small config file in the case directory and then look for a config file in the current directory and read it if it exists.  This file would only have CIME_MODEL in it.

**Comment by jedwards4b** [comment]
We should probably keep this one open.
