### ISSUE TITLE
a problem when I create a newcase

### ISSUE THREAD

**Issue by lvxin233** [ESMCI/cime#3617]
![image](https://user-images.githubusercontent.com/63852927/87242571-870e7e80-c460-11ea-9f5f-fb24a757712f.png)
it says "no queues found",but I dont know where the problem is.
below is my config_machine.xml file
![config_machine](https://user-images.githubusercontent.com/63852927/87242627-13b93c80-c461-11ea-8687-f2e50e5dd02b.png)

**Comment by jedwards4b** [comment]
The problem is probably in config_batch.xml -  how have you defined the available queues?

**Comment by lvxin233** [comment]
> The problem is probably in config_batch.xml - how have you defined the available queues?

Thanks for your apply，I'll try to modify it

**Comment by lvxin233** [comment]
I have a problem again, when I type the command "./case.build", an error "can't locate xml/libxml.pm in @INC" occurred. However, I already have the libxml.pm file, I don't know if I need to add the libxml.pm PATH to any config files.
Below is my settings in config_machines.xml file.

<module_system type="module">
<init_path lang="perl">/usr/share/Modules/init/perl.pm</init_path>
<init_path lang="python">/usr/share/Modules/init/python.py</init_path>
<init_path lang="sh">/usr/share/Modules/init/sh</init_path>
<init_path lang="csh">/usr/share/Modules/init/csh</init_path>
<init_path lang="bash">/usr/share/Modules/init/bash</init_path>
<cmd_path lang="perl">/usr/bin/modulecmd perl</cmd_path>
<cmd_path lang="python">/usr/bin/modulecmd python</cmd_path>
<cmd_path lang="sh">module</cmd_path>
<cmd_path lang="csh">module</cmd_path>
<cmd_path lang="bash">module</cmd_path>

**Comment by lvxin233** [comment]
@jedwards4b

**Comment by jedwards4b** [comment]
First this is the wrong forum for this discussion, please use http://forum.cgd.ucar.edu/
Second the modules section of your config_machines.xml file has nothing to do with the error you are getting.
libxml.pm should be distributed with your perl.   But I don't think that any cesm component requires that file any longer,
what are the steps to reproduce this problem?

**Comment by lvxin233** [comment]
> First this is the wrong forum for this discussion, please use http://forum.cgd.ucar.edu/
> Second the modules section of your config_machines.xml file has nothing to do with the error you are getting.
> libxml.pm should be distributed with your perl. But I don't think that any cesm component requires that file any longer,
> what are the steps to reproduce this problem?
I see. Thank you for your reply

**Comment by jgfouca** [comment]
I assume this discussion was moved to the correct forum.
