### ISSUE TITLE
xmlchange broken for complex arguments

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#364]
xmlchange needs to support the following:
```
./xmlchange CICE_CPPDEFS="-DCCSMCOUPLED -Dncdf -DNUMIN=11 -DNUMAX=99 -DNICECAT=5 -DNXGLOB=100 -DNYGLOB=116 -DNTRAERO=3 -DNBGCLYR=3 -DNICELYR=8 -DNSNWLYR=3 -DTRAGE=1 -DTRFY=1 -DTRLVL=1 -DTRPND=1 -DTRBRI=0 -DTRBGCS=0"
```

Since CESM was broken, I had to revert #343 . Please unrevert this revert, fix the above usecase, and maybe add a scripts_regression_test for this usecase.

**Comment by rljacob** [comment]
This was fixed by reverting #343
