### ISSUE TITLE
new scripts regression test G_TestBuildSystem hangs indefinately on cheyenne 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3640]
test_clean_rebuild (__main__.G_TestBuildSystem)  simply hangs.

**Comment by jedwards4b** [comment]
Also tried on izumi - this test seems to hang - I wonder if this is a general issue on batch systems?  It seems that the TestStatus is 
cat TestStatus
PASS SMS.f19_g16_rx1.A.cheyenne_intel CREATE_NEWCASE
PASS SMS.f19_g16_rx1.A.cheyenne_intel XML
PASS SMS.f19_g16_rx1.A.cheyenne_intel SETUP
PASS SMS.f19_g16_rx1.A.cheyenne_intel SHAREDLIB_BUILD time=135
PASS SMS.f19_g16_rx1.A.cheyenne_intel MODEL_BUILD time=21
PEND SMS.f19_g16_rx1.A.cheyenne_intel SUBMIT

But since the option was --no-run no job was submitted and I think it will just wait forever.

**Comment by jgfouca** [comment]
OK, I will look at it.
