### ISSUE TITLE
PR#3666 breaks building I compsets with NUOPC

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#3681]
It looks like only the scripts_regression_tests.py were run. I think this is a mistake and we need to run at least the nuopc testlist_drv.xml test suite before doing a CIME PR in the future.

**Comment by ekluzek** [comment]
Note, also that "A" compsets fail as well.

For example...

I have fails in both: SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default and the I compset SMS_D_Ld5_Vnuopc.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-default.

The A compset fail looks like this:

docn built in 0.405266 seconds
drof built in 0.405693 seconds
Building test for SMS in directory /glade/scratch/erik/CESM/cime/scripts/SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default.20200823_000721_5bpt9x
ERROR: BUILD FAIL: datm.buildlib failed, cat /glade/scratch/erik/SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default.20200823_000721_5bpt9x/bld/atm.bldlog.200823-000945
BUILD FAIL: docn.buildlib failed, cat /glade/scratch/erik/SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default.20200823_000721_5bpt9x/bld/ocn.bldlog.200823-000945
BUILD FAIL: dice.buildlib failed, cat /glade/scratch/erik/SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default.20200823_000721_5bpt9x/bld/ice.bldlog.200823-000945
BUILD FAIL: drof.buildlib failed, cat /glade/scratch/erik/SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.drv-default.20200823_000721_5bpt9x/bld/rof.bldlog.200823-000945

**Comment by ekluzek** [comment]
The I compset fails in finding the dshr_* modules...

Building test for SMS in directory /glade/scratch/erik/CESM/cime/scripts/SMS_D_Ld5_Vnuopc.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-default.20200821_193618_f1mdc7
/glade/scratch/erik/CESM/components/clm/src/cpl/nuopc/SoilMoistureStreamMod.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [DSHR_STRDATA_MOD]

/glade/scratch/erik/CESM/components/clm/src/cpl/nuopc/SoilMoistureStreamMod.F90(13): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [DSHR_METHODS_MOD]

/glade/scratch/erik/CESM/components/clm/src/cpl/nuopc/SoilMoistureStreamMod.F90(14): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [DSHR_STREAM_MOD

**Comment by jedwards4b** [comment]
A logic error in the bld cdeps line.  I've pushed the fix directly to master.
