### ISSUE TITLE
github is renaming master branch to main, should update documentation

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3692]
github is going to be renaming the master branch for all projects to main. This is a good change that we should go along with. The language we use in our code and code management needs to be inclusive and respectful to all.

This happens on Oct/1/2020 according to

https://github.com/github/renaming

We should update any README files and etcetera that refer to "master" to "main" when this happens (as well as in the wiki pages for similar things).

It looks like E3SM has explicit use of "master" in some of their scripts, for example...

scripts/lib/e3sm_cime_mgmt.py

I think these will likely break after the change. There are some system tests that do as well, but I wasn't sure if they would break.

@jgfouca and @rljacob can you and other E3SM people look into this?

Note, that CTSM is working on this as well: https://github.com/ESCOMP/CTSM/issues/1048

**Comment by jgfouca** [comment]
@ekluzek , E3SM is no longer using e3sm_cime_mgmt since we went to integrating CIME within E3SM via submodule.

**Comment by rljacob** [comment]
They aren't making existing projects change on Oct 1st.  That is when the default for new repos changes.   Later that year, they'll roll out tools to make it easier for existing projects to change.
