### ISSUE TITLE
test_cime_case_test_custom_project (__main__.K_TestCimeCase) no longer relevent 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3698]
I think that this test has outlived its usefulness as written - any suggestions or should we just remove it?

**Comment by jasonb5** [comment]
@jedwards4b There was never any response to this, are we fine with just removing this test?

**Comment by jedwards4b** [comment]
@jasonb5 I'm not sure now why I said this, I don't see anything wrong with this test as written.

**Comment by jasonb5** [comment]
@jedwards4b Sounds good, thanks!
