### ISSUE TITLE
Need to implement parser for NUOPC formatted namelist files

### ISSUE THREAD

**Issue by uturuncoglu** [ESMCI/cime#3705]
The CIME interface is providing a parse function for Fortran formatted namelist files but there is no such implementation for ESMF/NUOPC formatted namelist (or configuration) files. This is required to use user provided ESMF/NUOPC formatted namelist file to generate another Fortran formatted namelist file. In this case, the Fortran formatted namelist file basically requires some information from the ESMF/NUOPC formatted namelist file, which can be provided by the user. The possible implementation can be,

```
nmlgen = parse_nuopc('nuopc_runconfig')
```

**Comment by mvertens** [comment]
@uturuncoglu - I don't undertand why you  would need this. The current functionality lets you take the namelist_definition_drv.xml file and create the nuopc.runconfig and the drv_in file and the modeio files. What is your use case that this is not working for?
