### ISSUE TITLE
Namelist object returned form parse() function has no attribute '_definition'

### ISSUE THREAD

**Issue by uturuncoglu** [ESMCI/cime#3706]
The namelist object returned by parse function has no attribute '_definition'. 

user_namelist_file = os.path.join(caseroot,"SourceMods","src.ufsatm","atm_in")
nmlgen_input = parse(user_namelist_file)
var_type,_,_ = nmlgen_input._definition.split_type_string(var)

returns following error

```
    var_type,_,_ = nmlgen_input._definition.split_type_string(var)
AttributeError: 'Namelist' object has no attribute '_definition'
```

an example input namelist file can be found in `/glade/work/turuncu/UFS/S2S/rt_194339/cpld_fv3_ccpp_mom6_cice_cmeps_2d_atm_flux/input.nml`

I just wonder that is there any way to make it work? Maybe I am using wrong functions to parse the namelist or I need to call another function to add type information but I am not sure.

**Comment by uturuncoglu** [comment]
It seems that current _NamelistParser function does not include self._definition information.

**Comment by mvertens** [comment]
@uturuncoglu - I am confused as to why you need this. Normally input namelists are generated by the component caps (e.g. cdeps) using the call
`nmlgen.init_defaults(infile, config)`

**Comment by jedwards4b** [comment]
As a general rule in python any variable or function who's name begins with an underscore should be considered off-limits for use outside of the module.

**Comment by uturuncoglu** [comment]
@jedwards4b Thanks. I'll modify that part.
