### ISSUE TITLE
Should cime assume compname is in filenames?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3710]
While changing "clm" to "elm" in E3SM, I found that the short term archiver was expecting "clm" to be in the filenames.  (see issue #3704).   I don't think CIME should force/assume that.

There is a block of code in config_archive.xml that looks like:
```
  <comp_archive_spec compname="clm" compclass="lnd">
    <rest_file_extension>r</rest_file_extension>
    <rest_file_extension>rh\d?</rest_file_extension>
    <hist_file_extension>h\d*.*\.nc$</hist_file_extension>
    <hist_file_extension>e</hist_file_extension>
```

It seems we could use that to specify more about the filenames including if the root is "clm2" or "elm" or something unrelated to compname like "foo".

**Comment by jedwards4b** [comment]
Although I do agree that changing the name from clm to elm should not present an error (Where by the way is the error?)
I do think that we should have some conventions for file names including requirements for comp name in history and restart files.

**Comment by rljacob** [comment]
The error is in the archiver.  See original discussion in #3704 

I agree that a climate modeling group should require an identifying name in history and restart files and CIME should allow you to enforce that but I'm not sure CIME should require it.   Or it should not require that the string in the filename exactly match a COMP name.

**Comment by ekluzek** [comment]
From what I could tell from my work on this, somewhere in cime there is a requirement that the compnames used in filenames in the archiver, need to be the same as the compname with an optional single digit version identifier on the end. I didn't figure out where this was coming from, but it appeared to be the case. I couldn't for example have a two digit version identifier it needed to be one. And it did seem to need to match the compname used in cime. So I couldn't have the compname be "clm" and "ctsm" be the name used in the archiver.

So I still can't tell you where the error is. But, I can just say that I had the same experience as @rljacob

**Comment by billsacks** [comment]
I believe the assumption is here

https://github.com/ESMCI/cime/blob/7188df18bfffe1dc4ad4e952ba7b41bea352d5aa/scripts/lib/CIME/XML/archive_base.py#L98

and here

https://github.com/ESMCI/cime/blob/7188df18bfffe1dc4ad4e952ba7b41bea352d5aa/scripts/lib/CIME/XML/archive_base.py#L168

though I can't guarantee that those are the *only* places where that assumption is made.
