### ISSUE TITLE
module list for tcsh and csh users 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#372]
The module list command in env_mach_specific.py does not work for tcsh and csh users
I've commented out the call to this code in case_setup.py until the problem can be resolved.
Code was added in PR 337

**Comment by rljacob** [comment]
What was the reproducer for the issue?  I only saw a module list error on your jgfouca/add_postbuild_info branch regarding creation of software_environment.txt.

**Comment by jgfouca** [comment]
@rljacob yes, that's the error that should go away

**Comment by jgfouca** [comment]
Just to be clear, that specific branch did not add the software_environment.txt capability, that's just when you happened to see it.
