### ISSUE TITLE
uboot unable to compile in ubuntu 16.04

### ISSUE THREAD

**Issue by justdoGIT** [ESMCI/cime#3722]
uboot is throwing error while running make command in ubuntu 16.04

`$ make`

the error is 

> Makefile:37: *** missing separator.  Stop.

I think the reason is that make  version in ubuntu 16.04 is v3.81 and undefine keyword is supported after v3.82.
Is there any way to install latest version of make in ubuntu 16.04

**Comment by jedwards4b** [comment]
uboot is not a part of cime - did you intend to open an issue here?

**Comment by justdoGIT** [comment]
I am really sorry for this inconvenience
