### ISSUE TITLE
scripts_regression_tests.py Y_TestUserConcurrentMods is failing for cesm 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3728]
It seems to archive the cesm.log before the file is grepped to look for the run successful message.

**Comment by jedwards4b** [comment]
The test is also writing to the default archive directory instead of creating one in the TEST_ROOT and is not cleaning up after itself.

**Comment by jedwards4b** [comment]
It seems like a race condition, sometimes the test will pass and other times I get:
ERROR: Model did not complete, no /glade/scratch/jedwards/scripts_regression_test.20201005_115759/TESTRUNUSERXMLCHANGE.f19_g16.X.cheyenne_intel.fake_testing_only_20201005_115804/run/cesm.log.4498193.chadmin1.ib0.cheyenne.ucar.edu.201005-120142 log file 
However this file is in the archive/TESTRUNUSERXMLCHANGE.f19_g16.X.cheyenne_intel.fake_testing_only_20201005_115804/logs/cesm.log.4498193.chadmin1.ib0.cheyenne.ucar.edu.201005-120142

**Comment by jedwards4b** [comment]
The test cannot be rerun from the test directory because the number of occurrences of string
"model execution success" will increase with each run.

**Comment by jgfouca** [comment]
@jedwards4b , thx, I will take a look.
