### ISSUE TITLE
Remove pio1 from cime

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3733]
Now that pio2 is the default I would like to remove the pio1 and pio2 directories from cime and
make src/externals/ParallelIO a git submodule from https://github.com/NCAR/ParallelIO
remove variable PIO_VERSION 
and clean up buildlib.pio and the Makefile.

**Comment by rljacob** [comment]
This would be the first submodule in CIME?   Fine with me.

**Comment by billsacks** [comment]
I fully support removing pio1. However, I'd like to suggest that we wait a little while – maybe a month or two – after switching to pio2 as the default. That way, if issues are found after this switch, it will be easy for us to do A/B testing with pio1 vs. pio2.
