### ISSUE TITLE
FMS library needs to be set as required in Externals.cfg

### ISSUE THREAD

**Issue by jtruesdal** [ESMCI/cime#3742]
The fms external library is currently listed as not required and prevents building CAM with the FV3 dycore out of the box.  The fix is to list the fms external library as required. A workaround is to manually checkout fms after running manage_externals

manage_externals checkout externals

 or to call manage_externals with the -o option when first checking out the externals.  This will check out defaults as well as optional externals.

manage_externals -o

**Comment by gold2718** [comment]
First, why is this a CIME issue, CIME does not manage the CESM (or CAM) Externals.cfg files.

Second, since this is only needed in a small minority of use cases, why not push the responsibility for making sure it is checked out into CAM's buildlib?

**Comment by jtruesdal** [comment]
I'm happy to list this as an issue where ever the group feels its appropriate.

**Comment by jedwards4b** [comment]
Move to https://github.com/ESCOMP/CESM/issues

**Comment by gold2718** [comment]
Or CAM issues?
