### ISSUE TITLE
New grids needed for mizuRoute

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3758]
We need to add some new grids for use by mizuRoute: HDMAmz over CONUS, USGSmz over CONUS for nldas2 grid for land.

**Comment by ekluzek** [comment]
So the list of resolutions we want are: f19_g17_rHDMA, 5x5_amazon_r05,  5x5_amazon_rHDMA,  nldas2_rUSGS_mnldas2,  nldas2_rHDMA_mnldas2. For all but the amazon ones, we have mapping files and simplified mesh files to put into place. The default resolution for mizuRoute is r05mz, so other resolutions will default to it. The 5x5_amazon_rHDMA resolution will run with the full mesh file. I've got this setup in a branch, and will make a PR for it after we do some more testing with it.

**Comment by ekluzek** [comment]
We also should have f19_g17_rMERIT and f09_g17_rMERIT and f09_g17_rHDMA so that 1-degree and 2-degree standard CTSM resolutions are supported.

**Comment by ekluzek** [comment]
@jedwards4b thanks for the suggestion. What I did was to use "mz" for the ending for the full name used by ROF. But, I left the "mz" part off for the aliases for the full grid. I'm happy to add mz to the aliases if that sounds better.

So we'd have

f19_g17_rMERITmz and f09_g17_rMERITmz and f09_g17_rHDMAmz

I removed the "mz" for them just to shorten the names. So should I do that?

**Comment by jedwards4b** [comment]
No - I mean that the alias ought to have something about the grid resolution. MERIT means nothing to me, nor does HDMA.

**Comment by ekluzek** [comment]
Oh, that's a problem, because these are Hydrologic Response Unit's (HRU's) grids. So they don't correspond to anything akin to gridsize. Each HRU is of an irregular shape and has thousands of vertices to describe it. And different HRU's in the grid are going to be of different sizes as well. Roughly MERIT-Hydro is the highest resolution, and HDMA is lower than that and about the same as USGS-GF. But, I'm not really sure how to convey the resolution for these HRU grids. 

I do think that it's fair that anyone working with mizuRoute is going to be familiar with these names though. That's especially since mizuRoute is going to be considered experimental for quite a while. I will check with Naoki and Martyn to see if they have any further suggestions.
