### ISSUE TITLE
Z_FullSystemTest failing on master

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3762]
It appears that the second build in the system_tests_compare_two tests are failing.  The problem seems to be on all systems and all compilers.

**Comment by jedwards4b** [comment]
Running a single test ERP_Ln9.f45_g37_rx1.A from the command line is also failing in the same way:
case2 sharedlib_build is not completed before the job is submitted.

**Comment by jedwards4b** [comment]
This test passes with hash 2b860e536

**Comment by jedwards4b** [comment]
Also passes with hash c75b863a7 but fails in hash 03ba87d9.

**Comment by jgfouca** [comment]
@jedwards4b , I'm looking at it, but I don't see how 03ba could have caused these problems.

**Comment by jgfouca** [comment]
My testing confirms the problem. My fault for thinking code-checker and some by-hand testing was adequate for such a simple PR.

**Comment by jedwards4b** [comment]
I don't either, that's why I waited for you.  Have you tried to reproduce?
