### ISSUE TITLE
Python3 compatibility issue for statistical ensemble test

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3776]
We noticed some python2 type print statements in:

cime/tools/statistical_ensemble_test/pyCECT/pyEnsLib.py

https://github.com/ESMCI/cime/blob/master/tools/statistical_ensemble_test/pyCECT/pyEnsLib.py#L26

These should be changed to the python3 syntax. Are there other python2 issues in there as well?

**Comment by ekluzek** [comment]
Doing some grepping I see that it's an extensive problem for the stat ensemble test code. But, also a problem for tools/load_balancing_tool/tests/load_balancing_test.py.

And I was surprised to see a few instances in

scripts/lib/CIME/utils.py

**Comment by billsacks** [comment]
The prints I see in utils.py are just in a doc string, so don't impact the running of the code.

**Comment by ekluzek** [comment]
A small update. I re-found these files by running the python reformatter "black" on cime6.0.11 and telling it to target python-3.7.  In addition to that it also complains about a file in scripts/Tools

> error: cannot format scripts/Tools/xmlconvertors/grid_xml_converter.py: Cannot parse: 168:52:                     attribs = {'{}_mask'.format(comp:mask)}
