### ISSUE TITLE
Removing CISM_USE_TRILINOS; how far should this cleanup extend?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3783]
I'm removing the no-longer-used `CISM_USE_TRILINOS` variable from CISM in CESM, since this is always FALSE now. We could clean up some of cime by removing references to this variable throughout CIME (in `scripts/lib/CIME/build.py` and `scripts/Tools/Makefile`).

What I'm not sure of is how far we should go with this removal:

- Should we completely remove `USE_TRILINOS`, or is that still used in some other contexts? (According to the logic in build.py, it looks like it is only set to true if CISM_USE_TRILINOS is true, but I see a few machines in CESM's config_compilers.xml that define TRILINOS_PATH, and I'm pretty sure that was *not* for the sake of CISM, so I'm wondering if trilinos may be used by others.)

- If we do remove USE_TRILINOS, then should we go so far as to completely remove USE_CXX from the Makefile? The current logic is: https://github.com/ESMCI/cime/blob/1bcacca70fea0bf66b13909b787822ddc54f9c93/scripts/Tools/Makefile#L62-L71 
My understanding is that the Makefile is not used by E3SM, and I was vaguely under the impression that Albany is just an E3SM thing. So, without the need to support Trilinos, is there any reason to support C++ code in the Makefile build? We could clean up the Makefile by removing it, but I'm not sure whether it's needed now or in the near future for some other purpose.

@jedwards4b I'm hoping you can provide some guidance here.

**Comment by jedwards4b** [comment]
I thought that TRILINOS was an e3sm thing, we don't use it anywhere as far as I am aware.   We also do not use ALBANY and do not use any c++ code.

**Comment by rljacob** [comment]
Yes E3SM is using TRILNOS and ALBANY and C++ code.  I'm not sure about the CISM_USE_TRILINOS variable.

**Comment by billsacks** [comment]
Thanks @jedwards4b and @rljacob - and @jgfouca should probably be in the loop here too. So I'm still unclear how far my cleanup can / should extend.

My original plan was to remove references to `CISM_USE_TRILINOS`.

But then it seems like this logic
https://github.com/ESMCI/cime/blob/1bcacca70fea0bf66b13909b787822ddc54f9c93/scripts/lib/CIME/build.py#L695-L702
would lead to `USE_TRILINOS` always being FALSE. So that led me to think that I should completely remove `USE_TRILINOS`. But based on @rljacob 's comment, E3SM is using TRILINOS, so I'm wondering how that works: do you use the `USE_TRILINOS` XML variable or not? And what about the `TRILINOS_PATH` config_compilers variable? I'm wondering if it's safe to remove those or if you use them.

@jedwards4b - regarding the `USE_CXX` flag: As I look into this more, I'm feeling like it would be a bit too much of a peeling onion to remove this right now, because it's tied in with `SUPPORTS_CXX` and other CXX variables in config_compilers, and E3SM seems to still need this. So I'm thinking that, for now, USE_CXX would stay in place, but would always be set to FALSE in our Makefile. Does that seem okay?

**Comment by jedwards4b** [comment]
As I understand it E3SM no longer uses the Makefile so we can do whatever we need with it.  @jgfouca is this true?

**Comment by billsacks** [comment]
@jedwards4b to clarify what I meant: Although I could easily remove `USE_CXX` and other C++-related code from our Makefile, it would then leave a number of non-functional variables in config_compilers: I think everything related to CXX there. So I could remove all of those CXX variables from our config_compilers... but this started to feel like a more involved and risky task than what I originally set out to do. That said, I could take a stab at it if you think this level of cleanup would be worthwhile - e.g., if it's causing some pain to have these CXX variables around and we're pretty sure we're not going to want them anytime soon.

**Comment by mperego** [comment]
@ikalash I think these flags have to do with CISM Albany, can you comment on this?

**Comment by ikalash** [comment]
This actually predates my work on CISM.  @agsalin can probably comment on its original creation.  Basically initially CISM ran w/o Trilinos.  Then Andy hooked it up to Trilinos solvers, which led to the configure option.  My CISM-Albany interface requires Trilinos and it's in a feature branch, not in master E3SM.  I am not sure if you need the option in CISM master.  You could ask Steve Price or Matt Hoffman.

**Comment by mperego** [comment]
Thanks @ikalash. I'm checking with Steve and Matt. The USE_TRILINOS flag might be useful to build MALI in E3SM wiht the old build system (as a backup option).

**Comment by billsacks** [comment]
@ikalash @mperego - I'm pretty sure I put these flags in originally, working with @agsalin and others. What I'm not sure of is whether / how this logic gets invoked in E3SM now. But actually, you helped clarify one thing for me: I wasn't sure if CISM is still used in E3SM, but based on your comment, it sounds like it is, at least in some feature branches. So based on that, I guess I shouldn't remove this CISM logic. Does that sound right?

----

@ikalash and others working with CISM in E3SM: that leads me to another question: While I was looking into this cleanup, I noticed this block of code:
https://github.com/ESMCI/cime/blob/1bcacca70fea0bf66b13909b787822ddc54f9c93/scripts/lib/CIME/case/case_setup.py#L224-L226

I was about to remove it, because we don't need it anymore in CESM-CISM. Do you know if you still need it in E3SM? We used to use this to provide scripts that a user or developer could invoke to regenerate the i/o files, according to the procedure here <https://github.com/ESCOMP/CISM-wrapper/wiki/Regenerating-default-io-files>. A couple of years ago, @Katetc changed the CESM-CISM build process so that the i/o files are auto-generated at build time, just like what's done in the standalone CISM build. Do you know whether this is still needed in E3SM-CISM (i.e., do you ever use a procedure like the one documented in that wiki page?) or if it's safe to remove this call?

**Comment by ikalash** [comment]
@billsacks : sorry, I'm not the right one to ask about this.  I don't work on CISM in CESM - I just own the ali_interface branch of CISM, which contains the interface b/w CISM and ALI.  We never released that as a part of CISM - it's in the E3SM repo.

**Comment by jgfouca** [comment]
@jedwards4b , we still use it to build sharedlibs.

**Comment by jonbob** [comment]
@jgfouca - you understand the build system way better than I do (which is close to not at all), but my quick look showed this gets set only when the glc model is cism? And that model is not one of the E3SM components. But we can look offline, or I'm happy to simply not risk breaking anything

**Comment by jgfouca** [comment]
@jonbob , apologies, my comment was too brief and unclear. I meant that we do still use the classic CIME Makefile in our builds in order to build some of our sharedlibs (it looks like PIO, MCT, mpi-serial, csm_share all still use it). I'm pretty confident that we do not need any TRILINOS or USE_CXX stuff for these sharedlibs. We do use that stuff to build our components, but as many have already pointed out, those builds are going through our CMake system now. @billsacks should feel free to make his cleanups to the Makefile. Changes to build.py make me a bit more nervous since those could impact us.

**Comment by jonbob** [comment]
Thanks @jgfouca - that makes plenty of sense then. And thanks again for explaining

**Comment by billsacks** [comment]
Thank you all for your input. I'm still not very clear on the status of CISM within E3SM, but my takeaway from all of this is that any cleanup I try to do might break some branch(es) of E3SM. There isn't a huge need to do this cleanup as far as I'm concerned, so I won't touch this for now.
