### ISSUE TITLE
Attempt to fetch from allocatable variable DRIVER_TASK_NODE_MAP when it is not allocated

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3790]
The code introduced in #3788 appears to be generating an error when compiled in debug mode.
I tried the following test SMS_D.T62_g16.AIAF and got error:

0:forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable DRIVER_TASK_NODE_MAP when it is not allocated
0:
0:Image              PC                Routine            Line        Source             
0:cesm.exe           000000000158DCB6  Unknown               Unknown  Unknown
0:cesm.exe           000000000042E6C7  cime_comp_mod_mp_        2482  cime_comp_mod.F90
0:cesm.exe           0000000000464BCC  MAIN__                    153  cime_driver.F90
0:cesm.exe           0000000000407922  Unknown               Unknown  Unknown
0:libc.so.6          00002B97AEF726E5  __libc_start_main     Unknown  Unknown
0:cesm.exe           0000000000407829  Unknown               Unknown  Unknown

**Comment by amametjanov** [comment]
I've been trying to reproduce the error. SMS_D.T62_g16.AIAF works with `CIME_MODEL=e3sm`. Tried with `CIME_MODEL=cesm` on cori-haswell, but ran into other unrelated errors.

The array is allocated in src/drivers/mct/shr/seq_comm_mct.F90, TIMING macro is [defined here](https://github.com/ESMCI/cime/blob/master/src/build_scripts/buildlib.csm_share#L125) and is not e3sm-specific. If the build above did not involve `seq_comm_mct.F90`, can you please post steps to reproduce on Cori ? Thanks.

**Comment by klindsay28** [comment]
The allocation of `driver_task_node_map` in `src/drivers/mct/shr/seq_comm_mct.F90` is inside a `(info_taskmap_model > 0)` conditional, while the usage of `driver_task_node_map` in `src/drivers/mct/main/cime_comp_mod.F90` is not inside such a conditional.

The default value of `info_taskmap_model` in `src/drivers/mct/cime_config/config_component_e3sm.xml` is `2`, while the default in `src/drivers/mct/cime_config/config_component_cesm.xml` is `0`. Perhaps you can reproduce the error if you set `info_taskmap_model=0`.

**Comment by amametjanov** [comment]
Thanks! Any objections to turning on task-to-node mapping with INFO_TASKMAP_MODEL=1 in cesm? With it, cesm.log should have extra output of how many MPI tasks are bound to node by the resource manager (like Slurm): e.g. single-node 64x1 run of `SMS.T62_g16.AIAF.cori-knl_intel` has in e3sm.log
```
 0: 64 pes participating in computation of coupled model
 0: --------------------------------------------------------------
 0: GLOBAL communicator : 1 nodes, 64 MPI tasks
 0: COMMUNICATOR NODE # [NODE NAME] : (# OF MPI TASKS) TASK # LIST
 0: GLOBAL NODE 0 [ nid02522 ] : ( 64 MPI TASKS ) 0-63
 0: --------------------------------------------------------------
```
This can be a useful check of compacting tasks into as few nodes as possible: e.g. Slurm can spread out tasks one-per-node when there are more allocated cores than tasks.

**Comment by jedwards4b** [comment]
@amametjanov why don't you fix the bug and let us decide whether we want the additional info?

**Comment by jedwards4b** [comment]
To be clear: we welcome the new information but info_taskmap_model=0 still needs to work.
