### ISSUE TITLE
Enhancement to nmlgen: Allow setting defaults for specific namelist groups conditionally

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3792]
(Preface: I know that we are not very invested in continued maintenance of nmlgen.py for CESM because of @alperaltuntas 's new infrastructure, but I think that what I'm proposing here will be pretty easy to implement, and will help with CISM's buildnml python rewrite.)

For CISM's build-namelist, there are a few namelist groups that we only add to the namelist if a certain other namelist variable has a certain setting. For example, we only add the isostasy namelist group if the isostasy namelist variable is set to "on". This conditional addition of namelist groups can be done already, but it's currently awkward to add error checking to confirm that the user hasn't tried to set any invalid items in user_nl_cism: for example, that they aren't trying to set the value for some isostasy-related variable when isostasy is off (so the setting they're trying to make would never appear in the generated namelist). (Currently, I think this can only be done by listing all variables in the group explicitly in buildnml, which goes against the data-driven design.)

I think I can support this error checking with a few small changes to nmlgen.py and namelist_definition.py; I plan to do this in the next day or so unless anyone tells me that it's a terrible idea :-)

- Add a new optional argument to `init_defaults` (in nmlgen.py) and `set_nodes` (in namelist_definition.py): `skip_default_for_groups`. If provided, this should be a list of group names; any namelist variable in one of the given groups will _not_ be added to the list of `default_nodes`.

- Add a new function in `nmlgen.py`: `add_defaults_for_group(group)`. This will call `add_default` for all variables in the given group.

- Add a new function in `nmlgen.py`: `confirm_empty(group)`. This will ensure that no variables have had values set in the given group.

Then, in CISM, we can have code like this:

```python
nmlgen.init_defaults(infile, config, skip_default_for_groups=["isostasy", ...])

# ...

if int(nmlgen.get_value("isostasy")) == _ISOSTASY_ON:
    nmlgen.add_defaults_for_group("isostasy")
else:
    nmlgen.confirm_empty("isostasy")
```

**Comment by ekluzek** [comment]
This could be useful for CTSM where we have the same sort of thing going on. But, right now we do a lot of custom code checking to ensure this is true. This general check would be an improvement to what we currently do.

**Comment by billsacks** [comment]
@ekluzek Thanks. Yes, I was thinking that, too, though I'm really hoping that we'll be able to leverage @alperaltuntas 's infrastructure for CTSM. (I have time pressure to get CISM's in, and it's much easier than CTSM's, so I'm going ahead with it before @alperaltuntas 's infrastructure has been incorporated.)
