### ISSUE TITLE
Duplicate call to set_nodes in nmlgen:set_defaults looks suspicious

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3795]
I'm not 100% sure this is a bug, but it looks like one to me... if so, my guess is that it's just slowing things down a bit, probably not causing incorrect results, but it could still be worth fixing:

It looks to me like set_nodes is unnecessarily called twice here, and that only the second call (which saves the return results) should be done:

https://github.com/ESMCI/cime/blob/c258cdf083e55c950b47562408e96a27a8411b74/scripts/lib/CIME/nmlgen.py#L106-L109

But again, I'm not 100% sure that this is a bug: it may be that it needs to be called twice for some reason.

It looks like this came in with @mvertens 's overhaul of this code in #965. @mvertens can you comment on this?

**Comment by billsacks** [comment]
Here's another suspicious duplication: It looks like `self._entry_nodes.append(node)` will be called twice for each node:

https://github.com/ESMCI/cime/blob/c258cdf083e55c950b47562408e96a27a8411b74/scripts/lib/CIME/XML/namelist_definition.py#L103-L116

**Comment by jasonb5** [comment]
@billsacks
It looks like both cases cause duplications. 
https://github.com/ESMCI/cime/blob/83fbedf011b5e53a6cbc73449355ef79fd183c52/scripts/lib/CIME/XML/namelist_definition.py#L85-L86
The **first** case causes duplications in `_entry_nodes` and `_entry_ids`.
The **second** case causes duplications in `_entry_nodes`.
The end results is 4x as many values in `_entry_nodes` and 2x in `_entry_ids`.

Theses duplications don't appear to be an issue but removing the duplicate call and refacting reduces the total time spent in `set_nodes` from 0.006 seconds to 0.001 for my specific test case.

**Comment by billsacks** [comment]
Thanks a lot for your investigation of this, @jasonb5 !
