### ISSUE TITLE
PET test does not always rerun correctly 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3805]
When rerunning a PET test after a failed run the state is not restored correctly.   If the POP ocn model is involved the
new run will stop in the case.build with an error:
```
ERROR: Missing required pointer_file 
```
this is because the CONTINUE_RUN variable in the case is set to TRUE, you can work around this by manually setting CONTINUE_RUN=FALSE.   But then when the PET test is submitted it does not run the first case and goes directly to the case2run.  Once that run completes (and fails because run1 was not done) the test appears to be in a correct initial state again and another run will proceed correctly.

**Comment by billsacks** [comment]
If this is restricted to PET, my guess is that this is related to the fact that PET is a multi-submit test, and so there is some bug with the handling of multi-submit: at a glance, I don't see anything else that is fundamentally different between PET and other test types.

**Comment by jgfouca** [comment]
Giving this one to @WesCoomber since he has fixed similar issues with multisubmit tests before.

**Comment by jasonb5** [comment]
@jedwards4b I have a couple questions about reproducing this issue.
- Was this a newly created test that it failed?
- What phase did it fail in? (I was assuming it was the RUN_PHASE but I want to double check)
- When you reran the test was it using `create_test --use-existing ...` or calling `case.submit` directly?

**Comment by jedwards4b** [comment]
I know that I reran using case.submit.
I'm pretty sure it failed in the run phase.
I'll try to reproduce and get back to you.

**Comment by jasonb5** [comment]
@jedwards4b Sounds good.

I think I may have reproduced the issue:

Initial conditions from "failed" job:
- ./xmlchange IS_FIRST_RUN=FALSE
- ./xmlchange RESUBMIT=0
- Set the `RUN` to `PEND` in `TestStatus`
- Remove all netCDF outputs from the run directory (if using an existing case)

Calling `case.submit` results in the `COMPARE` phase failing, skipping phase 1 of the test and only generating the output from case2run.

**Comment by jasonb5** [comment]
@jedwards4b Just wanted to check-in to see if you had an update on this? I added some details on how I was able to reproduce something similar to what you described.

**Comment by jedwards4b** [comment]
No - I think that your reproducer is correct.

**Comment by billsacks** [comment]
Possibly somewhat related: #3933 . I think the underlying issue is different (for one thing, it isn't related to multi-submit tests), but there may be some overlap: I think both of these are connected to the logic for when the logic in `_resetup_case` is and isn't triggered. I have a sense of what's going on in #3933 and a possible fix, so I'll work on that in the next few days.

**Comment by jasonb5** [comment]
I'll move #3924 out of draft for a review as it fixes the above scenario.
