### ISSUE TITLE
mismatch of xml attributes 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3806]
In file config_compilers.xml we use an attribute compile_threaded and set it to string "TRUE" or "FALSE" 
in file config_machines.xsd there is an attribute threaded which is set to "0" or "1" but I don't see any use of this attribute in the cesm or ufs config_machines.xml files.   Is it used in e3sm?  If not I propose to change this to compile_threaded to be consistant with the config_compilers.xml attribute - any objections?

**Comment by rljacob** [comment]
Tag @amametjanov

**Comment by jgfouca** [comment]
@jedwards4b , we don't appear to be using that attribute:
```
% grep -i threaded config_machines.xml 
     for CICE to run threaded on this machine -->
%
```

**Comment by amametjanov** [comment]
Yes, `threaded` is not used in e3sm and can be removed (instead of rename) from the schema. config_machines.xml uses `SMP_PRESENT in ["TRUE", "FALSE"]` for run-time mods.
