### ISSUE TITLE
Plan to remove mct_mod.F90

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3815]
I'd like to remove mct_mod.F90 in cime/src/share/util and move unique functions to shr_mct_mod

MCT is going to have its own convenience module called "mct_mod" (https://github.com/MCSclimate/MCT/pull/65) so need to at least rename to avoid conflicts.   The CIME mct_mod.F90 has a few additional functions which I'll move to the existing shr_mct_mod.F90

**Comment by billsacks** [comment]
Thanks for the heads-up, @rljacob . I see that nearly every CESM component has use statements of `mct_mod`. How much time pressure is there on your end to do this? I'm wondering if this can wait until after the CIME code split that @mvertens has been discussing (because then this would not impact CESM)?

**Comment by rljacob** [comment]
Oh I didn't know use of mct_mod had extended beyond CIME.  It can wait.  Or I'll just rename the one in MCT.

**Comment by rljacob** [comment]
Did we discuss if we would still share the content of CIME/src/externals?  Because if we do, then even post split this would effect CESM if I updated externals/mct to a version with mct_mod (and did nothing else).

**Comment by rljacob** [comment]
externals/mct in CIME is a subtree.  What I can do is just remove MCTs mct_mod.F90 before I do a PR to update it.  Then there is never a conflict.   So I won't remove/rename the CIME mct_mod.F90.

**Comment by billsacks** [comment]
Thanks @rljacob . I don't know if we came to a conclusion about what to do about the stuff in src/externals. But given that we want cime to just end up with the CCS, it probably doesn't make sense for mct to be in cime long-term. If you're happy with your solution at least for now, that would be helpful - thanks.

**Comment by andreapiacentini** [comment]
There are less than 10 oasis routines using mct_mod. Feel free to rename it accordingly to CIME requirements, if needed, and OASIS will easily follow.

**Comment by jedwards4b** [comment]
Reopening as planned.

**Comment by ekluzek** [comment]
This remains important to do.
