### ISSUE TITLE
Add a "case-family" argument to create_newcase

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3825]
In order to complete all the simulations required for DECK, many cases will have to be run.   Each run (pi-control, 20th centruy, SSP85) will start with separate invocations of "create_newcase" with a different argument to "--case" for each simulation and that argument is recorded in the CASE variable in env_run.xml.

For constructing databases and other provenance tools, it would be useful to indicate that each case is part of something larger (in this instance, a DECK run).   The proposal is to add an optional argument like --case-family to create_newcase.  That value would be recorded in env_run.xml under CASE_FAMILY.

So you would have "create_newcase --case picontolCESM3 --case-family DECK_CESM3  --compset ....."

I'm not married to "--case-family" as the name of this argument.  "--simulation-campaign" was also suggested.

**Comment by rljacob** [comment]
Yes could could add a common string to all the case names but that doesn't make it easier to parse in xml and our case names are already getting long.

**Comment by jgfouca** [comment]
@rljacob , this looks pretty easy. Should I assign to @WesCoomber ? I assume you don't want to be the one writing the code.

**Comment by rljacob** [comment]
Yes go ahead.

**Comment by rljacob** [comment]
Maybe --case-group would be a better name for this option.

**Comment by sarats** [comment]
Ideally, the valid argument list should be maintained along with the code. Allowing free-form text would still pose some of the issues we are trying to fix.

**Comment by rljacob** [comment]
There are already rules for "case" and "case-group" can just follow those.

**Comment by rljacob** [comment]
Oh wait you want a finite list of specific possible values for "case-group"?   I was referring to what characters are allowed in the string.

**Comment by sarats** [comment]
Thinking out loud:

* Defined set of choices would prevent against typos and too many arbitrary (non-official) groups which will hinder tracking official simulation campaigns.
* However, letting folks enter free-form text provides flexibility. But it shifts the quality control burden to PACE etc. to aggregate important campaigns.

**Comment by rljacob** [comment]
There are all kinds of ways people might want to group cases so I don't think we can have a list in the source that you have to edit with a PR to add more options.   They way to make sure people doing simulation campaigns don't screw up is have double and triple checks on their case dir.

**Comment by rljacob** [comment]
On developers telecon, we agreed this was worth doing.

@WesCoomber please make implementing this your top priority.  We need it by end of this week.   Lets use --case-group as the option name.
