### ISSUE TITLE
crash in shr_flux_mod.F90

### ISSUE THREAD

**Issue by cecilehannay** [ESMCI/cime#3826]
We have had issues with the model crashing in the surface fluxes computation with the new vertical CAM grid. (see: issue https://github.com/ESCOMP/CAM/issues/297)

The model is failing because the denominator in
rd = rdn / (1.0_R8 + rdn/loc_karman*(alz-psimh))
becomes negative. 

Bill Large suggested ways to fix the issue.
- we did a run where we force U10n > 0.2 m/s, and it seems to overcome the stability problem.
- We did another where we prevent u10n from going negative in the first place by enforcing a negative minimum for
( rdn/loc_karman*(alz-psimh)). We used ( rdn/loc_karman*(alz-psimh))> -0.5 and it also overcomes the issue. 

As this is a CIME issue we are moving this issue from the CAM repo to the CIME repo.

**Comment by jedwards4b** [comment]
We can implement either of these solutions which do you prefer and can you provide a science justification to document it?

**Comment by cecilehannay** [comment]
Thanks. I did two runs to test these. We need to look at the results and then we can decide which solution we want to keep.

**Comment by cecilehannay** [comment]
The fix we have been using is in:
/glade/p/cesmdata/cseg/runs/cesm2_0/f.e21.FWscHIST.ne30_L48_BL10_v3_tag20201111.001/SourceMods/src.drv/shr_flux_mod.F90

The original file is: 
/glade/p/cesmdata/cseg/runs/cesm2_0/f.e21.FWscHIST.ne30_L48_BL10_v3_tag20201111.001/SourceMods/src.drv/shr_flux_mod.F90_orig

Basically we prevent the denominator to go negative with:
<            rd   = rdn / (1.0_R8 + max( rdn/loc_karman*(alz-psimh), -0.5_r8))
---
>            rd   = rdn / (1.0_R8 + rdn/loc_karman*(alz-psimh))

**Comment by cecilehannay** [comment]
Some diags with the fix: 
https://webext.cgd.ucar.edu/FWscHIST/f.e21.FWscHIST.ne30_L48_tag20201111_sfcflxfix.001/atm/f.e21.FWscHIST.ne30_L48_tag20201111_sfcflxfix.001_yrs1979-1987-f.e21.FWscHIST.ne30_L48_tag20201111.001_yrs1979-1987/

**Comment by rljacob** [comment]
I'm curious, how high is the resolution in this new vertical grid?

**Comment by billsacks** [comment]
@jedwards4b @cecilehannay @mvertens do you know if this has been fixed? If not, can you please move this issue to https://github.com/escomp/cesm_share (or to https://github.com/escomp/cmeps, where @mvertens intends to move shr_flux_mod)?

**Comment by jedwards4b** [comment]
This was fixed in https://github.com/ESCOMP/CESM_share/pull/7
