### ISSUE TITLE
Add tail from *cprnc.out files in TestStatus.log

### ISSUE THREAD

**Issue by oksanaguba** [ESMCI/cime#3831]
If possible, can we have a tail -n 20 for *nc.cprnc.out files in TestStatus.log ? it is a pain to open each file just for the last few lines. One example is when diffs are only fill diffs, yet, each *cprnc.out file in a suite needs to be opened to confirm that the diffs are harmless.

**Comment by jedwards4b** [comment]
I honestly don't see how that is going to be more convenient then just grepping the cprnc.out files.
```
grep diff *.cprnc.out
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0001.hi.0001-01-02-00000.nc.cprnc.out:          of which      0 had non-zero differences
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0001.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had differences in fill patterns
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0001.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had different dimension sizes
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0001.hi.0001-01-02-00000.nc.cprnc.out:  diff_test: the two files seem to be IDENTICAL 
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0002.hi.0001-01-02-00000.nc.cprnc.out:          of which      0 had non-zero differences
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0002.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had differences in fill patterns
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0002.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had different dimension sizes
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0002.hi.0001-01-02-00000.nc.cprnc.out:  diff_test: the two files seem to be IDENTICAL 
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0003.hi.0001-01-02-00000.nc.cprnc.out:          of which      0 had non-zero differences
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0003.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had differences in fill patterns
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0003.hi.0001-01-02-00000.nc.cprnc.out:               and      0 had different dimension sizes
SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel.C.20210107_133557_9msb36.cpl_0003.hi.0001-01-02-00000.nc.cprnc.out:  diff_test: the two files seem to be IDENTICAL 
```

**Comment by rljacob** [comment]
In our case, some of the machines are not easily accessible and all we have is the TestStatus.Log file uploaded to cdash.

**Comment by rljacob** [comment]
And for machines we can log in to, its still easier to just click through the various TestStatus.log files.

**Comment by billsacks** [comment]
This seems like a good idea: it seems like it could make things more convenient in some cases, and I don't see much downside. Would you do this all the time, or only if cprnc shows differences?

I'd also like to take this opportunity to remind people of the summarize_cprnc_diffs tool that lives alongside cprnc. This is something I put together in the pre-cime days (when we were writing things like this in perl), and still use heavily, but I think most other people aren't aware of it. You can run it with the -h flag for details, but briefly: I use this to verify that a set of tests only changes answers for certain fields and/or only has roundoff-level differences (or fill differences, as in this situation). I usually run it from the test directory (the one containing all the test cases), in which case the usage is the following, at least for the CESM testing workflow:

/path/to/summarize_cprnc_diffs -basedir . -testid '0123_4567_*'

Note the '.' after -basedir (you can also give some other path); of course, replace the testid with the actual testid; note that wildcards are supported in the testid, so I usually run it like above so it picks up all compilers at once (again, assuming the CESM workflow; I'm not sure if that differs with the e3sm workflow). It will generate 3 output files in the current directory which have the same content but differ in how they are sorted; see the help message for details.

I have thought it would be good to integrate that more into the cime test system....
