### ISSUE TITLE
default_run_exe

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3833]
I have a need to overwrite default_run_exe on a system (frontera).  The reason is that performance on this system is much improved if the exe is read from a local disk instead of the shared one.  So 
 <executable>sbcast ${EXEROOT}/cesm.exe /tmp/cesm.exe; ibrun</executable>

and 
 <default_run_exe>/tmp/cesm.exe </default_run_exe>

But I don't see a way to change the run_exe for one system or a subset of systems.

**Comment by jedwards4b** [comment]
It turns out there is code to handle this in env_mach_specific.py but not in config_machines.xsd,  I have a fix on the way.

**Comment by jedwards4b** [comment]
On the other hand it turns out this has already been implemented on the trunk but not on the ihesp branch I am currently working with, I will backport.

**Comment by jedwards4b** [comment]
There is a bug here.  In xsd the run_exe is expected to be under the mpirun node, it makes sense that it go there.
However in env_mach_specific.py populate get_first_child_nodes is used so the run_exe setting is never found.

**Comment by jedwards4b** [comment]
I've identified PR #3099 as the one that introduced this code.  I've also identified a problem in my fix in PR #3836 - the run_exe as defined in config_machines.xml is dependent on the MPILIB but there is no check for that in env_mach_specific.xml so testing on frontera has reveled that although I intended this change to apply only to impi it is
also used in mpich and mpi-serial - it causes failures in both these cases since the path in question is only created for impi.

**Comment by jedwards4b** [comment]
@jhkennedy I would like to bring your attention to this issue.

**Comment by jhkennedy** [comment]
@jedwards4b I'll take a look; it's been a year since I've looked at CIME some it might take me a little wrap my head around it and get setup for testing again

**Comment by jedwards4b** [comment]
@jhkennedy I hadn't realized you had left, I've solved the problem in PR #3836, you are welcome to review it if you like.
