### ISSUE TITLE
Teststatus.log error points to a non-existent directory

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3838]
In a recent run of one of our test suites, the TestStatus.log in cdash indicated a build fail:

ERROR: /gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_master/ACME/cime/src/build_scripts/buildlib.gptl FAILED, cat /lcrc/group/e3sm/e3smtest/scratch/chrys/ERS.f19_f19.IELM.chrysalis_intel.JMasterIntegration20210126_174820/bld/gptl.bldlog.210126-174839

See https://my.cdash.org/test/23309513

But the directory "/lcrc/group/e3sm/e3smtest/scratch/chrys/ERS.f19_f19.IELM.chrysalis_intel.JMasterIntegration20210126_174820" doesn't exist when I go to check that file.

Instead, there's a directory with a different postfix:   "/lcrc/group/e3sm/e3smtest/scratch/chrys/ERS.f19_f19.IELM.chrysalis_intel.JMasterIntegration20210127_035344"
And that directory has what looks like a successful build.

I can't tell if this is a create_test bug or a problem with how the E3SM jenkins interacts with create_test.

**Comment by jgfouca** [comment]
The job was run twice in close proximity when wade was setting things up. The old cases were archived or deleted.
