### ISSUE TITLE
CIME issue with extra files that have ".nc" in the names during phase BASELINE

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#3852]
Use a temp SCORPIO feature branch to reproduce this issue with a simple
E3SM test. The feature branch creates dummy "****.nc.xx" files in the test
run directory for testing.

Steps on a machine supported by E3SM:
```
git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM

git submodule update --init

cd externals/scorpio
git checkout dqwu/create_dummy_files

cd ../../cime/scripts
./create_test SMS.f09_g16_a.IGELM_MLI -b master --baseline-root=specified_baseline_directory --compare
```

TestStatus.log has some messages like below:
```
File '****.mali.hist.am.0001-01-01_00000.nc.xx' had no compare counterpart in 'specified_baseline_directory/SMS.f09_g16_a.IGELM_MLI.<machine>_<compiler>' with suffix ''
File 'mali.hist.am.0001-01-01_00000.nc.base' had no original counterpart in 'specified_test_run_directory' with suffix ''
```

**Comment by rljacob** [comment]
It could be that cprnc should only compare files that end in ".nc" instead of files with ".nc" anywhere in the name.

Or we should rename these files.

**Comment by rljacob** [comment]
Does the testsystem add ".base" at the end of ".nc" files?   That means we can't tighten the regex/glob.

**Comment by jedwards4b** [comment]
The test system adds .base, it may also optionally add any other extension. 
Some examples are:
   run_two_suffix = 'restart', 
   run_two_suffix = 'single_instance',
   run_two_suffix = 'multiinst',
   run_two_suffix = "singleinst",

**Comment by jgfouca** [comment]
@dqwu probably the easiest thing to do is to change the .nc.xx extension. How hard would that be?

**Comment by dqwu** [comment]
> @dqwu probably the easiest thing to do is to change the .nc.xx extension. How hard would that be?

My current workaround to test ADIOS type is to deleting the BP files directory after conversion which works. We also considering updating the ADIOS format (BP files directory) from "XXXX.nc.bp.dir" to "XXXX.bp.dir" as suggested by Rob.

**Comment by jgfouca** [comment]
@dqwu those are both good solutions. It looks like anything with `.nc` in the name is going to get noticed by CIME:

This is the regex that is used deep within CIME to identify hist files
```
m = re.search("(.+)_[0-9]{4}(.+.nc)",normalized_name)
```

**Comment by dqwu** [comment]
@jgfouca 
You can close this issue since we have other solutions such that no changes need to be done on CIME side so far.
