### ISSUE TITLE
How should we move forward with cprnc for CESM testing?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3854]
First a note: I'm labeling this as cesm-only because we can make a decision for cesm here that won't impact e3sm or others. But if we can come to some general agreement / recommendation across all modeling systems, then that would be even better.

I feel pretty strongly that we need to replace the way we currently manage cprnc with a procedure that lets us point to different cprnc versions for different cime versions. Currently, we point to the same cprnc location for all cime versions. This has the following problems:
- Adding new functionality to cprnc can be challenging because of the need for maintaining backwards compatibility
- Updating the version of cprnc on the machine sometimes causes people's test suites to fail if they are running during the time when cprnc is being updated
- We repeatedly run into permissions issues since multiple people are managing the cprnc build on our main test machines

I started down the path of addressing this via #3419 but ran into a couple of minor issues, so wanted to check in with others before going further down this path. The issues I ran into are:
- #3849: Some fake tests fail on machines where ccsm_cprnc isn't defined. At the very least, we would need to solve that issue before doing #3419.
- cprnc is built multiple times in a run of scripts_regression_tests. I'm not sure if this is actually a significant issue: It is only built once for each compiler in a given run of a create_test. From what I can tell from adding some extra diagnostic printing in the build (https://github.com/billsacks/cime/commit/90b7bf42bc70851617b23e1cf851640189136447), it looks like cprnc is built 7 times in the course of running scripts_regression_tests (it's possible that I missed some builds due to them being done in a way that bypassed my prints, but the total time taken by scripts_regression_tests was about the same for my branch with CCSM_CPRNC undefined on cheyenne and on master, so I don't think I'm missing *too* much). Each build takes 11-12 seconds on cheyenne-intel, so the total time spent building cprnc is about 80 seconds, which is about 2% of the total test time. (I'm not sure if parallelization in scripts_regression_tests makes it so this doesn't actually take this much time in terms of wallclock time?) @jedwards4b has suggested putting in place a mechanism so that cprnc is only built once for a whole run of scripts_regression_tests. That seems like a good idea. It has the minor downside that scripts_regression_tests then wouldn't be testing exactly the same procedure as is used in practice (because the create_test invocation would be using a pre-built cprnc), but that's probably okay.
- Related to the above build time issue: I feel like the 12 second build time of cprnc is small in the context of a full test suite, but could be considered significant in the context of a single test: in this case, the cprnc build time could account for a few percent of the total test build time.

So I would like to hear opinions from others about how we should proceed with this. The options I see are:

1. Move ahead with removing the definition of CCSM_CPRNC for cheyenne and izumi (#3419). This will mean that all CESM users running create_test will end up building cprnc on the fly. To do this, we would need to resolve #3849 and possibly introduce a mechanism so that scripts_regression_tests builds cprnc once up-front and then points to that for everything else done as part of that test suite. It will increase the build time of tests by about 12 seconds, whether building a single test or a whole test suite.

2. For now, maintain a cprnc build in the location pointed to by CCSM_CPRNC. Add an argument to `create_test` like `--force-build-cprnc` that we incorporate into our standard create_test workflow (e.g., including it in the CTSM, CAM and CESM testing scripts): #3418 . An alternative (which I would prefer) would be to make this the default, but provide an option like `--use-prebuilt-cprnc`; we could then consider using that option where needed in scripts_regression_tests. This has the advantage of letting people use either pre-built versions or build cprnc on the fly, depending on what best suits their workflow. But it would leave some of the above issues with maintaining cprnc still unresolved.

3. This is an option I just thought of while writing this issue, which feels somewhat more conservative than the other options (for better or for worse): Still maintain cprnc builds on cheyenne and izumi and point to them with CCSM_CPRNC. However, point to a *versioned* location. So, rather than pointing to some generic location like `$ENV{CESMDATAROOT}/tools/cime/tools/cprnc/cprnc.cheyenne`, the path would have some version information. I'd suggest using the short version of the cime hash from which the build was made. Then, if we want to use an updated build of cprnc, we would create a new directory with a new cime version, build cprnc there, and then update cime to point to this new version. This means we would still need to maintain a cprnc build on the system, but it would get around some of the biggest issues with doing so (listed at the top of this issue). Side-note: we would maintain a sym link pointing to the most recent version, so you can invoke 'cprnc' manually and get this most recent version.

What do others think?

<details>
  <summary>Spoiler alert: click for Bill's current feelings</summary>
I'm starting to think that (3) might be the best option, at least for now. It would be a pain if cprnc changed frequently, but given that it only changes a couple of times a year, the overhead seems fairly small and it avoids any possible issues with (1) and (2). Long-term I may still be in favor of building cprnc on the fly, but since some people have reservations with that, this could be a good compromise solution.
</details>

**Comment by jedwards4b** [comment]
I think option 3 is fine.

**Comment by rljacob** [comment]
I kind of like 2 but the default would be to use the pre-built since I think that's the most common case.  The only time you want to rebuild cprnc is on the rare times when cprnc is under development.   An argument like --use-custom-cprnc would build cprnc from latest source in a hidden directory in /tmp or something that was only used for that run of the test suite .

**Comment by cacraigucar** [comment]
I am okay with #3 as long as long as "could maintain a sym link" becomes "will maintain a sym link".  The last thing users who routinely use cprnc on the command line will want to do is to figure out where it actually is located and what version they should use.

**Comment by billsacks** [comment]
> I am okay with #3 as long as long as "could maintain a sym link" becomes "will maintain a sym link". The last thing users who routinely use cprnc on the command line will want to do is to figure out where it actually is located and what version they should use.

Agreed. I have changed "could maintain" to "would maintain".

**Comment by fischer-ncar** [comment]
I'm against #1, sometimes I'll run a test suites across different compilers.  We would need to ensure that cprnc is built with gnu, since it's compatible with intel, pgi, and nag.  If cprnc is built with intel, it'll be incompatible with pgi, nag and gnu.  Just thought I should mention this, but it looks like no one else is liking #1.

I'm fine with #3, even though it means I'll be the one maintaining the links on cheyenne and izumi.

Another suggestion is if CCSM_CPRNC is unset, or the file doesn't exists, is to automatically build cprnc.  It might also be time to rename CSM_CPRNC to CESM_CPRNC.

**Comment by jedwards4b** [comment]
@fischer-ncar it's not true that cprnc built with one compiler is incompatible with another.  If you use the --rpath flag to point to shared libraries this is not an issue.

**Comment by billsacks** [comment]
@fischer-ncar - adding to what @jedwards4b said: I also don't think (1) is an issue because cprnc is built separately for each compiler in the test suite, so a given test should use a version built with the compiler for that test.

Regarding this:

> Another suggestion is if CCSM_CPRNC is unset, or the file doesn't exists, is to automatically build cprnc. 

That is the implementation already in place (implemented last year by @WesCoomber ). So my attempt to address #3419 simply involved deleting the CCSM_CPRNC definitions from config_machines for those machines.

> It might also be time to rename CSM_CPRNC to CESM_CPRNC.

Yes, though not CESM, since this is used more generally by CIME, not just by CESM.

**Comment by billsacks** [comment]
Thanks, all, for your input. I'm closing this discussion issue and opening a new one that summarizes what we want to do: #3858
