### ISSUE TITLE
_PNETCDF is no longer defined for Scorpio/PIO builds

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#3865]
After the CIME change, https://github.com/ESMCI/cime/commit/78acaa0658f66c99067a12d7845bc9cd46815c19 , _PNETCDF is no longer defined for CIME builds.

However CIME still uses this Macro in shr_pio_mod.F90, https://github.com/ESMCI/cime/blob/9fd7ee81ca04cf6524b70f8b6d6d2def10ac0dc7/src/share/util/shr_pio_mod.F90#L646

**Comment by jgfouca** [comment]
Fixed by #3864
