### ISSUE TITLE
Assumption of drv cime_config dir in build.py

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3888]
While trying to move the location of the driver outside of cime, first thing I ran in to was lines like these in build.py:

 config_dir = os.path.join(cimeroot,"src","drivers","mct","cime_config")

config_dir should instead use
$COMP_ROOT_DIR_CPL/cime_config"

$COMP_ROOT_DIR_CPL is part of the "version 2" config_files.xml spec.

E3SM will convert to version 2 ASAP.

**Comment by rljacob** [comment]
@fischer-ncar have you already run in to this?

**Comment by jedwards4b** [comment]
@rljacob I think e3sm moving to version 2 is what we need to remove these hardcoded cases - there are just a few.

**Comment by jgfouca** [comment]
@rljacob , do you want me to convert e3sm to V2 as part of this issue?

**Comment by rljacob** [comment]
I was going to convert separately since the conversion doesn't need any changes to CCS.  Let me post that PR first.

**Comment by fischer-ncar** [comment]
Yes, I ran into this.  I did the following.

config_dir = os.path.join(srcroot,"cpl7","drivers","mct","cime_config")

Where srcroot=cimeroot/.. or cimeroot or default_srcroot, depending if it's a cesm clone, cime clone, or --srcroot is used.

**Comment by rljacob** [comment]
Now I'm confused about the format of our config_files.xml.   e3sm has at the top:
```
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="definitions_variables.xsl" ?>

<entry_id version="2.0">
```
And cesm has
```
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" ?>

<entry_id version="2.0">
```

But e3sm has no "COMP_ROOT_DIR" variables.

**Comment by jgfouca** [comment]
I believe this has been sorted out.
