### ISSUE TITLE
Should case.set_value raise an exception if you try to set a variable not in an xml file?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#389]
I tried to force an error in a system test (LII.py) by calling self._case.set_value on some non-existent variable ('foo'). To my surprise, no exception was raised.

Looking at the Case.set_value code, it looks like it can work in two different ways: (1) If you specify a variable that exists in some xml file, then it sets that variable. I'm guessing that's the typical operation. But (2) if you specify a variable that is not in some xml file, then it sets this variable in its lookups dictionary.

The problem here is that this means that a typo in the variable to set will not be caught. For example, I ran an ERS test with this difference:

``` diff
--- a/utils/python/CIME/SystemTests/ers.py
+++ b/utils/python/CIME/SystemTests/ers.py
@@ -42,7 +42,7 @@ class ERS(SystemTestsCommon):
         expect(stop_new > 0, "ERROR: stop_n value %d too short %d %d"%(stop_new,stop_n,rest_n))

         self._case.set_value("STOP_N", stop_new)
-        self._case.set_value("CONTINUE_RUN", True)
+        self._case.set_value("CONTINUEEEE_RUN", True)
         self._case.set_value("REST_OPTION","never")
         self._case.flush()
         logger.info("doing an %s %s restart test"
```

The typo went undetected, and the ERS test ran two initial runs rather than doing a continue run.

This makes it more likely that system tests (and other code) won't work as intended.

I'd propose that set_value be split into two different routines:

(1) set_value works only on xml variables. If you give it an item not found in an xml file, it raises an exception

(2) set_lookup_value contains the last block of code currently in set_value:

``` python
            if item in self.lookups.keys() and self.lookups[item] is not None:
                logger.warn("Item %s already in lookups with value %s"%(item,self.lookups[item]))
            else:
                self.lookups[item] = value
```

**Comment by rljacob** [comment]
Is there an answer for this question?

**Comment by jedwards4b** [comment]
The lookups hash is designed to hold items that will be defined in xml objects before the xml object has been defined.     Using set_lookup_value would require knowing each location where this situation exists and handling it explicitly.   Mostly this code is in case configure and I think this is a feasible task.

**Comment by billsacks** [comment]
@jedwards4b : It looks like you have largely addressed this. I think the one thing that's still needed is raising an exception in Case.set_value if the given item wasn't found. At a glance, it looks like this could be done by raising an exception at the end of the method, after the for loop exits.

**Comment by rljacob** [comment]
@billsacks, still an issue?

**Comment by billsacks** [comment]
From looking at the `set_value` code, it looks like my last comment still should be addressed.
