### ISSUE TITLE
Default PE counts/layouts for CESM containers

### ISSUE THREAD

**Issue by briandobbins** [ESMCI/cime#3893]
Selecting default values for the CESM/CESM-Lab containers is a bit tricky.  For CESM-Lab (CESM + Jupyter Lab), the focus is typically on laptop/desktop/workstation use, where we currently set the MAX_TASKS_PER_NODE / MAX_MPITASKS_PER_NODE variables to the number of _detected_ cores in the host machine, which seems reasonable for most cases as it'll use the whole computer.   However, for cloud use, or HPC use of the base CESM container, this often doesn't make sense, since we want multi-node runs.

Long term, we want to determine that layout / count at runtime, but that's a ways off, so for now, what's the best approach here?  People can obviously set the layouts by hand, but maybe there's a use for a utility to say, "Sure, I'm using the container, but copy the PE layout from machine 'X' for this compset/resolution?"  This could be done automatically with a (new) environment variable, such that running the containerized CESM _on_ a system like Cheyenne inherits the Cheyenne layouts when specified, but this functionality doesn't yet exist.

It might also just be nice to have a simple option to change PE layouts, vs doing it by hand - eg:
./xmlchange --layout cheyenne:small _# Change to the 'small' PE layout for this compset for Cheyenne if it exists?_

(Not saying xmlchange is the right tool for this; it could be a 'create_layout' tool or something.)

This isn't a critical issue since all of this can be done by hand, but I figured it's worth opening for some discussion.

**Comment by briandobbins** [comment]
Prepping a PR for the two different containers and started to think about PE layout issues, and wanted input on options since I'm not well-versed in CIME's design yet.  This really doesn't apply to the existing examples of the containerized environment (more for laptops/desktops), but I'm testing an HPC version that is ideal for running on Cheyenne, or university systems, etc, with full network and Intel compiler performance.  But running it on Cheyenne will have different layouts than, say, NWSC3, or a university cluster, etc, so what's the best way of enabling known layouts on supported systems, but via the container?

Here are a few options:

1) Do nothing - people using the container will have to set PE counts themselves, even if running on known systems.  Eg, use the container on Cheyenne, and you won't get Cheyenne's tested PE layouts.  This doesn't seem ideal, but maybe also isn't that bad since we already have non-containerized versions on Cheyenne.  It's a minor pain when I want to duplicate a Cheyenne layout on a different-but-similar system though.

2) Add something like the './xmlchange --layout=<machine name>' option above, which can set the full layout for containerized systems to that of a named, supported system.  This adds an extra step to the container on HPC systems, which isn't ideal, but it's just a single one, and maybe helps, since if you're running on an unsupported-in-the-source system, but want a Cheyenne layout, you can get it easily.

3) Add a new environment variable, CIME_CONTAINER, analogous to CIME_MACHINE that, when true, overrides CIME_MACHINE for all things other than PE layouts.  Requires a bit of changes elsewhere in CIME to enable that logic, I imagine, but lets us set that in the containers by default, and allows people to use the standard 'create_newcase --machine <whatever>' to get the layout for that machine, while using the containerized settings for compilers, libraries, etc.  This gives a portable build, but with PE selection without adding a '--layout' option somewhere.  (You could even set CIME_MACHINE as an environment variable, run the container, and not need to specify the '--machine' option.)

Other ideas?  Thoughts?  @jedwards4b @billsacks (Wasn't sure who to tag, so I started with you two.  If this is easier to have an online discussion about, let me know and I'll set one up, then put the outcome in the issues here.)

**Comment by billsacks** [comment]
Interesting. I don't have a clear feeling right now of the best solution, but here are some thoughts.

First, are you pretty sure that it's *just* the PE layout that you're going to want to inherit from the physical machine? The reason I ask is: It would start to feel painful if you need to adjust the PE layout to your physical machine, and setting X, and setting Y – whereas it feels not too burdensome to have to run a single command for this.

In terms of solutions, I'm thinking about two design aspects of cime:
1. I think we try to avoid using environment variables unless they are *really* needed, instead preferring command-line flags
2. `create_newcase` already supports some command-line flags related to setting PE layouts, so it would make sense to me to add a new flag (or possibly expand the use of one of the existing flags) to support this use case

So with these thoughts in mind, I could imagine adding a new `create_newcase` argument like `--pe-layout-machine` so you could run with `--pe-layout-machine cheyenne`. Does that feel reasonable, or would you prefer a solution where this could more easily be set out-of-the-box via the container? (I can't tell if your solution (3) might allow things to Just Work without any extra settings made by the user.)

This comes back to my first question, though: it feels reasonable to add one command-line flag for this use case, but I wouldn't want to have to specify `--pe-layout-machine cheyenne --something-else cheyenne --and-another-thing cheyenne`. This may just be a naming thing: if we discover we want to set some other things, we could rename `--pe-layout-machine` to something like `--physical-machine` which would then influence a few settings.

 I haven't looked into what it would take to implement this; I suspect it would be similar to what's needed for your option (3).

**Comment by briandobbins** [comment]
Bill, your first point is very good - I need to think about this more, as it might be nice to _also_ inherit things like paths, and be able to automatically mount them in.  The catch is, it seems like there's two different scenarios:

1) We're _on_ a supported machine, but running the container - here we want to inherit the layout, but quite probably also the paths (eg, DIN_LOC_ROOT, DOUT_S, etc).
2) We're on an _unsupported_ machine, and want the PE layout from something similar (eg, on a 36-core per node AWS system, and want to use the B1850 layout from Cheyenne), but we _don't_ want the paths, since /glade won't exist there.

Doing this with _two_ arguments is easy, though maybe not elegant.  I'll try to think if we can do it in a reasonable way with just one.  I also would suggest maybe '--host-machine' or '--host-layout' as the names, or '--host' if we can do it in one.

Anyway, thanks for your thoughts.  I'll save this for later, and simply get in a working version of the machine entry, without needing the PE layout stuff for now.
