### ISSUE TITLE
maint5.6 pop ecosys archive error 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3896]
POP ecosys files of the form casename.pop.rh.ecosys.nyear1.1976-01-01-00000.nc
are not being archived in the cesm2-le.  A review of cime/config/cesm/config_archive.xml
indicates that this file is not being tested for, it is not listed in the test_file_names section for pop.   I also question why this section of config_archive.xml is associated with cime and not in
the pop cime_config directory.  @mnlevy1981 can you please review the <test_file_names> subsection of the pop section in config_archives.xml and make sure that pop history and restart files are properly disposed by the tools.   Also please consider moving this section from cime to pop.

**Comment by billsacks** [comment]
It looks like this was fixed on maint-5.6. Does it also need to be fixed on master or should this be closed?
