### ISSUE TITLE
Wrong path gets written to .env_mach_specific.* shell files for ESMF on izumi_nag single processor case

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3907]
This shows up in tests like: 

SMS_Vnuopc_D_P1x1.f10_f10_mg37.I2000Clm50Sp.izumi_nag.clm-default
SMS_Vnuopc_D_P1x1.f10_f10_mg37.I2000Clm50Sp.izumi_nag.clm-default

Where a full MPI library is being used even though there's only one processor being used. These are NUOPC cases, but I assume the only thing that's important is that it's using the ESMF library. I also don't see bad behavior for cases using more than one processor, so there must be specific logic that shows up for a single processor. We also know that cases using mpi-serial work.

This is with cime5.8.40

The content of the .env_mach_specific.sh file looks like this...

```
source /usr/share/Modules/init/sh
module purge 
module load compiler/intel/20.0.1 tool/netcdf/4.7.4/intel/20.0.1 mpi/2.3.3/intel/20.0.1
module use /fs/cgd/data0/modules/modulefiles/esmfpkgs/intel/20.0.1
module load esmf-8.1.0b47-ncdfio-mvapich2-O
export OMP_STACKSIZE=64M
export PATH=/project/esmf/PROGS/esmf/8.1.0b47/mvapich2/2.3.3/intel/20.0.1/bin/binO/Linux.intel.64.mvapich2.default:/usr/local/hdf5-1.12.0-intel-cluster-20.0.1/bin:/usr/local/netcdf-c-4.7.4-f-4.5.2-intel-cluster-20.0.1/bin:/cluster/mvapich2-2.3.3-intel-cluster-20.0.1/bin:/usr/local/intel-cluster-20.0.1/bin:/home/erik/bin:/home/erik/bin/svn_scripts:/cluster/torque/bin:/cluster/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:.:/cluster/torque/bin:/cluster/torque/bin
```

As you can see the first path for ESMF points to the Intel version hence the nag compiler can't use it. Hence the build fails on GPTL with the following message...

> Time(Code Output): User 0.00, System 0.00
> [NAG Fortran Compiler normal termination, 49 warnings]
> NAG Fortran Compiler Release 6.2(Chiyoda) Build 6207
> Option warning: The -mismatch option disables the -C=calls option
> Fatal Error: /scratch/cluster/erik/ctsm5.1.dev030/cime/src/share/timing/perf_mod.F90, line 20: /project/esmf/PROGS/esmf/8.1.0b47/mvapich2/2.3.3/intel/20.0.1/mod/modg/Linux.intel.64.mvapich2.default/esmf.mod is not a valid module information file
>              detected at :@ESMF_TRACEREGIONENTER

**Comment by jedwards4b** [comment]
I don't see how you got intel results in the .env_mach_specific.sh file.   But I do see that the path is in error in mine:
```
[jedwards@izumi SMS_Vnuopc_D_P1x1.f10_f10_mg37.I2000Clm50Sp.izumi_nag.clm-default.20210403_112709_8wdzkq]$ cat .env_mach_specific.sh 
# This file is for user convenience only and is not used by the model
# Changes to this file will be ignored and overwritten
# Changes to the environment should be made in env_mach_specific.xml
# Run ./case.setup --reset to regenerate this file
source /usr/share/Modules/init/sh
module purge 
module load compiler/nag/6.2-8.1.0 tool/netcdf/c4.6.1-f4.4.4/nag-gnu/6.2-8.1.0 mpi/2.3.3/nag/6.2
export OMP_STACKSIZE=64M
export PATH=/usr/local/hdf5-1.8.7-gcc-g++-gfortran-8.1.0/bin:/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-8.1.0-nag-6.2/bin:/cluster/mvapich2-2.3.3-gcc-8.1.0-nag-6.2/bin:/usr/local/gcc-g++-gfortran-8.1.0/bin:/usr/local/nag-6.2/bin:/home/jedwards/bin:/home/jedwards/.local/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/cluster/torque/bin:/cluster/torque/bin
export ESMFMKFILE=/scratch/cluster/himanshu/PROGS/esmf/master/mvapich2/2.3.3/intel/20.0.1/lib/libg/Linux.intel.64.mvapich2.default/esmf.mk
```

I see the problem, the ESMFMKFILE env variable should not be set in config_machines.xml - I'll submit a PR.

**Comment by jedwards4b** [comment]
Ignore that last, I had an older cime checkout.  The problem is that on izumi if you want mpi-serial you need to explicitly unload the mpi module.  cime pr coming.
