### ISSUE TITLE
Provenance: Repo location in addition to model version

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#3909]
Currently, CIME saves the model version in GIT_DESCRIBE.$LID. However, this does not differentiate between the base repository location vs. any fork or quasi-related repository (e.g., SCREAM in the case of E3SM). It would be better to capture the repository name and location to clarify the context.

**Comment by sarats** [comment]
cc @rljacob

**Comment by sarats** [comment]
On a related note, do we capture the 'branch' info somewhere and any output from 'git status' for uncommitted changes etc.?

**Comment by sarats** [comment]
@jasonb5 Can you look into adding the repo location as well to your planned mods for GIT_LOG etc.

**Comment by jasonb5** [comment]
@sarats Just to double check you would like the base path to the repo in GIT_LOG e.g. `/home/jasonb5/E3SM`?

**Comment by rljacob** [comment]
I think he means "git remote -v".

**Comment by sarats** [comment]
I wonder if it's good to capture `.git/config` as that's comprehensive.

**Comment by rljacob** [comment]
That looks useful

**Comment by jasonb5** [comment]
I agree `.git/config` looks like a good option, I'll store it in `GIT_CONFIG`.

**Comment by jasonb5** [comment]
Alright I added GIT_CONFIG which copies `$srcroot/.git/config` and added GIT_REMOTE to handle the submodule remotes.

**Comment by rljacob** [comment]
What's in GIT_REMOTE that isn't in GIT_CONFIG?

**Comment by jasonb5** [comment]
It has the remotes for the submodules, thought it might be worth recording.

**Comment by rljacob** [comment]
But it looks like .git/config already has that.  Or am I missing something?

**Comment by jasonb5** [comment]
It only shows the `origin` remote. As an example I have my fork of cime as a remote.

GIT_CONFIG shows:
```shell
[submodule "cime"]
	active = true
	url = https://github.com/ESMCI/cime.git
```

while GIT_REMOTE has the following:
```shell
Entering 'cime'
downstream	https://github.com/jasonb5/cime.git (fetch)
downstream	https://github.com/jasonb5/cime.git (push)
origin	https://github.com/ESMCI/cime.git (fetch)
origin	https://github.com/ESMCI/cime.git (push
```

**Comment by rljacob** [comment]
Ok then we'll keep both.

**Comment by jgfouca** [comment]
Closing on @jasonb5 's recommendation.

**Comment by sarats** [comment]
@jasonb5 In a similar vein, can you confirm if GIT_CONFIG and REMOTE files are getting properly archived.
