### ISSUE TITLE
CESM nuopc build fails on izumi_nag

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3915]
With a CTSM branch (https://github.com/billsacks/ctsm/commit/bc4758979e36cbb6292962c5f65f9397797a4390) that I believe is pointing to the latest relevant externals (https://github.com/billsacks/ctsm/blob/bc4758979e36cbb6292962c5f65f9397797a4390/Externals.cfg) I am getting this build error for non-mpi-serial nuopc tests on izumi_nag:

```
Error: /home/sacks/ctsm_code/ctsm2/cime/src/drivers/nuopc/cime_config/../drivers/cime/esmApp.F90, line 16: Cannot find symbol MPI_BCAST in module MPI
       detected at MPI_BCAST@<end-of-statement>
```

**Comment by ekluzek** [comment]
Using  cime5.8.47, cmeps0.13.10, and cdeps0.12.9 as recommended by @jedwards4b this is working for me now.

**Comment by ekluzek** [comment]
This is fixed in ctsm5.1.dev049 with updated externals.
