### ISSUE TITLE
Charting a path towards dropping python2 support

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3919]
This question came up in yesterday's CESM Software Engineering Group meeting (raised by @gold2718 , also relevant to @alperaltuntas ): We have some python code coming into CESM that will assume python3. Some of this code will be invoked by cime scripts (buildnml / buildlib), so will run under whatever python version is used to invoke the cime scripts, as controlled by your environment together with the shebang lines in the various cime scripts. Our feeling in CESM is that it is reasonable at this point to require python3, since python2 support ended over a year ago.

**I guess the first question here is: Do others (e.g., in E3SM) agree that it's reasonable to require python3 moving forward?**

Currently, our shebang lines are `#!/usr/bin/env python`. My understanding (based on https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take, https://www.python.org/dev/peps/pep-0394/, etc.) is that that is correct usage when your python code is compatible with python2 and python3. However, some systems (like cheyenne) have `python` pointing to `python2`, even if you have loaded a python3 module, and it may be a while before we can assume `python` always refers to `python3`.

So I'd like to start a discussion about how we want to proceed here. I'm going under the assumption that all users will have python3 installed on their system, so the question is: **How do we ensure that the cime scripts are run under python3 rather than python2?**

Two possible solutions came up in our CSEG discussion:

1. Change our shebang lines to `#!/usr/bin/env python3`. My understanding (e.g., from the links a couple of paragraphs above) is that this is a generally recommended solution when you require python3. I'm not 100% sure that this is 100% reliable in all situations, though: it sounds to me like systems *should* define a python3 executable, but there may be some that don't.

2. Instruct users to use a python environment where `python` points to a python3 executable. From PEP 0394, it sounds like this will be the case if people use a python virtual environment. I have been wary of requiring use of a python virtual environment, because it feels like something that might make porting to a new machine more difficult for non-tech-savvy users, and might be hard for users to remember even on systems with tech-savvy sys admins: Users would need to remember to launch the right python environment before invoking any cime scripts (create_newcase, case.build, etc., etc., etc.).

My gut feeling leans towards (1), because part of the value of cime has been that it manages the environment for you, so (2) feels like it might add too much friction for the use of cime. But I'd like to hear thoughts from others, especially others who have more experience than I do with python system configuration & virtual environments (which is a low bar to be honest). One possible advantage of (2) is that it could help give a path towards requiring a limited number of python packages outside the standard library (for CESM, we've talked about yaml, numpy, and either scipy.io.netcdf or netcdf4).

Thoughts?

**Comment by rljacob** [comment]
Definitely option 1.

**Comment by billsacks** [comment]
From cime telecon: People are fine with option (1). Will need to remove travis-ci python2 tests.

**Comment by jedwards4b** [comment]
travis-ci was already removed from master.

**Comment by rljacob** [comment]
@billsacks should all buildnml and buildlib scripts also change to "/usr/bin/env python3"?   @lukaszlacinski was on a platform where "python3" is in the path but "python" is not and got an error while running case.setup.

**Comment by billsacks** [comment]
Good point. Probably. I forget the logic for when buildnml / buildlib scripts are called via python functions (so the shebang line wouldn't matter) vs. subprocess calls (where the shebang line is important), but it wouldn't hurt to change everything to be consistent.
