### ISSUE TITLE
Active WAV component not recongized as primary component

### ISSUE THREAD

**Issue by sbrus89** [ESMCI/cime#3934]
In a new compset I created with an active WAV component and data ATM, the pe layout defaults to the datm pe specification file: (`src/drivers/mct/cime_config/config_pes.xml`)

I *think* this could be fixed by adding:
```
        elif progcomps["WAV"]:
            primary_component = spec["WAV"]
```
before the `else`  in  the following `if` statement:
https://github.com/ESMCI/cime/blob/44b241d263e3d2ace62f5340a1110f7174ca79e5/scripts/lib/CIME/case/case.py#L520-L573

**Comment by sbrus89** [comment]
The longname of the compset is:

2000_DATM%IAF_SLND_SICE_SOCN_SROF_SGLC_WW3_SIAC_SESP

**Comment by jedwards4b** [comment]
@sbrus89 I think that you are correct.  Did you try it?

**Comment by sbrus89** [comment]
@jedwards4b, yes I did; it seems to work for me.

**Comment by jedwards4b** [comment]
@sbrus89 please submit a PR with this change. We never had WAV as a primary component in the past.

**Comment by jonbob** [comment]
@sbrus89 - we had fixed this just a month or so ago? @jgfouca had put in that exact fix, so I'm not sure what happened

**Comment by jonbob** [comment]
@sbrus89 -- I spoke too soon. We did exactly that but were adding the ability for ROF to be a primary component

**Comment by sbrus89** [comment]
@jedwards4b, will do. 

@jonbob, thanks for pointing that out; I can see that fix with blame. You're right that It'll be the exact same thing expect for WAV.
