### ISSUE TITLE
Should we put in place a more general fix instead of #3939 and #3924?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3940]
Two recent PRs (#3939 and #3924) have fixed very similar issues: in certain circumstances, test values weren't getting reset to their original values when they should have been. I'm concerned that, even with these fixes, there could be scenarios where test values aren't being reset when a test is rerun. (I am concerned about this because I feel it's very important that we be able to have confidence that rerunning a test gives the same behavior as running it the first time.)

These two PRs fixed very specific things:
- #3939 fixes the specific case where a test has failed in the RUN phase and it is rerun via either the `--retry` or `--use-existing` options to `create_test`. This fix was needed because, with either of these options, a FAILed phase is changed to PEND, which then caused `_resetup_case` to skip doing the reset.
- #3924 fixes multisubmit tests

However, these do not solve the possible problem of *non-multisubmit* tests being left with their RUN phase in a PEND status, and then being rerun via any mechanism. Is this possible? I'm not sure, but if there are ways for a multisubmit test to be left in a PEND state (as suggested by the reproducer in https://github.com/ESMCI/cime/issues/3805#issuecomment-818331261), then I wonder if this is possible for a non-multisubmit test. But I have done a bit of testing to confirm that *if* a non-multisubmit test is left in a PEND RUN state, then it is *not* properly reset. (I ran an ERP test, killed it with `qdel`, edited TestStatus to change the RUN phase to PEND and then xmlchange'd `STOP_N`. Then I ran `./case.submit`. I found that `STOP_N` did *not* get reset to its original value. It *does* get reset if the RUN phase is FAIL rather than PEND. I think this is due to the check for a PEND state in `_resetup_case`: not doing the resetup if the current phase is PEND.)

**I would feel more comfortable if we could either:**
1. Identify the reason that the PET test in issue #3805 ended up in a PEND state, and either fix that underlying issue or be confident that that issue can only affect multi-submit tests (so that #3924 is really a sufficient fix).
2. Put in place a more general fix. My initial proposal would be to change `_resetup_case` to not depend on whether the given stage is PENDing or not. That change could replace the specific fixes of #3939 and #3924. I'm not sure if that would have any unintended consequences, but from looking back at the history of this function, it looks like the addition of the PEND check may have been a performance optimization to prevent unnecessary runs of case.setup (see #986). I don't think we want to go back to how things were prior to #986 (with the resetup done in the constructor of SystemTestsCommon), but this removal of the PEND check could be a compromise. As a side note, I wonder if we really still need the call to `case_setup` in `_resetup_case`, or if that was only needed when we had tests that changed the PE layout within a single case, which I think no longer happens now that we have SystemTestsCompareTwo.

What do others think about this? @jgfouca ? @jedwards4b ? @jasonb5 ?

**Comment by jgfouca** [comment]
@billsacks , I haven't thought enough about it to have an opinion on a solution, but I share your concern about reruns not behaving as expected. We could use a really thorough re-run test that checks all the major test types (ERS, PET, etc), for initial runs both passing and failing, the re-running it does exactly what we want.

**Comment by billsacks** [comment]
> @billsacks , I haven't thought enough about it to have an opinion on a solution, but I share your concern about reruns not behaving as expected. We could use a really thorough re-run test that checks all the major test types (ERS, PET, etc), for initial runs both passing and failing, the re-running it does exactly what we want.

Yeah, that certainly wouldn't hurt. Though I wouldn't have confidence in my own ability to come up with the full range of test conditions that fully exercise this. The best approach may be a combination of the testing you're suggesting along with a tweak in the implementation to make it more fool-proof.

**Comment by billsacks** [comment]
Based on nobody having strong (or any) feelings on this at today's cime telecon: We decided that, for now, we'd merge the existing PRs. Then we can revisit the idea of a more general fix if we run into further issues with rerunning tests.
