### ISSUE TITLE
Create hash at create_newcase time.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3944]
To help uniquely identify cases in experiment data bases, create a hash using:

- the create_newcase command arguments,
- the date and time,
- the local host name
- the user id.

Store the value of this hash in env_case.xml.  Only way to change it is re-create the case.

This should be enough to create unique hashes for every case created with cime.

**Comment by sarats** [comment]
So, what happens when folks use xmlchange? Does it necessitate creating a new hash? We are presently using LID to distinguish completed jobs but that's runtime.

**Comment by rljacob** [comment]
No.  It just needs to be unique for the invocation of create_newcase and not try to capture anything about the content of the case.  The rest of the provenance can do that.  But this hash will be how we add more provenance from things like zstash.

**Comment by sarats** [comment]
So, if there are multiple jobs submitted from that case directory, they will share the hash then. Then it's not unique for jobs.

**Comment by rljacob** [comment]
right.  Just for the case.   Its finer-grained then --case-group which multiple cases might have but not for each case.submit invocation in the casedir.
