### ISSUE TITLE
Try to use MPIRUN_RETRY_REGEX to rerun failed jobs on izumi

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3947]
Recently, I have been experiencing more frequent job failures on izumi. They usually/always have the same characteristic pattern: the job successfully runs all the way to the mpi finalize (or somewhere around there) and then dies when trying to finalize, with a message in the log file like this:

```
[mpiexec@i040.unified.ucar.edu] HYDT_bscd_pbs_wait_for_completion (tools/bootstrap/external/pbs_wait.c:67): tm_poll(obit_event) failed with TM error 17002
[mpiexec@i040.unified.ucar.edu] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@i040.unified.ucar.edu] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@i040.unified.ucar.edu] main (ui/mpich/mpiexec.c:340): process manager error waiting for completion
```

For CTSM's testing, we have recently started to routinely add `--retry 1` to the `create_test` command to work around this issue. Today, @jgfouca and @jedwards4b suggested a possibly cleaner fix: using the config_machines variables `MPIRUN_RETRY_REGEX` and `MPIRUN_RETRY_COUNT`, giving a regex that matches this error.

@fischer-ncar - would you be able to give this a shot and see if it allows tests on izumi to reliably run to completion?

One thing I'm not sure about is whether this code

https://github.com/ESMCI/cime/blob/3bd687d0c762da9582ff186edc90f76cfacb6f91/scripts/lib/CIME/case/case_run.py#L171-L178

would cause any issues when run within a test case. (I don't have any reason to think that it *would* cause problems, but it just raised that question in my mind.)

FYI @ekluzek @cacraigucar @gold2718 @mvertens @jedwards4b

**Comment by billsacks** [comment]
I'm fine with closing this as a wontfix if others are. The `--retry` mechanism, while not the most elegant, has been working pretty well for us.

**Comment by ekluzek** [comment]
@billsacks I agree it would be OK to close this as a wontfix. The solution proposed here does sound good and possibly not hard to do, but also not a priority.
