### ISSUE TITLE
Add ability to xmlchange to modify NUOPC streams xml files (or add a new tool to do so)

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3950]
I'd like the ability for streams files such as created in CDEPS to be editable using xmlchange. Or add a new tool that would be specific for the streams files (called something like streamchange). @jedwards4b thought it should be possible to use xmlchange though using the "--subgroup" option group-name to set the stream name the change would apply to.

I think this is an important capability in order to allow users to easily change specific settings in the streams files without having to touch others. This is especially important when a set of changes for a case needs to be applied to a new case with a different model version. You want to keep the defaults for other stream settings for the new model version, and only change the few settings requested. Since, this is commonly done in simulations it's important to have a way to do this for the streams files. Doing this will make it easier to work with the streams than with the previous interface. 

This relates to this issue in CDEPS...

https://github.com/ESCOMP/CDEPS/issues/76

**Comment by mvertens** [comment]
@jedwards @ekluzed - I think we should keep this issue open. I think as CDEPS is used more widely it will be really nice to have this and at least keep it on our radar in the near term.

**Comment by ekluzek** [comment]
@mvertens since we now have the capability to change CDEPS streams using the user_nl_*_streams file -- is this one in cime still important? This issue was created before that capability, and I think maybe that capability takes care of what this issue was about.  So my inclination is to leave this closed since the CDEPS https://github.com/ESCOMP/CDEPS/issues/76 took care of it. What do you think about that?

**Comment by mvertens** [comment]
@ekluzek - all good points. I was thinking more along the lines of being able to remove or add a stream - which we cannot currently do easily from the current capabilities. You can only change what is already there in the streams. However, looking more closely - you already raised this in https://github.com/ESCOMP/CDEPS/issues/211.
So I am fine with keeping this issue closed.
