### ISSUE TITLE
Extend #3958 to output python 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3960]
If we extend #3958 to output a python script using a case object we
may encourage our scientists to use it instead of sh.   I think this may be a gentle way to ease users into python.

**Comment by jedwards4b** [comment]
@billsacks  Very often when users want to demonstrate some problem they are having in cesm they will provide me a script that they have been using in the course of running their experiments.  I'm not talking about wrapping each line in a subprocess call.   I'm talking about, for example, replacing 
xmlchange with case.set_value but as I write this I realize that #3958 outputs one step at time and to make a good python script you would want to reuse the same object and not create a new object each time.   But maybe we could write something like:
```
#!/usr/bin/env python3

import os, sys
cesmroot = os.environ.get('CESM_ROOT')

if cesmroot is None:
    raise SystemExit("ERROR: CESM_ROOT must be defined in environment")

_LIBDIR = os.path.join(cesmroot,"cime","scripts","Tools")
sys.path.append(_LIBDIR)
_LIBDIR = os.path.join(cesmroot,"cime","scripts","lib")
sys.path.append(_LIBDIR)

from CIME.case import Case
import CIME.build

# Created 2021-05-07 22:52:59
CASEDIR="/data/cime_testing/scratch/test50"
compset = "A"
res = "f19_g16_rx1"

with Case(CASEDIR, read_only=False) as case:
  if not os.path.isdir(CASEDIR):
    case.create(os.path.basename(CASEDIR), cesmroot, compset, res)
    case.case_setup()
    build.case_build(CASEDIR, case=case)
  case.set_value(NTASKS,2)
  case.set_value(STOP_N, 10)
  case.case_setup()
  case.clean()
  build.case_build(CASEDIR, case=case)
  case.submit()
```

I can see how writing that would be a lot trickier that the shell script...

**Comment by sarats** [comment]
+1 For instance, this capability could be useful in orchestrating a _simple_ set of simulations (ensembles support is a super-set/complex topic).
