### ISSUE TITLE
Need better abstraction for user_nl mods in tests

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3964]
The eri.py test has some hard-coded mods to user_nl_cam to help the test run.

We should figure out some way to not require such model-specific things in a test that should work for any CIME-enabled model.

There's also specific user_nl mods in the non-BFB tests:  mvk, pgn, tsc.

**Comment by billsacks** [comment]
With a naive glance at what you needed to do with the ERI test: My initial reaction is that the test should set an xml variable that components can then respond to appropriately in their build-namelist.

**Comment by rljacob** [comment]
Yes thats a good approach.

I started to think about testmods but I realized I don't know how testmods work in a compare-2 test.  To the mods apply to both phases?  Can you specify just one?

**Comment by billsacks** [comment]
> I started to think about testmods but I realized I don't know how testmods work in a compare-2 test. To the mods apply to both phases? Can you specify just one?

Testmods apply to both cases. They are applied to the original case, then that case is cloned, maintaining the testmods.

If that's what you want, that can be a workable solution if you just have a couple of tests of a particular type. But it would get hard to manage for something where you want to run a given test type (like ERI) on a bunch of different configurations, where you may be using testmods for each of those different configurations.
