### ISSUE TITLE
Deciding on a minimum python version for cime

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3965]
Now that we have officially(?) dropped python2 support, I think we should have some discussion on the minimum python version we require. This is partly for the sake of being able to document this for users, and partly for the sake of being able to decide what python features are and aren't allowed in the code.

I can see two ways to come at this:

1. What python features would we like to take advantage of, and what minimum python version is needed for them?
2. What python version can we reasonably expect users to have, both on our supported systems, and on their own systems to which they want to port CIME?

**Comment by jgfouca** [comment]
@billsacks , it would be really nice to have full pathlib support. Also having fstrings would be awesome.

**Comment by billsacks** [comment]
> What python features would we like to take advantage of, and what minimum python version is needed for them?

full pathlib support: 3.4 and later

f-strings (https://www.python.org/dev/peps/pep-0498/): 3.6 and later

One feature I'd really like to start using is [type hints](https://docs.python.org/3/library/typing.html), which is available in python 3.5 and later. I feel like this would really help with the understandability of CIME code, as well as helping tools like static checkers, various IDE-like features, etc. However, if I understand correctly, function annotations (which are what I'd be most inclined to use) are supported starting with 3.0 (https://www.python.org/dev/peps/pep-3107/).

I think I remember some people (@alperaltuntas ?) saying that python3.6 is required for some features he'd like to use.

> What python version can we reasonably expect users to have, both on our supported systems, and on their own systems to which they want to port CIME?

Some major versions (https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions):
- python3.4 was released March, 2014; it is no longer supported even with security fixes
- python3.5 was released Sept. 2015; it is no longer supported even with security fixes
- python3.6 was released Dec., 2016; it will continue to have partial support (for security fixes) through the end of 2021
- python3.7 was released June, 2018
- python3.8 was released Oct, 2019
- python3.9 was released Oct, 2020

CESM's two major systems:
- cheyenne has 3.4.6 if you don't load any modules, and 3.7.9 with 'module load python'
- izumi has 3.6.8 by default

**My very tentative conclusions so far: 3.4 seems like a pretty safe requirement; 3.6 would be good if we can expect users to do a "module load python".**

**Comment by billsacks** [comment]
> full pathlib support: 3.4 and later

Actually, from a skim of https://realpython.com/python-pathlib/, it sounds like there may not be complete support of some features until 3.6?

**Comment by jgfouca** [comment]
@billsacks , IMO we should shoot for at least 3.6. The pathlib situation is complicated. The library was released in 3.4, but support for pathlib objects throughout the standard library came in pieces through later versions. For example, shutil.rmtree and os.chdir both do not support pathlib arguments in 3.5 so you have to do annoying str conversions.

**Comment by billsacks** [comment]
Closing this discussion issue, because I think we're decided on 3.6. See #4035 .
