### ISSUE TITLE
Record number of nodes for given job

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#3966]
Presently, CIME computes the number of nodes required for a job submission but this information is not recorded anywhere AFAIK. Can we store it for archiving purposes?

**Comment by jgfouca** [comment]
@sarats , so you want to add this to the E3SM provenance?

**Comment by rljacob** [comment]
Yes eventually.  Ideally it would be recorded in an xml variable.  But if it was output as part of ./preview_run (on its own line) that would help.

**Comment by ekluzek** [comment]
Note, there is no reason to make this ONLY apply to E3SM. It should apply to all models, there's no reason to make it work only for one. And actually making it only work for one adds more work, so you might as well make it easier on yourself and have it work for all.

**Comment by rljacob** [comment]
We weren't implying this should only be done for E3SM.  It should be general CIME CCS feature.

**Comment by jedwards4b** [comment]
I think that this is already recorded for a given run in several places.  It's in the log files,
and it's in the timing files.  I think introducing another xml variable for this is unwarranted.

**Comment by jedwards4b** [comment]
If you really want this information for provenance then you should save the env_mach_pes.xml

**Comment by sarats** [comment]
Yes, but probably CESM would like it too? 

In fact, it might be capture 'preview_run.log' as well if not already? That could contain the mpirun/jsrun/srun invocation as well which could be handy along with the `replay.sh` script.

**Comment by rljacob** [comment]
Here's the output of preview_run from a recent case I ran:
[jacob@chrlogin1 Ftestrh]$  ./preview_run 
```
CASE INFO:
  nodes: 3
  total tasks: 96
  tasks per node: 32
  thread count: 2

```
The value of 3 for "nodes" doesn't appear anywhere except the output of preview_run.

**Comment by sarats** [comment]
To add, the directives in .case.run would be dependent on the batch system on a given platform, so it would prudent to have a more generic output. 

Additionally, our mpirun/srun/jsrun invocations often use runtime logic (inline shell commands) to construct the final command-line. So, we should also capture preview_run.log.

**Comment by sarats** [comment]
@jasonb5 Can you confirm where the number of nodes information is stored? Is that archived in provenance.py?

**Comment by rljacob** [comment]
I see it in preview_run.log.* in the CASEDIR.  At the top, that file has:

```
CASE INFO:
  nodes: 48
  total tasks: 1728
  tasks per node: 36
  thread count: 1
  ngpus per node: 0
```

**Comment by sarats** [comment]
So, preview_run.log is being archived (https://github.com/ESMCI/cime/blob/231c8e783d9df1896f7ac0bdd1f31e74f496bdac/scripts/lib/CIME/provenance.py#L345).

However, I don't see it for recent water cycle experiments (Version: v2.0.0-beta.3-17386-ge3472d21b2). Perhaps they need to pull in a CIME update?

**Comment by sarats** [comment]
We probably need to get the fix for replay.sh in their update as well along with GIT_REMOTE and GIT_CONFIG commits.

**Comment by jasonb5** [comment]
They're stored in run directory only.

I'll need to make another fix to have them added to the performance archive.

Should all the GIT_* be included in the perforamance archive as well?

**Comment by sarats** [comment]
Yes, all of these new features you added recently - those files should be saved in the archive.

**Comment by jasonb5** [comment]
Ok I'll make a PR to fix this.
