### ISSUE TITLE
NUOPC failing to build on izumi for gnu, intel, and nag compilers

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3970]
The cdeps library is failing to build on izumi for all compilers: gnu, intel, and nag. There is a separate issue about PGI.

Since, I don't know if this is a problem in cdeps or cime (or both) I've also documented this in CDEPS here...

https://github.com/ESCOMP/CDEPS/issues/96

This is with cime5.8.47

**Comment by ekluzek** [comment]
Note, a simple thing I tried (since this works in previous versions) was to use the Macros.cmake,Macros.make file from the previous case that worked. However, this failed so it wasn't such a simple fix.

**Comment by ekluzek** [comment]
Using  cime5.8.47, cmeps0.13.10, and cdeps0.12.9 as recommended by @jedwards4b this is working for me now.

**Comment by billsacks** [comment]
@ekluzek should this and ESCOMP/CDEPS#96 be closed? The two related tests in our CTSM expected fails list (`ERS_D_Mmpi-serial_Ld5_Vnuopc.1x1_brazil.I2000Clm50FatesRs.izumi_nag.clm-FatesColdDef` and `SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-NEON_NIWO`) are now passing.

**Comment by ekluzek** [comment]
This will be fixed in ctsm5.1.dev044 with updated cmeps and cdeps versions.

**Comment by ekluzek** [comment]
@billsacks I closed the CDEPS issue, and you should close this when the tag is done.
