### ISSUE TITLE
Issue of building a case with gris4 GLC grid

### ISSUE THREAD

**Issue by sjsprecious** [ESMCI/cime#3972]
I am trying to build a CESM case on Cheyenne with the CIME codes on the master branch (commit: `ad68a5d`). Some detailed configurations are summarized below:

- Compset: F2000climo
- Resolution: f19_f19_mg17
- Compiler: Intel

The build step fails with an error message `ERROR: gris included in compset but gland not in grid gris4`.

I guess this error is related to the recent renaming of GLC grid (see https://github.com/ESMCI/cime/commit/a52e7faf63146786950eaca50d1659b1f0656c63). Does anyone know how to fix this issue?

@jedwards4b @billsacks

**Comment by ekluzek** [comment]
This cime update must go along with an update of cism at the same time. You likely just need to update your cism version in your sandbox to the latest version.

**Comment by sjsprecious** [comment]
> This cime update must go along with an update of cism at the same time. You likely just need to update your cism version in your sandbox to the latest version.

Thanks @ekluzek for your quick reply. Currently I use the tag `cism2_1_78` for CISM but it still does not work. Is there a newer version of CISM that you would like to suggest? It is better to be a stable tag since this update of CISM will be included in my CAM PR, too.

**Comment by billsacks** [comment]
You need the latest version of cism: cismwrap_2_1_83 (note the change in tag naming convention). This is a stable, tested version that has been through prealpha testing (cesm2_3_alpha03a).

I'm going to close this issue but feel free to reopen or email me directly if you're still having problems.
