### ISSUE TITLE
create_test --xml-driver argument should be named --driver for consistency

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3979]
The `--xml-driver` argument to `create_test` is inconsistent with the other `--xml-*` arguments; this inconsistency is confusing: These arguments typically specify search criteria to find particular tests in the xml files. For example, specifying `--xml-compiler intel` would give you all tests that are defined for the intel compiler. In contrast, arguments without the `--xml-` prefix can be used to *change* aspects of the tests. For example, the `--compiler` argument can override the compiler given for the selected tests (if I understand it correctly).

In contrast to the other arguments, `--xml-driver` is *not* about selecting tests, but is about overriding tests. Therefore, I feel it should be renamed to `--driver` for consistency.

**Comment by billsacks** [comment]
I'll plan to do this after #4162 is merged: this is a trivial one-line change, but in a file that was moved in that PR, so no need to create a merge conflict.

@fischer-ncar @cacraigucar @jgfouca - will renaming `create_test --xml-driver` to `--driver` cause any problems with CESM / CAM / E3SM testing workflows?

**Comment by cacraigucar** [comment]
> I'll plan to do this after #4162 is merged: this is a trivial one-line change, but in a file that was moved in that PR, so no need to create a merge conflict.
> 
> @fischer-ncar @cacraigucar @jgfouca - will renaming `create_test --xml-driver` to `--driver` cause any problems with CESM / CAM / E3SM testing workflows?

This change will necessitate minimal changes in our test_driver.sh script and as such is perfectly fine.  I actually like that it aligns with the directive that we are using for create_newcase.

**Comment by fischer-ncar** [comment]
This will not affect prealpha/prebeta testing.  But updates will need to be made in the github workflows for CESM_share, CESM_CPL7andDataComps, and cime.

**Comment by jedwards4b** [comment]
@fischer-ncar I just checked the workflow for CESM_share, and cime I don't see anything that would be affected by changing this flag.  can you please elaborate?

**Comment by fischer-ncar** [comment]
@jedwards4b sorry, I was wrong.  I was thinking the scripts repression tests was using --xml-driver for the mct tests.  I forgot about the CIME_DRIVER environment variable.  So I'll say the change for --xml-driver to --driver won't affect the github workflows.

**Comment by jedwards4b** [comment]
> scripts repression tests 
very funny

**Comment by fischer-ncar** [comment]
Freudian typo.
