### ISSUE TITLE
Missing default namelist values should raise an error but do not

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3984]
If a namelist variable has defaults defined for certain attribute values but not others, and no match is found, the current code simply puts an empty string in as the value and moves on (even if the variable is not a character variable). Instead, an error should be raised in this situation.

I feel like this error checking is important because it is easy to accidentally leave out certain sets of matches from a `namelist_definition` file, and it would be much better for this issue to be caught at `preview_namelists` time rather than generating a presumably cryptic error at model runtime. It looks like CIME has been missing this error checking ever since the introduction of the python-based nmlgen, but I just noticed it now because I have only started working with python-based buildnmls in the last few months.

To reproduce this issue, introduce diffs like these:

``` diff
diff --git a/src/drivers/mct/cime_config/namelist_definition_drv.xml b/src/drivers/mct/cime_config/namelist_definition_drv.xml
index 05800db03..1927e53fc 100644
--- a/src/drivers/mct/cime_config/namelist_definition_drv.xml
+++ b/src/drivers/mct/cime_config/namelist_definition_drv.xml
@@ -750,10 +750,6 @@
       Setting this to zero will always do flux_max_iteration
     </desc>
     <values>
-      <!-- the value for f09 grids is maintained as 0.0 for compatibility with cmip6 experiments
-           the 1% convergence criteria improves performance of the atm ocn flux calculation in shr_flux_mod.F90 -->
-      <value cime_model='cesm'>0.01</value>
-      <value cime_model='cesm' atm_grid="0.9x1.25">0.0</value>
       <value cime_model='e3sm'>0.0</value>
     </values>
   </entry>
```

then run a test like the following, using `cime_model` = 'cesm' (note that I have removed the default values for 'cesm' in the above diffs):

```
./create_test --no-build SMS.f09_g16.X.bishorn_gnu
# cd to the test directory
./preview_namelists
grep flux_convergence CaseDocs/*
```

(I have reproduced the issue for integer & real values. For strings, the issue ends up triggering the valid value check if valid values are defined for that variable. That still doesn't seem like the right behavior, but at least it's better than not triggering an error at all.)

It looks like the issue is that https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/XML/namelist_definition.py#L195-L196 prevents the error checking that is supposed to happen in https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/nmlgen.py#L308-L310 . It looks like the behavior change came in 9991c862d32254b9d78131560309804b7e03d34a; I can't tell from that commit what the purpose of the change was and in what situations that change was needed. Without understanding the details, I would naively think that, if certain variables need the ability to have a fall-back value of an empty string, then they should do it explicitly in their `namelist_definition` file, by setting `<value> </value>`.

**Comment by billsacks** [comment]
The specific use case that led me to this issue is: I am introducing different default values for some CISM config variables depending on whether we're generating a config file for Greenland or Antarctica. If I forget to add a default for one ice sheet – or if someone adds defaults for a new ice sheet but overlooks some variable – it would be great if buildnml raised an error rather than putting an empty string in for the value. But there are a lot of other situations throughout CESM (and presumably E3SM and others) where it would similarly be good to have this error checking.

**Comment by ekluzek** [comment]
I agree with @billsacks it's easier to figure these problems out if it happens at preview_namelist time, rather than at run-time. I also agree that if there should be a default value used it should be set in the namelist_definition file explicitly. Doing this all in the namelist build is much easier and more obvious to figure out than at runtime. Sometimes runtime errors may be informative, but often they aren't obvious, and sometimes the model merely crashes in some strange fashion so it can be hard to debug. In contrast dieing at preview_namelist with a message "This setting could not find a default value" makes it much more obvious both to users and developers. Users could then get around it by setting the namelist item explicitly, and developers can easily see they just need to add something to the namelist_definition file.

**Comment by billsacks** [comment]
Looking more closely at the changes in 9991c862d32254b9d78131560309804b7e03d34a, I see that, before that commit, there was a distinction between two different causes of a `None` value:
1. If there were no matches, then the return value was `None`
2. If `self.text(mnode)` was `None`, then that `None` value was converted to an empty string

I'm not sure if (2) is actually needed, but to be safe, I think I'm going to add some extra logic that returns to that old behavior.

**Comment by billsacks** [comment]
> prevents the error checking that is supposed to happen in https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/nmlgen.py#L308-L310

That's the wrong reference. Actually the error checking that should be triggered is:

https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/nmlgen.py#L646

**Comment by billsacks** [comment]
I'm working on this....

**Comment by billsacks** [comment]
The changes in 3f3396ed5 seem to solve this issue. However, it appears that this bug was masking another bug, so when I fix this one, the other bug emerges.

The issue now is that, if a variable doesn't have a default specified for the given configuration, but it is explicitly specified in a `user_nl` file, we get the error, "No default value found". I'm not 100% sure, but I *think* we want to proceed without errors in that situation. I'm pretty sure that the problem is that the code here https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/nmlgen.py#L628-L631 should set `have_value = True` if a value is retrieved from that call to `get_variable_value`.

I spent a while digging into the history of this little block of code.

Early versions of this function did as I'm suggesting – e.g., https://github.com/ESMCI/cime/blob/9991c862d32254b9d78131560309804b7e03d34a/utils/python/CIME/nmlgen.py#L497-L499

In 7b6bf8e7fb2540424e8d63cf858038adba57f8b5 (part of https://github.com/esmci/cime/pull/964), @mvertens added what appears to have been intended as a performance enhancement:

https://github.com/ESMCI/cime/blob/7b6bf8e7fb2540424e8d63cf858038adba57f8b5/utils/python/CIME/nmlgen.py#L532-L533

But in 97244cbe5769dc5b92cb8092d95c8fd501d1bbbd (part of https://github.com/ESMCI/cime/pull/1259), @jedwards4b removed both the setting of `have_value = True` and the early return (he commented those lines out in that commit, then removed them in a following commit). It's hard for me to tell what motivated that change, but I can speculate: My guess is that the problem @jedwards4b ran into related to the early return added by @mvertens, *not* the setting of `have_value = True`. At the time, @jedwards4b was working on adding functionality related to lists of values. I can see how the early return would cause problems for that: If some subset of list items is given in the user_nl file and the rest are meant to be taken from the defaults, then this early return would have stopped the code from picking up the extra list items from the defaults.

(Another side-effect of that early return that may not have been intended is: if there is a file name in the user_nl file: if we return immediately according to @mvertens's change, it won't get the abs path appended; if we do *not* return immediately, it *will* get the abs path appended. I'm not sure what the expectation is in this respect, but modern versions of the code have done away with that early return, so it may be best to keep current behavior, even if it means some performance degradation.)

**My proposal, therefore, is to return to the logic in** https://github.com/ESMCI/cime/blob/9991c862d32254b9d78131560309804b7e03d34a/utils/python/CIME/nmlgen.py#L497-L499 – without the early return that @mvertens added later.

**Comment by billsacks** [comment]
I found another issue that was being masked by this initial issue: If a variable does not have any default value for this configuration, but is specified in the user_nl file (as in the flux_convergence reproducer noted above), after fixing the issue noted in my proposal at the bottom of https://github.com/ESMCI/cime/issues/3984#issuecomment-854409941 I was getting:

```
Traceback (most recent call last):
  File "/Users/sacks/projects/scratch/SMS.f09_g16.X.bishorn_gnu.20210604_110707_j41dj3/./preview_namelists", line 57, in <module>
    _main_func(__doc__)
  File "/Users/sacks/projects/scratch/SMS.f09_g16.X.bishorn_gnu.20210604_110707_j41dj3/./preview_namelists", line 54, in _main_func
    case.create_namelists(component=args.component)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 89, in create_namelists
    run_sub_or_cmd(cmd, (caseroot), "buildnml",
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 427, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/Users/sacks/cime/src/drivers/mct/cime_config/buildnml", line 409, in buildnml
    _create_drv_namelists(case, infile, confdir, nmlgen, files)
  File "/Users/sacks/cime/src/drivers/mct/cime_config/buildnml", line 72, in _create_drv_namelists
    nmlgen.init_defaults(infile, config)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/nmlgen.py", line 147, in init_defaults
    self.add_default(self._definition.get(entry, "id"))
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/nmlgen.py", line 673, in add_default
    self._namelist.set_variable_value(group, name, current_literals, var_size)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/namelist.py", line 1041, in set_variable_value
    self._groups[gn][vn][i-1] = value.pop(0)
IndexError: list assignment index out of range
```

I realized that what's going on is that the return value of `Namelist:get_variable_value` is a reference (i.e., pointer) to `namelist._groups[gn][vn]`. In `NamelistGenerator:add_default`, `current_literals` is then aliased to this internal namelist value; this is passed to the `value` argument in `set_variable_value`. Then, in `set_variable_value`, the call to `value.pop(0)` inadvertently pops from the internal namelist value, since `value` there is aliased to `self._groups[gn][vn]`.

This issue didn't show up before because the `get_default` call was never returning `None`, which meant that we were always entering this block: https://github.com/ESMCI/cime/blob/8ec59c02d0042b9e1e134ffbeba9fccb1f31a061/scripts/lib/CIME/nmlgen.py#L642-L645 That, in turn, meant that we were always calling `merge_literal_lists`, which ends up making a copy of the values. Now that we have fixed `get_default` to correctly return `None` in some situations, though, we are *not* always calling `merge_literal_lists`, and so this new issue appears.

This diff seems to fix the problem, and from a search through the code, this copy seems like a safe thing to do:

``` diff
diff --git a/scripts/lib/CIME/namelist.py b/scripts/lib/CIME/namelist.py
index cc76117da..1b0716cfb 100644
--- a/scripts/lib/CIME/namelist.py
+++ b/scripts/lib/CIME/namelist.py
@@ -953,7 +953,9 @@ def get_variable_value(self, group_name, variable_name):
         if gn:
             vn = string_in_list(variable_name,self._groups[gn])
             if vn:
-                return self._groups[gn][vn]
+                # Make a copy of the list so that any modifications done by the caller
+                # don't modify the internal values.
+                return self._groups[gn][vn].copy()
         return ['']

     def get_value(self, variable_name):
```
