### ISSUE TITLE
More shebang lines that need to be changed to python3

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3987]
scripts_regression_tests failed for me due to a python3 feature I (accidentally) introduced. This made me realize that there are still a lot more shebang lines that should be changed to python3 beyond those changed in #3948 .

e.g., do this from the top level of cime:
```
git grep 'usr/bin/env python' | grep -v python3
```

Many files are ones that I think are going to be split out of cime with @fischer-ncar 's cime split. So it might make sense to wait to fix this until that's done.

@fischer-ncar would you be willing to take this on after you finish the cime split?

**Comment by fischer-ncar** [comment]
Yes, it's a good idea to do this after the cime split.
