### ISSUE TITLE
Want clearer indication of what aspects of a test have not yet finished

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#399]
This issue began discussion in the comments for https://github.com/ESMCI/cime/pull/392 with my proposal for a requirement:

**If there is a TestStatus file in the test directory, and if the test has not completed successfully, then there must be at least one line in the TestStatus file with a status other than PASS**

@mvertens agrees with this proposal, and we both like the solution proposed by @gold2718 

> When a test is created, it should know all the phases that are part of the test.... At the end of the init, I would like to see the self.phase_statuses be filled out with each phase marked INCOMPLETE (with INCOMPLETE added to the list of valid test statuses.

(See discussion in https://github.com/ESMCI/cime/pull/392 for details.)

**Comment by billsacks** [comment]
I believe that implementing @gold2718 's suggestion would require a clearer separation between COMPAREs done for the sake of in-test comparison (e.g., .base vs .rest) and those done for baseline comparisons. These should become two fundamentally different stages, e.g. TEST_COMPARE and BASELINE_COMPARE. A number of CSEG members want this distinction returned for the sake of test reporting, too, so I'd suggest that we fold that into this issue.

**Comment by rljacob** [comment]
I've only been partly following these testing threads but I agree there should be a high-level and obvious distinction between a test *really* failing (.base vs. .rest are different) vs. a baseline comparison fail.  The latter is almost routine while the former is a big reason to worry.

**Comment by billsacks** [comment]
@rljacob @mvertens @jedwards4b @jgfouca : Should this issue be in the cime5.1.0 milestone? It seems like an important one to me....

**Comment by jgfouca** [comment]
It's not a blocker for anything I need in the milestone but I don't think it would be particularly hard either.

**Comment by billsacks** [comment]
To clarify my thoughts: I don't feel this is critical, but it would make me more comfortable to start using cime5 in my CLM development if this were resolved.

**Comment by jgfouca** [comment]
I'm willing to do this if it's OK with our leaders @rljacob  and @mvertens

**Comment by rljacob** [comment]
If you don't think it would be hard or delay other PRs, I'm ok with it.

**Comment by mvertens** [comment]
I agree with Rob's consensus.

**Comment by billsacks** [comment]
Bumping this issue. We were just bitten by a bunch of tests bailing after the XML phase, so that the TestStatus file ended up like this:

```
PASS ERP_Ld5_P24x1.f10_f10.ICRUCLM50BGC.hobart_nag.clm-reduceOutput CREATE_NEWCASE
PASS ERP_Ld5_P24x1.f10_f10.ICRUCLM50BGC.hobart_nag.clm-reduceOutput XML
```

So all our automated parsing of test results, e.g., via cs.status, made it look like everything has been passing for the last month, when in fact many tests weren't even making it to the build.

cc @mvertens @jedwards4b @ekluzek @fischer-ncar @jgfouca

**Comment by jgfouca** [comment]
How did the failure not get reflected in TestStatus?

**Comment by billsacks** [comment]
> How did the failure not get reflected in TestStatus?

That's a good question, and one that probably deserves a separate issue. The TestStatus.log file looks like this:

```
Adding user mods directory /home/sacks/cesm_code/clm_limitirrig/components/clm/cime_config/testdefs/testmods_dirs/clm/reduceOutput
Pre-pending file /home/sacks/cesm_code/clm_limitirrig/cime/scripts/tests_0929-1430/ERP_Ld5_P24x1.f10_f10.ICRUCLM50BGC.hobart_nag.clm-reduceOutput.GC.0929-1430.45.n/user_nl_clm

Errput:
2016-09-29 14:31:27: SETUP FAILED for test 'ERP_Ld5_P24x1.f10_f10.ICRUCLM50BGC.hobart_nag.clm-reduceOutput'.
Command: ./case.setup
Output: Guessing CIME_MODEL=cesm, set environment variable if this is incorrect

Errput: ERROR: it is not possible to run with OpenMP if using the NAG Fortran compiler
```

I haven't traced the logic to determine how this error fell through the cracks in the TestStatus reporting.

Nevertheless, to me this points to the need for marking tests as INCOMPLETE with some failure line, as a sort of fail-safe in the event that we have failures like this that fall through the cracks - i.e., so bugs in the testing scripts don't result in failures appearing as passes.

**Comment by jgfouca** [comment]
Fixed by #639.

**Comment by billsacks** [comment]
In talking this over with @gold2718 , we felt that @jgfouca 's fix in #639 went part-way, but not all the way, toward addressing this issue. So I'm reopening it.

Specifically, we'd still like some indication about stages that are required for a given test, but not for all tests. The important ones are the ones following RUN, and in particular the COMPARE_* stage and the BASELINE stage.

For this to work, I'm imagining that there would be a method call on TestStatus like `teststatus.add_required_phase(phase)` - e.g., if --compare is given, then this would look like `teststatus.add_required_phase(test_status.BASELINE_PHASE)`. Each TestStatus object would then have its own list of CORE_PHASES (maybe called something like `required_phases`). If the ordering of this is important (and it looks like it is), then `add_required_phase` will need to look at the ordering in ALL_PHASES to determine where to insert the new phase in `required_phases` (or something like that).

Because TestStatus is periodically written and read, it feels like any state needs to be represented in the TestStatus file (if I understand the design correctly). If that's true, then _all_ required phases would need to appear in TestStatus; any required phase that hasn't yet run would have a PEND status. @gold2718 and I both prefer having this extra information in TestStatus anyway.

For example, for a test run with --compare and has a COMPARE_base_rest phase, the TestStatus file would look like this after the build is complete but before the run:

```
[Some lines omitted]
PASS MODEL_BUILD
PEND RUN
PEND COMPARE
PEND BASELINE
```

It's possible that _parse_test_status additionally would require marking each phase as to whether it should be in the required_phases list. If so, perhaps we could come up with an annotation to mark a phase as such; e.g.,

```
PASS (r) CREATE_NEWCASE
PASS (r) XML
PASS (r) SETUP
PASS     NAMELIST
PASS (r) SHAREDLIB_BUILD
PASS (r) MODEL_BUILD
PEND (r) RUN
PEND (r) COMPARE
PEND (r) BASELINE
```

But I'm not at all tied to that latter suggestion.

**Comment by jgfouca** [comment]
@billsacks I don't know if this is possible without making things ugly. What your asking for tightly couples the TestStatus object to the run phase of the system test from the moment the case is created.

**Comment by gold2718** [comment]
@jgfouca , I don't see why that is true. What I thought might happen is that `./crease_test --use-existing` would read TestStatus and set the run phase to the first FAIL or PEND step. Other than that, processing would not change. @billsacks , does that sound sound?

**Comment by billsacks** [comment]
@jgfouca - I don't understand how this leads to the tight coupling you mention (which is truly a reflection of my naivety - I'm not trying to argue with you on this point). I'd be interested to try to understand this better.

@gold2718 : I didn't get into rerunning / --use-existing here. I definitely liked the conceptual idea you presented to me on this point yesterday. Thinking about it more, I'm not sure it would be easy to pick up at any arbitrary point, but it makes sense to me to be able to pick up at the start of the build phase or the start of the submit/run phase.

Anyway, it probably makes sense for the three of us to have a chat about all of this at some point - presumably after early November, since Steve won't be available until then.

To be clear: I'm in no rush for this - I'm happy for this issue to remain open for a while at low priority until we (a) understand what we want, and (b) have time to implement it. To make that more clear, I'm removing Jim as an assignee, and calling this an enhancement.

**Comment by jgfouca** [comment]
@billsacks I will try to explain by presenting a scenario. test_scheduler will run create_newcase for a testcase and after the case is created, we currently update the TestStatus as follows:
```
PASS <CASE> CREATE_NEWCASE
PEND <CASE> XML
```
What you're asking for is this, lets assume it's an ERS case:
```
PASS <CASE> CREATE_NEWCASE
PEND <CASE> XML
PEND <CASE> SETUP
PEND <CASE> NLCOMP
PEND <CASE> SHAREDLIB_BUILD
PEND <CASE> MODEL_BUILD
PEND <CASE> RUN
PEND <CASE> BASELINE
PEND <CASE> COMPARE_base_rest
```
This means that the TestStatus object created by test_scheduler after the create_newcase phase now needs to know the following additional bits of information:
1) That the test case is doing baseline comparisons (not too hard to do this)
2) That the ERS test case is expected to do a COMPARE_base_rest during its run phase (hard)

(2) is what I'm concerned about and is what I meant by tightly coupling TestStatus to the details of the run phase of the testcase. We could set up a system where each system test registers ahead of time what comparisons it does during its run phase; we'd have to set up checks so that doing an unregistered comparison is an error or failing to do a registered comparison is also an error. This seems somewhat inelegant.

**Comment by billsacks** [comment]
@jgfouca - Now I see the confusion. I'm not exactly suggesting that. What I'm suggesting is that, initially, the TestStatus file would NOT contain

```
PEND <CASE> COMPARE_base_rest
```

Rather, this would be added to the list once the actual ERS object is created: In the constructor for the ERS test, there would be a call to self.teststatus.add_required_phase("COMPARE_base_rest"), or something like that. So we wouldn't necessarily have a complete list of expected phases from the very beginning, but this would be close enough.

**Comment by rljacob** [comment]
After telecon discussion, we feel this has been addressed.  Please open a new issue if further work needed.

**Comment by billsacks** [comment]
@rljacob - I don't think my comments from Oct 11-13, 2016 were ever addressed. These requests came out of discussions between @gold2718 and myself. My head isn't back in this right now, but my recollection is that these changes are still needed if we want the test system to be more robust against the kinds of errors that have happened in the past - where tests aborted at some early phase but no FAILs appeared in the TestStatus file.

That said, I'm okay closing it for now if @gold2718 is okay with this. I'm giving it a wontfix label so that, when we look back later, it's clear that it wasn't completely addressed.

**Comment by billsacks** [comment]
I'm reopening this, because we have been bitten yet again by some tests looking like they passed when in fact they did not complete all required phases - specifically, PET tests are not running the second case or doing the comparison between the first and second case; this would have been caught if all system_tests_compare_two tests marked the compare phase as required. See https://github.com/ESMCI/cime/issues/2597https://github.com/ESMCI/cime/issues/2597
