### ISSUE TITLE
Makefile Addition for MPAS NUOPC

### ISSUE THREAD

**Issue by jtruesdal** [ESMCI/cime#3995]
To complete NUOPC integration for MPAS we need to know when the NUOPC driver is chosen.  I think we can just pass the COMP_INTERFACE variable to the make call for libmpas and the MPAS Makefile can check if its nuopc and make the appropriate CPP define for building the dycore library.

I'll be making a misc tag soon for MPAS for which I can make the appropriate mods to enable use of NUOPC if the above proposition is acceptable for the CIME side of things.

**Comment by jedwards4b** [comment]
@jtruesdal Note that the COMP_INTERFACE is already returned from a call to build.py get_standard_makefile_args.

**Comment by jtruesdal** [comment]
@jedwards4b Noted and thank you.  No change needed to CIME.  For future reference is it OK for me to close an issue that I created here or is that up to the CIME developers?

**Comment by jedwards4b** [comment]
You are welcome to close any issue that you open.

**Comment by jtruesdal** [comment]
Closing. As Jim noted is interface type is already available.
