### ISSUE TITLE
Avoid creating a case directory until all input options are validated.

### ISSUE THREAD

**Issue by quantheory** [ESMCI/cime#4]
The `create_newcase` command (and other scripts, e.g. `create_test`) should not create directories or write any files until first validating user-specified options. If someone forgets to add the `-compset` option, for instance, the directory is created, but the command fails, meaning that you have to go wipe it before trying again.

**Comment by douglasjacobsen** [comment]
Alternatively, you could consider adding a --force options to `create_newcase` which will force the creation of the new case in the location you specified (could `rm -rf` the case before creating it, just to make sure nothing weird is left there).

**Comment by quantheory** [comment]
@douglasjacobsen 

This is admittedly a very minor issue, but I hit this a lot because I make a lot of typos and then forget that I have to remove the case directory afterward. I don't think that we want `--force`. If you don't use `--force` habitually, it doesn't add much convenience, since it's not much harder to remember to `rm -rf` by hand. If you *do* use `--force` habitually, it seems far too easy to make a mistake and blow away a case (or any other directory) that you want to keep.

Most command-line tools that I use on a regular basis check for valid options before doing anything (and `create_newcase` already has some checks, they just aren't complete). I think it would be better if we can make sure that, all the required options are provided, and the grid/compset/machine/whatever are valid values, before starting to copy things into a case directory.

**Comment by rljacob** [comment]
Fixed in new python version.
