### ISSUE TITLE
use the --verbose flag in preview_run 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4000]
Instead of hardcoding verbose=True you should use the --verbose flag which is already present.
@jasonb5

**Comment by jasonb5** [comment]
@jedwards4b 
The `verbose` flag use to be hardcoded to **True** and printing the environment variables was handled by `case.load_env`, this did not allow me to control the formatting. I changed the hardcoded `verbose` argument to **False** and updated `case.load_env` to return the environment variables so I could control the formatting when printing them.

I think we have two options here: **1)** I can revert the change to `case.load_env` and link the `verbose` argument to the flag, this will result in some weird formatting. To fix the formatting I could add an indent argument to `case.load_env`. **2)** I could wrap this new bit of code https://github.com/ESMCI/cime/pull/3998/files#diff-005383c2e8eda64f577682e804aff212324bfa4c634136a01cc32fc06a8d7c9cR1794-R1795 with the verbose flag.

**Comment by jedwards4b** [comment]
This is what I am seeing now:
```
Setting Environment OMP_STACKSIZE=1024M
      Setting Environment OMP_STACKSIZE=1024M
Setting Environment TMPDIR=/glade/scratch/jedwards
      Setting Environment TMPDIR=/glade/scratch/jedwards
Setting Environment MPI_TYPE_DEPTH=16
      Setting Environment MPI_TYPE_DEPTH=16
Setting Environment MPI_IB_CONGESTED=1
      Setting Environment MPI_IB_CONGESTED=1
Setting Environment ESMF_RUNTIME_PROFILE=ON
      Setting Environment ESMF_RUNTIME_PROFILE=ON
Setting Environment ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
      Setting Environment ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
Setting Environment UGCSINPUTPATH=/glade/work/turuncu/FV3GFS/benchmark-inputs/2012010100/gfs/fcst
      Setting Environment UGCSINPUTPATH=/glade/work/turuncu/FV3GFS/benchmark-inputs/2012010100/gfs/fcst
Setting Environment UGCSFIXEDFILEPATH=/glade/work/turuncu/FV3GFS/fix_am
      Setting Environment UGCSFIXEDFILEPATH=/glade/work/turuncu/FV3GFS/fix_am
Setting Environment UGCSADDONPATH=/glade/work/turuncu/FV3GFS/addon
      Setting Environment UGCSADDONPATH=/glade/work/turuncu/FV3GFS/addon
Setting Environment OMP_WAIT_POLICY=PASSIVE
      Setting Environment OMP_WAIT_POLICY=PASSIVE
Setting Environment MPI_DSM_VERBOSE=true
      Setting Environment MPI_DSM_VERBOSE=true
      Setting Environment OMP_NUM_THREADS=3

```

This is what I would like to see
```
      Setting Environment OMP_STACKSIZE=1024M
      Setting Environment TMPDIR=/glade/scratch/jedwards
      Setting Environment MPI_TYPE_DEPTH=16
      Setting Environment MPI_IB_CONGESTED=1
      Setting Environment ESMF_RUNTIME_PROFILE=ON
      Setting Environment ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
      Setting Environment UGCSINPUTPATH=/glade/work/turuncu/FV3GFS/benchmark-inputs/2012010100/gfs/fcst
      Setting Environment UGCSFIXEDFILEPATH=/glade/work/turuncu/FV3GFS/fix_am
      Setting Environment UGCSADDONPATH=/glade/work/turuncu/FV3GFS/addon
      Setting Environment OMP_WAIT_POLICY=PASSIVE
      Setting Environment MPI_DSM_VERBOSE=true
      Setting Environment OMP_NUM_THREADS=3
```

**Comment by jasonb5** [comment]
That's with master branch?

https://github.com/ESMCI/cime/blob/71ddf1ced43ca77e422abe2b460adfb29710b91a/scripts/lib/CIME/case/case.py#L1792 should prevent those unindented messages from printing.

I'm checking now, to try and reproduce this.

**Comment by jedwards4b** [comment]
@jasonb5 Sorry - I thought I was looking at the latest master, but I was behind by a couple of commits, up to date now and this is no longer an issue.
