### ISSUE TITLE
imp module is deprecated; replace with importlib

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4007]
I notice that we have a few uses of the 'imp' module in CIME. According to python documentation, this was deprecated as of python3.4, and we should switch to using importlib.

That said, I'm adding another use of the 'imp' module that follows our current patterns, because it seems like it will be easiest to stay consistent and then switch everything at once. The right way to switch our usage of imp.load_source over to importlib seems to depend on the python versions we want to support. According to https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path, for python3.5+, we'll need this lovely bit of code (apparently the python maintainers really don't want you to do this):

```python
import importlib.util
spec = importlib.util.spec_from_file_location("module.name", "/path/to/file.py")
foo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(foo)
```

See also https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly, which adds a line, `sys.modules[module_name] = module`; I'm not sure if that's needed.

So I guess, if we are comfortable only supporting python3.5+, we should add a utility function that does the above and then switch our current usage to use that.

Thoughts?

**Comment by jgfouca** [comment]
I agree.

**Comment by jedwards4b** [comment]
I thought that we had already made a decision to support only 3.7 and newer.  https://github.com/ESMCI/cime/blob/master/.github/workflows/srt.yml#L21
