### ISSUE TITLE
maxOccurs set to 1 for MAX_TASKS_PER_NODE breaks E3SM machine

### ISSUE THREAD

**Issue by jasonb5** [ESMCI/cime#4017]
PR #3989 introduced a change that breaks some E3SM machines.

Commit introducing the change https://github.com/sjsprecious/cime/commit/89a4292be3c78244e5042a8ad36453ae5407a7d8.

Machines broken with change
- **summit** https://github.com/E3SM-Project/E3SM/blob/d28e8771e4d33ea5e7179eeccf2e031a9838ac8c/cime_config/machines/config_machines.xml#L2715-L2742
- **ascent** https://github.com/E3SM-Project/E3SM/blob/d28e8771e4d33ea5e7179eeccf2e031a9838ac8c/cime_config/machines/config_machines.xml#L2867-L2894

Original error:
```bash
ERROR: Command: '/usr/bin/xmllint --xinclude --noout --schema E3SM/cime/config/xml_schemas/config_machines.xsd E3SM/cime_config/machines/config_machines.xml' failed with error 'E3SM/cime_config/machines/config_machines.xml:2737: element MAX_TASKS_PER_NODE: Schemas validity error : Element 'MAX_TASKS_PER_NODE': This element is not expected. Expected is one of ( MAX_GPUS_PER_NODE, MAX_MPITASKS_PER_NODE ).
E3SM/cime_config/machines/config_machines.xml:2896: element MAX_TASKS_PER_NODE: Schemas validity error : Element 'MAX_TASKS_PER_NODE': This element is not expected. Expected is one of ( MAX_GPUS_PER_NODE, MAX_MPITASKS_PER_NODE ).
E3SM/cime_config/machines/config_machines.xml fails to validate' from dir 'E3SM/cime/scripts'
```

**Comment by jedwards4b** [comment]
@jasonb5 Thanks - I will fix.
