### ISSUE TITLE
Missing src/externals/mct causes error when building mct for E3SM

### ISSUE THREAD

**Issue by jasonb5** [ESMCI/cime#4018]
PR #3990 & #4010 

It looks like the intention of #3990 (https://github.com/fischer-ncar/cime/blob/1345b4bcb41309ca939033031648a7972744ef66/CMakeLists.txt#L28-L32) was to use `${SRC_ROOT}/libraries/mct` if present otherwise `${CIME_ROOT}/src/externals/mct`. PR #4010 then removed `src/externals/mct`.

Original error:
```bash
can't copy 'E3SM/cime/src/externals/mct/mct/Makefile': doesn't exist or not a regular file
```

**Comment by rljacob** [comment]
This should be fixed by first introducing mct as a new submodule in E3SM/externals and then updating the build script accordingly.

**Comment by jasonb5** [comment]
@rljacob @jgfouca  
Ok so we want to add https://github.com/MCSclimate/MCT as a new submodule in E3SM/externals then adjust https://github.com/ESMCI/cime/blob/ccdf7376e6677853332f9da887c5369e5d1157f5/CMakeLists.txt#L28-L32 to point to `${SRC_ROOT}/externals/mct`.

How do we want to handle mct when cime is running in a standalone mode?

**Comment by rljacob** [comment]
If you check out just CIME, you'll have to use the manage_externals tool to get a full software stack.

**Comment by rljacob** [comment]
Although, yes, where would MCT go?   @jedwards4b ?

**Comment by jasonb5** [comment]
I think `Externals.cfg` is set to clone mct into `libraries/mct` in the CIME_ROOT and I'm assuming SRC_ROOT is CIME_ROOT when running standalone.
