### ISSUE TITLE
Allow a test to have multiple testmods

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4024]
Based on discussions with @jedwards4b and @ekluzek around how to make the behavior of #4020 more explicit, I am working on changes to allow multiple testmods in a test.

To do this, I plan to allow multiple arguments to the `--user-mods-dir` argument to create_newcase. Thus, the value of this argument in the code will now be a *list* of directories instead of a single directory. Then, anywhere where we operate on this argument, I'll add a loop over the elements of this list. It looks like there are only a few places where changes will be needed.

A minor challenge is how to specify multiple testmods in a test name. I considered using a new special character for this purpose, and was tentatively thinking of `,` (which some searches suggested to me is a reasonable character to include in a Unix file name, even if it isn't POSIX compliant). However, CLM's build-namelist didn't handle this properly.

**My current thinking is to use a double-hyphen as the separator between testmods.** Hyphen already has a special meaning in the testmod name, serving as a directory separator (i.e., each `-` is turned into `/` in determining the path to the testmod). So I can't see any current valid use of two hyphens in a row, and this feels like a reasonable syntax that sticks to only using characters that we know will work. So a test name like `ERP_D_Ld5.f10_f10_mg37.I1850Clm50BgcCropG.cheyenne_intel.clm-default--clm-foo-bar` would pull in two testmods, `clm/default` and `clm/foo/bar` (and as per @jedwards4b's recent change, any of these could actually end up pointing to a directory in the usermods space instead of the testmods space).

**Comment by billsacks** [comment]
I should have mentioned the purpose of this change. The primary purpose is to support the goal of #4020 in a more explicit way. That is, a test can use an existing usermod directory and add some test-specific stuff on top of it. However, I think this feature will also be useful in allowing us to clean up CTSM's (and maybe other components') testmods: we currently have some testmods directories that mainly/only exist for the purpose of combining two other existing testmods; we could do away with those and instead pull in both testmods directly. (A caveat with this is that things can get a little messy if multiple testmods include the same testmod.)

**Comment by jedwards4b** [comment]
@billsacks Thanks for this, I think that the -- syntax is fine and like that the inclusion of the additional test mod will be explicit instead of implicit as in #4020.

**Comment by ekluzek** [comment]
Yes the double hyphen makes sense to me. I'm not surprised it was hard to identify a good character to use, so I'm fine with whatever you figured out. 

And I like the fact that this will allow us to combine testmods and user-mods in an explicit way. I think this might make our inheritance structure in testmods more obvious as well. I think you are right this likely means we could remove many of our testmod directories that are just there to combine other testmods together. The only cost that I see is that the test name will be longer, which does have some concern in that some of our tests are too long as it is. And we do sometimes run into trouble with names that are too long. But, we still can create testmods if needed to shorten the testname, so there's no real downside to this.

**Comment by jedwards4b** [comment]
@billsacks do you have an ETA on this mod?

**Comment by billsacks** [comment]
I'm mostly done but have a few final pieces to wrap up. I'm not sure how much time I'll have to work on it today, but should have it ready by tomorrow. (As with many things, the code changes aren't too large, though it took some time to find all the places that needed changes.)
