### ISSUE TITLE
Support building components via python function instead of subprocess

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4025]
It looks like the call to buildlib for model components (which I *think* is done by `_build_model_thread`, but I may be wrong) is only set up to call buildlib as a subprocess, not as a python function. This is in contrast with `_build_libraries`, which calls `run_sub_or_cmd`.

It seems like the build of the component model libraries should also use `run_sub_or_cmd` based on whether the given file contains a `buildlib` function.

**Comment by jedwards4b** [comment]
I think that there was an issue in doing that related to thread safety @jgfouca do you remember?

**Comment by billsacks** [comment]
Oh, right. I see the comments from @jgfouca in https://github.com/ESMCI/cime/pull/3547 . Never mind.
