### ISSUE TITLE
Have cime abort if xmllint is not found as it fails anyway

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4039]
Jackie ran into the following problem on izumi, where because she didn't have xmllint in her path her case failed to be created.

This is with branch_tags/cime5.8.32_a02 but it looks like the same problem would be on master as well.

> job is case.run USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None WALLTIME_FORMAT %H:%M:%S
> 
> job is case.st_archive USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None WALLTIME_FORMAT %H:%M:%S
> 
>  Creating Case directory /home/jkshuman/FATES_cases/C4Gr_TropTrees/BCI_ens_test/fire_test_main_4x5_2a90c206_64c557e0
> 
> 
> Setting Environment OMP_STACKSIZE=64M
> 
> Setting Environment PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/cluster/torque/bin
> 
> Setting Environment ESMFMKFILE=/home/dunlap/ESMF-INSTALL/8.0.0bs16/lib/libg/Linux.intel.64.mvapich2.default/esmf.mk
> 
> Setting resource.RLIMIT_STACK to -1 from (8388608, -1)
> 
> xmllint not found, could not validate file /home/jkshuman/git/fates_main_api/cime/config/cesm/config_files.xml
> 
> xmllint not found, could not validate file /home/jkshuman/git/fates_main_api/cime/config/cesm/machines/config_machines.xml
> 
> xmllint not found, could not validate file /home/jkshuman/git/fates_main_api/cime/config/cesm/machines/config_compilers.xml
> 
> /home/jkshuman/FATES_cases/C4Gr_TropTrees/BCI_ens_test/fire_test_main_4x5_2a90c206_64c557e0/env_mach_specific.xml already exists, delete to replace
> 
> /home/jkshuman/FATES_cases/C4Gr_TropTrees/BCI_ens_test/fire_test_main_4x5_2a90c206_64c557e0/env_mach_specific.xml already exists, delete to replace
> 
> ERROR: File /home/jkshuman/FATES_cases/C4Gr_TropTrees/BCI_ens_test/fire_test_main_4x5_2a90c206_64c557e0/env_mach_pes.xml appears to have changed without a corresponding invalidation.
> 
> Traceback (most recent call last):
> 
>   File "./xmlchange", line 225, in <module>

**Comment by ekluzek** [comment]
Also shouldn't it be "validation" rather than "invalidation"?

scripts/lib/CIME/XML/generic_xml.py:               "File {} appears to have changed without a corresponding invalidation.".format(self.filename))

**Comment by jedwards4b** [comment]
xmllint is ubiquitous in Linux, if it's not in your path you have much bigger problems.  I don't think that we should consider this change.

**Comment by ekluzek** [comment]
@jedwards4b hmmm, but isn't that exactly a reason TO do this? If it can't find something ubiquitous -- shouldn't it go and abort as soon as possible? I'm reporting on an experience of an actual user, that I'm actually still having a hard time figuring out what's wrong with her environment. The sooner we have cime report on and abort when it identifies a problem the easier it will be for users to fix their own problems, or for us to help them. That's why I'm asking here, I think having this in place might've made it easier both for her to find her own problem, and for me to help her. Both of which I think are good. 

You are right that we can't protect against every crazy environment setup that a user *might* have. But, it seems to me to be good to protect against ones that we find actual users running into.

**Comment by jedwards4b** [comment]
sure okay, I understand now - xmllint should be required and cime should fail with a reasonable error if it is not found.
