### ISSUE TITLE
Issue workflow:  leave Backlog and Ready issues unassigned

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#405]
I hope everyone is using the waffle board to see what is going on in CIME:
https://waffle.io/ESMCI/cime

I'd like to suggest leaving any issues in "Backlog" or "Ready" unassigned.  This will let other developers know that they are not being worked on.

"Backlog" is for any open issue.
"Ready" is for an issue where discussion has finished and its ready to be worked on but no one has started yet.

Even if you know JimE is the only person who can fix issue X, it should stay unassigned until its in the "In Progress" column.

**Comment by gold2718** [comment]
From my perspective, the proliferation of CIME workflow tools makes it harder for me to keep up (and I thought tools were supposed to help). We have git along with various github tools (issues, pull requests) and waffle.
At least with waffle, you can click on an issue and see the github text.
However, now there is at least one reference to slack (from @jedwards4b) and I don't even know what slack site is being used or if it ties into any of the other tools.

And of course, none of this is documented on the wiki as far as I can see. Help!

**Comment by rljacob** [comment]
I'll document at least this part if everyone is ok with it.

Yes we shouldn't point to slack from github.  Github issues, wiki and the CIME git log provide our public record of CIME development.  Slack is private.

**Comment by rljacob** [comment]
I'll un-assign the open/ready issues if there are no objections.  @mvertens ?

**Comment by jgfouca** [comment]
@rljacob i'd prefer this not happen. I've been trying to use the ticket system as my todo list.

**Comment by rljacob** [comment]
Good point.   But I'd say take the ones you're going to work on and move those to "Ready".  The Backlog should be unassigned.  "Ready" will be a mix of assigned and un-assigned.  The un-assigned tasks will be the CIME-wide todo list that anyone can pick from.

**Comment by jgfouca** [comment]
OK, that works for me

**Comment by mvertens** [comment]
No objections from me.

**Comment by rljacob** [comment]
Result:  Backlog will be unassigned.  Ready will be a mix.
