### ISSUE TITLE
drv namelist failing with pio_netcdf_format for stub ESP component

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4051]
This is in cime6.0.1 and following

In many (but not all aux_clm) cases for example this one

SMS_N2_D_Lh12.f09_g17.I2000Clm50Sp.cheyenne_intel.clm-pauseResume

Preview namelist dies with the following error

> Create namelist for component drv
>    Calling /glade/work/erik/ctsm_neon/components/cpl7/driver/cime_config/buildnml
> ERROR: No default value found for pio_netcdf_format with attributes {'component': 'esp'}.

Using git-bisect I found this first occurs in this commit.

de588aafa8c338e56fa4d6369b47b0cb5d51fdf2

**Comment by ekluzek** [comment]
@billsacks this appears to be @jedwards4b merge of your billsacks-error_for_missing_nml_default branch. I'm not seeing why what you did should be a problem it seems safe to me. I'm guessing this must be something to do with ESP being a stub component? It does look like PIO_NETCDF_FORMAT is set correctly for all components in the env xml files:

> ./xmlquery PIO_NETCDF_FORMAT
> 	PIO_NETCDF_FORMAT: ['CPL:64bit_offset', 'ATM:64bit_offset', 'LND:64bit_offset', 'ICE:64bit_offset', 'OCN:64bit_offset', 'ROF:64bit_offset', 'GLC:64bit_offset', 'WAV:64bit_offset', 'IAC:64bit_offset', 'ESP:64bit_offset']

**Comment by billsacks** [comment]
It looks like this issue is fixed in cpl7.0.3 – can you try updating to that version of the cpl7 external and seeing if it fixes the problem?

**Comment by ekluzek** [comment]
Yes. Good call. That seems to fix the problem. I'll run more testing over night and we'll see if that resolves everything.

**Comment by ekluzek** [comment]
As stated before this was already fixed.
