### ISSUE TITLE
Add standard_name optional element to entry_id_namelist.xsd

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#4061]
To help integrate namelist processing with the CCPP, we would like to add a new optional element to entry_id_namelist.xsd
The new element, `standard_name`, would be the CCPP standard name for that namelist item.
Because it is optional, it should not affect any current uses of namelist files.

**Comment by jedwards4b** [comment]
I don't see any downside to this.

**Comment by rljacob** [comment]
Maybe call it CCPPstandard_name ?

**Comment by gold2718** [comment]
> Maybe call it CCPPstandard_name ?

I don't mind branding it (although I prefer `CCPP_standard_name`) unless anyone else can think of another use for the field (that is not CCPP).

**Comment by ekluzek** [comment]
standard_name is something that's part of the CF convention standard. We don't tend to use them, but it is there.

I also agree about adding the underscore.

**Comment by rljacob** [comment]
another underscore is fine.  I was thinking about CF but also if the possible values are defined by CCPP and its only for interaction with CCPP then its appropriate to add "CCPP" to the variable name.

**Comment by gold2718** [comment]
The CCPP does use CF names where available (it is the first of the [Rules for CCPP Standard Names](https://github.com/ESCOMP/CCPPStandardNames/blob/main/StandardNamesRules.rst)), however, those only cover about 5% of the need.

**Comment by gold2718** [comment]
I'm not going to close this at the moment but I will point out that it is no longer needed because of a competing definition that came in with ParamGen (scripts/lib/CIME/ParamGen/xml_schema/entry_id_pg.xsd). If no one has a problem with this, then this issue should be closed.
