### ISSUE TITLE
datm.input_data_list files aren't updated wtih user_datm.streams.txt file updates...

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4062]
This is a problem that was pointed out in a CESM discussion forum.

https://bb.cgd.ucar.edu/cesm/threads/clm5-checks-input-data-directory-for-gswp-and-cruncep-before-path-specified-in-user_datm-streams-txt.6368/

The problem is that when you have a user_datm.streams.txt file, the datm.input_data_list file isn't updated with what's in the user defined text file, but the default files for the configuration. As such those files need to exist even if they aren't used. And the files that are going to be used aren't checked for existence by check_input_data.

**Comment by ekluzek** [comment]
I just put this here for visibility of the issue. I think this probably should be closed as a WONTFIX.

**Comment by billsacks** [comment]
@ekluzek at your suggestion, I'm closing this as a wontfix.
