### ISSUE TITLE
Need for a 'POSTARCHIVE_SCRIPT' option 

### ISSUE THREAD

**Issue by briandobbins** [ESMCI/cime#4067]
Currently, it seems CIME has a PRERUN_SCRIPT and a POSTRUN_SCRIPT option to run external scripts before or after the model run.  I think it'd be useful to also have a POSTARCHIVE_SCRIPT for running an external script after the short-term archiver is finished.

This would be useful for automating calling a tool like the CESM Postprocessing suite for time-series generation, or other data processing / conversion / analysis scripts.

I'll be prototyping this in some AWS runs, and tying this issue to a PR afterwards.  If existing functionality like this already exists, though, that'd be great to know.  A second issue will also look into extending the use of these variables to use remote scripts, vs local ones.

**Comment by jedwards4b** [comment]
There is already capability to run cesm postprocessing in a somewhat different mechanism.  For example the option
--workflow timeseries to create_newcase will add a timeseries generation step.

**Comment by briandobbins** [comment]
Ah, thank you - I'll take a look into this.  I'm completely unfamiliar with the 'workflow' capabilities.  Does it have the capability to add multiple arbitrary scripts?  We want to do timeseries creation _and_ call a custom script for transferring to a cloud bucket.

**Comment by jedwards4b** [comment]
yes, we should be able to do that

**Comment by ekluzek** [comment]
It sounds like this wasn't really an issue.
