### ISSUE TITLE
Add remote capability to *_SCRIPT options in CIME

### ISSUE THREAD

**Issue by briandobbins** [ESMCI/cime#4068]
This is an independent issue to #4067 but, in my opinion, also useful.  The goal is to interpret any script name given by those options that starts with a 'http' as an external link, to pull & run.  The upside is that this would allow users to link to (for example) Github code for these scripts, enabling easy sharing of them, not to mention mid-run modification if desired.

This might not matter for systems where all runs are done locally, but if you're doing runs distributed across multiple clusters without a shared file system, it's very convenient.  This is the case for a set of cloud runs we'll be doing where each has an independent file system.

One catch with this is that many systems don't currently allow compute nodes direct access to the internet, so do we need to detect if we're using a URL, and check that if so?  Or just chalk that up as 'user error', like specifying an output directory that doesn't exist?  On cloud platforms, where this will be tested, this isn't a problem.

Another potential issue is security related - if not done carefully, one could of course reference a script that looks good, then it gets modified to do nefarious things.  I guess a mitigation strategy here is to use Github hashes, or repos you trust?  Since this isn't likely to be a common feature for now, though, I'm inclined to not worry about this for the moment, if ever.

**Comment by jedwards4b** [comment]
I'm not sure I see an advantage to this and given the security downside would be hesitant to automate it.  I would like to understand better the issue - let's discuss.
