### ISSUE TITLE
Naming conventions for files in cime_config/

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#4076]
## Background

In recent CSEG meetings, we talked about file naming conventions to maintain consistency among all the components -- namely, should python files have the `.py` extension or not. The prevailing view was that python modules that are meant to be imported should have the extension, scripts that should be run from the command line should not have it, and files that currently do double duty via `if __name__ == "__main__"` blocks should be split into two files (a `.py` module and a extension-free wrapper).

One big hitch to this plan is how CIME treats `cime_config/buildnml`. Currently there is logic that tries to import specific functions from `buildnml`, and falls back to executing the script via `subprocess`. @billsacks and I chatted about how to modify CIME to follow these conventions, and came up with some interesting ideas we thought were worth discussing.

## Potential paths forward

Assuming other groups agree that this would be a nice convention to follow, there a few possible ways to proceed.

1. The simplest fix would be to update `run_sub_or_cmd()` to try to import `f"{filename}.py"` before falling back on the current behavior of trying to import `filename` and running `filename` if the import fails. Perhaps in a later version this could collapse to "try to import `filename.py` or run `filename`", but leaving the middle check would maintain backwards compatibility for the current version.
2. Another possibility would be to allow components to make `cime_config` a package (i.e. include `__init__.py`). Then we could try to import `cime_config`, and fall back to the current behavior in CIME6 (again, perhaps cutting out the `import filename` option in future versions). This could potentially clean up some python code in components -- one example is that POP has a python layer that sits between `buildnml`; if these functions are included in the `cime_config` package it is easier to import them into `buildnml`.
3. A third possibility would be to enforce a rule that each component has `cime_config/${COMPNAME}/__init__.py`; this would let us more cleanly separate the python code in `cime_config` from the XML and the test suite files. It might also let us clean up `import` statements since there is no longer a namespace conflict every time you import a new `buildnml` (or `cime_config` in the above option)

## Questions

1. Does it make sense to make `buildnml` a wrapper script that imports `buildnml.py`?
2. If so, are any of the above paths the right answer for how CIME should make use of this renamed module?

In case it changes how you answer the above questions, I'll note that I am happy to take lead on implementing whatever solution results from this issue ticket.

**Comment by rljacob** [comment]
Other suggestions from telecon:
${COMPNAME}_forcime_py
${COMPNAME}_cimepck_py

NOT ${COMPNAME}_py because another model may use that in some other context.

**Comment by billsacks** [comment]
I think that the ideas proposed here will also make for a cleaner method of importing system test modules that are defined in components. For example, see this comment that I wrote a while ago:

https://github.com/ESCOMP/CTSM/blob/09ef76bddcd4681bff4cec6b1043b1f8171f8722/cime_config/SystemTests/lii2finidatareas.py#L44-L57
