### ISSUE TITLE
Include xmlchange in tests

### ISSUE THREAD

**Issue by wilke** [ESMCI/cime#408]
xmlchange has no test in scripts_regression_tests.

**Comment by gold2718** [comment]
@rljacob , @mvertens 
Is xmlchange supposed to error on invalid inputs? For instance,
`./xmlchange STOP_OPTION=foo`
seems to run just fine (and a subsequent xmlquery call verifies that foo is the new value). In CIME4, this gave an error.

**Comment by jedwards4b** [comment]
It should check against valid values if defined.  I have a fix, testing now, pr soon.

**Comment by rljacob** [comment]
What to test for is being discussed in #550

**Comment by rljacob** [comment]
There are now 2 uses of xmlchange in scripts_regression_tests.

**Comment by rljacob** [comment]
Also above example from gold2718 now gives an error.
