### ISSUE TITLE
tx0.1v3 mesh file is missing needed for running grids with t13 for NUOPC

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4089]
The mesh file is missing from config_grids.xml for tx0.1v3. This means that any grids that use t13 fail when you try to run the case.

The nuopc.runconfig file is missing a setting for mesh_mask which is set to UNSET.

cesm.log returns with a bunch of errors like this...

```
29:NetCDF Error: UNSET : No such file or directory
30:NetCDF Error: UNSET : No such file or directory
3:MPT ERROR: Rank 3(g:3) is aborting with error code 1.
3:	Process ID: 72703, Host: r11i1n29, Program: /glade/scratch/erik/SMS_Vnuopc_Ld1.hcru_hcru_mt13.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20210909_143420_zcv0b5/bld/cesm.exe
3:	MPT Version: HPE MPT 2.22  03/31/20 15:59:10
3:
3:MPT: --------stack traceback-------
-1:MPT ERROR: MPI_COMM_WORLD rank 17 has terminated without calling MPI_Finalize()
-1:	aborting job
```

**Comment by ekluzek** [comment]
The grids that will fail for NUOPC are:

T62_t13
TL319_t13
TL319_t13
ne120pg3_ne120pg3_mt13
ne120pg3_t13

@alperaltuntas @fischer-ncar these are grids that you added

**Comment by alperaltuntas** [comment]
@ekluzek. I believe we need to create the mesh file using the ESMF_Scrip2Unstruct tool, right? If so, could you point me to a recent version and instructions on how to use it?

**Comment by ekluzek** [comment]
Yes, I think that's right as well. I did use it once for another grid, a few months ago, but I'm not that current on it either. There's an option to the tool to create a "dual mesh" and I did find that we don't need to do use that option. So that's the main advice I can give you don't use the option to create a dual mesh.

**Comment by gustavo-marques** [comment]
@alperaltuntas, I've created a mesh for the MOM6 tx0.1_v3 a while ago. Here is the script I used:

`/glade/work/gmarques/Projects/MOM_tx0.1_v3/create_mesh
`

`/glade/scratch/mvertens/meshes/ESMF_Scrip2Unstruct `is no longer there, so try using the version below instead.

`/glade/p/cesmdata/cseg/PROGS/esmf/8.2.0b13/mpt/2.22/intel/19.1.1/bin/binO/Linux.intel.64.mpt.default/ESMF_Scrip2Unstruct`

**Comment by ekluzek** [comment]
@alperaltuntas the file you created was in NetCDF-4 format 

/glade/p/cesmdata/cseg/inputdata/share/meshes/tx0.1v3_210910_ESMFmesh.nc

so I converted it to NetCDF-5 format and called it...

share/meshes/tx0.1v3_ESMFmesh_cdf5_c20211011.nc

This update is in the PR #3823

**Comment by uturuncoglu** [comment]
@alperaltuntas this is the correct way to create ESMF Mesh file. What do you mean when you are saying "mesh file doesn't appear to have the correct coordinates"? It might be an issue in SCRIP file itself that could lead to a buggy ESMF Mesh file. As I know, NCL is not perfect way of creation SCRIP files especially for tri-polar grids.

**Comment by alperaltuntas** [comment]
Thanks, @uturuncoglu. 

@mvertens , I just tested the tx0.1v2 mesh you created earlier and it is also leading to the same error. Here is the test root: /glade/scratch/altuntas/SMS_D_Vnuopc.T62_t12.GIAF_HR.cheyenne_gnu.20211019_105920_yio209

**Comment by ekluzek** [comment]
OK, I moving the problem with the mesh files for POP under a new issue #4121.

This issue will close when my PR for mizuRoute comes in as it provides a file that's functional for non-ocean cases.
