### ISSUE TITLE
domain files are required for NUOPC grids, but unused

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4090]
In order to add a CESM grid a domain file MUST be specified in order for the grid to be recognized. But, in the NUOPC driver case those same domain files are ultimately ignored. So it would be good to have a way to validate the grid by setting the domain file to something like NUOPC_unused or some such string so that they make the grid valid, but they aren't actually used anywhere.

**Comment by ekluzek** [comment]
As a first try at this I'm doing this for a half degree grid:

``` xml
     <domain name="360x720cru">
       <nx>720</nx> <ny>360</ny>
       <file grid="atm|lnd">$DIN_LOC_ROOT/share/domains/domain.clm/domain.lnd.360x720_cruncep.100429.nc</file>
+      <file grid="atm|lnd" mask="tx0.1v3" >$DIN_LOC_ROOT/share/domains/domain.does_not_exist.nc</file>
       <mesh driver="nuopc">$DIN_LOC_ROOT/share/meshes/360x720_120830_ESMFmesh_c20210507.nc</mesh>
       <desc>Exact half-degree CRUNCEP datm forcing grid with CRUNCEP land-mask -- only valid for DATM/CLM compset</desc>
     </domain>
```

So I'm giving it a name to a file that doesn't exist. If you don't add a line for the mask the grid is considered invalid. I am able to get it to build with the above setup, but right now it's failing for me.

**Comment by billsacks** [comment]
@mvertens has resolved this.
