### ISSUE TITLE
Need Help! build error

### ISSUE THREAD

**Issue by demibing** [ESMCI/cime#4096]
Sorry to bother you, there's a problem that has been bothering me for a few days. When I build a case, there is error "ERROR: /cime/src/build_scripts/buildlib.gpl FAILED, cat /CASE_DIR/test/bld/gptl.bldlog.210918-095207" and I really didn't know how to do. I really need your help, Thanks a lot.

**Comment by billsacks** [comment]
Sorry, this fell through the cracks and I just noticed it in a review of open issues. If this is an issue with CESM (or one of the components of CESM, such as CAM or CTSM), please post your issue to the CESM forums <https://bb.cgd.ucar.edu/cesm/> - specifically, <https://bb.cgd.ucar.edu/cesm/forums/infrastructure-cime-porting-machines-scripts.132/>. Please be sure you include the information requested here: <https://bb.cgd.ucar.edu/cesm/threads/information-to-include-in-help-requests.4974/>
