### ISSUE TITLE
License text file update

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4107]
I'm not sure I have all of this right from the meeting today.  So I'll start an issue so I'll be sure to get it right.

ESMCI/CIME LICENSE.TXT:                  Remove the reference to Argonne.
ESCOMP/CESM_share:                        Remove the reference to Sandia.
ESCOMP/CESM_CPL7andDataComps: Remove the reference to Argonne.

@rljacob and @billsacks correct me if I'm wrong.  Which I'm pretty sure I am.

**Comment by billsacks** [comment]
> ESCOMP/CESM_CPL7andDataComps: Remove the reference to Argonne.

I think that should be: Remove the reference to Sandia.

Other than that, I think that's right, but @rljacob should confirm.
