### ISSUE TITLE
Need way to specify different pelayout in tests.py tests

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#4111]
For testing supported via tests.py, we need a way to specify a pelayout to use only if a case is part of a test.

For example, SMS.ne30pg2_EC30to60E2r2.WCYCL1850 will ask for 53 nodes on Chrysalis which is much more then the debug queue (20).  It will compete with other users in the regular queue, not run for hours, and keep the suite from finishing overnight.

Now I could add "PS" to the name to force the "small" layout but this has several problems:  it changes the name of the test and so new baselines are needed, it forces the "small" layout to be used everywhere that test runs and small may not be defined or be to small on other machines (so it takes forever to run).  

What we need instead, is a way to say "if this case is part of a test and on this machine, use this pelayout".   The existing pelayouts are optimized for production runs.

One way to do this would be the look for config_pesall.test.xml for the pelayouts if create_test is used.  This would override whats in PES_SPEC_FILE.   Another way is to add an optional key in config_pesall.xml to separate test from regular entries.

**Comment by rljacob** [comment]
I thought the xml-based testing already supported this?

**Comment by jedwards4b** [comment]
XML currently only supports definitive values for both mpi tasks and threads eg _P36x4, what Bill is suggesting is _Px2 would use the default layout but change the thread count to 2.  That should be an easy feature to add.
