### ISSUE TITLE
Add python module load command for izumi

### ISSUE THREAD

**Issue by peverwhee** [ESMCI/cime#4116]
To ensure CAM runs with python 3.7.0, add a module load command to the izumi section in config_machines.xml.

>  < command name="load" >lang/python/3.7.0</command>

**Comment by gold2718** [comment]
There has been a discussion over in #4117 about whether and why python 3.7 might be needed in CAM.
The new answer (after much testing) is that we do not need python 3.7 to build and run CAM.
However, we would like to use at least one python3.7 feature to clean up our code and for running tests.
An example of the change is in the "type" of a compiler regular expression.

In python 3.6.8 (default on Izumi):
```
>>> import re
>>> foo = re.compile(r"hi mom")
>>> type(foo)
<class '_sre.SRE_Pattern'>
>>> isinstance(foo, _sre.SRE_Pattern)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_sre' is not defined
>>> bar = foo.match("hi mom, how are you?")
>>> type(bar)
<class '_sre.SRE_Match'>
```

In python 3.7.0:
```
>>> import re
>>> foo = re.compile(r"hi mom")
>>> type(foo)
<class 're.Pattern'>
>>> isinstance(foo, re.Pattern)
True
>>> type(bar)
<class 're.Match'>
>>> isinstance(bar, re.Match)
True
```

So both in code (wanting to use duck typing to catch an input that may be a regular expression pattern) and in doctests (e.g., did a routine correctly return a regular expression match), python 3.7 offers a cleaner approach.
