### ISSUE TITLE
Update mpi-serial library

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#412]
Update the mpi-serial library (part of MCT) to recognize MPI 3 code in PIO1. Also fix the configure script so that it works on Cetus/Mira.

**Comment by jayeshkrishna** [comment]
As @sarich noted in PR #410 , mpi-serial fails to recognize MPI_ORDER_FORTRAN (fails to compile).

**Comment by jayeshkrishna** [comment]
The issue with MPI_ORDER_FORTRAN not being recognized by the mpi-serial library on eos is now solved (a typo mistake in the config file for eos resulted in pnetcdf modules being loaded for mpi-serial. Once the typo was fixed the current build system disables MPIIO in PIO1, that uses MPI_ORDER_FORTRAN, for the mpi-serial library).
However this is a to-do item.
Also mpi-serial still does not build on Cetus/Mira.

**Comment by rljacob** [comment]
Turns out MPI_ORDER_FORTRAN isn't needed.  Closing.
