### ISSUE TITLE
Easier split of case jobs into different queues

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4120]
The system on which I (the user) run CESM2.1.3 (archer2) uses Slurm and has two queues: "standard" and "short", the latter being suited for small jobs shorter than 20 minutes.

1) Is there a way to configure CESM2 (presumably using config_batch.xml) so that any jobs with walltime ≤ 20 minutes are automatically submitted to the short queue, rather than the standard one (without having to manually edit the case.st_archive file)?

2) Additionally, for jobs submitted to the short queue, this system requires an extra sbatch option, "--reservation=shortqos". Again, I wondered if there's way to set up config_batch.xml so that any jobs submitted to the short queue will automatically include that option.

**Comment by jgfouca** [comment]
@jedwards4b , config_batch.xml supports `walltimemax` and `walltimemin`. These should be what you need for 1. 

As for 2., I don't think config_batch.xml is expressive enough to support what you need. Looking at what's currently supported, I think there is room for improvement.

Current syntax:
```
<arg flag="--time" name="$JOB_WALLCLOCK_TIME"/>
```

I think this would be better:
```
<arg [optional selectors] >"--time=$JOB_WALLCLOCK_TIME"</arg>
```

This would bring things more closely in line with how the rest of the XML system works.

Your use case would look like this:
```
<arg job_queue="short">"--reservation=shortqos"</arg>
```
