### ISSUE TITLE
Alternative way to do long runs with CCS

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#4126]
The current recommended way to set up a long 100+ year run with the CCS is:
1. user determines total years, say 100
2. user determines what chunk is best done in a single submission taking queue limits, etc. in to account.   Say that is 20 years.
3. User sets STOP_OPTION to nyears, STOP_N to 20 and RESUBMIT to 5.   Submit once to do entire run.

This is great unless the chunk does not evenly divide the total years.  If the total was 90 years but best chunk is 20, the user would
1.  Set STOP_OPTION to nyears, STOP_N to 20 and RESUBMIT to 4.  submit.
2. Set STOP_N to 5 (resubmit would already be 0). submit.

What if we had a way to do that last example in a single submission?
1. User sets STOP_OPTION to nyears.   User sets (new CCS variables) TOTAL_N to 90 and CHUNK_N to 20.
2. CIME calculates that 90/20 = 4 and sets RESUBMIT to 4.
3. CIME also calculates RESUB_REMAIN to be 10 and, after resubmit winds down to 0, does a final submission of 10 years.

I don't have a strong opinion on the new variable names.

**Comment by rljacob** [comment]
cc @golaz

**Comment by singhbalwinder** [comment]
Thanks for explaining it so clearly. I like the "single submission" approach. If possible, we can also add an option for having a different wall clock time for the RESUB_REMAIN run. As an odd corner case example, if we are to run a simulation for 81 years with CHUNK_N=20, RESUB_REMAIN is just 1. If we asking 2 days. of wall clock time for each CHUNK_N, the last one year of simulation may have to wait for a long time to get into the queue.

**Comment by ekluzek** [comment]
@rljacob an alternative way to do this may be available now. This used to work, but I don't think it's commonly used now. There is a STOP_DATE option that you can set for the end date of your entire simulation. So you would set that as the final date you want to run to, and then set the RESUBMIT and STOP_N normally.

If this doesn't work it could be setup to work pretty easily and you wouldn't have to add any new xml variables.

**Comment by rljacob** [comment]
Yes I was wondering if that was possible.  So CIME will pay attention to STOP_DATE even if STOP_OPTION is not set to "date" ?

**Comment by ekluzek** [comment]
It used to be setup that way anyway. I don't know that it still works though, so I'd recommend trying it out.

**Comment by golaz** [comment]
I found another relevant discussion under in https://github.com/ESMCI/cime/issues/3969. 

In that thread, it seems like STOP_DATE won't do anything unless STOP_OPTION is set to "date".

**Comment by ekluzek** [comment]
@golaz I looked at this issue, and I don't think that was strictly determined. I suggest trying it out now and see if it works. If not it's likely easy to change so that it does.

**Comment by golaz** [comment]
@ekluzek : I just ran a short test (2x6 days) and specifying STOP_DATE to stop after 10 days instead of 12 days. Good news, it worked!

STOP_DATE must be specified as yyyyddmm **without leading zeros** in yyyy as discussed in the other thread.

I'm going to use this for my next long simulation. This will make my life easier.

Thanks for the suggestion.

**Comment by jgfouca** [comment]
Closing. Please reopen if the STOP_DATE solution is not adequate.
