### ISSUE TITLE
Extraneous warnings when creating a case: "Machine object has no machine defined"

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4135]
When creating a case where the machine is not explicitly defined, the warning "Machine object has no machine defined" is sometimes generated numerous times (once on cheyenne, four times on my Mac). From inserting some debugging statements, it looks like this is generated after each attempt to lookup a machine with the new `$ENV` pattern introduced in #4106. I'm not sure this warning actually indicates a problem, but getting these extra warnings when creating a case can be confusing.

I think I understand why this is happening, but I'm not sure what the right solution is: I think the issue is that the `__init__` method in `Machines` calls `probe_machine_name`, which calls `_probe_machine_name_one_guess`, which calls `get_resolved_value` which calls `get_value`, all before `self.set_machine` is called (which is done at the end of the `__init__` method) – and since `self.set_machine` hasn't been called yet, `self.machine_node` is `None`, triggering the warning in `get_value`.

**Comment by jasonb5** [comment]
@billsacks Thanks, you're spot on with the analysis. The logic looks fine, and as you pointed out the warning doesn't really indicate a problem. I'm inclined to just change this to a debug statement.

**Comment by jedwards4b** [comment]
Sorry, I thought that I had fixed this already, but I forgot to commit it.
My change was to change the logger.warning to logger.debug in machines.py

**Comment by billsacks** [comment]
Sounds good, thanks guys.

**Comment by jasonb5** [comment]
@billsacks @jedwards4b I think I found another issue with detecting a machine, so I'll bundle these together in a PR.
