### ISSUE TITLE
PFUNIT-based unit tests should use new CMake Macros files, not old config_compilers.xml

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4136]
In updating my Mac's CIME port to the new CMake Macro-based system, I noticed that `scripts/fortran_unit_testing/run_tests.py` still needs things defined in config_compilers.xml: defining PFUNIT_PATH (and maybe other things?) in the new macros format does not seem sufficient.

For example, if I remove the path to PFUNIT from the cheyenne section in CESM's config_compilers.xml, I get

```
ERROR: PFUNIT_PATH not found for this machine and compiler, with MPILIB=mpi-serial and compile_threaded=FALSE.
You must specify PFUNIT_PATH in config_compilers.xml, with attributes MPILIB and compile_threaded.
```

(I tried this out of the latest CTSM master, with its externals, running `../cime/scripts/fortran_unit_testing/run_tests.py --build-dir unit_tests.temp` from CTSM's `src` directory.)

Since I think we want to eventually remove the need for config_compilers.xml (I assume?), I'm thinking this run_tests.py script should be updated to use the new macros-based method.

By the way, this exercise made me explore the new CMake Macro-based system in more detail. I feel like this is a definite improvement over the previous config_compilers.xml. Thank you @jgfouca and @jedwards4b for all of your work on this!

**Comment by jgfouca** [comment]
Thanks, @billsacks . I will look at this when i get a chance. Yes, we want to be able to remove config_compilers.xml.

**Comment by billsacks** [comment]
Maybe related to this: I'm finding that, since the changes in #4122 , running the PFUNIT-based unit tests requires setting `CIME_NO_CMAKE_MACRO=ON` in your environment. This requires a change to funit.py for now. I will submit a PR shortly. I'm hoping that once this issue is resolved, we can remove the setting of `CIME_NO_CMAKE_MACRO=ON` both in funit.py and here:

https://github.com/ESMCI/cime/blob/7e63749f25beb78e319514292c6b0d2ca26f3054/scripts/lib/CIME/tests/test_sys_unittest.py#L18
