### ISSUE TITLE
All CDASH builds failing

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4140]
Merge of #4129  is causing all of the cdash builds to fail.

**Comment by jedwards4b** [comment]
@jasonb5 this broke the cmake/ctest interface to scripts_regression_tests.py

**Comment by jedwards4b** [comment]
In my sandbox I've moved CMakeLists.txt and list_tests from cime/scripts/tests to cime/scripts/lib/CIME/tests 
but the list_tests script no longer finds and test except the one B_CheckCode which is explicitly listed therein.

**Comment by jasonb5** [comment]
@jedwards4b Looking at this now.

**Comment by jedwards4b** [comment]
Update: currently the cdash tests all indicate passing, but a deeper look will reveal that most are still failing.

**Comment by jasonb5** [comment]
#4143 Fixes returning correct test status and I've only been seeing 4 tests failures after this fix.

**Comment by jgfouca** [comment]
I think this was fixed by #4143 .
