### ISSUE TITLE
scripts_regression_tests fails not captured 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4146]
FAIL: test_self_build_cprnc (CIME.tests.test_sys_cime_case.TestCimeCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/lib/CIME/tests/test_sys_cime_case.py", line 721, in test_self_build_cprnc
    self._wait_for_tests(self._baseline_name, always_wait=True)
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/lib/CIME/tests/base.py", line 262, in _wait_for_tests
    self.run_cmd_assert_result(
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/lib/CIME/tests/base.py", line 137, in run_cmd_assert_result
    self.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 100 != 0 : 
    COMMAND: /glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/Tools/wait_for_tests  *fake_testing_only_20220103_081933/TestStatus
    FROM_DIR: /glade/scratch/jedwards/scripts_regression_test.20220103_081933
    SHOULD HAVE WORKED, INSTEAD GOT STAT 100
    OUTPUT: FAIL ERS_Ln7.f19_g16_rx1.A.cheyenne_intel (phase RUN)
    Case dir: ERS_Ln7.f19_g16_rx1.A.cheyenne_intel.fake_testing_only_20220103_081933
    ERRPUT: 
    

----------------------------------------------------------------------
Ran 1 test in 385.827s

FAILED (failures=1)
All pass, removing directory: /glade/scratch/jedwards/scripts_regression_test.20220103_081933

**Comment by jgfouca** [comment]
This is very bad if tests are failing but not getting reported.

**Comment by jasonb5** [comment]
To clarify, the test results are reported correctly, this issue is concerning the message `All pass, removing directory: /glade/scratch/jedwards/scripts_regression_test.20220103_081933`.
