### ISSUE TITLE
Some CIME capabilities should be extendable by the host model without needing to change CIME itself

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#4153]
Provenance is an obvious one. Any place that requires an `if model == "xxx"` is a candidate for a better extension mechanism.

**Comment by mvertens** [comment]
@jgfouca - thanks for raising this point. I think it would be good to get an inventory of all places in CIME where 'if model == 'xxx' occurs and start reviewing those at the next CIME meeting. It would at least be a starting point for determining the next lowest hanging fruit.

**Comment by rljacob** [comment]
We could start with the two ways of constructing and processing test suites.   One use a python dict and the other an xml file.

**Comment by jgfouca** [comment]
Jason's big recent PR fixed this.
