### ISSUE TITLE
ERT tests reference AVG_HIST_N/AVG_HIST_OPTION and hence fail to work

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4160]
ERT tests (in cime6.0.12) reference two non-existing XML variables (at least in CESM) AVG_HIST_N and AVG_HIST_OPTION

scripts/lib/CIME/SystemTests/ert.py:        self._case.set_value("AVG_HIST_N", 1)
scripts/lib/CIME/SystemTests/ert.py:        self._case.set_value("AVG_HIST_OPTION", "nmonths")

Tests with ERT thus fail with an error something like this...

> Submitting job script qsub -q premium -l walltime=00:40:00 -A P93300606 -v ARGS_FOR_SCRIPT='--skip-preview-namelist' .case.test
> Submitted job id is 2486390.chadmin1.ib0.cheyenne.ucar.edu
> Submitted job case.test with id 2486390.chadmin1.ib0.cheyenne.ucar.edu
> env_batch.xml appears to have changed, regenerating batch scripts
> manual edits to these file will be lost!
> 
> submit_jobs case.test
> Submit job case.test
> 
>  ---------------------------------------------------
> 2022-01-15 12:23:01: ERROR: No variable AVG_HIST_N found in case
>  ---------------------------------------------------

I'm not quite sure why AVG_HIST is being exercised here for this test.

**Comment by ekluzek** [comment]
Looking at it, I had thought that the ERT test changed just the number of threads (similar to the ERP test). But, it's actually constructed to just do a 2 month restart test. And there's actually little flexibility to change the length. So I'm wondering if we shouldn't just completely remove this?

It's also not being exercised (at least for CESM) as far as I could tell. @mvertens @jedwards4b @fischer-ncar should we just remove this test?

**Comment by ekluzek** [comment]
It did seem to work when I commented out the two lines in ert.py that had to do with AVG_HIST settings.

> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default CREATE_NEWCASE
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default XML
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SETUP
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SHAREDLIB_BUILD time=203
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default MODEL_BUILD time=39
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SUBMIT
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default RUN time=337
> FAIL ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default COMPARE_base_rest
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default MEMLEAK insuffiencient data for memleak test
> PASS ERT_P720x4.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SHORT_TERM_ARCHIVER

**Comment by rljacob** [comment]
Should this test instead use HISTAVG_N and HISTAVG_OPTION which do exist (in the mct coupler) ?

**Comment by rljacob** [comment]
Some old docs have this for ERT:
ERT (exact restart from startup, default 2 month + 1 month (ERS with info dbug = 1))

**Comment by billsacks** [comment]
From cime telecon: we should remove this old, non-working test.
