### ISSUE TITLE
Document new scripts_regression_tests testing procedure on wiki

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4164]
In https://github.com/ESMCI/cime/pull/4129 @jasonb5 updated the CIME user's guide for the new scripts_regression_tests procedure. (Thank you, Jason!). It looks like our wiki page on testing (which is where I tend to look) should also be updated: https://github.com/ESMCI/cime/wiki/Testing . Maybe one should link to the other? (Arguments for having the wiki page be the definitive guide on testing CIME itself are: I view wikis as more developer-centric and User's Guides as more user-centric; and updating the wiki as procedures change is lighter-weight. But an argument for having this in the User's Guide is that we can document different versions of the testing procedure for different versions of CIME. In the end, I don't have strong feelings one way or the other.)

This can wait until after Jason's recent reorganization PR is merged, since I imagine the details of the testing procedure might change with that.

**Comment by billsacks** [comment]
Also, I noticed that the CIME user's guide needs to be rebuilt. See https://github.com/ESMCI/cime/wiki/Working-with-Sphinx-and-reStructuredText

**Comment by jasonb5** [comment]
@billsacks @jgfouca @jedwards4b @mvertens 
I've updated the wiki (https://github.com/ESMCI/cime/wiki/Testing), please review when you get a chance.

There will be a PR with this as well to remove [CIME's scripts regression tests](https://esmci.github.io/cime/versions/master/html/users_guide/testing.html#cime-s-scripts-regression-tests) from `gh-pages` and replace it with a link to the wiki so all of our CIME developer information is in a single place.

**Comment by jgfouca** [comment]
@jasonb5 , looks good, thanks!

**Comment by billsacks** [comment]
Thanks so much! I don't have time to look in detail right now, but I appreciate this and am fine with you closing this issue.

**Comment by jasonb5** [comment]
Sounds good, I'll close this with the PR removing dev documentation and replacing with link to wiki.

**Comment by jasonb5** [comment]
Side note concerning documentation, I've fixed the GitHub actions documentation workflow.

If you make a PR with documentation changes the workflow will build the documentation and comment with a link to a preview. Once the PR is merged the documentation is available as the `master` version.

Another thing to note, if you're making documentation changes the PR must be from a branch in the `cime` repo not a forked branch. PR's from forked branches don't have the permissions required for the workflow to run correctly. This is also true for PRs containing changes to the CIME container under `docker/`.
