### ISSUE TITLE
PROJECT not resolving on blues during create_newcase

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#417]
Using the latest master (212b185f239) I'm getting the following error on Blues:

blogin1[45]: ./create_newcase --case tryX --compset X --res f19_g16 --project ACME 
Compset longname is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV 
Compset specification file is /lcrc/group/earthscience/jacob/cimeESMCI2/scripts/Tools/../../driver_cpl/cime_config/config_compsets.xml
Pes     specification file is /lcrc/group/earthscience/jacob/cimeESMCI2/scripts/Tools/../../cime_config/acme/allactive/config_pesall.xml
Not able to fully resolve item '/lcrc/project/$PROJECT/jacob/acme_scratch/tryX/bld'
Not able to fully resolve item '/lcrc/project/$PROJECT/jacob/acme_scratch/tryX/run'

$PROJECT DOES get set in env_batch.xml

**Comment by rljacob** [comment]
On further investigation, the "bld" and "run" directories are quietly (no message to stdout) created by case.setup. Should create_newcase or case.setup make those?

**Comment by rljacob** [comment]
@jedwards4b  said "case.setup".  Then what is create_newcase trying to do with those paths?

**Comment by jedwards4b** [comment]
create_newcase is looking to see if they exist and warning the user if they do.   I'm looking into why this doesn't resolve now.

**Comment by jedwards4b** [comment]
I think that cime is working fine on blues with the exception of printing this warning in create_newcase.
