### ISSUE TITLE
Fix races with wait_for_tests and/or TestStatus.log

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#418]
```
======================================================================
FAIL: test_b_full (scripts_regression_tests.O_TestTestScheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "scripts_regression_tests.py", line 601, in test_b_full
    "Broken test did not report build error")
AssertionError: Broken test did not report build error
```

^ This is the test where the race manifests. It probably has something to do with test_scheduler and system_test_common both trying to write to the TestStatus.log file simultaneously. The test_scheduler should no longer need to do anything to TestStatus.log for the build or test phase. There also could be a problem with wait_for_tests not waiting.

**Comment by rljacob** [comment]
Its not clear what the content in the description has to do with the issue.   Also, should that say "Fix races"?

**Comment by jgfouca** [comment]
@rljacob ok, updated

**Comment by rljacob** [comment]
So ACME's cime2 is also doing this?

**Comment by jgfouca** [comment]
No, cime2 doesn't even have this test and test_scheduler (called create_test_impl in cime2) handles all the TestStatus.log updates.

**Comment by jedwards4b** [comment]
There was no race condition; the problem was simply that the submitted batch job for case.test was sending the exception to stderr but not logging it and test_scheduler was not able to log it on batch systems.
