### ISSUE TITLE
create_newcase does not show --driver option

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#4181]
The `create_newcase` script does not show the `--driver` option, however, some users need to access it. git blame points to @jgfouca. Does anyone know why `help=argparse.SUPPRESS` is added to this option?

**Comment by jedwards4b** [comment]
I have confirmed that the driver option is shown in create_newcase.  
```
 --driver {mct,nuopc}  Override the top level driver type and use this one (changes xml variable COMP_INTERFACE) [this is an advanced option]
```

**Comment by rljacob** [comment]
Have to remember to update that string to include moab.
