### ISSUE TITLE
case cloned via create_clone does not have RESUBMIT match the parent case

### ISSUE THREAD

**Issue by jhollowed** [ESMCI/cime#4192]
As title; after cloning a case with `case_clone`, I find that the clone is identical in configuration to the parent case, except that teh `RESUBMIT` option defaults back to `0`, when in the parent case, it is nonzero. Is this intentional?

**Comment by jedwards4b** [comment]
Yes, this is intentional.

**Comment by jhollowed** [comment]
> Yes, this is intentional.

Thanks for the response! Is there any documentation that details this feature? It's not immediately obvious to me why this should be the case, and I also don't want to inadvertently do something wrong by misunderstanding (e.g. am I able to manually set the RESUBMIT option in a cloned case after the fact, or will this have consequences?)

**Comment by jedwards4b** [comment]
Yes you can absolutely change the RESUBMIT option after cloning.  It's reset so that the case is in a known state after cloning. 

[cloning a case](https://esmci.github.io/cime/versions/ufs_release_v1.1/html/users_guide/cloning-a-case.html?highlight=clone)
