### ISSUE TITLE
Baselines being removed from generated baseline directory

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4193]
PR #4154 is overly aggressive in remove baselines when using --retry in create_test.

For example
./create_test --xml-category aux_cime_baselines --generate TEST_BASELINE2 --compare cesm2_3_alpha08b --no-build --retry 2
./create_test --xml-category aux_cime_baselines --generate TEST_BASELINE1 --compare cesm2_3_alpha08b --no-build

TEST_BASELINE2 has been cleaned out, while TEST_BASELINE1 still has the baseline namelist files.

**Comment by fischer-ncar** [comment]
Can we do something like this.

```
                        if allow_baseline_overwrite and retry == "None":
                            if self._namelists_only:
                                clear_folder(os.path.join(test_baseline, "CaseDocs"))
                            else:
                                clear_folder(test_baseline)
```

Of course we would need to have retry passed in.  I was able to put something together that seemed to work.

**Comment by jedwards4b** [comment]
@fischer-ncar do you want to submit a PR?

**Comment by fischer-ncar** [comment]
Okay.
