### ISSUE TITLE
Height modifier to res option appears to be broken

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4200]
There is a little known feature of the res argument that allows you to specify a non-standard
vertical dimension argument, so for example f09z83_g17 should give you a case with 83 vertical levels,
however testing in cesm2.1.4-rc11 seems to indicate that this option is broken in cesm2.1.  
```
./create_newcase --case $casedir --res f09z83_g17 --compset B1850cmip6 --run-unsupported     
Compset longname is 1850_CAM60_CLM50%BGC-CROP-CMIP6DECK_CICE%CMIP6_POP2%ECO%ABIO-DIC_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD
Compset specification file is /glade/work/jedwards/sandboxes/cesm2_1/cime/../cime_config/config_compsets.xml
Warning: missing non-idmap ATM2OCN_FMAPNAME for atm_grid, 0.9x1.25z83 and ocn_grid gx1v7 
Warning: missing non-idmap ATM2OCN_SMAPNAME for atm_grid, 0.9x1.25z83 and ocn_grid gx1v7 
Warning: missing non-idmap ATM2OCN_VMAPNAME for atm_grid, 0.9x1.25z83 and ocn_grid gx1v7 
Warning: missing non-idmap OCN2ATM_FMAPNAME for atm_grid, 0.9x1.25z83 and ocn_grid gx1v7 
Warning: missing non-idmap OCN2ATM_SMAPNAME for atm_grid, 0.9x1.25z83 and ocn_grid gx1v7 
Warning: missing non-idmap ATM2LND_FMAPNAME for atm_grid, 0.9x1.25z83 and lnd_grid 0.9x1.25 
Warning: missing non-idmap ATM2LND_SMAPNAME for atm_grid, 0.9x1.25z83 and lnd_grid 0.9x1.25 
Warning: missing non-idmap LND2ATM_FMAPNAME for atm_grid, 0.9x1.25z83 and lnd_grid 0.9x1.25 
Warning: missing non-idmap LND2ATM_SMAPNAME for atm_grid, 0.9x1.25z83 and lnd_grid 0.9x1.25 
Warning: missing non-idmap ATM2WAV_SMAPNAME for atm_grid, 0.9x1.25z83 and wav_grid ww3a 
```

**Comment by jedwards4b** [comment]
I also tried in cesm2_3_beta08 and it doesn't give the mapping errors as above but it also doesn't modify the vertical coordinate.

**Comment by gold2718** [comment]
Does this problem happen with both NUOPC and MCT? Currently, there is a prebeta CAM test that exercises this functionality:
```
  <test compset="FDABIP04" grid="T85z60_T85_mg17" name="ERP_D_Ln9_Vmct" testmods="cam/outfrq9s">
    <machines>
      <machine name="izumi" compiler="nag" category="prebeta"/>
    </machines>
  </test>
```
Did this test run in the cesm2_3_beta08 tests?

**Comment by jedwards4b** [comment]
@fischer-ncar ^

**Comment by fischer-ncar** [comment]
ERP_D_Ln9_Vmct.T85z60_T85_mg17.FDABIP04.izumi_nag.cam-outfrq9s ERP_D_Ln9_Vmct.T85z30_T85_mg17.FDABIP04.izumi_nag.cam-outfrq9s 
ERP_D_Ln9_Vmct.T85z60_T85_mg17.FHS94.izumi_nag.cam-outfrq9s
ERP_D_Ln9_Vmct.T85z30_T85_mg17.FHS94.izumi_nag.cam-outfrq9s

All passed

The cam config commands for the FDABIP04 tests were.

/home/fischer/code/cesm2_3_alpha08d/components/cam/bld/configure -s -fc_type nag -dyn eul -hgrid 128x256 -cpl mct -usr_src /scratch/cluster/fischer/ERP_D_Ln9_Vmct.T85z30_T85_mg17.FDABIP04.izumi_nag.cam-outfrq9s.GC.c2_3_b08d_nag/SourceMods/src.cam -nlev 30 -spmd -nosmp -ocn socn -phys adiabatic


/home/fischer/code/cesm2_3_alpha08d/components/cam/bld/configure -s -fc_type nag -dyn eul -hgrid 128x256 -cpl mct -usr_src /scratch/cluster/fischer/ERP_D_Ln9_Vmct.T85z60_T85_mg17.FDABIP04.izumi_nag.cam-outfrq9s.GC.c2_3_b08d_nag/SourceMods/src.cam -nlev 60 -spmd -nosmp -ocn socn -phys adiabatic

**Comment by jedwards4b** [comment]
Thank you @fischer-ncar 
Can you confirm that this works for f09z83_g17 when using mct but not when using nuopc.

**Comment by fischer-ncar** [comment]
For cesm2_3_beta08 f09z83_g17.B1850 I'm getting ncdata undefined errors.  I'll try with an A compset.

**Comment by fischer-ncar** [comment]
For cesm2_3_beta08 B1850 and A for mct I'm getting the following error.
ERROR: Need to provide valid mapping file between atm and ice in xml variable atm2ice_fmapname
Then for nuopc, The A compset ran,  the B1850 compset will build, but it needs 83 level inputfiles.

**Comment by jedwards4b** [comment]
@fischer-ncar What I saw in nuopc was that it was simply ignoring the z83 setting - did you confirm that cam is set with -nlev=83?

**Comment by fischer-ncar** [comment]
@jedwards4b For B1850 nuopc,  the cam configure script was setting "-nlev 83", and the error message I'm getting during the run is.
```
 /glade/p/cesmdata/cseg/inputdata/atm/cam/topo/fv_0.9x1.25_nc3000_Nsw042_Nrs008_
 Co060_Fi001_ZR_sgh30_24km_GRNL_c170103.nc
 hycoef_read: ERROR: file lev does not match model. lev (file, model):
          32          83
 ERROR: hycoef_read: ERROR: file lev does not match model.
```

**Comment by jedwards4b** [comment]
I guess I made a mistake then, could you try this in cesm2.1.4-rc11?  If it works there we can close this issue.

**Comment by fischer-ncar** [comment]
For cesm2.1.4-rc11, -nlev 83 is being set for the cam configure script.  But during build I'm getting

`ERROR: Need to provide valid mapping file between atm and ice in xml variable atm2ice_smapname 
`

**Comment by jedwards4b** [comment]
okay that was the original error.  Changing vertical levels should not require changing mapping files so this is a bug.

**Comment by jedwards4b** [comment]
I tried test ERP_Ln9_D.T85z60_T85_mg17.FDABIP04.cheyenne_intel.cam-outfrq9s in cesm2.3.beta12 and it works as expected.
