### ISSUE TITLE
Not all self.text() should be resolved in PR #4209

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4213]
In PR #4209 self.text() was replaced with self.resolved_text().  This is breaking the connection between
the coupling frequency variables ATM_NCPL, LND_NCPL, ICE_NCPL, GLC_NCPL, WAV_NCPL and OCN_NCPL.  
For C and D compsets LND_NCPL, ICE_NCPL, WAV_NCPL, and GLC_NCPL should be set to $ATM_NCPL. 

Here's a list of some of the tests that are failing.

```
ERI.T62_g17.2000_DATM%NYF_SLND_CICE5_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST.cheyenne_intel.cice5-default 
PEND ERI_Vnuopc.T62_g17.2000_DATM%NYF_SLND_CICE_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST.cheyenne_intel.cice-default
PEND ERS_D_Ld5.T62_g17.2000_DATM%NYF_SLND_CICE5_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST.cheyenne_intel.cice5-default 
ERS_D_Ld5_Vnuopc.T62_g17.2000_DATM%NYF_SLND_CICE_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST.cheyenne_intel.cice-default 
SMS_D.T62_g37.G1850ECO.cheyenne_intel.pop-cice_ecosys
SMS_Ld20.T62_g17.G.cheyenne_intel.pop-performance_eval 
SMS.T62_g17.C1850ECO.cheyenne_intel.pop-ecosys
SMS.T62_g37.C.cheyenne_intel.pop-default
```

The error message I was getting is.
`        ERROR: assume that lnd_cpl_time is equal to atm_cpl_time`

**Comment by jedwards4b** [comment]
I'm sorry I didn't think about this when I reviewed the PR.  This is not the only place where we do not want the 
resolved result.   In, for example, env_base.py there is an argument to get_value: resolved

Is this argument being respected?

**Comment by jasonb5** [comment]
@jedwards4b @fischer-ncar I'm thinking I need to rollback the changes in component.py, compsets.py, and all env_*.py files.

**Comment by jasonb5** [comment]
@jedwards4b The original issue was #4209. I can revert and focus on the one specific case. @jgfouca Do any of the other instances look like we may want to keep the fix?

**Comment by jgfouca** [comment]
@jasonb5 , without having thought too much about it, i think we want to be as consistent as we can when dealing with XML values, so I would revert the change as widely as possible but keep the change that fixes 4209 and add a comment for why the alternate approach is needed there.

**Comment by jasonb5** [comment]
ok sounds good.

**Comment by jedwards4b** [comment]
Do you have a time estimate for this fix?

**Comment by jasonb5** [comment]
@jedwards4b About to create the PR now.

**Comment by jasonb5** [comment]
@jedwards4b https://github.com/ESMCI/ccs_config_cesm/commit/c996fc2b0286727ebb223b8c8db385b52350c334 is causing tests to fail, https://github.com/ESMCI/cime/runs/5841083721?check_suite_focus=true#step:16:574.

**Comment by jedwards4b** [comment]
Please add an env variable CIME_TEST_PLATFORM=ubuntu-latest
to your github workflow.
