### ISSUE TITLE
Remove argparse.SUPPRESS for --driver option in create_newcase

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4220]
The --driver option is suppressed in the help for create_newcase. It is available for create_test. For CESM it would be nice to have help for it so that users can see that it's an option, especially for our transition from MCT to NUOPC. I assume the only reason it was suppressed was it was considered an advanced feature that most people wouldn't use.

There's two other options that are suppressed --script-root and --test and for those I see why they are suppressed.

The change is just to remove the help=argparse.SUPPRESS and add a help string such as

"Override the top level driver type and use this one (changes xml variable COMP_INTERFACE) [this is an advanced option]"

**Comment by ekluzek** [comment]
@jgfouca you are the one that added this in, and included the suppress. What do you think about adding help for this?

**Comment by jgfouca** [comment]
@ekluzek what would be ideal is for only model 'cesm' to have this unsuppressed because we (e3sm) still do not support this option.

**Comment by rljacob** [comment]
We do support --driver.  Its used to switch between mct and moab.

**Comment by ekluzek** [comment]
@rjacob should I add the option back in then for e2sm? I could have the list of valid options different between cesm and e3sm. Maybe that's the only part that should be different between the two?

**Comment by rljacob** [comment]
Yes that sounds good.
