### ISSUE TITLE
E3SM build: Update total_build time computation

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#4250]
A recent PR (https://github.com/ESMCI/cime/pull/4217) added the total build time to the logs. However it appears to capture the the 'user' portion from the time command which may not account for system, kernel and some of the I/O overheads. 

We also need to check how the "target built in xx.xx seconds" is getting captured and update it to "real" (from time command) if needed.

In both these examples, we want the "real" elapsed time, especially the second example. 
Examples:
```
[e3sm]$ time sleep 5;

real    0m5.003s
user    0m0.000s
sys     0m0.002s
[e3sm]$ time find ~ -iname "sample.txt"

real    0m7.851s
user    0m0.105s
sys     0m0.873s
```

cc @jgfouca @rljacob @gaurabkcutk

Forgot to add: It would be nice to get this on maint-2.0 as well.

**Comment by sarats** [comment]
It would be better to change the name from Total_Build to Total_Elapsed_Time so that I can differentiate this from the old data in database.

**Comment by sarats** [comment]
Thinking out loud, we need to keep an eye out on total_compute_cost vs. total_elapsed time for builds to get a sense of how parallel builds are doing. Compared to previous version, the "real" (elapsed time) would be higher, so might reduce the difference with total_compute_cost further.

**Comment by jgfouca** [comment]
@sarats , you should be able to get this info now that you'll have the `real` time. Just take the sum of the individual targets and compare to `real`.

**Comment by sarats** [comment]
Yeah, we will do that once this gets into E3SM master and user experiments from different machines start reporting to PACE.

**Comment by jgfouca** [comment]
This has been fixed in CIME and pushed to E3SM (master and maint-2).
