### ISSUE TITLE
E3SM: NGPUS_PER_NODE calculation on GPU machines

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#4258]
Looking at comments for in https://github.com/ESMCI/cime/blob/d5f9983917a86d1b02cab2fb795d6eef82f31cf7/CIME/case/case.py#L1479

```
        #     3. For compilers with the string "gpu" in the name:
        #        3.1. if ngpus-per-node argument is smaller than 0, an error will be triggered.
        #        3.2. if ngpus_per_node argument is larger than the value of MAX_GPUS_PER_NODE, the NGPUS_PER_NODE
        #             XML variable in the env_mach_pes.xml file would be set to MAX_GPUS_PER_NODE automatically.
        #        3.3. if ngpus-per-node argument is equal to 0, it will be updated to 1 automatically.
```
I still get NGPUS_PER_NODE=0 on Summit for gnugpu for Scream.

cc @jgfouca

**Comment by jedwards4b** [comment]
Do you have MAX_GPUS_PER_NODE defined in the config_machines.xml for summit?  And you are using the --ngpus-per-node argument to create_newcase with a non-zero value and the resulting case xml has NGPUS_PER_NODE=0?

**Comment by sarats** [comment]
I have not seen any machine in E3SM with the attribute MAX_GPUS_PER_NODE defined
https://github.com/E3SM-Project/E3SM/blob/master/cime_config/machines/config_machines.xml

When I tried to add it, I run into schema validation error:
```
Pes     specification file is /gpfs/alpine/cli115/scratch/sarat/repos/E3SM/components/eam/cime_config/config_pes.xml
ERROR: Command: '/usr/bin/xmllint --xinclude --noout --schema /gpfs/alpine/cli115/scratch/sarat/repos/E3SM/cime/CIME/data/config/xml_schemas/config_machines.xsd /gpfs/alpine/cli115/scratch/sarat/repos/E3SM/cime_config/machines/config_machines.xml' failed with error '/gpfs/alpine/cli115/scratch/sarat/repos/E3SM/cime_config/machines/config_machines.xml:3437: element MAX_GPUS_PER_NODE: Schemas validity error : Element 'MAX_GPUS_PER_NODE': This element is not expected. Expected is one of ( MAX_MPITASKS_PER_NODE, COSTPES_PER_NODE, PROJECT_REQUIRED, mpirun ).
```

**Comment by jedwards4b** [comment]
This is a cesm option that has not yet been adopted by e3sm.

**Comment by sarats** [comment]
Ok, that explains. I presume we need to update our schema definition as well (config_machines.xsd)

**Comment by sarats** [comment]
I see that it's added in the CIME repo at https://github.com/ESMCI/cime/blob/6298fec9cde0bc0154f01624bfd0c4fb3480dac1/CIME/data/config/xml_schemas/config_machines.xsd#L57

So, we probably just wait for a CIME update on E3SM end once @jgfouca returns.

**Comment by rljacob** [comment]
We currently have cime6.0.24 from May 4th so that's in our version.  We just need to add it to our machine configs.

**Comment by sarats** [comment]
Hmm...looks like it needs that attribute specifically in the order specified in the schema. After I added next to MAX_TASKS_PER_NODE, ./create_newcase reports the following
```
$ ./create_newcase --compset F2010 --res ne4pg2_oQU480 --case nfe4-t1 --compiler gnugpu --queue batch-hm --walltime 00:30 --ngpus-per-node=6
...
ESP component is Stub external system processing (ESP) component
Pes     specification file is /gpfs/alpine/cli115/scratch/sarat/repos/E3SM/components/eam/cime_config/config_pes.xml
Machine is summit
ERROR: No variable MAX_GPUS_PER_NODE found in case
```

**Comment by sarats** [comment]
This is what the config_machines excerpt looks like after my addition for Summit
```
3429     <MAX_TASKS_PER_NODE>84</MAX_TASKS_PER_NODE>
3430     <MAX_TASKS_PER_NODE compiler="pgigpu">18</MAX_TASKS_PER_NODE>
3431     <MAX_TASKS_PER_NODE compiler="gnugpu">42</MAX_TASKS_PER_NODE>
3432     <MAX_TASKS_PER_NODE compiler="ibmgpu">42</MAX_TASKS_PER_NODE>
3433     <MAX_GPUS_PER_NODE>6</MAX_GPUS_PER_NODE>
3434     <MAX_MPITASKS_PER_NODE>84</MAX_MPITASKS_PER_NODE>
3435     <MAX_MPITASKS_PER_NODE compiler="pgigpu">18</MAX_MPITASKS_PER_NODE>
3436     <MAX_MPITASKS_PER_NODE compiler="gnugpu">42</MAX_MPITASKS_PER_NODE>
3437     <MAX_MPITASKS_PER_NODE compiler="ibmgpu">42</MAX_MPITASKS_PER_NODE>
```

**Comment by bartgol** [comment]
Not sure if it's related, but, just in case.

is it possible that CIME always assumes you use all gpus on each node? On Summit, asking for NTASKS=2 and MAX_MPITASKS_PER_NODE=MAX_TASKS_PER_NODE=1, i end up with jsrun requesting 12 resources, 6 per node, 1gpu per resource, while I'd like 2 resources total (1 gpu/res, 1 res/host). I don't see any xml parameter specifying the number of GPUs per TASK. Actually, `./xmlquery --listall | grep GPU` returns nothing.

I guess being able to set NGPUS_PER_NODE would fix it, but conceptually one would be more interested in setting NGPUS_PER_TASK, maybe.

Sorry if this is OT. I can open a question issue if more appropriate.

**Comment by jedwards4b** [comment]
Thank you @sjsprecious - I think that this is the step that was missed.  E3SM doesn't use cmeps, but they will need to define the MAX_GPUS_PER_NODE variable in the mct config_component.xml file.

**Comment by sarats** [comment]
@jedwards4b Just curious, how are you using this attribute? I see it reported by preview_run. Are you using to generate mpirun parameters etc. or ...?

@bartgol The NGPUS_PER_NODE  attribute is not used in generating jsrun parameters for Summit.

**Comment by jedwards4b** [comment]
Is the issue that summit uses the get_aprun_cmd_for_case from CIME.aprun?

**Comment by sarats** [comment]
No, Summit uses IBM's LSF (jsrun) and we (E3SM) use inline shell commands in config_machines.xml to figure out the right parameters to pass.
