### ISSUE TITLE
Describing machines with heterogeneous nodes

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#4274]
We are finding that CIME's methods for describing heterogeneous machines, machines where the nodes have cpus and gpus, could be simpler.

The base of the problem is the multiple way the machine can be used.   A typical use would be to run on both the cpus and gpus, but running on just the cpus is useful for testing.   Depending on what you're doing, different compilers will be needed and different batch system commands.

With current CIME, it's possible to make multiple machine entries but this can create a lot of duplication complicating maintenance.  Another way is to let the --compiler option make the decision which has less duplication but is also non-intuitive: the compiler options should just be concerned with the compiler and its flags.   Also we typically have multiple compilers that can address both gpu and cpu with different levels of completeness/performance and want access to all for testing.

One suggestion (from @ndkeen ) was a --hw option to create_newcase that would let the user pick what hardware they are using and which, along with --compiler and --machine, could completely describe the desired config.

Note:  this is a different problem than a host like cori that is a login for 2 different types of machines.  Each type is homogeneous and different machine entries work great (but still with some dupication).   Perlmutter is becoming a real mess since its one host with two different machines and one of them is heterogenous (cpu and gpu)

**Comment by jedwards4b** [comment]
@sjsprecious For your attention.

**Comment by sjsprecious** [comment]
Thanks @jedwards4b for pinning me. Currently we have the `--ngpus-per-node` option to `create_newcase`, which specifies the number of GPUs per compute node. In particular, `--ngpus-per-node 0` means using a pure CPU node. Is there a reason why we have to add another `--hw` option here?

**Comment by jedwards4b** [comment]
Good question - perhaps @ndkeen is not aware of this option?

**Comment by sarats** [comment]
Before we get distracted with a flag (--ngpus-per-node or another), how do you manage the disparate configurations required for CPU and GPU compiler/environment invocations w.r.t. machine specification? Do you create different machine entries or use different compiler labels (e.g., gnu vs. gnugpu).

**Comment by sarats** [comment]
Some context/motivation: how would CIME machine spec facilitate a CPU vs. GPU speedup study on a single machine containing both CPUs and GPUs. 

On Summit, we have used the different compiler labels to differentiate and run for the past few years. It feels a little unseemly to base a bunch of env and batch options based on compiler label. So, that precipitated this discussion to identify a consistent manner that works (rather than despite) with CIME.

**Comment by ndkeen** [comment]
There is no such thing as a compiler named `gnugpu` -- the compiler is `gnu`. So if there is some other information we want to specify, we should find an alternate way. My suggestion to have a new variable (say `--hw`) could be used to indicate `cpu` vs `gpu`. But there might be another way. Note that for a given machine, it has been clear the primary method to build/run -- eg for GPU-enabled machines, it would be rare to NOT use the GPU's.  Running in CPU-only mode is an odd edge case that might be used for testing/debugging (ie if case fails with GPU's on machine X, does it fail with only CPU's?) _or_ for directly comparing performance results to see the impact of using GPU's.

(of course, for all current machines, GPU-runs also means using the CPU's -- generally 1 CPU per GPU)

**Comment by rljacob** [comment]
Pointing to this for interest:  the PR that added ngpus-per-node   https://github.com/ESMCI/cime/pull/3989

**Comment by sarats** [comment]
>  Running in CPU-only mode is an odd edge case 
@ndkeen This is the exact scenario required for computational readiness studies for INCITE proposals etc. And, CIME should facilitate this case.

**Comment by rljacob** [comment]
Here's an example of what might work for everyo 
--machine perlmutter --hw cpu   (run on the cpu-only half of perlmutter)
--machine perlmutter --hw gpu --ngpus-per-node 0  (run on the cpus only of the cpu-gpu half of perlmutter)
--machine  perlmutter --hw gpu --ngpus-per-node 4   (run on the cpu and all 4 gpus of the cpu-gpu half of perlmutter)

"hw" also give us some future-proofing for when we have nodes with FPGAs on them.

**Comment by ndkeen** [comment]
Regarding Perlmutter, again this is not the same situation as other GPU machines.  Perlmutter is actually two different machines (and named `pm-cpu` and `pm-gpu`). Where `pm-cpu` is a large partition of nodes that ONLY contain CPU's (cannot run on GPU's).  Where `pm-gpu` has 4 GPU's per node -- it also has a CPU, but running CPU-only is _very_ wasteful and should be discouraged.

**Comment by jedwards4b** [comment]
In my opinion perlmutter is a situation in which having two separate machine definitions in cime makes sense.

**Comment by ndkeen** [comment]
Absolutely. Which is what I did.  But that's not what *I* am discussing here.  For `pm-gpu` and for other GPU machines, it does not seem like we should need a compiler named `gnugpu` to indicate we want to build/run on the GPUs.

**Comment by jedwards4b** [comment]
If you have two machine definitions then why do you need this separate compiler name?  Just call it gnu and it is understood that code compiled on the pm-gpu system is gpu compiled (or enabled if you prefer).

**Comment by ndkeen** [comment]
For `pm-cpu` that's true.  For `pm-gpu` (and other GPU machines) that's not true.

**Comment by jedwards4b** [comment]
@ndkeen that doesn't make sense.   Please explain why you need both compilers on either system.

**Comment by sarats** [comment]
Concrete examples of how we had to get some things working on Summit. 

Different batch options had to be specified for a GPU case and we had to base that on the compiler label.

https://github.com/E3SM-Project/E3SM/blob/master/cime_config/machines/config_batch.xml#L557
```
     <directives compiler=".*gpu">
       <directive>-alloc_flags "gpumps smt$SHELL{echo "(`./xmlquery --value MAX_TASKS_PER_NODE`+41)/42"|bc}"</directive>
     </directives>
```

Different mpirun equivalent options had to be specified for the GPU cases and we had to incorporate custom env-vars to make it work.

**Comment by ndkeen** [comment]
For machine `pm-gpu`, we currently have compiler `gnugpu` that is used to build/run on GPU's.  I think it should just be `gnu` and then some other mechanism to control how/where to build -- ie if compiler is `gnu` to run on GPU's, how then to build/run on only the cpu's of `pm-gpu` (if it were ever needed).

**Comment by jedwards4b** [comment]
Not a question for me but for @sjsprecious.   What I'm trying to get out of @ndkeen is why do we need to have a compiler on pm-gpu that does not enable gpus and if we do not need that compiler then just rename gnugpu and call it gnu.

**Comment by rljacob** [comment]
Its for that case where we need to run on just the cpus of the cpu-gpu nodes.  Yes its wasteful and we'd never do that in production but its needed for performance evaluation.

**Comment by jedwards4b** [comment]
In that case why not just say --ngpus-per-node 0

**Comment by rljacob** [comment]
We have not implemented ngpus in any of our machines yet but yeah I think that would be enough if you also have --machine pm-gpu

**Comment by sarats** [comment]
To be clear, does this mean we will have a single machine entry and use the ngpus flag to differentiate?
One drawback I see is that the ngpus-per-node argument need to be specified for each create_newcase invocation. 

Is there a way to enable the max. number of GPUs available on a machine by default? In that case, we can use it as a boolean value to force CPU only builds using --ngpus-per-node 0.

**Comment by jedwards4b** [comment]
We can set the default ngpus-per-node to be the maximum on the system.

**Comment by sarats** [comment]
Another suggestion, rather than having conditional blocks (ngpus-per-node > 0) interspersed in various XML files (env_batch,config_machines etc.), it might be better to define an internal boolean flag(e.g., HAVE_GPU) so that GPU specific flags/mpi-args/env vars/batch options can be encapsulated.

**Comment by jedwards4b** [comment]
It seems like even with the boolean HAVE_GPU flag you will need another flag to control how many gpus you use.

**Comment by sarats** [comment]
True, but it's good to separate out the build vs. run phase requirements. A bulk of the issue on our end is managing the build configuration for GPUs which the boolean value solves succinctly.

The only place we might use ngpus information in the future is to construct our mpirun equivalent invocations.
Right now, we do that through custom logic and env-vars for our jsrun arguments for the large supercomputers to deal with various binding, affinity flags, GPU aware etc.

**Comment by sjsprecious** [comment]
> @jedwards4b I have the same question for you. Looking at the Casper set up in https://github.com/ESMCI/ccs_config_cesm/tree/main/machines, why do you need`pgi`and `pgi-gpu` ? doesn't ngpus > 0 help you pick?

The usage of `pgi` and `pgi-gpu` here is probably due to a limited knowledge of CIME from me. I thought that I had to generate the separate `Depends.pgi` and `Depends.pgi-gpu` files in order to apply the GPU flags to my targeted codes (using `pgi-gpu`) without affecting the original way of running the same codes on CPU (using `pgi`). If the `ngpus_per_node` option could be recognized in the `Depends.pgi`, then I think it should be able to pick up the GPU flags when necessary and there is no need to keep `pgi` and `pgi-gpu` at the same time (@jedwards4b correct me if I am wrong). Note that I only want to apply the GPU flags to some specific GPU-enabled CAM codes so I do not want to add `-acc` to something like `FFLAGS` or `CFLAGS` by default.

**Comment by sarats** [comment]
Btw, looking at https://github.com/ESMCI/cime/pull/3989/files#diff-d3c4653cc30f04107b5d316e2f80539ca2caff1a319afb3cc250e640dc69f383, why is `NGPUS_PER_NODE` specified in config_component.xml in addition to config_machines.xml/xsd?

**Comment by jedwards4b** [comment]
config_component.xml defines the variables, config_machines.xml sets the default value for each machine.

**Comment by jedwards4b** [comment]
This is still a work in progress.
