### ISSUE TITLE
create_clone not working when cloning for another user

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4280]
When cloning a case from a different user, the new case fails to build with an error in buildlib.mct.
The error message in mct.bldlog is

`gmake: *** No rule to make target '/glade/scratch/fischer/X.clone/bld/intel/mpt/nodebug/nothreads/nuopc/mct/Makefile.conf'.  Stop.
`

To repeat this error.

`./create_clone --clone /glade/scratch/jedwards/SMS_Ln9.f19_g17.X.cheyenne_intel.20220708_114246_qbf4tc --case /glade/scratch/fischer/X.clone --cime-output-root /glade/scratch/fischer`

Then run ./case.build.

**Comment by ekluzek** [comment]
I tried this with the latest CTSM ctsm5.1.dev122 and it seems to work now so closing.

```
 ./create_clone --clone /glade/scratch/jedwards/SMS.f19_g17.X.cheyenne_intel.20230428_084845_4qiufa --case /glade/scratch/$USER/X2.clone --cime-output-root /glade/scratch/$USER
cd /glade/scratch/$USER/X2.clone
./case.build
```
