### ISSUE TITLE
Allow multiple testmods

### ISSUE THREAD

**Issue by bartgol** [ESMCI/cime#4293]
It would be nice if CIME allowed multiple testmods, like

```
create_test SMS.$grid.$compset.$mach_$comp.$testmod1.$testmod2...
```
Since testmods are all at the end, it seems to me that CIME could allow an arbitrary number of them, processed in the same order that they appear.

This would allow one to, say, create only 2 testmods folders, and be able to create 4 possible test configurations. It could allow, say, to isolate specific parametrizations/components testmods in their exclusive folder, and allow the user to combine them:
```
create_test [...].eam-rrtmgp-no_option1.eam-clubb-yes_option_2
```
rather than create all possible combination of testmods. It would be linear in the number of (conceptually independent) testmods, rather than exponential.

**Comment by jgfouca** [comment]
@jedwards4b , if you agree with this request, I think this would be a good one for JasonB to take on.

**Comment by jedwards4b** [comment]
@jgfouca I think that this is already possible.  If you look at https://github.com/ESMCI/cime/blob/master/CIME/utils.py#L997 I believe that unit test is using that capability.

**Comment by jedwards4b** [comment]
It's actually the line above that one: https://github.com/ESMCI/cime/blob/master/CIME/utils.py#L996

**Comment by bartgol** [comment]
SWEET! I tried `$testmod1.$testmod2` and `$testmod1_$testmod2`, but did not test the double dash.

Thanks!

**Comment by jgfouca** [comment]
@jedwards4b , thanks, I was not aware of that syntax.

**Comment by bartgol** [comment]
You guys are very fast at solving issues! :)
