### ISSUE TITLE
CIME calls cprnc in a non-symmetric way

### ISSUE THREAD

**Issue by bartgol** [ESMCI/cime#4303]
I changed the output precision of a test from double to float. I was expecting baseline tests to fail, but our tests still passed.

Intrigued, I manually ran cprnc and indeed it reported 0 diffs. However, flipping the files order did show the difference. I'm guessing cprnc chooses the precision from the 1st file (which, for me, was float), so even if the second file has higher precision, it does not see that.

Is this desired? Should CIME do a symmetric test instead? Or is this too much of a corner case to be worth cime mods?

**Comment by jedwards4b** [comment]
I can reproduce this issue.   I think that it should do a symmetric test.

**Comment by bartgol** [comment]
It would be enough to grab the field with the highest precision. Or maybe check that the two have the same precision, and return a diff if they don't (the likelihood of a `double` field to store the same values as a `float` field is probably very tiny anyways).

**Comment by jedwards4b** [comment]
Here is my proposed solution
If the lower resolution data type is in the first file:
```
SUMMARY of cprnc:
 A total number of    427 fields were compared
          of which      0 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
               and      1 had different data types
 A total number of      0 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT 
```
If it is in the second file:
```
SUMMARY of cprnc:
 A total number of    427 fields were compared
          of which      1 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
               and      1 had different data types
 A total number of      0 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT 
```
In either case additional information is available in cprnc output:
```
 WARNING: Variable Med_alb_ocn_So_avsdf types differ
 TYPEDIFF Med_alb_ocn_So_avsdf                       6           5
```
@bartgol will this meet your needs?

**Comment by bartgol** [comment]
Yes, I think it's great. Thanks!
