### ISSUE TITLE
case.build --clean-build will remove the CASEDIR contents if EXEDIR points to the CASEDIR

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4313]
I'm reporting this from @dmleung. He setup some cases where EXEDIR was set to be the same as CASEDIR (so NOT a bld subdirectory of the CASEDIR).  If he then runs "./case.build --clean-build" it then erases the contents of the CASEDIR. Outside of that it actually functions fine, but if you clean your build it will cause problems. Note, that he did this with older cime versions and it seemed to work OK, but with cime6.0.45 it will remove the case directory contents.

The important thing to note is that this is something you should NOT do! So we can either close this as a WONTFIX as a degenerate case that you shouldn't do. Or a simple thing to do would be to add a simple check that EXEDIR should not be the same as CASEDIR, or there should be an error reported.

**Comment by jedwards4b** [comment]
The feature you mean is ```./case.build --clean-all``` and yes it will delete the EXEDIR.   It's been there a long time, since sometime early in cime5 I think.
