### ISSUE TITLE
Rename a case

### ISSUE THREAD

**Issue by changliao1025** [ESMCI/cime#4323]
Can we have a function (e.g., rename_case) that renames an existing case to a different name? 
There are scenarios we want to preserve the case but use the case name/directory for a new case.
This would be a new feature request.

**Comment by jedwards4b** [comment]
Can you please spell out in detail the scenario that you would like to support?

**Comment by changliao1025** [comment]
An example is when I had already finished a list of cases (simulation + analysis) and found out one of the cases had issues. Usually, I would delete this "troubled" case and rerun it which will overwrite all the files. But sometimes I want to keep a record of this case. Without changing many post-processing codes for this multi-case analysis, renaming this case to a different name/directory seems to be a good solution for me.

**Comment by jedwards4b** [comment]
Why not just create a tar file (or a version control repo) of the original then creating a new case with the same name? 
Changing the case name would be complicated and error prone to implement.
