### ISSUE TITLE
make nuopc the default for cesm testing 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4351]
Although nuopc is the default COMP_INTERFACE for cesm it is 
still not the default for testing.  Making nuopc the default means that components will need to add
an explicit _Vmct to tests that they want to continue using mct.

**Comment by billsacks** [comment]
Are you sure about this? Our aux_clm tests that don't specify `_Vmct` are running with the nuopc comp interface. I don't *think* we do anything special to get this behavior, though I could be missing something.

**Comment by ekluzek** [comment]
@jedwards4b yes I'm not sure what you are suggesting here. In CTSM as @billsacks points out we do have some tests with an explicit _Vmct, but since we are phasing MCT out, with the first thing being removing it from testing is that we'll be removing those explicit _Vmct tests. The same with other components as well.

**Comment by fischer-ncar** [comment]
I think this is an issue that the cmeps testlist file isn't being seen by cime.

**Comment by jedwards4b** [comment]
There were two issues - one is that the cmeps testlist wasn't being seen, I tried to correct that by explicitly changing the driver for testing to nuopc and as a result I ran a bunch of tests using the nuopc driver that should have been mct tests, due to disk quota issues I've removed these tests, but it could have been due to components other than ctsm.

**Comment by mvertens** [comment]
@jedwards4b - isn't nuopc already the default?

**Comment by jedwards4b** [comment]
Yes it is - closing this old issue.
