### ISSUE TITLE
creat_newcase srcroot parser typo?

### ISSUE THREAD

**Issue by rgknox** [ESMCI/cime#4353]
Sorry if this is duplicate or my error, but the parser add_argument call for the srcroot in create_newcase looked different from the other calls:

https://github.com/ESMCI/cime/blob/master/CIME/scripts/create_newcase.py#L179

Is this right?:

```
parser.add_argument(
        "--srcroot",
        default=srcroot_default,
        help="Alternative pathname for source root directory. "
        "\nThe default is {srcroot_default}",
    )
```

**Comment by jedwards4b** [comment]
No, the code on master is correct - if you are getting an error it's probably because your python version is too old.
