### ISSUE TITLE
E3SM replay.sh functionality: Missing quotes for xmlchange invocations

### ISSUE THREAD

**Issue by sarats** [ESMCI/cime#4361]
I noticed that replay.sh does not capture quotes around arguments for xmlchange invocations.

For instance,
although the case was created and modified using
```./xmlchange --append --id CAM_CONFIG_OPTS --val  " -nlev 276 "```
replay.sh has
```./xmlchange --append --id CAM_CONFIG_OPTS --val  -nlev 276```

It causes the following problem when you try running replay.sh:
```
$ ./xmlchange --append --id CAM_CONFIG_OPTS --val  -nlev 276
WARNING: The -nlev argument is deprecated. Multi-character arguments should begin with "--" and single character with "-"
  Use --help for a complete list of available options
usage: xmlchange [-h] [-d] [-v] [-s] [--caseroot CASEROOT] [--append] [--subgroup SUBGROUP] [--id ID] [--val VAL] [--file FILE] [--delimiter DELIMITER] [--dryrun] [--noecho] [-f] [-N] [-loglevel LOGLEVEL] [listofsettings]
xmlchange: error: argument --val/-val: expected one argument
$ ./xmlchange --append --id CAM_CONFIG_OPTS --val " -nlev 276 "
For your changes to take effect, run:
./case.build --clean-all
./case.build
```

**Comment by sarats** [comment]
cc @jasonb5

**Comment by oksanaguba** [comment]
i thought it was only scream behavior, apparently not https://github.com/E3SM-Project/scream/issues/1856

**Comment by jasonb5** [comment]
@sarats I'm looking into this.

@oksanaguba That definitely looks related to this.
