### ISSUE TITLE
Don't have to build clean after changing pe's

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#4364]
I still see this message when changing the pelayout:
```
[jacob@chrlogin1 Wne4rivfil]$ ./xmlchange ROOTPE_CPL=0
For your changes to take effect, run:
./case.setup --reset
./case.build --clean-all
./case.build
```
You actually don't have to do a "--clean-all" for E3SM and I think CESM only needs to clean POP.  Can we make those instructions reflect that?   The reason is that a full rebuild is 30-50 minutes depending on platform so we should not force one unless really necessary.

**Comment by jedwards4b** [comment]
CESM needs to clean POP and possibly CICE depending on version.  This message is simple and safe, I think that trying to be more precise about what is cleaned will lead to confusion and errors by the naive user.   Experienced users know what they need to do.

**Comment by rljacob** [comment]
What if we changed it to:
```
For your changes to take effect, run:
./case.setup --reset
(if using POP or CICE:  ./case.build --clean-all)
./case.build
```

**Comment by jedwards4b** [comment]
I prefer to leave the message as is - also POP and CICE (cice5 is what this is for) are deprecated and won't be in the next cesm release.   What is wrong with erring on the side of caution and letting experienced users ignore this advice?

**Comment by rljacob** [comment]
I don't think even experienced users know you can skip that step if the model doesn't have any compile-time dependencies on the number of tasks.   I'd just like to communicate that in some way.

**Comment by jedwards4b** [comment]
Perhaps you should just skip the warning for e3sm if you like.

**Comment by rljacob** [comment]
Yes but I'm really hesitant to put more "if model" clauses in the CCS.   I'll just try other channels to spread awareness.
