### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by changliao1025** [ESMCI/cime#4367]
Does CIME provide a debug mode? I can only run most scripts in the command line, but I want to run them inside an IDE such as VS Code. An example of doing so?

**Comment by changliao1025** [comment]
The closest I can find is using the launch json file to set the arguments inside a debug section. https://code.visualstudio.com/docs/python/debugging

**Comment by jedwards4b** [comment]
All of the cime python code supports a --debug option.

**Comment by jedwards4b** [comment]
Closing issue as answered.
