### ISSUE TITLE
create_clone and MOM INPUT 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4371]
we need to make sure that create_clone is working with MOM.  I just found that the
INPUT directory created by MOM in the run directory is not reproduced in the cloned case, I'm really not sure that cime is the appropriate place for this issue.
@alperaltuntas

**Comment by gustavo-marques** [comment]
You were cloning a case that has been manually modified because we are still testing the new MOM6 grid. I had to create the INPUT dir in the RUNDIR because I was using files that are not in `cseg/inputdata`.

**Comment by jedwards4b** [comment]
@gustavo-marques thank you for the explanation, closing this issue.
