### ISSUE TITLE
Failure in XML phase of system test for system tests defined in land component

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4373]
Recent versions of CIME give failures in the XML phase of system tests for tests defined in the land component, with this message:

```
Finished XML for test LII_D_Ld1_P8x1.f10_f10_mg37.I2000Clm50BgcCropQianRs.green_gnu.clm-default in 0.043439 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /Users/sacks/projects/scratch/LII_D_Ld1_P8x1.f10_f10_mg37.I2000Clm50BgcCropQianRs.green_gnu.clm-default.20230316_142236_rqvwwt
    Errors were:
        Test 'LII_D_Ld1_P8x1.f10_f10_mg37.I2000Clm50BgcCropQianRs.green_gnu.clm-default' failed in phase 'XML' with exception 'ERROR: Multiple matches for name 'test' and attribs '{'NAME': 'LII'}' in file /Users/sacks/ctsm/ctsm0/cime/CIME/data/config/config_tests.xml'
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/test_scheduler.py", line 1093, in _run_catch_exceptions
            return run(test)
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/test_scheduler.py", line 851, in _xml_phase
            testnode = config_test.get_test_node(test_case)
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/XML/tests.py", line 32, in get_test_node
            node = self.get_child("test", {"NAME": testname})
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/XML/generic_xml.py", line 376, in get_child
            child = self.get_optional_child(
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/XML/generic_xml.py", line 399, in get_optional_child
            expect(
          File "/Users/sacks/ctsm/ctsm0/cime/CIME/utils.py", line 166, in expect
            raise exc_type(msg)
```

The problem came in with cime6.0.71, when @ekluzek added the SLIM component in config_files.xml. The problem is due to a duplication in the LND entry in this part of config_files.xml:

```xml
  <entry id="CONFIG_TESTS_FILE">
    <type>char</type>
    <values>
      <value>$CIMEROOT/CIME/data/config/config_tests.xml</value>
      <!-- component specific config_tests files -->
      <value component="clm">$COMP_ROOT_DIR_LND/cime_config/config_tests.xml</value>
      <value component="slim">$COMP_ROOT_DIR_LND/cime_config/config_tests.xml</value>
      <value component="cam">$COMP_ROOT_DIR_ATM/cime_config/config_tests.xml</value>
      <value component="cism">$COMP_ROOT_DIR_GLC/cime_config/config_tests.xml</value>
      <value component="mom">$COMP_ROOT_DIR_OCN/cime_config/config_tests.xml</value>
    </values>
    <group>test</group>
    <file>env_test.xml</file>
    <desc>file containing system test descriptions </desc>
  </entry>
```

I think I can fix this issue by changing tests.py to avoid re-reading any file that has already been read. I'll try that fix and submit a PR if it fixes the issue. However, there's a part of me that feels like there should perhaps be a more general solution here that would apply to all config_files entries, since it seems like similar problems could arise elsewhere when we define multiple lnd components, multiple ocn components, etc. For example:
- Should the Files object only loop through the components actually present in the given case? (Though I realize that won't always work since sometimes you need to use the config_tests entries before you know what components are present – such as in interpreting a compset alias.)
- Or should we institute a convention where these files all have the specific component name attached to them? (But I realize that requires painful coordination across all components.)
- Or is there some other way to rework this? It feels like there should be, but I haven't thought about it enough for a good solution to come to mind.

For now I plan to fix this the easy way so I can move things along, but I'm open to other suggestions.

**Comment by jedwards4b** [comment]
I'm not sure that I see the problem here, both clm and slim point to the same config_tests.xml file - are you saying that one is appended to the other and that leads to a duplicate test?  In that case wouldn't the solution be to check to see if file a and b are the same file and avoid appending in that situation?

**Comment by billsacks** [comment]
Yes, that's exactly the problem and the solution. I have tested it and it works... will submit a PR later.

**Comment by ekluzek** [comment]
@billsacks I'm glad you have a solution here. I'm not quite sure why I didn't see this issue in my testing in SLIM. It seems like I should have seen the same issue for SLIM. I'm not sure if that means I didn't do enough testing  or the right testing. This same form shows up for other config files, I'm not sure what's different about the config_tests file that makes this a problem but it isn't for the other files?

I would also be fine with the solution to make the "new" component (i.e. SLIM in this case) have to include it's name in the config_tests filename. In this case you wouldn't need to change ALL components, just anytime you add a second optional component type. I think it also ONLY applies when you allow the second optional component to have it's own checkout like SLIM and CTSM do.  When you have a CESM checkout the files are nicely separated under clm and slim subdirectories beneath components.

**Comment by ekluzek** [comment]
It looks like what I did for testing for this PR was to run a SLIM test case. I think I probably needed to run the SLIM test list to see this problem?

**Comment by ekluzek** [comment]
Ahhh, I think the reason I didn't see this in SLIM is that currently SLIM doesn't have a config_tests.xml file. It's added to cime in case such a file is added in the future. Since, CLM does have a config_test file, it causes a problem in CLM, but not SLIM. So I needed to do more testing with CLM for this even though the changes were to just add new files for SLIM, so it didn't look like a lot of testing with CLM was needed.

**Comment by jedwards4b** [comment]
Thanks @billsacks
