### ISSUE TITLE
create_test --srcroot problem

### ISSUE THREAD

**Issue by proteanplanet** [ESMCI/cime#4393]
I have encountered an issue with the create_test script while running PEM and PET tests:

1) The following worked for these tests:
${CODE_ROOT}/cime/scripts/create_test  --output-root "${CASE_ROOT}"  --machine "${MACHINE}" --project "${PROJECT}" --wait "e3sm_ice_developer"

2) This did not work:
${CODE_ROOT}/cime/scripts/create_test  --output-root "${CASE_ROOT}"  --srcroot "${CODE_ROOT}" --machine "${MACHINE}" --project "${PROJECT}" --wait "e3sm_ice_developer"

Am I using --srcroot incorrectly?

Both of the above examples worked for ERS and SMS tests, but not PEM and PET tests, for which only the first example worked.  The tests failed to build.

**Comment by rljacob** [comment]
What was the error message at the end of the failed test?

**Comment by proteanplanet** [comment]
@rljacob, @jasonb5: If you would like to look over an example of the failure on Anvil, see /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/Test.ice.newjontest.master.E3SM-Project.anvil

**Comment by jasonb5** [comment]
@proteanplanet Thanks for the example, I'll take a look and have an update soon.
