### ISSUE TITLE
CIME behavior should not depend on login shell.

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#440]
We have a couple of cases where tcsh/csh users could not get CIME to function correctly.  This was very puzzling for developers using bash who never saw a problem.   That shouldn't happen but appears to be related to module environment issues before CIME starts.

Example 1:  the attempt to use "module list" to write out the module environment didn't work with tcsh/csh.   https://github.com/ESMCI/cime/pull/339#issuecomment-238350291

Example 2:   User had to add a .bashrc file with correct python module even though he is a tcsh/csh user:  https://github.com/ESMCI/cime/pull/410#issuecomment-241076350

**Comment by jedwards4b** [comment]
I think that it just indicates that we need to test in a tcsh environment.  How frequently?  Who?  Where?

**Comment by jgfouca** [comment]
I agree with @jedwards4b . I will assign myself and set up a tcsh test on melvin or some other machine.
