### ISSUE TITLE
CIME does not always download all the necessary input files for test cases that modify case2

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#4400]
We are seeing that some test cases will sometimes need different input files for their case2 (ERP, PEM). These files don't appear to be automatically downloaded by CIME which can lead to failures.

**Comment by jgfouca** [comment]
@jonbob , does this summarize the issue correctly?

**Comment by jedwards4b** [comment]
I wonder if the issue is due to case2 being submitted from a (compute) node that doesn't have internet access?   One way to solve this might be to explicitly call check_inputdata --download from the ERP and PEM tests in the case2 directory.

**Comment by jonbob** [comment]
That might do it -- it's only the mpas graph (decomposition) files that are different and get missed. And thanks @jgfouca, I think that covers it. The graph files should be listed in the mpas input_data_list's, so hopefully it's as simple as calling check_download from case2

**Comment by jonbob** [comment]
This issue is still important to E3SM
