### ISSUE TITLE
Documentation needs to be rebuilt

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4431]
I noticed that the documentation – specifically https://esmci.github.io/cime/versions/master/html/users_guide/unit_testing.html#building-pfunit – is not up-to-date with some changes I made recently. Is this supposed to be rebuilt automatically now? If not, are the instructions in https://github.com/ESMCI/cime/wiki/Working-with-Sphinx-and-reStructuredText still correct?

**Comment by jedwards4b** [comment]
https://github.com/ESMCI/cime/blob/master/.github/workflows/docs.yml  Should automatically rebuild the docs.
I also notice that some documentation I recently changed has not been updated.  
I am going to put up a PR that only does a documentation change and see what happens. 
@jasonb5 Could you have a look?

**Comment by jasonb5** [comment]
The documentation is only auto deployed if the PR is made from the ESMCI repo, this is due to GitHub security practices preventing the `GITHUB_TOKEN` from being passed to workflows triggered by PR's from forked repos.

I wasn't aware of https://github.com/ESMCI/cime/wiki/Working-with-Sphinx-and-reStructuredText and can update it.

**Comment by billsacks** [comment]
Is it possible to tie a workflow to a merge to master instead of to a PR? If so, would that solve this issue – because, presumably, by the time something is merged to master, it wouldn't matter whether it came from a fork or the main repo?

**Comment by jedwards4b** [comment]
https://github.com/ESMCI/cime/blob/master/.github/workflows/docs.yml#LL3C1-L6C13  I think that @jasonb5 thought that this code would do that, but it apparently isn't working either.

**Comment by jedwards4b** [comment]
What if instead of tying the doc build to a repository event we just do a cron on master and build the documentation each night?

**Comment by rljacob** [comment]
How do we test if our documentation mods will break the documentation build?  We have to push the branch to ESMCI?

**Comment by jasonb5** [comment]
> Is it possible to tie a workflow to a merge to master instead of to a PR? If so, would that solve this issue – because, presumably, by the time something is merged to master, it wouldn't matter whether it came from a fork or the main repo?

@billsacks If you pushed straight to master the workflow should trigger from this https://github.com/ESMCI/cime/blob/master/.github/workflows/docs.yml#LL3C1-L6C13. If somebody has pushed straight to master and the workflow didn't trigger, let me know.

@jedwards4b I can split this up and do just a doc build for a PR and the actual deploy in a cron job.

@rljacob The first check should be developers locally, we can still do a check in the PR.

**Comment by rljacob** [comment]
Build it locally?  I had the toolchain for that once but it broke and some point and I never fixed it.

**Comment by jasonb5** [comment]
In the CIME repo the following will work.
```bash
python -m venv docs-venv
source docs-venv/bin/activate
pip install -r doc/requirements.txt
make -C doc html
open doc/build/html/index.html
```
