### ISSUE TITLE
Appending Arguments to `BATCH_COMMAND_FLAGS` Overwrites Existing PBS Batch Arguments in CESM Scripts

### ISSUE THREAD

**Issue by negin513** [ESMCI/cime#4439]
Hello, 
I would like to add a new PBS argument to my CESM job submission scripts. However, when I use `./xmlchange` to add a new argument to `BATCH_COMMAND_FLAGS`, it seems to ignore the other PBS batch arguments, rather than appending the new one to them.

Here's an example of what I'm experiencing to replicate this:
```
./create_newcase --case ~/cases/b.day1.0 --res f19_g17 --compset B1850
qcmd -- ./case.build
```
Running `./preview_run` then shows the following submission command:

```
qsub -q regular -l walltime=12:00:00 -A SCSG0002 -v ARGS_FOR_SCRIPT='--resubmit --silent' .case.run
```
-------
However, when I use `./xmlchange` to add a new `BATCH_COMMAND_FLAGS`:
```
./xmlchange --subgroup=case.run BATCH_COMMAND_FLAGS="-l place=group=rack"
```
The `./preview_run` shows:

```
qsub -l place=group=rack -v ARGS_FOR_SCRIPT='--resubmit' .case.run
```

As a result, the previous flags `-q regular -l walltime=12:00:00 -A SCSG0002` are removed, causing PBS to fail when submitting the job.

I understand that it's possible to manually include all necessary PBS arguments in `BATCH_COMMAND_FLAGS`. However, this approach doesn't seem to be the most efficient or intuitive. By default, the `BATCH_COMMAND_FLAGS` is empty and CIME automatically finds the necessary PBS information (i.e. job queue, walltime, project code). 

**More importantly, it seems that once `BATCH_COMMAND_FLAGS` is modified, CIME no longer pulls queue, project values, or walltime from the case information, which can potentially lead to confusion and errors.**

Is there a different way to append a new PBS argument to the CIME job scripts? 
If not, it could be helpful to the user community to add this functionality and address the issue with `BATCH_COMMAND_FLAGS`.

**Comment by jedwards4b** [comment]
@jasonb5 @jgfouca  - Would it be better if BATCH_COMMAND_FLAGS append rather than replace existing flags?  Perhaps we should populate BATCH_COMMAND_FLAGS with the default set of flags and always use it instead of having it be an empty string?

**Comment by jgfouca** [comment]
@jedwards4b , I like the idea of populating it with whatever CIME computes for the batch command. This would allow the user to `./xmlchange --append XXX` if that's what they want.
