### ISSUE TITLE
Lengthen time for stale-bot to 3-months and don't trigger it if "Low Priority" label is set

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4441]
The stale-bot is great at keeping stale issues under control, but I'd like to tweak it just a bit. First to increase the time when it triggers from a single month to 3 months. And second to have it NOT be triggered if the "Low Priority" label is set for an issue. The number of "Low Priority" issues is only 18 right now which is reasonable to look through. Those could be examined on a more manual basis on something like a yearly basis. For most issues I'd like to be reminded about it on a lower frequency and think that a few months would be about right for me, with monthly being a little too fast.

**Comment by ekluzek** [comment]
This means adding exempt-issue-labels: Low Priority, and increasing the time in days-before-stale.

**Comment by billsacks** [comment]
I agree. See also discussion in https://github.com/ESMCI/cime/issues/4404 . I could see increasing the time to even longer, like a year: our pace of development is not that fast currently.

**Comment by jedwards4b** [comment]
I totally disagree with change it to a year.   This action has really helped us to adjust our priorities and clean up issues - changing to a year might as well be turning it off.

**Comment by billsacks** [comment]
My rationale is: My sense is that most of the issues that were (helpfully) auto-closed had been stale for at least a year, and often significantly more.

**Comment by billsacks** [comment]
Can we get Erik's suggestion or something similar put in place? I'd still personally like something like a year now that we're done with the initial stage of cleaning, but Erik's original suggestion would be fine if others don't want to extend the auto-close time that long. I'm getting a bit overwhelmed by the frequent emails reminding me that, nope, we still haven't acted on these issues.

**Comment by billsacks** [comment]
(I'm letting some issues auto-close simply because I'm not up for repeatedly removing the stale label, even though I still feel the issues are worth doing.)
