### ISSUE TITLE
Write NOC test using SystemTestsCompareTwo infrastructure

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#445]
We want to convert the various system tests that compare two runs to use the SystemTestsCompareTwo infrastructure, where possible. I am opening separate issues for each such system test, so that we can check them off as we do this conversion.

Currently it looks like the NOC test is essentially just an SMS test - it looks like a place-holder waiting to be filled in.

**Comment by mfdeakin-sandia** [comment]
A few questions about what the NOC test is supposed to do.
NINST needs to be set for the ocean component, but what it's supposed to be set to isn't specified. Is there a place I can find what it's supposed to be set to? Or will CIME supply a suitable default value?
The NOC description mentions that mod needs to be set, but doesn't give any information about what mod is. Where could I find this?

**Comment by jedwards4b** [comment]
See the old csh code for example here https://github.com/ESMCI/cime/blob/cime4.5.22/scripts/Testing/Testcases/
look at both NOC_build.csh and NOC_script

**Comment by jedwards4b** [comment]
To summarize this test does two runs with NINST 2, with two user_nl files (call them a and b) - in the first run instance 1 useses file a and instance 2 uses file b.  In the second run instance 2 uses file a and instance 1 uses file b.   The results are compared run 1 instance 1 should match run 2 instance 2 and run 1 instance 2 should match run 2 instance 1.

**Comment by mfdeakin-sandia** [comment]
Alright, thanks. So how will I determine what namelists to use, and how do I tell it to perform the run with these namelists? The NOC script uses some predefined namelists, user_nl_cice_000%d.base, and user_nl_cice_000%d.mod.
Also, if I understand the description of the test correctly, it sounds like it might make more sense to consider running with the different namelists as two separate tests.

**Comment by jedwards4b** [comment]
No, the test is to make sure that each instance of a mutli-instance test is creating and reading its own namelist.

**Comment by mfdeakin-sandia** [comment]
Sorry for the pause on this.
I think I understand this better than before, and see that it should be similar to NCK, but am not certain how to generate the two different sets of namelists. Do I need to do that myself in a different location than the NOC class?
It also looks like I need to do more than simply write the NOC test class and add the config_tests options, as that crashes. What else needs to be done?

**Comment by billsacks** [comment]
Who made the decision to can the NOC test? Our testing of multi-instance is pretty feeble; NOC was a step in the right direction, by making sure that the two instances are really doing something different.

I am therefore reopening this issue. If some decision has been made to delete this test, please document it here.

**Comment by mfdeakin-sandia** [comment]
On Slack on Nov 15:

jedwards	[2:37 PM]  
@mdeakin I have a silly question about this test?  Is it one we really want in such a specific form?  I mean you guys dont even use cice?

jgfouca	[2:38 PM]  
no, we don't

mdeakin	[2:38 PM]  
I don't know, I was just assigned to implement it

jgfouca	[2:38 PM]  
it's possible we don't even need a NOC test

[2:38]  
i was just thinking that too

[2:39]  
if you guys (CESG) don't need it, we certainly do not

jedwards	[2:40 PM]  
I don't think we do at least not now

jgfouca	[2:41 PM]  
alright, @mdeakin your PR for completing that task should just remove NOC entirely

**Comment by jedwards4b** [comment]
How do we formulate this test in a way that will work for any compset for which multi-instance capability is required.   I feel that this should be on cseg to figure out since multi-instance isn't a capability that acme uses.

**Comment by ekluzek** [comment]
It seems to me you need a test-mods directory that is specific to the compset. I think that directory could have an includes to a component level test-mods directory that would have the specific changes that that component wants to exercise for each instance. One of the main points is to make sure the two instances are doing something that changes answers between the two instances. The NOC test itself would have to figure out how to reverse the user_nl_* instances.

**Comment by billsacks** [comment]
I agree with @ekluzek . We may need component-specific versions of this test. Maybe they can inherit from some NOC_base, or maybe they can all use some common routines.

**Comment by billsacks** [comment]
@mfdeakin-sandia @jedwards4b @jgfouca : Regarding our process: Can we please try to make it a policy to summarize any important slack discussions on the relevant github issue so that others who are interested can comment? I and some others in CSEG find slack much too chatty to be able to feasibly follow all of the discussions there, but I'd like to be notified of discussions relevant to my issues before (say) the issue is closed as a wontfix.

**Comment by rljacob** [comment]
Yes that should be the practice because Slack is not archived or public.  Github issues have both.

**Comment by mfdeakin-sandia** [comment]
Alright, sorry, I should have done so and will next time.

**Comment by jedwards4b** [comment]
My fault

**Comment by jgfouca** [comment]
I agree with @jedwards4b , it was all his fault! :)

**Comment by rljacob** [comment]
From telecon:  Do we still need to revive this test?

**Comment by billsacks** [comment]
I doubt @gold2718 will have time to work on this any time soon, so we're reassigning to @fischer-ncar

**Comment by billsacks** [comment]
Feeling from the CESM side is that this should be closed as a wontfix: it doesn't feel high priority for us now. I'm tentatively closing it. @rljacob @jgfouca or others, feel free to reopen if it's important for you.

**Comment by jgfouca** [comment]
@billsacks , E3SM does not use NOC tests, so I'm find with closing.
