### ISSUE TITLE
query_config --grids doesn't show new MOM grid unless --comp_interface nuopc is specified

### ISSUE THREAD

**Issue by klindsay28** [ESMCI/cime#4456]
When I run `query_config --grids` with cesm2_3_beta15, there is no mention of the recently added MOM grid `tx2_3v2`.
It shows up if I add the argument `--comp_interface nuopc` to the command line invocation.
It looks like this is because the default for `--comp_interface` is `mct`:https://github.com/ESMCI/cime/blob/bc19d7150c9b87384de578d3ef67f0b9e0b627b0/CIME/scripts/query_config.py#L315-L320
For CESM, this default differs from the default for `--driver` in `create_newcase`,
so CESM users see output from `query_config` that doesn't match `create_newcase` (by default).
Would it make sense to make the default for `--comp_interface` in `query_config` be `get_cime_default_driver()`,
as is done in `create_newcase`? https://github.com/ESMCI/cime/blob/bc19d7150c9b87384de578d3ef67f0b9e0b627b0/CIME/scripts/create_newcase.py#L240-L245

(Is there a reason for this option to be named `--driver` in `create_newcase` and `--comp_interface` in `query_config`? I find it confusing, but perhaps there is a distinction that I'm not aware of.)

**Comment by ekluzek** [comment]
I have the same problem with the mizuRoute grids, that I've been putting up with, but would like the default updated as well. Since, CESM has MCT deprecated, we really should update the default to be NUOPC.

**Comment by ekluzek** [comment]
It looks like the way to have a different default for cesm is to do something like:

``` python
comp_interface_default = "mct"
if config.test_mode == "cesm":
   comp_interface_default = "nuopc"

 parser.add_argument( 
     "--comp_interface", 
     choices=supported_comp_interfaces, 
     default=comp_interface_default, 
     help="Coupler/Driver interface", 
 ) 
```

**Comment by klindsay28** [comment]
Is there a reason to not use the `get_cime_default_driver()` function from `CIME.utils`, like is done for `create_newcase`?
This is what I was getting at in the initial comment.

**Comment by ekluzek** [comment]
Ahhh, I see what you mean. I didn't pick that up on my first read through. I do think that's the way to do it, and it might as well also use drv_choices to list the options the same was as done in create_newcase.

For the purposes of these two scripts, I don't think there is an important distinction between "driver" and "comp_interface". The name of the internal XML variable is "COMP_INTERFACE", so --comp_interface corresponds closer to that. But, you also can't just create a case and change the COMP_INTERFACE variable and get the case to work. It is something that you need to know at the top level to get it to work correctly.

**Comment by ekluzek** [comment]
In looking at the blame and git log for these two scripts, it looks like create_newcase always used driver and query_config always used comp_interface going all the way back. The query_config script does have several internal variables that use comp_interface, so having the command line option be "driver", would be a little strange unless you changed all of that. I also get the impression that the query_config could use the simpler methodology used in create_newcase, but I can't say for sure.

@jasonb5 you did a lot of the work on query_config for this, do you think the distinction for comp_interface in query_config is important? Could it be changed to use "driver" and more similar to the methodology used in create_newcase?

**Comment by jasonb5** [comment]
@ekluzek The distinction is not very important. I'd be fine with updating the argument to be `driver`. @jgfouca Any thoughts on this change?

The model specific driver options and defaults are exposed through the `Config` class
https://github.com/ESMCI/cime/blob/5877fde1677982ad5b2fdd3adc49be59aa231dae/CIME/config.py#L190-L197

If the defaults don't work, you can [customize](https://esmci.github.io/cime/versions/master/html/users_guide/cime-customize.html) it in your model's `cime_config` directory, you can reference the [E3SM config](https://github.com/E3SM-Project/E3SM/blob/fc9f903ccd497204c699a2517cc0dbc0df83d54b/cime_config/customize/config.py#L34-L35).

**Comment by jgfouca** [comment]
I'd be fine with changing the arg to driver.
