### ISSUE TITLE
Convert PET test to SystemTestsCompareTwo infrastructure

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#447]
We want to convert the various system tests that compare two runs to use the SystemTestsCompareTwo infrastructure, where possible. I am opening separate issues for each such system test, so that we can check them off as we do this conversion.

**Comment by mfdeakin-sandia** [comment]
This looks like this was completed on or before Sept 13

**Comment by billsacks** [comment]
You're right. I'm not sure why I ever created this issue, since I had fixed PET before opening it. Closing this.
