### ISSUE TITLE
Adding a "Responsibility: CTSM" label to issues.

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4470]
In CESM we have decided to add a new label to a lot of our externals "Responsibility: CTSM". This means it's the CTSM software groups responsible to manage and accomplish the tasks in the issue. In some cases the CTSM group might know who should be assigned one of these tasks, but some might be a lower priority until other things are accomplished, so might not be assigned an individual until later. But, using that label makes it obvious who's responsibility it is to both manage and make happen. CAM-SIMA is also likely to add a similar label, but they'll do it when they've established a need for it.

Any comments about this from E3SM folks? @jgfouca @rljacob ?the CESM-only and E3SM-only labels could also be changed to Responsibility: CESM and Responsibility: E3SM as well. The -only labels both point out responsibility as well as how it will be handled in the code though. So it would also be OK to leave them as they are.

**Comment by ekluzek** [comment]
I do have the ability to edit labels, so as soon as I hear that this sounds OK to folks, I'll go ahead and add it and close this. But, I figure I should wait to hear from more people before I do that.

**Comment by rljacob** [comment]
That is fine with me but this would seem to imply there are still model-specific things in CIME and I thought we had removed them all.

**Comment by ekluzek** [comment]
Good point @rljacob. There isn't as much as there used to be, but there are some issues assigned to me that should have the CTSM label: #3390,#3097. There are a bunch of other issues assigned to me that need to be moved to CMEPS and/or CDEPS. So I'll move those over and close the cime version.

So for cime I imagine there will be a small number of issues where this makes sense. So might still be worth creating the label. But, I also see your point where this is important for other externals, but maybe not so much for cime. So I'd be OK with canning this idea for cime.

Do you have comments about changing the cesm-only and E3SM-only labels? Thanks for the discussion.

**Comment by rljacob** [comment]
No go ahead and change them.

**Comment by ekluzek** [comment]
OK, I created the new label, and changed the existing -only ones. So closing.
