### ISSUE TITLE
ESMF_LOGFILE_KIND option is not working properly

### ISSUE THREAD

**Issue by uturuncoglu** [ESMCI/cime#4498]
The `esmf_logging ` option in  `nuopc.runconfig` is not working since the esmf logging is controlled by `drv_in` using `create_esmf_pet_files` namelist option (in CMEPS driver code). So, I am not sure but maybe there is no need to expose `ESMF_LOGFILE_KIND` in the `cmeps/cime_config/namelist_definition_drv.xml` file. Unexperienced uses like me might have some difficulty to change the default value of ESMF login since it is confusing.

**Comment by jedwards4b** [comment]
I don't understand - I use this all the time and it seems to work fine for me.
Please elaborate with an example.   Unless perhaps this issue only applies to UFS?

**Comment by jedwards4b** [comment]
Actually @uturuncoglu why is this in cime - isn't it a cmeps issue?

**Comment by uturuncoglu** [comment]
No it is not UFS. I am using CESM for CMCC regional coupling work. BTW, What is the meaning of having `esmf_logging` option. Is it used by any component? I think CMEPS driver is not looking to it instead of it is looking to the drv_in and this information only meaningful to the driver. I could not be sure about where is the right place to open this issue. Maybe it is CMEPS but since it is also related with the CMEPS CIME interface I decided to put in here.

**Comment by jedwards4b** [comment]
XML variable 	CREATE_ESMF_PET_FILES is used and converted to namelist entry create_esmf_pet_files  in drv_in.   The reason this is not in nuopc.runconfig is that it needs to be read before esmf is initialized.

I see now that there is a variable esmf_logging in nuopc.runconfig that doesn't appear to be used at all.   Now I understand the issue - but it should be opened in cmeps - not in cime

**Comment by jedwards4b** [comment]
@uturuncoglu please move this issue to CMEPS

**Comment by uturuncoglu** [comment]
@jedwards4b Closing this since I created new one under CMEPS - https://github.com/ESCOMP/CMEPS/issues/416
