### ISSUE TITLE
bless_test_results and compare_test_results assume ACME's baseline directory organization

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#451]
bless_test_results and compare_test_results assume that you're using ACME's organization of the baseline directories, whereby there is a COMPILER subdirectory of the given baseline directory. CESM does not use this directory organization. This assumption appears on this line in bless_test_results.py and compare_test_results.py:

```python
        baseline_full_dir = os.path.join(baseline_root, case.get_value("COMPILER"), baseline_name, case.get_value("CASEBASEID"))
```

@jgfouca recently commented by email that the need for this extra COMPILER level in the directory structure may no longer exist. If so, it seems like it could simplify the scripts if this were removed. But if there is a reason to maintain it in the ACME workflow, then bless_test_results and compare_test_results need to be generalized to handle a directory structure that doesn't contain the compiler.

**Comment by jedwards4b** [comment]
bless_test_results is not used in the cesm workflow so it should not matter.  I'll take a look at compare_test_results

**Comment by billsacks** [comment]
@jedwards4b : bless_test_results is not used in the standard workflow, but I have used the same functionality in what used to be baseline_gen_comp in the past, so I feel it would be good for bless_test_results to work for CESM, too.

I believe that bless_test_results follows basically the same structure as compare_test_results, so a fix in one should hopefully slide in relatively easily to the other as well.

**Comment by jgfouca** [comment]
@jedwards4b : Don't worry about it, I'm going to remove the compiler level in the directory structure of ACME.

**Comment by jedwards4b** [comment]
It seems to me that test_schedular writes the correct baseline directory to the case XML in
BASELINE_NAME_GEN and BASELINE_NAME_CMP and that the other scripts should be using those variables.

**Comment by billsacks** [comment]
> It seems to me that test_schedular writes the correct baseline directory to the case XML in
> BASELINE_NAME_GEN and BASELINE_NAME_CMP and that the other scripts should be using those variables.

No, that won't work: Much of the point of these scripts is to be able to specify new directories (for the baseline tag name and/or the baseline root), so you can't use what was specified at create_test time.

**Comment by jedwards4b** [comment]
Sure it will - if you want a different directory use xmlchange to update the value.

**Comment by billsacks** [comment]
> Sure it will - if you want a different directory use xmlchange to update the value.

I just mentioned this to @jedwards4b but to keep everyone in the loop: This won't work well because you'd have to do this for every test, defeating much of the purpose of these tools.

Anyway, we'll defer solving this to @jgfouca 's plan to remove the compiler level from the baseline directory path.
