### ISSUE TITLE
Error message in TestStatus

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4511]
After PR #4506 I started getting the following error messages in TestStatus for all tests.

FAIL SMS.f19_g17.X.cheyenne_intel MEMCOMP [Errno 2] No such file or directory: '/glade/campaign/cesm/cesmdata/cesm_baselines/nightly_previous/SMS.f19_g17.X.cheyenne_intel/cpl-mem.log'
FAIL SMS.f19_g17.X.cheyenne_intel TPUTCOMP [Errno 2] No such file or directory: '/glade/campaign/cesm/cesmdata/cesm_baselines/nightly_previous/SMS.f19_g17.X.cheyenne_intel/cpl-tput.log'

**Comment by jedwards4b** [comment]
They took out code that allowed this file to be missing - at performance.py lines 37 and 86

**Comment by fischer-ncar** [comment]
Fixed with #4570
