### ISSUE TITLE
All multi-instance history files should be compared in NCK test

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#452]
Until PR #413 the shell script-based component_compare_test had logic specific to the multi-instance tests (NCK and its variants) so that it would compare both the _0001 and the _0002 file from the multi-instance run with the standard file from the non-multi-instance run. I believe that was a critical piece of these tests. @mvertens wrote this.

That functionality is now gone.

I'll be the first to admit that the old way of doing it wasn't ideal - i.e., embedding this test-specific logic in the general component_compare_test. Ideally, we'd have a mechanism for an individual test to specify some custom code for doing in-test comparisons. (And, as an aside, that would address a desire that I and others have expressed for a while: we'd like to be able to make component-specific tests that do something more than just doing a blanket comparison of history files for equality.) But I realize that that might require some significant rework (or maybe not... I'm not sure).

In any case, I believe we should have some mechanism for maintaining the old NCK (etc.) behavior, even if it's via a short-term kludge that we will improve later.

**Comment by jedwards4b** [comment]
How about if we only store the first instance in the baseline and make sure that all instances are compared to that.   I don't want the short term kludge you suggest and believe we can fix this correctly.

**Comment by billsacks** [comment]
@jedwards4b : An NCK test should do its in-test comparisons regardless of whether you're comparing with baselines. This is important in the case where you're not doing a baseline comparison, or in the common case where you expect baseline comparisons to fail but still want to ensure that the basic test functionality passes. (Here I consider 'basic test functionality' to mean ensuring that the _0001 and _0002 hist files in the multi-instance test match the hist file in the single-instance test.)

Personally, I'm fine with deferring the solution of this problem if you (understandably) don't want a short-term kludge.

**Comment by jedwards4b** [comment]
i don't think it'll be that difficult to fix
