### ISSUE TITLE
Name of cprnc.out files is less informative than before

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#453]
Example: an ERS test, which produces hist files with suffix .base and .rest.

Before PR #413 , cprnc.out files had a format given by either:

(1) In-test comparisons: *.rest.cprnc.out

(2) Baseline comparisons: *.base.cprnc.out

Now, if I understand things right, we instead get:

(1) In-test comparisons: *.base.cprnc.out

(2) Baseline comparisons: *.cprnc.out (no suffix)

This is less informative. I can live with it if it was intentional for some reason, but I'm guessing it may have been an unintentional change.

**Comment by jedwards4b** [comment]
The information about what was compared is the first text inside these file.  I think this is a low priority issue - unless you find that info to be incorrect.

**Comment by billsacks** [comment]
I agree that this is low priority, but it would be good to fix at some point - at least for the name of the file produced by the in-test comparisons (e.g., the .rest vs .base file). 

I looked a little more closely at the cime4 vs. cime5 behavior, and I see:

For in-test comparisons:

cime4: file1 = .rest, file2 = .base
cime5: file1 = .base, file2 = .rest

The cprnc.out file is named based on the suffix of file1, so this explains the change in behavior. (As far as I can think of, I don't _think_ it matters which one is used as file1 and which is used as file2... but it would be good if the cprnc.out file were named with the suffix of run2 - e.g., the 'rest' suffix for a restart test.)

For baseline comparisons:

cime4: file1 = test file with 'base' suffix, file2 = baseline
cime5: file1 = test file with no suffix, file2 = baseline

It's not clear to me if there are any potential problems due to using the file with no suffix, as opposed to the file with the 'base' suffix, for the baseline comparisons. For tests I'm most familiar with, these should do the same thing as long as the test itself passed. But @mvertens put in the original logic to ensure use of the 'base' file for baseline comparisons, so maybe she could comment further.

**Comment by billsacks** [comment]
I can live with this if others like @mvertens can, so am closing it as a wontfix
