### ISSUE TITLE
Why is -m used for cprnc?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#455]
@jedwards4b : Why is the -m flag now used for cprnc, in hist_utils.py: cprnc?

```
    stat, out, _ = run_cmd("%s -m %s %s 2>&1 | tee %s/%s.cprnc.out" % (cprnc_exe, file1, file2, rundir, basename))
```

It looks like you added this flag in 39a778b4b335ee970e8aac4a4bf276e2e6886f78

I'm curious to know why this is needed. In many cases, it won't change behavior, but in some cases it will mean (I believe) that only the last time sample is compared on a history file that contains multiple time samples.

**Comment by jedwards4b** [comment]
It's needed to analyze some files that have no time dimension - I don't think that it's a problem to only compare the last time sample in a multiple time file - do you?

**Comment by billsacks** [comment]
What I meant to ask was: Why is this needed now, when it wasn't needed in the past? Are there some new file types that are being compared now that we weren't handling in the past?

Regarding whether it's a problem to only compare the last time sample: This is similar to the question of whether we should compare all history files or just the last history files for each test: The more we compare, the more robust the tests are, at the expense of extra cost for cprnc. In this case, my preference would be to maintain the old behavior of comparing all times unless there's a good reason not to: It gives test developers the flexibility of comparing more than just the last time slice of the test by outputting history files with multiple times in them. (e.g., in principle you could get this to compare select variables across the whole model run by having a history file, say .h2, which has enough time samples to span the whole test.)

A compromise solution, with the expense of a few extra lines of code, would be to do something like the following (warning: untested):

```python
    stat, out, _ = run_cmd("%s %s %s 2>&1 | tee %s/%s.cprnc.out" % (cprnc_exe, file1, file2, rundir, basename))
    # See if we need to try again with the -m argument, which prevents looking
    # for a time dimension: If the above command failed because there was no
    # time dimension, the last line of output of cprnc will be 'NetCDF: Variable
    # not found'.
    if out.splitlines()[-1] == 'NetCDF: Variable not found':
        stat, out, _ = run_cmd("%s -m %s %s 2>&1 | tee %s/%s.cprnc.out" % (cprnc_exe, file1, file2, rundir, basename))
```

**Comment by jedwards4b** [comment]
Yes, some new types of files are now being compared.  I will consider your suggestion.

**Comment by billsacks** [comment]
Sorry, it turns out I was wrong in my interpretation of the '-m' flag: For comparison of two files with time dimensions that match up, it looks like '-m' has no effect. It looks like '-m' just helps when you have files that have different time dimensions, where some times match up and others don't. e.g., if you have file1 with times 1, 2, 3, 4 and file2 with times 3, 4, 5, 6, then cprnc _without_ -m will match up times 3 & 4 in both files, whereas cprnc _with_ -m will try to compare file1 time 1 with file2 time 3, etc.

Based on that, I can't think of a situation where -m would be problematic in our test system, and actually it seems to provide a bit _more_ robustness. So I'm fine with -m being used all the time.

Sorry about the confusion.
