### ISSUE TITLE
Allow users to force a restart dump and stop

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#4552]

**Comment by rljacob** [comment]
I'm pretty sure this can be done entirely in the coupler/driver without any CIME mods.  It could work like this:
In main coupler run loop, look for a file named "STOPNOW" in the $RUNDIR.
If found, send the restart-and-stop signal by setting the appropriate alarm.

A user or some other system could place the STOPNOW file.

I can't implement this without spending some time remembering how the alarms work.

**Comment by jgfouca** [comment]
Thanks, @rljacob . I agree that it would be ideal to leave CIME out of this if possible.

**Comment by jedwards4b** [comment]
I agree that this does not need to involve cime.
