### ISSUE TITLE
Merge Mira and Cetus settings as much as possible in ACME configs

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#457]
Mira and Cetus only need to differ, wrt configuration settings,
in the batch queue settings. We should merge the changes
in config_machines and config_compilers for Mira and Cetus
to a single entry. This change would make maintaining compiler
versions easier on these machines.

**Comment by jedwards4b** [comment]
On the CESM side (and this applies to cime2 as well as cime5) we do not have a separate definition for cetus, we identify that machine as mira as well.

**Comment by rljacob** [comment]
The machine name, when used as an index in to the config files, is arbitrary and does not have to match the actual unix machine name (thanks to the regex ability).  So we could collapse those in to one machine called "bgq" or similar.

**Comment by rljacob** [comment]
Of course "-mach" is no longer a required argument so this could all be done under the hood.

**Comment by jayeshkrishna** [comment]
We do want different settings for the batch queues on the two machines. The other places using "mira|cetus" should work, i think.

**Comment by rljacob** [comment]
If you make the distinction in one file do you have to make it in all files?

**Comment by jedwards4b** [comment]
It's going to use the machine identified by config_machines.xml so if that identifies the machine as mira then mira will be the identifier for all of the other files.

**Comment by rljacob** [comment]
Sounds like we can't do this then:  have one entry in config_compilers and machines then expand to 2 entries in config_batch.

**Comment by jayeshkrishna** [comment]
I think this feature should be added to CIME. Machine name should not be set/derived from the MACH field, it should rather be matched with the MACH field (the machine name should be stored independently of this matching criterion).
We could be using two different rules (matching rules) in config_machines.xml and config_compilers.xml, for example.

**Comment by rljacob** [comment]
@jayeshkrishna is this still a feature request?  Can you explain?

**Comment by rljacob** [comment]
telecon:  closing.
