### ISSUE TITLE
cpl-mem.log not being created for short tests

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4590]
In tests that are run for less than a day, no memory diagnostics are being written to log files.
Therefore no baseline cpl-mem.log is being generated.  This creates false fails when checking 
for the baseline cpl-mem.log.

`FAIL SMS_Ln9_Vnuopc.f09_f09_mg17.FW1850.derecho_intel.cam-reduced_hist3s MEMCOMP [Errno 2] No such file or directory: '/glade/campaign/cesm/cesmdata/cesm_baselines/cesm2_3_alpha17a/SMS_Ln9_Vnuopc.f09_f09_mg17.FW1850.derecho_intel.cam-reduced_hist3s/cpl-mem.log'
`

**Comment by fischer-ncar** [comment]
Still needs to be fixed.

**Comment by samsrabin** [comment]
I just ran into this with CTSM testing. It makes me uncomfortable to see spurious failures, because it inures me to seeing `FAIL`, and eventually I'll ignore a real one. Could this be bumped up the priority list?
