### ISSUE TITLE
IRT test failing after PR #4557

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#4591]
After PR #4557, IRT tests fail with "Missing required pointer" error.

Removing the following line and the IRT test will pass.  But probably breaks everything else.

https://github.com/ESMCI/cime/blob/58b7cab30d17b30ccb7fb5d85c319839420f453c/CIME/SystemTests/system_tests_compare_two.py#L565C25-L565C35

To recreate the error use ./create_test IRT_Ld7.f09_g17.BHIST.derecho_intel.allactive-defaultio
Other IRT tests using A or QPC6 will pass.

**Comment by jedwards4b** [comment]
This issue is specific to the pop ocean model which we do not plan to carry forward to cesm3.  The decision was made to move this test to use the MOM ocean model instead of fixing it for POP.
