### ISSUE TITLE
Feature: Parameters for SystemTests

### ISSUE THREAD

**Issue by jasonb5** [ESMCI/cime#4592]
A request has come to update the MVK to support another component.
This update involves adding additional static values to the MVK test.
Continuing to define these additional values is not sustainable especially
as more components may utilize the MVK test.

I'm proposing to add a general feature to enable passing a parameter
file to `create_test` e.g. `create_test --params /somepath/eamxx_v1.json`.
In addition we could enable this for testmods by providing a `params.json`
file under the specific testmod directory. An optional level of providing 
these parameters could be through `$SRCROOT/cime_config/test_params/MVK.f19_g16.S.json`,
this could provide parameters at a specific test level regardless of the testmods.

This feature would be enabled for all test types.

I'm at a toss up for the file format, I was leaning towards a json but I'm not
opposed to just defining another XML class.

Example parameter file, if a testmod is used the `user_nl*` could be omitted.
```json
{
  "component": "eamxx",
  "user_nl": {
    "new_random": ".true.",
    "pertlim": "1.0e-10",
  }
  # could be per inst
  "user_nl_0001": {
    "new_random": ".true.",
    "pertlim": "1.0e-10",
  },
  "module": "ks.py",
  "test-case": "Test",
  "critical": "13",
}
```
@jgfouca @rljacob @jedwards4b @billsacks

**Comment by billsacks** [comment]
Can you describe the advantages of this over the current testmods approach?

**Comment by jasonb5** [comment]
Testmods can provide the namelist files but it currently cannot provide configuration to the actual test e.g. for MVK configure the invocation of evv4esm. The addition of the flag to `create_test` would allow one-offs or overriding the testmods values.

**Comment by jgfouca** [comment]
One good thing about testmods is that using them changes the case name which is important since the mods make it a different test than unmodded. Why not just incorporate JSON support into the testmod system? Kind of like how it expects `shell_commands` to be there now, it could also check for .json files.

**Comment by jasonb5** [comment]
I'm fine making testmods the default way of providing the parameters.

Is it worth including a new argument to `create_test` to override testmods? A use-case I was thinking of is a user wanting to test something without changing the testmod, maybe this isn't really a practical use-case though.

**Comment by rljacob** [comment]
This PR has an attempt to add MVK to the ocean  https://github.com/E3SM-Project/E3SM/pull/6207  But it seems to be using the xml test system which E3SM doesn't use.  Can what you propose allow MVK to be used for ocean?

**Comment by rljacob** [comment]
@mkstratos

**Comment by jasonb5** [comment]
@billsacks You're right, it's simple enough to change the file or create another testmod so there's probably no merit in adding it.

**Comment by jedwards4b** [comment]
I am looking at this test for the first time and I realize that I have some concerns with the way that it is implemented.  First, as far as I can tell, this test only works with the CAM model as defined in e3sm.   There are no namelist variables for [new_random, seed_custom and seed_clock ](https://github.com/ESMCI/cime/blob/master/CIME/SystemTests/mvk.py#L72)in CAM as defined in CESM.   

So if this change would make the test useful for CESM by removing the namelist modifications to a json file whose selection could depend on CIME_MODEL then I support the change.   I also agree that it is important to maintain a one-to-one correspondence between test names and the actual test conducted, so doing this as a part of the testmods is also good.   I would also like to point out that this reference:
[https://github.com/E3SM-Project/E3SM/blob/master/cime/scripts/climate_reproducibility/README.md](https://github.com/E3SM-Project/E3SM/blob/master/cime/scripts/climate_reproducibility/README.md ) from [mvk.py ](https://github.com/ESMCI/cime/blob/master/CIME/SystemTests/mvk.py#L188) appears to be a broken link.

**Comment by jasonb5** [comment]
@jedwards4b That's correct this update would make the mvk test completely customizable through a testmod. Do you have a preference between a python module or json file? I'm leaning towards a python module so we can support more complex setup for the test as required by https://github.com/E3SM-Project/E3SM/pull/6207. We could also support a json file for a simple configuration this wouldn't add too much.
