### ISSUE TITLE
what does e3sm build still use? 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4612]
I'm trying to clean up the cesm build since we are no longer planning to support the cpl7 and I am a little confused about what parts of the build system are still needed by e3sm and what parts are just dead code?   For example - does e3sm call build.py?

**Comment by rljacob** [comment]
@jgfouca see above.

**Comment by jgfouca** [comment]
@jedwards4b , are you talking about `cime/CIME/build.py` ? We make extensive use of that file.
