### ISSUE TITLE
Handle chdir calls more robustly

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#462]
Creating this issue based on a conversation with @jgfouca and @quantheory on slack. The original discussion came from an issue that I was responsible for with scripts_regression_tests, where some of the code I was testing had a chdir call that (in the unit test environment) changed into a temporary directory that was deleted at the end of the test. I had neglected to chdir back to the original directory when the test finished. This original issue was fixed via PR #458 , but the broader issue remains. I am copying some of the relevant conversation from slack.

From @jgfouca 

> Most everything we do now happens within a single process which is a big change from earlier versions of CIME. This is mostly a very good thing for performance and debugging, but it does mean more of the code is sharing the "global" state associated with a process such as the current working directory. In my opinion, any chdir or os.environ will lead to bugs that are potentially very difficult to find. I was stumped for many hours today with this getcwd issue.
> 
> i'm looking at all the chdir calls in the code. it isn't too bad, there's only a few. we don't need to remove them. we need to encapsulate in a context manager ("with" statement). so that upon object close, the cwd is restored
> 
> The SystemTestsCommon class will need to be used via content manager

(should this say SystemTestsCompareTwo?)

> other than SystemTests, the only chdir calls i'm worried about are these:

```
utils/python/CIME/build.py:    os.chdir(caseroot)
utils/python/CIME/case.py:        os.chdir(self._caseroot)
utils/python/CIME/case_setup.py:    os.chdir(caseroot)
```

I'm not entirely clear on what @jgfouca is suggesting, although it sounds something like this: 
http://nedbatchelder.com/blog/201508/using_context_managers_in_test_setup.html

I suggested that a more robust solution would be to remove all uses of getcwd, which I thought would allow removing all(?) uses of chdir as well. (See also https://www.reddit.com/r/Python/comments/1sxil3/chdir_a_context_manager_for_switching_working/). But @quantheory pointed out:

> If we could prevent tools from relying on the working directory it would be nice, but I think that's a bit harder than just getting rid of all `getcwd` uses. There could also be problems with using relative paths.

So maybe the context manager suggestion is the best near-term solution.

**Comment by jgfouca** [comment]
I attempted this, but the current directory is deeply baked into a large amount of our code. I'm going to punt and unassign myself for now until this is more urgently needed.

**Comment by billsacks** [comment]
@jgfouca - any feelings as to whether we keep this open as Low Priority, or close it as wontfix? I'm fine either way.

**Comment by jgfouca** [comment]
Low priority is my opinion.

**Comment by jgfouca** [comment]
Closing. Would be nice, but would be quite hard.
