### ISSUE TITLE
'use --append' is not a valid value of the atomic type 'xs:NCName' for the cime w/t e3sm/maint-2.1 (2.0) 

### ISSUE THREAD

**Issue by jsbamboo** [ESMCI/cime#4620]
When I copied the latest Livermore Computing machine configuration from the E3SM / scream repo to the `e3sm/maint-2.1` and `maint-2.0` branches, create_newcase reported the following error due to the `use --append` parameter in the latest LC config_machines.xml:
`<command name="use --append">/usr/gdata/e3sm/install/quartz/modulefiles</command> `

> ERROR: Command: '/usr/bin/xmllint --xinclude --noout --schema /p/lustre2/zhang73/GitTmp/push_to_remote/E3SM_maint-2.0/cime/CIME/data/config/xml_schemas/config_machines.xsd /p/lustre2/zhang73/GitTmp/push_to_remote/E3SM_maint-2.0/cime_config/machines/config_machines.xml' failed with error '/p/lustre2/zhang73/GitTmp/push_to_remote/E3SM_maint-2.0/cime_config/machines/config_machines.xml:1761: element command: Schemas validity error : Element 'command', attribute 'name': 'use --append' is not a valid value of the atomic type 'xs:NCName'.
> /p/lustre2/zhang73/GitTmp/push_to_remote/E3SM_maint-2.0/cime_config/machines/config_machines.xml:1818: element command: Schemas validity error : Element 'command', attribute 'name': 'use --append' is not a valid value of the atomic type 'xs:NCName'.

I assume it's related to the cime version w/t `e3sm/maint-2.1` and `e3sm/maint-2.0` since there is no `use --append` for all machines in config_machines.xml, so I'm here to post the issue. When I shifted to an older mach config version on LC (without use --append) it passed build.

**Comment by jsbamboo** [comment]
Jason, please help to check the issue @jasonb5

**Comment by jedwards4b** [comment]
I think that you don't want the --append and it's not required for any module system that I am aware of.

**Comment by jsbamboo** [comment]
Cool it passed! I'm going to close this issue

> I think that you don't want the --append and it's not required for any module system that I am aware of.
