### ISSUE TITLE
Where did one-letter case names come from?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#4626]
Does anyone remember how the one-letter case names (B-case, F-case) came about?

Its in the CESM1.0 docs
https://www2.cesm.ucar.edu/models/cesm1.0/cesm/cesm_doc_1_0_4/x42.html

But I'm pretty sure its older then that.

**Comment by klindsay28** [comment]
The convention is mentioned in CSM/CCSM 1 [documentation](https://www2.cesm.ucar.edu/experiments/ccsm1.0/names.html#1).
According to documentation on [legacy releases](https://www.cesm.ucar.edu/models/legacy), this version was released in June 1996.
This doesn't describe how the convention came about,
it just demonstrates that it's been around a long time.
