### ISSUE TITLE
regression test  test_d_create_clone_new_user FAILS

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4630]
@jasonb5 this looks like it's due to https://github.com/ESMCI/cime/pull/4609

======================================================================
FAIL: test_d_create_clone_new_user (test_sys_create_newcase.TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/CMEPS/CMEPS/cesm/cime/CIME/tests/test_sys_create_newcase.py", line 264, in test_d_create_clone_new_user
    self.run_cmd_assert_result(
  File "/home/runner/work/CMEPS/CMEPS/cesm/cime/CIME/tests/base.py", line 141, in run_cmd_assert_result
    self.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 1 != 0 : 
    COMMAND: ./xmlchange CIME_OUTPUT_ROOT=/home/this_is_not_a_user/cesm/scratch/scripts_regression_test.20240514_194710/TestCreateNewcase
    FROM_DIR: /home/runner/cesm/scratch/scripts_regression_test.20240514_194710/TestCreateNewcase/testcreatenewcase
    SHOULD HAVE WORKED, INSTEAD GOT STAT 1
    OUTPUT: 
    ERRPUT: Detected diff in locked file 'env_build.xml'
	'CIME_OUTPUT_ROOT' has changed from '/home/runner/cesm/scratch/scripts_regression_test.20240514_194710/TestCreateNewcase' to '/home/this_is_not_a_user/cesm/scratch/scripts_regression_test.20240514_194710/TestCreateNewcase'
ERROR: For your changes to take effect, run:
./case.build --clean-all
./case.build

**Comment by jasonb5** [comment]
@jedwards4b Will have this fixed shortly.

**Comment by jasonb5** [comment]
@jedwards4b Was this fixed by https://github.com/ESMCI/cime/pull/4631?
