### ISSUE TITLE
error in timing makefile

### ISSUE THREAD

**Issue by dudek313** [ESMCI/cime#4639]
commit a488510bc24b981809b3dda5ee7b9809a7fc9616 (HEAD, tag: cime5.6.49

cesm/cime/src/share/timing/Makefile

Line 74-75:

-       cp -p *.$(MOD_SUFFIX) $(SHAREDPATH)/include
-       cp -p libgptl.a $(SHAREDPATH)/lib
+       cp -p $(GPTL_DIR)/*.$(MOD_SUFFIX) $(SHAREDPATH)/include
+       cp -p $(GPTL_DIR)/libgptl.a $(SHAREDPATH)/lib

**Comment by jedwards4b** [comment]
I think that I see what you want to do - but I can't read it as written.  Please clarify and consider opening a PR with your suggested change.

**Comment by dudek313** [comment]
Apologies @jedwards4b I was in a bit of a haste.

The makefile has a couple of cp commands that don't have the base path $(GPTL_DIR), so the copy fails.

For example, I think that line 74 should be:
cp -p $(GPTL_DIR)/*.$(MOD_SUFFIX) $(SHAREDPATH)/include

What makes me uneasy is that this is supposed to be the production branch so something like that would be caught early. Perhaps this is the time to disclose that I am migrating from a really old version of CESM (1.0.6) ;)

**Comment by jedwards4b** [comment]
The maint-5.6 branch has, as you pointed out, been stable for a very long time.  This code has not been a problem for anyone that I am aware of.   If you can document an error, providing all of the relevant information to reproduce the error we will be happy to address it.
