### ISSUE TITLE
titan config_pes collision

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#464]
in cime_config/machines/acme/allactive/config_pesall.xml we have two nodes (with different configurations) that are generating the
same matching score in pes.py:

 ```
<grid name="a%ne30np4">
    <mach name="titan|stampede|bluewaters">
      <pes compset="any" pesize="any">...
 <grid name="a%ne30np4_l%ne30np4_oi%gx1v6">
    <mach name="titan|stampede|bluewaters">
      <pes compset="any" pesize="any">...

```
triggering the error message:

`ERROR: We dont expect to be here`

Is this a problem with how the xml should be designed or does the scoring system need to be a little smarter?

Jason

**Comment by jedwards4b** [comment]
Can you refine the grid name field so that there is a distinction between the two?   In other words change the first grid so that it isn't just a subset of the second one.

**Comment by rljacob** [comment]
Looking at the original (cime_config/acme/allactive/config_pes.xml.cime2), its hard to tell what the logic was intending.  There are 2 different layouts.  The first one is supposed to be for any grid with ne30np4 and the the second for that specific grid.  That seems like good logic.   We can't do that now?

**Comment by sarich** [comment]
Yes I could change this field, but there are multiple instances of this substring matching and it would be easier to enhance the logic in the scoring.

**Comment by rljacob** [comment]
Jim, do entries across all the config_pes files have to be unique?  This might be a case where us still having one file is biting us.  The first one should probably be in components/cam/cime_config/config_pes.xml (which doesn't exist yet for ACME).

**Comment by jedwards4b** [comment]
So if you specify a compset match for the first one to match only F compsets that should also work.

**Comment by rljacob** [comment]
For the first entry, change compset="any"
 to
 compset="CAM.+CLM.+DOCN."

**Comment by sarich** [comment]
I've made a list of all the conflicts in cime_config/acme/allactive/config_pesall.xml, I need some help
determining which compsets can be assigned:

```
SUB  : a%ne240np4
 mach=any pesize=any compset=any
SUPER: a%ne240np4_l%0.23x0.31_oi%gx1
 mach=any pesize=any compset=any

SUB  : a%ne240np4
 mach=any pesize=any compset=any
SUPER: a%ne240np4_l%0.23x0.31_oi%tx0.1v2
 mach=any pesize=any compset=any

SUB  : a%ne120np4
 mach=titan|stampede|bluewaters pesize=any compset=CAM.+CLM.+CICE.+POP
SUPER: a%ne120np4_l%0.23x0.31_oi%tx0.1v2
 mach=hopper|titan|stampede|janus pesize=any compset=CAM.+CLM.+CICE.+POP

SUB  : a%ne30np4   **** assign compset="CAM.+CLM.+DOCN." ****
 mach=titan|stampede|bluewaters pesize=any compset=any
SUPER: a%ne30np4_l%ne30np4_oi%gx1v6
 mach=titan|stampede|bluewaters pesize=any compset=any

SUB  : a%ne30np4  **** assign compset="CAM.+CLM.+DOCN." ****
 mach=hopper pesize=any compset=any
SUPER: a%ne30np4_l%ne30np4_oi%gx1v6
 mach=hopper pesize=any compset=any

SUB  : a%1.9x2.5
 mach=any pesize=T compset=any
SUPER: a%1.9x2.5_l%1.9x2.5_oi%gx1
 mach=any pesize=T compset=any

SUB  : a%1.9x2.5
 mach=any pesize=T compset=any
SUPER: a%1.9x2.5_l%1.9x2.5_oi%1.9x2.5
 mach=any pesize=T compset=any

SUB  : a%0.9x1.25
 mach=any pesize=T compset=any
SUPER: a%0.9x1.25_l%0.9x1.25_oi%gx1
 mach=any pesize=T compset=any

SUB  : a%wr50a
 mach=any pesize=any compset=any
SUPER: a%wr50a_l%wr50a_l%ar9v
 mach=any pesize=any compset=any
```

**Comment by rljacob** [comment]
I think all of those can be fixed by adding compset="CAM.+CLM.+DOCN." to the SUB.  Use that to replace the a%ne120np4.
