### ISSUE TITLE
pelayout changes no longer working

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4643]
I used to be able to do commands like:

./xmlchange NTASKS_CPL=-6,NTASKS_ATM=-6,NTASKS_LND=-2,NTASKS_ICE=-4,NTASKS_ROF=-4,ROOTPE_ICE=-2,ROOTPE_OCN=-6

But in the current cime master I am getting an error:

Detected diff in locked file 'env_mach_pes.xml'
	'NTASKS' has changed from 384 to 768
ERROR: For your changes to take effect, run:

and only the first change is applied:

 ./pelayout
Comp  NTASKS  NTHRDS  ROOTPE PSTRIDE
CPL :    768/     2;      0      1
ATM :    384/     2;      0      1
LND :    128/     2;      0      1
ICE :    256/     2;    128      1
OCN :    256/     2;    384      1
ROF :    128/     2;      0      1
GLC :    128/     2;      0      1
WAV :    128/     2;      0      1
ESP :      1/     2;      0      1
ESMF_AWARE_THREADING is False
ROOTPE is with respect to 64.0 tasks per node

Can we go back to the previous behavior?

**Comment by jasonb5** [comment]
@jedwards4b I'll have a fix for this soon, thanks for reporting it.

**Comment by jasonb5** [comment]
@jedwards4b Try again with #4650.
I left the diff message, I feel like it's a good verification of what has changed. I could change the wording. If it's really not wanted I can hide it and expose with `-v`.

```
Detected diff in locked file 'env_mach_pes.xml'
        'NTASKS_CPL' has changed from 8 to 48
        'NTASKS_ATM' has changed from 8 to 48
        'NTASKS_LND' has changed from 8 to 16
        'NTASKS_ICE' has changed from 8 to 32
        'NTASKS_ROF' has changed from 8 to 32
        'ROOTPE_ICE' has changed from 0 to 16
        'ROOTPE_OCN' has changed from 0 to 48
ERROR: For your changes to take effect, run:
./case.setup --reset

```
