### ISSUE TITLE
Python coding convention(s)

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#47]
What coding convention should CIME python code use?

**Comment by rljacob** [comment]
I'll repeat the meta-convention:  when adding to an existing code base, follow the existing convention.  We can talk about if we should uniformly transition the code to a different one and if so what.

**Comment by bandre-ucar** [comment]
CIME python coding conventions should follow the community standard.

https://www.python.org/dev/peps/pep-0008/

The autopep8 should regularly be run to enforce basic consistency:

https://pypi.python.org/pypi/autopep8

Tools like pep8, pylint or pyflakes should also be run and come back mostly clean

https://pypi.python.org/pypi/pep8
http://www.pylint.org/
https://github.com/pyflakes/pyflakes

These conventions are generally not burdensome to adhere to with basic editor integration:

emacs - https://github.com/jorgenschaefer/elpy
vim - ???? https://realpython.com/blog/python/vim-and-python-a-match-made-in-heaven/

**Comment by jgfouca** [comment]
Agree on pylint and following the PEP. I think the current code base follows it pretty closely with the exception of the hash marks highlighting functions, that's just a personal preference.

**Comment by rljacob** [comment]
We all agreed to follow PEP8
