### ISSUE TITLE
Why does the default testid use UTC time rather than local time?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#470]
@jedwards4b or @jgfouca : I've been curious why the default testid uses UTC time rather than local time (i.e., the local time of whatever machine you're on). I never realized how much I rely on this time stamp to help me orient myself to the various tests I ran, until I was no longer able to do so with this change: I'll often think, "let me look at the test I ran yesterday morning"... but now I need to do some mental math to convert UTC time back to local time.

If there's a reason for this change, I can live with it, but if this was an arbitrary choice, I'd prefer going back to the old behavior of using local time.

**Comment by mvertens** [comment]
@billsacks I completely agree with your points.

**Comment by gold2718** [comment]
I agreed with your concerns but 6 hours before you wrote them (or did I do that math backwards)?
One compromise is to use ISO 8601 format. Something like:
datetime.datetime.now().replace(microsecond=0).isoformat() but with the UTC offset. I'm not sure how to do that with standard python (while widely available, I don't think pytz is part of the standard library). What I really want is the bash:
date --iso-8601=seconds

**Comment by jgfouca** [comment]
This change was not deliberate on my part.

**Comment by rljacob** [comment]
Sounds like there are no objections to changing it to local time?

**Comment by jedwards4b** [comment]
Fixed by #483
