### ISSUE TITLE
This line of code looks wrong in hist_utils.py: _hists_match

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#472]
In this code snippet:

```python
    for hists, suffix, normalized in [(hists1, suffix1, normalized1), (hists2, suffix2, normalized2)]:
        for hist in hists:
            normalized_name = hist[hist.rfind(model):]
            if suffix1 != "":
                expect(normalized_name.endswith(suffix), "How did '%s' not have suffix '%s'" % (hist, suffix))
                normalized_name = normalized_name[:len(normalized_name) - len(suffix)]
```

The use of suffix1 in the conditional:

```python
            if suffix1 != "":
```

looks wrong to me: Intuitively, it looks like this should be simply `suffix`. I haven't taken the time to fully understand this function, so my intuition may be wrong... but if it is, an explanatory comment would help here.

**Comment by billsacks** [comment]
@jgfouca I think you wrote this code; can you comment on this?

**Comment by jgfouca** [comment]
You're correct. I'll fix.
