### ISSUE TITLE
Exact Restart tests fail for 765 days

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4722]
In what will be ctsm5.3.016 I have two 765 day ER tests that fail due to the DRV_RESTART_POINTER file setting (off by a day) being wrong. This uses:

cime6.1.49
cmeps6.0.32

The full description of the case is here for CTSM.

https://github.com/ESCOMP/CTSM/issues/2914

If the logic is wrong, there are likely other test lengths that will fail. But, there is a wide spectrum of test lengths that come with CTSM testing, so many/most must be fine.

**Comment by jedwards4b** [comment]
Please indicate the name of the test so that I can reproduce.  What calendar is it using?

**Comment by ekluzek** [comment]
Use this one:

ERP_P64x2_Ld765.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel.clm-monthly

It's using the default NO_LEAP calendar.
