### ISSUE TITLE
"./manage_case --query-machines" doesn't work on a non defined machine

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#479]
manage_case is a simple query script that should be able to work on any *nix machine. However, when the --query-machines option is chosen it sets up a machine object that queries the hostname  and when it doesn't find it, will fail as follows...

./manage_case --query-machines
Could not probe machine for hostname 'yongi'
ERROR: Could not initialize machine object

By setting a machine, you can get beyond this problem and it will properly do the query. It doesn't really matter what machine you choose, as long as it's in the config_machine.xml list, since it won't really do anything with the machine information for manage_case which is merely a query tool. You would want to pick a machine that will be in both the cesm and acme machine lists, and you want to pick something that will be in both for the duration. Possibly, we should add an option that is specific for this case?

Here's a sample change that gets it to work:

Index: manage_case
===================================================================
--- manage_case	(revision 10787)
+++ manage_case	(working copy)
@@ -35,7 +35,7 @@
     expect(os.path.isfile(config_file),
            "Cannot find config_file %s on disk" %config_file)
 
-    machines = Machines(config_file)
+    machines = Machines(config_file,machine="mira")
     machines.print_values()
 
 ###############################################################################

**Comment by rljacob** [comment]
Is there a better way to fix this problem?  Like a fake machine that could be generated internally?

**Comment by jedwards4b** [comment]
why fake instead of real

**Comment by rljacob** [comment]
Because real seems fragile and not extendable.  What happens if that machine goes away or one team deletes it?  Or a third model joins CIME with no machines in common?

**Comment by ekluzek** [comment]
OK, here's a more extensive set of changes that gets it to work, by adding a "Query" option to machine that means you are just doing some type of query. @rljacob  Is this better?

Index: scripts/manage_case
===================================================================
--- scripts/manage_case	(revision 10787)
+++ scripts/manage_case	(working copy)
@@ -35,7 +35,7 @@
     expect(os.path.isfile(config_file),
            "Cannot find config_file %s on disk" %config_file)
 
-    machines = Machines(config_file)
+    machines = Machines(config_file,machine="Query")
     machines.print_values()
 
 ###############################################################################
Index: utils/python/CIME/XML/machines.py
===================================================================
--- utils/python/CIME/XML/machines.py	(revision 10787)
+++ utils/python/CIME/XML/machines.py	(working copy)
@@ -39,7 +39,7 @@
         if os.path.exists(infile):
             GenericXML.read(self, infile)
 
-        if machine is None:
+        if machine is None and machine is not "Query":
             machine = self.probe_machine_name()
 
         expect(machine is not None, "Could not initialize machine object")
@@ -126,7 +126,9 @@
         ...
         SystemExit: ERROR: No machine trump found
         """
-        if self.machine != machine or self.machine_node is None:
+        if machine == "Query":
+            self.machine = machine
+        elif self.machine != machine or self.machine_node is None:
             self.machine_node = self.get_optional_node("machine", {"MACH" : machine})
             expect(self.machine_node is not None, "No machine %s found" % machine)
             self.machine = machine

**Comment by jedwards4b** [comment]
Erik can you please submit a PR with this change.
