### ISSUE TITLE
-mach no longer a required argument to create_newcase

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#480]
-mach is still labeled as a required argument to create_newcase, but it no longer is. Here's a sample change that clarifies it...

Index: create_newcase
===================================================================
--- create_newcase	(revision 10787)
+++ create_newcase	(working copy)
@@ -33,7 +33,7 @@
                         "To see list of current compsets, use the utility manage_case in this directory")
 
     parser.add_argument("--mach", "-mach",
-                        help="(required) Specify a machine. "
+                        help="Specify a machine (if not set, base it off of the hostname). "
                         "To see list of current  machines, use the utility manage_case in this directory")
 
     parser.add_argument("--compiler", "-compiler",

**Comment by jedwards4b** [comment]
Erik - can you please submit a PR with this change.

**Comment by jedwards4b** [comment]
Fixed by #484

**Comment by ndkeen** [comment]
that's nice
