### ISSUE TITLE
When specifying test root with ./create_test -r test_root, the run/ and bld/ directories should also change

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#485]
`./create_test cime_developer -r $SCRATCH/acme_scratch/foo -t foo`

Will create `/global/cscratch1/sd/ndk/acme_scratch/foo` with the case directories as expected, however I also get the same case directory names in `/global/cscratch1/sd/ndk/acme_scratch` which contain only bld/ and run/ dirs.

In xml, we have:

``` <RUNDIR>$CESMSCRATCHROOT/$CASE/run</RUNDIR>
  <EXEROOT>$CESMSCRATCHROOT/$CASE/bld</EXEROOT>
```

Could we add $TESTROOT?  That is:
`<RUNDIR>$CESMSCRATCHROOT/$TESTROOT/$CASE/run</RUNDIR>`
Where it would normally be empty unless specified.

@jgfouca edit: Add a flag[s] to create_test to allow user to change rundir and exeroot potentially with a short cut option to have them go under the case directory.

**Comment by jedwards4b** [comment]
This is a feature not a bug.   To change the location of build and run directories you should change $CESMSCRATCHROOT.

**Comment by ndkeen** [comment]
OK, sounds like the suggested way to have multiple test case dirs is to change CESMSCRATCHROOT.

a) Why is this not an option to create_test?
b) What in the world, then, is the -r flag for?

I'd prefer to see acme_scratch, and then below that have named directories, each one containing the case dirs of tests I'm running.

**Comment by jedwards4b** [comment]
Why is this not an option:   Noone ever requested it.
What is the -r flag for:   The -r flag moves the case directory, on many hpc systems there is a distinction between scratch space which is not backed up and workspace which is.   Typical usage has been to create the case directory in workspace so that it's backed-up and the run and bld directories in scratch space which is usually larger and possible faster IO.  

You can add the acme_scratch directory to the CESMSCRATCHROOT for your machine in config_machines.xml

**Comment by jgfouca** [comment]
@jedwards4b is correct. When I first joined ACME, I also assumed that run/bld should always just go with the case. I got a lot of push back and had to revert that change for the reasons he described.

**Comment by ndkeen** [comment]
if i get around to changing it, should i change only for myself?

**Comment by rljacob** [comment]
Sounds like the solution is to add the option to create_test to set CESMSCRATCHROOT.  If that is set to the same dir as -r, will it give the desired behavior?

**Comment by jgfouca** [comment]
@rljacob yes, i believe it would.

**Comment by jedwards4b** [comment]
Yes that would work but you probably want to add the option to both create_test and create_newcase and implement it in create_newcase (create_test would just pass it on)

**Comment by bishtgautam** [comment]
Couldn't `CESMSCRATCHROOT` be modified via `-user_mods_dir`?

**Comment by jedwards4b** [comment]
No --user_mods_dir is a different functionality altogether.   You _could_ actually use it to modify CESMSCRATCHROOT but that would be a really convoluted way to go about it.

**Comment by rljacob** [comment]
After discussion, will add additional option to create_test to move bld and run dirs.

**Comment by ekluzek** [comment]
So @rljacob this will be a separate option and the behavior of "-r" won't change? I think that would be good, I can see myself using both options.
