### ISSUE TITLE
cs.status is broken in cime standalone

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#5]
Running the cs.status script in a cime standalone environment results in the error:
Global symbol "$ccsmroot" requires explicit package name at ./cs.status.150408-131201.mira line 37.
BEGIN not safe after errors--compilation aborted at ./cs.status.150408-131201.mira line 46.

**Comment by rljacob** [comment]
Is this still a bug?

**Comment by rljacob** [comment]
Outputs data but not interfaced with testdb

**Comment by rljacob** [comment]
How does this relate to issue #104?

**Comment by jedwards4b** [comment]
Fixed
