### ISSUE TITLE
Latest CIME not working on blues/Cetus

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#509]
The latest CIME master (cime5.0.10-10-gf21e864) does not work on blues.
The case.setup (-res f45_g37_rx1 -compset A) fails with the following error message,

```
ERROR: Expected full directory path, got 'UNSET'
```

**Comment by rljacob** [comment]
I suspect a bash/tcsh thing.

**Comment by jayeshkrishna** [comment]
This also happens on Cetus.
Seems to be a bug in master.
This happens when case_setup.py tries to read value of USER_MODS_FULLPATH (the value of this var in env_case.xml is "UNSET")

**Comment by jayeshkrishna** [comment]
@jedwards4b already has a fix for this bug.
