### ISSUE TITLE
Why do we obfuscate code location?

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#514]
Do we have a standard on how to import CIME code into CIME scripts? Sometimes, the source is documented as in:
`import CIME.build as build`
However, other times, the source is purposefully obscured as in:
`from CIME.hist_utils import *`
This is fine if you have memorized all the source-code locations but seems unnecessary and seems to conflict with the PEP 8 style guide which states:

> Wildcard imports ( from <module> import * ) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools.

@jgfouca your name is on those lines, any comment?

**Comment by jgfouca** [comment]
Yes, import * is not technically PEP8 compliant, but it's so convenient that do use it sometimes.

Alternatives are:
```
from CIME.X import A, B, C, D, E, F
```
or
```
import CIME.X
...
i = CIME.X.A
j = CIME.X.B
```
or
```
import CIME.X.A as A
import CIME.X.B as B
import CIME.X.C as C
import CIME.X.D as D
import CIME.X.E as E
import CIME.X.F as F
```

The first alternative is annoying because as soon as you need an additional item from CIME.X, you need to add it to the list. Also, if you no longer need something, pylint will flag it.

The second alternative is annoying because it makes referring to items from CIME.X very verbose.

The third alternative is extremely verbose in the imports.

That said, import * has the obvious downside of making it hard for readers of the source to know where names are coming from.

If we can all agree on something, I'd be happy to change the code.

**Comment by jgfouca** [comment]
All that said, my current process is if I need 1-4 things from a library, I use alternative 1 from my previous comment. If I need more than that, I use import *.

**Comment by gold2718** [comment]
I prefer alternatives one or two (i.e., both are fine).
What tools do you use to find obscured code?

**Comment by jgfouca** [comment]
At this point, I kinda know where everything is. In the rare case where I don't:
```
git grep name_to_look_for
```
works quite well in almost all cases.

**Comment by gold2718** [comment]
I have to pipe `git grep` through a `grep def` since some of your names generate a huge number of hits (`def move` comes to mind as one where a bit of verbosity would help).

**Comment by jgfouca** [comment]
Yeah, looking for def X works great if X is a common word and you know it's a function.

**Comment by jedwards4b** [comment]
``` git grep 'def move'
utils/python/CIME/hist_utils.py:def move(case, suffix):
```

**Comment by gold2718** [comment]
An alternative which is not in your list (but which is in system_tests_common.py which contains four different import usages) is:
`import CIME.build as build`
This allows shortening the verbosity so, for example, `move` could become `hist.move` which does not seem "very verbose" (to use your phrase). I vote for using that as well.
Speaking of PEP 8, system_tests_common.py also imports multiple packages on one line which is discouraged.

**Comment by jgfouca** [comment]
That's alternative 3 from my original post.

**Comment by gold2718** [comment]
Except that my example imports an entire module with one prefix name while your example imported individual methods. Mine documents the origin of a call with minimal (controllable) extra verbiage.

**Comment by jgfouca** [comment]
Oh, I see what you mean.

So alternative 4:
```
import CIME.X as X
...
i = X.A
j = X.B
```

I guess that's a little better than alternative 1, but usually the X is a lot more characters than CIME.

**Comment by billsacks** [comment]
Joining this party a bit late, but I'd like to add a voice of support for @gold2718 's request - the use of "import *" has bothered me as well: I know that it makes it easier to write the code initially if you're already familiar with what's where, but I find that it makes understanding and modifying the code more difficult, particularly for those of us who aren't intimately familiar with the code yet.

I'd be fine with any of the alternatives that have been proposed.

**Comment by jgfouca** [comment]
Maybe we can try to come to an agreement during Friday's teleconn. I prefer alternative one.

**Comment by gold2718** [comment]
I probably can't make the telecon, however, I'm fine with either your first alternative:
`from CIME.X import A, B, C, D, E, F`
or mine
`import CIME.X as Y`
where `Y` can by `X` or a shortened version of `X` for verbosity control (e.g., hist in place of hist_utils).
I see no reason to restrict which form is used although I would like like an agreement to _not_ add blanket imports of CIME code (i.e., no asterisks).

**Comment by billsacks** [comment]
Bringing @gold2718 into the loop, since he missed today's discussion: There was general agreement that _most_ instances of "import *" should be replaced with one of the alternatives (I forget which, if any, of the alternatives emerged as a winner). @jgfouca and @jedwards4b requested exceptions for standard_module_setup and standard_script_setup - i.e., that we may still allow 'import *' from those two modules. I was hesitant about that, but was willing to accept it if they felt it was important.

I asked whether pylint would pick up namespace collisions between something implicitly imported through an 'import *' and something else defined locally. I just did a test and the answer is yes, which makes me a little more willing to accept these limited cases of 'import *' if others feel they're important to maintain.

**Comment by rljacob** [comment]
Here are the ones that will be changed:
```
grep -r 'import \*' * | grep -v standard_module_setup | grep -v standard_script_setup
scripts/Tools/case.build:from CIME.test_status     import *
scripts/Tools/save_provenance:from CIME.provenance import *
scripts/Tools/cs_status:from CIME.test_status import *
scripts/Tools/pointclm/pointCLM.py:#from Numeric import *
scripts/Tools/pointclm/post_process.py:#from Numeric import *
tools/unit_testing/python/test_environment.py:from environment import *
tools/unit_testing/run_tests.py:from xml_test_list import *
utils/python/tests/scripts_regression_tests.py:from CIME.test_status import *
utils/python/CIME/XML/build.py:from CIME.macros_writers import *
utils/python/CIME/SystemTests/system_tests_common.py:from CIME.test_status import *
utils/python/CIME/SystemTests/system_tests_common.py:from CIME.hist_utils import *
utils/python/CIME/test_scheduler.py:from CIME.test_status import *
utils/python/CIME/case_setup.py:from CIME.test_status       import *
utils/python/CIME/case_test.py:from CIME.SystemTests.system_tests_common import *
utils/python/CIME/bless_test_results.py:from CIME.test_status import *
utils/python/CIME/wait_for_tests.py:from CIME.test_status import *
utils/python/CIME/compare_test_results.py:from CIME.test_status import *

```

**Comment by billsacks** [comment]
(I will note, though, that it was precisely the wildcard imports from standard_module_setup that caused me problems in first trying to understand some of the cime python code - such as where 'expect' was coming from.)

**Comment by jgfouca** [comment]
Thanks @billsacks  for testing that; it's good to know pylint will save us from ourselves :)

@jedwards4b will investigate if the standard_setup stuff we're doing is really necessary; this will happen after 5.1 release.

I feel strongly that I don't want to see 100 lines of imports when I open up our code, so for CIME imports I'm recommending this format
```
from CIME.utils import X, Y, Z
```
For items from the python standard library:
```
import os, sys, re
```

**Comment by rljacob** [comment]
I think in the call we decided to do both options 1 and 4.

**Comment by gold2718** [comment]
I just want to note that the large exception carved out for standard_module_setup and standard_script_setup raises the learning bar for anyone who might want to collaborate with or work on CIME in the future. It also means that the in-code documentation of the standard python libraries is _better_ than internal CIME code! This seems to be a trade-off between short-term gain (typing slightly fewer characters on some lines of code) versus less long term readability which increases code maintenance costs.

**Comment by jedwards4b** [comment]
The intent of those standard files was to avoid having to duplicate a section of boilerplate code in every file along with the inevitable result that eventually that boiler plate code begins to diverge from one file to another.   You can probably avoid this by providing some documentation for developers regarding the standard that we would like to maintain, but I would submit that this is no different than providing documentation on the usage of the standard files.   I think that the same functionality can be handled in the __init__.py file and I will look into moving it there but I don't think that does anything to address your claim of obfuscation.

**Comment by gold2718** [comment]
Jim, Everything you said also applies to the python standard libraries. And yet, the group decided to maintain documentation of that usage (e.g., by using `import os` instead of `from os import *`). Why are the CIME internal libraries treated with less care than the standard python libraries?
