### ISSUE TITLE
TOTALPES value computed incorrectly on hyperthread capable platforms

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#518]
Many HPC systems are hyperthread capable and can overload the number of tasks x threads per
node by factors of 2x or 4x or more.   The current setting of TOTALPES in cime fails to take this into account which results in an incorrect Model Cost estimate.   For example on yellowstone for a particular F case I use 960 tasks and 2 threads per task.  I have set the ptile to use 15 tasks per node so the number of tasks to be used for the cost estimate should be 1024.   Currently the 
TOTALPES value in cime for this run is 1920 and COST_PES=0.    They should be 960 and 1024.

**Comment by jgfouca** [comment]
This is going to involve that TaskMaker code that none of us want to touch.

**Comment by jedwards4b** [comment]
I think most of the functonality of task_maker should be moved to env_mach_pes.py and be broken into smaller subroutines - but this is a task beyond the cime5.1 milestone, for 5.1 I think I have a workaround for this problem, it involves making a special case for yellowstone where by default we use 15 of the 16 tasks per node.
