### ISSUE TITLE
create_test --test-id [arg] needs to error if a component name is included in the arg string

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#523]
If the create_test --test-id argument contains the name of a model component that is also listed in the config_archive.xml, then the st_archive will incorrectly move/copy files from the rundir to the DOUT_S_ROOT location because of the regex pattern matching. 

For example,
execca ./create_test --test-id b01_mosart_nomods ERR.f19_g16.B1850.yellowstone_intel.allactive-defaultio

Creates $CASE = b01_mosart_nomods ERR.f19_g16.B1850.yellowstone_intel.allactive-defaultio.b01_mosart_nomods

When the st_archive runs, it matches on the XML comp_archive_spec compname="mosart" for all
case files and incorrectly copies them all to $DOUT_S_ROOT/archive/$CASE/rof/hist. 

This issue maybe addressed by #500 which will include better pattern matching based on component output filename settings.

**Comment by rljacob** [comment]
Jim says better pattern matching in hist_utils could fix this.
