### ISSUE TITLE
cime5 no longer validates MPILIB from list of MPILIBS in config_machines

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#524]
This is in cime5.0.9, after setting up a case, I can freely change MPILIB to any string I want. It does NOT validate if it's a valid setting by comparing to the list of MPILIBS in config_machines.xml. If I set it to a bad value, the build will likely fail, but in a non-obvious way that doesn't make it easy to realize that the MPILIB setting is the problem.

**Comment by jedwards4b** [comment]
This wouldn't be hard to fix but the MPILIB is validated at the time of create_newcase and I just wonder how much we need to protect the user from themselves?  There are hundreds of variables in the model and we don't know the allowed values for many of them.

**Comment by rljacob** [comment]
Erik, you're talking about using xmlchange after create_newcase?  Did you used to get an error message?

**Comment by ekluzek** [comment]
Yes using xmlchange. I thought cime4 gave an error, but I checked it again and it doesn't. It does keep the list of valid MPILIBS so it could've checked, and the list makes it easier for the user to make sure they are doing the right thing. I thought the reason for keeping the list in cime4 was to validate, but it turns out that's not the case.

So I'm ok with dropping this since cime4 didn't validate either.
