### ISSUE TITLE
Remove PEA from cime_developer

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#527]
cime_developer should run everywhere.
Not everywhere has mpi-serial
so remove PEA.

**Comment by jedwards4b** [comment]
I don't think that we should remove this test from the suite because a few platforms don't support it, perhaps we can skip the test on those platforms?

**Comment by rljacob** [comment]
"cime_developer should run everywhere"  or its not a good developer test suite.  Maybe PEA can be modified to use the default mpi library if mpi-serial is not available.

**Comment by jedwards4b** [comment]
PEA is explicitly a comparison of mpi-serial to mpi build it doesn't make any sense for it to use the default mpi library.

**Comment by rljacob** [comment]
Ok.  Then it should be removed.  For porting, cime_developer is also the suite that MUST pass to verify you've ported CIME correctly.  But we don't want to force people to get mpi-serial working.

**Comment by jgfouca** [comment]
@rljacob as best as I can tell, there was never a PEA test in cime_developer. Did you mean acme_developer?

**Comment by rljacob** [comment]
Sorry it wasn't PEA. It was SMS_D_Ln9_Mmpi-serial.f19_g16_rx1.A.

**Comment by jgfouca** [comment]
Looks like @jedwards4b already did this.
