### ISSUE TITLE
Is 'gmake' required?

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#528]
Tests on compute001.mcs.anl.gov are failing because 'gmake' is not found, but should it be checking for 'gmake' or for the value in the machine config file tag ```<GMAKE>make</GMAKE>```? 
Will not having 'gmake' cause problems elsewhere?

I know there are ways to work around this, but then what is the point of that tag?

**Comment by rljacob** [comment]
my opinion:  An executable called "gmake" should not be required.   On most Linux systems, The GNU version of make is just called "make" and a link to it called "gmake" doesn't always exist.

**Comment by jedwards4b** [comment]
It should be checking for the value in <GMAKE> .  We have tried to eliminate any cases not using that value but there may still be one or two around and they should be considered bugs.   Note that the Makefile's do use some gnu make extensions so that even if <GMAKE>make</GMAKE> is used throughout the code there may still be problems in the build if you are not using a gnu compatible make utility.

**Comment by rljacob** [comment]
So GMAKE really should be the GNU version of make?

**Comment by sarich** [comment]
OK, I'm going to change the test to check for <GMAKE> if it's there, otherwise use 'gmake'.

**Comment by jedwards4b** [comment]
I think that you misunderstood - we should always be using whatever is defined in the ```<GMAKE>``` field in xml and not hardcoding the name of a make utility anywhere.

**Comment by sarich** [comment]
So GMAKE is a required tag?

**Comment by jedwards4b** [comment]
Yes it's required.

**Comment by sarich** [comment]
There is only 1 entry in cesm/machines/config_machines.xml, and 0 in acme/machines/config_machines.xml that define this value

**Comment by rljacob** [comment]
So we can't use GMAKE everywhere in CIME until all machines define it.  In that case, maybe just replace the hardcoded use of "gmake" with "make" until GMAKE is really defined for all machines.

**Comment by gold2718** [comment]
Or how about just adding a <GMAKE>gmake</GMAKE> tag to every machine that has worked until now since they probably have gmake (probably as a link to make)?

**Comment by jedwards4b** [comment]
Oh - the ```<GMAKE>``` field needs to be in env_build.xml but it defaults to gmake so
there is no need to define it for each machine.  Sorry for the confusion.

**Comment by sarich** [comment]
So it's ok for the regression test to check for the config_machines.xml entry <GMAKE>, and use 'gmake' as the default if it isn't found?
