### ISSUE TITLE
scripts_regression_tests cmake tests fail on corip1

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#540]
cmake tests in scripts_regression_tests complain about invalid c compiler.

**Comment by jedwards4b** [comment]
A possible solution to this is to add CMAKE_COMPILER_WORKS flags to avoid testing the compiler.

**Comment by rljacob** [comment]
Telecon discussion:  This has been fixed.  Cmake needs a special flag for cray systems.  cmake_system_name=catamount.

**Comment by rljacob** [comment]
Also introduced option to turn off cmake test.
