### ISSUE TITLE
Overall status in TestStatus report for a test should not change for nl compare or mem-leak

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#560]
Right now the Overall status in the TestStatus file for a test can be set to NLFAIL if namelists compare differently -- even if the history files are identical for the case. The Overall status is useful  to grep for to see a summary of all of the tests, but some fails aren't so useful to look at. Typically if the namelists are different, but the history files are identical -- you want to call that a PASS. If you want to see which tests have different namelists then you'll want to dig into the details. But, the most useful category for the Overall behavior when namelists are different, but history files are identical is that it was a PASS.

Similarly, the memleak tests aren't necessarily reliable enough to have them trigger a Overall FAIL. If someone wants to figure out which tests have a memory leak they should look into the details for the test. And TPUTCOMP applies as well.

So I'd like to see that the Overall status could be reported as:

FAIL -- build, run, or test functionality fail
PEND - Test hasn't run yet.
PASS - everything worked, and if baseline comparison's were done they passed as well
             (NLCOMP, TPUTCOMP and MEMLEAK fails could still be reported as a PASS)
DIFF -- everything worked (so functionally a PASS), but one or more of the baseline comparison's  
             failed.

@bandre-ucar @jedwards4b @mvertens @billsacks

**Comment by ekluzek** [comment]
I should note that PEND is a valid overall status, as well before tests have run. cime4 also put tests that failed midstream as RUN (possibly cime5 has this status as well) that would be a valid overall status as well.

**Comment by jgfouca** [comment]
@ekluzek I believe most if not all of your requests have been handled in other issues/PRs. Please reopen this issue if that's not the case.
