### ISSUE TITLE
Want cs.status output to include test name and other information from TestStatus file

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#564]
The TestStatus file gives the test name on each line of output. We'd really like the cs.status output to maintain this. In addition, there is other information in comments in the TestStatus output that should be maintained in the cs.status output - see #563 .

Essentially, if the cs.status output was the concatenation of all relevant TestStatus files, that would address this issue.

tagging @ekluzek @mvertens

**Comment by billsacks** [comment]
also tagging @fischer-ncar

**Comment by billsacks** [comment]
One possible way to accomplish this goal would be to refactor test_status.py so that the call from cs.status uses the same code as TestStatus.flush. Specifically, I could imagine having a TestStatus.\_\_str\_\_ method that does most of the work that is currently in TestStatus.flush. Then TestStatus.flush would make use of this string conversion method, and cs.status would too.

See also https://github.com/ESMCI/cime/issues/429#issuecomment-240903457

**Comment by fischer-ncar** [comment]
Fixed in PR #570
