### ISSUE TITLE
Some build/run report as fail, but work on resubmission

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#572]
This is with cime5.1.1. And it's really just a placeholder if more information is forthcoming. Since, I can't seem to see what is happening, nor necessarily able to reproduce it, I don't expect anyone to solve it. But, I want to document it as something annoying.

Submitting the aux_clm40/45 test suites on hobart I got two tests that reported a fail in the build, but then worked fine when build/run again. And one that reported a fail on the run, but worked fine when I built/run again.

The cases are:

SMS_D_Ld1_Mmpi-serial.1x1_mexicocityMEX.I.hobart_nag.GC.20160921_155208
ERS_D_Mmpi-serial_Ld5.1x1_brazil.ICLM45ED.hobart_nag.clm-edTest.GC.20160921_155208
ERS_D_Ld5_Mmpi-serial.1x1_mexicocityMEX.I1PTCLM45.hobart_nag.clm-default.GC.20160921_155208

@billsacks @bandre-ucar

**Comment by jedwards4b** [comment]
There is a bug, now fixed on master and on maint-cime5.1 (the 5.1 maintenance branch) in which check_input_data would download data missing from inputdata but then fail anyway - this happens in case.build, but when you run case.build again the data is there and so it works fine.   This sounds very much like what you are reporting.

**Comment by ekluzek** [comment]
Hi Jim. That's a possibility, so I checked. It shouldn't have needed to download any data, but I made sure no new data appeared in DIN_LOC_ROOT, and nothing had. So it's not that.

There's also a list of 85 tests on yellowstone that didn't go the first time either. I'm now in the process of rebuilding and resubmitting, and we'll see if they act the same.

**Comment by jedwards4b** [comment]
CISL introduced a problem on yellowstone for a couple of hours yesterday afternoon that could have caused some failures.

**Comment by billsacks** [comment]
Closing this issue. Reopen if you think it's still a problem.
