### ISSUE TITLE
Test build fails seemingly due to a race condition in the sharedlib build

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#581]
In Erik's run of the aux_clm test suites with cime5.1.1, we noticed a failure in this test:

SMS_Ld1_Mmpi-serial.f45_f45.I.yellowstone_intel.clm-40ptsRLA.GC.20160922_231048

This failed in the csm_share build with:

```
ifort: error #10236: File not found:  'shr_frz_mod.F90'
ifort: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance
ifort: command line error: no files specified; for help type "ifort -help"
/glade/p/work/erik/clm_esmciport/cime/scripts/SMS_Ld1_Mmpi-serial.f45_f45.I.yellowstone_intel.clm-40ptsRLA.GC.20160922_231048/Tools/Makefile:747: recipe for target 'shr_frz_mod.o' failed
gmake: *** [shr_frz_mod.o] Error 1
gmake: *** Waiting for unfinished jobs....
ifort: error #10236: File not found:  'shr_assert_mod.F90'
ifort: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance
ifort: command line error: no files specified; for help type "ifort -help"
/glade/p/work/erik/clm_esmciport/cime/scripts/SMS_Ld1_Mmpi-serial.f45_f45.I.yellowstone_intel.clm-40ptsRLA.GC.20160922_231048/Tools/Makefile:747: recipe for target 'shr_assert_mod.o' failed
gmake: *** [shr_assert_mod.o] Error 1
gmake  complib -j 8 MODEL=csm_share COMPLIB=libcsm_share.a USER_CPPDEFS="  -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WA\
V=1 -DNUM_COMP_INST_ROF=1 -DNUM_COMP_INST_ESP=1" -f /glade/p/work/erik/clm_esmciport/cime/scripts/SMS_Ld1_Mmpi-serial.f45_f45.I.yellowstone_intel.clm-40ptsRLA.GC.20160922_231048/Tools/Makefile  returned \
non-zero exit status 2
```

This seemed weird, since there are other, nearly identical tests in the test suite that passed.

When I looked in `/glade/p/work/erik/clm_esmciport/cime/scripts/sharedlibroot.20160922_231048/intel/mpi-serial/nodebug/nothreads` I saw:

```
-rw-r--r-- 1 erik cgdtss 112264 Sep 23 00:16 csm_share.bldlog.160923-001545
-rw-r--r-- 1 erik cgdtss  54981 Sep 23 00:16 csm_share.bldlog.160923-001615
```

suggesting that two tests' builds were happening basically simultaneously. This makes me suspect a race condition in the sharedlib build when building test suites.

Incidentally: Erik ran this test as a single test, and it passed.

Tagging @ekluzek @jedwards4b @mvertens @jgfouca

**Comment by jedwards4b** [comment]
Hi Bill, can you tell if these are both trying to build the same library or if they point to different paths?

**Comment by billsacks** [comment]
@jedwards4b - I'm not sure what you mean. I assumed that, since they both appear in intel/mpi-serial/nodebug/nothreads, that they're trying to build the same library. Is that not necessarily the case?

The 160923-001615 time-date-stamp was produced by the test that failed:

```
SMS_Ld1_Mmpi-serial.f45_f45.I.yellowstone_intel.clm-40ptsRLA.GC.20160922_231048
```

(I know that because that bldlog is referenced in that test's TestStatus.log file.)

I see the 160923-001615 time-date-stamp on this file:

```
./SMS_Ld1_Mmpi-serial.1x1_mexicocityMEX.I1PTCLM45.yellowstone_intel.clm-default.GC.20160922_231048/bld/lnd.bldlog.160923-001545
```

which maybe means that that's the test that was trying to build csm_share with that same date-time-stamp?

**Comment by billsacks** [comment]
Ah... upon further investigation, I believe this problem arose from the fact that Erik ran two ./create_test instances at once, which used the same testid - one for the aux_clm40 test list and one for the aux_clm45 test list. @ekluzek can you confirm this? If so, I don't think the scripts can be expected to do anything about that, since the two create_test instances don't know about each other. Instead, this points to the importance of using different testids for each create_test instantiation -- which I believe was important in cime4 as well.

So, if @ekluzek confirms that this is what happened, then I'd say we can close this issue.

**Comment by ekluzek** [comment]
Hi Bill

Yes, I think you are correct. I let it use the default test-id which is
based on the date, and submitted each with a script right after each other.
I was surprised that it combined them together to one test-id name, I
hadn't seen that before.

So I just need to add a sleep between each submission, so the testids end
up being different.

*Erik Kluzek, (CGD at NCAR)*

*National Center for Atmospheric Research*

*Boulder CO, *

*(off) (303)497-1326 (fax) (303)497-1348*

*(skype) ekluzek    (cell) (303)859-0183*

*Pronouns: he/his/him*

*------------------ Home page ------------------------*

*          http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*

*          https://staff.ucar.edu/users/erik
<https://staff.ucar.edu/users/erik>*

*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*

**Comment by billsacks** [comment]
@ekluzek : Adding a sleep isn't always sufficient on yellowstone, where you submit these jobs to the caldera queue: Even if you submit them a few seconds apart, they can end up starting at the same time.

What I do is this (bash syntax assumed):

```
export testid=`date +%m%d-%H%M`
./create_test ... --test-id ${testid}.${category:7:2}.${compiler:0:1}
```

then you can run that command with various categories and compilers and get a different _descriptive_ testid for each one. The substrings get you things like 40 vs 45 (for aux_clm40 vs aux_clm45) and the first letter of the compiler. (I had to shorten the full strings because, at least at one point, using the whole category & compiler could lead to too-long case names, leading to crashes.)

**Comment by billsacks** [comment]
Closing this, because I don't think it's actually a problem with cime.

Well: I guess it would be nice if there were more error-checking to try to ensure that you don't run two test suites in the same location with the same test id... but that might be hard to check robustly. Another option would be to put some (short) random string at the end of the auto-created testid to try to make it unique. But these are all topics for a separate issue....
