### ISSUE TITLE
create_test should prevent running two test suites in the same directory with the same testid

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#582]
Inspired by #581 : It would be nice if create_test attempted to detect when you were running multiple create_test instances in the same directory with the same testid. Doing so can create subtle problems with your test suites.

This is likely hard (or impossible) to catch 100% of the time, but I think we could come up with a solution that works 99.something% of the time, which is better than nothing.

For example, a quick and dirty solution could be for create_test to create some empty file whose name contains the given testid... this would be done right at the beginning of create_test. But, before creating this file, it would check to see if a file with this name already appears, and if so, abort. This could still be prone to race conditions, but they should be significantly less common than how often you accidentally get the same testid for two runs of create_test.

Tagging @ekluzek

**Comment by jedwards4b** [comment]
This is a best practice issue and I don't think that it's worthy of a modification in the code.

**Comment by billsacks** [comment]
I'd accept that if the only way this problem could occur is via manually-specified testids. But this problem most often appears due to the auto-generated testid: It's common practice (at least for CLM testing) to fire off multiple test suites at once, so if you use the auto-generated testid, it's easy to get collisions.

Based on that argument: Maybe the solution here is to change the auto-generated testid to add a few random characters at the end?

**Comment by rljacob** [comment]
I can see the merits of making the auto-generated id more unique.  But...if your use mode is to "fire off multiple test suites at once" then its your job to specify unique ids in each of those and not rely on the auto-generated ones.

**Comment by ekluzek** [comment]
Personally in cime4 I used to do one create_test submission, because it was able to handle that.  I used regular expression matching for categories and compilers. Other's did multiple submissions, because it was more efficient. Currently in cime5.1.1 it can't handle doing a single submission because of issue #294 (which looks like has been merged to master). So I have to do multiple submissions. I think in cime5 it does a better job of doing the builds so doing one submission makes more sense.

**Comment by billsacks** [comment]
To be clear: I'm not thinking about myself here: I have a workflow that uses multiple, unique test ids. I'm thinking about less experienced users. We have a hard enough time getting them to run test suites at all, and I feel that it's our responsibility to make this Just Work, to lower the burden we place on them.

I'm hearing a lot of responses along the lines of "it's the user's responsibility to ensure that unique test ids are used for each run of the test suite, and this doesn't justify any additional code on our part". If everyone else feels that way, I'll defer to your opinions. But I would ask that we then at least document this requirement well. For example, the documentation of `--test-id` in `./create_test --help` does not make any mention of the test IDs being unique. I don't think it's fair to say that less experienced users should just intuitively know that requirement.

**Comment by jgfouca** [comment]
@billsacks I like the idea of adding a couple random characters to the test id.

**Comment by jedwards4b** [comment]
I did this in PR 590
