### ISSUE TITLE
Should tests' hist_utils move rather than copying history files?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#583]
I noticed that `hist_utils.py : move` actually copies rather than moving the last set of history files (despite the name). For tests where two runs are done out of the same run directory (such as ERS), this can cause it to look like the second run produced a history file when it really did not. 

For example, imagine that the first run produced a history file named `foo.h.0001-01.nc` - and this was the only history file produced for the 'foo' component. Then `move` would copy this to `foo.h.0001-01.nc.base`. Now imagine that the second run failed to produce any history files. hist_utils would look for foo's history files in the run directory, find the still-existing `foo.h.0001-01.nc` (which was produced by the first run), and copy it to `foo.h.0001-01.nc.rest` (or whatever suffix is used for the second run). Then, of course the history file comparison would match, because this is really the same file as the .base file.

I think the only thing needed to make the tests more robust would be to change `shutil.copy` to `os.rename` in the `move` function. However, to avoid confusion, an ideal behavior to me would be for `move` to move _all_ history files (i.e., everything found by `_get_all_hist_files`) to some subdirectory (e.g., `"saved_history_files_%s"%suffix`), and/or append the suffix to the end of all history files. Then if a second run is done out of the same case directory, there will be no possible confusion as to which history files were produced by each run. Without the second piece, I think we could get confusing results, but probably wouldn't get any accidental passes. For example, if the first run produced `foo.h.0001-01.nc` and `foo.h.0001-02.nc` and the second run produced no history files, then, with `shutil.copy` changed to `os.rename`, we'd get `foo.h.0001-02.nc.base` and `foo.h.0001-01.nc.rest`. There shouldn't be any `.rest` file from this run, so that's confusing - but at least it would still be reported as a failure.

However, looking back at the cime4 version of `component_compare_move.sh`, I see that there was the same behavior / misnomer, along with this comment from @bandre-ucar :

```
		# FIXME(bja, 2014-11) temp change to test if cp fixes the
		# problem with mfilt in restart tests. If it does, then
		# rename this script to component_compare_copy.sh !
		/bin/cp "$test_hist" "$test_hist_suffix"
```

@bandre-ucar or @mvertens - can you remember the details of the problem that prompted the change to cp rather than mv?

If there is a legitimate reason why this needs to be a copy rather than a move (as suggested by the above comment from bja), then this could cause problems for the clone-based test infrastructure (SystemTestCompareTwo), if we switch restart tests like ERP to use this infrastructure: For these tests, there is a clear separation between the files produced by each run, so the behavior is similar to what I describe as an "ideal behavior" above, and would presumably trigger whatever problem prompted bja to make the switch to /bin/cp.

Tagging @mvertens @jedwards4b @jgfouca @bandre-ucar

**Comment by billsacks** [comment]
To clarify what I mean about this:

> However, to avoid confusion, an ideal behavior to me would be for move to move all history files (i.e., everything found by _get_all_hist_files) to some subdirectory (e.g., "saved_history_files_%s"%suffix), and/or append the suffix to the end of all history files. 

I still imagine that _comparisons_ would just be done using the last history file from each component (as is the current behavior), so it's possible that some other code would have to be tweaked a bit to handle the fact that we'd now have a whole bunch of `*.base` files (or whatever), but still just want to do comparisons using the last from each component. (Or maybe the logic already handles that... I haven't looked.)

**Comment by mvertens** [comment]
The reason you need to copy rather than move is if you have a history file
that will need to continue to be filled on the next phase (say a restart
run). If this is not the case, then a move is fine. Maybe the best solution
would be to have the option to either copy or move based as an input
argument that each test can set separately.

**Comment by billsacks** [comment]
@mvertens that's a very good point. Now I understand.

> Maybe the best solution
would be to have the option to either copy or move based as an input
argument that each test can set separately.

Since we want to move most of the non-restart tests to the SystemTestCompareTwo infrastructure, this is probably a moot point.

So maybe the solution here is to just rename the `move` function to `copy`, and to add a comment describing the need for copying, similar to Mariana's post? That would help prevent this question from coming up again in the future. (Otherwise, I'm sure I'll ask it again a year from now once I've forgotten this discussion.)

Do others feel like that's a reasonable solution?

**Comment by jgfouca** [comment]
@billsacks yes, i like that solution

**Comment by billsacks** [comment]
Okay, I'll make this change soon.
