### ISSUE TITLE
More memleak false positives

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#588]
This test:

```
ERS_Ly5.T31_g37_gl5.IGCLM45.yellowstone_intel.clm-glcMEC_long
```

generates a memleak false positive. In the 2-year restart portion of the run (which is the portion tested for memleak), there is a true, small increase of about 0.1 MB per day for the first few months (but I don't think that alone would have triggered a failure). Then there is a big jump at the start of the second year:

```
FAIL ERS_Ly5.T31_g37_gl5.IGCLM45.yellowstone_intel.clm-glcMEC_long MEMLEAK memleak detected, memory went from 533.950000 to 620.100000 in 19999 days
```

```
 tStamp_write: model date =    41230       0 wall clock = 2016-09-26 13:49:09 avg dt =     1.10 dt =     1.05
 memory_write: model date =    41230       0 memory =     549.67 MB (highwater)       2426.76 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC WAV ESP)
 tStamp_write: model date =    41231       0 wall clock = 2016-09-26 13:49:10 avg dt =     1.10 dt =     1.02
 memory_write: model date =    41231       0 memory =     549.67 MB (highwater)       2426.76 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC WAV ESP)
 tStamp_write: model date =    50101       0 wall clock = 2016-09-26 13:49:19 avg dt =     1.12 dt =     8.77
 memory_write: model date =    50101       0 memory =     619.98 MB (highwater)       2446.15 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC WAV ESP)
 tStamp_write: model date =    50102       0 wall clock = 2016-09-26 13:49:20 avg dt =     1.12 dt =     1.02
 memory_write: model date =    50102       0 memory =     619.98 MB (highwater)       2446.15 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC WAV ESP)
```

The full, 5-year run also has the increase at the start of year 2, but then memory use stays roughly constant after that (other than an increase when the restart files are written).

This test uses CISM, which only runs once per year. So this increase in memory use at the start of the second year (really, the very end of the first year) is expected.

I'm not quite sure what the ideal solution is here. Off the top of my head, I can see two:

1. Quick & dirty: Allow tests to specify that they expect a (false) memleak failure, via some xml entry, and thus don't run the memory check on those tests.

2. Improve the heuristics used in these memleak tests. I'm not quite sure what would be the best way to code this, though. I know that you should ignore a jump at the end of the first year / beginning of the second year in a run that uses CISM, but how should we specify that in a general way? e.g., Should each component somehow specify the time frequency at which it does its work, and then ignore memory jumps at the first instance of each of those frequencies? Note that, for CISM, this differs from GLC_NCPL (generally 1 day), which complicates things.

**Comment by jedwards4b** [comment]
What's wrong with the status quo - the test has alerted you to a potential memory leak issue and you look at it and decide that it's expected for this particular test?   I don't think that either of your solutions is an improvement on that.

**Comment by gold2718** [comment]
How about a variant of your first option? After examining the failure, the run, and the code, we could decide the number is acceptable (or necessary as in the CISM case) and add an expected MEMLEAK amount. After that, it would only trigger a failure if that number grew.

**Comment by billsacks** [comment]
> What's wrong with the status quo

The problem is that it forces me to look at this every time I run the test suite. I work hard to try to keep the aux_glc test suite clean (no failures); if I can't do that, then I'll need to develop a system to keep track of which tests are expected to fail. Whenever I run the test suite, I won't be able to simply 'grep -v PASS' to see if everything passed; instead, I'll need to cross-check the failures with the expected failure list, making the checking of the test suite take O(minutes) rather than O(seconds). Furthermore, I'll need to remember to communicate this list of expected failures to anyone else who might want to run the aux_glc test suite. At some point (say, when the list of expected failures grows to 3 or 4 memleak failures rather than just 1 or 2), I'll decide this isn't worth the effort, and will just filter out all memleak failures... bringing us back to square one.

Incidentally, an acceptable alternative solution would be a more general mechanism for recording and filtering out expected failures, as @bandre-ucar has been proposing for a while.

I should note that I don't feel a need for this issue to be resolved immediately, particularly since I can't think of a clean and easy solution. I just wanted to open this as a way of noting that I feel this should be addressed at some point.

> How about a variant of your first option? After examining the failure, the run, and the code, we could decide the number is acceptable (or necessary as in the CISM case) and add an expected MEMLEAK amount. After that, it would only trigger a failure if that number grew.

This seems like it could be a good solution, as long as there is enough of a buffer built in so that memleak tests don't require too much babysitting.

**Comment by billsacks** [comment]
I also notice a memleak failures for at least one hobart_nag debug test, where roughly equivalent yellowstone tests show no memleak behavior - specifically, `SMS_D_P24x1_Ld5.f10_f10.ICRUCLM50BGCCROP.hobart_nag.clm-irrig_spunup` (compared with the initial run of `ERP_D_P15x2_Ld5.f10_f10.ICRUCLM50BGCCROP.yellowstone_intel.clm-irrig_spunup`).

It's possible that this is a true memory leak, but I'm not sure if it's worth spending time trying to track down a memory leak that only appears with nag in debug mode, and not with our production compilers. So this further suggests the need to mark tests with expected memleak amounts, or some similar mechanism. 

As I think about this more, I'm liking @gold2718 's suggestion:

> After examining the failure, the run, and the code, we could decide the number is acceptable (or necessary as in the CISM case) and add an expected MEMLEAK amount. After that, it would only trigger a failure if that number grew.

**Comment by jedwards4b** [comment]
It is certainly possible to do this with an additional field in the testlist.xml options section.

**Comment by billsacks** [comment]
I just ran the CLM test suite. This generates a LOT of memleak results. To maintain my sanity, I'm going to have to start ignoring the memleak results entirely until some "expected failure" mechanism is put in place for these.

Also cc'ing @ekluzek

**Comment by mvertens** [comment]
I agree with Bill. Have a slew of memory leak failures at this point just
adds an enormous amount of overhead and frustration to tracking testing
output. As a very short term fix can we really increase the threshold for
reporting a failure so that we can proceed to a more robust solution
without having to continually track these failures.

**Comment by jedwards4b** [comment]
That amounts to turning off the test.   I'll try to add a field to the testlist xml file today so that this can be tuned to individual cases.

**Comment by billsacks** [comment]
>  I'll try to add a field to the testlist xml file today so that this can be tuned to individual cases.

One challenge I foresee with this is that this metadata will need to be preserved when translating to and from the flat text-based testlist. (Since that's how we typically modify test lists.) Perhaps this calls for the rework of the xml-based testlist that Jay and I discussed a while ago, which would simplify the xml format sufficiently that there would no longer be a need for a text-based testlist. I can discuss that with you if you want.

I'm not in a rush for this - personally, I'm fine with simply ignoring MEMLEAK results for the time being. So, for example, if it makes the most sense to wait to do this until we have time to rework the format of the xml-based test list, that's fine with me.

**Comment by jedwards4b** [comment]
I was not aware of a plan to reformat testlists - this is a bigger project than I want to take on at the moment.   Perhaps this proposal can be outlined in a separate issue.

**Comment by billsacks** [comment]
Looking back at this, I remembered that you (or someone) already have reformatted the testlist xml file - I had forgotten because this was done in a backwards-compatible way, so that the component testlist xml files are still in the old format. I see some possible issues with the current format, including issues with how to mark expected failures / expected memleak results with the current format. I'll open a separate issue to discuss those.

**Comment by billsacks** [comment]
Okay, Jim E corrected me to show that this new feature actually can fit in cleanly to the new testlist format - that this format is actually more flexible than I had thought. So the idea of adding a new field to the testlist xml sounds good to me.
