### ISSUE TITLE
version(s) of timing library in CIME

### ISSUE THREAD

**Issue by worleyph** [ESMCI/cime#59]
Based on the https://github.com/ESMCI/cime branch, it appears that the
decision has been made to use only the ACME version of the timing
library in the shared CIME version. I would rather that both versions be
available, if possible.

I need the ACME version to do my current job. As part of this I also
need that everyone else in ACME use it. Finally, I need to be able to
continue to modify the timing library as necessary for the needs of the
project, and then push this out to others in the project. However, this
is all very project specific, and seems inappropriate for the
coordinated management being discussed and impolite to impose on the
CESM and others.

For example, my latest "additions" were just conveniences, an option to
measure timing overhead directly (adding yet more overhead) and an
option to add the detail level to timer names so that I could determine
how to modify t_adj_detail calls in the code, neither of which will ever
be used during production runs. I made the mistake in the first case of
adding this option to the env_run.xml file, which introduces a conflict
with the CESM version of the timing library, but this is completely
unnecessary. Both options can simply be included in user_nl_cpl when
needed.

So, other than this one example, I have been managing to keep the two
APIs the same. And the differences in the two GetTiming scripts is very
small, and maintaining both versions should not be difficult.

To repeat, I would be much more comfortable if we could support both the
latest and greatest Jim Rosinski-based timing library and the current,
still evolving, ACME timing library. Is this possible without adding
extra work? Coordination would then simply be at the level of
maintaining compatible APIs.

This all assumes that CSEG has been happy with using the more 
recent versions of GPTL, and with treating GPTL as an external library.

**Comment by mvertens** [comment]
Sorry for the delay in my response. The working group meetings unfortunately made this fall through the cracks. 
I feel at this point that this would be a lot of additional work right now. I am happy to take the ACME GPTL now and feel that this would address all of the current CSEG needs. Can we revisit having both versions out there once a lot of the other high priority issues are resolved?

**Comment by worleyph** [comment]
> Can we revisit having both versions out there once a lot of the other high priority issues are resolved?

Of course. Thank you for the reply.
