### ISSUE TITLE
Bug in hist_utils.py causes tests to fail when just the baselines are missing

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#599]
TestStatus is reporting that the RUN phase is failing when it's just the baselines missing.
Looks like I made a typo in hist_utils.py when I added BFAIL to the comment when baselines are missing. @jedwards4b

**Comment by rljacob** [comment]
Which PR introduced this bug?

**Comment by fischer-ncar** [comment]
PR #577 introduced the bug.
