### ISSUE TITLE
build timing library first

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#600]
I like to alter the build order for the shared libs so the timing library is built first.

Its a simpler library then MCT or PIO so it makes more sense to build it first.  Also this allows adding timers to MCT or PIO if one would like to (in a branch).

**Comment by jedwards4b** [comment]
I believe that this should be considered in the context of issue #601

**Comment by rljacob** [comment]
I don't think this needs to be coupled with 601.  The build order is a different decision from which version to build.

**Comment by jedwards4b** [comment]
True but if you decouple you are going to do much of the same work twice.

**Comment by worleyph** [comment]
I found th one-line change that needed to be made in CIME2 to build libgptl first (so that I can use it to look at performanct in MCT), and have been using this for the past few months. It has been VERY convenient.

Looking at CIME5, I can't see where/how to make a similar change. Any guidance?

**Comment by jedwards4b** [comment]
I have this on my todo list for cime5 in combination with splitting the csm_share library up, I should be able to get to it soon.

**Comment by worleyph** [comment]
Well I need it now. Guess that this is not an option. I'll go back to the old way (commenting out all timers in MCT, building, uncommenting, rebuilding.) Sure was simple in CIME2.

**Comment by worleyph** [comment]
I found the location for the change in CIME5, also a one-liner (in cime/utils/python/CIME/build.py). This is all I need. Please do not reprioritize for my sake.

**Comment by jedwards4b** [comment]
#948 fixes this in general.
