### ISSUE TITLE
Update to latest GPTL timing library

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#601]
The current GPTL library used by CIME Is quite out of date and does not support some features such as nested threading.   I believe that this issue and issue #600 should be consider together.
The latest GPTL is available at http://jmrosinski.github.io/GPTL/ and I believe that it should be treated as an external in CIME.

**Comment by jayeshkrishna** [comment]
FYI, There are some changes that @worleyph made to gptl code (cime/share/timing/*) that needs to be ported if we are bringing in a new version of the lib.

**Comment by rljacob** [comment]
Yes diffs between our timing library and GPTL master will have to be reconciled before we can switch to main GPTL.
