### ISSUE TITLE
Want more user-friendly way to retrieve PE settings for a user compset

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#608]
This is an enhancement that I'd like to see by the cesm2 release, but is not critical before then.

In order to specify a user-compset, you currently need to point to the xml file containing the PE settings you want to use (using the --pesfile argument to create_newcase). This requires expert knowledge of:
1. For a given compset, which component will contain the xml file you need
2. The path to the given xml file

I feel that users should not be required to know either of these things: the scripts should be able to figure this out for you. We have rules for where to find the appropriate config pes settings, based on what compset you're using. It may not be trivial to code up these rules, but I feel that it will be easier to do that than to try to train all CESM2 users on these rules.

This is especially important for CESM2, where we are planning to have very few out-of-the-box compsets, relying much more heavily on user-compsets.

**Comment by ekluzek** [comment]
Agreeing with Bill that this is important. Having to know the specific path for the config_pes.xml is ridiculous and onerous for a new user.

**Comment by billsacks** [comment]
I'm changing this from an enhancement to an issue, because I think it's really an issue that needs to be resolved for cesm2.

**Comment by jedwards4b** [comment]
Please lead me through an example.  How do we determine that the user_compset input is a valid compset and then how do we determine what the principle component of that compset is?

**Comment by mvertens** [comment]
One idea is to have a first pass match list for the principle component - 
- e.g. you have CAM + CLM  + DOCN  then the principle component is CAM
if a match is not found - then the user would be told they have to specify the pes file
thoughts?

**Comment by billsacks** [comment]
@mvertens - yes, I agree with your idea. My conceptual thinking is: What is the process that you or I would currently go through to figure out where to find the pes file for a given user compset? We "just" need to put that process into code. I agree that the first step is to determine the principle component, as you say.

**Comment by rljacob** [comment]
I didn't realize --pesfile had to point to a pre-existing config_pes.xml.   Shouldn't it point to a user-created env_mach_pes.xml?   It doesn't make sense for a user's custom compset to have its pe-layout in the same files as the regular compsets.

**Comment by billsacks** [comment]
@rljacob - In most cases, I think user-defined compsets are just slight one-offs from existing compsets - e.g., using a combination of options for which there is no alias. Since the pe layout is usually more general than that (e.g., all I compsets at a given resolution should use this pe layout), it makes sense to reuse the existing config_pes file.

**Comment by jedwards4b** [comment]
config_pes.xml and env_mach_pes.xml have pretty different formats, but as of
PR #1494 either can be used as a pesfile.

**Comment by rljacob** [comment]
Ok.   What's missing is the compset alias.   CIME finds which component has the compset alias, then it uses the pe-layout pointed to by that component in PES_SPEC_FILE.   The decision of which config_compset to put the alias in is where the "mapping" is done to the "principle component". 
So instead of --pesfile and a full path, change it to --user-component which would be one of "atm", "ocn" etc.   Then it could create_newcase could still get the pe-layout from PES_SPEC_FILE.

**Comment by billsacks** [comment]
@rljacob - your suggestion of having `--user-component` is basically what was done in cime4. That is an improvement, and would be a big step towards an ideal solution. However, I feel that even this tripped people up: Most users are not aware that, for example, if they're doing an F compset, then the pes are set by atm, etc. We as the cime developers know that, so should be able to encode that information as @mvertens suggested.

That said, a partial solution is better than nothing if that's all there's time for.

**Comment by rljacob** [comment]
If the only purpose of --user-component is to find the pe layout, then we could make the option more obvious:  --pes-component ?   If the user really did want to make their own env_mach_pes.xml they could point to that with --pesfile instead.

**Comment by billsacks** [comment]
@rljacob - there used to be a `--user-pes-setby` option that did what you're suggesting. But, particularly given #1525 , I'm thinking we want the scripts to determine this for you. I believe that the same "principal" / "primary" component would be used for both purposes.

**Comment by rljacob** [comment]
Can every possible user compset be mapped uniquely to one primary component? (note using the new name!).    To user knows so give a method for the user to tell CIME.

**Comment by billsacks** [comment]
@rljacob can you clarify what you mean by

> To user knows so give a method for the user to tell CIME.

**Comment by rljacob** [comment]
I meant "the user knows what the primary component should be so bring back --user-pes-setby"

**Comment by billsacks** [comment]
The problem is that most non-expert users do _not_ know this - whereas we do. So my point is that it's likely easier for us to code up the rules that determine the primary component given a compset, rather than leaving this up to the user and then needing to help users set this argument every time they want to create a --user-compset case.

**Comment by jedwards4b** [comment]
I'm working on this issue, I think that the scripts can guess correctly most of the time and users can use the already existing --pesfile when the system cannot guess.   I'll replace principle with primary as part of this change.

**Comment by rljacob** [comment]
If they're using a user compset, they should have enough knowledge to understand primary component.  We should explain it in the user guide.
