### ISSUE TITLE
Change in default test id causes namelist failures

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#611]
Recently, the following change went into `create_test` (line 260):

```
-        args.test_id = CIME.utils.get_timestamp()
+        args.test_id = "%s.%s"%(CIME.utils.get_timestamp(), CIME.utils.id_generator())
```

This changes the case name in a generated test from `TEST.RES.COMPSET.MACH_COMPILER.TESTMODS.ACTION.TESTID` to `TEST.RES.COMPSET.MACH_COMPILER.TESTMODS.ACTION.TESTID.MORETESTID` and the namelist comparison doesn't consider the last `.` as part of the `TESTID`. The result is unexpected failures in the namelist compare, as in the following example (from `SMS.T62_g37.CECO.hobart_nag.pop-ecosys.GC.20160929_143649.t7r5a0`):

```
Differences in namelist 'diagnostics_nml':
  BASE: diag_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.pop.dd'
  COMP: diag_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.t7r5a0.pop.dd'
  BASE: diag_transport_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.pop.dt'
  COMP: diag_transport_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.t7r5a0.pop.dt'
  BASE: diag_velocity_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.pop.dv'
  COMP: diag_velocity_outfile = SMS.T62_g37.CECO.hobart_nag.pop-ecosys.ACTION.TESTID.t7r5a0.pop.dv'
```

A simple fix would be to replace the `.` with `_` (or some other character):

```
-        args.test_id = "%s.%s"%(CIME.utils.get_timestamp(), CIME.utils.id_generator())
+        args.test_id = "%s_%s"%(CIME.utils.get_timestamp(), CIME.utils.id_generator())
```

A more complicated fix would be to make sure the `.MORETESTID` is actually included in `TESTID` when running the namelist comparison.

**Comment by billsacks** [comment]
I'm reopening this issue because this doesn't just apply to the auto-generated testid: This same problem seems to occur for any user-created testid with a '.' in it: With a testid of `0929-0852.45.p`, I'm seeing:

```
Differences in namelist 'seq_infodata_inparm':
  BASE: case_name = 'ERP_Ld5.f10_f10.I1850CLM45BGC.yellowstone_pgi.clm-default.ACTION.TESTID
  COMP: case_name = 'ERP_Ld5.f10_f10.I1850CLM45BGC.yellowstone_pgi.clm-default.ACTION.TESTID.45.p'
```

So, either the namelist comparison should be fixed to handle this, or create_test should check the validity of the test-id, and prevent you from having a '.' in your test id.

**Comment by jedwards4b** [comment]
Here is a list of invalid characters for test-id are you aware of others?  How is this list different for casenames?

r"[\.<>/{}[\]~`@]"
