### ISSUE TITLE
I'd prefer if tests generated a non-zero exit status under fewer conditions

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#614]
I'll preface this by saying that I'm fine with being overruled here if the majority is happy with the current behavior. But I wanted to throw in my $0.02 on this issue.

I use email filters to separate out successful batch jobs from jobs that failed. In the past this has really helped when I run test suites with hundreds of jobs: I basically get instant email notification of any major problems.

In cime4, and for a long time before, a failed test job meant that the run failed. However, with cime5, a failure exit code is generated under many more conditions - such as a failed MEMLEAK test or a failed baseline comparison. This is a problem for me, because MEMLEAK failures are often expected / false positives (at least for now), and baseline comparison failures are often expected. With all of this "noise", the email filter becomes basically useless, and I'm going to end up having to filter out the failed jobs as well to avoid flooding my inbox.

I'd prefer if the behavior were changed back to the cime4 behavior, where a failure (non-zero) exit status were only generated in the case of a definitive problem. A model crash should generate a non-zero exit status, as it did before. I'd also be happy with a failure in the in-test comparison (e.g., base vs. rest) generating a non-zero exit status (though would also be okay if it didn't). But I feel that pieces of the test that are often expected to fail, such as baseline comparisons and (currently) memleak, should generate a zero exit status.

Maybe get_overall_test_status could be used for this exit status, with check_throughput=False, check_memory=False, ignore_namelists=True, ignore_memleak=True; and TEST_DIFF_STATUS would result in a 0 exit status.

**Comment by jgfouca** [comment]
Hi @billsacks , which tool do you want to have a different return code? create_test? case.test?

**Comment by billsacks** [comment]
I guess it's case.test: that's the one that is submitted to the queue for each test, right?

**Comment by jgfouca** [comment]
@billsacks sorry for taking so long to get around this, especially considering how easy it was. PR incoming.
