### ISSUE TITLE
 <!--  <GMAKE>make</GMAKE> <- this doesn't actually work! -->

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#618]
This line is present in several acme/machines and for melvin in cesm/machines. This tag works, the comment is confusing, is there a reason it is still there?

**Comment by rljacob** [comment]
@jedwards4b do you know?

**Comment by jedwards4b** [comment]
I think that at least in the past (and possibly presently) there are some places in the code where make or gmake is hard coded instead of using the GMAKE xml variable.    Maybe someone could take on confirming that these have all been removed and then remove the comment.

**Comment by rljacob** [comment]
Maybe change the comment to "Warning: not all scripts use this variable"
