### ISSUE TITLE
Tweak testlist xml format to facilitate adding test metadata

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#620]
The current testlist xml format looks like this:

```xml
  <test name="ERR_N3" grid="f19_g16" compset="B1850" testmods="allactive/defaultio">
    <machines>
      <machine name="edison" compiler="intel" category="prebeta"/>
      <machine name="yellowstone" compiler="intel" category="prealpha"/>
      <options>
	<option name="wallclock"> 00:20 </option>
      </options>
    </machines>
  </test>
```

(First a word of appreciation: This is a lot nicer than the older testlist xml format, which was heavily nested.)

Currently, this supports the option of wallclock. We have also talked about adding options for expected memleak amounts (in #588 ) and expected failures (in some older discussions). But these latter options - and to some extent the wallclock option - are machine and compiler-specific, so it seems like these need to be nested under machine, not in a separate options block that applies to all machines/compilers.

Also, somewhat related: Can someone document how to do the following with the testlist xml files (or point me to this documentation if it's already documented somewhere):

1. Add a comment that appears when using the tool that queries testlists (i.e., not just a comment in the xml, but something with a special comment tag). I don't see any examples of this in the new xml formatted files. Incidentally, this would be another tag that is good to have nested under a specific machine / compiler / category, because my comments are often specific to that level.

2. Have the exact same test appear in multiple categories: Is the correct way to do this to have two <machine...> lines that are identical except for their category, or to have something like <machine name="yellowstone" compiler="intel" category="aux_clm45|prealpha">?

3. Similar question to (2), but how do you have the same test run with multiple compilers? Again, is the expectation that there should be multiple <machine...> lines or one machine line with a '|' in the match?

**Comment by billsacks** [comment]
cc @jedwards4b

**Comment by billsacks** [comment]
Incidentally: I personally still prefer an even flatter format that more closely matches the test names that are used when creating single tests or examining test results. e.g., something like:

```xml
<test name="SMS_D_Ly6.1x1_smallvilleIA.IHISTCLM45BGCCROP.yellowstone_pgi.clm-crop_trans_sville">
...
```

Although I can also see some argument for separating out the machine and compiler. This would work best if we made the testmods come before the machine and compiler, so an individual test would look like `SMS_D_Ly6.1x1_smallvilleIA.IHISTCLM45BGCCROP.clm-crop_trans_sville.yellowstone_pgi` and the xml would look like:

```xml
<test name="SMS_D_Ly6.1x1_smallvilleIA.IHISTCLM45BGCCROP.clm-crop_trans_sville">
  <machine name="yellowstone" compiler="pgi" category="aux_clm45">
...
```

My rationale for these suggestions is motivated by my typical use cases:

1. Adding a new test to a test list
Here, I usually run the test first as a single test, to make sure it passes, then add it to the list. It's less error-prone if you can simply copy and paste here.

2. Removing a test
Here, I typically know the exact test (full test name) I want to remove, and then search the plain text file for it. This would be harder to do with the pieces of the test name separated into separate attributes.

3. Modifying one or more existing tests – e.g., changing the run length, grid, etc.
This use case is similar to (2), in that I typically first do a search for the exact test(s) I want to change. As with (2), this search would be easier if the xml file contained a single string giving the full test name (without machine/compiler).


I realize that munging together all of the aspects of the test name into a single period-delimited string is less clean / elegant than the current format. However, I don't see much practical downside of it myself. It means that create_test needs to parse this string, but that machinery is needed anyway for creation of single tests. It also means that developers need to know how to combine these attributes into a test name, but again: that's needed anyway for the creation of single tests and for understanding test results.


However, all that said: I realize that we had this discussion a year ago and I lost this argument :-)

**Comment by jedwards4b** [comment]
> Currently, this supports the option of wallclock. We have also talked about adding options for expected memleak amounts (in #588 ) and expected failures (in some older discussions). But these latter options - and to some extent the wallclock option - are machine and compiler-specific, so it seems like these need to be nested under machine, not in a separate options block that applies to all machines/compilers.

Note that the options section can apply to all machines as shown above, or to a particular machine by nesting it one level deeper.

**Comment by billsacks** [comment]
> Note that the options section can apply to all machines as shown above, or to a particular machine by nesting it one level deeper.

Thanks for pointing that out, Jim. 

Okay, assuming that

https://github.com/ESMCI/cime/issues/620#issuecomment-250797536

ain't gonna happen, I think all that's needed here is better documentation. This includes the 3 things I mentioned above, plus now one more... all copied here for one-stop-shopping:

Can someone document how to do the following with the testlist xml files:

1. Add a comment that appears when using the tool that queries testlists (i.e., not just a comment in the xml, but something with a special comment tag). I don't see any examples of this in the new xml formatted files. Incidentally, this would be another tag that is good to have nested under a specific machine / compiler / category, because my comments are often specific to that level.

2. Have the exact same test appear in multiple categories: Is the correct way to do this to have two lines that are identical except for their category, or to have something like ?

3. Similar question to (2), but how do you have the same test run with multiple compilers? Again, is the expectation that there should be multiple lines or one machine line with a '|' in the match?

4. Document the different ways you can specify options - either nested under a machine tag or not.


I'm not sure what the best place would be for this documentation, but testlist.py seems like a reasonable option.

**Comment by billsacks** [comment]
Oops, my offline writing crossed paths with Jim's PR #626 . To keep things clear, I'll change this back to the old title, and open a new issue regarding documentation.
