### ISSUE TITLE
Create_test without any arguments creates very wrong tests

### ISSUE THREAD

**Issue by Katetc** [ESMCI/cime#625]
I accidentally typed "create_test" and hit enter before giving any arguments on Yellowstone, and the following tests were created in my scratch dir while I panicked and pounded "Cntrl-C" over and over:
SBN.ne30_g16.I1850.null_null.20160930_145847.fx1krp
ERS_Lm3.T62_g16.C.edison_intel.pop-default.20160930_145847.fx1krp
SMS.f19_g16.X.yellowstone_intel.20160930_145847.fx1krp
NCK_Ld5.f19_g16.BC5L45BGCRG.yellowstone_intel.allactive-defaultio.20160930_145847.fx1krp
ERS.T62_s11.C.bluewaters_pgi.pop-default.20160930_145847.fx1krp
PET_Ld3.f45_g37_rx1.A.eos_cray.20160930_145847.fx1krp
SMS_Ld1.1x1_mexicocityMEX.I1PT.janus_intel.clm-40default.20160930_145847.fx1krp
SMS_P15x1_D.T62_g37.CECO.yellowstone_intel.pop-ecosys.20160930_145847.fx1krp
ERS_Ld3.f19_g16.B1850Cw.yellowstone_gnu.allactive-defaultio.20160930_145847.fx1krp
ERP_Ld5.f19_g16.IHISTCN.titan_pgi.clm-40default.20160930_145847.fx1krp
SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_intel.clm-ptsRLA.20160930_145847.fx1krp
SMS_D_Ly1_P24x1.f09_g16_gl4.TGIS2.hobart_nag.20160930_145847.fx1krp
SMS_Ld1.f45_f45.I.yellowstone_gnu.clm-40ptsRLA.20160930_145847.fx1krp
ERS_Ld5_D.T62_g37.GECO.yellowstone_intel.pop-ciso_abio_dic_dic14.20160930_145847.fx1krp
ERS_Ld30.T62_g37.CECO.yellowstone_intel.pop-abio_dic_dic14.20160930_145847.fx1krp
NCK_Ld3.f19_g16_rx1.A.eos_intel.20160930_145847.fx1krp
PEA_P1_Ld3.f45_g37_rx1.A.yellowstone_pgi.20160930_145847.fx1krp
ERS.T62_g16.G.hobart_pgi.pop-cice.20160930_145847.fx1krp
ERS_Ld5_Mmpi-serial.1x1_vancouverCAN.I1PTCLM50.yellowstone_intel.clm-default.20160930_145847.fx1krp
ERP_Ld5.f10_f10.ICLM45BGC.yellowstone_intel.clm-default.20160930_145847.fx1krp
ERP_P180x2_Ld5.f19_g16.I1850CN.yellowstone_pgi.clm-40default.20160930_145847.fx1krp
ERR_N3.f19_g16.B1850.yellowstone_intel.allactive-defaultio.20160930_145915.y4cg7j

So, right off the bat, I don't think Create_Test should be making tests for "null_null" ever, and it probably shouldn't be making tests for edison, bluewaters, eos, janus, titan and hobart on Yellowstone. I, personally, don't think it should do anything without arguments, because if I accidentally launch the entire Yellowstone test suite, I'm going to be a cranky girl.

**Comment by billsacks** [comment]
Oh, c'mon, next you'll be saying that

```
./launch_nukes
```

shouldn't automatically launch the entire nuclear arsenal ;-)
