### ISSUE TITLE
Question on use of logging vs. print

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#630]
This is a question for @jedwards4b and @jgfouca . I'm asking it as an issue in case it's of interest to others.

I'm writing a little script to query the testlist xml files. Thus, the fundamental result of this script is output to stdout. I know we are generally using the logging infrastructure for output, and I see how that works well for tracking events that occur as various operations are performed. But for this use case, where output to stdout is the fundamental result, and it would make no sense to suppress the output, it feels to me like `print` is the right tool for the job.

This feeling is confirmed here

https://docs.python.org/2/howto/logging.html

For "Task you want to perform: Display console output for ordinary usage of a command line script or program" it lists "The best tool for the task: print()".

So, do you agree that I should use `print` in this case?

**Comment by jedwards4b** [comment]
yes print is what you should use here.

**Comment by billsacks** [comment]
Okay, thanks!
