### ISSUE TITLE
Need better test case coverage in cime_developer

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#646]
We are currently only testing NCK, ERI, SEQ, ERS, ERR, and SMS.

Untested: ERP, ERT, ICP, LII, NCR, NOC, PEA, PEM, PET, PFS, REP, SSP

It seems like we should be testing most if not all of these nightly.

**Comment by rljacob** [comment]
After discussion:  LII and SSP can't be tested in CIME.  Others can't easily be tested in CIME without full component models.

**Comment by rljacob** [comment]
Can we use fake tests?

**Comment by jgfouca** [comment]
I forgot about this issue. This is fairly important if we want to guarantee that things like PET will work for our users. @rljacob this should be assigned to someone so that we don't forget; not sure who the best person is, probably one of the Jims.

**Comment by rljacob** [comment]
So PET is now tested but what about the others from that list?

**Comment by jgfouca** [comment]
@rljacob , maybe I have my ACME hat on here too much, but at this point, every test that ACME cares about is tested.

**Comment by rljacob** [comment]
Well I think this issue should be viewed with a CIME hat on.

**Comment by jgfouca** [comment]
@rljacob probably but this is a case where I understand PET and it is testable in CIME standalone and that's not the case for the others. I'll go ahead an unassign myself because I have no plans to do further work on this in the near term.

**Comment by jgfouca** [comment]
Hah, you already did that.
