### ISSUE TITLE
Rerunning an ERI case seems to get stuck

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#656]
This is at least with cime5.1.1. Rerunning an ERI case seems to consistently get stuck with a complaint about CASE and RUN_REFCASE are identical. If the case goes fine on first submission, this doesn't come up, but if you try to rerun it, it does. I'm assuming it has some problem in resetting to the same state it was when initially setup.

err=ERROR: Command /glade/p/work/erik/clm_phs_clean/cime/driver_cpl/bld/build-namelist -caseroot /glade/p/work/erik/clm_phs_clean/cime/scripts/ERI_D_Ld9.T31_g37.ICLM45.yellowstone_intel.clm-SNICARFRC.C.20161006_115523.ref2 -cimeroot /glade/p/work/erik/clm_phs_clean/cime  -infile /glade/p/work/erik/clm_phs_clean/cime/scripts/ERI_D_Ld9.T31_g37.ICLM45.yellowstone_intel.clm-SNICARFRC.C.20161006_115523/Buildconf/cplconf/namelist -pio_version 1 -grid a%T31_l%T31_oi%gx3v7_r%r05_m%gx3v7_g%null_w%null -atm_grid T31 -lnd_grid T31 -rof_grid r05 -ocn_grid gx3v7 -wav_grid null failed rc=255
out=infile is /glade/p/work/erik/clm_phs_clean/cime/scripts/ERI_D_Ld9.T31_g37.ICLM45.yellowstone_intel.clm-SNICARFRC.C.20161006_115523/Buildconf/cplconf/namelist 
 Read fldsin file: /glade/p/work/erik/clm_phs_clean/cime/scripts/ERI_D_Ld9.T31_g37.ICLM45.yellowstone_intel.clm-SNICARFRC.C.20161006_115523.ref2/Buildconf/clmconf/drv_flds_in
build-namelist ERROR: CASE and RUN_REFCASE are identical
err=Set BRNCH_RETAIN_CASENAME to TRUE in env_run.xml

**Comment by jgfouca** [comment]
@ekluzek this should be fixed by recent work to support re-runnability for our tests. Please re-open and assign to me if that's not the case.
