### ISSUE TITLE
CIMEROOT environment variable used too aggressively

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#657]
If you have CIMEROOT defined in your environment (or, presumably, in your .cime_config), it appears that any scripts you run from cime load at least some things from the directory referenced from CIMEROOT, rather than the current directory.

I tested this by setting:

```bash
export CIMEROOT=/path/does/not/exist
```

and then trying to run create_test from cime/scripts. This gave:

```
Traceback (most recent call last):
  File "./create_test", line 11, in <module>
    from Tools.standard_script_setup import *
  File "/glade/p/work/sacks/cime/scripts/Tools/standard_script_setup.py", line 15, in <module>
    import CIME.utils
ImportError: No module named CIME.utils
```

(similar things happen for create_newcase, etc.)

I'm not really concerned about this exact case (where CIMEROOT points to a non-existent directory). I was more using this as a measure of whether standard scripts like create_newcase and create_test try to load anything out of CIMEROOT - and apparently they do.

It's unclear to me, then, what comes from CIMEROOT and what comes from the current directory. 

This could be very confusing and cause incorrect results in situations like this: Someone has CIMEROOT set to point to some cime clone, and they also have a CESM checkout with a different version of cime. They run create_newcase from their CESM checkout. Would this actually be using some / all things from CIMEROOT rather than from the current directory? This, in my opinion, would be a Bad Thing.

I forget the reason why CIMEROOT was introduced originally. But I'm having trouble seeing any reason why you would ever want to run a script out of cime directory A, and have it use pieces from cime directory B. It feels like this creates potential for significant confusion and unexpected behavior.

**Comment by jedwards4b** [comment]
PR #655 should address this issue.   Please consider reviewing it now.

**Comment by gold2718** [comment]
I don't think that PR #655 covers the larger issue. I think we should all agree on the proper use of CIMEROOT (if any) and make sure all the code enforces that use.
Going back to the origin of CIME, I recall that the idea was for CIME to be a unified, standalone tool set. A logical consequence is that any use of any CIME script must use the consistent version from whence it came. The function, get_python_libs_location_within_cime, seems to fulfill this purpose. What independent role does CIMEROOT play? Why is it ever needed or consulted?
What I see as a reasonable split is having CIME not be in a CESM or ACME directory tree but be able to operate on that tree. Thus, I can see create_newcase or create_test using the CESMROOT environment variable to make that link.
Is there ever a reason for a CIMEROOT environment variable? If so, please document it here (and in the CIME manual) so we can ensure consistent usage.

**Comment by jgfouca** [comment]
The only time I've needed it was to run some of the few tools that are copied/generated (not symlinked) in the case directory.

**Comment by jgfouca** [comment]
It's like that, if you're in a case directory, there's another way to get the CIMEROOT without have to use the environment. I'll look into this.

**Comment by jedwards4b** [comment]
I think that the submitted jobs : template.* need to have it in the environment, so be sure and test changes with a batch system :-)

**Comment by gold2718** [comment]
I would argue that this is an error as the correct CIME location is known when these files are processed. I think this also applies to config_batch.xml with lines such as:
`<arg flag="--env" name='"CIMEROOT=$CIMEROOT"'/>`

**Comment by jedwards4b** [comment]
I think that you are correct - this use in config_batch.xml is no longer needed.
