### ISSUE TITLE
CIME User's guide:  how many guides?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#671]
We need to decide on an outline for the CIME User's guide but first we need to agree on highest-level organization of CIME-related content.

Proposal:  From the wiki ESMCI home page, you'll be able to choose between 3 different guides depending on your interest

1. CIME Users' Guide. 
   Part 1:  basic CIME usage (create_newcase, case.setup, case.build, case.submit, manage_case) including explanation of all arguments.  examples with and without archiving/resubmitting.  How to make changes to the xml files.  When/why case.submit or case.build have to be re-run.  User options for the data models and coupler.
   Part 2:  Advanced CIME usage:  create_clone, create_test,  manage_testslists, how to add tests,  how to edit the config files to add compsets, grids, machines.

2. CIME Developers Guide:  Directory structure of CIME, What the code in utils/python does and how it relates to the config files, how the build system works.  How the submit system works.  The externals and how to manage them.  Our git workflow and testing procedure.

3. Building a coupled model with CIME:   how to replace an existing cime model with another one, how to integrate your model in to the cime build/configure system and coupler.   How to work with the data models (if you don't have those)   What to do if you want to add another component to the long name.

"What is CIME" would be in a 4th document at the same level as the ones above.

**Comment by rljacob** [comment]
Most of http://www.cesm.ucar.edu/models/cesm1.2/cpl7/doc/book1.html would go in guide no. 3 above.

**Comment by rljacob** [comment]
I think the data model content http://www.cesm.ucar.edu/models/cesm2.0/data8/doc/book1.html would also go in no. 3.

**Comment by mvertens** [comment]
I think there are several key guides that are missing:

- data model documentation
- driver documentation
- creating mapping files
- running the verification test
- pointer to running diagnostics

- also - we need to have a section in the User's guide for porting
should this be a different guide by itself?

**Comment by rljacob** [comment]
As a user, I'd hate to be confronted with 7-10 guides all at the same level with no clear distinction of what's really important.  That's why I was trying to reduce it to 3.

But I can see how the data model's and driver need their own guides.  "creating mapping files" goes in the "building a coupled model" guide.  Porting is in the advanced section of the user's guide. 

What do you mean by "the verification test"?   That's probably in the developer's guide.

The scripts to run the diagnostics would be in the Part I user's guide but the content of the diagnostics is model-specific and should lie outside CIME.

**Comment by mvertens** [comment]
By the verification test - I mean the statistical ensemble test that can be
used to validate porting. ACME is working on their own validation test
processes - but there is enormous interest in these utilities and I think
they belong in CIME. At any rate - we can defer and have more discussions
after I return.

Mariana

**Comment by rljacob** [comment]
We can have a top level guide called "Miscellaneous Tools" and put guides for verification and the other ones there.

**Comment by mvertens** [comment]
I think that's a great idea.

**Comment by rljacob** [comment]
So at the top level of the cime wiki we would have:

What is CIME
User's Guide
Developer's Guide
Coupler
Data Models
Building a coupled model with CIME
Miscellanous Tools

**Comment by mvertens** [comment]
This looks like a good outline.
