### ISSUE TITLE
Most Z_FullSystemTest tests fail with cime_model=ACME on yellowstone/caldera

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#684]
I tried this from something near the head of cime, from yellowstone:

```
bsub -q caldera -n16 -PP93300601 -W8:00 -o cime_tests.%J.out -e cime_tests.%J.err CIME_MODEL=acme ./scripts_regression_tests.py Z_FullSystemTest
```

This gave:

```
FAIL: test_full_system (__main__.Z_FullSystemTest)
```

with this extra info:

```
At test-scheduler close, state is:
FAIL SEQ_Ln9.f19_g16_rx1.A.caldera_intel (phase RUN)
    Case dir: /glade/scratch/sacks/SEQ_Ln9.f19_g16_rx1.A.caldera_intel.fake_testing_only_20161017_153741
FAIL NCK_Ld3.f45_g37_rx1.A.caldera_intel (phase RUN)
    Case dir: /glade/scratch/sacks/NCK_Ld3.f45_g37_rx1.A.caldera_intel.fake_testing_only_20161017_153741
PASS ERS_Ld3.ne30_g16_rx1.A.caldera_intel RUN
    Case dir: /glade/scratch/sacks/ERS_Ld3.ne30_g16_rx1.A.caldera_intel.fake_testing_only_20161017_153741
FAIL SMS_D_Ln9.f19_g16_rx1.A.caldera_intel (phase RUN)
    Case dir: /glade/scratch/sacks/SMS_D_Ln9.f19_g16_rx1.A.caldera_intel.fake_testing_only_20161017_153741
PASS ERI.f45_g37.X.caldera_intel RUN
    Case dir: /glade/scratch/sacks/ERI.f45_g37.X.caldera_intel.fake_testing_only_20161017_153741
PASS ERR_Ld3.f45_g37_rx1.A.caldera_intel RUN
    Case dir: /glade/scratch/sacks/ERR_Ld3.f45_g37_rx1.A.caldera_intel.fake_testing_only_20161017_153741
FAIL ERS_N2_Ld3.f19_g16_rx1.A.caldera_intel (phase RUN)
    Case dir: /glade/scratch/sacks/ERS_N2_Ld3.f19_g16_rx1.A.caldera_intel.fake_testing_only_20161017_153741
test-scheduler took 1088.84169292 seconds
ERRPUT: Phase 'RUN' for test 'SEQ_Ln9.f19_g16_rx1.A.caldera_intel' required more processors, 64, than this machine can provide, 18
Phase 'RUN' for test 'SMS_D_Ln9.f19_g16_rx1.A.caldera_intel' required more processors, 64, than this machine can provide, 18
Phase 'RUN' for test 'ERS_N2_Ld3.f19_g16_rx1.A.caldera_intel' required more processors, 64, than this machine can provide, 18
```

**Comment by jgfouca** [comment]
You don't need to do it like that unless you want --no-batch. Just run ./scripts_regression_tests.py Z_FullSystemTest and let the scripts do the submit.

**Comment by jedwards4b** [comment]
We intentionally define caldera as a no-batch system.  Perhaps someone was unclear about where or how to code the number of tasks for a given system, but I haven't been able to find where this is done yet so I don't have a suggested fix.   Where is the 64 tasks number being set?

**Comment by jedwards4b** [comment]
The problem is that all config_pes settings are coming from cime_config/acme/allactive/config_pesall.xml as set in
cime_config/acme/config_files.xml   instead of from driver_cpl/cime_config/config_pes.xml as in cesm.   

We could make a special case in this file for caldera, but because of the way the file is set up we would need a different special case for each grid resolution.   My preference would be to point config_files.xml back to the driver_cpl file, this would allow A and X cases to run on a single node.   @jgfouca and @rljacob are you okay with that?

**Comment by jgfouca** [comment]
I'll defer to @rljacob . All the changes that ACME has made to PE configuration since our project has started were migrated into the allactive config_pes.xml.

**Comment by rljacob** [comment]
I do want to make that change but also want to remove the X and A cases from the combined config_pesall.xml at the same time.  Haven't had the time to do that.

**Comment by jedwards4b** [comment]
All you need to do is change the pointer in config_files.xml, I don't think there are any explicit X or A cases in the combined file.

**Comment by billsacks** [comment]
I think this issue is essentially resolved. From something close to the latest master I ran

```
[yslogin1:/glade/p/work/sacks/cime/scripts/tests]$ bsub -q caldera -n16 -PP93300601 -W8:00 -o cime_tests.%J.out -e cime_tests.%J.err CIME_MODEL=acme ./scripts_regression_tests.py Z_FullSystemTest
Job <72574> is submitted to queue <caldera>.
```

Tests seemed to pass except for this one:

```
FAIL PRE.f45_g37_rx1.ADESP.caldera_intel (phase RUN)
    Case dir: /glade/scratch/sacks/scripts_regression_test.20170421_095701/PRE.f45_g37_rx1.ADESP.caldera_intel.fake_testing_only_20170421_095728
```

but I'm going to assume there is a specific issue with that test, rather than the more general issue alluded to here.
