### ISSUE TITLE
More tests have BUILD_THREADED which shouldn't, I think

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#687]
@jedwards4b recently fixed a problem in which BUILD_THREADED was set to TRUE for all ERP tests, whereas it shouldn't be. It looks like ERI and DAE tests have the same problem: BUILD_THREADED is set to TRUE for these tests in config_tests.xml. This seems to be causing ERI tests to fail on hobart-nag (and presumably would cause DAE tests to fail there, too, but I don't run those).

I assume these lines should be removed, but I want to run this by @jedwards4b , because I'm not clear on why they were added initially.

Also cc @fischer-ncar @ekluzek

**Comment by billsacks** [comment]
@jedwards4b - do you see any problem with removing BUILD_THREADED from the ERI and DAE tests? This is causing ERI tests to fail on hobart. I don't see any reason why ERI tests should use BUILD_THREADED, but I wanted to check with you before removing this. I'm guessing the DAE test simply copied the ERI test in this respect.

**Comment by jedwards4b** [comment]
Sorry, I haven't tried it yet.   The only thing I can think of is that both parts of a two part test need to have the same value of BUILD_THREADED.

**Comment by billsacks** [comment]
Right... but eri and dae tests don't change threading for any of the cases, so that seems not to matter. I'm happy to wait a bit longer on this if you still want to find time to investigate more closely. Otherwise, I can submit a PR with the necessary change (and a bit of testing) if you prefer that I do that.

**Comment by jedwards4b** [comment]
That would be great, thanks.
