### ISSUE TITLE
Occasional build failures with large test suites

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#690]
I have been running into occasional build failures when running the large aux_clm test suite on yellowstone. Here, "occasional" means: happens for every test suite, though just for a small fraction of the tests. The failed tests work when I rebuild them. I'd be tempted to chalk this up to a system problem, except that it was quite rare to encounter problems like this prior to cime5 - whereas I am commonly running into this with cime5: I have seen this in all 3 of my last 3 runs of the test suite (which I think have been my only runs of the full aux_clm45 test suite with cime5). In addition, I just did 5 separate runs of the full aux_clm test suite out of a CLM version with cime4, and there was not a single build failure, giving me more confidence that this is _not_ just due to recent machine flakiness. So this makes me wonder if the parallel builds are occasionally stomping on each other somehow.

I have been running the aux_clm test suite as 5 separate jobs (with 5 different test ids): one for clm40-intel, one for clm40-pgi, one for clm45-intel, one for clm45-pgi, and one for clm45-gnu.

This is with a slightly old version of cime - something basically equivalent to d321e4b . So, apologies if this is something that has been fixed since then - though I don't remember seeing any relevant PRs.

Here are the relevant build failures:

**From my most recent run of the test suite; the sharedlib directory was in /glade/scratch/sacks**

For `ERP_D_Ld5.f10_f10.ICLM45.yellowstone_pgi.clm-reduceOutput.GC.1018-1324.45.p`: Error in building the executable:

```
/glade/scratch/sacks/tests_1018-1324/sharedlibroot.1018-1324.45.p/pgi/mpich2/debug/threads/lib/libmpeu.a: file not recognized: File truncated
```
(even though the modification time on that file is about an hour before the time stamp on the relevant build log file).

**From a run a few weeks ago; the sharedlib directory was under /glade/p/work/sacks**

For `ERI_D_Ld9.f19_g16.I1850CN.yellowstone_pgi.clm-40default.GC.0929-2129.40.p`: Error in building the lnd library:

```
PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/p/work/sacks/cesm_code/clm_limitirrig/components/clm/src_clm40/main/accumulMod.F90: 577)
```

For `ERP_D_Ld5.f19_g16.ICLM45BGC.yellowstone_intel.clm-default.GC.0929-2129.45.i`: Error in building the executable:

```
ld: BFD version 2.20.51.0.2-5.36.el6 20100205 internal error, aborting at merge.c line 872 in _bfd_merged_section_offset

ld: Please report this bug.

gmake: *** [/glade/scratch/sacks/ERP_D_Ld5.f19_g16.ICLM45BGC.yellowstone_intel.clm-default.GC.0929-2129.45.i/bld/cesm.exe] Error 1
```

For `ERI_D_Ld9.f10_f10.ICLM45BGC.yellowstone_pgi.clm-reduceOutput.GC.0929-2129.45.p`: Error in building the executable:

```
PGF90-F-0004-Corrupt or Old Module file m_mpif.mod (/glade/p/work/sacks/cesm_code/clm_limitirrig/cime/driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90: 208)
PGF90/x86-64 Linux 15.10-0: compilation aborted
```

**And from another run a few weeks ago; the sharedlib directory was under /glade/p/work/sacks**

For `ERP_D_Ld5.f19_g16.ICLM45BGC.yellowstone_intel.clm-default.GC.0929-0852.45.i`: Error in building the executable:

```
/glade/p/work/sacks/cesm_code/clm_limitirrig/cime/scripts/tests_0929-0852/sharedlibroot.0929-0852.45.i/intel/mpich2/debug/threads/lib/libmct.a: file not recognized: File truncated
```

For `ERP_Ld5.f10_f10.I1850CLM45BGC.yellowstone_pgi.clm-default.GC.0929-0852.45.p`: Simultaneous failures in building stub glc, esp and ice: like this:

```
PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/p/work/sacks/cesm_code/clm_limitirrig/cime/components/stub_comps/sglc/cpl/glc_comp_mct.F90: 11)
```

**Comment by billsacks** [comment]
@ekluzek and @bandre-ucar : if you have been seeing problems like this, too, do you want to add any additional notes here?

**Comment by billsacks** [comment]
Brainstorming some possible, though admittedly half-baked (or one-one-hundredth-baked):

1. If there is an identifiable race condition, fix it. However, at least in some of these cases, it looks like the problem is simply trying to read some existing file, which seems like a funny thing to cause problems.

2. Can we put in place a retry system for the builds, so that it tries up to 3 times before failing?

 The main problem I see with this is: Ideally, I'd like to be notified somehow that it needed to retry, so that this doesn't mask a real problem. What should this notification look like? e.g., should we report up to three BUILD phases, like:

 ```
 FAIL MODEL_BUILD_1
 FAIL MODEL_BUILD_2
 PASS MODEL_BUILD_3
 ```

 or if it passed on the first try we'd just see:

 ```
 PASS MODEL_BUILD_1
 ```

 so that we keep going as long as there is a pass in one of the MODEL_BUILD phases... but the failures are still reported in the final reporting.

3. To deal with the problems during the link phase: Could we make copies of the libraries before linking? (Then, for static linking, could we delete those copies later?)

4. Rather than having all of the parallel builds using the same sharedlib space: Create a separate sharedlib space for each parallel build instance. So thread 1 would use sharedlib...1, thread 2 would use sharedlib...2, etc. I don't know how the build threads are created, though: if they're created dynamically (i.e., constantly being created), then there would need to be a more complex mechanism to accomplish this - e.g., getting a currently-unused sharedlib index, and putting a lock on that.

 I realize this would reduce the efficiency of the parallel builds, since the shared libraries would need to be created multiple times.

5. If none of these ideas are feasible, and no other ideas are forthcoming, then I'd likely deal with this by just reducing the parallelism of the builds for the aux_clm test suite: As long as there isn't a huge impact on build time (which I don't expect there will be for CLM testing, since most of the build uses the sharedlib space), I prefer to have builds that Just Work, even if they have a slightly longer turnaround time. (I often run test suites overnight, in which case turnaround time is less important than having everything completely done when I come back to it in the morning.)

**Comment by billsacks** [comment]
@jgfouca and @jedwards4b : I don't understand the parallel builds, so would welcome any input from either of you.

**Comment by jgfouca** [comment]
@billsacks You could try disabling the build parallelism in build.py:build_model

**Comment by billsacks** [comment]
@jgfouca - thanks, I'd like to try that. But I'm not confident enough in my understanding of the code to know how I should change things so that it works as before, simply without threading.

Also: My understanding is that the code you pointed me to handles the parallelization across component models. My understanding is that there are at least three levels of parallelization:

1. Multiple tests are built in parallel
2. For a given test, multiple components are built in parallel
3. For a given build, you still use make -j 8 (or whatever)

Is that correct? If so, can you also tell me how to disable the parallelization in (1)? Then I can try that as well.

**Comment by jgfouca** [comment]
@billsacks you are correct and only 1 and 2 are new to CIME5.

create_test -j 1 will disable all parallelization in test_scheduler

For 2, just change this:
```
        t = threading.Thread(target=_build_model_thread,
            args=(config_dir, model, caseroot, bldroot, libroot, incroot, file_build,
                  thread_bad_results, smp))
        t.start()
```
to this
```
_build_model_thread(config_dir, model, caseroot, bldroot, libroot, incroot, file_build, thread_bad_results, smp)
```

**Comment by billsacks** [comment]
Okay, some testing points the finger at:

 > 1. Multiple tests are built in parallel

I did three sets of experiments:

1. Control: out-of-the-box create_test (using d321e4b)
2. Disabled parallelism in the model_build, using the above mods, plus also deleting this:

 ```diff
 -    # Wait for threads to finish
 -    while(threading.active_count() > 1):
 -        time.sleep(1)
 -
 ```

3. Disabled parallel test setup / build, by specifying `-j 1` to create_test (but went back to having no diffs in the scripts)

For each experiment, I ran 5 separate iterations of the full yellowstone CLM test suite, using a different testid for each (so the different iterations shouldn't be stomping on each other - they're using different sharedlib spaces). Each iteration actually consisted of 5 runs of create_test: one for clm40-intel, one for clm40-pgi, one for clm45-intel, one for clm45-pgi, and one for clm45-gnu. So each experiment had 25 create_test instantiations in all. The full test suite contains something like 150 tests (or maybe slightly more). Here I'm reporting the number of failures per full test suite, since that's what matters to me.

(1) Average of 3 build failures per run of the test suite. Time to completion of all builds: about 3 - 3.5 hours.

(2) Average of 2.6 build failures per run of the test suite. Time to completion of all builds: about 3 hours.

(3) Exactly 0 build failures. Time to completion of all builds: about 5 - 5.5 hours.

So it seems that the aggressive parallelization over tests is causing some build failures in large test suites like this one. On the other hand, it trims roughly 40% off of the test setup / build time, which is nothing to sneeze at.

Next steps:

- I'd like to see whether a more modest `-j 2` achieves much of the speedup without leading to build errors. But yellowstone is hanging right now, so this will have to wait until tomorrow.

- @jgfouca / @jedwards4b : Any guesses why this parallelization over tests is causing these problems? I can point you to all of the failed builds if you'd like.

**Comment by jgfouca** [comment]
Hi @billsacks , we've been aggressively parallelizing builds on the ACME side for over a year and I've never seen what you're describing. I can't imagine how doing independent builds simultaneously could cause failures except for maybe causing the system to run out of resources.

One thing that is different in CIME5 compared to ACME is that the sharedlibs are actually shared between all tests in a suite whereas in ACME we build sharedlibs within each test case so they are not actually shared at all. In CIME5 there's special code in test_scheduler to prevent multiple shared-lib builds from occurring at once. It's possible that there's a problem with this code, but I'd be surprised that we haven't seen it on any other machine. It does look like many of the errors you reported involve sharedlibs, but not all, so again that's confusing.

Did you see anything obviously wrong in the create_test output? Like multiple sharedlib builds kicking off simultaneously? Is there any identifiable pattern that causes the error?

**Comment by billsacks** [comment]
I was really hoping that using `-j 2` would solve this problem; alas, it does not. I did the same set of 5 instantiations of the clm test suite, with `-j 2`. 

On the plus side, the total time to completion was about 3 hours, so this is just as fast as the super-parallelization, at least for the CLM test suite. 

However, I still got 1.6 build failures per test suite – about a 1% failure rate. Better than the ~ 2% failure rate before, but still not ideal.

Here are the details of the failures this time around:

```
tests_1020-0508q/ERP.f19_g16_gl5.IG1850CLM45.yellowstone_pgi.1020-0508q.45.p/TestStatus:FAIL ERP.f19_g16_gl5.IG1850CLM45.yellowstone_pgi MODEL_BUILD time=122

PGF90-F-0004-Corrupt or Old Module file piolib_mod.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/driver_cpl/driver/seq_map_mod.F90: 593)

tests_1020-0508r/ERP.f19_g16_gl5.IG1850CLM45.yellowstone_pgi.1020-0508r.45.p/TestStatus:FAIL ERP.f19_g16_gl5.IG1850CLM45.yellowstone_pgi MODEL_BUILD time=123

PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/driver_cpl/driver/prep_atm_mod.F90: 224)
PGF90/x86-64 Linux 15.10-0: compilation aborted
PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/driver_cpl/driver/prep_ice_mod.F90: 181)
gmake: *** [prep_atm_mod.o] Error 2
gmake: *** Waiting for unfinished jobs....
PGF90/x86-64 Linux 15.10-0: compilation aborted
PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/driver_cpl/driver/map_lnd2glc_mod.F90: 196)
PGF90/x86-64 Linux 15.10-0: compilation aborted
gmake: *** [prep_ice_mod.o] Error 2
gmake: *** [map_lnd2glc_mod.o] Error 2

tests_1020-0508r/SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_intel.clm-ptsRLA.1020-0508r.45.i/TestStatus:FAIL SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_intel.clm-ptsRLA MODEL_BUILD time=33

Failed in datm build; hard to tell what exactly happened, but here are some errors:

/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/components/data_comps/datm/datm_shr_mod.F90(12): error #7013: This module file was not generated by any release of this compiler.   [SHR_C
AL_MOD]
  use shr_cal_mod,   only: shr_cal_date2julian
------^
/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/components/data_comps/datm/datm_shr_mod.F90(55): error #6683: A kind type parameter must be a compile-time constant.   [R8]
real(R8) function datm_shr_getNextRadCDay( ymd, tod, stepno, dtime, iradsw, calendar )
-----^

tests_1020-0508s/ERP_D_Ld5.f10_f10.ICRUCLM50BGC.yellowstone_pgi.clm-ciso_flexCN_FUN.1020-0508s.45.p/TestStatus:FAIL ERP_D_Ld5.f10_f10.ICRUCLM50BGC.yellowstone_pgi.clm-ciso_flexCN_FUN MODEL_BUILD time=137

PGF90-F-0004-Corrupt or Old Module file pio_types.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/driver_cpl/driver/cesm_comp_mod.F90: 149)

tests_1020-0508s/ERP_D_Ld5.f19_g16_gl5.ICLM45GLCMEC.yellowstone_intel.clm-glcMEC_changeFlags.1020-0508s.45.i/TestStatus:FAIL ERP_D_Ld5.f19_g16_gl5.ICLM45GLCMEC.yellowstone_intel.clm-glcMEC_changeFlags MODEL_BUILD time=238

ld: can not read symbols: File truncated

tests_1020-0508s/SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_pgi.clm-ptsRLA.1020-0508s.45.p/TestStatus:FAIL SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_pgi.clm-ptsRLA MODEL_BUILD time=34

sesp, swav, and socn builds all fail with:

PGF90-F-0004-Corrupt or Old Module file seq_infodata_mod.mod (/glade/scratch/sacks/cesm_code/clm4_5_12_r196_cime_d321e4b/cime/components/stub_comps/socn/cpl/ocn_comp_mct.F90: 110)

tests_1020-0509t/ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.yellowstone_pgi.clm-default.1020-0509t.45.p/TestStatus:FAIL ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.yellowstone_pgi.clm-default MODEL_BUILD time=145

/glade/scratch/sacks/tests_1020-0509t/sharedlibroot.1020-0509t.45.p/pgi/mpich2/debug/threads/lib/libpio.a: could not read symbols: File truncated

tests_1020-0509t/PEM_D_Ld5.ne30_g16.ICLM45BGC.yellowstone_intel.clm-default.1020-0509t.45.i/TestStatus:FAIL PEM_D_Ld5.ne30_g16.ICLM45BGC.yellowstone_intel.clm-default MODEL_BUILD time=182

ld: can not read symbols: File truncated
```

**Comment by billsacks** [comment]
@jgfouca : 

> One thing that is different in CIME5 compared to ACME is that the sharedlibs are actually shared between all tests in a suite whereas in ACME we build sharedlibs within each test case so they are not actually shared at all. 

I think this is exactly the problem, based on what I have seen: In most, or possibly all, of the cases, it looks like the problem occurs when trying to build or link against a file in the sharedlib space.

What's the current behavior of ACME with cime5: Now that you're using cime5 do you use a shared sharedlib space, or is there a difference between the acme and cesm builds such that you still separate the sharedlib spaces for each test?

> In CIME5 there's special code in test_scheduler to prevent multiple shared-lib builds from occurring at once. It's possible that there's a problem with this code, but I'd be surprised that we haven't seen it on any other machine. It does look like many of the errors you reported involve sharedlibs, but not all, so again that's confusing.

It looks to me like the problem is not in the _building_ of the shared libs, per se, but rather trying to _use_ an existing shared lib build (either building against an existing module file, or linking against an existing static library).

> Did you see anything obviously wrong in the create_test output? Like multiple sharedlib builds kicking off simultaneously? Is there any identifiable pattern that causes the error?

I'm not quite sure what to look for here. Any specific suggestions?

I don't really understand what could be causing this. It seems that the problem comes in trying to access files that have already been created, which would suggest that there is a problem in simply having two builds try to _read_ those files at once, which seems weird. Is it possible that, even if it turns out there's nothing to do for these files, the build system briefly opens the relevant files (module & library files) for writing before closing them again? i.e., if one test is trying to link against a given foo.a file when another test is trying to build that library (even though it's already been built and there's nothing more to be done), maybe this causes the failures we're seeing.

One thought based on this is... still half-baked: Maybe after a sharedlib build is done, its files are copied to a separate, 'frozen' location. Then includes and library locations point to that separate, frozen location. The tricky part of this is when to re-copy a file: If you say 'never copy over existing files in the frozen location', then I think rebuilding after making changes would require a clean_build; but if you say 'always copy over existing files in the frozen location', then we could run into the same problem of trying to build/link against files that are being overwritten (though maybe the problem would be less common if this was just during a copy operation rather than during a more complex build operation). So we might need more smarts here....

**Comment by jgfouca** [comment]
@billsacks ACME's main branch is still not using CIME5, so unfortunately I don't have any data on this issue from the ACME side.

@jedwards4b I wonder if this is serious enough to go back to not sharing sharedlibs at all.

**Comment by billsacks** [comment]
I have dug into this some more - specifically, looking at modification times on various files in the sharedlib build area. I think I understand what might be going on for the failed mpi-serial builds, though am less sure of what's wrong for the mpich2 builds.

For the mpi-serial builds, quite a few .mod and .a files are recreated in each build. It looks to me like the root cause of the problem is that there are some mpi header files (.h) copied into the include/ directory. **It appears that these mpi-serial header files are re-copied with each build; I'm thinking they should be copied with a makefile rule, so that they are only re-copied if the version in the source tree has changed.** It looks like this re-copying of the .h files has a cascading effect, presumably because make sees updated prerequisites which force other things to be rebuilt: lib/libmpi-serial.a is rebuilt, as are about half of the .mod files in csm_share, csm_share.a, and essentially all CLM files. I think that this constant re-creation of libraries causes problems when tests in the model_build phase are trying to use them: they're trying to read files that are changing out from under them.

For the mpich2 builds, I was not able to find any files whose mtime was getting changed after the initial build. However, the ctime _does_ get changed on most or all files. Could it be a problem if a build is trying to use foo.mod, while at the same time something is happening to foo.mod that results in a change in its ctime? I could imagine a situation where foo.mod very briefly has permission bits set such that it momentarily becomes inaccessible, but I'm really speculating here.

In addition, for the mpich2 builds, this file _is_ recreated each time:  pgi/mpich2/nodebug/threads/MCT/noesmf/include  -- this is a text file that seems to be giving include information for something in CLM; is this correct?

If we can't figure out what's causing the non-mpi-serial problem, then it seems like one possible solution (more fully baked than some of my other suggestions) would be: **The last step of a sharedlib build would involve copying the relevant files (.mod, .a; others?) into a case-specific location. Then the model build (including building the final executable) is done against that case-specific location.** i.e., for the model build phase, the include and link paths point to the case-specific location, rather than the sharedlib space.

**Comment by jgfouca** [comment]
Nice catch. So our options are:
1) Change the building of sharedlibs so that once a certain configuration is built, it is left alone
2) Copy built shared libs into each case
3) Go back to not sharing sharedlibs

**Comment by jedwards4b** [comment]
@billsacks thanks for digging in, I just did some work on the buildlib.pio and I think what you are saying makes a lot of sense.   Option 2 sounds like a very good idea and I think that it could be a few line change.   I will look into it.

**Comment by billsacks** [comment]
> 1) Change the building of sharedlibs so that once a certain configuration is built, it is left alone

Good point. I hadn't thought of this, but it does seem like a good solution, if the logic doesn't end up being too tricky.

> 2) Copy built shared libs into each case

Right.

> 3) Go back to not sharing sharedlibs

I'm reluctant to go with this because I remember it gave us a huge speedup for CLM testing - since we had worked hard to move all configuration options to runtime. I guess I'd be reluctantly willing to accept it if the parallel builds can give us the same turnaround as sharedlibs, for CLM testing. Only "reluctantly" because it seems like the sharedlibs solution scales better as you increase the size of your test suite, which we're continually doing.

I'll also add, for completeness:

4) Do some more digging to determine what, exactly, is causing the problem with non-mpi-serial builds. e.g., I see that many (though not all) of the problems were coming from pio modules or the pio library; I wonder if this is at all related to the cmake-based pio build, the things @jedwards4b just changed, or something else....



Either (1) or (2) seem like the best solutions to me, and I'm happy to go with whichever of these is simplest to implement.
