### ISSUE TITLE
Have case dir echoed at beginning of build as well as at end

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#691]
I find that while my case is building, I sometimes want to investigate how it is being setup or the progress of the build.  I have to do some investigating as to what the actual case dir name is at this point.  If the case dir was echoed at the beginning of the build, this would allow me to easily go the appropriate directory.

**Comment by billsacks** [comment]
Is this similar to #369 or different?

**Comment by cacraigucar** [comment]
This is different, though 369 brings up a good point of "heritage after the run".  My request is while the job is actually in the middle of building, I would like to know where to go to check that the namelist has been built properly, see how far the compiles have gotten, change my project #, etc.  The "Case Dir" is echoed to the screen at the end of the create_test, and I'm just requesting that it be echoed at the beginning of the process as well.

**Comment by jgfouca** [comment]
Fixed by #693

**Comment by cacraigucar** [comment]
I am reopening #691 as I see it was closed, but my request has not yet been implemented.  My request must not have been clear - sorry.    I'm requesting that the Case Dir lines at the end of the create_test output be echoed at the beginning of the run as well as at the end. 

I've included the output from my .create_test command and have shown a possible location for the Case Dir.  The Case Dir line I'd like to see echoed at the beginning of the create_test run is at the end of this output.

-----------------------

 yslogin5$ execca ./create_test --xml-machine yellowstone --xml-category aux_cam_short --walltime 0:30 --project CESM0005
 
  Requesting 1 core(s) to caldera queue, 
  to submit ./create_test --xml-machine yellowstone --xml-category aux_cam_short --walltime 0:30 --project CESM0005 the usage is to be charged into P93300606 
  running

  bsub -Is -q caldera -n1 -PP93300606 -W24:00 "./create_test --xml-machine yellowstone --xml-category aux_cam_short --walltime 0:30 --project CESM0005"

  please wait.. 

Job <903793> is submitted to queue <caldera>.
<<Waiting for dispatch ...>>
<<Starting on pronghorn07-ib>>
Verifying using schema /glade/u/home/cacraig/cam5_4_100/-testcime/cime/cime_config/xml_schemas/config_machines.xsd
Testnames: ['ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5', 'ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5']
Verifying using schema /glade/u/home/cacraig/cam5_4_100-testcime/cime/cime_config/xml_schemas/config_machines.xsd
RUNNING TESTS:
  ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5
  ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5
**>>> ECHO CASE DIRS HERE? <<<**
Starting CREATE_NEWCASE for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Starting CREATE_NEWCASE for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Finished CREATE_NEWCASE for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 2.459673 seconds (PASS)
Finished CREATE_NEWCASE for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 2.467189 seconds (PASS)
Starting XML for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Starting XML for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Finished XML for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 0.843903 seconds (PASS)
Finished XML for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 0.857477 seconds (PASS)
Starting SETUP for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Starting SETUP for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Finished SETUP for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 3.837245 seconds (PASS)
Finished SETUP for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 3.838538 seconds (PASS)
Starting SHAREDLIB_BUILD for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Finished SHAREDLIB_BUILD for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 343.197531 seconds (PASS)
Starting MODEL_BUILD for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 4 procs
Starting SHAREDLIB_BUILD for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 1 procs
Finished SHAREDLIB_BUILD for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 499.982464 seconds (PASS)
Finished MODEL_BUILD for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 500.002066 seconds (PASS)
Starting MODEL_BUILD for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 4 procs
Starting RUN for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 with 1 proc on interactive node and 360 procs on compute nodes
Finished RUN for test ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 in 18.836262 seconds (PEND)
Finished MODEL_BUILD for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 501.058495 seconds (PASS)
Starting RUN for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 with 1 proc on interactive node and 360 procs on compute nodes
Finished RUN for test ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 in 15.438890 seconds (PEND)
Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
PEND ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5 RUN
    **Case dir: /glade/scratch/cacraig/ERP_Ln9.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq9s_clm5.20170113_165437_fabsn8**
PEND ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5 RUN
    **Case dir: /glade/scratch/cacraig/ERP_Ln9.f09_f09.F1850_DONOTUSE.yellowstone_intel.cam-outfrq9s_clm5.20170113_165437_fabsn8**
test-scheduler took 1367.86096001 seconds

**Comment by cacraigucar** [comment]
An alternative to echoing all of the Case Dirs at the beginning of the run would be to echo the timestamp qualifier which is attached to the end of all the Case Dirs.  This single line would allow users to easily find the correct directories while create_test is running (and before the case dirs are echoed at the end of create_test).
