### ISSUE TITLE
mpi-serial builds fail in pio build

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#700]
With cime at e9202d5 (which includes the PIO build update), all of my mpi-serial builds are failing. I see this error in the pio configure:

```
  /opt/ibmhpc/pe1307/ppe.poe/bin/mpcc: ERROR - mpi-serial is not a supported
  MPI library type.
```

Here's a sample, failing test: `ERP_Lm54_Mmpi-serial.1x1_numaIA.ICLM45BGCCROP.yellowstone_intel.clm-cropMonthOutput`

**Comment by rljacob** [comment]
Fixed in a previous PR
