### ISSUE TITLE
Add upper limit for the default number of pio io tasks for high-proc runs

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#702]
From our experiments with high resolution runs we find that
restricting the value of pio numiotasks (the default, when it
is set to "-1" in env_run.xml) to <=128 helps us overcome
a lot of "out of memory" errors. 
By default the number of pio iotasks set is pio_tasks/stride,
and this value can be quite large for high resolution runs (and
frequently results in "out of memory" errors).

**Comment by jayeshkrishna** [comment]
@jedwards4b : What do you think about this change (in csm_share/shr/shr_pio_mod.F90)?

**Comment by jedwards4b** [comment]
Seems like this is a machine dependent issue and would be more appropriate in the config_pio.xml file.

**Comment by jedwards4b** [comment]
Also are you seeing this behavior in pio1 or pio2 or both?

**Comment by worleyph** [comment]
My experience is a little different from @jayeshkrishna and @amametjanov , seeing up to 1024 pio tasks as being reasonable on some systems and cases, but the current PIO1 default is almost never appropriate for high resolution cases using large process counts.

**Comment by jayeshkrishna** [comment]
The defaults (pio_tasks/stride, stride=4) almost never work. Although performance might be better, for some cases/machines, with higher number of pio_iotasks (the optimal config can be set in config_pio.xml for that machine) the default configuration should work without the model crashing with "out of memory".
We have had several cases of these failures (and once someone manually tunes the iotasks to a lower value the problem goes away) with PIO1.

**Comment by jedwards4b** [comment]
I have no problem with changing the defaults and if you want to change the default stride in shr_pio_mod.F90 I think that's okay too - but restricting the max number of io tasks seems 
to be a setting more appropriate to config_pio.xml and on a per machine basis.

**Comment by jayeshkrishna** [comment]
Just to be clear, I am only proposing restricting the max number of io tasks if pio_stride and pio_numiotasks are set as default (-1) and the user expects CIME to calculate both of these parameters.
But I think I understand your point. I will explore setting the value (max number of io tasks) in config_pio.xml (per machine) then.

**Comment by worleyph** [comment]
@jayeshkrishna , just checking:

>  I will explore setting the value (max number of io tasks) in config_pio.xml (per machine) then.

This still refers to the default from using "-1", correct, and not a max when setting stride or numiotasks explicitly?

**Comment by jedwards4b** [comment]
Setting it in config_pio.xml would overwrite the -1 default setting but could be tuned for a particular machine, resolution and compset.     If you want to choose a different setting in shr_pio_mod.F90 to override the -1 I'm okay with that but I think it's better to adjust in terms of stride (and making sure that it's a multiple of tasks_per_node) than numiotasks.

**Comment by rljacob** [comment]
@jayeshkrishna is this feature still needed?

**Comment by rljacob** [comment]
@jayeshkrishna is this still an issue?
