### ISSUE TITLE
PR #689 has caused case.setup script to fail on ANL workstations

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#703]
In cime/scripts directory:
./create_newcase -mach anlworkstation -compiler gnu -case test_X_compute001 -compset X -res f19_g16
cd test_X_compute001
./case.setup

ERROR: Could not resolve value for val=$(dirname $(dirname $(which ncdump)))

It seems that this error is introduced by PR #689 (git checkout f6e3e14 has no such error)

**Comment by jayeshkrishna** [comment]
I don't see this error on blues+master. Let me try compute001

**Comment by jayeshkrishna** [comment]
I can recreate this issue on anlworkstation

**Comment by jayeshkrishna** [comment]
@jgfouca : Do you know why create_newcase might be failing on compute001 after PR #689 was merged?

**Comment by jayeshkrishna** [comment]
I am now able to recreate the problem on blues too. Specifying the "-compiler" option with create_newcase causes ./case.setup to fail while trying to resolve path to ncdump

**Comment by jedwards4b** [comment]
I think so.   It's a conflict with deciding when we are going to interpret from the environment vs when we expect things to be defined in xml.

**Comment by jgfouca** [comment]
Bash is no longer supported in that field. We'll need to use environment variables.
