### ISSUE TITLE
Understanding diffs in coupler between cime2 and cime5

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#706]
To help with the merge of cime5 in to ACME, we need to understand the differences between the coupler and share code in the two versions and especially which group of changes might produce bit-for-bit differences in an F-case.   Ideally, we would like to back out the BFB changes on the merge branch and make the CIME5 merge a bfb change to ACME (then add them back later with separate PRs)

Below, in no particular order are the files that have diffs grouped by commit along with the hash for using "git show".  Which ones will produce BFB differences?    ACME started with cime2.0.14 (Sept 3, 2015).

**Switch production code to use new gradient calculator**   7979df551
    driver_cpl/driver/prep_glc_mod.F90

**adding elevation class bounds to gradient calculator**  a24c07e587
    driver_cpl/driver/prep_glc_mod.F90
    driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90
    driver_cpl/shr/glc_elevclass_mod.F90

**Remove dependence of vertical_gradient_calculator on glc_elevclass_mod**  bf715bb6d7f
   driver_cpl/driver/prep_glc_mod.F90
   driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90

**Separate computation stage of gradient calculators**  58b85357  
   driver_cpl/driver/map_lnd2glc_mod.F90
   driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90
   driver_cpl/driver/vertical_gradient_calculator_base.F90
   driver_cpl/driver/vertical_gradient_calculator_continuous.F90
   driver_cpl/driver/vertical_gradient_calculator_factory.F90   NEW FILE

**water isotopes**   3d72660c01
    driver_cpl/bld/namelist_files/namelist_definition_drv.xml
    driver_cpl/driver/mrg_mod.F90   NEW FILE
    driver_cpl/driver/prep_ice_mod.F90
    driver_cpl/driver/prep_ocn_mod.F90
    driver_cpl/driver/prep_rof_mod.F90
    driver_cpl/driver/seq_diag_mct.F90
    driver_cpl/driver/seq_flux_mct.F90
    driver_cpl/shr/seq_flds_mod.F90
    share/csm_share/shr/shr_const_mod.F90
    share/csm_share/shr/shr_flux_mod.F90
    share/csm_share/shr/water_isotopes.F90   NEW FILE
    share/csm_share/shr/water_types.F90   NEW FILE

**Remove ESMF interface**  83e7e0f02  
   driver_cpl/cime_config/config_component.xml
   driver_cpl/driver/cesm_comp_mod.F90
   driver_cpl/driver/cesm_driver.F90
   driver_cpl/driver/component_mod.F90
   driver_cpl/driver/component_type_mod.F90
   driver_cpl/driver/cpl_comp_esmf.F90
   driver_cpl/driver/seq_diag_mct.F90
   driver_cpl/driver/seq_map_esmf.F90
   driver_cpl/driver/seq_map_mod.F90
   driver_cpl/driver/seq_map_type_mod.F90
   driver_cpl/shr/seq_comm_mct.F90
   driver_cpl/shr_esmf/esmf2mct_mod.F90
   driver_cpl/shr_esmf/esmfshr_attribute_mod.F90
   driver_cpl/shr_esmf/esmfshr_infodata_mod.F90
   driver_cpl/shr_esmf/esmfshr_mod.F90
   driver_cpl/shr_esmf/esmfshr_util_mod.F90
   driver_cpl/shr_esmf/mct2esmf_mod.F90   

**Added ESP component and SESP** 032abf22  
   driver_cpl/bld/build-namelist
   driver_cpl/bld/namelist_files/namelist_definition_drv.xml
   driver_cpl/cime_config/config_component.xml
   driver_cpl/cime_config/config_compsets.xml
   driver_cpl/cime_config/config_pes.xml
   driver_cpl/doc/chap1.xml
   driver_cpl/driver/cesm_comp_mod.F90
   driver_cpl/driver/component_mod.F90
   driver_cpl/driver/component_type_mod.F90
   driver_cpl/driver/seq_rest_mod.F90
   driver_cpl/shr/seq_comm_mct.F90
   driver_cpl/shr/seq_infodata_mod.F90
   driver_cpl/shr/seq_timemgr_mod.F90

**Remove flux_epbal and flux_albav**
   driver_cpl/bld/namelist_files/namelist_defaults_drv.xml   

**Update freezing point code**  6e3fecbb  b5956b94e9
  driver_cpl/bld/namelist_files/namelist_definition_drv.xml
  driver_cpl/driver/cesm_comp_mod.F90
  driver_cpl/shr/seq_infodata_mod.F90
  share/csm_share/shr/shr_frz_mod.F90.in  NEW FILE
  components/data_comps/dice/dice_comp_mod.F90
  components/data_comps/docn/docn_comp_mod.F90

**Brought in new coupler field needed for mosart**   25a8e5a667
  driver_cpl/driver/cesm_comp_mod.F90
  driver_cpl/driver/prep_rof_mod.F90
  driver_cpl/driver/seq_diag_mct.F90
  driver_cpl/driver/seq_domain_mct.F90
  driver_cpl/shr/seq_flds_mod.F90 

**klindsay changes for mcog**    c2cd328446
  driver_cpl/bld/namelist_files/namelist_definition_drv.xml
  driver_cpl/cime_config/config_component.xml
  driver_cpl/driver/prep_ocn_mod.F90
  driver_cpl/shr/seq_flds_mod.F90  

**Fix bug regarding atm_present and TG cases**  502fb8810a
  driver_cpl/driver/seq_domain.mct.F90

**fix shr_flux_atmocn_diurnal restart problem related to cold start initialization logic**  8a80287d
  driver_cpl/driver/seq_flux_mct.F90
  share/csm_share/shr/shr_flux_mod.F90

**Workaround to not write a field called "hgt".** 416e9b35
   driver_cpl/driver/seq_io_mod.F90

**accommodate more VOC species in the VBS SOA chemistry scheme**  9a10d302
**updates to seq_drydep_mod** 84cbcde6
  driver_cpl/shr/seq_drydep_mod.F90

**add BARRIER_OPTION to driver and new logic for opening and**  
**closing files in the streams input to improve performance.**    89e1b548
    driver_cpl/bld/build-namelist
    driver_cpl/bld/namelist_files/namelist_defaults_drv.xml
    driver_cpl/bld/namelist_files/namelist_definition_drv.xml
    driver_cpl/cime_config/config_component.xml
    driver_cpl/driver/cesm_comp_mod.F90
    driver_cpl/shr/seq_timemgr_mod.F90
    share/csm_share/shr/shr_dmodel_mod.F90
    share/csm_share/shr/shr_strdata_mod.F90
    share/csm_share/shr/shr_stream_mod.F90

**update cime for pop single column and strm4d capabilities**   a3e75019
   driver_cpl/shr/seq_flds_mod.F90
   share/csm_share/shr/shr_dmodel_mod.F90
   share/csm_share/shr/shr_ncread_mod.F90
   share/csm_share/shr/shr_scam_mod.F90
   share/csm_share/shr/shr_strdata_mod.F90
   share/csm_share/shr/shr_stream_mod.F90

**Update C1DIAF streams**  af95400d
   share/csm_share/shr/shr_map_mod.F90

**A few tweaks needed to run 01col grid**  fd09d4fa
   driver_cpl/driver/seq_domain_mct.F90
   share/csm_share/shr/shr_map_mod.F90

**add pio_rearranger option to pio namelists fix issues with testing**  1bfe399b
**add pio1 communications options to namelist for pio1 only**  a12abc3e
   share/csm_share/shr/shr_pio_mod.F90

**Add `shr_RandNum_mod`** 8cbbc2e7f9  367f19912c
   share/shr_RandNum   NEW DIRECTORY

**Improve the accuracy of `shr_orb_cosz`**   148a48527de
   share/csm_share/shr/shr_orb_mod.F90

**Comment by billsacks** [comment]
I'll comment on the ones I know about

> Switch production code to use new gradient calculator 7979df5
> driver_cpl/driver/prep_glc_mod.F90
> 

Only relevant for cases that include an active GLC model - irrelevant in an F case.

> adding elevation class bounds to gradient calculator a24c07e
> driver_cpl/driver/prep_glc_mod.F90
> driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90
> driver_cpl/shr/glc_elevclass_mod.F90
> 

Only relevant for cases that include an active GLC model - irrelevant in an F case.

> Remove dependence of vertical_gradient_calculator on glc_elevclass_mod bf715bb
> driver_cpl/driver/prep_glc_mod.F90
> driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90

Only relevant for cases that include an active GLC model - irrelevant in an F case.

> 
> Separate computation stage of gradient calculators 58b8535
> 
> driver_cpl/driver/map_lnd2glc_mod.F90
> driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90
> driver_cpl/driver/vertical_gradient_calculator_base.F90
> driver_cpl/driver/vertical_gradient_calculator_continuous.F90
> driver_cpl/driver/vertical_gradient_calculator_factory.F90 NEW FILE
> 

Only relevant for cases that include an active GLC model - irrelevant in an F case.

> Fix bug regarding atm_present and TG cases 502fb88
> driver_cpl/driver/seq_domain.mct.F90

Only relevant in TG cases - irrelevant in an F case

**Comment by rljacob** [comment]
What is "klindsay changes for mcog"?

**Comment by rljacob** [comment]
@apcraig the commit that introduced the rofdto field to the coupler is called "runoff direct to ocean" but its passed to mosart.  How does it get to the ocean?  And what does it mean that ACME doesn't have this in its coupler right now?

**Comment by rljacob** [comment]
Removed  "Diurnal ocean feature from exp tag cesm1_3_aofluxd02" f84ab34 from above list because ACME already has that.

**Comment by apcraig** [comment]
this was a field requested by folks in CESM.  You should talk to the 
CESM land folks for more info.  It's not clear it still in use.  But my 
understanding is that they wanted a separate field that would be passed 
to mosart and then mosart would send that flux directly to the ocean.  
Mosart is implemented with a few different paths to the ocean including 
a direct method.  Mosart in ACME and mosart in CESM are almost the same, 
but some of the details of the coupling are a little different.  If that 
field is not used in ACME, I am pretty certain there is no problem.  
Some of the water sent to mosart is direct routed in ACME without the 
using the rofdto field too.  Ruby should be aware of the scientific issues.

**Comment by rljacob** [comment]
Once the Depends.Intel issue was discovered, I went back to an F-case with all the above and only the shr_orb change will change answers between cime2 and cime5.

**Comment by rljacob** [comment]
The above is true for most cases. See Issue #837 .
