### ISSUE TITLE
ERP test doesn't halve the number of ESP tasks

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#723]
The ERP test has

                # halve the number of tasks and threads
                for comp in ['ATM','CPL','OCN','WAV','GLC','ICE','ROF','LND']:

I think ESP should be included here, too. Without it, we are sometimes getting PE layouts where most components are running on N tasks, but ESP is running on 2N tasks.

**Comment by jedwards4b** [comment]
There is now a method to get the components_class list and that should be used.
comp_classes = case.get_values("COMP_CLASSES")

**Comment by billsacks** [comment]
I'll make this change along with the fix for #687
