### ISSUE TITLE
driver_cpl: With some PE layouts, on a restart, fractions_ax is accessed without being allocated

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#724]
Testing the CLM trunk with cime5.2.0-alpha.5 (but I don't see any driver_cpl updates to cime since that tag), I'm getting failures in all ERP debug tests with hobart-nag: e.g., from `ERP_D_Ld5_P24x1.f10_f10.I1850CLM45BGC.hobart_nag.clm-ciso.GC.1025-0639.45.n`

```
Runtime Error: /home/sacks/cesm_code/cime_update_cesm2_0_beta03_ish/cime/driver_cpl/driver/cesm_comp_mod.F90, line 1955: Reference to undefined POINTER FRACTIONS_AX
```

I think there might actually be two problems contributing to this error:

(1) Due to #723 ESP is running on 24 tasks while the rest of the system is running on 12 tasks

(2) This issue at hand: It appears that fractions_ax is only allocated on the coupler PEs, but is accessed on all PEs when doing a restart: In cesm_comp_mod.F90:

Line 1744:

``` fortran
   if (iamin_CPLID) then
      call t_startf ('CPL:init_fracs')
      call t_adj_detailf(+2)

      allocate(fractions_ax(num_inst_frc))
      allocate(fractions_lx(num_inst_frc))
      allocate(fractions_ox(num_inst_frc))
      allocate(fractions_ix(num_inst_frc))
      allocate(fractions_gx(num_inst_frc))
      allocate(fractions_rx(num_inst_frc))
      allocate(fractions_wx(num_inst_frc))
```

Line 1954:

``` fortran
   if (read_restart) then
      call seq_rest_read(rest_file, infodata, &
           atm, lnd, ice, ocn, rof, glc, wav, esp, &
           fractions_ax, fractions_lx, fractions_ix, fractions_ox, &
           fractions_rx, fractions_gx, fractions_wx)
   endif
```

It looks to me like this has been a long-standing issue: the relevant code looks the same back to at least March, 2015 (pre-cime1). It seems like this would be a problem whenever you do a restart with a PE layout where the coupler is on a subset of the PEs. I'm not sure why this hasn't triggered an error before - maybe it's only picked up by nag in debug mode, and we don't typically run with these PE layouts there?

cc @fischer-ncar @jedwards4b @apcraig

**Comment by jedwards4b** [comment]
It looks like it just needs to be ```   if ( read_restart .and. iamin_CPLID) then```

**Comment by rljacob** [comment]
Make sure the bug fix branch for this starts before the cime5.1 branch.

**Comment by apcraig** [comment]
if you look, there is an "iamin_CPLID" inside the seq_rest_write. it 
doesn't necessarily
need to be added in the driver.  i don't think the fractions are 
accessed on non-cpl
pes.  is nag complaining that the there are unallocated arrays passed in 
an interface?

tony......

**Comment by billsacks** [comment]
@apcraig - good point. So I think this wouldn't cause any problems in practice. Yes, this is an instance of nag being picky: If I remember correctly, it doesn't like unallocated pointers passed through an interface, unless the dummy arguments are declared as pointers (which they are not here).

So another solution would be to move these allocate statements:

```fortran
      allocate(fractions_ax(num_inst_frc))
      allocate(fractions_lx(num_inst_frc))
      allocate(fractions_ox(num_inst_frc))
      allocate(fractions_ix(num_inst_frc))
      allocate(fractions_gx(num_inst_frc))
      allocate(fractions_rx(num_inst_frc))
      allocate(fractions_wx(num_inst_frc))
```

to outside the CPLID conditional - if you think it would be more robust to keep the call to seq_rest_read happening on all PEs.

**Comment by apcraig** [comment]
i think it's better to add the extra if CPLID in the driver around the 
restart call
rather than allocate the arrays on all pes.  Maybe we should remove the if
CPLID in the restart code at the same time, but i guess that's not critical.
Only a problem if the "if CPLID" is ever changed in the driver to another
set of pes and then old "if CPLID" is still in the restart code.

tony....

**Comment by billsacks** [comment]
> Maybe we should remove the if
> CPLID in the restart code at the same time

Yeah, I wondered that too - and then saw that the seq_rest_write call currently has an if CPLID conditional around the call as well as within it... so at least the two are now consistent, for whatever that's worth....
