### ISSUE TITLE
case.build should set BUILD_COMPLETE=FALSE if a subsequent build fails

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#732]
I see this in cime5.1.1. And assume unless someone's done something about it that it still exists.

If I setup and run a case successfully, so now BUILD_COMPLETE==TRUE, but then change code and run case.build over again, but this time I screwed something up so the build fails (BUILD_COMPLETE still is TRUE so I can submit and run my case [but it will use the exe before my changes]). I'd really like it to set BUILD_COMPLETE=FALSE so that I know it didn't compile.

Also as part of this, it's not obvious that the build step fails as it is currently. I can see it only with

stat=1

reported somewhere in all the standard output. I'd like it to report this in a more obvious manner at the end of the case.build.

**Comment by jedwards4b** [comment]
I have not been able to reproduce the problem you reported of BUILD_COMPLETE not being reset to FALSE on a build failure - please provide a specific example that I can try to reproduce.

**Comment by jedwards4b** [comment]
And we've done some work on the build since cime5.1.1 so please use the current trunk.

**Comment by jedwards4b** [comment]
I have submitted PR #736 which I believe resolves this issue, in the end I did find a case that reproduced your results.  (clm45 clm50 errors were not being handled the same as other components)

**Comment by ekluzek** [comment]
From the pull request it looks like this was also a potential problem with the aqua-planet build as well.
