### ISSUE TITLE
Testmods get applied repeatedly rather than just once during create_newcase

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#734]
See #692 for the original report of this issue.

In cime4, I'm pretty sure that testmods / user_mods were applied at create_newcase time, ensuring that they were applied once and only once. Now they are applied both at create_newcase time and also in case.setup. The implications are:
1. The xmlchange commands get executed repeatedly. Often this has no effect, but for these `--append` options, it leads to xml variables like this (for the CLM test `ERP_P60x2_Lm36.f10_f10.ICRUCLM50BGCCROP.yellowstone_intel.clm-clm50cropIrrigMonth_interp`):
   
   ``` xml
   <entry id="CLM_BLDNML_OPTS" value="-fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -fire_emis -irrig .true. -bgc bgc -crop">
   ```
2. We have code to check if the contents of a given user_nl file from testmods have already been applied to the user_nl file in the case directory, and if so, don't reapply them. This code wasn't needed in cime4, because testmods were applied once and only once. This new code generally won't cause problems, but it (a) leads to additional complexity, and (b) can be wrong in some edge cases. An example of such an edge case is where testmod 'foo' includes 'bar' which includes 'default'. 'default' sets `x = 17` (among other things), 'bar' sets `x = 42`, then 'foo' sets `x = 17` (as the only thing that it sets). The desired behavior here would be to use the last setting, `x = 17`; but I believe that the current implementation will keep `x = 42`, because it will skip applying the 'foo' testmods.

Is there a reason why cime5 applies testmods in this later stage and repeatedly, rather than following what was done in cime4 and just applying them once at create_newcase time? Can the call from case.setup be removed? I believe this would also allow us to remove the code for checking if the contents of a user_nl file have already been applied.

**Comment by billsacks** [comment]
It looks like the case.setup call to apply_user_mods was put in to handle some multi-instance cases - applying the user_mods to each instance. This change was made in ca97ca9eabf1d564a08ac17ab99c4f494aebfbe6 / #261 . I'm thinking that it was specifically needed for NCK tests, where one of the runs sets NINST=2, but that's not known at create_newcase time.

To me, it feels like it would be cleaner to move this special-purpose functionality (i.e., replicating the user_nl files to user_nl_foo_0001 and user_nl_foo_0002) into the NCK test itself (and similar NC* tests). I could imagine having a function in `utils/python/CIME/SystemTests/test_utils/user_nl_utils.py` like:

```python
def copy_user_nl_files_to_multiinst(caseroot, num_multiinst):
    """
    For each file user_nl_foo, copy user_nl_foo to user_nl_foo_0001,
    user_nl_foo_0002, etc., up to user_nl_foo_<num_multiinst>.

    Args:
        caseroot (str): Full path to the case directory

        num_multiinst (int): Number of instances
    """
```

(or there could also be a 'component' argument, and then it's up to the caller to loop through the appropriate components).

This way, we could remove the code from case.setup that leads to repeated application of testmods, remove the code for checking duplicate contents in user_nl files, and just restrict the complexity to the tests that actually need it.

**Comment by jedwards4b** [comment]
Yes, that's why its in case_setup.py but its not just for testing, if a user changes the NINST value in a case the user_nl_ files created by case_setup currently have the testmods applied.  Putting something in NCK to handle this only fixes part of the problem.   We could however add code to case_setup that copies the user_nl_* files to instance files if the instance files did not already exist.  I think that this would fix both NCK and this scenario.

**Comment by billsacks** [comment]
Ah, interesting. I'm not sure exactly what the use case is for this non-test multi-instance case you're describing, so am a bit reluctant to suggest a possible implementation. But if the desired behavior is: When NINST gets extended, say from 4 (old value) to 5 (new value), then copy any user_nl_foo file _in the case directory_ to user_nl_foo_0005. Note that I'm suggesting using the user_nl_foo file in the case directory, rather than re-applying the user_mods. That means that, if the user added anything in user_nl_foo, it would get applied to the new instance; I'm not sure if that's what is desired or not.

If that _is_ the desired behavior, then I think it could be applied in `_build_usernl_files`, like this: #735 

Let me know if that's the desired behavior; if so, I can do some testing on #735
