### ISSUE TITLE
Convert lt_archive.sh script to python and add command line arguments

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#740]
lt_archive.sh needs to be converted to python. It will be called from the existing
case_lt_archive.py script. 

It needs to include 2 arguments:
--dryrun  - print messages out to the log for what the actions would be without copying any files to HPSS
--delete   - delete files from DOUT_S_ROOT upon successful copy to HPSS. This option is a null-op when --dryrun is selected.

**Comment by rljacob** [comment]
In a telecon on 4/26/17, we decided not to do this. 

>  A long-lived branch is adding tons of complexity. External tools can do better. Current lt-archive is in bash and only recognizes 2 layers of directories in short-term. Short-term is adding more. queue dependency issue: depends on success of short. Can't restart. Might run at same time as short-term.
> 
> decision: we will remove bash lt_archive.sh script. Can't pythonize/test/support it.
