### ISSUE TITLE
Hard to find reason for NLCOMP failure in TestStatus.log

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#741]
Apologies for not giving concrete examples, I cleaned up a lot of old testing directories before realizing I should keep the results to include in this ticket. But basically, I had two different causes for `NLCOMP` failures in various tags -- one was a change in `user_nl_pop` and the other a change in `pop_in`. The `TestStatus` file just reads `FAIL ... NLCOMP`, and then the `TestStatus.log` file is several hundred lines long with no clear way to search for these namelist-generated fails. Could we include the `NLCOMP` keyword along with a message about which file(s) is/are to blame for the fail somewhere in the log?

**Comment by jgfouca** [comment]
@mnlevy1981 sorry for taking so long to get around to this. The modifications were simple.
