### ISSUE TITLE
unset environment variables after module purge

### ISSUE THREAD

**Issue by singhbalwinder** [ESMCI/cime#771]
I often use the following sequence of commands in my machines files:
```
module purge
unsetenv LD_LIBRARY_PATH

....load modules for specific compiler/netcdf/mpi
```
In principle, `LD_LIBRARY_PATH` should have no entries after `module purge` command. However, it is not always the case. For example, if a user manually adds something to  `LD_LIBRARY_PATH`, it wont be removed by module purge. In some cases, users may load modules in such a sequence that `module purge` may not be able to clear entries in `LD_LIBRARY_PATH`. I come across these issues quite often and un-setting `LD_LIBRARY_PATH` variable almost always resolves these kind of issues.

Right now, we cannot unset a variables to achieve the above sequence of commands.

I am also interested in knowing if other folks have encountered this issue and if they have a better solution.

**Comment by apcraig** [comment]
There is also a need to allow relatively arbitrary strings in the env_mach_specific file.  This was easily possible in the past when this file was a simple shell scripts.  It also was extremely easy for users to modify this file and for port testing to be carried out when it was simpler.  In particular, we need 

limit coredumpsize unlimited
limit stacksize unlimited

for some machines, but there could be a lot of others things that might be needed.  It is critical that the env_mach_specific equivalent file can be setup as needed with a significant amount of flexibility such that the model can be used out of the box without any problems.  There should never be settings required in the local user login scripts.  It should also be easy for users to set this up when porting or for users to modify the file in cases where the underlying machine system setup has changed and the file needs to be modified.

**Comment by billsacks** [comment]
This has had the "critical" label for nearly 6 months. #1847 "addressed" it, but doesn't say it fixed it. Is this still a critical issue?

**Comment by jgfouca** [comment]
Closing. Please reopen if you think addition work is needed.
