### ISSUE TITLE
Handle GSWP3 forcing for CESM_BGC option

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#773]
Here's a simple change to allow GSWP3 forcing to work in transient cases..

diff --git a/driver_cpl/cime_config/config_component.xml b/driver_cpl/cime_config/config_component.xml
index ded21cb..f176a33 100644
--- a/driver_cpl/cime_config/config_component.xml
+++ b/driver_cpl/cime_config/config_component.xml
@@ -3042,8 +3042,8 @@
       <value compset="_DATM"    >none</value>
       <value compset="_BGC%BPRP">CO2C</value>
       <value compset="_BGC%BDRD">CO2C</value>
-      <value compset="HIST.*_DATM%(QIA|CRU)">CO2A</value>
-      <value compset="RCP.*_DATM%(QIA|CRU)" >CO2A</value>
+      <value compset="HIST.*_DATM%(QIA|CRU|GSW)">CO2A</value>
+      <value compset="RCP.*_DATM%(QIA|CRU|GSW)" >CO2A</value>
     </values>
     <group>run_coupling</group>
     <file>env_run.xml</file>

Note as a separate issue, we should possible add 1PT (for tower sites) as well, but 1PT is not currently setup for transient cases so that might be more involved.

**Comment by billsacks** [comment]
@ekluzek - is this needed for cesm2?

**Comment by ekluzek** [comment]
Yes, it's a simple change that we should just do.

**Comment by mvertens** [comment]
I don't like having each new mode of DATM be part of the CCSM_BGC. CO2A is important only when you have CLM in place. I propose the following for config_component_cesm.xml.

 <entry id="CCSM_BGC">
    <type>char</type>
    <valid_values>none,CO2A,CO2B,CO2C,CO2_DMSA</valid_values>
    <default_value>none</default_value>
    <values>
      <value compset="_CAM">CO2A</value>
      <value compset="_DATM">none</value>
      <value compset="_DATM%CPLHIST.+POP\d">CO2A</value>
      <value compset="HIST.*_DATM.*_CLM">CO2A</value>
      <value compset="RCP.*_DATM.*_CLM">CO2A</value>
      <value compset="_BGC%BPRP">CO2C</value>
      <value compset="_BGC%BDRD">CO2C</value>
    </values>
    <group>run_coupling</group>
    <file>env_run.xml</file>
    <desc>Flag to turn on new fields in coupling.
    If the value is not none, the coupler is compiled so that optional
    BGC related fields are exchanged between component models.
    </desc>
  </entry>
