### ISSUE TITLE
Run Fortran unit tests automatically as part of test suites

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#787]
This issue came up today in a discussion with @mvertens @jedwards4b @jgfouca @rljacob @agsalin @mfdeakin-sandia 

We'd like to run the Fortran unit tests automatically when you run a test suite. In my mind, this applies to both the cime Fortran unit tests and any component's unit tests (currently mainly used in CLM).

At the time, we thought of having a system test that just runs the unit tests, and then you could add this system test to the test suite. But upon further reflection, I don't think that makes sense, because the current system test infrastructure assumes you have a case, with a compset, grid, etc., and that makes no sense for the unit tests.

I'm thinking it would make more sense to run these via some higher-level wrapper, which runs these unit tests along with various other tests. For cime, this could fit into scripts_regression_tests, although I'm not sure if that's the right home for it, because this has nothing to do with testing the scripts. For component models, we'd presumably have some other wrapper script specific to that component model. (e.g., for CLM, we could have a script that fires off the CLM system test suite and unit tests all at once.)

**Comment by jedwards4b** [comment]
I agree that it's not a system test and it doesn't belong in scripts_regression_tests.   What steps currently need to be taken to run the cime fortran unit tests?  Can we update the wiki with that information?

**Comment by billsacks** [comment]
> I agree that it's not a system test and it doesn't belong in scripts_regression_tests. What steps currently need to be taken to run the cime fortran unit tests? Can we update the wiki with that information?

This is documented in cime/README.unit_testing. The wiki currently points to that file.

There are some outstanding issues related to making this more generic - i.e., not yellowstone-specific. e.g., https://github.com/CESM-Development/cime/issues/92 and https://github.com/CESM-Development/cime/issues/12

**Comment by billsacks** [comment]
Jim Edwards addressed this for the Fortran unit tests within cime by adding them to scripts_regression_tests (we felt this wasn't their ideal home, but would do well enough).

What remains is coming up with a general solution for running components' unit tests as part of their test suites.

**Comment by jgfouca** [comment]
Maybe take the "fake" system test approach used for HOMME?

**Comment by billsacks** [comment]
Looking back at my original comment: At this point we have introduced a CLM-specific wrapper script for running the CLM system tests, so in principle we could run the unit tests from there, too. However, at the moment I prefer @jgfouca 's idea of using the "fake" system test approach, mainly because it leads to more consistent reporting of the test results.

This amounts to having a "system" test that runs `cime/scripts/fortran_unit_testing/run_tests.py` with appropriate settings for `--test-spec-dir` (for cime this is simply the top-level cime directory; for CLM this is the src subdirectory, etc.) and `--build-dir`. The full output from this should be captured in something like TestStatus.log.
