### ISSUE TITLE
Make a batch system-specific entry for the signal sent when wallclock time is exceeded

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#793]
#755 introduced a check for whether a test has been killed due to running out of wallclock time, by catching the appropriate signal. Currently this catches all signals that we have found lead to this condition. Eventually, we'd like to introduce a machine-specific entry, e.g., in env_batch.xml, that specifies the signal on a given machine / batch system.

cc @jgfouca @jedwards4b

**Comment by billsacks** [comment]
On today's cime telecon, we weren't sure whether to keep this one open. I read back through the discussion in #755. Both @jedwards4b and I requested the change mentioned in this issue, and I still feel it would be helpful, particularly because the signal list includes some very generic things like SIGUSR1 and SIGUSR2:

https://github.com/ESMCI/cime/blob/83ea95c94084c929499895840240b29433dcbe57/scripts/lib/CIME/case/case_test.py#L42

My sense is that the code for addressing this issue shouldn't be too hard: we need a new variable in config_batch.xml (probably) that defines the signal(s) that are sent by each batch system when a job is killed due to either timing out or some other reason (like the user kills it). Then we replace this hard-coded list with a use of that variable. The hardest part is probably determining which signals are possible for each batch system type, but since we currently only support 5 (cobalt, lsf, pbs, moab, slurm), maybe that won't be so bad?

I'm unassigning myself, though, since I was only assigned in order to determine if this should be kept open.

**Comment by rljacob** [comment]
@billsacks still wanted?

**Comment by billsacks** [comment]
Well, on the one hand, I still think the earlier discussion holds: ideally this would be changed so that we don't assume a signal means running out of wallclock time when really it means something different on this batch system. On the other hand, if it hasn't caused any noticeable issues in 6 years, maybe it can be left as is.

So I'm fine closing this if others are. @jedwards4b @jgfouca or others feel free to reopen if you feel this should still be done.
