### ISSUE TITLE
XML option to control email at end of the run

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#797]
On slack, @rljacob said
> Some people want to turn off or on the "email at end of job" setting.

This is something I would like to be able to control, and I think `env_batch.xml` is the way to do it:

> I was thinking it would be nice to run `./xmlchange JOB_EMAIL_ON_COMPLETION=...` either as a binary or a string compare (`valid_values=always, if_success, if_failure,never`?)

I think the actual XML variable name and the best implementation is still open for debate.

**Comment by billsacks** [comment]
I like this idea. I feel that making the if_failure option useful - for tests, anyway - depends on #614 

But I'd also say: It feels like this is an option that you'd want to be able to specify as an option to create_test, or possibly via your .cime_config directory (or whatever it's called) in your home directory - because needing to change this setting manually for each case would be more work than just deleting the email.

**Comment by erichlf** [comment]
Should we default to the user email in the users profile, or should the user be required to specify an email? I am not sure all batch systems allow a user specified email though and some batch systems require a user email be provided (cobalt).

For cobalt, I can't seem to see how to control when an email is sent. For cobalt, all I see is where to send an email and it seems to default to start and stop.
http://trac.mcs.anl.gov/projects/cobalt/wiki/qsub.1.html

For LSF, controlling email output isn't controlled by a keyword followed by and argument. In fact, each email option appears to be controlled by a flag. In this case I am unsure how to control this in the xml config/*/machines/config_batch.xml
http://www.vub.ac.be/BFUCC/LSF/man/bsub.1.html

**Comment by jedwards4b** [comment]
I think maybe what you want is a way to modify directives and/or specify additional directives in
the env_batch.xml file.   If we first develop that capability it will make it easier to add the specific case of adjusting email settings.

**Comment by erichlf** [comment]
currently we have the batch_args, which allows this control already and I developed that for exactly this reason. Of course, what this is is more specific. Using batch_args is the current workaround though.

I will move forward and see how things progress.
