### ISSUE TITLE
Attribute for testing vs. scientifically supported compsets

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#804]
From the Sept 12, 2016 CSEG meeting notes:
_______

Earlier idea was to have a test_alias (rather than alias for this).

But idea from today's discussion is to have a separate support_level attribute. Possible values are:
Scientifically supported
Functionally supported
Testing only
(And then there are user_compsets that don't match an alias, which is another level: "You're on your own").

Then, when you ask for a list of possible compsets, you'd by default only get a list of scientifically supported and functionally supported... but you could ask to see testing-only as well. (And I think the discussion is that you'd need to explicitly ask if you want to create a case with one of these testing-only compsets using create_newcase.)

Sheri: Points out that scientific support is tied to grid. Maybe need an attribute describing that.
___________________

This is becoming important.  A user on the bulletin board posted a question.  During his discussion, as an aside, he said he was using the Bi1850 compset.  This is a compset which is for testing isotopes only and shouldn't be used for science runs currently.  This user naively used it as it seemed to fit his requirements the best (without understanding the subtleties of all the %WISO fields).

**Comment by billsacks** [comment]
@cacraigucar - this is a duplicate of #533 . Can you please move any new comments there and then close this issue?

**Comment by cacraigucar** [comment]
Closed because it was a duplicate

**Comment by cacraigucar** [comment]
Closed
