### ISSUE TITLE
Stampede support

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#821]
Stampede is unable to submit jobs to the queue from the compute nodes.  This is a problem with archiving and continuation runs.  The scripts will need to ssh to the login node in order to submit jobs to the queue.  According to @jedwards4b, there is code for mira that already does this.

**Comment by jedwards4b** [comment]
It occurs to me that this could be as easy as changing 
```<batch_submit>qsub </batch_submit>```
for that system to 
```<batch_submit>ssh loginnode qsub </batch_submit>```
in config_batch.xml for that system - could you try this?
