### ISSUE TITLE
NCK_N3 doesn't work as intended

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#838]
In PR #835 @fischer-ncar changed ERR_N3 to NCK_N3. However, the _N3 doesn't do anything in an NCK test: this runs just like a normal 2-instance test (confirmed by setting up `NCK_N3.f45_g37.A.yellowstone_intel`).

cc @jedwards4b

**Comment by fischer-ncar** [comment]
This was fixed in cime5.2.0-alpha.14.
