### ISSUE TITLE
python user_nl parser doesn't understand +=

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#839]
The perl user_nl parser (Namelist.pm) has the capability to parse '+=': from the documentation:

```perl
# In addition to accepting 'variable = value', the parser also accepts 'variable
# += value'. The latter will append the new value to any existing value(s) for
# the given variable, separating values with commas. For example, this lets you
# specify:
#
# hist_fincl1 += 'foo'
# hist_fincl1 += 'bar'
#
# and the final setting of hist_fincl1 will then be:
#
# hist_fincl1 = 'foo','bar'
```

We use this feature extensively for CLM testmods.

This feature appears not to have been carried over to the python: In an A compset test, I tried adding:

```
mapmask += 'nomask'
```

in user_nl_datm and got:

```
  errput: ERROR: Error in parsing namelist: expected '=' but found '+' at line 3, column 8
```

(I'm not sure that you'd use += for that particular use case in practice - I just did it to test the infrastructure.)

cc @mvertens

**Comment by jedwards4b** [comment]
If this feature is used extensively why hasn't the problem been found before now?

**Comment by billsacks** [comment]
Because CLM is not yet using the python parser? (its build-namelist is still in perl)

**Comment by jedwards4b** [comment]
Ah - that makes sense - thanks.
