### ISSUE TITLE
module load errors

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#841]
Module load errors are not echoed to the screen and do not cause the build to abort.

**Comment by jedwards4b** [comment]
This seems to be system dependent.  I found the problem on cori and tried to reproduce on yellowstone, but yellowstone seems to correctly error and abort if a module error occurs.

**Comment by jedwards4b** [comment]
The module load call is issued from env_mach_specific function _load_module_modules which
calls run_cmd_no_fail from utils.py.   This function is looking for a non-zero return code but the module system is returning a zero return code even though the err code is written to stderr.

**Comment by jgfouca** [comment]
This is a well-known issue with modules in general. We'll have to resort to grep.

**Comment by jedwards4b** [comment]
I think that what I've done covers it - is there a case where stderr is not empty but there is no error?

**Comment by jgfouca** [comment]
@jedwards4b yes, your solution looks good to me
