### ISSUE TITLE
preview_namelists generates errors for an I compset

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#847]
From latest cime master, in clm4_5_13_r205:

```
./create_newcase -case test_1129a -compset ICLM45 -res f19_g16
cd test_1129a/
./case.setup
./preview_namelists
```

gives these errors (amongst other output):

```
  errput: ERROR: No variable GLC_SMB found

  errput: ERROR: No variable TESTCASE found
```

These errors did not appear in cime5.2.0-alpha.7

preview_namelists _appears_ to work despite those errors. It's not clear to me if these are new errors, or just newly-detected errors.

cc @mvertens

**Comment by jedwards4b** [comment]
These are output from the xmlquery command as per issue #826 and PR #836 
The messages are not acted upon and can be safely ignored, but the fix would be in the buildnml command that is querying these fields that don't exist.

**Comment by jedwards4b** [comment]
looks like they are in clm (GLC_SMB) 
and rtm (TESTCASE)

**Comment by billsacks** [comment]
Ah, okay, thanks Jim.

I realized that (I think) the GLC_SMB variable can be removed... I'll do that.

I'm not sure what should be done about TESTCASE: it's accessed near the top of rtm's buildnml like this:

```perl
my $TESTCASE            = `./xmlquery  TESTCASE		 -value`;
```

and then used in an error check like this:

```perl
			    if ($GET_REFCASE eq 'TRUE') {
				if ($TESTCASE eq 'SBN') {
				    # do nothing
				} else {
				    die "ERROR rtm buildnml: GET_REFASE is TRUE, so aborting because couldn't find files";
				}
			    }
```

It seems like either:

1. rtm's buildnml needs more logic to only try to get TESTCASE if this is actually a test

2. xmlquery needs to support something like a -default argument that provides a default value to return if the given variable isn't found, for cases like this. I'm thinking of something like python's dictionary `get` method, which supports an optional default value if the key isn't found.

If we want to go with (1), then I'll move this issue to an RTM bug; if (2), then I'll keep it open as a cime issue.

Also cc'ing @ekluzek

**Comment by jedwards4b** [comment]
There is no SBN test so we can get rid of this.

**Comment by billsacks** [comment]
Okay, moved to http://bugs.cgd.ucar.edu/show_bug.cgi?id=2381

**Comment by mvertens** [comment]
I have refactored rtm's build-namelist to be totally python - and am in the
process of testing it. I'll make sure this is taken care of then.
