### ISSUE TITLE
When are the names of coupler fields important?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#849]
At the top of seq_flds_mod, there is a documented naming convention for fields, which in addition to discussing the importance of the first letter (F vs. S), includes this:

```Fortran
  !    If flux prefix has first letter of P (so first five characters are PFlmn_)
  !    then flux is passed straight through without scaling by the corresponding fraction)
```

However, from some quick searches through the code, it looks like these first letters only have an impact on the mapping for fields merged to atm or ocn.

Can someone clarify (ideally via a PR that updates the seq_flds_mod documentation, but if you do it in an issue comment, I can update the Fortran myself): When does changing a coupler field name change the way it is mapped / merged, and when can you change the field name without changing behavior? Or conversely (asking the actual question I'm interested in): When do you need to change a field name in order to change how it is mapped / merged?

cc @whlipscomb @apcraig @mvertens

**Comment by apcraig** [comment]
There is a PF field, PFioi_swpen_ifrac_, but I don't think I've ever seen that feature used and don't know when it came into being.  That feature also seems to be available as part of the custom field list stuff which I don't know much about.  The PF feature does seem part of some of the merge logic though.  In general, the state and flux lists determine how fields are mapped while the individual field naming convention does not play a role in mapping.  If you put a state in a flux list of vice versa, you will map via the list it's in, not it's name.  For merging, much of that is done via field name matching.  So in that case, it's important to make sure the field part of the field name is consistent across multiple component coupling field lists.  The merges are self documenting in the cpl.log file, so you can always check to see what the coupler is doing by reviewing the cpl.log output.  To try to answer your question, if you want to change how a field is mapped, you need to add it to a different list of fields.  If you want to change how it's merged, then you might need to change the field name.  That's probably incomplete, but is a starting point for further discussion and clarification.

**Comment by billsacks** [comment]
Thanks a lot, Tony. @mvertens , do you know more than this? In particular, what aspects of the field naming convention affect behavior of the merge - e.g., in mrg_mod? For example, if I rename a field from S... to F..., but keep it in all the same lists (i.e., keep it in the state lists), will behavior change in some circumstances?

**Comment by mvertens** [comment]
I have to review this and get back to you Bill - but I'm in an off-site
meeting the next two days. I think renaming a field from S to F it will
change the behavior.

**Comment by mvertens** [comment]
If you look at the top of seq_flds_mod.F90 - the naming convention is the
following:

!  ---------
  !  definitions:
  !  ---------
  !  state-prefix
  !    first 3 characters: Sx_, Sa_, Si_, Sl_, So_
  !    one letter indices: x,a,l,i,o,g,r
  !    x => coupler (mapping, merging, atm/ocn flux calc done on coupler
procs)
  !    a => atm
  !    l => lnd
  !    i => ice
  !    o => ocn
  !    g => glc
  !    r => rof
  !    w => wav
  !
  !  state-name
  !    what follows state prefix
  !
  !  flux-prefix
  !    first 5 characters: Flmn__
  !    lm => between components l and m
  !    n  => computed by component n
  !    example: Fioi => ice/ocn flux computed by ice
  !    example: Fall => atm/lnd flux computed by lnd
  !    If flux prefix has first letter of P (so first five characters are
PFlmn_)
  !    then flux is passed straight through without scaling by the
corresponding fraction)
  !
  !  flux-name
  !    what follows flux-prefix
  ---------
  !  rules:
  !  ---------
  !  1) states:
  !     a) atm attributes fields that HAVE a state-prefix of Sx_ in
seq_flds_x2a_states
  !        rule: will merge all identical values of the state-names from
  !           seq_flds_i2x_states
  !           seq_flds_l2x_states
  !           seq_flds_o2x_states
  !           seq_flds_xao_states
  !         to obtain output state-name in seq_flds_x2a_states
  !
  !        rule: to merge input states that originate in the
  !           lnd (l2x_a) will be scaled by the lndfrac
  !           ice (i2x_a) will be scaled by the icefrac
  !           cpl (xao_a) will be scaled by the ocnfrac
  !           ocn (o2x_a) will be scaled by the ocnfrac
  !
  !        example:
  !           seq_flds_l2x_states = "Sl_t"
  !           seq_flds_i2x_states = "Si_t"
  !           seq_flds_o2x_states = "So_t"
  !           seq_flds_x2a_states = "Sx_t"
  !           attribute fields Sl_t, Si_t, So_t, in
  !           attribute vectors l2x_a, i2x_a, o2x_a will be
  !           merged to obtain attribute Sx_t in attribute vector x2a_a
  !
  !     b) atm attribute fields that DO NOT HAVE a state-prefix of Sx_ in
seq_flds_x2a_states
  !        rule: copy directly all variables that identical state-prefix
  !               AND state-name in
  !           seq_flds_i2x_states and seq_flds_x2a_states
  !           seq_flds_l2x_states and seq_flds_x2a_states
  !           seq_flds_o2x_states and seq_flds_x2a_states
  !           seq_flds_xao_states and seq_flds_x2a_states
  !
  !        example
  !           seq_flds_i2x_states = ":Si_snowh"
  !           seq_flds_x2a_states = ":Si_snowh"
  !           attribute field of Si_snowh in i2x_a will be copied to
  !           attribute field Si_snowh in x2a_a
 2) fluxes:
  !     rule: will merge all identical values of the flux-names from
  !         seq_flds_i2x_states
  !         seq_flds_l2x_states
  !         seq_flds_o2x_states
  !         seq_flds_xao_states
  !       to obtain output state-name in seq_flds_x2a_states
  !
  !     rule: input flux fields that originate in the
  !         lnd (l2x_a) will be scaled by the lndfrac
  !         ice (i2x_a) will be scaled by the icefrac
  !            - ignore all fluxes that are ice/ocn fluxes (e.g. Fioi_)
  !         cpl (xao_a) will be scaled by the ocnfrac
  !         ocn (o2x_a) will be scaled by the ocnfrac+icefrac

**Comment by billsacks** [comment]
@mvertens - thanks for this. The comments you pasted are where I started, but I couldn't tell for sure when the field name matters and when it doesn't. Poking around in the code, it looks like the field name is parsed in some of the routines in mrg_mod - e.g., for merging to atm / ocn, but seemingly not to the other components. In any case, it looked to me like there was special handling for certain components in this respect, and that's what I was hoping for some explicit documentation on.

**Comment by billsacks** [comment]
Closing this as a wontfix... the question was partly answered, but not completely. Oh well.
