### ISSUE TITLE
Split csm_share

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#852]
The csm_share library is a mix of several application libraries and should be split into 
several pieces.   This issue was discussed in CESM-Development/cime issue 18.

**Comment by jedwards4b** [comment]
Also see CESM_DEVELOPMENT issue 96

**Comment by jedwards4b** [comment]
This issue wasn't intended to be just about renaming the directory.  The intent is to separate the code into topic libraries.  I see three libraries:  foundation code like shr_kinds_mod.F90 or shr_const_mod.F90 doesn't have any dependencies within the model or with external libraries such as mpi,  mpi interface code doesn't have any internal dependencies but does depend on the mpi library and finally component interface code which may depend on pio.

**Comment by jgfouca** [comment]
This should be done in the CMake refactor.

**Comment by billsacks** [comment]
Closing since this no longer applies to CIME.
