### ISSUE TITLE
casename restrictions should be enforced 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#853]
There are certain characters which cannot be included in a casename, these characters should 
be trapped and an error reported.   This issue is moved from CESM-DEVELOPMENT/cime 38

**Comment by jedwards4b** [comment]
See also CESM-DEVELOPMENT issue 334

**Comment by billsacks** [comment]
In addition, scripts should check the case name length against the length currently allowed by various components - see https://github.com/CESM-Development/cime/issues/85

**Comment by jedwards4b** [comment]
What maximum length do we want?  What is the list of restrictions for case name?
