### ISSUE TITLE
shr_flux_mod update to use shr_wv_sat_mod

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#854]
This issue is moved from CESM-DEVELOPMENT issue 39.
shr_flux_mod should use the saturation vapor pressure from shr_wv_sat_mod instead of 
having it's own method.  
Any of the common approximation methods will give effectively the same answer at reasonable temperatures/pressures over the ocean, and this is not performance-critical code that needs optimization. Still, it's better practice to call the standard routine than to have a series of duplicated/hard-coded formulas, so this should probably be cleaned up some time.

The one caveat is that there's a factor of 0.98 applied to the humidity, which roughly adjusts for the ocean salinity. That factor needs to be kept, in the subroutines where it is present to begin with.

**Comment by jgfouca** [comment]
Check if done.

**Comment by billsacks** [comment]
Moved to https://github.com/ESCOMP/CESM_share/issues/21
