### ISSUE TITLE
Possible bug in shr_cal_mod

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#858]
Keith Oleson 2013-04-04 14:54:20 MDT
In running a single-point (single gridcell) simulation with clm4_0_69 I found a possible bug in shr-cal_mod.F90 (subroutine shr_cal_advDate).
In this simulation the START_TOD is 72000 seconds.  In the initial call to this subroutine, the following statement is executed:

   ! take secIn into account here since it's real
   dSec = dSec - secIn

Here, dSec on the right side is 0. and secIn is 72000.  So dSec is -72000 and
eventually the datm looks for a time stamp in an atmospheric forcing file that is 72000 seconds before the first time step in the file and the model aborts.

I see that previous versions of this subroutine have:

   dSec = dSec + secIn

When I use this statement, the model runs as expected.  Not sure if this is a robust solution for all situations however.

**Comment by jedwards4b** [comment]
Related issue from CESM_DEVELOPMENT issue 75:

   I found a bug in CESM 1.1.1 with CLM. I used GREGORIAN in drv_in.
   The bug is:

   if we use:
start_tod = 72000
start_ymd = 20120228
stop_option = 'date'
stop_tod = 18000
stop_ymd = 20120301

CLM can move the the stop time.

if we use:
start_tod = 72000
start_ymd = 20120228
stop_option = 'date'
stop_tod = 18000
stop_ymd = 20120229

CLM will get the wrong stop time at (stop_tod = 18000 and  stop_ymd = 20120228).

**Comment by billsacks** [comment]
@olyson I stumbled across this same bug recently. I agree with your suggested fix. I'm implementing this fix, and it should be on cime master soon.
