### ISSUE TITLE
Setting different thread counts for components doesn't work

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#864]
Currently all CESM components will use OMP_NUM_THREADS from the environment and ignore
the setting passed from the coupler.  This is copied from CESM-DEVELOPMENT issue 181

A test should be developed to confirm that it is working.

**Comment by jayeshkrishna** [comment]
@jedwards4b : So is the issue that the driver is not setting+resetting the number of threads (omp_set_num_threads) before invoking the run sequence for the components (After a quick look in the driver code it looks like the calls are missing before/after component_run())? The ACME components seem to store and use the number of threads passed during init (driver already sets the number of threads correctly for each component during init).

**Comment by rljacob** [comment]
The discussion on the old issue (https://github.com/CESM-Development/cime/issues/181) implies we fixed this in our version of cime2.  Apparently it did not get carried over to cime5.

**Comment by jedwards4b** [comment]
Even if the driver is calling omp_set_num_threads before each call to the component run sequence the components are not always calling omp_get_num_threads and instead are using the OMP_NUM_THREADS from the environment which will be the max thread count for any component.

**Comment by jayeshkrishna** [comment]
So is the solution to set+reset the OMP_NUM_THREADS env variable inside the driver?
@amametjanov has found in the past (with cime2?) that turning the threading on works correctly with the ACME cases.

**Comment by jedwards4b** [comment]
No the solution is in the components - they need to accept the setting as passed from the driver.
I think that this should be a system test that can be run regularly and I have opened issue #881 to track its development.

**Comment by jayeshkrishna** [comment]
So is this change in cime or outside cime?

**Comment by jedwards4b** [comment]
I think that the change is in the components outside cime.

**Comment by jayeshkrishna** [comment]
I know there were some changes done by @amametjanov on the ACME side (for ATM). @amametjanov : Any comments?

**Comment by rljacob** [comment]
Yes I think ACME made changes to the driver (part of CIME) that did not make it to CIME5.

**Comment by amametjanov** [comment]
In ACME, threading works like this:
- `drv_threading=true` so that drv calls `omp_set_num_threads(N)` in component initialization
- components call `nthreads=omp_get_max_threads()` in their init routine and store the result locally
- components' main time-stepping loop is surrounded with `!$omp parallel num_threads(nthreads)`

**Comment by rljacob** [comment]
So which components exactly is this not working for?  ACME prognostic components have the necessary changes.   Do CIME data models and X models have it?  (does it even make sense to thread them?).  This might be a CESM-only issue.

**Comment by jedwards4b** [comment]
If you guys have it working for acme than it is a cesm only issue.   I would still like to see a test.

**Comment by rljacob** [comment]
I can confirm that threading from the driver does work with ACME.  I did a 36x1 and 9x4 case on Anvil and they both worked.   We are having trouble with the PET testing but that's a different issue.

**Comment by jedwards4b** [comment]
Can you be more specific about what it is you did?   What processor layout did you expect and how did you confirm that that's what you got.

**Comment by rljacob** [comment]
It was a -compset X -res f19_g16 case.  By default, that runs on one full node with no threads and on anvil thats 36 tasks .  So I compiled and ran that.  I then created another version of that case and hand-edited the env_mach_pes.xml file to be 9 tasks and 4 threads; setup, build, run, and it worked.

**Comment by rljacob** [comment]
I guess that's not a full-model case so I'll try that too.

**Comment by jedwards4b** [comment]
As long as everyone is using either 1 thread or the same number of threads I think things work fine.   But suppose we want atm to have 8 threads per task but lnd to have only 4 threads per task.   That is what is not working, and it's component specific, I don't think you can test this with cime standalone.

**Comment by mvertens** [comment]
This will only work if the separate full component components all do not
depend on their particular decompositions. In our case, pop and cice do. So
a 36x1 and 9x4 will not give the same answers for a B compset in our case.
However, the PET test is careful to keep the decomposition the same but
only increase the number of threads (i.e. 9x4 versus 9x1).

**Comment by rljacob** [comment]
Got it.  It looks like the PET test depends on their being a pe layout already defined that has threads >1.  That's the first run and then second run sets all the threads to 1.  But what happens if there is no pe-layout to be found that has threads?  Or the one it gets has threads=1 to start?

**Comment by rljacob** [comment]
Is there a reason NTHRDS_ESP is set to 0 for all cases?  If you leave it 0 while trying to increase the thread count for other components, you get an error `ERROR: (seq_comm_setnthreads)  ERROR: nthreads less than one.`

**Comment by gold2718** [comment]
@ekluzek , NTHRDS_ESP=0 seems to come from driver_cpl/bld/testdir/env_mach_pes.xml, any ideas?

**Comment by ekluzek** [comment]
That really doesn't make any sense. That test directory isn't used in any sense by anything else. It just allows you to run the driver build-namelist without having to setup a case.

**Comment by rljacob** [comment]
The default for NTHRDS_ESP is in driver_cpl/cime_config/config_components.xml

**Comment by gold2718** [comment]
But those are all zero so that can't be the source of the issue. Is it because ESP is an optional component? @jedwards4b ?

**Comment by jedwards4b** [comment]
I corrected that issue with NTHRDS_ESP some time ago - is this still the cime5.1 branch?

**Comment by rljacob** [comment]
Its still set to zero.  https://github.com/ESMCI/cime/blob/master/driver_cpl/cime_config/config_component.xml#L2204

And it stays zero because none of the entries in config_pes address it.  For the other components, the 0 is always overridden with an explicit nthreads setting in a config_pes entry.

**Comment by rljacob** [comment]
NTHRDS_ESP discussion should be moved to #889

**Comment by rljacob** [comment]
I think this issue should be closed because its CESM specific.  The driver/cime does the right thing in trying to pass thread settings to components.

**Comment by rljacob** [comment]
We confirmed we can still run an F-case with DRV_THREADING in ACME using cime5.1

**Comment by rljacob** [comment]
This is more of a documentation issue on how to use driver threading.  See #1201
