### ISSUE TITLE
build-namelist reads XML variables from files, but doesn't abort if variable not found

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#865]
_From @mnlevy1981 on March 16, 2016 22:57_

Some users copy "known good" versions of XML files from case to case. A recent CIME update added three variables to `env_run.xml` relating to the barrier settings (presumably to go along with the `COMP_RUN_BARRIERS` option). These three new variables are read in by the coupler's `build-namelist` and values in `drv_in` are set accordingly... however, if these variables are not present in the XML file then `build-namelist` assumes they are blank strings and behaves accordingly. It seems like better behavior would be for `build-namelist` to error out with a "variable not found" message - currently, the first indication of a problem is that the run crashes during the namelist read.

More specifics... by default, `env_run.xml` contains

```
  <entry id="BARRIER_DATE"  value="-999">
    <type>char</type> 
    <group>run_begin_stop_restart</group> 
    <desc>Alternative date in yyyymmdd format
      sets periodic model barriers with BARRIER_OPTION and BARRIER_N for synchronization</desc> 
  </entry> 

  <entry id="BARRIER_N"  value="1">
    <type>char</type> 
    <group>run_begin_stop_restart</group> 
    <desc>sets periodic model barriers with BARRIER_OPTION and BARRIER_DATE for synchronization</desc> 
  </entry> 

  <entry id="BARRIER_OPTION"  value="never">
    <type>char</type> 
    <valid_values>none,never,nsteps,nstep,nseconds,nsecond,nminutes,nminute,nhours,nhour,ndays,nday,nmonths,nmonth,nyears,nyear,date,ifdays0,end</valid_values> 
    <group>run_begin_stop_restart</group> 
    <desc>sets frequency of full model barrier (same options as STOP_OPTION) for synchronization with BARRIER_N and BARRIER_DATE</desc> 
  </entry> 
```

which produces the following in `drv_in`:

```
 barrier_n = 1
 barrier_option = 'never'
 barrier_ymd = -999
```

Deleting those lines from `env_run.xml` (or copying in a version that never had them to begin with) results in the following in `drv_in`:

```
 barrier_n =
 barrier_option = ''
 barrier_ymd =
```

I think catching this error in `build-namelist` would be preferable.

_Copied from original issue: CESM-Development/cime#395_

**Comment by jedwards4b** [comment]
_From @ekluzek on March 17, 2016 17:2_

Mike

All that we need to do to catch this is to add

$definition->validate($nl);

before the namelist is written out by the driver. We do this in CLM and
probably other models as well.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by mvertens** [comment]
In recent versions of CIME master this has been resolved. I have verified that if I remove `BARRIER_OPTION` and then issue `preview_namelists` I get an abort with the following error:

`ERROR: Namelist default for variable barrier_option refers to unknown XML variable BARRIER_OPTION.
`
