### ISSUE TITLE
Optionally pass ozone from datm to coupler

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#866]
_From @ekluzek on March 4, 2016 22:54_

We need the optional ability to pass surface ozone from datm to the coupler. This also goes with #389 for the driver. Here's a sample streams file that deals with ozone 

```
  <dataSource>
     GENERIC
  </dataSource>
  <domainInfo>
     <variableNames>
        time    time
        lon     lon
        lat     lat
        area    area
        mask    mask
     </variableNames>
     <filePath>
        /glade/p/work/dll
     </filePath>
     <fileNames>
        hist2002-09o3.nc
     </fileNames>
  </domainInfo>
  <fieldInfo>
     <variableNames>
        O3_SRF  ozone
     </variableNames>
     <filePath>
        /glade/p/work/dll
     </filePath>
     <fileNames>
        hist2002-09o3.nc
     </fileNames>
     <offset>
        0
     </offset>
  </fieldInfo> 
```

_Copied from original issue: CESM-Development/cime#390_

**Comment by jedwards4b** [comment]
_From @ekluzek on March 4, 2016 23:4_

Changes for CLM are documented in bugzilla in 2294.

**Comment by jedwards4b** [comment]
_From @ekluzek on August 31, 2016 16:28_

This was closed accidentally via a pull request on a different issue.

**Comment by rljacob** [comment]
Closing since this is no longer CIME but a coupler/driver specific issue.
