### ISSUE TITLE
Need to pass surface Ozone to land model

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#868]
_From @ekluzek on March 4, 2016 22:46_

For Ozone damage in plants for CLM, we need to allow passing surface concentration of Ozone in driver.

One implementation of that adds this bit of code in seq_flds_mod.F90
! in the future, move this to be with the state variables, not fluxes as here
     ! ozone concentration (mol/mol) 
     call seq_flds_add(a2x_fluxes,"Faxa_ozone")
     call seq_flds_add(x2l_fluxes,"Faxa_ozone")
     longname = 'ozone concentration'
     stdname  = 'ozone_concentration'
     units    = 'mol/mol'
     attname  = 'Faxa_ozone'
     call metadata_set(attname, longname, stdname, units)

It sounds like it should set it as a state -- rather than a flux though. And should it be optional?

_Copied from original issue: CESM-Development/cime#389_

**Comment by rljacob** [comment]
Closing since this is no longer a CIME issue but a coupler/driver issue.
