### ISSUE TITLE
Speed up unit test build & run

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#869]
_From @billsacks on December 21, 2015 23:21_

The unit test build and run can take longer than I'd like. This is particularly true for CLM, which now has 20 unit test executables; each of these is linked against the CLM library, so whenever you change any CLM code, all 20 need to relink. So the build takes some time due to that. In addition, particularly on yellowstone, the use of mpi-based tests means that each test executable takes more than 1 sec to run, leading to a total test time of about 30 sec (these tests should run in milliseconds).

A few ideas about how to speed things up:

(1) Create a single test executable for all of CLM (or perhaps one executable for each CLM subdirectory - e.g., a biogeophys test executable, etc.). However, by itself, this is considered unacceptable, because CTest doesn't give granular enough reporting. So, would it be possible to have a single executable, with CTest calling it multiple times in different ways (as in http://baoilleach.blogspot.com/2013/06/using-ctest-with-multiple-tests-in.html)? Having a single executable would (a) speed up the build, (b) speed up the run, (c) make it easier to move around code and its associated tests.

(2) Revisit issue https://github.com/CESM-Development/cime/issues/26 : allow tests to use a serial build of pFUnit when possible. This would allow you to run CLM unit tests from yellowstone (rather than needing to do so on caldera), and would speed up the run time if (1) isn't feasible.

_Copied from original issue: CESM-Development/cime#341_

**Comment by billsacks** [comment]
cc @quantheory @bandre-ucar

**Comment by rljacob** [comment]
@billsacks still relevant?

**Comment by billsacks** [comment]
Still possibly relevant but never gonna happen.

**Comment by billsacks** [comment]
(In practice, when I'm doing test-driven-development, after I do an initial build and run of the unit tests on a branch, I cd into the unit test build subdirectory for just the tests I'm working on and run something like 'make && make test' from there, so that I only end up rerunning the tests I'm currently working on. This works well for me, though is currently undocumented.)
