### ISSUE TITLE
drof iaf settings

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#871]
_From @apcraig on July 15, 2015 20:41_

the drof iaf settings currently have the following settings in the namelist_defaults_drof.xml file,

`<strm_year_align stream="rof.diatren_iaf_rx1">1</strm_year_align>`
`<strm_year_start stream="rof.diatren_iaf_rx1">1948</strm_year_start>`
`<strm_year_end   stream="rof.diatren_iaf_rx1">2009</strm_year_end>`
`<strm_offset     stream="rof.diatren_iaf_rx1">0</strm_offset>`
`<strm_domdir     stream="rof.diatren_iaf_rx1">$DIN_LOC_ROOT/lnd/dlnd7/RX1</strm_domdir>`
`<strm_domfil     stream="rof.diatren_iaf_rx1">runoff.daitren.iaf.20120419.nc</strm_domfil>`
`<strm_datdir     stream="rof.diatren_iaf_rx1">$DIN_LOC_ROOT/lnd/dlnd7/RX1</strm_datdir>`
`<strm_datfil     stream="rof.diatren_iaf_rx1">runoff.daitren.iaf.20120419.nc</strm_datfil>`

I believe the align value should be set to 1948 and the end value should be set to 2011 to be consistent with the dataset and ensure the model years align with the input data years when they overlap.  Can someone else review this proposal before we make the change.

_Copied from original issue: CESM-Development/cime#52_

**Comment by jedwards4b** [comment]
_From @mvertens on July 15, 2015 21:42_

I agree with the proposed changes.

**Comment by jedwards4b** [comment]
assign to dave bailey

**Comment by jedwards4b** [comment]
@mvertens has this been addressed?

**Comment by jedwards4b** [comment]
_From @mvertens on November 30, 2016 21:21_

no - this has not been addressed and should be as soon as possible

**Comment by jedwards4b** [comment]
_From @mvertens on November 30, 2016 21:28_

This has not been addressed - but I believe that Dave Bailey needs to give
us feedback as to what this needs to be for AIAF versus GIAF and CIAF.

**Comment by mvertens** [comment]
Actually, this is the correct setting.
All of the IAF compsets use model_year_align as 1. Given that they often run 600 years, it doesn't make sense to use the forcing years. They cycle over 1948-2007 several times. So an align year of 1 is the only reasonable setting.
