### ISSUE TITLE
bless_test_results and failing NLCOMP test

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#878]
I am using bless_test_results to create my baselines.  When I then use these baselines in a subsequent create_test runs, the NLCOMP fails due to missing namelist files.  

When I look back at baseline directories which were created using the --generate flag on create_test, the namelist files are in those directories.  When I look at baseline directories which were created using bless_test_results, there are only *nc files in those directories.

**Comment by jgfouca** [comment]
Did you run bless_test_results with --hist-only?

**Comment by cacraigucar** [comment]
Yup, my mistake.  I forgot my script had that flag in it, because I was getting a fatal error without it.  I'll close this issue and open another one with the error message I'm getting when running without that flag.

**Comment by cacraigucar** [comment]
I see that the bug was fixed in #823
