### ISSUE TITLE
bless_test_results - can not find create_test command

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#882]
I am using tag:
 https://github.com/CESM-Development/cime/tags/cime5.2.0-alpha.10

When I issue the command:
 /glade/u/home/cacraig/cam5_4_94/cime/scripts/Tools/bless_test_results  -t '' -c '' -r /glade/scratch/cacraig/aux_cam_20161123172411 -b cam5_4_94-copy6 -f

I get the following error:
FAILED TO BLESS TEST: SMS_Lm13.f09_f09.F2000_DEV.yellowstone_intel.cam-outfrq1m_clm5, reason Namelist regen failed: '/bin/sh: create_test: command not found'

The baseline directory created by this script has the netCDF files in it, but no namelists are copied.  I've tried running this command from various locations including the cime/scripts directory where create_test resides, and can not eliminate this error.

**Comment by jedwards4b** [comment]
It seems like the script should be run from the cime/scripts directory and you need to add a ./ in front of the create_test call at line 21 of bless_test_results.py

**Comment by jgfouca** [comment]
@cacraigucar thanks, the current implementation is very fragile. I will fix.

**Comment by cacraigucar** [comment]
CAM is planning on making this utility an integral part of our testing framework.  Should we reconsider our plans on using this tool (I'm asking because of the comment that it is very fragile).

**Comment by jedwards4b** [comment]
I think that that tool just hasn't had a lot of users yet, now that you are integrating it with your testing we will assure that it works robustly.

**Comment by jgfouca** [comment]
@cacraigucar the tool as a whole is not fragile (at least, it shouldn't be). I found one particular line that was that I will fix.
