### ISSUE TITLE
Divide by zero error in xmlchange

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#883]
A relatively simple set of valid commands results in divide by zero errors from xmlchange.

```
./create_newcase -case <caseroot> -mach yellowstone -res ne30_ne30 -project P93300642 -compset FC5
cd <caseroot>
./xmlchange MAX_TASKS_PER_NODE=15
./xmlchange CALENDAR=NO_LEAP

```
```
Traceback (most recent call last):
  File "./xmlchange", line 148, in <module>
    _main_func(__doc__)
  File "./xmlchange", line 145, in _main_func
    xmlchange(caseroot, listofsettings, xmlid, xmlval, subgroup, append, noecho, force , dry)
  File "./xmlchange", line 97, in xmlchange
    with Case(caseroot, read_only=False) as case:
  File "/glade/u/home/goldy/Projects/camTrunk/cime/scripts/Tools/../../utils/python/CIME/case.py", line 104, in __init__
    self.initialize_derived_attributes()
  File "/glade/u/home/goldy/Projects/camTrunk/cime/scripts/Tools/../../utils/python/CIME/case.py", line 121, in initialize_derived_attributes
    self.cores_per_task = ((self.get_value("MAX_TASKS_PER_NODE")/smt_factor) \
ZeroDivisionError: integer division or modulo by zero

```
Also, other xmlchange commands trigger the same error message, e.g., 
`./xmlchange NTASKS_ATM=15
`
Oddly enough, I can not seem to reproduce this in a CIME-only configuration (A case). Is something one of sync between CIME and CAM?

Both the FC5 case and the A case were from the head of master (3c8ceaa3ddb88f7d653c0acafc9f693323f42452).

**Comment by gold2718** [comment]
Note this bug was first found by Jerry Olson, I just narrowed it down a bit.

**Comment by jedwards4b** [comment]
MAX_TASKS_PER_NODE should never be < PES_PER_NODE, this was causing smt_factor = 0 
I've changed the code to be smt_factor = max(1, MAX_TASKS_PER_NODE/PES_PER_NODE)
PR #885

**Comment by jedwards4b** [comment]
Note that the reason this is only happening in cam is that @fvitt put PES_PER_NODE=16 into cams
config_pes.xml file for F cases.
