### ISSUE TITLE
cs.status/cimeteststatus no longer reporting reporting which components fail baseline comparison tests

### ISSUE THREAD

**Issue by klindsay28** [ESMCI/cime#884]
Before cime5, e.g. cime 4.6.0, cimeteststatus would report which model components were failing a baseline comparison. I found this useful in the usecase where I was changing history output in a single component and would see easily from the cimeteststatus output that only that component failed the baseline comparison.

This feature appears to be no longer present in cime5. Now you only see that there is a net baseline failure, not which components failed. I request that this feature be brought back.

The analogous feature was also dropped for namelist baseline comparisons. I request that it be brought back as well. When I change namelist values in a single component, I'd like to be able to easily see from cs.status output that the only namelists changes were from the component that I changed.

**Comment by billsacks** [comment]
@klindsay28 how strongly do you feel about this? Personally, while I still see value in this, I've learned to live with the current test reporting, and it might take a fair amount of rework to accommodate this feature. Would you be okay closing this as a wontfix, or do you still feel like it should be changed?

**Comment by ekluzek** [comment]
I do see where this would be a useful feature. But, I think I agree with @billsacks that I've gotten used to not having it, so can work in the current environment.

**Comment by klindsay28** [comment]
​My understanding of #2988 is that it makes cprnc more strict in its file comparison. For instance, it sounds like adding history vars will lead to baseline failures. So I’m expecting to see more baseline failures. In my opinion, that makes it more relevant for CIME to provide details on the failures, easing the job of the developer who is parsing those failures.

That said, it just eases the developer's job. As pointed out, one can live without this.

So if the current structure of CIME makes this feature request too challenging/inconvenient to implement, then this issue could be closed. That seems like a judgement call, based on the effort to implement and maintain the feature. Not being familiar with CIME internals, I'll leave that judgement to CIME developers.

**Comment by billsacks** [comment]
Thanks for your thoughts @klindsay28 . I think I'll close this, since I don't think anyone working on cime has the time to make the (possibly large) changes that would be needed for this.
