### ISSUE TITLE
What might cause diffs in an active-land ice case compared to cime2?

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#888]
We have an IG case that is producing different answers from cime2 and not sure why.
2000_DATM%QIA_CLM45%SP_SICE_SOCN_RTM_MPASLI_SWAV

As we look at the 2 CaseDocs directories, one thing that is different is that the CIME5 datm now has a datm.streams.txt.topo.observed file and changes in datm_atm_in to read it.   What exactly does that new feature do?

**Comment by jedwards4b** [comment]
CISM may change the topo file to account for changing land ice topo.

**Comment by rljacob** [comment]
But will the shift from not having a topo stream to having one change answers in a land ice case?  That seems to be what is happening.  Tagging @billsacks .

**Comment by billsacks** [comment]
The new topo stream should only affect the system if ACME-Land explicitly handles it, which I suspect it does not: This topo stream (sent from datm or CAM in CESM) replaces a CLM file which used to specify the atmosphere's topographic: it is needed for CLM to remain consistent with CAM without having a duplicate file (maintenance problem).

Which is to say: I doubt this topo file is affecting the operation of ACME, but ACME _should_ ideally update its active components with this feature at some point.

However, I _would_ expect answer changes from this change:

https://github.com/CESM-Development/cime/pull/447

**Comment by rljacob** [comment]
Oh yeah!  And I think you had mentioned that before.  Is there a way to configure the new vertical gradient calculator to restore the cime2 answers?  Tagging @jonbob .

**Comment by billsacks** [comment]
This wasn't designed to be able to switch back to the old method easily. That said, you _might_ be able to reproduce the old answers by deleting these lines, around line 200 of  driver_cpl/driver/vertical_gradient_calculator_2nd_order.F90:

```
            call this%limit_gradient(elevation_class, ec_low, ec_high, &
                  this%vertical_gradient(:,elevation_class))
```

**Comment by rljacob** [comment]
That didn't work.   We had another active MPAS land-ice case that DID have the same answers but is it because its using the stub land model?
2000_DATM%NYF_SLND_MPASCICE_MPASO_DROF%NYF_MPASLI_SWAV

**Comment by billsacks** [comment]
Yes, I wouldn't expect answer changes for that case with a stub land.

**Comment by jonbob** [comment]
@rljacob : I ran one-day tests and dropped cpl history files every timestep.  Those history files are the same until the end of day 1, when glc runs.  At that point, there are three cpl fields that have diverged:
x2g_Sl_tsrf
x2g_Flgl_qice
g2x_Sg_topo
To me that looks like the first differences are coming from what the cpl sends to mpasli.  So maybe not issues with the new topo field in datm, like @billsacks thought.

**Comment by rljacob** [comment]
If those are coupler fields AFTER it talked to GLC, and GLC is changed because of the vertical remap/topo, then I'd expect any/all coupler fields to diff after that.

**Comment by billsacks** [comment]
x2g fields are the fields sent from lnd -> glc, which is exactly what I expect to differ based on the changes I mentioned. g2x_Sg_topo is the field sent back from glc to lnd, but that will only affect the future evolution of the system if two-way feedbacks are enabled; I'm not sure whether that's the case in your acme configurations.

**Comment by jonbob** [comment]
Yes, we do have two-way feedbacks enabled.  And Bill is exactly right -- the future evolution will (or does) get more different as the tests run, with each GLC invocation.  I guess my point is that the differences start with the fields from the land, so unless we can find a way to back out those changes, we won't be able to make this test bfb with the previous version.  However, I'm not sure that's critical.  This could be one where we just bless new baselines and move forward.

**Comment by rljacob** [comment]
Yes we now understand the source of the diffs, which was the main goal of this issue.
