### ISSUE TITLE
NTHRDS_ESP default of 0 causing problems with DRV_THREADING

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#889]
NTHRDS_ESP is by default 0 and none of the config_pes.xml entries reset it to 1.

When DRV_THREADING is true, and NTHRDS>1 for some other component, this will produce an error:
` ERROR: (seq_comm_setnthreads)  ERROR: nthreads less than one`

**Comment by rljacob** [comment]
Reproducer:

1. Using latest master, create an X-case with -compset X -res f19_g16
2. Change DRV_THREADING to TRUE
3. edit env_mach_pes.xml and change NTHRDS for any component (not ESP) to >1.
4. setup, build,submit

**Comment by gold2718** [comment]
@ekluzek , it seems to come from driver_cpl/bld/testdir/env_mach_pes.xml, any ideas?

**Comment by rljacob** [comment]
The default for NTHRDS_ESP comes from driver_cpl/cime_config/config_components.xml.  Unlike the other defaults, it never gets changed by an entry in a config_pes.xml file.

**Comment by rljacob** [comment]
@jedwards4b is correct and this was fixed in CIME.  I thought my cime-only X case test was using the driver_cpl config_pes.xml but it was still using ACME's (which doesn't set threads for esp).
