### ISSUE TITLE
Reduce verbosity of some case xml files 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#890]
Several variables in the case xml files which may be different for different components are currently set as XXX_ATM=blahm, XXX_LND=blah and so on for each component,   This proposed change will  
make the case xml files much shorter and easier to read.  Instead of a separate variable for each component the new format would be
```
<entry id="XXX">
<values>
  <value component="ATM">blahm</value>
  <value component="LND">blah</value>
...
</values>
</entry>
```

This makes the xml much more manageable and would also allow to do things with xmlquery and xmlchange to get the settings for all components of variable XXX.

**Comment by gold2718** [comment]
I would love this change!
