### ISSUE TITLE
extend clone_case to make copy of user_mods to all files in case directory

### ISSUE THREAD

**Issue by jtruesdal** [ESMCI/cime#892]
Nancy Norton noticed that the clone_case script ignored user changes in the Tools subdirectory.  This is counterintuitive to what we would expect from cloning a case and seems like a bug.  I think Jim Edwards suggested fix below would make the routine more consistent with the definition of a clone being an almost identical copy of the original case.  I also think making the user go through some hoops (breaking links, etc.)  when they modify a critical script in the case directory is a good idea and will help to make the user aware that they are playing with fire. 

Jim Edwards comments and suggestion: 

Many of the files under the case directory are links to the source and are not intended to be modified.   We could add something such that if a user broke that link and changed the file the copy would be cloned - can you open an esmci issue on this please?

**Comment by rljacob** [comment]
Is this still needed?
