### ISSUE TITLE
Output build time per component

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#893]
In CIME2, there was a timestamp output to the screen when each component build started.  Example from an F-case:
```
      Wed Dec  7 14:06:40 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/lnd.bldlog.161207-140501
      Wed Dec  7 14:06:58 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/ice.bldlog.161207-140501
      Wed Dec  7 14:07:18 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/ocn.bldlog.161207-140501
      Wed Dec  7 14:07:20 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/glc.bldlog.161207-140501
      Wed Dec  7 14:07:21 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/wav.bldlog.161207-140501
      Wed Dec  7 14:07:22 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/rof.bldlog.161207-140501
      Wed Dec  7 14:07:28 2016 /lcrc/project/ACME/jacob/acme_scratch/FC5ne30c2gnuthrdblues/bld/cesm.bldlog.161207-140501

```

Those time stamps don't appear when building with cime5.  They are useful for finding which component is responsible for an increase in total build time.

Would like to at least get the build timestamps back in output.  Ideally, the build start and end times would also be logged in CaseStatus for each component.

**Comment by jedwards4b** [comment]
Build start and end times are written to the CaseStatus file.  Since component builds now occur in parallel it may be a little trickier to get individual timing output.

**Comment by rljacob** [comment]
Isn't that the full build start and end time written to CaseStatus (just one each)?

**Comment by jedwards4b** [comment]
correct

**Comment by rljacob** [comment]
I agree the parallelism means the starts and end timestamps could be out-of-order.  In that case, we would need to internally calculate the total build time and output that.
