### ISSUE TITLE
JOB_WALLCLOCK_TIME defaults to walltimemax

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#896]
There is a
```
     <batch_system MACH="mira" type="cobalt">
       <queues>
        <queue walltimemax="06:00:00" jobmin="1" jobmax="786432" default="true">default</queue>
       </queues>
       <walltimes>
        <walltime default="true">03:00:00</walltime>
       </walltimes>
     </batch_system>
```
section in cime/cime_config/$model/machines/config_batch.xml. `case.submit` submits with walltimemax of 6 hours instead of the expected 3 hours.

**Comment by jedwards4b** [comment]
The <walltimes> section is no longer used and should be removed from config_batch.xml
You can also set the walltime using --walltime in create_test or xmlchange JOB_WALLCLOCK_TIME in the case.

**Comment by amametjanov** [comment]
This is for cases created with `create_newcase`.

Related issue is that previously `$case.run` contained the actual runjob/srun/aprun commands and it was easy to customize them. The new `case.run` does not have them.

**Comment by jedwards4b** [comment]
You will find them in config_batch.xml

**Comment by amametjanov** [comment]
I'd prefer keeping the old default walltime as an attribute in `<queue walltime=03:00:00 walltimemax=06:00:00 ...`. Editing local config_batch.xml or `./xmlchange -id JOB_WALLCLOCK_TIME -val "03:00:00"` in a case-dir works too.

**Comment by rljacob** [comment]
From reading the above, I'm not sure what this closed.  What is the resolution?

**Comment by amametjanov** [comment]
It appears that `JOB_WALLCLOCK_TIME` is supposed to default to `walltimemax`.
