### ISSUE TITLE
Need support for TEST specifiers in config_pes.xml

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#897]
Previously, it was possible to define test-specific PE layouts: e.g.
```
<pes MACH="cetus" TEST="^.+$">
<NTASKS_ATM>64</NTASKS_ATM> <NTHRDS_ATM>16</NTHRDS_ATM> <ROOTPE_ATM>0</ROOTPE_ATM>
...
```

The new PE XML appears to support only machine, compset, grid, pesize tags. Is there a specifier for tests?

**Comment by jedwards4b** [comment]
You can use a modifier in the test name such as SMS_P64.f19_f19.FC5  here the P64 says set all NTASKS = 64.

**Comment by amametjanov** [comment]
Test names cannot be changed, they are part of a test suite. The whole test suite needs to run with 64x16 PEs.

**Comment by billsacks** [comment]
It seems risky to have test-specific PE layouts that are applied in a hidden way like this: It means that it's impossible to test the relevant production PE layout, and it is not obvious to someone working with the tests that they're using a different PE layout from what would be used in production.

That said, I don't feel strongly enough about this to stop someone else from doing it, but I'd want to avoid doing so myself - with a preference for the method suggested by Jim Edwards.

**Comment by rljacob** [comment]
Our case is we want to test non-production cases on Mira so that things like compiler bugs and software stack can be tested.  acme_developer is a bunch of simple compsets and small grids and they all need to be run at 64x16.  I guess the way in cime5 would be to pretend each compset/res is production and make a cetus-specific entry in the appropriate config_pes.xml

**Comment by rljacob** [comment]
Another thought:  if you want a single pe-layout for all tests in an run of a test-suite, the right place to say that is on the command line to create_test.  @jgfouca ?

**Comment by jgfouca** [comment]
@rljacob that might be possible. This could potentially implemented in the XML_PHASE of the tests without having to modify the test names as JimE suggested.

**Comment by jedwards4b** [comment]
If you want a separate command line option for this in create_test it should follow the same internal code path that the _P name modifier does now - I think that's possible without too much trouble.
