### ISSUE TITLE
PET tests need support for _PT suffix

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#900]
Previously, PET_PT tests ran with PECOUNT="T" PE layout. This allowed one to set component-specific number of threads: e.g. ATM with 4 threads, but OCN with 1 thread.

The new PE configuration XML does not appear to support the PECOUNT="T" tag. So it's not possible to do BFB-tests for multi- vs. single-threaded runs for specific components. In the example above, do a PET test for ATM, but not OCN runs, for all grid or resolution names that come after PET_PT in `PET_PT.res-name.grid-name`.

**Comment by jedwards4b** [comment]
We chose to drop the _PT suffix, setting threads for a test is done using the PXXxYY format where XX is the number of mpi tasks and YY is the number of threads per task.

**Comment by rljacob** [comment]
Does that then set it uniformly across all components?  What we need is a threading test that will start with a known good layout, where the thread count is possibly different for each component, then set all thread to 1 and compare.

**Comment by jedwards4b** [comment]
That's the PET test.

**Comment by jedwards4b** [comment]
If you had the testlist.xml instead of hardcoding the tests in python this would be easier to customize for each system.

**Comment by amametjanov** [comment]
1. PET.f19_g16.X -- creates a default 64x1 PE layout
2. PET_P128.f19_g16.X --> 128x1 PEs
3. PET_P128x8.f19_g16.X --> 128x8
4. PET_Px8.f19_g16.X --> goes back to the default 64x1 layout, instead of the expected 64x8

Unless there is a syntax to set threads to a number other than 2 (which is covered by the PET test), there is an asymmetry in being able to set custom MPI ranks with default OMP threads, but not the other way around.

**Comment by rljacob** [comment]
That ("PET_Px8" not giving you a 64x8 layout) looks like a bug.

**Comment by rljacob** [comment]
Correction:  PET.f19_g16.X will force a 64x2 run and then use the default 64x1.   

Also "Px8" won't work.  The mpi-tasks must be specified.   We could add support for that if desired

**Comment by rljacob** [comment]
I can still see a case where the old "_PT" suffix might be needed:  The default for a machine/case is not threaded because its not yet trusted.  But there is a partially-threaded layout (some comps have >1 threads, others don't) working and available denoted with "pesize=T".  I want to do a PET test with that layout.

**Comment by jgfouca** [comment]
@amametjanov is this still an issue?

**Comment by amametjanov** [comment]
No. Checked in ACME-master and these modifiers are now working:
- PET_PMx1.ne4_ne4.FC5AV1C-L --> 6x1 PE layout (default is 6x16 for all components)
- PET_PT.ne4_ne4.FC5AV1C-L --> 6x16 for all except ICE and OCN which are at 6x1.

Thank you.
