### ISSUE TITLE
create_clone is not working across different users

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#917]
I am trying to clone a case created by a different user - using as an example the command

`./create_clone --case testclone --clone /glade/scratch/klindsay/temp_caseroots/g.e20.GECO.T62_g16.mvertens_test.001`

create_clone is picking up the username from the clone directory and trying to write into that user's directory (which generates an error)

The output is the following:

 ```
Creating Case directory /glade/p/work/mvertens/cesm2_0_beta04.klindsay_spinup/cime/scripts/testclone
 Successfully created new case testclone from clone case g.e20.GECO.T62_g16.mvertens_test.001 
/glade/p/work/mvertens/cesm2_0_beta04.klindsay_spinup/cime/scripts/testclone/env_mach_specific.xml already exists, delete to replace
Checking file env_case
Creating batch script case.run
Writing case.run script from input template /glade/p/work/mvertens/cesm2_0_beta04.klindsay_spinup/cime/cime_config/cesm/machines/template.case.run
Writing case.st_archive script from input template /glade/p/work/mvertens/cesm2_0_beta04.klindsay_spinup/cime/cime_config/cesm/machines/template.st_archive
Writing case.lt_archive script from input template /glade/p/work/mvertens/cesm2_0_beta04.klindsay_spinup/cime/cime_config/cesm/machines/template.lt_archive
Locking file env_mach_pes.xml
ERROR: Could not make directory '/glade/scratch/klindsay/testclone/bld/cpl/obj', error: [Errno 13] Permission denied: '/glade/scratch/klindsay/testclone'

```

The problem is that CIME_OUTPUT_ROOT is resolved in case.py in the following statements:

```
        # Resolve the CIME_OUTPUT_ROOT variable, other than this
        # we don't want to resolve variables until we need them
        if output_root is None:
            output_root = self.get_value("CIME_OUTPUT_ROOT")
        self.set_value("CIME_OUTPUT_ROOT", output_root)
```

But this causes create_clone to look at a value of CIME_OUTPUT_ROOT that has the wrong user_name and is causing the above error.  

So I believe what happened is that a change was made to case.py and caused problems to create_clone as a side effect. So I would suggest that create_clone tests be carried out any time changes to case.py are made in the future.  This utility is extensively used by cesm scientists in their workflow. Maybe we can add this as a possible item in the testing summary for PRs.

**Comment by jedwards4b** [comment]
I think that you are correct.  We should not resolve $USER for this variable.

**Comment by mvertens** [comment]
What testing should we do to put this in a PR? I'm not sure when this was introduced - but I want to make sure that if we remove it we don't break something else.
