### ISSUE TITLE
Allow passing batch arguments through case.submit command line options

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#922]
Suggested by @erichlf over on ACME.

If one wants to add arguments to the batch submit command, they have to edit env_batch.xml.  For experimenting and trying something once, it would be easier to pass additional commands as an argument to case.submit like this:
case.submit --batchargs '--mail-user=user@server.com --mail-type=END'

**Comment by erichlf** [comment]
The original PR can be seen [here](https://github.com/ACME-Climate/ACME/pull/1180#issuecomment-267092914).

**Comment by jedwards4b** [comment]
This seems like a good idea.
