### ISSUE TITLE
xmlchange with XML variables containing lots of subvariables

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#934]
This is not a high priority at the moment, but at some point next year running a `CECO` compset will result in setting `OCN_TRACER_MODULES_OPT` in `env_build.xml` to `AUTOTROPHS_CNT=3 ZOOPLANKTON_CNT=1 GRAZING_PREY_CNT=1 SILIFICIER_CNT=1` and so on... it would be nice if there was a option in `xmlchange` to, for example, set `ZOOPLANKTON_CNT=2` without changing the rest of the variables.

My first thought was some sort of nested XML schema, so we could just run

```
$ ./xmlchange ZOOPLANKTON_CNT=2
```

This would create a requirement that no variables in `OCN_TRACER_MODULES_OPT` share a name with any `env_*.xml` variables, which would be okay. @mvertens thought another option would be to add the `substring` option and run

```
$ ./xmlchange --substring OCN_TRACER_MODULES_OPT ZOOPLANKTON_CNT=2
```

I'd be happy with that approach if it's easier to implement than the nested schema or more generally applicable to other existing variables.

**Comment by jedwards4b** [comment]
I'm looking at the definition of OCN_TRACER_MODULES_OPT in the current pop tag:
``` <entry id="OCN_TRACER_MODULES_OPT">
    <type>char</type>
    <valid_values></valid_values>
    <default_value></default_value>
    <values>
      <value compset="_POP2%DAR">darwin</value>
      <value compset="1850.*_BGC-BDRDDARWIN">darwin</value>
    </values>
    <group>build_component_pop</group>
    <file>env_build.xml</file>
    <desc>Optional ocean tracers option.  Any one of: darwin quota mono</desc>
  </entry>```

**Comment by jedwards4b** [comment]
I don't see anything about ZOOPLANKTON_CNT for example - so are you proposing a change to the entryid schema?

**Comment by mnlevy1981** [comment]
Yeah, that description is painfully out of date... I think Mariana's branch to convert `buildnml`, `buildlib`, and `configure` to python will also update the description (and remove `darwin` altogether).

We are intentionally not adding `ZOOPLANKTON_CNT` in yet because currently MARBL only knows how to run with 3 autotroph species and 1 zooplankton species but we are currently developing a more general approach to these species. There are other tracer modules that use this option as well (the Impulse Response Function module already exists on the trunk, and I believe a dye module is in development on a branch), though currently we don't have compsets to turn them on by default. Those are probably coming down the line as well.

**Comment by jgfouca** [comment]
@mnlevy1981 could you give me a different example? Something that I'd find in standalone CIME. I grepped for ZOOPLANKTON_CNT and OCN_TRACER_MODULES_OPT and found nothing.

**Comment by mnlevy1981** [comment]
@jgfouca I'm not sure this use-case of XML variables exists in CIME - `OCN_TRACER_MODULES_OPT` is a POP-specific XML variable that has always been used to house additional variables. Does the current XML schema support nested variables? `config_pes.xml` is set up so that

```
$ ./xmlquery NTASKS
        NTASKS: ['CPL:30', 'ATM:30', 'LND:30', 'ICE:30', 'OCN:30', 'ROF:30', 'GLC:30', 'WAV:30', 'ESP:1']
$ ./xmlquery NTASKS_OCN
        NTASKS_OCN: 30
```

If there's a way to set up something similar in `config_components.xml`, it would be great to see

```
$ ./xmlquery OCN_TRACER_MODULES_OPT
        OCN_TRACER_MODULES_OPT: ['AUTOTROPH_CNT:3', 'ZOOPLANKTON_CNT:1', 'ECOSYS_BASE_NT:27', ...]
```

I guess this would result in setting variables with

```
$ ./xmlchange OCN_TRACER_MODULES_OPT_AUTOTROPH_CNT = 4
```

which is unpleasant but at least better than what we have now. Unlike the `NTASKS` example, though,

```
$ ./xmlchange OCN_TRACER_MODULES_OPT=4
```

should return an error rather than set all subvariables to 4. (Also, not all variables are integer-valued.)

**Comment by jedwards4b** [comment]
I think that we could do something analogous to what is done for eg NTASKS and PIO_STRIDE

**Comment by mnlevy1981** [comment]
So I think the best solution is to close this ticket as "not actually a CIME issue" and then sometime this summer I'll talk to @jedwards4b about getting the functionality we want from the existing schema.

**Comment by jgfouca** [comment]
OK, thx
