### ISSUE TITLE
EntryID.get_value crashes if no value is found

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#935]
The line,
if "$" in val:
assumes that val is an iterable. However None does not qualify so the routine crashes.
My suggested fix (coming to a PR soon) is to return None in this case.
Of course, this causes other issues which I will also fix.
The cause of this crash was trying ./create_newcase with an invalid compset.

**Comment by jedwards4b** [comment]
I think that this may already be fixed on the trunk or in #932

**Comment by gold2718** [comment]
Not fixed in master. Partially fixed in refactor_xml_compvars
My suggested fix (in addition to the fix in entry_id.py you already made) is in case.py. In Case.get_resolved_value change
`num_unresolved = item.count("$")`
to 
`num_unresolved = item.count("$") if item else 0`

My test is to just create an A case but before doing so, mess up the compset in driver_cpl/cime_config/config_compsets.xml (e.g., replace SWAV with SWAVx).

**Comment by jgfouca** [comment]
Looks like this made it onto master at some point.
