### ISSUE TITLE
Printenv should be part of case.run

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#940]
Something like `os.system('printenv >& run_env.txt')`; always on by default. This would help in debugging issues with env-vars on compute nodes.

**Comment by jgfouca** [comment]
@amametjanov software_environment.txt should meet this need, right?

**Comment by amametjanov** [comment]
I thought so too, but it appears that software_environment.txt is generated on login nodes. So run-time env-vars like `PBS_O_PATH` are missing in that file.

**Comment by jgfouca** [comment]
Ah, good point. So maybe we need to either delay or overwrite software_environment.txt from the compute nodes.

**Comment by worleyph** [comment]
software_environment.txt is meant primarily to capture the build-time environment. As long as it is not overwritten until it has been copied to the performance archive, this will not bother me personally, but not everyone will be using the performance archive. Having both build and runtime environments captured is probably a better solution.

**Comment by rljacob** [comment]
Yes, lets rename software_environment.txt to build_environment.txt and also output a run_environment.txt.

**Comment by jgfouca** [comment]
OK, I will do that.

**Comment by amametjanov** [comment]
I think `run_environment.YYMMDD-HHMMSS.txt` should also be placed in the run-dir so that there is a record of how the environment changed between two or more runs.

BTW, need some cleanup in the bld-dir:
- remove sym-links from GIT_DESCRIBE, SourceMods.tar.gz, build_environment.txt to the latest time-stamped versions. All three files are time-stamped already.
- remove comp.bldlog.time-stamp files after gzip

**Comment by jedwards4b** [comment]
Putting these environment files into the run dir is really going to clutter it up when doing long production runs - how about putting them into the log subdirectory instead (with the same LID as the model logs have)

**Comment by amametjanov** [comment]
Sounds good. I think the three bld-dir files (GIT_DESCRIBE, SourceMods.tar.gz, build_environment.txt) should be placed into `provenance` subdirectory to also reduce clutter.
