### ISSUE TITLE
File inquiry operators: csh VS tcsh

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#945]
In cime_config/buildlib.mct, last file modification time is obtained with file inquiry operator M (supported by tcsh)
`if ( (-M $MCT_DIR/Makefile ) >= (-M Makefile ) ) then`

On the header of this file, it is indicated to use csh as the shell
`#! /bin/csh -fx`

On most machines, csh is actually tcsh so the command above works.
/usr/bin/csh -> /bin/tcsh
/bin/csh -> /etc/alternatives/csh, /etc/alternatives/csh -> /bin/tcsh

On some machines where csh is not tcsh (e.g. bsd-csh on Ubuntu) we will get an error:
if: Badly formed number.

If CIME wants to support both csh and tcsh, would it be better to test the csh version and suggest users to install tcsh (if csh is not tcsh)?

**Comment by jedwards4b** [comment]
My suggestion is just to change the header to be
#! /bin/tcsh -fx 
to correctly reflect the language requirement of this script.
