### ISSUE TITLE
Build errors on Edison with -compiler gnu

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#950]
Use gnu as the compiler:
./create_newcase -mach edison -compiler gnu -case test_X_Edison -compset X -res f19_g16

When run ./case.build, there are build errors
ERROR: buildlib.gptl failed

The output log shows:
gmake: c: Command not found

If we add \<GMAKE\>make\<\/GMAKE\> to config_machines.xml, the build would still fail:
make: c: Command not found

**Comment by rljacob** [comment]
What is the hash for this?

**Comment by dqwu** [comment]
I reproduced with latest master branch.

**Comment by dqwu** [comment]
Also, the default Python version is 2.6.9, so we will get:
ERROR: Python 2, minor version 7+ is required, you have 2.6

It would be better that we do not have to manually run "module load python"

**Comment by rljacob** [comment]
Since CIME is now python, having the right python version in place at the start has to be the user's job.

**Comment by jgfouca** [comment]
The problem seems to be with the environment for edison. I've contacted the machine point of contact.

**Comment by jedwards4b** [comment]
As far as I understand they won't change the default python version for you - users will just need to know to module load python.

**Comment by jgfouca** [comment]
@jedwards4b my comment was regarding the original problem in the ticket, not the python issue.

**Comment by jedwards4b** [comment]
hmm - i've built on edison recently without issue?

**Comment by jgfouca** [comment]
@jedwards4b did you use gnu compiler?

**Comment by jedwards4b** [comment]
ah - good point, no i haven't done that in a while.   c command not found rings a bell though.

**Comment by jgfouca** [comment]
@dqwu This appears to be fixed now. I think fixes on the ACME side were finally merged over to ESMCI.
