### ISSUE TITLE
pelayout tool 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#953]
A tool to display and update the NTASKS, NTHRDS and ROOTPE fields from xml is desired.
This tool should have customizable io formats and should warn the user if an update is questionable. 
For example if ROOTPE_OCN < NTASKS_ATM in a B compset then a warning should be delivered.

**Comment by rljacob** [comment]
The warning sounds cool but also hard.  Lets get the printing working first.  @gold2718 do you still want to do this?

**Comment by gold2718** [comment]
I'd love to have a go (I've been playing with this for a while and have a script that I use to do this sort of thing). I'll try to put some ideas together this weekend . . .

**Comment by gold2718** [comment]
I made a pull request for the first pass which is viewing only. I would like this reviewed but would like to propose a second pass which has two simple change options:

> --ntasks <#tasks>
> Set the total number of tasks to the new number while keeping the approximate shape of the simulation the same. For sequential layouts (all ROOTPE_<comp> == 0), this means just change all the NTASKS_<comp> to the new value. For more complicated layouts with concurrent components, grow or shrink all component task counts by the same percentage and adjust the ROOTPE_<comp> values to match.
> 

> --nthreads <#threads>
> Set the number of threads in all components to the new number.

Does this sound useful? @rljacob @amametjanov ? Send some feedback.

**Comment by billsacks** [comment]
@gold2718 - I would find that very useful.
