### ISSUE TITLE
Rebuilding a case does unnecessary work even if nothing changed

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#954]
This is a minor issue:

I noticed that, if I rebuild a case with case.build, then cesm_comp_mod.F90, cesm_driver.F90 and the executable get rebuilt, even if I didn't change anything.

I'm guessing this happens because the various files in bld/lib/include are getting re-copied with updated time stamps: datm_comp_mod.mod, atm_comp_mct.mod, etc. For a case that includes CLM, the similar lnd file in the install location (e.g., bld/intel/mpich2/debug/nothreads/MCT/noesmf/include/lnd_comp_mct.mod) is also re-copied with an updated time stamp.

I have reproduced this with:

```
./create_newcase -case testbuild_1222 -compset A -res f45_g37
```

then building it twice, out of the latest cime master.

**Comment by jedwards4b** [comment]
This is a feature - relinking the executable even if nothing has apparently changed is a good idea.  There are things in the environment that can affect what libraries are linked, for example loading a new module or updating LD_LIBRARY_PATH.

**Comment by billsacks** [comment]
Okay, thanks for this clarification. I guess there's still some unnecessary rebuild of cesm_comp_mod and cesm_driver, but that seems to be very fast, so I'm closing this issue.
