### ISSUE TITLE
CIME User's guide outline

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#955]
We previously discussed how many top-level guides to have in #671.   Here's a proposed outline of content in the CIME User's guide.

- Part 1  basic CIME usage 
  create_newcase, case.setup, case.build, case.submit, manage_case
  Explanation of all arguments. 
  examples with and without archiving/resubmitting. 
  How to make changes to the xml files. 
  When/why case.submit or case.build have to be re-run. 
  User options for the data models and coupler.

- Part 2: Advanced CIME usage: 
   create_clone, create_test, 
   manage_testslists, 
   how to add tests, 
   how to edit the config files to add compsets, grids, machines.

**Comment by billsacks** [comment]
This looks like a good high-level outline to me, except:

> manage_testslists,

This is obsolete and should be removed once all test lists have been converted to the new format. Instead, we should describe query_testlists.

**Comment by rljacob** [comment]
There's a lot of stuff in the current CIME User's Guide that I don't think belongs there.  In the process of setting up the above outline, I'm getting rid of the following if there are no objections.

1.2:  cime directory structure and overview of contents:  goes later or in the developers guide.  The first thing we point people to are the tools in cime/scripts.  People curious about the rest can be pointed to the right section.

1.3-1.5:  Tables of specific ACME and CESM compsets, grids, machines.  This will be instantly out-of-date and people are supposed to use cime tools to get this info.  Doesn't go in the documentation. 

5. Porting and validating CIME:  goes in developers guide.

6. Use cases and FAQs:  this all looks out of date.  We should have a standalone FAQ at the same level as this guide.

**Comment by billsacks** [comment]
> Porting and validating CIME: goes in developers guide.

I disagree with this one: Porting is a very important aspect of the CIME user's guide, which many users need to know how to do.

**Comment by jedwards4b** [comment]
I've been updating the porting section in the users guide

**Comment by rljacob** [comment]
I clarified that some content will be moved, not deleted.

It depends what we mean by "user".  I'm thinking this guide is for the typical model user who only wants to know how to use cime to configure/run/test the model.  It assumes cime is ported and working.   I don't mind leaving porting there but that's for "advanced users".

**Comment by mvertens** [comment]
In our case - porting will need to be done by a large number of users of
CESM that do not have access to our supported machines. So this would not
really fit the bill of "advanced" user - but "new" user.

**Comment by rljacob** [comment]
Ok it will still be in Part 1.

**Comment by rljacob** [comment]
I've updated the user's guide with placeholders for the pieces missing from the above outline.  But we have not come to agreement on what exactly Part 1 should be.  I'll close this issue and open a new one.
