### ISSUE TITLE
Can't get map_field to build

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#956]
I'm trying to build the map_field tool (in tools/mapping/map_field), and can't get it to build. I have an old version sitting around which I think I can use for now, so this isn't critical, but just something that should be fixed before the release.

I tried following something similar to the instructions in the INSTALL file, but adapted to what appears to be the current interface of the configure tool, but the build failed.

I ran:

```
cd tools/mapping/map_field/src
export CIME_MODEL=cesm
../../../configure --machine yellowstone --macros-format Makefile
. .env_mach_specific.sh
gmake
```

and got this output:

```
f77 -c   -I/glade/apps/opt/netcdf/4.3.3.1/intel/15.0.3/include -I/glade/apps/opt/netcdf/4.3.3.1/intel/15.0.3/include map_field.F90
f77: map_field.F90: linker input file unused because linking not done
f77 -o ../map_field map_field.o
f77: map_field.o: No such file or directory
Makefile:131: recipe for target '../map_field' failed
gmake: *** [../map_field] Error 1
```

**Comment by jedwards4b** [comment]
Works for me on laramie:
``` 
1052  CIME_MODEL=cesm ../../../configure --machine laramie --macros-format Makefile
 1053  ls -ltr
 1054  make
 1055  ls -ltr
 1056  ls -ltr ../
 1057  history
jedwards@laramie2:~/cesm2_0_alpha/cime/tools/mapping/map_field/src> 
```

**Comment by jedwards4b** [comment]
Works on yellowstone too:

**Comment by jedwards4b** [comment]
```CIME_MODEL=cesm ../../../configure --machine yellowstone --macros-format Makefile
yslogin1: ~/sandboxes/cesm2_0_alpha/cime/tools/mapping/map_field/src
:) source .env_mach_specific.sh
yslogin1: ~/sandboxes/cesm2_0_alpha/cime/tools/mapping/map_field/src
:) make
mpif90  -c   -DFORTRANUNDERSCORE -DNO_R16  -DINTEL_MKL -DHAVE_SSE2  -qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source     -xHost   -O2 -debug minimal   -I/glade/apps/opt/netcdf-mpi/4.3.3.1/intel/15.0.3/include -I/glade/apps/opt/netcdf-mpi/4.3.3.1/intel/15.0.3/include map_field.F90
map_field.F90(524): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [RCODE]
SUBROUTINE sys_getenv(name, val, rcode)
---------------------------------^
map_field.F90(524): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [VAL]
SUBROUTINE sys_getenv(name, val, rcode)
----------------------------^
mpif90  -o ../map_field map_field.o   -mkl=cluster   -Wl,-rpath /glade/apps/opt/papi/5.3.0/intel/12.1.5/lib64  -L/glade/apps/opt/papi/5.3.0/intel/12.1.5/lib64  -lpapi 
```

**Comment by jedwards4b** [comment]
I've updated the build instructions in the README file:
> cd src
> setenv CIMEROOT ~/cime
> setenv CIME_MODEL cesm
> $CIMEROOT/tools/configure --machine yellowstone --macros-format Makefile
> source .env_mach_specific.csh
> gmake
> cd ../

**Comment by billsacks** [comment]
Thanks for looking into this. After an hour of trial and error, I have determined that my problem was that I have an item in my path that contains an old .env_mach_specific.sh file (/glade/p/cesmdata/cseg/tools/cime/tools/cprnc is in my path).

This works for me if I use:

```
source ./.env_mach_specific.sh
```

rather than

```
source .env_mach_specific.sh
```

Can you please update the README accordingly? (I'd do it myself but it looks like your latest changes aren't on master yet, and I don't want to cause a merge conflict.)

**Comment by billsacks** [comment]
There still seems to be a problem here: Now I can get it to build, but not run: If I run:

```
$ ./map_field -m "/glade/p/work/sacks/cime/tools/mapping/gen_mapping_files/gen_ESMF_mapping_file/map_gland4kmOld_TO_gland4kmNew_aave.161223.nc" -if landcover_old.nc -iv landcover -of landcover_new.nc -ov landcover
```

I get:

```
(shr_sys_getenv) ERROR: no implementation of getenv for this architecture
```

It looks like the problem is that -DLINUX isn't set in Macros.make, but seems to be needed by this code:

```Fortran
#if (defined IRIX64 || defined CRAY || defined UNICOSMP)

   call pxfgetenv(name, lenname, val, lenval, rcode)

#elif (defined AIX || defined OSF1 || defined SUNOS || defined LINUX || defined NEC_SX)
#ifdef F2003
    call GET_ENVIRONMENT_VARIABLE(trim(name),value=val, length=lenval, status=rcode)
#else
   call getenv(trim(name),tmpval)
   val=trim(tmpval)
   rcode = 0
   if (len_trim(val) ==  0         ) rcode = 1
   if (len_trim(val) >  CL) rcode = 2
#endif
#else

   write(*,F00) 'ERROR: no implementation of getenv for this architecture'
   stop subname//'no implementation of getenv for this machine'

#endif
```

**Comment by mfdeakin-sandia** [comment]
I've added -DLINUX to Macros.cmake for Yellowstone in mfdeakin-sandia/map_field_build; are there any other machines it's needed for? Also, does this need to be done for any of ACME's machines?
I will note that -DLINUX is added for all of the models, since from what I can tell, map_field is built by hand.

**Comment by jedwards4b** [comment]
For builds using make this flag is generated in the Makefile and so it is not output to Macros.make
and thus it doesn't appear in Macros.cmake either.   But we can change that, removing it from the Makefile and adding it to the Macros files so that it can be used by both make and cmake.

**Comment by mfdeakin-sandia** [comment]
I actually meant Macros.make. If this flag might negatively affect compilation, I can see about changing this to only occur in the Makefile (though I haven't looked into how that's generated...)

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
Currently this is in the Makefile 
```
CPPDEFS := $(USER_CPPDEFS) -D$(OS) -DCPR$(shell echo $(COMPILER) | tr a-z A-z)
```
I'm suggesting that this be moved from the Makefile to config_compilers.xml so that it shows up in both Macros.make and Macros.cmake.

**Comment by mfdeakin-sandia** [comment]
I was hoping that I could just add (at least until the syntax is changed) -D<var>OS</var> to CPPDEFS in the global compilers block, but that doesn't appear to be the case. Am I correct in understanding that I need to explicitly add -DLINUX to CPPDEFS for each individual machine that needs it?
