### ISSUE TITLE
Use buildlib.pio to invoke the PIO build system instead of machines/Makefile

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#979]
The makefile system is somewhat fragile to changes and does not isolate configuration options between components. Using the python to invoke PIO's build system directly instead of using the makefile will reduce issues caused by changes, as well as being more readable, less subject to the users environment, and likely faster due to less redundant work.

**Comment by jedwards4b** [comment]
The reason that these went through the Makefile is so that the same FFLAGS, CFLAGS, etc are uses in the cmake (or configure) step as will be used in the build - this is important for consistancy.   The new python code in  CIME/BuildTools/configure.py will now give you these settings outside of the Makefile.

**Comment by mfdeakin-sandia** [comment]
From what I can tell, PIO doesn't care about changes to the environment variables after the configure step; which given it uses CMake, is to be expected. Is that incorrect (Why would PIO intentionally break this feature?), and do I need to use the methods in configure.py because of this?
I'm admittedly less knowledgeable about other build systems, so this not being true for components that use them wouldn't be unexpected.

**Comment by jedwards4b** [comment]
It is important that the cmake step in pio as well as the configure step in mct use the same flags for their setup as are used in the model makefile.  These flags are available through the configure.py interface.   I didn't say anything about environment variables and so I don't understand your question.

**Comment by mfdeakin-sandia** [comment]
Ah. I was confused since you said the flags must be the same in the configure step as will be used in the build.

**Comment by mfdeakin-sandia** [comment]
The variables in macros.cmake do not correspond to the ones the PIO build system is expecting. I'd be surprised if any of the build systems were expecting them, as they're all prefixed with CIME. Is this intentional, or is there a way to avoid this?

**Comment by rljacob** [comment]
Closing.  See #2068
